### ISSUE TITLE
Add error hint for `setindex(::Type, ...)

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLang/julia#53241]
The typical pattern that this would help is something like
```
d = Dict
d[1] = 2
```
which gives the only somewhat helpful error message `ERROR: MethodError: no method matching setindex!(::Type{Dict}, ::Int64, ::Int64)`. Since Types are never indexable, it seems like it would be reasonable to give an error hint that links to some docs on the difference between a type and a type constructor.
See https://discourse.julialang.org/t/use-dict-to-store-tree-with-uninitialized-tree-nodes/109895 for an example of a user running into this.

**Comment by AbhinavMir** [comment]
Would something like this work? - `ERROR: Cannot assign value to 'Dict' type directly. Use 'Dict()' to create an instance before assignment.`

**Comment by oscardssmith** [comment]
looks great (although obviously this shouldn't be specifically for Dict but whatever the type name happens to be)

**Comment by AbhinavMir** [comment]
Thanks! How far should it go? `ERROR: Cannot assign value to '<TypeName>' directly. Initialize with '<TypeName>()' before assignment.` seems generic enough. Also: Where in the source code is this error actually being triggered? I assume It's multiple methods forming the final string, but where would I usually start at? 

Thanks!

**Comment by vtjnash** [comment]
It could likely be added as an additional MethodError hint with `register_error_hint` (or it could be a method definition like `setindex!(T::Type, val, inds...) = error("Cannot assign a value to $T directly. Use $T() ...")` instead, but the former seems probably preferable?)
