### ISSUE TITLE
Shortcut to test a local package

### ISSUE THREAD

**Issue by gitboy16** [JuliaLang/julia#53258]
Hi,
I think it would be nice to have something like:
```julia
julia --test-package=folder
```
To test a local package (a bit like cargo test in the rust world). Is it something that you would consider?
Thank you

Related discussion:
https://discourse.julialang.org/t/test-a-local-package/109974

**Comment by KristofferC** [comment]
I would say a possible plan is when https://github.com/JuliaLang/Pkg.jl/pull/3772 is landed, to make an app for Pkg itself and then this would be something just like `pkg test`

**Comment by gitboy16** [comment]
Thank you @KristofferC . I hope we will be able to specify the path of the local package/library.

**Comment by stevengj** [comment]
Note that you can just do `julia folder/test/runtests.jl`

**Comment by IanButterworth** [comment]
That doesn't set up the test environment

**Comment by gitboy16** [comment]
In the meantime I just added the functionality to my "personal" juliaup version and I can make it work with different version of Julia. If you are interested let me know. I can post the code.

**Comment by gitboy16** [comment]
@KristofferC would you be open to the proposal in my very first comment if I do the PR? Thank you

**Comment by gitboy16** [comment]
Hi, I was wondering if you have any feedback please? Is ok to do a PR? Or are you against it? I really think it would be great to have an option for that. Thank you.

**Comment by fredrikekre** [comment]
There will be a Pkg CLI app based on https://github.com/JuliaLang/Pkg.jl/pull/3772. Until then you can for example use https://github.com/fredrikekre/jlpkg
