### ISSUE TITLE
Crash with @async Webviews.run (core dumped)

### ISSUE THREAD

**Issue by ritulahkar** [JuliaLang/julia#53279]
Julia crashes on calling \@async with Webviews.run as follows:

`

        ritu@ritu-B450M-DS3H-V2:~$ julia
                       _
           _       _ _(_)_     |  Documentation: https://docs.julialang.org
          (_)     | (_) (_)    |
           _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
          | | | | | | |/ _` |  |
          | | |_| | | | (_| |  |  Version 1.10.0 (2023-12-25)
         _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
        |__/                   |
        
        julia> using Webviews
        
        julia> webview1 = Webview()
        Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
        Webview (0 bindings): pending
        
        julia> navigate!(webview1, "https://julialang.org/")
        Webview (0 bindings): pending
        
        julia> y=@async run(webview1)
        Task (runnable) @0x00007f5a4c355460
        
        julia> 
        [12460] signal (6.-6): Aborted
        in expression starting at none:0
        KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
        Failed to create GBM buffer of size 1024x768: Permission denied
        KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
        Failed to create GBM buffer of size 1024x768: Permission denied
        KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
        Failed to create GBM buffer of size 1024x768: Permission denied
        Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
        pthread_kill at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
        raise at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
        abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
        _Z20WTFCrashWithInfoImpliPKcS0_immmm at /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18 (unknown line)
        _ZN3JSC18sanitizeStackForVMERNS_2VME at /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18 (unknown line)
        unknown function (ip: 0x7f59ffe32659)
        unknown function (ip: 0x7f59ffe8f7be)
        unknown function (ip: 0x7f59ffe90aa0)
        JSContextGroupCreate at /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18 (unknown line)
        unknown function (ip: 0x7f59fee1f925)
        unknown function (ip: 0x7f59fedec59f)
        unknown function (ip: 0x7f59fedefeeb)
        unknown function (ip: 0x7f5a07fc51de)
        g_object_new_with_properties at /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (unknown line)
        g_object_new at /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (unknown line)
        unknown function (ip: 0x7f59f7c5eb82)
        unknown function (ip: 0x7f59f7c5ebf7)
        unknown function (ip: 0x7f59f7cb7773)
        unknown function (ip: 0x7f59f7cac887)
        unknown function (ip: 0x7f59f7bb8aac)
        unknown function (ip: 0x7f59f7bc8b06)
        unknown function (ip: 0x7f59f7b32aca)
        unknown function (ip: 0x7f59f7ad0d14)
        unknown function (ip: 0x7f59f7ad0ed4)
        unknown function (ip: 0x7f59f7ad2cb1)
        unknown function (ip: 0x7f5a002ba25c)
        unknown function (ip: 0x7f5a0031835c)
        unknown function (ip: 0x7f5a00318ca2)
        g_main_context_dispatch at /lib/x86_64-linux-gnu/libglib-2.0.so.0 (unknown line)
        unknown function (ip: 0x7f5a07f11257)
        g_main_loop_run at /lib/x86_64-linux-gnu/libglib-2.0.so.0 (unknown line)
        gtk_main at /lib/x86_64-linux-gnu/libgtk-3.so.0 (unknown line)
        run at /home/ritu/.julia/packages/Webviews/SLFXk/src/platforms/linux/Impl.jl:115 [inlined]
        run at /home/ritu/.julia/packages/Webviews/SLFXk/src/API.jl:90
        unknown function (ip: 0x7f5a5390e995)
        _jl_invoke at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
        ijl_apply_generic at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:3076
        #3 at ./REPL[4]:1
        unknown function (ip: 0x7f5a5390e1e2)
        _jl_invoke at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
        ijl_apply_generic at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:3076
        jl_apply at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/julia.h:1982 [inlined]
        start_task at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/task.c:1238
        Allocations: 1875933 (Pool: 1874111; Big: 1822); GC: 3
        Aborted (core dumped)

`

Versioninfo :

`

        julia> versioninfo()
        Julia Version 1.10.0
        Commit 3120989f39b (2023-12-25 18:01 UTC)
        Build Info:
          Official https://julialang.org/ release
        Platform Info:
          OS: Linux (x86_64-linux-gnu)
          CPU: 12 × AMD Ryzen 5 5500
          WORD_SIZE: 64
          LIBM: libopenlibm
          LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
          Threads: 1 on 12 virtual cores

`

Julia is intalled on my Linux mint 21.3 using juliaup script.

**Comment by vchuravy** [comment]
The crash is not within Julia so I would recommend opening an issue with Webviews.jl.

If it turns out to be an issue with Julia core I am happy to reopen this.
