### ISSUE TITLE
Assigning a View to a field in a struct typed as an Array unexpectedly copies values

### ISSUE THREAD

**Issue by rafaelbailo** [JuliaLang/julia#53271]
If seems that attempting to assign a View to a field in a struct that's typed as an Array does not error, but rather silently copies the values from the View to the Array:
```julia
mutable struct Foo{T}
  u::T
end

u = rand(10)
v = rand(2, 10)
w = view(v, 1, :)

foo = Foo(u)
foo.u = w # I would have expected this to throw a Type Error

@show foo.u == u # false
@show foo.u == w # true
@show foo.u === w # false
typeof(foo.u) # Vector{Float64}
```

I would have expected a Type Error; just copying the values could create confusion. Is this expected behaviour?

Here's `versioninfo()`:
```julia
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
  Threads: 11 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by jishnub** [comment]
I think this is expected. Having the type declaration on a variable leads to an implicit conversion on assignment. The conversion in the OP in assigning to a field of a  `mutable struct` is documented at https://docs.julialang.org/en/v1/manual/performance-tips/#Type-declarations, although perhaps the documentation may be improved to explicitly point this out.
