### ISSUE TITLE
Make Type-Stable Circular Foo{Foo{Foo{...

### ISSUE THREAD

**Issue by uniment** [JuliaLang/julia#53292]
Consider that this self-referencing object is type-stable:

```julia
mutable struct Bar
    x::Int
    b::Bar
    Bar(x) = let b=new(x);  b.b=b  end
end
b = Bar(1)
```

This one, however, is not:
```julia
mutable struct Foo{X,F}
    x::X
    f::F
    Foo(x::X) where X = let f=new{X,Foo}(x);  f.f=f  end
end
f = Foo(1)
```

Because `Foo` is type-parameterized, it's impossible to make it type-stable when it references itself. Maybe this is only because we can't represent circular type parameters... is this the case?

Imagine maybe if this notation would construct a circularly-referencing type `Foo{Int, Foo{Int, Foo{Int, ... }}}`:

```julia
(*) : Foo{Int, *}
```

(maybe this would represent a call to `CircularType(Foo{Int, CircularBaseReference()})` or something)

Then we could write:
```julia
mutable struct Foo{X,F}
    x::X
    f::F
    Foo(x::X) where X = let f=new{X,(*):Foo{X, *}}(x);  f.f=f  end
end
```

If we had such a way to represent circular type references, would it be possible to make `Foo(1)` type-stable?

**Comment by vtjnash** [comment]
> If we had such a way to represent circular type references

There is. It is written thusly:

```julia
mutable struct Foo{X}
    x::X
    f::Foo{X}
    Foo(x::X) where {X} = (f = new{X}(x);  f.f = f; f )
end

julia> Foo(1)
Foo{Int64}(1, Foo{Int64}(#= circular reference @-1 =#))
```

It may not be the mostly immediately intuitive pattern, but it does come up occasionally. The [Discourse forum](http://discourse.julialang.org) may a better place for getting help on usage questions. It is easier to answer questions over there, where there are better controls for message formatting and threading.

**Comment by uniment** [comment]
Oops, I oversimplified my MWE so that it is trivially solvable. I will try again.

**Comment by uniment** [comment]
I can salvage this MWE by introducing a minor constraint.

Suppose the edit @vtjnash proposes is not possible because for some instances `foo` of `Foo`, `foo.f` will be of a type other than `Foo`, yet still for some other instances `foo` of `Foo`, `foo.f` must be self-referential.

If we had such a way to represent circular type references, would it be possible to make the self-referential `Foo`s type-stable?

**Comment by vtjnash** [comment]
In some cases, my edit is salvageable too. Here's a version where sometimes it is self-referential and sometimes wraps a different type of Foo:
```
mutable struct Foo{X, Y}
    x::X
    f::Foo{Y}
    Foo(x::X) where {X} = (f = new{X, X}(x);  f.f = f; f )
    Foo{X, Y}(x::X) where {X, Y} = new{X, Y}(x)
end
```
Or a version where it is either self-referential or holds an object of kind Y:
```
mutable struct Foo{X, Y}
    x::X
    f::Union{Y, Foo{X}}
    Foo(x::X) where {X} = (f = new{X, Union{}}(x);  f.f = f; f)
    Foo(x::X, y::Y) where {X, Y} = new{X, Y}(x, y)
end
```

**Comment by uniment** [comment]
@vtjnash Ah, the second one addresses my use case. Thanks 🙏

Interestingly, `@code_warntype Foo(1).x` seems to think both of them are type-unstable, but afaict it's stable.
