### ISSUE TITLE
Split long files in julia repo

### ISSUE THREAD

**Issue by inkydragon** [JuliaLang/julia#53290]
## Top 10 long file in ...
Raw CSV data: https://gist.github.com/inkydragon/89e6ad4ca969f60afd39885d39e199eb

### `base/`
<img width="414" alt="image" src="https://github.com/JuliaLang/julia/assets/5158738/d1234b73-c5bd-45e8-953d-21e8a951f6c8">

| filename                                             | language | code  | comment | blank | total |
|------------------------------------------------------|----------|-------|---------|-------|-------|
| base/loading.jl                                      | Julia    | 3,015 | 284     | 333   | 3,632 |
| base/compiler/abstractinterpretation.jl              | Julia    | 2,858 | 381     | 158   | 3,397 |
| base/compiler/tfuncs.jl                              | Julia    | 2,810 | 265     | 193   | 3,268 |
| base/show.jl                                         | Julia    | 2,783 | 217     | 320   | 3,320 |
| base/abstractarray.jl                                | Julia    | 2,696 | 249     | 618   | 3,563 |
| base/docs/basedocs.jl                                | Julia    | 2,630 | 96      | 828   | 3,554 |
| base/array.jl                                        | Julia    | 2,444 | 164     | 486   | 3,094 |
| base/reflection.jl                                   | Julia    | 2,233 | 121     | 441   | 2,795 |
| base/compiler/ssair/passes.jl                        | Julia    | 2,125 | 259     | 180   | 2,564 |
| base/sort.jl                                         | Julia    | 1,864 | 189     | 419   | 2,472 |

### `src/`
<img width="414" alt="image" src="https://github.com/JuliaLang/julia/assets/5158738/9c69bc2a-738d-409d-8493-4225d02ee87c">

| filename                      | language | code  | comment | blank | total  |
|-------------------------------|----------|-------|---------|-------|--------|
| src/codegen.cpp               | C++      | 8,860 | 697     | 567   | 10,124 |
| src/subtype.c                 | C        | 4,487 | 414     | 232   | 5,133  |
| src/gc.c                      | C        | 3,718 | 583     | 302   | 4,603  |
| src/cgutils.cpp               | C++      | 3,692 | 355     | 216   | 4,263  |
| src/gf.c                      | C        | 3,294 | 529     | 211   | 4,034  |
| src/jltypes.c                 | C        | 3,141 | 246     | 233   | 3,620  |
| src/staticdata.c              | C        | 3,134 | 406     | 237   | 3,777  |
| src/builtins.c                | C        | 2,269 | 132     | 147   | 2,548  |
| src/flisp/flisp.c             | C        | 2,223 | 97      | 171   | 2,491  |
| src/llvm-late-gc-lowering.cpp | C++      | 2,176 | 550     | 122   | 2,848  |

### `test/`
<img width="413" alt="image" src="https://github.com/JuliaLang/julia/assets/5158738/b36b5ace-a504-410d-80a5-58c90db75bfa">

| filename                                       | language | code  | comment | blank | total |
|------------------------------------------------|----------|-------|---------|-------|-------|
| test/core.jl                                   | Julia    | 6,569 | 695     | 866   | 8,130 |
| test/compiler/inference.jl                     | Julia    | 4,612 | 463     | 561   | 5,636 |
| test/numbers.jl                                | Julia    | 2,824 | 91      | 258   | 3,173 |
| test/syntax.jl                                 | Julia    | 2,768 | 338     | 534   | 3,640 |
| test/arrayops.jl                               | Julia    | 2,692 | 143     | 369   | 3,204 |
| test/ranges.jl                                 | Julia    | 2,211 | 94      | 287   | 2,592 |
| test/compiler/EscapeAnalysis/EscapeAnalysis.jl | Julia    | 2,138 | 96      | 77    | 2,311 |
| test/show.jl                                   | Julia    | 2,073 | 293     | 318   | 2,684 |
| test/subtype.jl                                | Julia    | 1,911 | 247     | 416   | 2,574 |
| test/compiler/inline.jl                        | Julia    | 1,788 | 178     | 196   | 2,162 |

**Comment by vtjnash** [comment]
None of those seem particularly egregious to me, as long as they contain all mostly related content. Those are not generally even the slow  tests, and the files seem to me to have fairly consistent content. While we do split some files (such as codegen.cpp to multiple places such as ccall.cpp, cgutils.cpp, and intrinsics.cpp), I don't think we should commonly be adding `#include <file.c>`-style

**Comment by fingolfin** [comment]
What this issue is missing is an explanation of *why* these "long" files should be split. If there is content in one file that "obviously" is not strongly connected and thus there is a natural logical way to split the file, sure, why not.

But if the argument is just "the file is too long", I don't follow. What is "too long" about it, what problem does this cause? After this has been explained, we can debate it :-)
