### ISSUE TITLE
Possible bug in 1.9 heuristics branch

### ISSUE THREAD

**Issue by d-netto** [JuliaLang/julia#53325]
[This](https://github.com/JuliaLang/julia/blob/8e5136fa2979885081cd502d2210633dff1d2a1a/src/gc.c#L3611) should probably be `not_freed_enough`, since that's the case we want to let the interval increase.

CC: @gbaraldi

**Comment by kpamnany** [comment]
Should I open the PR to `release-1.9`? There's no `backports-release-1.9`. Cc: @KristofferC

**Comment by KristofferC** [comment]
You can but it's unclear if there will be new 1.9 releases.

**Comment by d-netto** [comment]
We fixed in our fork.

Closing it since there won't be 1.9 releases (probably) where this code is used.
