### ISSUE TITLE
A_mul_B and all that jazz

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#5332]
The purpose of this issue is to discuss the future of the dozens of functions in Julia that are slight variations of matrix multiplication, matrix division and backslash. I presume that the point was to have fine-grained control over the use of matrix variables and temporaries when needed. However, I don't understand why the availability of these functions is so inconsistent: is this intentional design or a consequence of organic growth with methods being implemented as needed?
## List of all the functions (existing and plausibly existing in the future)

Here are the 3x3x3x2=54 possible functions that can be constructed out of A, its transpose At and its Hermitian conjugate Ac; and similarly for B, Bt and Bc; mul, rdiv and ldiv; and mutating and non-mutating variants. (`###` means that this function does not exist.)

``` julia
A_mul_B #deprecated synonym of A*B
A_mul_B!
A_mul_Bt
A_mul_Bt!
A_mul_Bc
A_mul_Bc!

At_mul_B
At_mul_B!
At_mul_Bt
At_mul_Bt!
At_mul_Bc   ###
At_mul_Bc!  ###

Ac_mul_B
Ac_mul_B!
Ac_mul_Bt #deprecated
Ac_mul_Bt!  ###
Ac_mul_Bc
Ac_mul_Bc!


A_ldiv_B    ### synonym of A\B
A_ldiv_B!
A_ldiv_Bt
A_ldiv_Bt!  ###
A_ldiv_Bc
A_ldiv_Bc!  ###

At_ldiv_B
At_ldiv_B!  ###
At_ldiv_Bt
At_ldiv_Bt! ###
At_ldiv_Bc  ###
At_ldiv_Bc! ###

Ac_ldiv_B
Ac_ldiv_B!  ###
Ac_ldiv_Bt  ###
Ac_ldiv_Bt! ###
Ac_ldiv_Bc
Ac_ldiv_Bc! ###


A_rdiv_B    ### synonym of A/B
A_rdiv_B!   ###
A_rdiv_Bt
A_rdiv_Bt!  ###
A_rdiv_Bc
A_rdiv_Bc!  ###

At_rdiv_B
At_rdiv_B!  ###
At_rdiv_Bt
At_rdiv_Bt! ###
At_rdiv_Bc  ###
At_rdiv_Bc! ###

Ac_rdiv_B
Ac_rdiv_B!  ###
Ac_rdiv_Bt  ###
Ac_rdiv_Bt! ###
Ac_rdiv_Bc
Ac_rdiv_Bc! ###
```

I'm rocking this boat because it's come up as a natural consequence of systematically making methods available for special matrix types.
## Specific issues
1. **Documentation.** The existence, motivation and use of these functions is sparsely documented. Not all the functions even have defined help strings.

2 **Growth and proliferation.** Do we foresee an eventual future where all 54-3=51 functions (omitting the synonyms for `*`, `/` and `\`) become defined and have methods implemented? There would a great many methods that would have to be implemented to cover all the possible types of matrices that currently exist.
- Can we eliminate any of these functions on the basis of being useless? There are no functions defined that mix `Ac`
  and `Bt`, for example; however, this is a somewhat rare but entirely plausible combination to operate on. Do we care?
- How many of these functions can be implemented with just a fallback method?
- Having more things in `Base` without reason is not ideal, but conversely these functions form a coherent grouping for which it doesn't make sense to have some but not others.
- How many of these functions can be defined trivially in terms of lazy array views (#5003) and rewriting rules (#122)?

cc: @JeffBezanson @StefanKarpinski @andreasnoackjensen @dmbates @lindahua

**Comment by JeffBezanson** [comment]
Getting rid of these is one of my top wishlist items. We can even have `mul!`, `ldiv!`, and `rdiv!`, just no underscores :) Let's move ahead with this.

**Comment by johnmyleswhite** [comment]
I just telling someone today how these methods are one of the main weak points of Julia's otherwise amazing design for linear algebra.

**Comment by tkelman** [comment]
#6837 is step one, right?

**Comment by JeffBezanson** [comment]
@andreasnoack Any update here?

**Comment by andreasnoack** [comment]
Not yet. I'll give an update on this after the weekend.

**Comment by andreasnoack** [comment]
I've pushed a version that eliminates all the `Ax_mul_Bx` functions to https://github.com/JuliaLang/julia/pull/6837. I'm using a `Transpose` type with a `conjugated` field. I think it works fairly well. It is also possible to avoid quite a few explicit transposes. 

However, this hurts compilation time significantly. With the new version, the `triangular.jl` tests take more than 15 minutes on my machine. The total number of allocations is 3x the version on master and total ammount of memory allocation is more than 2x. Running the tests a second time is still as fast as master so this is about compilation.

**Comment by kmsquire** [comment]
Anything you could add to `base/precompile.jl` that might help?

**Comment by andreasnoack** [comment]
My impression is that precompilation is actaully slower that "normal" compilation so I'd expect that the total compile would be longer although the time in the tests might be shorter.

**Comment by tkelman** [comment]
xref #6837 for upcoming work here

**Comment by StefanKarpinski** [comment]
Status of #6837, @andreasnoack? If we can just merge that, this can make it into 0.5, otherwise 0.6.

**Comment by vtjnash** [comment]
I think it might be better to defer this to v0.6. After a recent discussion I had with carnaval about refactoring (aka simplifying) our array representation, I'm now convinced we should work on that ASAP and then figure out what that enables once ArrayView types are basically free of runtime costs.

**Comment by vtjnash** [comment]
revisit this after https://github.com/JuliaLang/julia/issues/4774 is closed

**Comment by ViralBShah** [comment]
It would certainly also be helpful to understand the needs of the ML folks before taking a final call on many of the open linalg issues. That would put these improvements squarely past 1.0, and that may be ok.

cc @MikeInnes

**Comment by MikeInnes** [comment]
I will link the [CUBLAS wrappers](https://github.com/JuliaGPU/CuArrays.jl/blob/12269b828626bf519e442076caf36b5b9582d775/src/blas/highlevel.jl). You can see that there's a fair bit of redundancy with Base; given that CUBLAS has an identical api to blas, ideally we'd just swap out the final `gemm!` calls without ever touching the higher-level API.

That said it does work fine at present, and I expect that things will be improved with whatever changes are made – reducing the redundancy would just be icing.

I think it's actually a bigger deal for AD, where we have to code a derivative for every `Ax_mul_Bx` combination. Having a single `mul!` would be a huge improvement there.

**Comment by StefanKarpinski** [comment]
Is there some way we can isolate Base from this change? The special lowering to these function names is an issue, but it would be possible to provide the fallbacks and then override them in the future, which would leave the unfortunate lowering hack but would allow this to be fixed in the future.

**Comment by StefanKarpinski** [comment]
Related: https://github.com/JuliaLang/julia/pull/23424.

**Comment by StefanKarpinski** [comment]
Our options at this point are:

1. Keep `A_mul_B` and all that jazz and live with it until 2.0.

2. Move `a'` etc. out of `Base` into `LinAlg` and fix this post 1.0, this means that you'd have to do `using LinAlg` before you can do `x'y` for a dot product.

3. Hassle @andyferris about finishing the lazy transpose and conjugate work that this requires.

**Comment by andyferris** [comment]
> Hassle @andyferris about finishing the lazy transpose and conjugate work that this requires.

Noted. :)

**Comment by StefanKarpinski** [comment]
For what it's worth, I think this is more crucial than getting the indexing with associatives stuff sorted. The main action item there would simply be to iterate dictionaries by value. The most conservative potential change for 0.7 would be to just deprecate dict iteration altogether and force explicit choice of iteration by `pairs(d)`, `keys(d)` or `values(d)`. That leaves us in a position to choose any means of iteration we want in the future, including going back to pair iteration.

**Comment by JeffBezanson** [comment]
The more I think about it, the more I like the idea of requiring `pairs(d)`, `keys(d)`, or `values(d)` to iterate over dicts. Anything else just leads to surprises --- other popular languages do keys by default, and on the other hand many operations make the most sense on values or pairs. There just isn't one obvious right way to do it.

**Comment by vtjnash** [comment]
What does that have to do with A_mul_b and all that jazz?

**Comment by quinnj** [comment]
> What does that have to do with A_mul_b and all that jazz?

Because we're collectively prioritizing @andyferris's discretionary time and open-source efforts 😆

**Comment by andyferris** [comment]
@StefanKarpinski I came to the same conclusion - if someone else wants to volunteer for a `ValueIterator` for dicts and deprecating `next(::Associative)`, I'd love to work on this stuff ;)

@JeffBezanson Getting even more off topic, I still feel the answer lies in what you want `map(f, dict)` and `reduce(op, dict)` to do (my answer: the most useful behavior for `map` (for manipulating data, especially after a `group`/`groupby` function) is to preserve keys and map values, just like for arrays (including offset arrays), and to `reduce` over values). These functions seem subservient to the iteration API - especially `reduce`.

@vtjnash Yes, it's a bit convoluted how this conversation ended up here! :smile:

**Comment by vtjnash** [comment]
Please take off-topic remarks elsewhere. This thread is about making implementations of A_mul_b better, not about making Associative worse.

**Comment by StefanKarpinski** [comment]
> Please take off-topic remarks elsewhere.

As explained, these are not off-topic and have to do with work prioritization which involves this issue.

**Comment by Sacha0** [comment]
Linking [this analysis of paths to addressing this issue by 1.0](https://github.com/JuliaLang/julia/issues/20978#issuecomment-347360279). Best!

**Comment by JeffBezanson** [comment]
These functions have been removed :tada: so I think we can close this.
