### ISSUE TITLE
keyword argument constructor for immutables

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#5333]
@JeffBezanson and I were discussing adding a second default constructor with the semantics

``` julia
immutable foo
bar::Int
baz::Int
# this is the usual default constructor
foo(bar,baz) = new(bar,baz)
# I am proposing this in addition
foo(x::foo;bar=nothing,baz=nothing) = 
    foo(bar === nothing ? x.bar : bar, baz === nothing ? x.baz : baz)
end
```

This would cover the case where you want to obtain a new value with one field changed  e.g. in the example above

```
julia> foo(1,2)
foo(1,2)

julia> foo(ans,baz=3)
foo(1,3)
```

This is especially useful when the immutable has a lot of field. One example that comes to mind and where I already define a constructor like the above is URIParser.jl

**Comment by Keno** [comment]
I think we need to start thinking about syntax for modifying immutables in place in arrays (and potentially in other mutables) now that that tuples can be used as fixed size arrays. Right now using them that way is quite painful.

**Comment by johnmyleswhite** [comment]
Bump

**Comment by damiendr** [comment]
It seems the above commit (92339436a97753b950e63f8a095148b3ea8a755e) is not in the current `master`. Will it eventually get there, or did this get reverted?

**Comment by ihnorton** [comment]
See #6122

**Comment by StefanKarpinski** [comment]
I think we still want this – at least I periodically do and then wonder why we don't have it yet.

**Comment by StefanKarpinski** [comment]
I don't believe this would be breaking, would it?

**Comment by tkf** [comment]
Wouldn't it break `Adjoint`?

**Comment by vtjnash** [comment]
Base now has `@kwdef`, which I guess pretty much replaces this, since we haven't had this for many releases now anyways
