### ISSUE TITLE
Add a function to get indices from a RegexMatch

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#53370]
This would provide a generic function

```julia
indices(rm::RegexMatch) = (rm.offset-1) .+ eachindex(rm.match)
```

which is useful, but not essential, as RegexMatch's fields are public. However, a generic function is useful because it allows packages to define something similar for their types that do not have public fields. Motivated by https://github.com/JuliaLang/JuliaSyntax.jl/issues/417, and by an AbstractMatch type I'm currently defining elsewhere in a package.

**Comment by jariji** [comment]
- Do you mean `.+` instead of `+`? 
- I think `indices` is a confusing name since `RegexMatch` already has `eachindex`.

**Comment by LilithHafner** [comment]
Yes

Perhaps `parent_indices` or `source_indices`?

**Comment by LilithHafner** [comment]
Thanks! I missed that.
