### ISSUE TITLE
Colors are gone in logging on master

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#53384]
<img width="173" alt="image" src="https://github.com/JuliaLang/julia/assets/1282691/14599094-d2f3-4ee4-bfad-8f4362e7e547">

**Comment by KristofferC** [comment]
@tecosaur, is this some styled string thing? But Logging depends on that and there are still no colors?

**Comment by tecosaur** [comment]
Should be fixed with #53333.

**Comment by giordano** [comment]
Logging macros without `using Logging` are still colourless:

![image](https://github.com/JuliaLang/julia/assets/765740/a5bb433c-fa87-4756-a076-dc2cdd9439b8)

**Comment by KristofferC** [comment]
Yew, but that is captured in a different issue already.

**Comment by giordano** [comment]
Link to the issue for reference?

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/issues/52075
