### ISSUE TITLE
Thread pool of main thread varies depending on how Julia is started

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLang/julia#53389]
Depending on whether Julia is started with or without interactive threads, the main thread is in either the interactive or default threadpool:

```julia
cb@mm ~
➜ julia -t 3 -E 'Threads.threadpool()'
:default

cb@mm ~
➜ julia -t 3,1 -E 'Threads.threadpool()'
:interactive
```

I find this surprising. Is this intentional? If so, what is the reasoning behind this?

Note that this is wrongly documented since 1.9 (I created a [doc fix PR](https://github.com/JuliaLang/julia/pull/53388)).

Came up [in this issue](https://github.com/JuliaLang/julia/issues/53217) and also seems to be causing problems (see [discourse.julialang.org/t/what-is-julia-doing-with-your-threads/110052/20](https://discourse.julialang.org/t/what-is-julia-doing-with-your-threads/110052/20) and the related issue https://github.com/JuliaLang/julia/issues/53269).

**Comment by carstenbauer** [comment]
> This was implemented [here](https://github.com/JuliaLang/julia/pull/49094), and the [docfix](https://github.com/JuliaLang/julia/pull/53117) came sometime after.

Note that this docfix is orthogonal to what is discussed here. I was just fixing a statement about thread ids, specifically, there order.

**Comment by JeffBezanson** [comment]
Yes this is intentional. Thanks for the doc fix. We will have the option of changing this at some point, but in the meantime I don't think it's so strange that if there are any interactive threads, then the main thread is one.

**Comment by carstenbauer** [comment]
> I don't think it's so strange that if there are any interactive threads, then the main thread is one.

The part that is a bit more surprising is that the main thread isn't always an interactive thread. (That's also what Valentin seemed to convey with his post [here](https://github.com/JuliaLang/julia/issues/53217#issuecomment-1930722108).)
But ok, I take it that this is not considered to be an issue.
