### ISSUE TITLE
llvm-julia-16.0.6-2.tar.gz checksum fail

### ISSUE THREAD

**Issue by semarie** [JuliaLang/julia#53399]
While building julia with `USE_BINARYBUILDER=0`, the llvm tarball fetched is `llvm-julia-16.0.6-2.tar.gz`, and it failed the checksum check.

the `deps/checksums/llvm` has been updated by #53195, and the downloaded file currently match the previous hash.

I am unsure if:
- the fetched file isn't the right one because the PR updated llvm to 16.0.6+4 (and we are fetching 16.0.6-2)
- the fetched file isn't the right one because the file should have been updated too (and it wasn't)
- the fetched file is the right one and the checksum change is unintented

Cc @gbaraldi and @vchuravy who worked on the llvm update

**Comment by vchuravy** [comment]
The source hash should not have changed. Since https://github.com/JuliaLang/llvm-project/tags is still on 16.0.6-2 and 16.0.6+4 was a pure build change in Yggdrasil. I am unsure why `contrib/update_checksums` messed that up.
