### ISSUE TITLE
Type inference for cat

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#5339]
The return type of `cat` is determined by the value of the `dim` argument as well as the types of the inputs, which means we can't infer the dimensionality of the returned array. OTOH `dim` is usually constant, so we usually have all of the information necessary to determine the return type at compile time, just not in a way that type inference can use. What is the best approach here?

**Comment by rikhuijzer** [comment]
Related PR at https://github.com/JuliaLang/julia/pull/45028.

**Comment by aviatesk** [comment]
Fixed by #45028, thanks for mentioning this issue on the PR, @rikhuijzer !
