### ISSUE TITLE
[BUG] Julia Nightly (1.12.0-DEV.49) Issue with HTTP.jl 

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaLang/julia#53425]
Hi folks!

This is a bit of a strange thing but I have a [test suite arbitrarily failing](https://github.com/JuliaHealth/OMOPCDMCohortCreator.jl/actions/runs/7996837725/job/21840120555?pr=75#step:6:217) on Julia nightly (1.12.0-DEV.49, all other tests pass and they also pass locally) and see that it is from something related to HTTP.jl. Originally I thought this might be coming from a dependency I had but I think it might be something screwy with nightly. Is this a Julia bug or a package bug or just CI misbehaving?

Additionally, I am more inclined to believe it is a Julia bug with nightly after further discussion with @mortenpi on the Julia Slack. Morten was saying they were also seeing issues with HTTP.jl in their work. And since this behavior I see is only happening on nightly, it might be there. 

Happy to provide more information but that is all I have seen so far and hopefully the error log included helps a bit too!

**Comment by quinnj** [comment]
We probably just need to merge a few of @vtjnash's recent PRs (like https://github.com/JuliaWeb/HTTP.jl/pull/1148)

**Comment by TheCedarPrince** [comment]
Ah coolio! Let me know when the PRs merge and I'll report back if I still see the errors I was noticing!

**Comment by mortenpi** [comment]
Looks to be fixed with https://github.com/JuliaWeb/HTTP.jl/releases/tag/v1.10.3

**Comment by vtjnash** [comment]
The tests still fail, but that is because fixes for them didn't get merged from https://github.com/JuliaWeb/HTTP.jl/pull/1148
