### ISSUE TITLE
Allow QR decomposition for zero-row matrices.

### ISSUE THREAD

**Issue by manuelbb-upb** [JuliaLang/julia#53451]
This came up in https://github.com/DynareJulia/FastLapackInterface.jl/issues/39

Currently, Julia allows for QR decomposition of zero-column matrices by skipping the call to LAPACK with a simple conditional [in this line].(https://github.com/JuliaLang/julia/blob/923fe2d74d469d73f0285a9cd41c88f90edd04d1/stdlib/LinearAlgebra/src/lapack.jl#L456)

Zero-row matrices are not supported and give an argument error:
```julia
 LA.qr(zeros(0, 10))
```
```
 ** On entry to DGEQRT parameter number  3 had an illegal value
ERROR: ArgumentError: invalid argument #3 to LAPACK call
```

Is there a reason for this?
The data type should support these matrices:
```julia
import LinearAlgebra as LA
A = Matrix{Float64}(undef, 0, 10)
T = Matrix{Float64}(undef, 0, 0)
qr = LA.QRCompactWY(A, T)
```
and `qr` is as I would expect it.

**Comment by dkarrasch** [comment]
Would it fix the issue if we changed the condition to

```julia
n > 0 && m > 0
```

so that we go down the LAPACK path only in the LAPACK-valid cases ? If yes, would you be able to submit a PR, together with unit tests?

**Comment by manuelbb-upb** [comment]
That would indeed be sufficient. I will prepare a PR until tomorrow evening.
