### ISSUE TITLE
need Array `typeinfo` support for NamedTuple

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#53455]
Doesn't seem necessary to print the type at all in the last case:
```julia
julia> (1,)
(1,)

julia> (a=1,)
(a = 1,)

julia> ([(1,)],)
([(1,)],)

julia> ([(a=1,)],)
(@NamedTuple{a::Int64}[(a = 1,)],)
```

**Comment by JeffBezanson** [comment]
Also an issue with no tuple and just show/repr:
```
julia> show([(a=1,)])
@NamedTuple{a::Int64}[(a = 1,)]
```
Needs typeinfo support in array printing, I believe.

**Comment by JeffBezanson** [comment]
Adding a case to `typeinfo_implicit` should do it.
