### ISSUE TITLE
regression in inference performance caused by CodeInstance refactor

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#53459]
It looks like #53219 causes some fairly extreme performance issues in inference (up to 50x longer inference times), though curiously also sometimes provides up to a 5x speed up

_Originally posted by @vtjnash in https://github.com/JuliaLang/julia/issues/53219#issuecomment-1962747276_

**Comment by oscardssmith** [comment]
Do we have a MWE for the regression?

**Comment by vtjnash** [comment]
Yes, sorry, I should have pointed out that this is reported by BaseBenchmarks for this commit: https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/1c25d93_vs_c0a93f8/report.md

**Comment by Zentrik** [comment]
FWIW, it seems like a lot of the regression has been fixed, but there's still a fairly large regression in the abstract interpretation benchmarks (in the daily benchmarks at least):

# Summary
| | Range | Mean | Count |
|:---:|:---:|:---:|:---:|
| Regressions | 1.97%, 855.32% | 119.18% | 12 |
| Improvements | - | 0.00% | 0 |
| All | 1.97%, 855.32% | 119.18% | 12 |

# Abstract Interpretation Benchmarks
| Benchmark | % Change |
|:---:|:---:|
| inference.abstract interpretation.Base.init_stdio(::Ptr{Cvoid}) | 855.32%
| inference.abstract interpretation.REPL.REPLCompletions.completions | 226.32%
| inference.abstract interpretation.broadcasting | 103.55%
| inference.abstract interpretation.println(::QuoteNode) | 65.12%
| inference.abstract interpretation.rand(Float64) | 49.64%
| inference.abstract interpretation.sin(42) | 45.25%
| inference.abstract interpretation.many_invoke_calls | 31.07%
| inference.abstract interpretation.many_method_matches | 21.72%
| inference.abstract interpretation.many_global_refs | 20.46%
| inference.abstract interpretation.many_opaque_closures | 7.69%
| inference.abstract interpretation.many_const_calls | 2.08%
| inference.abstract interpretation.many_local_vars | 1.97% 

Per http://tealquaternion.camdvr.org/compare.html?stat=min-wall-time&name=inference.abst&nonRelevant=true

**Comment by vtjnash** [comment]
Okay, the init_stdio regression is probably fine then, since we just significantly increased the amount of code visible to the compiler, but didn't change the compiler.
