### ISSUE TITLE
comparison bug in `Version`

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#53502]
Since semVer 2.0.0, they have dropped the `build` part for comparison completely, so both of these are wrong:

```julia
julia> v"1.2.3-pre.3+build.3" < v"1.2.3-pre.3+build.4"
true

julia> v"1.2.3-pre.3+build.4" == v"1.2.3-pre.3+build.3"
false
```

ref: https://semver.org/spec/v2.0.0.html#spec-item-10

spotted by @avx-ctan

**Comment by PallHaraldsson** [comment]
It seems highly ironic that semver broke version numbers... I.e. RC2 more strict, than 2.0.0, my understanding.

If 2.0.0 had been out would we have followed it? This is about version numbers, i.e. the code for it in Base, but indirectly about every Julia project...?! Most would be ok with only 2.0.0? Or I think so, so do we need version 2, for Julia, or at least just the version numbers? Should we state for package registration that only following 2.0.0 is ok (RC2 not needed)?
