### ISSUE TITLE
Inconsistent int-float promotion in `hypot`

### ISSUE THREAD

**Issue by danielwe** [JuliaLang/julia#53505]
`hypot(::Int64, ::Float32)` promotes the arguments and result to `Float64`, contrary to the behavior of `promote`, which gives `Float32` in this case.

```julia-repl
julia> hypot(1, 3.0f0)
3.1622776601683795

julia> promote(1, 3.0f0)
(1.0f0, 3.0f0)
```

The culprits are the following method definitions:

https://github.com/JuliaLang/julia/blob/71f68b4ce9189e64f320631f3f74ffb3dd10e875/base/math.jl#L798-L799

Seems like this could be rewritten as follows for consistency with `promote`:

```julia
hypot(x::Number, y::Number) = _hypot(float.(promote(x, y))...)
hypot(x::Number, y::Number, xs::Number...) = _hypot(float.(promote(x, y, xs...)) 
```

**Comment by mikmoore** [comment]
Another consequence is permutation-asymmetry in the return type
```julia-repl
julia> hypot(1, 1f0)
1.4142135623730951 # Float64

julia> hypot(1f0, 1)
1.4142135f0 # Float32
```
