### ISSUE TITLE
Parser glitch?

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#53522]
I am surprised by the following behavior. Not quite sure if it is a bug.
```julia
julia> :(1 .== 2).args[1]
:.==


julia> :(.==)
:((.==))
```
I would have expected that `:(1 .== 2)` yields `:(.==)`. It came up here: https://github.com/jw3126/ArgCheck.jl/issues/44
Furthermore:
```julia

julia> eval(:(1 .== 2))
false

julia> eval(:(1 .== 2).args[1])
ERROR: UndefVarError: `.==` not defined
```
I would have expected that when I can eval an expression like this one, I can also eval its args without error.

**Comment by mbauman** [comment]
> I would have expected that when I can eval an expression like this one, I can also eval its args without error.

I don't think that's a valid assumption.  Beyond dotted operators, there are other Exprs that the parser generates whose args require lowering — and aren't separately eval-able.  For example:

```julia
julia> ex = :(f(::Int)=2)
:(f(::Int) = begin
          #= REPL[3]:1 =#
          2
      end)

julia> eval(ex)
f (generic function with 1 method)

julia> eval(ex.args[1])
ERROR: syntax: invalid "::" syntax
```

In this case in particular, you're seeing the difference between `Symbol(".==")` and `Expr(:., :(==))`

**Comment by jw3126** [comment]
Thanks! Any recommendations on how to deal with this? As a julia programmer, should I roll my own lowering, that converts `Symbol(".==")` to  `Expr(:., :(==))`?
