### ISSUE TITLE
Some functions will show undefined 

### ISSUE THREAD

**Issue by lichen2023905** [JuliaLang/julia#53550]
julia> using Pkg
julia> using NetworkLayout
julia> using PlasmoPlots
julia> plt_matrix = matrix_layout(graph1, node_labels=true, markersize=15)

ERROR: UndefVarError: `matrix_layout` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[20]:1

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/ instead.
