### ISSUE TITLE
InvertedIndices broke on 1.11

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#53591]
The following code now errors on 1.11:

```julia
using InvertedIndices
A = reshape(-10:13,3,2,:)
z = A .== -10
A[Not(z)]
```

On 1.10 it resulted in 

```
julia> A[Not(z)]'
23-element Vector{Int64}:
 -9  -8  -7  -6  -5  -4  -3  -2  -1  0  1  2  3  4  5  6  7  8  9  10  11  12  13
```

Bisected to 933a83af6af1a5d272095a8875192f944b182f29. cc @N5N3

**Comment by vtjnash** [comment]
It looks like there is a fault with how InvertedIndices implements its own computation of `picks`, which fails its own boundscheck implementation:
```
julia> axes(Base.to_indices(A, (Not(z),))[1].picks)
(Base.OneTo(24),)

julia> axes(A)
(Base.OneTo(3), Base.OneTo(2), Base.OneTo(4))
```
The issue looks like it might have been pirating `Base.to_indices` before, resulting in slightly different calls to its own internal functions, causing this change to uncover a bug in the package's boundscheck implementation.
