### ISSUE TITLE
Broken links in manual

### ISSUE THREAD

**Issue by lbilli** [JuliaLang/julia#53594]
When browsing the [documentation](https://docs.julialang.org), clicking on the `source` tooltip popup of certain functions, such as [`Statistics.mean()`](https://docs.julialang.org/en/v1/stdlib/Statistics/#Statistics.mean), lands on a `404` page.

This happens  on current `v1.10.2` as well as `v1.12-dev` versions of the manual.

Other standard library modules are similarly affected: _e,g_ `Profile`, `SharedArrays`.

For most other though, the `source` tooltip doesn't pop up!

**Comment by giordano** [comment]
Duplicate of #50035?
