### ISSUE TITLE
Installation problem due to glibc requirement (CentOS 6.10, glibc 2.12, linux kernel 2.6.32)

### ISSUE THREAD

**Issue by lhapp27** [JuliaLang/julia#53605]
As the title says, I'm currently trying to upgrade/install the current julia version (1.10.2) via juliaup on a server with CentOS 6.10, which has only glibc 2.12 installed. I understand that this OS is outdated, unfortunately I have no rights (root/sudo) to upgrade it. Nevertheless, the linux kernel version is
`
$ uname -r 
#2.6.32-754.33.1.el6.x86_64
`
which according to the table of supported platforms on https://julialang.org/downloads/#supported_platforms is supported (2.6.24+). The same website also mentions that we should file an issue here when having problems. Despite some search, I cannot find any official information on which glibc version is required. In some other place (https://github.com/JuliaLang/juliaup/issues/321#issuecomment-1267124944) it is mentioned that 2.12 is still supported, but I'm not sure that information is still valid. Some other place mentioned 2.17 i think, but I dont have a link at hand.

To install julia, I downloaded juliaup via
`curl -fsSL https://install.julialang.org | sh`
the installation procedure (default option) then worked without errors.

Trying to run julia however results in the error claiming that a newer glibc version (here 2.14) is necessary. 
> /home/[username]/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/bin/julia: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/[username]/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/bin/../lib/libjulia.so.1.10)

I tried to install that version of glibc manually and locally for my user, and link the julia binary to that new glibc libraries, but so far without success (see [my post on discourse.julialang](https://discourse.julialang.org/t/using-workaround-for-unsupported-eold-operating-systems-e-g-centos-6-was-test-julia-basic-functionality/107787/22?u=physh) for more details and more people reporting similar problems). Before putting more effort in fixing that issue, I would like to know if I'm on the correct path, or maybe 2.12 is indeed sufficient and I misunderstand the problem. Also it would be good to know which glibc version is required in the end (I dont want to fix 2.14 and then get an error about 2.15 ...)

Another idea is downloading julia manually (https://julialang.org/downloads/#install_julia) as "Tarball with dependencies (GPG)". Does that mean it includes all necessary glibc library files, and I dont need to worry about manually downloading and linking them?

Please ask if you need additional information from my side. As the OS version is outdated, I can understand if you cannot provide full support. However, as more people might have similar issues (in the future for then outdated versions), maybe you can help me to find some kind of workaround.

**Comment by gbaraldi** [comment]
@staticfloat will correct me but IIRC we bumped minimum glibc support in 1.10 to 2.17, targeting RHEL 7.

**Comment by staticfloat** [comment]
Yes, because CentOS 6 was EOL in November of 2020, if I understand properly.  Also, I believe that the version of LLVM that we use in Julia v1.10 requires glibc v2.15+.

**Comment by lhapp27** [comment]
Thank you for your replies. I understand that CentOS 6 is EOL now. Is there any way to figure out which Julia version needs which glibc version? I think it would be good if such a table for system requirements/glibc dependencies exists. Or more concretely for my case: What version of Julia works with glibc 2.12?

**Comment by staticfloat** [comment]
Julia v1.9.2 is the last release that supports glibc v2.12.

**Comment by lhapp27** [comment]
Thank you, I have switched now to Julia 1.9.2 and it works.

Nevertheless, I think it would be good to have the official glibc-requirements for each Julia version listed somewhere, instead of letting people come here to ask case by case.

For comepleteness, maybe someone can reply to this question too?
> Another idea is downloading julia manually (https://julialang.org/downloads/#install_julia) as "Tarball with dependencies (GPG)". Does that mean it includes all necessary glibc library files, and I dont need to worry about manually downloading and linking them?

Then, I am happy to consider this case as closed.

**Comment by staticfloat** [comment]
> Another idea is downloading julia manually (https://julialang.org/downloads/#install_julia) as "Tarball with dependencies (GPG)". Does that mean it includes all necessary glibc library files, and I dont need to worry about manually downloading and linking them?

It does not include binaries; that tarball includes sources for you to compile Julia yourself.
