### ISSUE TITLE
Linalg: `ERROR: could not load symbol "dggsvd_64_"` in `LAPACK.ggsvd!`

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#53624]
```julia
julia> using LinearAlgebra

julia> LAPACK.ggsvd!('N', 'N', 'N', rand(4,4), rand(4,4))
ERROR: could not load symbol "dggsvd_64_":
/home/jishnu/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/bin/../lib/julia/libblastrampoline.so.5: undefined symbol: dggsvd_64_
Stacktrace:
 [1] ggsvd!(jobu::Char, jobv::Char, jobq::Char, A::Matrix{Float64}, B::Matrix{Float64})
   @ LinearAlgebra.LAPACK ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/LinearAlgebra/src/lapack.jl:1817
 [2] top-level scope
   @ REPL[2]:1

julia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  LD_LIBRARY_PATH = :/usr/lib/x86_64-linux-gnu/gtk-3.0/modules
  JULIA_EDITOR = subl
```
The error is present on `v"1.12.0-DEV.138"` as well.

The function `dggsvd` [has been deprecated](https://www.netlib.org/lapack/explore-html/dd/db4/dggsvd_8f_afd7d6d65e83c5417d757360f0e236b14.html#afd7d6d65e83c5417d757360f0e236b14) by LAPACK in favor of `dggsvd3` (and similarly for the equivalents). Unfortunately, simply updating the name of the function in `lapack.jl` seemed to throw a segfault, which I haven't looked into in detail.

**Comment by aravindh-krishnamoorthy** [comment]
Hello. Since `dggsvd3!` is already defined in ` lapack.jl`, using it will directly work.

```julia
julia> LAPACK.ggsvd3!('N', 'N', 'N', rand(4,4), rand(4,4))
```

The incompatibility (segfault) is likelz due to a new integer parameter `LWORK` defined in `ggsvd3`, which is not present in `ggsvd`.

Furthermore, I also feel it might not be a good idea to rewire `ggsvd!` to `ggsvd3_` since there may be BLASs out there that don't support the new function.
