### ISSUE TITLE
`--output-bc` is broken after LLVM bump

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#53646]
```
# ./usr/bin/julia.exe -J ./usr/lib/julia/sys.dll --compile=all --strip-ir --output-bc sys.bc.a -e 'exit()'
ERROR: failed to emit output file 'text_opt#0.bc': Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM16.0.6jl' Reader: 'LLVM 16.0.6jl')
```

**Comment by gbaraldi** [comment]
I took a look at this but not sure what to do. WriteArchive doesn't take a context so we can't set the opaque pointers setting inside, which causes the error.

**Comment by vtjnash** [comment]
It seems like this bug will just go away on its own once we upgrade llvm again and lose typed-pointers

**Comment by gbaraldi** [comment]
Yep

**Comment by gbaraldi** [comment]
Seems to work on master.
