### ISSUE TITLE
Can't sample random `Core.BFloat16`

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#53651]
`Core.BFloat16` was added as a new `AbstractFloat` in #51470, but so far it doesn't seem possible to call `rand(BFloat16)`:

```julia
julia> rand(Core.BFloat16)
ERROR: MethodError: no method matching Random.Sampler(::Type{TaskLocalRNG}, ::Random.SamplerTrivial{Random.CloseOpen01{…}, Core.BFloat16}, ::Val{1})
This error has been manually thrown, explicitly, so the method may exist but be intentionally marked as unimplemented.

Closest candidates are:
  Random.Sampler(::Type{<:AbstractRNG}, ::Random.Sampler, ::Union{Val{1}, Val{Inf}})
   @ Random ~/julia/usr/share/julia/stdlib/v1.12/Random/src/Random.jl:145
  Random.Sampler(::Type{<:AbstractRNG}, ::Any, ::Union{Val{1}, Val{Inf}})
   @ Random ~/julia/usr/share/julia/stdlib/v1.12/Random/src/Random.jl:181
  Random.Sampler(::Type{<:AbstractRNG}, ::BitSet, ::Union{Val{1}, Val{Inf}})
   @ Random ~/julia/usr/share/julia/stdlib/v1.12/Random/src/generation.jl:488
  ...

Stacktrace:
 [1] Random.Sampler(T::Type{TaskLocalRNG}, sp::Random.SamplerTrivial{Random.CloseOpen01{…}, Core.BFloat16}, r::Val{1})
   @ Random ~/julia/usr/share/julia/stdlib/v1.12/Random/src/Random.jl:145
 [2] Random.Sampler(rng::TaskLocalRNG, x::Random.SamplerTrivial{Random.CloseOpen01{Core.BFloat16}, Core.BFloat16}, r::Val{1})
   @ Random ~/julia/usr/share/julia/stdlib/v1.12/Random/src/Random.jl:139
 [3] rand(rng::TaskLocalRNG, X::Random.SamplerTrivial{Random.CloseOpen01{Core.BFloat16}, Core.BFloat16})
   @ Random ~/julia/usr/share/julia/stdlib/v1.12/Random/src/Random.jl:253
 [4] rand(rng::TaskLocalRNG, ::Type{Core.BFloat16})
   @ Random ~/julia/usr/share/julia/stdlib/v1.12/Random/src/Random.jl:256
 [5] rand(::Type{Core.BFloat16})
   @ Random ~/julia/usr/share/julia/stdlib/v1.12/Random/src/Random.jl:259
 [6] top-level scope
   @ REPL[31]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

This was found in [these](https://github.com/Seelengrab/PropCheck.jl/blob/ef65810b14bf855447766c80cda0c8c5e05387c8/test/runtests.jl#L156) nightly tests (CI log is [here](https://github.com/Seelengrab/PropCheck.jl/actions/runs/8200981595/job/22428821623#step:6:71)). I can mark that particular combination of arguments broken for now, but it would be cool to get this functionality at some point :)

I'm not 100% sure the label `float16` is correct. This is about `BFloat16` after all, which is slightly different. Feel free to adjust as necessary!

**Comment by gbaraldi** [comment]
This is a type that doesn't have a full implementation in base, it's there to make sure codegen understands it in a packaged like https://github.com/JuliaMath/BFloat16s.jl

**Comment by Seelengrab** [comment]
It's a bit odd to me to define a type in Base that claims to be `AbstractFloat`, without actually behaving like that at all :/

**Comment by giordano** [comment]
I'm going to close this ticket as the random sampling method is implemented in [`BFloat16s.jl`](https://github.com/JuliaMath/BFloat16s.jl).  It's true `BFloat16s.jl` is basically doing type piracy, but at least there's coordinate with Base, it was expected to behave like that already in the above mentioned #51470, and if anything that's a separate issue.
