### ISSUE TITLE
Support multiple packages as arguments to Pkg.checkout()

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#5366]
It would be convenient to checkout multiple packages with `Pkg.checkout("pkg1", "pkg2", "pkg3")`.

**Comment by KristofferC** [comment]
Can be done with `Pkg.checkout.(["A", "B"])`

**Comment by tkelman** [comment]
same comment applies here as https://github.com/JuliaLang/julia/issues/19591#issuecomment-303965386, the resolver would have to run after each checkout, but I think this is a less common pattern than adding multiple packages so not as worth the trouble of optimizing
