### ISSUE TITLE
Buffer issue on nightly 1.12.0-DEV.148 (2024-03-08)

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/julia#53676]
I'm wondering why a test fails on nightly 1.12.0-DEV.148 (2024-03-08); I've got as far as this, but now I'm stuck:

```julia
julia-1.10> using Luxor
julia-1.10> d1 = Drawing(200, 100, :svg); circle(O, 20, :fill); finish()
true
julia-1.10> length(d1.bufferdata)
463
```

```julia
julia-1.12> using Luxor
julia-1.12> d1 = Drawing(200, 100, :svg); circle(O, 20, :fill); finish()
true
julia-1.12> length(d1.bufferdata)
0
```

I'd be grateful for some hints as to whether this is something I need to try to fix or if it's a known issue...

(probably starting [here](https://github.com/JuliaGraphics/Luxor.jl/blob/0ef020715718601b9f30bb33c9166ece909cc65c/src/drawings.jl#L33))

**Comment by oscardssmith** [comment]
there have been some changes to iobuffer recently. Is Luxor accessing the internals of it?

**Comment by cormullion** [comment]
I don't think it's doing much of that.

Starting at:

```julia
bufdata = UInt8[]
iobuf = IOBuffer(bufdata, read = true, write = true)
```

there's

```julia
Cairo.CairoSVGSurface(iobuf, w, h)
```

which is the `stream` for this (Cairo.jl):

```julia
function CairoSVGSurface(stream::T, w::Real, h::Real) where {T<:IO}
    callback = get_stream_callback(T)
    surf = CairoSurface(C_NULL, w, h, stream)
    GC.@preserve surf begin
        surf.ptr = ccall((:cairo_svg_surface_create_for_stream,libcairo), Ptr{Nothing},
                         (Ptr{Nothing}, Ptr{Nothing}, Float64, Float64), callback,
                         get_stream_ptr(surf), w, h)
    end
    return surf
end
```

**Comment by giordano** [comment]
I guess the question is "what do you want to do with `bufdata`?".  In julia v1.11+ `IOBuffer(::Vector{UInt8})` doesn't wrap directly the vector passed as input, and looking at [the docstring](https://docs.julialang.org/en/v1.10/base/io-network/#Base.IOBuffer) it doesn't look like it promised to do that.

**Comment by cormullion** [comment]
Thanks, Mosè! I think I vaguely understand. 

Do you think the behaviour of this on master is likely to change, or will I have to change my code somehow?

**Comment by oscardssmith** [comment]
We aren't currently planning on reverting the change, but we perhaps should ask triage on this one. In theory the change only affected internals, but it has broken a lot of people's code that was (intentionally or not) depending on internals.

**Comment by cormullion** [comment]
I'm happy to change my code - if you tell me what to change it to! 😀

**Comment by oscardssmith** [comment]
the issue here is that figuring out what to change it to is pretty hard. This code seems to be built extensively on the assumption that if you give a `Vector` to an `IOBuffer`, at some unspecified later point in time, after you have done a lot of things with that `IOBuffer`, the `Vector` you passed in to the `IOBuffer` at the beginning will have all the bytes that were read into the `IOBuffer`. I think the correct change, might be to remove the `bufferdata` field entirely, and replace the uses of `String(copy(buffer.bufferdata))` with
```
seekstart(buffer.buffer)
read(buffer.buffer)
```

That said, given the API that this package exposes, I think this would likely be a breaking change for the package.

**Comment by cormullion** [comment]
Thanks, Oscar. I think I see what's going on. 

I'm not able to rebuild this area of the code at the moment, so I'll close this issue for now.
