### ISSUE TITLE
What is used for value display in REPL?

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#53678]
My original question is "which function is used by the REPL to display values", and I couldn't really find a definite answer.

Docs point to `display(x)`
https://github.com/JuliaLang/julia/blob/6f8ba49e157d4b0de3726be8613a6ae607c5ccd2/doc/src/manual/types.md?plain=1#L1483-L1484

and to `show`

https://github.com/JuliaLang/julia/blob/6f8ba49e157d4b0de3726be8613a6ae607c5ccd2/stdlib/REPL/docs/src/index.md?plain=1#L60

on different pages.

But this is definitely not the whole story, the output of `display(x)` and just `x` in REPL is different:
```julia
julia> using StructArrays, JLArrays  # or any actual GPU array instead of JLArray

julia> x = StructArray(a=JLArray(rand(3)))
3-element StructArray(::JLArray{Float64, 1}) with eltype @NamedTuple{a::Float64}:
 (a = 0.7284120253405527,)
 (a = 0.12606390581511362,)
 (a = 0.6120157378655939,)

julia> x |> display
3-element StructArray(::JLArray{Float64, 1}) with eltype @NamedTuple{a::Float64}:
ERROR: Scalar indexing is disallowed.
...
```

So, would be nice to document how it actually works... I personally don't understand it for now.

**Comment by jariji** [comment]
See also 

https://discourse.julialang.org/t/improving-doc-for-display-print-show-repr/69124

**Comment by stevengj** [comment]
This is documented in [Custom pretty-printing](https://docs.julialang.org/en/v1/manual/types/#man-custom-pretty-printing) in the manual.

The REPL calls `display`, which defaults to the **3-argument** `show` (with an appropriate `IOContext`), which defaults to the 2-argument `show`.

**Comment by stevengj** [comment]
See also #53927.

**Comment by stevengj** [comment]
#53926 fixes the omission of `display` from the REPL docs.
