### ISSUE TITLE
Error Interacting with Commercial DLL

### ISSUE THREAD

**Issue by eric-hintz** [JuliaLang/julia#53684]
I am new to Julia, so apologies if  I am missing something basic, and please let me know if I need to change anything or include anything more to this post. 

I am attempting to write a small wrapper for a function in a DLL, which is from a commercial fortran library (REFPROP, for those familiar). The module I have written is below:

```julia
module RefPropWrapper

export REFPROPdll

using Libdl

function REFPROPdll(hFld,hIn,hOut,iUnits,iMass,iFlag,a,b,z)
    rpdll = Libdl.dlopen("C:/Program Files (x86)/REFPROP/REFPRP64.DLL")

    rppoint = Libdl.dlsym(rpdll,:REFPROPdll)

    ccall(rppoint,Any,(Cstring,Cstring,Cstring,Cint,Cint,Cint,Cdouble,Cdouble,Ptr{Cdouble}),hFld,hIn,hOut,iUnits,iMass,iFlag,a,b,z)
end

end
``` 

Here's the error I'm getting when I run that code:

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ff9f3c2f473 -- is_enter_interpreter_frame at C:/workdir/src\stackwalk.c:35 [inlined]
jl_unw_stepn at C:/workdir/src\stackwalk.c:156
in expression starting at C:\Users\erich\Documents\GitHub\AmmoniaSynthesis\Tst.jl:6
is_enter_interpreter_frame at C:/workdir/src\stackwalk.c:35 [inlined]
jl_unw_stepn at C:/workdir/src\stackwalk.c:156
rec_backtrace_ctx at C:/workdir/src\stackwalk.c:201
jl_throw_in_ctx at C:/workdir/src\signals-win.c:141
jl_exception_handler at C:/workdir/src\signals-win.c:272 [inlined]
jl_exception_handler at C:/workdir/src\signals-win.c:229
__julia_personality at C:/workdir/src\win32_ucontext.c:28
_chkstk at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlRaiseException at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
KiUserExceptionDispatcher at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
unknown function (ip: 00007ffa6f0f16a0)
REFPROPdll at C:\Program Files (x86)\REFPROP\REFPRP64.DLL (unknown line)
REFPROPdll at C:\Users\erich\Documents\GitHub\AmmoniaSynthesis\RefPropWrapper.jl:12
unknown function (ip: 00000243ffec6868)
jl_apply at C:/workdir/src\julia.h:1982 [inlined]
do_call at C:/workdir/src\interpreter.c:126
eval_value at C:/workdir/src\interpreter.c:223
eval_stmt_value at C:/workdir/src\interpreter.c:174 [inlined]
eval_body at C:/workdir/src\interpreter.c:635
jl_interpret_toplevel_thunk at C:/workdir/src\interpreter.c:775
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:934
jl_eval_module_expr at C:/workdir/src\toplevel.c:215 [inlined]
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:736
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:877
ijl_toplevel_eval at C:/workdir/src\toplevel.c:943 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:985
eval at .\boot.jl:385 [inlined]
include_string at .\loading.jl:2076
_include at .\loading.jl:2136
include at .\client.jl:489
unknown function (ip: 00000243ffec02eb)
jl_apply at C:/workdir/src\julia.h:1982 [inlined]
do_call at C:/workdir/src\interpreter.c:126
eval_value at C:/workdir/src\interpreter.c:223
eval_stmt_value at C:/workdir/src\interpreter.c:174 [inlined]
eval_body at C:/workdir/src\interpreter.c:635
jl_interpret_toplevel_thunk at C:/workdir/src\interpreter.c:775
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:934
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:877
ijl_toplevel_eval at C:/workdir/src\toplevel.c:943 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:985
eval at .\boot.jl:385 [inlined]
eval_user_input at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:150
repl_backend_loop at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:246
#start_repl_backend#46 at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:231
start_repl_backend at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:228
#run_repl#59 at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:389
run_repl at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:375
jfptr_run_repl_95792.1 at C:\Users\erich\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\lib\julia\sys.dll (unknown line)
#1013 at .\client.jl:432
jfptr_YY.1013_86568.1 at C:\Users\erich\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:1982 [inlined]
jl_f__call_latest at C:/workdir/src\builtins.c:812
#invokelatest#2 at .\essentials.jl:892 [inlined]
invokelatest at .\essentials.jl:889 [inlined]
exec_options at .\client.jl:333
_start at .\client.jl:552
jfptr__start_86593.1 at C:\Users\erich\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:1982 [inlined]
true_main at C:/workdir/src\jlapi.c:582
jl_repl_entrypoint at C:/workdir/src\jlapi.c:731
mainCRTStartup at C:/workdir/cli\loader_exe.c:58
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 2907 (Pool: 2899; Big: 8); GC: 0
```

**Comment by giordano** [comment]
What's the API of the `REFPROPdll` function (is it really called like that?)? What are the types of `hFld`, `hIn`, `hOut`, `iUnits`, `iMass`, `iFlag`, `a`, `b`, `z`? Also, did you read https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/ including all the caveats about Fortran?

**Comment by sgaure** [comment]
I don't know the dll, but generally Fortran expects arguments to be passed by reference. I.e. a pointer to the data. So `Cint`, `Cdouble` etc. might be inappropriate. I would try to specify the type as `Ptr{Cint}` and pass it as `Ref(iUnits)` etc.  What it does about strings I do not know. It depends, I suspect.

**Comment by inkydragon** [comment]
It looks like the main problem is the lack of necessary parameters.

### Doc for `REFPROPdll`
https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll

```c
#define RP_SIZE_T std::size_t
#define REFPROPdll_ARGS \
    char *,char *,char *,INT_REF,INT_REF,INT_REF,DOUBLE_REF,DOUBLE_REF,\
    double *,double *,char *,INT_REF,double *,double *,double *,DOUBLE_REF,INT_REF,char *,\
    RP_SIZE_T,RP_SIZE_T,RP_SIZE_T,RP_SIZE_T,RP_SIZE_T
```

https://github.com/CoolProp/REFPROP-headers/blob/2f206de280a71752e163e4fa6aff2ff358f464ac/REFPROP_lib.h#L438

There are some wrappers written in other languages for reference:
https://github.com/usnistgov/REFPROP-wrappers

**Comment by eric-hintz** [comment]
> What's the API of the `REFPROPdll` function (is it really called like that?)? What are the types of `hFld`, `hIn`, `hOut`, `iUnits`, `iMass`, `iFlag`, `a`, `b`, `z`? Also, did you read https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/ including all the caveats about Fortran?

The (Fortran) types of those parameters are char*, char*, char*, int, int, int, double, double, array(double)* respectively. I have read the docs, thanks for the link.



> I don't know the dll, but generally Fortran expects arguments to be passed by reference. I.e. a pointer to the data. So `Cint`, `Cdouble` etc. might be inappropriate. I would try to specify the type as `Ptr{Cint}` and pass it as `Ref(iUnits)` etc. What it does about strings I do not know. It depends, I suspect.

Thanks for this advice, I messed around with parameter types and which to send as pointers and that got me past the error. I'm still having another error (read-only memory), but this was definitely an improvement.



> It looks like the main problem is the lack of necessary parameters.
> ### Doc for `REFPROPdll`
> 
> https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll
> 
> ```c
> #define RP_SIZE_T std::size_t
> #define REFPROPdll_ARGS \
>     char *,char *,char *,INT_REF,INT_REF,INT_REF,DOUBLE_REF,DOUBLE_REF,\
>     double *,double *,char *,INT_REF,double *,double *,double *,DOUBLE_REF,INT_REF,char *,\
>     RP_SIZE_T,RP_SIZE_T,RP_SIZE_T,RP_SIZE_T,RP_SIZE_T
> ```
> 
> https://github.com/CoolProp/REFPROP-headers/blob/2f206de280a71752e163e4fa6aff2ff358f464ac/REFPROP_lib.h#L438
> 
> There are some wrappers written in other languages for reference: https://github.com/usnistgov/REFPROP-wrappers

I am confident I have the input parameters correct (except for type conversion), as I have worked with this DLL extensively in other languages. Most of those parameters you see in the #define result are outputs, not inputs.

Apologies for the screenshot, but here are the parameters defined in the documentation:
![image](https://github.com/JuliaLang/julia/assets/99251619/b2253643-553c-43bf-a672-732731342d53)

**Comment by Keno** [comment]
As pointed out by @inkydragon, the ABI appears incorrect. This isn't really the kind of thing you can just guess at. In particular different fortran compilers will sometimes implement ABIs differently, so the documention is not sufficient to determine the ABI. @inkydragon's reference to the C headers is likely your best bet for translation. Regardless, this is not a bug, so future discussion on this is best had at https://discourse.julialang.org/.
