### ISSUE TITLE
Pkg.update() does not report errors when git pull fails

### ISSUE THREAD

**Issue by ivarne** [JuliaLang/julia#5370]
I try to test the new REPL and because it is too early to tag versions, `Pkg.checkout` is very handy. It works very nice and updates to the most recent commit when I type `Pkg.update()`.

The problem is that I often need to change something in the package, to test solutions to bugs. When there are uncommitted changes in the package repository that conflicts with `git pull`, `Pkg.update()` fails silently. I would want to get a warning that it could not update the relevant repository instead.

I might work on this if others find it useful.

**Comment by jakebolewski** [comment]
I don't think this is an issue anymore.
