### ISSUE TITLE
`power_by_squaring(::Float16, ::Integer)` involves unnecessary conversion to `Float64`

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#53745]
On any target which has native support for `Float16` (e.g. Apple Silicon) you can see that `power_by_squaring` is doing unnecessary promotion to higher precision (`Float64`, not just `Float32`):
```julia
julia> code_llvm((Float16,); debuginfo=:none) do (x) x ^ 2 end
```
```llvm
; Function Signature: var"#9"(Float16)
define half @"julia_#9_2873"(half %"x::Float16") #0 {
top:
  %0 = fpext half %"x::Float16" to double
  %1 = call double @"j_#power_by_squaring#522_2882"(double %0, i16 signext 2)
  %2 = fptrunc double %1 to float
  %3 = fptrunc float %2 to half
  ret half %3
}
```
```julia
julia> code_llvm((Float16,); debuginfo=:none) do (x) abs2(x) end
```
```llvm
; Function Signature: var"#11"(Float16)
define half @"julia_#11_2885"(half %"x::Float16") #0 {
top:
  %0 = fmul half %"x::Float16", %"x::Float16"
  ret half %0
}
```

***Edit***: @jakobnissen pointed out this is happening around https://github.com/JuliaLang/julia/blob/912460bb7418ac68139dde9fdd854314bd32c6cd/base/math.jl#L1343-L1349 Note that this doesn't happen for `Float32`
```julia
julia> code_llvm((Float32,); debuginfo=:none) do x x^2 end
```
```llvm
; Function Signature: var"#59"(Float32)
define float @"julia_#59_13034"(float %"x::Float32") #0 {
top:
  %0 = fmul float %"x::Float32", %"x::Float32"
  ret float %0
}
```
@MasonProtter showed that's because https://github.com/JuliaLang/julia/blob/912460bb7418ac68139dde9fdd854314bd32c6cd/base/intfuncs.jl#L370 and `Float16` isn't in https://github.com/JuliaLang/julia/blob/912460bb7418ac68139dde9fdd854314bd32c6cd/base/intfuncs.jl#L362-L363

**Comment by giordano** [comment]
Now that llvm automatically handles Float16 demotion correctly (#55486), should we be able to extend the `literal_pow` method to Float16 for all targets?

**Comment by oscardssmith** [comment]
we could, but it's slightly tricky since for hardware that doesn't support Float16, doing the math in Float16 is probably a bad idea for speed reasons. otoh, it is reasonable to argue that if you do float16 computation without hardware support, it's your fault that it's slow...

**Comment by giordano** [comment]
To be clear, you aren't really doing math in `Float16` on hardware without native support: with the demotion working correctly in LLVM all `Float16`s are automatically converted to `Float32` and the result of each operation is converted back to `Float16`, and so on.  Yes, all these `Float16` -> `Float32` -> `Float16` conversions are going to be slow on hardware which doesn't have native support for `Float16`, but as you said that should be on the users.  `Float16` is useful only in limited cases anyway, and users should be aware that it's worth it only on dedicated hardware.  The advantage for julia would be in not treating `Float16` differently from` Float32` and `Float64` anymore.
