### ISSUE TITLE
ERROR: LoadError: type CodeInfo has no field linetable

### ISSUE THREAD

**Issue by ctkelley** [JuliaLang/julia#53753]
I filed  this as an issue with revise and was advised that it is a Julia Interpreter issue. Here is what I observe
julia12 --startup=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.206 (2024-03-15)
 _/ |\__'_|_|_|\__'_|  |  Commit 3c4af03cf2c (0 days old master)
|__/                   |

(@v1.12) pkg> add Revise
   Resolving package versions...
    Updating `~/.julia/environments/v1.12/Project.toml`
  [295af30f] + Revise v3.5.14
    Updating `~/.julia/environments/v1.12/Manifest.toml`
  [da1fd8a2] + CodeTracking v1.3.5
  [aa1ae85d] + JuliaInterpreter v0.9.29
  [6f1432cf] + LoweredCodeUtils v2.4.5
  [bac558e1] + OrderedCollections v1.6.3
  [ae029012] + Requires v1.3.0
  [295af30f] + Revise v3.5.14
  [0dad84c5] + ArgTools v1.1.2
  [56f22d72] + Artifacts v1.11.0
  [2a0f44e3] + Base64 v1.11.0
  [ade2ca70] + Dates v1.11.0
  [8ba89e20] + Distributed v1.11.0
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching v1.11.0
  [b77e0a4c] + InteractiveUtils v1.11.0
  [b27032c2] + LibCURL v0.6.4
  [76f85450] + LibGit2 v1.11.0
  [8f399da3] + Libdl v1.11.0
  [56ddb016] + Logging v1.11.0
  [d6f4376e] + Markdown v1.11.0
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.12.0
  [de0858da] + Printf v1.11.0
  [3fa0cd96] + REPL v1.11.0
  [9a3f8284] + Random v1.11.0
  [ea8e919c] + SHA v0.7.0
[9e88b42a] + Serialization v1.11.0
  [6462fe0b] + Sockets v1.11.0
  [f489334b] + StyledStrings v1.11.0
  [fa267f1f] + TOML v1.0.3
  [a4e569a6] + Tar v1.10.0
  [cf7118a7] + UUIDs v1.11.0
  [4ec0a83e] + Unicode v1.11.0
  [deac9b47] + LibCURL_jll v8.6.0+0
  [e37daf67] + LibGit2_jll v1.7.2+0
  [29816b5a] + LibSSH2_jll v1.11.0+1
  [c8ffd9c3] + MbedTLS_jll v2.28.6+0
  [14a3606d] + MozillaCACerts_jll v2023.12.12
  [83775a58] + Zlib_jll v1.2.13+1
  [8e850ede] + nghttp2_jll v1.59.0+0
  [3f19e933] + p7zip_jll v17.4.0+2
Precompiling project...
  ◑ JuliaInterpreter

  1 dependency had output during precompilation:
┌ JuliaInterpreter
│  ERROR: LoadError: type CodeInfo has no field linetable
│  Stacktrace:
│    [1] getproperty(ci::Core.CodeInfo, s::Symbol)
│      @ Base ./deprecated.jl:330
│    [2] linetable(arg::Core.CodeInfo)
│      @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/KozUS/src/utils.jl:269
│    [3] JuliaInterpreter.FrameCode(scope::Method, src::Core.CodeInfo; generator::Bool, optimize::Bool)
│      @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/KozUS/src/types.jl:148
│    [4] prepare_framecode(method::Method, argtypes::Any; enter_generated::Bool)
│      @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/KozUS/src/construct.jl:178
│    [5] prepare_framecode
│      @ ~/.julia/packages/JuliaInterpreter/KozUS/src/construct.jl:138 [inlined]
│    [6] prepare_call(f::Any, allargs::Vector{Any}; enter_generated::Bool)
│      @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/KozUS/src/construct.jl:249
│    [7] prepare_call
│      @ ~/.julia/packages/JuliaInterpreter/KozUS/src/construct.jl:235 [inlined]
│    [8] determine_method_for_expr(expr::Expr; enter_generated::Bool)
│      @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/KozUS/src/construct.jl:582
│    [9] determine_method_for_expr
│      @ ~/.julia/packages/JuliaInterpreter/KozUS/src/construct.jl:573 [inlined]
│   [10] enter_call_expr(expr::Expr; enter_generated::Bool)
│      @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/KozUS/src/construct.jl:621
│   [11] enter_call_expr
│      @ ~/.julia/packages/JuliaInterpreter/KozUS/src/construct.jl:619 [inlined]
│   [12] macro expansion
│      @ ~/.julia/packages/JuliaInterpreter/KozUS/src/construct.jl:237 [inlined]
│   [13] _precompile_()
│      @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/KozUS/src/precompile.jl:7
│   [14] top-level scope
│      @ ~/.julia/packages/JuliaInterpreter/KozUS/src/packagedef.jl:168
│   [15] include(mod::Module, _path::String)
│      @ Base ./Base.jl:559
│   [16] include(x::String)
│      @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/KozUS/src/JuliaInterpreter.jl:1
│   [17] top-level scope
│      @ ~/.julia/packages/JuliaInterpreter/KozUS/src/JuliaInterpreter.jl:14
│   [18] include
│      @ ./Base.jl:559 [inlined]
│   [19] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
│      @ Base ./loading.jl:2679
│   [20] top-level scope
│      @ stdin:4
│  in expression starting at /Users/ctk/.julia/packages/JuliaInterpreter/KozUS/src/packagedef.jl:168
│  in expression starting at /Users/ctk/.julia/packages/JuliaInterpreter/KozUS/src/JuliaInterpreter.jl:1
│  in expression starting at stdin:4
└

(@v1.12) pkg>
```

**Comment by KristofferC** [comment]
JuliaInterpreter repo is here https://github.com/JuliaDebug/JuliaInterpreter.jl and has an issue about it already https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/616
