### ISSUE TITLE
`convert` doesn't preserve `Base.OneTo` if the element type is being changed

### ISSUE THREAD

**Issue by mtfishman** [JuliaLang/julia#53806]
For example:
```julia
julia> convert(AbstractVector{Int32}, Base.OneTo(Int32(4)))
Base.OneTo(4)

julia> convert(AbstractVector{Int32}, Base.OneTo(4))
4-element Vector{Int32}:
 1
 2
 3
 4
```
Tested on v1.10.2 and v1.12.0-DEV.199.

Related to https://github.com/JuliaArrays/FillArrays.jl/issues/353.

**Comment by jishnub** [comment]
May be fixed by https://github.com/JuliaLang/julia/pull/48894

**Comment by mtfishman** [comment]
Sorry, this is a duplication of #27138.
