### ISSUE TITLE
Segfault when LD_LIBRARY_PATH is set at something

### ISSUE THREAD

**Issue by arthuradriaens-code** [JuliaLang/julia#53802]
I run arch linux with kernel version 6.8.1-arch1-1 x86_64 and installed julia trough it's binary installer. (version 1.10.2)

the REPL opens up in a terminal if I call julia but segfaults as soon as I try to do work with packages (be it install them or use them). However, when I set LD_LIBRARY_PATH="" and then start the REPL (or run any .jl file) everything runs as expected.

For now I just export LD_LIBRARY_PATH but might there be some straight-forward reason with which I can preventing it from segfaulting?

**Comment by Seelengrab** [comment]
>  installed julia trough it's binary installer. (version 1.10.2)

Just to be clear, have you installed julia through ` juliaup` , the binaries provided through [julialang.org/downloads/](https://www.julialang.org/downloads/) or through an Arch repository/`pacman`? Does the issue also occur if julia is installed through either `juliaup` or the provided binaries of the website?

**Comment by giordano** [comment]
I don't know what you expect Julia to do about this. Your issue doesn't provide concrete information, we don't see what you were trying to do when you get the crash, nor a full stacktrace to show where the error happened. But in general if you're setting LD_LIBRARY_PATH, which is a mechanism outside of Julia control since it's part of the dynamic loader, then all responsibility is on you.

**Comment by arthuradriaens-code** [comment]
@Seelengrab 
I installed it trough juliaup (by running 'curl -fsSL https://install.julialang.org | sh' in the terminal) , not pacman.
I tried the binary, and it gives the same problem.
@giordano 
I thought this issue might be relevant as no other programming languages I have have this kind of issue, I need LD_LIBRARY_PATH of course for my C++ software and it's just /usr/local/lib , /usr/lib and /lib64.

when I try julia --bug-report=rr I get a segmentation fault

I tried strace but I don't know if you could learn anything from this, I included part of it (attached text file) 
[stracefile.txt](https://github.com/JuliaLang/julia/files/14693685/stracefile.txt)

**Comment by arthuradriaens-code** [comment]
Ah this stracefile was from:

$julia
$]
$add ForwardDiff

This happens with any package and also with the inclusion of a package.

**Comment by giordano** [comment]
>  I thought this issue might be relevant as no other programming languages I have have this kind of issue, I need LD_LIBRARY_PATH of course for some specific software to work, normally it should just be used the same way as PATH, to look up if certain libs are installed. My LD_LIBRARY_PATH is /usr/local/lib , /usr/lib and /lib64 btw.

You may need more experience then:
```console
% mkdir dir1     
% echo 'void foo(int *p){ *p = 100; return; }' | cc -x c - -shared -o dir1/libfoo.so
% mkdir dir2                                                                         
% echo 'void foo(int *p){ return; }' | gcc -x c - -shared -o dir2/libfoo.so    
% echo 'void foo(int *p); int main(void) { foo((int *)0); return 0; }' | gcc -x c - -o main -L dir2 -lfoo -Wl,-rpath,dir2
% ./main                                                                                                                 
% LD_LIBRARY_PATH=dir1 ./main
zsh: segmentation fault (core dumped)  LD_LIBRARY_PATH=dir1 ./main

**Comment by arthuradriaens-code** [comment]
Ah thanks @giordano, I indeed had the wrong impression of how this worked, do I understand your point correctly that the cause are some incompatible libraries residing within one of the my lib folders, which Julia uses? Or did I misunderstand?

**Comment by gbaraldi** [comment]
Right, who knows what might be there, julia ships it's own libraries to avoid any incompatibilites but `LD_LIBRARY_PATH` goes around our efforts.
