### ISSUE TITLE
Misleading warning on ambiguous method definition

### ISSUE THREAD

**Issue by burrowsa** [JuliaLang/julia#5384]
If I do this:

    immutable Foo{T} end
    =={T}(lhs::Foo{T},rhs::Foo{T}) = lhs===rhs
    =={T}(lhs::Foo{T},rhs::Any) = false
    =={T}(lhs::Any,rhs::Foo{T}) = false

I get this warning

> Warning: New definition 
    ==(Any,Foo{T}) at none:1
is ambiguous with: 
    ==(Foo{T},Any) at none:1.
To fix, define 
    ==(Foo{T},Foo{T})
before the new definition.

even though I have already defined `==(Foo{T},Foo{T})`.

After a trying lots of alternatives it would seem that the solution is to do:

    immutable Foo{T} end
    =={T1,T2}(lhs::Foo{T1},rhs::Foo{T2}) = lhs===rhs
    =={T}(lhs::Foo{T},rhs::Any) = false
    =={T}(lhs::Any,rhs::Foo{T}) = false

So I think that the warning is misleading and should be changed to:

> Warning: New definition 
    ==(Any,Foo{T}) at none:1
is ambiguous with: 
    ==(Foo{T},Any) at none:1.
To fix, define 
    ==(Foo{T1},Foo{T2})
before the new definition.

**Comment by artkuo** [comment]
I'm not sure if it's related, but I get the following warning (0.5.0-dev, 0.4):
```julia
julia> foo(A::AbstractVecOrMat, B::Tridiagonal) = println("tridiagonal")
foo (generic function with 1 method)

julia> foo(A::AbstractVector, B::AbstractMatrix) = println("abstract matrix")
WARNING: New definition
    foo(AbstractArray{T<:Any, 1}, AbstractArray{T<:Any, 2}) at none:1
is ambiguous with:
    foo(Union{AbstractArray{T<:Any, 1}, AbstractArray{T<:Any, 2}}, Base.LinAlg.Tridiagonal) at none:1.
To fix, define
    foo(AbstractArray{T<:Any, 1}, Base.LinAlg.Tridiagonal)
before the new definition.
foo (generic function with 2 methods)
```
The warning can be avoided by inserting the following between the two lines:
```julia
foo(A::AbstractVector, B::Tridiagonal) = println("tridiagonal vector")
```

Or the first line can be split into separate definitions for `AbstractVector` and `AbstractMatrix` to eliminate the problem. There seems to be confusion related to the Union that is `AbstractVecOrMat`, which is so distracting that the other argument, `AbstractMatrix` is not recognized to be an unambiguous super of `Tridiagonal`?

**Comment by mauro3** [comment]
Close now that no more warnings are printed?
