### ISSUE TITLE
Loading test "relocatable upgrades" fails locally

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#53885]
@staticfloat @fatteneder it seems potentially problematic that this test added in https://github.com/JuliaLang/julia/pull/51989 fails locally but not on CI.

I added a `@show` to see the contents of the dir
```
loading    (1) |         failed at 2024-03-28T11:25:42.333
Test Failed at /Users/ian/Documents/GitHub/julia/usr/share/julia/test/loading.jl:1402
  Expression: length(filter(endswith(".ji"), readdir(foo_compiled_path))) == 1
   Evaluated: 2 == 1

Test Failed at /Users/ian/Documents/GitHub/julia/usr/share/julia/test/loading.jl:1403
  Expression: filesize(cache_path) != cache_size
   Evaluated: 1092 != 1092

readdir(foo_compiled_path) = ["Or1XO_bUlBJ.dylib", "Or1XO_bUlBJ.dylib.dSYM", "Or1XO_bUlBJ.ji", "Or1XO_mVdBs.dylib", "Or1XO_mVdBs.dylib.dSYM", "Or1XO_mVdBs.ji"]
```

https://github.com/JuliaLang/julia/blob/1172d6b75060c2dc4c159dc1a286631b0b09b027/test/loading.jl#L1400-L1401

**Comment by fatteneder** [comment]
For me these tests pass locally and I am on linux + current master.

What version are you on? And is this on windows?

**Comment by IanButterworth** [comment]
I'm on e07c0f1ddbfc89ad1ac4dda7246d8ed5d0d57c19 on MacOS

**Comment by fatteneder** [comment]
For me the tests also pass on that commit.
So maybe a MacOS issue?
