### ISSUE TITLE
Disallow size zero memory

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#53903]
possibly too late, but would the design have been simpler if we just disallowed 0 length memory? since it's not resizable, there isn't much need to be able to make one.

_Originally posted by @oscardssmith in https://github.com/JuliaLang/julia/pull/53896#discussion_r1545405814_

**Comment by vtjnash** [comment]
Not currently, as it is depended on in quite a few places

**Comment by oscardssmith** [comment]
which places? The only ones I can think of at the moment are they are constructed by empty arrays and Dicts. Changing those to allocate ones with a minimal capacity would allow us to remove the boundscheck in memoryrefget/set and the caching of size 0 memories. Is there additional problems we would incur that I'm missing?

**Comment by oscardssmith** [comment]
ah, is the problem that we use `jl_an_empty_memory_any` as a "null" value in a lot of typemap.c?

**Comment by jakobnissen** [comment]
From a user POV, I like being able to have zero-sized memory. Not allowing it would be an strange inconsistency (similar to say, not allowing zero-sized strings), and it also happens to make a useful placeholder value which can be more practical than a Nothing.

**Comment by mikmoore** [comment]
It would be nifty if creating size zero memory didn't actually result in an allocation (e.g., all size zero memory aliased to the same address). For example, if calls of `pointer(Float64[])` happened to always point to some static and unreadable address until the vector is resized. But maybe there are good reasons not to do this (it sounds like a null pointer and I hear those aren't very popular these days).

**Comment by oscardssmith** [comment]
@mikmoore good news for you:
```
julia> @btime Memory{Int}(undef, 0)
  1.716 ns (0 allocations: 0 bytes)
0-element Memory{Int64}
```

**Comment by KristofferC** [comment]
Doesn't seem like
