### ISSUE TITLE
Expose codegen option to emit dwarf debug info for native code

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#53910]
This patch
```diff
diff --git a/src/disasm.cpp b/src/disasm.cpp
index c2a55f23d12..d5975456ffc 100644
--- a/src/disasm.cpp
+++ b/src/disasm.cpp
@@ -1224,7 +1224,7 @@ jl_value_t *jl_dump_function_asm_impl(jl_llvmf_dump_t* dump, char emit_mc, const
             MCContext *Context = addPassesToGenerateCode(TM, PM);
             if (!Context)
                 return jl_an_empty_string;
-            Context->setGenDwarfForAssembly(false);
+            Context->setGenDwarfForAssembly(true);
             // Duplicate LLVMTargetMachine::addAsmPrinter here so we can set the asm dialect and add the custom annotation printer
             const MCSubtargetInfo &STI = *TM->getMCSubtargetInfo();
             const MCAsmInfo &MAI = *TM->getMCAsmInfo();
@@ -1252,8 +1252,8 @@ jl_value_t *jl_dump_function_asm_impl(jl_llvmf_dump_t* dump, char emit_mc, const
             std::unique_ptr<AsmPrinter> Printer(
                 TM->getTarget().createAsmPrinter(*TM, std::move(S)));
             Printer->addAsmPrinterHandler(AsmPrinter::HandlerInfo(
-                        std::unique_ptr<AsmPrinterHandler>(new LineNumberPrinterHandler(*Printer, debuginfo)),
-                        "emit", "Debug Info Emission", "Julia", "Julia::LineNumberPrinterHandler Markup"));
+                        std::unique_ptr<AsmPrinterHandler>(new DwarfDebug(*Printer)),
+                        "emit", "Debug Info Emission", "Julia", "DWARF"));
             if (!Printer)
                 return jl_an_empty_string;
             PM.add(Printer.release());
```
courtesy of @vchuravy, allows us to emit dwarf debug info, which for example can be used in Compiler Explorer, see for example demo from https://github.com/compiler-explorer/compiler-explorer/pull/6285#issue-2207163816:

![image](https://github.com/compiler-explorer/compiler-explorer/assets/765740/7c2f80b4-9c92-4761-9f6e-393d0ad26935)

However we don't want to enable dawrf debug info unconditionally, but rather expose a codegen parameter to switch this on upon demand.

**Comment by vchuravy** [comment]
Do we need those changes? IIRC I didn't need them locally.

**Comment by giordano** [comment]
Ah, good question, I still had them and now I'm not sure whether they were actually needed, or whether `Base.CodegenParams(; debug_info_kind=Cint(1), debug_info_level=Cint(2))` is sufficient :thinking:  Will need to double check it.

**Comment by giordano** [comment]
Ok, yes, I can confirm compiler explorer works with an official build of julia v1.11.0-alpha2, without the patch proposed above.  So we can get all the dwarf debug info we need just by using the codegen parameters `Base.CodegenParams(; debug_info_kind=Cint(1), debug_info_level=Cint(2))`.  Thanks!
