### ISSUE TITLE
Wrong typed `nothing` mixed in phi nodes

### ISSUE THREAD

**Issue by butterunderflow** [JuliaLang/julia#53932]
## The output of `versioninfo()`
```
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 11th Gen Intel(R) Core(TM) i5-11500H @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, tigerlake)
  Threads: 1 on 12 virtual cores
```

## How you installed Julia
```
wget https://mirrors.tuna.tsinghua.edu.cn/julia-releases/bin/linux/x64/1.9/julia-1.9.3-linux-x86_64.tar.gz
tar -xvzf julia-1.9.3-linux-x86_64.tar.gz && \
rm julia-1.9.3-linux-x86_64.tar.gz
PATH /julia-1.9.3/bin:$PATH
```

## My issue

I'm trying to learn Julia's internal IR design and its exception-handling mechanism. 
But I found some wrong type hinted `nothing` node (like `nothing::Tuple{Int64, Int64, Int64}` bellow) within the phi sequence when I combine try-catch statement with an unpack expression. 

```
julia> function evil()
           local tu
           try
               tu = (1, 2, 3)
               true
           catch e
               false
           end && print(tu...)
       end
evil (generic function with 1 method)

julia> code_typed(evil, ();debuginfo=:source)
1-element Vector{Any}:
 CodeInfo(
1 ─       nothing::Nothing
│   @ REPL[1]:3 within `evil`
│   %2  = ϒ (false)::Bool
└──       nothing::Union{}
2 ─ %4  = $(Expr(:enter, #5))
    @ REPL[1]:4 within `evil`
3 ─ %5  = ϒ (true)::Bool
│         nothing::Tuple{Int64, Int64, Int64}
│   @ REPL[1]:5 within `evil`
└──       $(Expr(:leave, 1))
4 ─       goto #7
5 ┄ %9  = φᶜ (%2, %5)::Bool
│         nothing::Tuple{Int64, Int64, Int64}
└──       $(Expr(:leave, 1))
    @ REPL[1]:7 within `evil`
6 ─       $(Expr(:pop_exception, :(%4)))::Any
7 ┄ %13 = φ (#4 => true, #6 => %9)::Bool
│         nothing::Tuple{Int64, Int64, Int64}
│   %15 = φ (#4 => true, #6 => false)::Bool
└──       goto #9 if not %15
8 ─       $(Expr(:throw_undef_if_not, :tu, :(%13)))::Any
│   %18 = invoke Main.print(1::Int64, 2::Int64, 3::Int64)::Nothing
└──       return %18
9 ─       return false
) => Union{Nothing, Bool}
```

My question is: 
1. Why insert `nothing` into phi nodes? What's the purpose of this `nothing` node? (note: it seems like an [invariant](https://github.com/JuliaLang/julia/pull/50158) hold by Julia);
2. Why the annotated type of the `nothing` node is not `Nothing`? Is this a bug or any design decision behind it?

Thank you so much for having a look,

**Comment by Keno** [comment]
This is legal. `nothing` in statement position is used as a deletion marker for the next compaction. As such it is semantically special (like other node types) and not a literal, so there's no reason to require the type to match (and we don't since it's both extra work, and sometimes helpful when debugging to have the type of what was deleted there, since it's a bit of extra information).

**Comment by Keno** [comment]
That said, questions like this are best posted on discourse: https://discourse.julialang.org/. You are however encouraged to submit PRs to the devdocs that improve the documentation about anything you found confusing once the answer has been found.
