### ISSUE TITLE
"@ref adding-tests-to-packages" is broken

### ISSUE THREAD

**Issue by dwinrow** [JuliaLang/julia#54021]
Anywhere (@ref adding-tests-to-packages) appears, the link is broken.

It currently links to https://pkgdocs.julialang.org/dev/creating-packages/#Adding-tests-to-the-package

However, the "dev" version of the Pkg docs no longer has a section on "creating-packages".

Note "v1" of the Pkg docs does.

I would change this myself and submit a Pull but I can't figure out where to make the change.

**Comment by KristofferC** [comment]
Will be fixed by https://github.com/JuliaLang/julia/pull/53509

**Comment by KristofferC** [comment]
Should be fixed now.
