### ISSUE TITLE
Unoptimal inference when function has error in a implicit return

### ISSUE THREAD

**Issue by gbaraldi** [JuliaLang/julia#54029]
While investigating some type instabilities in Pkg code specifically
```julia
	code_typed(Pkg.Artifacts.:(var"#ensure_artifact_installed#21"), (Base.BinaryPlatforms.Platform, Bool, Bool, IO, typeof(Pkg.Artifacts.ensure_artifact_installed), String, Dict, String), optimize=true)
```
the #21 might not be correct but it's the kwcall done in `code_typed(Core.kwcall, (@NamedTuple{platform::Base.BinaryPlatforms.Platform}, typeof(Pkg.Artifacts.ensure_artifact_installed), String, Dict{String, Any}, String))`
this code has a unstable return type because inference isn't able to succeed in realising that a call to `error` always throws

```
│     %486 = Base.not_int(%485)::Bool
└────        goto #107 if not %486
106 ─        goto #97
107 ┄ %489 = φ (#105 => %453, #96 => %405)::Any
│     %490 = Pkg.Artifacts.error(%489)::Any
└────        return %490
108 ─ %492 = π (%2, Base.SHA1)
│     %493 = Pkg.Artifacts.artifact_path::typeof(Artifacts.artifact_path)
│     %494 = invoke Artifacts.:(var"#artifact_path#7")(true::Bool, %493::typeof(Artifacts.artifact_path), %492::Base.SHA1)::String
└────        return %494
```

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/49260 I guess

**Comment by aviatesk** [comment]
It turns out that this is because Pkg.jl set `@max_methods 2` globally: https://github.com/JuliaLang/Pkg.jl/blob/00aa38cb3a85e200c4bd19efef3a15e32e192a8f/src/Pkg.jl#L5-L7

I have a potential solution in my mind, but it looks like it won't require merging #49260.

**Comment by aviatesk** [comment]
See #54086.
