### ISSUE TITLE
Bad backtraces because codeloc compression does not roundtrip properly

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#54031]
I've been noticing completely garbage backtraces in longer functions. I've looked into this a bit, and I believe the root cause is that `codelocs` don't roundtrip properly through the compression. E.g. here is the linetable from one of my larger functions, which comes out garbage from decompression: https://gist.github.com/Keno/0a5a9d90427f8352c5f9bf1ce394a998

**Comment by IanButterworth** [comment]
I wonder if this is the issue behind https://github.com/JuliaLang/julia/issues/53816 and that the libunwind warning is a red herring

**Comment by Keno** [comment]
Try the PR and see if the issue is fixed.
