### ISSUE TITLE
Provide a julia alternative of `pthread_once`

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#54042]
`pthread_once` is a way to execute a function only once (https://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_once.html) and assure that the function has run after it returns. This would probably be useful to provide in Julia.

**Comment by quinnj** [comment]
Maybe this could be simplified as:
```julia
mutable struct OnceControl
    @atomic set
    OnceControl() = new()
end

function execute_once!(oc::OnceControl, f)
    if @atomiconce(oc.set = true)
        f()
    end
end

function example_init()
    println("Example initialization executed by $(Threads.threadid()).")
    error()
end

const once_control = OnceControl()
@sync for i in 1:10
    Threads.@spawn execute_once!(once_control, example_init)
end
```

I don't personally love the idea of just retrying on a different thread on failure. I think if it fails, it fails, with no retry. Unless you have some kind of specific failure mode in mind that would warrant a retry? Or is there some behavior from pthread_once you're trying to emulate?
