### ISSUE TITLE
Allow symlink'd startup.jl file

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/julia#54058]
I like to have all of my configuration files in a single git repo so I can synchronize them across machines. The basic workflow is:

```bash
mv ~/.zshrc ~/Documents/sysconfig/.zshrc
ln -s ~/Documents/sysconfig/.zshrc ~/.zshrc
```

which lets me track changes to all of my configuration files.

However, I tried to do this with the Julia `~/.julia/config/startup.jl` file and it complains about the symbolic link:

```bash
> julia
ERROR: IOError: stat("/Users/mcranmer/.julia/config/startup.jl"): too many symbolic links encountered (ELOOP)
Stacktrace:
 [1] uv_error
   @ ./libuv.jl:106 [inlined]
 [2] stat(path::String)
   @ Base.Filesystem ./stat.jl:176
 [3] isfile
   @ ./stat.jl:494 [inlined]
 [4] _local_julia_startup_file
   @ ./client.jl:348 [inlined]
 [5] load_julia_startup()
   @ Base ./client.jl:356
 [6] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:281
 [7] _start()
   @ Base ./client.jl:526
```

Could symlink'd startup.jl files be allowed?

**Comment by giordano** [comment]
The error message
```
too many symbolic links encountered (ELOOP)
```
means that you a circular symlink.

**Comment by MilesCranmer** [comment]
Thanks. That's very very weird. I removed the symlink and tried `ln -s` again and the error went away. Not sure what my filesystem was up to... The original file remains unmodified
