### ISSUE TITLE
`take!` after `pushfirst!` reads garbage values

### ISSUE THREAD

**Issue by nhz2** [JuliaLang/julia#54097]
Here is a MWE:
```julia
julia> b = pushfirst!([0x02], 0x01)
2-element Vector{UInt8}:
 0x01
 0x02

julia> take!(IOBuffer(b))
5-element Vector{UInt8}:
 0x01
 0x02
 0x69
 0x73
 0x69
```

```julia
julia> versioninfo()
Julia Version 1.12.0-DEV.347
Commit c0611e8c49c (2024-04-15 17:22 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 7800X3D 8-Core Processor
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver4)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
```

I think the issue is
https://github.com/JuliaLang/julia/blob/d8b9810b8908560cc4aaa744c0e587f4dfd11bfb/base/iobuffer.jl#L461
using `StringVector(io.size)` instead of `StringVector(nbytes)`.

The `pushfirst!` causes the `IOBuffer` to have a nonzero `offset` field (added in https://github.com/JuliaLang/julia/pull/53192) which makes `nbytes` and `io.size` different.

**Comment by andrewjradcliffe** [comment]
Technically, it's not reading garbage values, but rather, nothing is written to the trailing `io.size - nbytes` values allocated by `StringVector`.

**Comment by KristofferC** [comment]
I made a PR to get the ball rolling (https://github.com/JuliaLang/julia/pull/54129). Want to see if this fixes a regression found by PkgEval.
