### ISSUE TITLE
inv() not working on mac

### ISSUE THREAD

**Issue by ivanuricardo** [JuliaLang/julia#54103]
Hello,

I currently have a problem with the inv() function in the base LinearAlgebra library. I installed Julia 1.10.2 using the binaries on the (official website)[https://julialang.org/downloads/] and it is a clean install. For reference, `versioninfo()` yields
```
Julia Version 1.10.2

Commit bd47eca2c8a (2024-03-01 10:14 UTC)

Build Info:

  Official https://julialang.org/ release

Platform Info:

  OS: macOS (arm64-apple-darwin22.4.0)

  CPU: 8 × Apple M1 Pro

  WORD_SIZE: 64

  LIBM: libopenlibm

  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)

Threads: 1 default, 0 interactive, 1 GC (on 6 virtual cores)
```

As an example, I try running
```
using LinearAlgebra
A = [1 2 3; 4 5 6; 7 8 9]
inv(A)
```
and I do not obtain an error, where I expect a singularity error. Moreover, I run
```
A * inv(A)
```
and I obtain the matrix `[0 0 0; -4 0 0; -4 0 0]`, where I would instead expect another error.
Let me know if there is anything additional required, or if there is a quick fix.
Thanks.

**Comment by ivanuricardo** [comment]
Update: I was able to replicate the error on a linux machine. Indeed, when I run 
```
A = [1 2 3;4 5 6;7 8 9]
inv(A)
```
I obtain an error. Whereas when I do
```
inv(Number[1 2 3;4 5 6;7 8 9])
```
I do not.

**Comment by StefanKarpinski** [comment]
Not a bug, see: https://discourse.julialang.org/t/inv-not-working-in-mac/113014
