### ISSUE TITLE
Document behavior of `copy!(ys, xs)` when lengths differ

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#54142]
This behavior is not specified.

https://discourse.julialang.org/t/how-is-copy-legal-when-the-size-of-src-and-dst-array-are-different/113151

**Comment by Hero777-tech** [comment]
**@jariji Addressing the Issue:**

-- If the issue is about handling size mismatches, consider using [deepcopy] or creating a new array with similar size before copying.

{ 
x = similar(y)
for i in 1:length(y)
    x[i] = y[i]
end
 }
