### ISSUE TITLE
PkgEval doesn't test latest versions, likely since Pkg doesn't always install latest

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#54150]
Such as for: https://github.com/JuliaGraphics/QML.jl/issues/196

Ideally Pkg would install latest, it doesn't always even if nothing is blocking later versions. I could have made a bug report at Pkg, maybe should have... For now only reporting once, here.

I'm not sure where to report on PkgEvel except here, and we don't want false alams there, it hurts going through real problems. However, ideally we want old versions to work too...

**Comment by DilumAluthge** [comment]
Should probably be opened on https://github.com/JuliaCI/PkgEval.jl instead.

**Comment by KristofferC** [comment]
QML is not compatible with CxxWrap 0.15: https://github.com/JuliaGraphics/QML.jl/blob/8dc510d4d7ebaebc9a18ca1d927b88f6745137d7/Project.toml#L18

**Comment by KristofferC** [comment]
I don't really know what you are talking about but if you have a concrete example that can be replicated now you can post it to Pkg.jl
