### ISSUE TITLE
`isone(::AbstractMatrix)` is UB for offset arrays

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#54163]
1. it uses `size`, which is not guaranteed to be defined for abstract arrays in general according to its doc string

2. it assumes one-based indexing when accessing the elements

**Comment by nsajko** [comment]
Given that multiplication isn't defined among offset arrays, as pointed out at #54162, probably we should just require one-based indexing for now, to prevent out-of-bounds reads.

**Comment by LilithHafner** [comment]
For example, this segfaults:

```julia
julia> isone(OffsetArray([1 0; 0 1], 0, 100000000))

[91199] signal 11 (1): Segmentation fault
in expression starting at REPL[40]:1
Segmentation fault (core dumped)
```
