### ISSUE TITLE
deepcopy should potentially rehash dictionaries

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#54160]
```
julia> mutable struct ConstIdentity
       end

julia> dict = Dict{ConstIdentity, Int64}()
Dict{ConstIdentity, Int64}()

julia> c1 = ConstIdentity()
ConstIdentity()

julia> c2 = ConstIdentity()
ConstIdentity()

julia> dict[c1] = 1
1

julia> dict[c2] = 2
2

julia> haskey(dict, c1)
true

julia> dict2 = deepcopy(dict)
Dict{ConstIdentity, Int64} with 2 entries:
  ConstIdentity() => 1
  ConstIdentity() => 2

julia> haskey(dict2, c1)
false
```

The identity-only-mutables in the keys got copied, so their hash values changed and the resulting dict is broken. I think it would be better if `deepcopy` preserved the data structure here.

**Comment by KristofferC** [comment]
Thinking about deepcopy as serialize + deserialize, this doesn't feel too surprising.

**Comment by Tortar** [comment]
This would be bad from my point of view because that would mean that `dict` and `dict2` wouldn't be independent, which is pretty much what I expect when using `deepcopy`

**Comment by Keno** [comment]
My bad, my reduction was bad. In my actual example, turns out I have an `OrderedDict`, not a `Dict` and the issue was the the dicts are losing their keys. Turns out `Dict` already has the rehashing behavior I want. I'll open an issue on OrderedCollections instead.

**Comment by Keno** [comment]
https://github.com/JuliaCollections/OrderedCollections.jl/issues/115
