### ISSUE TITLE
Support opaque pointers with `llvmcall`?

### ISSUE THREAD

**Issue by chriselrod** [JuliaLang/julia#54188]
```
<string>:9:45: warning: ptr type is only supported in -opaque-pointers mode
  call void @llvm.lifetime.start.p0(i64 32, ptr nonnull %newstruct9.i)
                                            ^
ERROR: Failed to parse LLVM assembly: 
<string>:9:45: error: expected type
  call void @llvm.lifetime.start.p0(i64 32, ptr nonnull %newstruct9.i)
                                            ^        
```
Typed pointer support [was dropped in LLVM 17](https://llvm.org/docs/OpaquePointers.html#version-support).

**Comment by vchuravy** [comment]
An LLVM context can support either opaque pointer or typed pointers, but not both.

**Comment by maleadt** [comment]
You can use opaque pointers if you run with `JULIA_LLVM_ARGS="-opaque-pointers=1"` (which will be the default with LLVM 17).

**Comment by maleadt** [comment]
I guess this can be closed then, as it's already possible. See LLVM.jl for code to detect which mode the default context is in (and thus whether it's legal to use opaque pointer IR in llvmcall).

**Comment by chriselrod** [comment]
Yes, I can confirm it works
```julia

julia> julia_typed_pointers = let
           ir = sprint(io->code_llvm(io, unsafe_load, Tuple{Ptr{Int}}))
           if occursin(r"load i64, i64\* .+, align 1", ir)
               true
           elseif occursin(r"load i64, ptr .+, align 1", ir)
               false
           else
               error("could not determine whether Julia uses typed pointers")
           end
       end
false

julia> Base.libllvm_version, VERSION
(v"15.0.7", v"1.10.2")

julia> ENV["JULIA_LLVM_ARGS"]
"-opaque-pointers=1"
```
https://github.com/maleadt/LLVM.jl/blob/5b03a11753c077ebc0e6b33e765f652b960357df/test/runtests.jl#L13-L22

My issue is that I have a library where I use `LLVM.jl` to load a module that uses opaque pointers and compiling them.
However, the functions themselves cannot be precompiled, because the resulting function is just a `ccall` to an interpolated (i.e. literal) function pointer.

If I could place the IR string inside an `llvmcall` instead, it could be precompiled.

However, that won't be feasible until we switch to LLVM 17, which likely means Julia 1.12.
We don't have separate precompile images based on whether the `ENV` variable is set.
