### ISSUE TITLE
Warning in the Building HTML documentation

### ISSUE THREAD

**Issue by gitboy16** [JuliaLang/julia#54226]
The following warning appears while building the html documentation on master:

```julia
The active manifest file has dependencies that were resolved with a different julia version (1.11.0-DEV). Unexpected behavior may occur.
```
That can be solved by either updating the Manifest.toml or adding a line of code in /doc/make.jl (line 9).

```julia
using Pkg
Pkg.resolve() # Pkg.update() should also work and would probably be better?
Pkg.instantiate()
```
That should avoid any warning going forward? And need to update the Manifest.toml?

Removing the Manifest is not working on my side probably because of my connection:
```
Error: RequestError: HTTP/1.0 200 OK (Operation too slow. Less than 1 bytes/sec transferred the last 20 seconds)
```

**Comment by fredrikekre** [comment]
Since docs are built succesfully on CI it means that the warning are harmful. If you want to run `Pkg.resolve` and make a PR with that that would be good though.

**Comment by gitboy16** [comment]
Thank you for the feedback. I can amend the `Pkg.update()` to `Pkg.resolve()` in the PR I did. There was no need to close my PR, right?
