### ISSUE TITLE
Update main entry-point docs to use lowercase `args`

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#54252]
> I would like to suggest a change to the doc to recommend users define `main` as `main(args)` instead of `main(ARGS)` to clarify the differences between the global var `Core.ARGS` and the function parameter. Defining the `main(ARGS)` is confusing to me if the `ARGS` is just a normal parameter.

_Originally posted by @ctarn in https://github.com/JuliaLang/julia/issues/50974#issuecomment-2077208333_

**Comment by ctarn** [comment]
It would be great if we could finish it before the release of 1.11.0. I am also happy to prepare a PR if needed. I can start it tomorrow since I'm struggling with a report due in 12 hours later...
