### ISSUE TITLE
Julia is incorrectly passing arguments to C on Apple M1

### ISSUE THREAD

**Issue by WardBrian** [JuliaLang/julia#54257]
I have a package which passes a fairly long list of arguments to a C function (24). I noticed today after GitHub Action's runners updated to use Apple M1s by default with macos-14 that one of them (a lowly `int`) was no longer receiving the correct value.

## Reproducible example

(The following is adapted from my existing code, hence the odd names. I'm currently trying to minify it)

Given the following C file:
```c
// file dummy.c

#include <stdio.h>
#include <stddef.h>
#include <stdbool.h>

int very_long(
    const void *model, size_t num_paths, const char *inits,
    unsigned int seed, unsigned int id, double init_radius, int num_draws,
    int max_history_size, double init_alpha, double tol_obj,
    double tol_rel_obj, double tol_grad, double tol_rel_grad, double tol_param,
    int num_iterations, int num_elbo_draws, int num_multi_draws,
    bool calculate_lp, bool psis_resample, int refresh, int num_threads,
    double *out, size_t out_size, void **err)
{
    printf("in C:\t\t%d\n", num_threads);
    fflush(stdout);
    return num_threads;
}

```

and the following Julia file:

```julia
run(`gcc dummy.c -shared -fPIC -o dummy.so`)

dummy = Libc.Libdl.dlopen("./dummy.so")


num_threads = -1
println("in Julia:\t", num_threads)

out = [0.0]
ret = ccall(Libc.Libdl.dlsym(dummy, "very_long"),
    Cint,
    (
        Ptr{Cvoid},
        Csize_t,
        Cstring,
        Cuint,
        Cuint,
        Cdouble,
        Cint,
        Cint,
        Cdouble,
        Cdouble,
        Cdouble,
        Cdouble,
        Cdouble,
        Cdouble,
        Cint,
        Cint,
        Cint,
        Cint, # really bool
        Cint, # really bool
        Cint,
        Cint,
        Ref{Cdouble},
        Csize_t,
        Ref{Ptr{Cvoid}},
    ),
    C_NULL,
    1,
    "dummy",
    1234,
    1,
    2.0,
    1000,
    5,
    0.1,
    0.1,
    0.1,
    0.1,
    0.1,
    0.1,
    1000,
    1000,
    1000,
    Int32(true),
    Int32(false),
    0,
    num_threads, # THIS IS THE ONE THAT GETS PRINTED
    out,
    length(out),
    C_NULL,
)

println("in Julia:\t", ret)

```

I would expect the following output:

```
in Julia:	-1
in C:		-1
in Julia:	-1
```

And indeed this is what I get locally on Linux and on Intel-Based Macs. However on the M1s, it prints

```
in Julia:	-1
in C:		0
in Julia:	0
```

I have set up a simple github repo with an action that shows this: 
https://github.com/WardBrian/julia-macos-test/actions/runs/8839471421/job/24272888529#logs

**Comment by WardBrian** [comment]
I think this may be a result of using `Cint` for my couple `bool` parameters, since Julia does not have a `Cbool` type. I'm guessing this isn't ABI-compatible on M1 but is on intel?

**Comment by giordano** [comment]
Use `Bool` instead of `Cint`?  With that I get
```
in Julia:	-1
in C:		-1
in Julia:	-1
```

Also, for what is worth, I personally find
```julia
ret = @ccall "./dummy.so".very_long(
    C_NULL::Ptr{Cvoid},
    1::Csize_t,
    "dummy"::Cstring,
    1234::Cuint,
    1::Cuint,
    2.0::Cdouble,
    1000::Cint,
    5::Cint,
    0.1::Cdouble,
    0.1::Cdouble,
    0.1::Cdouble,
    0.1::Cdouble,
    0.1::Cdouble,
    0.1::Cdouble,
    1000::Cint,
    1000::Cint,
    1000::Cint,
    true::Bool,  # really bool
    false::Bool, # really bool
    0::Cint,
    num_threads::Cint, # THIS IS THE ONE THAT GETS PRINTED
    out::Ref{Cdouble},
    length(out)::Csize_t,
    C_NULL::Ref{Ptr{Cvoid}},
)::Cint
```
much more readable than your `ccall` (also, you don't need to dlopen the library and call dlsym on it, not even with the `ccall` syntax)

**Comment by WardBrian** [comment]
`Bool` is assuming `sizeof(bool) == 1` which isn't required by the C or C++ specification, but will probably work for the platforms I care about.

**Comment by giordano** [comment]
> Bool is assuming sizeof(bool) == 1 which isn't required by the C or C++ specification,

Also `Cint` is assuming some size, and on macOS, both [x86_64](https://github.com/giordano/julia-macos-test/actions/runs/8840071454/job/24274716322#step:4:7) and [aarch64](https://github.com/giordano/julia-macos-test/actions/runs/8840071454/job/24274716050#step:4:7), `sizeof(bool) == 1` , so `Cint` is definitely wrong.

**Comment by WardBrian** [comment]
Yeah, it would be nice if there was a `Cbool` which was platform-defined right size. 

I agree it's somewhat surprising that `Cint` works on x86_64-based macOSes, not to mention Windows and Linux
I think the reason I got away with this for a while is I mostly have functions that are small enough to pass things in registers, where a bool will fill a register the same as an int

**Comment by giordano** [comment]
The problem is that these types are really compiler-dependent.  All the `C...` aliases are best guesses, they aren't really guaranteed to be always correct.

**Comment by gbaraldi** [comment]
`bool` in C is only defined in C23 so we would need that to figure it out. :\

**Comment by vtjnash** [comment]
This seems a neat list, which shows that even a single C compiler does not always get it consistently right: https://github.com/MaulingMonkey/abibool

**Comment by gbaraldi** [comment]
Using it is fine, it's just that until C figures it's stuff out julia won't be able to help you too much I don't think.

**Comment by WardBrian** [comment]
> C figures it's stuff out

Probably waiting forever, then 😉 

I think this can be closed now, it's an odd difference between the architectures but I was also doing odd things
