### ISSUE TITLE
What is the recommended value of JULIA_CPU_TARGET on macOS?

### ISSUE THREAD

**Issue by fxcoudert** [JuliaLang/julia#54319]
As part of updating our Julia build in Homebrew (https://github.com/Homebrew/homebrew-core/pull/170476), a contributor suggested tweaking the value of `JULIA_CPU_TARGET` for our build. I must admit I have no idea what the right value is, but I do not believe we (Homebrew) should be in the business of choosing this ourselves. So I'd like to ask: do you (Julia) document somewhere was values of `JULIA_CPU_TARGET` are used for official binaries? If not, could you kindly consider it?

We would then simply check and make sure we ship the same configurations as you do, because you sure know best 😄

**Comment by fredrikekre** [comment]
https://github.com/JuliaCI/julia-buildkite/blob/ea50eb719242bc3e844227a2ebf54a49d308bafc/utilities/build_envs.sh#L20-L82

**Comment by fxcoudert** [comment]
Thanks @fredrikekre!

Looking at the aarch64 case, it appears to be shared between macOS and other OSes (I suppose aarch64-linux):

```
            # Absolute base aarch64 feature set
            "generic"
            # Cortex A57, Example: NVIDIA Jetson TX1, Jetson Nano
            "cortex-a57"
            # Cavium ThunderX2T99, a common server architecture
            "thunderx2t99"
            # NVidia Carmel, e.g. Jetson AGX Xavier; serves as a baseline for later architectures
            "carmel,clone_all"
            # Apple M1
            "apple-m1,base(3)"
            # Vector-length-agnostic common denominator between Neoverse V1 and V2, recent Arm server architectures
            "neoverse-512tvb,base(3)"
```

Given that 1. macOS does not support anything with fewer features than Apple M1, 2. its processors don't really align with Neoverse, am I right that we could simplify it (for macOS builds) to:

```
            # Absolute base aarch64 feature set
            "generic"
            # Apple M1
            "apple-m1,clone_all"
```

without risk?

**Comment by giordano** [comment]
Yes, that (in the form of `generic;apple-m1,clone_all`) should be safe on aarch64-apple-darwin machines. The main risk is having inefficient code baked in the sysimage, but the `apple-m1` target should cover all the systems you care about, and the `generic` target ensures a safe fallback for all other cases.

**Comment by fxcoudert** [comment]
Thanks. I appreciate the help!
