### ISSUE TITLE
Energy saving advice: Only trigger Continuous Integration manually.

### ISSUE THREAD

**Issue by NeroBlackstone** [JuliaLang/julia#54317]
I noticed that Julia's continuous integration is automatically triggered after every code commit, and it lasts for a staggering 6 hours! 

However, some changes do not require immediate testing. Can we set the triggering of CI to manual, or provide a command to temporarily block CI.

Of course, I don't know if this is consistent with the actual development of this project. But I hope every open source project can practice green software development. Feel free to close this issue.

**Comment by Keno** [comment]
The cost (both time and energy) of somebody forgetting to CI and committing something bad would likely be much worse. There is some support for explicit `[skip ci]` (but needs improvement https://github.com/JuliaCI/julia-buildkite/issues/340). Regardless, this is likely the wrong place to look. All of Julia CI is a few kW of power at most. Programs written in Julia are likely using MW scale power continuously (and even worse for programs not written in Julia). Slowing down julia development, even marginally, to save a few kwh of energy is likely to be highly net-negative in terms of total energy use.
