### ISSUE TITLE
Documentation section on Environment Variables

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#5432]
It would be useful to have a doc section on envvars, seeing as we're starting to get more of them (that are quite useful as well!)  Things like `JULIA_PKGDIR`, `JULIA_LOAD_PATH` (once #5425 is merged), `JULIA_HOME`, `JULIA_CPU_CORES`, `JULIA_EDITOR`, etc...

**Comment by FRidh** [comment]
Why is this issue closed? The docs don't seem to include such a section.
