### ISSUE TITLE
Parser warning for `using EllipsisNotation: (..) as …`: “parentheses are not required here”

### ISSUE THREAD

**Issue by Socob** [JuliaLang/julia#54351]
Running the following file (which intentionally has invalid syntax at the end to trigger the syntax warning, which doesn’t seem to appear otherwise?):
>     using EllipsisNotation: .. as …
>     
>     (

gives a warning on the line `using EllipsisNotation: .. as …` (in addition to the syntax error):
>     ERROR: LoadError: ParseError:
>     # Warning @ ~/tmp.jl:1:25
>     using EllipsisNotation: (..) as …
>     #                       └──┘ ── parentheses are not required here
>     # Error @ ~/tmp.jl:3:3
>     
>     (
>     #
>     └ ── Expected `)`
>     Stacktrace:
>      [1] top-level scope
>        @ ~/tmp/tmp.jl:3
>     in expression starting at ~/tmp.jl:3

However, the parentheses do seem to be required, as evidenced by what happens when omitting them:
>     using EllipsisNotation: .. as …

Resulting error:
>     ERROR: LoadError: ParseError:
>     # Warning @ ~/tmp.jl:1:27
>     using EllipsisNotation: .. as …
>     #                         ╙ ── space between dots in import path
>     # Error @ ~/tmp.jl:2:2
>     using EllipsisNotation: .. as …
>     
>     #└ ── premature end of input
>     Stacktrace:
>      [1] top-level scope
>        @ ~/tmp/tmp.jl:2
>     in expression starting at ~/tmp.jl:2

---

1. The output of `versioninfo()`:
>     Julia Version 1.10.3
>     Commit 0b4590a5507 (2024-04-30 10:59 UTC)
>     Build Info:
>       Official https://julialang.org/ release
>     Platform Info:
>       OS: Linux (x86_64-linux-gnu)
>       CPU: 16 × AMD Ryzen 7 4800H with Radeon Graphics
>       WORD_SIZE: 64
>       LIBM: libopenlibm
>       LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
>     Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)

2. How you installed Julia: juliaup
3. A minimal working example (MWE), also known as a minimum reproducible example: see above

**Comment by ericphanson** [comment]
Xref https://github.com/JuliaLang/JuliaSyntax.jl/issues/350
