### ISSUE TITLE
`String(v::Memory{UInt8})` doesn't make a copy

### ISSUE THREAD

**Issue by nhz2** [JuliaLang/julia#54369]
The docstring of `String` says:

> To avoid truncation
  of Vector{UInt8} data, use String(copy(v)); for other AbstractVector types,
  String(v) already makes a copy.

Since `Memory` is an `AbstractVector`, `String` should make a copy. However, it doesn't look like this is happening in:

https://github.com/JuliaLang/julia/blob/9d8e0e7016ad64890f81b1fd93c1d46de9588a02/base/strings/string.jl#L67-L71

```julia
julia> v = Memory{UInt8}(undef, 10);

julia> fill!(v, 0x01);

julia> String(v)
"\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01"

julia> v
0-element Memory{UInt8}
```

Maybe the current `String(v::Memory{UInt8})` method could be renamed to something like `take_string!` to make it clear that it can mutate `v`.

**Comment by jakobnissen** [comment]
I think it's pretty much agreed that the truncating behaviour of `String(::Vector{UInt8})` was a design mistake: https://github.com/JuliaLang/julia/issues/32528. It'd be unfortunate to repeat this with Memory, given that there is still time before 1.11 is released.
