### ISSUE TITLE
REPL stdout output should not be highlighted in code examples

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#54399]
For example from `?sum`:
![image](https://github.com/JuliaLang/julia/assets/11698744/d8c3b706-33f8-4b4c-9717-8be268bdc69b)

**Comment by tecosaur** [comment]
I have code to handle this properly, but Jameson (softly) veto'd it with the original PR: https://github.com/JuliaLang/julia/pull/51928#discussion_r1483598716.

I'll can PR this separately fairly shortly, but I might try to bump JuliaSyntaxHighlighting first.
