### ISSUE TITLE
`iterate` returns tuple for non-existent state

### ISSUE THREAD

**Issue by Tortar** [JuliaLang/julia#54455]
consider this:

```julia
julia> itr = 1:1
1:1

julia> iterate(itr)
(1, 1)

julia> iterate(itr, 1)

julia> iterate(itr, 2)
(3, 3)
```

It seems logical that instead `iterate(itr, 2)` should return `nothing` instead, or maybe error.

**Comment by KristofferC** [comment]
What `iterate` does after `nothing` has been returned is more or less arbitrary.

**Comment by Tortar** [comment]
mmh, ok but maybe returning `nothing` could a bit better anyway? It would be easy in this case

```julia
function iterate(r::OrdinalRange{T}, i) where {T}
    @inline
    i >= last(r) && return nothing # >= instead of ==
    next = convert(T, i + step(r))
    (next, next)
end
```

**Comment by Tortar** [comment]
I think that anyway the docstring should say that this happens

**Comment by Tortar** [comment]
Actually the previous implementation wasn't totally correct because of decreasing ranges, this would return `nothing` whenever the state is outside the range:

```julia
function iterate(r::OrdinalRange{T}, i) where {T}
    @inline
    rf, rl = first(r), last(r)
    rf < rl && (i < rf || i >= rl) && return nothing
    rf >= rl && (i <= rl || i > rf) && return nothing
    next = convert(T, i + step(r))
    (next, next)
end
```

I would have assumed that this is more costly but I see on 1.10 and 1.11 this:

```julia
julia> function f(x)
           s = 0
           for i in 1:x
               s += rand() < 0.5 ? 1 : 2
           end
       end
f (generic function with 1 method)

julia> @btime f(1000) # before
  581.742 ns (0 allocations: 0 bytes)

julia> @btime f(1000) # after
  489.426 ns (0 allocations: 0 bytes)
```

which indicates the opposite, does someone know why?

**Comment by Tortar** [comment]
ok sorry I wasn't returning `s`, now I see same performance

**Comment by Tortar** [comment]
but it is fighting a losing battle trying to make this safer without compromising performance, e.g. still a step greater than 1 should be taken care of
