### ISSUE TITLE
suboptimal return type inference for `Base.setindex`

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#54462]
```julia-repl
julia> Core.Compiler.return_type(Base.setindex, Tuple{Tuple,Nothing,Int}) <: Tuple
false

julia> versioninfo()
Julia Version 1.12.0-DEV.495
Commit 3c966a5107a (2024-05-09 11:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-17.0.6 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

FWIW the type inference for `Base.setindex` was better on v1.7.3.

A quick fix, for `Base.setindex` at least, is adding a `::Tuple` type assertion for the `Base._setindex` return value.

However, I'm not sure why does the inference fail, actually? We do have:

```julia
Core.Compiler.return_type(ntuple, Tuple{Any,Val}) <: Tuple
```

`Cthulhu.descend` shows that, in `Base._setindex`, the return value gets inferred as `Any` even though the `Val{N}()` gets inferred as `Val`. Weird.

**Comment by martinholters** [comment]
```julia
julia> methods(ntuple, Tuple{Any,Val})
# 5 methods for generic function "ntuple" from Base:
 [1] ntuple(f, ::Val{3})
     @ ntuple.jl:50
 [2] ntuple(f, ::Val{2})
     @ ntuple.jl:49
 [3] ntuple(f, ::Val{1})
     @ ntuple.jl:48
 [4] ntuple(f, ::Val{0})
     @ ntuple.jl:47
 [5] ntuple(f::F, ::Val{N}) where {F, N}
     @ ntuple.jl:69
```
Five methods is too much for inference which therefore bails out. Which is quite unfortunate. Maybe it's worth renaming those to `_ntuple` and adding `ntuple(f::F, ::Val{N}) where {F,N} = _ntuple(f, Val{N}())::Tuple{Vararg{Any,N}}`?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/54528 is an alternative to that

**Comment by martinholters** [comment]
:+1: Yes, that looks like good idea to me.
