### ISSUE TITLE
`@doc` (`MD` object) doesn't print with horizontal bars between methods, which can mislead the reader.

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#54486]
Consider this docstring:
<img width="1652" alt="Screenshot 2024-05-15 at 5 06 11 PM" src="https://github.com/JuliaLang/julia/assets/1582097/df22f81d-beea-4784-8273-e45bdc5c221e">

This **very much** appears to be _one docstring_ for `rem(x, ::Type)`, which has two consecutive `Examples` sections, and some text in between.

However, what's _actually_ happening is that the end of the first docstring is a codeblock, and the _start_ of the second method's docstring is also a codeblock, so these appear to run together. This is a common occurrence in docstrings, so I imagine this has confused others as well.

Compare that to how the docstring is printed via help (`?`):
![Screenshot 2024-05-10 at 9 29 47 AM](https://github.com/JuliaLang/julia/assets/1582097/4616b2ff-5ecb-459e-b55e-471d6c532ae2)

Now, you can see that this is actually 3 separate methods.

I believe that the `show(::IO, ::MIME"text/plain", ::MD)` function simply needs to be updated to introduce the same `------`s that we have in `?` help.

**Comment by xlxs4** [comment]
There's [`REPL.insert_hlines`](https://github.com/JuliaLang/julia/blob/0fd1f04dc7d4b905b0172b7130e9b1beab9bc4c9/stdlib/REPL/src/docview.jl#L82), but `REPL` depends on `Markdown`. Should I move `insert_hlines` somewhere where both `REPL` and `Markdown` can use it?
