### ISSUE TITLE
safety consideration for operations with incompletely initialized types

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#54543]
For example, when declaring a type with a field whose type  has not yet been defined, an error occurs when trying to construct the type, but the type itself is defined and may be referenced in the subsequent session.
In such cases, performing basic operations like `getfield` or `fieldtype` can cause a segfault, and the `tfunc` that models these operations can also segfault.

For instance, consider the following situation:
```julia
julia> struct A
           b::B
       end
ERROR: UndefVarError: `B` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[14]:1

julia> code_typed((A,)) do a
           a.b
       end
Assertion failed: (n > 0 && "expected empty case to be handled during construction"), function jl_compute_fieldtypes, file jltypes.c, line 2692.

[55309] signal 6: Abort trap: 6
in expression starting at REPL[2]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 5286346 (Pool: 5285851; Big: 495); GC: 6
[1]    55309 abort
```

Should this behavior be kept, or show we try to keep the session alive at least without segfaulting it? If we choose the latter, we need to change the assertions in functions like `jl_compute_fieldtypes` to handleable errors.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/53754

**Comment by aviatesk** [comment]
Yes, exactly, this is the same issue. Let's focus on that. Thanks for your help.
