### ISSUE TITLE
Binaries for prereleases of patch versions

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/julia#54633]
I see on @KristofferC's 1.10.4 prerelease announcement that

> Binaries are not available for prereleases of patch versions at this time

I was just wondering if this could be changed?

I would be eager to help test the prerelease over all of my Julia packages, but it not practical for me to modify all of the GitHub actions in all 8 repositories every prerelease. If there was a binary available via Juliaup, I could do all my testing locally with a single script, and be able to report any bugs that come up to core devs.

Perhaps there is some constraint here that makes this impractical? In which case feel free to close

**Comment by giordano** [comment]
> If there was a binary available via Juliaup, I could do all my testing locally with a single script, and be able to report any bugs that come up to core devs.

Not in juliaup, but you can download the binaries from https://buildkite.com/julialang/julia-release-1-dot-10/builds/318

**Comment by MilesCranmer** [comment]
Thanks. Would it be possible for you to move this issue to the juliaup repo?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/juliaup/issues/842

**Comment by MilesCranmer** [comment]
Thanks
