### ISSUE TITLE
`Base.isconcretetype` incorrect for `Type{T}`?

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/julia#54646]
I saw the following weird behaviour on https://discourse.julialang.org/t/ann-dispatchdoctor-jl-offers-you-a-prescription-for-type-stability/114837/35

```julia
julia> Base.isconcretetype(Type{Float32})
false
```

I think this could be a bug? The definition states:

> Determine whether type `T` is a concrete type, meaning it could have direct instances (values `x` such that `typeof(x) === T`).

However, `typeof(T)` returns a `DataType` rather than `Type{Float32}`. But the docstring for `DataType` says `DataType <: Type{T}`. So I'm confused.

If this indeed a bug I think it's because the `@nospecialize` here was implemented without expecting such an input:

```julia
isconcretetype(@nospecialize(t)) = (@_total_meta; isa(t, DataType) && (t.flags & 0x0002) == 0x0002)
```

The solution would be to add a

```julia
isconcretetype(::Type{Type{T}}) where {T} = isconcretetype(T)
```

whose recursion would automatically deal with `Type{Type{Float32}}` and so on.

But obviously this would be a massive breaking change so wouldn't be possible. So I guess I'm just looking for some clarification :)

**Comment by martinholters** [comment]
The subtyping relationship is `Type{Float32} <: DataType <: Type`, and as you've discovered yourself, `typeof(Float32)==DataType`, so neither `Type{Float32}` nor `Type` are concrete, but `DataType` is.

What's confusing indeed is the `DataType <: Type{T}` in the docstring. While `DataType <: Type{T} where T` is true (and just a more verbose form of `DataType <: Type`), for any actual `T`,  `DataType <: Type{T}` does not hold.

**Comment by MilesCranmer** [comment]
Got it, thanks.
