### ISSUE TITLE
`else` isn't documented in `try` block docstring

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#54686]
https://docs.julialang.org/en/v1/base/base/#try

`else` was added in https://github.com/JuliaLang/julia/pull/42211

**Comment by vchuravy** [comment]
x-ref: #54269

**Comment by 95481** [comment]
hey @IanButterworth can I work on this??

**Comment by IanButterworth** [comment]
Yes and you don't need to ask to work on issues if no one is assigned to them already :)
