### ISSUE TITLE
Iterators.flatten throws an exception on missing values

### ISSUE THREAD

**Issue by g-gundam** [JuliaLang/julia#54682]
I'm working with vectors that contain values of type `Missing`, `Float64`, or `Vector{Float64}`.  I'm trying to flatten these vectors, but when I encounter a `missing` value, `Iterators.flatten` throws an exception.

## Code
```julia
Iterators.flatten([1.0, missing, [3.0, 4.0]]) |> collect
```

## Expected Result
```julia
[1.0, missing, 3.0, 4.0]
```

## Actual Result
```
ERROR: MethodError: no method matching iterate(::Missing)

Closest candidates are:
  iterate(::WeakRefStrings.PosLenString)
   @ WeakRefStrings ~/.julia/packages/WeakRefStrings/31nkb/src/poslenstrings.jl:325
  iterate(::WeakRefStrings.PosLenString, ::Int64)
   @ WeakRefStrings ~/.julia/packages/WeakRefStrings/31nkb/src/poslenstrings.jl:325
  iterate(::Base.AsyncGenerator, ::Base.AsyncGeneratorState)
   @ Base asyncmap.jl:362
  ...

Stacktrace:
 [1] iterate
   @ ./iterators.jl:1202 [inlined]
 [2] grow_to!(dest::Vector{Int64}, itr::Base.Iterators.Flatten{Vector{Any}}, st::Tuple{Int64, Int64, Nothing})
   @ Base ./array.jl:929
 [3] grow_to!(dest::Vector{Any}, itr::Base.Iterators.Flatten{Vector{Any}})
   @ Base ./array.jl:911
 [4] _collect
   @ ./array.jl:811 [inlined]
 [5] collect
   @ ./array.jl:759 [inlined]
 [6] |>(x::Base.Iterators.Flatten{Vector{Any}}, f::typeof(collect))
   @ Base ./operators.jl:917
 [7] top-level scope
   @ REPL[17]:1

```
I wasn't sure if this was a bug or not, but someone more experienced than me [thought it was a bug](https://julialang.zulipchat.com/#narrow/stream/274208-helpdesk-.28published.29/topic/.E2.9C.94.20Flattening.20Vectors.20with.20Missing.20Values).

### versioninfo()
```
Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 4800U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
Environment:
  JULIA_ERROR_COLOR = red
```
### installation method
juliaup

**Comment by jariji** [comment]
`flatten([[missing]])` should go to `[missing]`, but it's not clear to me what `flatten([missing])` would do: how many values should it expand to? I think it's ambiguous and so error is the best option.

**Comment by jakobnissen** [comment]
The behaviour is semantically correct. Flatten takes an iterator of iterators, and missing is not an iterator. It happens to work for floats, because they unfortunately implement iterate.

**Comment by g-gundam** [comment]
After further [discussion](https://julialang.zulipchat.com/#narrow/stream/274208-helpdesk-.28published.29/topic/.E2.9C.94.20Flattening.20Vectors.20with.20Missing.20Values) over at the Julia zulipchat, the consensus seems to be that this isn't a bug.  I'm preemptively closing this issue.
