### ISSUE TITLE
Filenames on Windows in coverage output are missing drive letter

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#54697]
The filenames that are written into the `.info` file are of the form:
```
\Users\david\source\julia-vscode\scripts\packages\JuliaInterpreter\src\interpret.jl
```
They are missing the drive letter.

Pinging @MilesCranmer in the hopes that he might take an interest and knows how to fix this :) This is another blocker for the VS Code coverage integration for test items.

**Comment by davidanthoff** [comment]
Haha, well, the problem is I am on Windows, so I have no motivation to do a MacOS/Linux only feature ;)

**Comment by davidanthoff** [comment]
@vtjnash any chance you might be able to take a look at this? If this gets fixed for 1.12 it would unlock some really nice features in the VS Code extension.

**Comment by vtjnash** [comment]
I haven't the slightest idea about this, as we have a test here that this should be printing the realpath:
https://github.com/JuliaLang/julia/blob/9d8ecaa899d5baf58e5cd75a5ba44a8bf4135c62/test/cmdlineargs.jl#L472-L473

**Comment by vtjnash** [comment]
I rather suspect this is a bug in your parser library, since it doesn't appear to understand how to correctly parse fields with `:` in them: https://github.com/friedemannsommer/lcov-parser/blame/8a980f27039fd41ba6188d37888b1ec9331ec04d/src/parser.ts#L229-L230

**Comment by davidanthoff** [comment]
Yes, you are right! Sorry for the noise here, and thanks for figuring that out. I filed a bug report over at https://github.com/friedemannsommer/lcov-parser/issues/140.
