### ISSUE TITLE
Proposed Negation Default Broadcast Behavior

### ISSUE THREAD

**Issue by pixelplum** [JuliaLang/julia#54694]
I'm proposing a behavior/syntax change for the `!` and potentially `~` unary operators.

I find the syntax of `.![true false true]` to be quite unintuitive and disjoint with other operators like unary minus, so I am proposing to adopt the same broadcast rule as unary minus, which could be simply implemented as:

```diff --git a/base/abstractarraymath.jl b/base/abstractarraymath.jl
index a9efc2b87b..234de4fba5 100644
--- a/base/abstractarraymath.jl
+++ b/base/abstractarraymath.jl
@@ -217,6 +217,8 @@ julia> reim(fill(2 - im))
 reim(A::AbstractArray)

 -(A::AbstractArray) = broadcast_preserving_zero_d(-, A)
+!(A::AbstractArray) = broadcast_preserving_zero_d(!, A)
+~(A::AbstractArray) = broadcast_preserving_zero_d(~, A)

 +(x::AbstractArray{<:Number}) = x
 *(x::AbstractArray{<:Number,2}) = x
```

Which would enable the following syntax...
```julia
julia> ![true false true]
1×3 BitMatrix:
 0  1  0
```
...and...
```julia
julia> ~[1 2 3]
1×3 Matrix{Int64}:
 -2  -3  -4
```

I'd like to hear if there was prior motivation for disallowing the default broadcast behavior for these operators, and if the Julia org would be open to a PR. The `!` operator may need to be handled slightly differently as it doesn't do type promotion like unary minus, and is restricted to `Bool` arrays, and I'm sure there is other subtlety I'm not seeing.

~pixelplum

**Comment by Keno** [comment]
I think the key issue here is that things like `+` and `-` make sense as the unary operation on the matrix itself as an algebraic object. The fact that it happens to match broadcast is somewhat incidental. One could perhaps make a similar case for `~`, but the case is much less strong for `!`. Overall, I think this is probably not a good idea.

**Comment by Keno** [comment]
Another issue with `!` is that it also has functional behavior, so for things that are both array-like and function-like, it would be confusing that it attaches to the latter.

**Comment by pixelplum** [comment]
Ok! No complaints from me, will mark this as closed.

Could you perhaps provide more insight into why `!.[true false true]` isn't valid syntax? I guess this is what tripped me up in the first place. The function `!()` couldn't be broadcasted by the usual dot notation for functions, and I was at a loss of what to try next.

My only wish would be consistency and this didn't match the unary `-x` or the normal function broadcast case `f.(x)`

**Comment by Keno** [comment]
> Could you perhaps provide more insight into why `!.[true false true]` isn't valid syntax?

There's a conflict between field access, unary operator and broadcast syntax. You can use parentheses to disambiguate:
```
julia> (!).([true false true])
1×3 BitMatrix:
 0  1  0
```
