### ISSUE TITLE
Dotplot not overlaying violin plot

### ISSUE THREAD

**Issue by tidalDisruptionEvent** [JuliaLang/julia#54695]
When attempting to create a violin plot with the individual data points overlayed over the violin plot the ! operator does not result in overlay. Namely, if one uses Plots.violin(data) and then dotplot!(data) the plots are side-by-die. 

See issue on the discourse: **[Violin and Dotplot not overlaying](https://discourse.julialang.org/t/placing-dotplot-over-violin-plot/115253)**

<img width="600" alt="Screenshot 2024-06-05 at 3 41 02 PM" src="https://github.com/JuliaLang/julia/assets/125692071/3909890c-24d7-4742-a182-e7651e3bee65">

**Comment by oscardssmith** [comment]
This issue belongs on the Plots.jl repository not the Julia repository.
