### ISSUE TITLE
`factorize(<:AbstractMatrix)` prefers `Cholesky` but `factorize(<:Hermitian)` prefers `BunchKaufman`

### ISSUE THREAD

**Issue by mikmoore** [JuliaLang/julia#54717]
Julia v1.10.3

```julia-repl
julia> x = rand(3,3);

julia> factorize(x'*x) |> typeof
Cholesky{Float64, Matrix{Float64}}

julia> factorize(Hermitian(x'*x)) |> typeof
BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
```

The first thing `factorize(x'*x)` does is determine that `x'*x` is structurally hermitian. Once it does, it attempts `cholesky`. If that fails, it calls `factorize(Hermitian(x'*x))`.

But when `factorize(Hermitian(x'*x))` is called (either directly or after determining that `x'*x` is structurally hermitian), `cholesky` is never attempted. Instead, it attempts `Diagonal`, then `bunchkaufman` or `lu` depending on the `eltype`.

This is at odds with `@doc factorize`, which says `cholesky` is favored for positive definite matrices (which are necessarily `ishermitian`, if not `Hermitian`).

Ignoring the documentation discrepancy, it seems that there shouldn't be this distinction. Either `cholesky` should be preferred for all `ishermitian` matrices or we should never try at all. The fact that the `factorize(<:Hermitian)` method does *not* attempt `cholesky` makes me think someone thought about this and preferred "never cholesky".

However, `bunchkaufman` is 1.5-2x slower than `cholesky` (default OpenBLAS, sizes $3 \times 3$ to $500 \times 500$) and appears to even be somewhat slower than `lu` (1.0-1.5x). It seems that `bunchkaufman` is either overrated or has some low-hanging performance improvements available.

`cholesky` has the potential to be faster, but work is wasted if it fails. `lu` is still faster than `bunchkaufman` (but algorithmically this seems backwards, so *could* reverse in the future), but forgets the hermitian structure. I'm not sure what should be preferred, but I think a consistent preference would be better than the current situation. I guess my dream world would have `bunchkaufman` nearly as fast as `cholesky` and we would just use that (since `cholesky` can still fail for many nonsingular matrices).

**Comment by dkarrasch** [comment]
Concerning `\`, not even trying `Cholesky` has been noted and appreciated in https://doi.org/10.1007/978-3-319-74222-9: section B.19 on page 115. The "problem" is that feasibility of `cholesky` is not encoded in the (Hermitian) type, so I agree with the reference that `cholesky` should be called by the user explicitly when they have structural knowledge that the matrix _is_ s.p.d. So I'd vote for removing the `cholesky` trial in `factorize(::AbstractMatrix)` and just call `factorize(Hermitian(A))` in that branch.

**Comment by dkarrasch** [comment]
Also, quoting that reference:

> As it were, this method (Bunch-Kaufman) has the same complexity of m3 /3 flop as the Cholesky decomposition, but
for s.p.d. matrices it is less amenable to optimized BLAS and therefore slower due to the overhead of pivoting.
