### ISSUE TITLE
Julia Rejecting this target due to use of runtime-disabled feature

### ISSUE THREAD

**Issue by uncomfyhalomacro** [JuliaLang/julia#54727]
Running Julia on openSUSE Tumbleweed raises this error
```
ERROR: Unable to find compatible target in cached code image.
Target 0 (znver3): Rejecting this target due to use of runtime-disabled features
```

Possibly related to #54482

## Affected versions in openSUSE Tumbleweed
OpenBuildService Science Repo: 1.10.4
OpenBUildService Factory and Tumbleweed Repo: 1.10.3

A recent snapshot rebuild has happened therefore all packages in the distribution were rebuilt.

**Comment by vchuravy** [comment]
Is there a downstream issue with OBS? It looks like you are one of the maintainers?

This looks like the build didn't pick up your `JULIA_CPU_TARGETS="generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)"` flag and instead used `native` from the build system

**Comment by vchuravy** [comment]
And that's because the build flag is `JULIA_CPU_TARGET` without the extra s

**Comment by uncomfyhalomacro** [comment]
oh! i didnt notice. someone asked me to put merge his changes but i probably missed that he missed an S. going to close this. thank you!
