### ISSUE TITLE
`view(::Memory, ::UnitRange)` should not create a `Vector`

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#54768]
I wasn't around to complain about https://github.com/JuliaLang/julia/pull/53896, but I think that PR was a bad idea. That PR made `view` worse at doing the regular job that `view` is used for, and repurposes it for a different job. 

1) This now makes it so that generic functions that call
```julia
view(::AbstractVector, ::UnitRange)
```
might end up doing an unnecessary allocation depending on if you get a `Memory` (because `Vector` is a mutable struct). This means that any generic function that takes a `view` at every iteration of a loop is in danger of accidentally performing `N` allocations if it is passed a `Memory`. For example:

```julia
function f(v)
    s = 0.0
    for i ∈ firstindex(v):lastindex(v)-1
        s += sum(@view v[i:i+1])
    end
    s
end;

julia> let m = Memory{Float64}(undef, 10000) .= 1
           @btime f($m)
       end
  43.232 μs (9999 allocations: 312.47 KiB)
19998.0

julia> let v = Vector{Float64}(undef, 10000) .= 1
           @btime f($v)
       end
  10.129 μs (0 allocations: 0 bytes)
19998.0
```

2) If you actually wanted a regular `SubArray{<:Memory}`, you cannot use `view` for that and instead need to call the `SubArray` constructor directly

3) The only reason you'd want this to return a `Vector` instead of a `SubArray` is if you wanted to `push!` or otherwise resize the result, but it's generally not good practice to encourage people to write `push!(view(m, idxs), x)` because that'd normally error.

_______________

I propose we remove this method before 1.11 drops.

**Comment by KristofferC** [comment]
So what to do? Revert the `wrap` -> `view` PR and the `wrap` feature PR?

**Comment by oscardssmith** [comment]
I think for 1.11, a good enough solution would be to revert `wrap`->`view` and unexport `wrap`. We do need an internal way of doing this, but we don't need a public interface.

**Comment by KristofferC** [comment]
> We do need an internal way of doing this

We do? Julia seemed to work fine before https://github.com/JuliaLang/julia/pull/52049.

**Comment by jakobnissen** [comment]
Reverting sounds good to me for now. Also much less risky compared to adding a new function this late in the 1.11 release cycle.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/53192 makes a straight-up revert convoluted so I had to resort to just unexporting it in the end.

**Comment by JeffBezanson** [comment]
Looks like the decision has been made; removing triage tag.
