### ISSUE TITLE
SEO problem with Julia documentation?

### ISSUE THREAD

**Issue by droodman** [JuliaLang/julia#54776]
When I Google "julia iterators accumulate" [the official, current documentation](https://docs.julialang.org/en/v1/base/iterators/) for Iterators.accumulate does not appear. Is this an SEO (search engine optimization) problem?

![image](https://github.com/JuliaLang/julia/assets/25406697/a07826ca-3d65-49e6-ad64-92e11f163ed1)

**Comment by Keno** [comment]
I can reproduce the issue, but I don't see any errors in the google search console:

![Screenshot 2024-06-12 at 8 42 47 PM](https://github.com/JuliaLang/julia/assets/1291671/242a86c1-edd8-43a1-9f65-19f78b9fc0c7)

**Comment by droodman** [comment]
(This may not be helpful, but FYI Googling "julia iterators accumulate -site:https://web.mit.edu" has the same problem....)

**Comment by evetion** [comment]
This works fine from the Netherlands, official documentation is the first hit.

**Comment by vchuravy** [comment]
@wsmoses might be able to look into who this website belongs too

**Comment by wsmoses** [comment]
I've looked up the owner and forwarded details to @vchuravy

**Comment by vchuravy** [comment]
I reached out to the person in question.

**Comment by wsmoses** [comment]
This should now be resolved.

**Comment by KristofferC** [comment]
Google found this one now https://gensoft.pasteur.fr/docs/julia/1.4.1/base/iterators.html (showing up as the second suggesion). No idea what that side is.
