### ISSUE TITLE
Feature Request: Add Syntactic Sugar for Compile-Time Constants in Function Definitions

### ISSUE THREAD

**Issue by kylincaster** [JuliaLang/julia#54797]
I would like to suggest a feature enhancement for Julia to include syntactic sugar in function definitions, similar to `constexpr` in C++.

Currently, functions capture external symbols by reference. For example:

```julia
k = 1
add(x::Int) = k + x
```

In this case, calling `add(10)` returns `11`. However, if the value of `k` is changed to `10`, we get:

```julia
julia> k = 10
10

julia> add(10)
20
```

To capture the value of `k` at the time of function definition, we can use a generated function:

```julia
julia> k = 1;
julia> @generated add(x) = :(x + $k)
julia> add(10)
11

julia> k = 10;
julia> add(10)
11
```

In this case, the value of `k` is captured by value, avoiding runtime changes. Similar to C++'s `constexpr`, we want to compute certain values at compile time rather than runtime.

Therefore, I propose introducing syntactic sugar in function definitions to allow capture of constants at compile time. For example:

```julia
function add(x)
    const v = ConstExprFunc()
    x + v
end
```

Here, the value of the constant `v` should be determined at compile time. While this can be achieved using macros, having a dedicated syntax would be more intuitive and convenient.

Thank you for considering this enhancement.
Any suggestion is welcome.

**Comment by Keno** [comment]
> ```julia
> julia> @generated add(x) = :(x + $k)
> ```

This is an illegal generated function

Aren't you just looking for let?:
```
julia> let k=k
       global add(x::Int) = x+k
       end
add (generic function with 1 method)

julia> add(2)
3

julia> k = 2
2

julia> add(2)
3
```

**Comment by kylincaster** [comment]
@Keno Thank you for your reply and for reminding me about the use of `let`. Currently, the value of `k` can be captured by the `add` function using the following approach:

```julia
add = let captured_k = k
    function add(x::Int)
        captured_k + x
    end
end
```

As I mentioned, there are various ways to capture external values or the return value of a (constexpr) function. However, having dedicated syntactic sugar for this purpose would be more convenient and improve code readability by using `const`.

**Comment by vtjnash** [comment]
Typically that would be written `@eval add(x) = $k + x` (you can find several examples of this in Base, though it is not especially common). Those examples of `@generated` functions violate the requirement of being pure / not observing mutable state

**Comment by vtjnash** [comment]
The syntax for your proposal would be `add(x) = $k + x`, but that is intentionally not allowed without the explicit `eval`. Alternatively, the equivalent of constexpr is `const` in Julia, as `const k = 1` would do the same in your original proposal.
