### ISSUE TITLE
export statement lowering correctness, causing regression

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#54805]
```
Failed to precompile EngThermBase [dffbff30-506a-45ba-b474-e78cc8ad254e] to "/home/pkgeval/.julia/compiled/v1.12/EngThermBase/jl_Zo5R80".
ERROR: LoadError: syntax: malformed "export" statement
Stacktrace:
  [1] top-level scope
    @ none:1
  [2] top-level scope
    @ ~/.julia/packages/EngThermBase/ob2Gj/src/amounts.jl:327
  [3] eval
    @ ./boot.jl:437 [inlined]
  [4] mkWhlAmt(TYPE::Symbol, SUPT::Symbol, FNAM::Symbol, ALIA::Symbol, SYMB::String, UNIT::Unitful.FreeUnits{(), NoDims, nothing}, USTR::String, WHAT::String, DELT::Bool)
    @ EngThermBase ~/.julia/packages/EngThermBase/ob2Gj/src/amounts.jl:253
  [5] top-level scope
    @ ~/.julia/packages/EngThermBase/ob2Gj/src/amounts.jl:387
```
https://github.com/JEngTherm/EngThermBase.jl/blob/master/src/amounts.jl#L327

I don't know if it is somehow incorrectly becoming local, which also is observed to corrupt the lowering of the export, or something else going on there:
```
julia> @eval begin
       local b = 1
       export b
       end
ERROR: syntax: malformed "export" statement
```

**Comment by vtjnash** [comment]
Similar looking bug here (for import):
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2024-06/13/AdaptiveSparseGrids.primary.log

**Comment by Keno** [comment]
I believe I found and fixed this in https://github.com/JuliaLang/julia/pull/54773

**Comment by Keno** [comment]
Specifically this change: https://github.com/JuliaLang/julia/pull/54773/files#diff-5d79463faae0f7f19454c7f9888498d9f876082e258ab3efdca36a0ee64b0c87R5161

**Comment by vtjnash** [comment]
Since that is a one line fix, should we make that a separate change and backport as needed for PkgEval?

**Comment by Keno** [comment]
Yeah, probably.
