### ISSUE TITLE
[Test] need shim for FieldError

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#54807]
Similar to our shim for `@test_throws` with LoadError, we may need a shim for FieldError. Some examples:
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2024-06/13/UnPack.primary.log
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2024-06/13/Parameters.primary.log
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2024-06/13/FunctionOperators.primary.log

**Comment by arhik** [comment]
@vtjnash this can be closed if it meets your issue.
