### ISSUE TITLE
`last(::Tuple{})` throws `BoundsError`

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#54828]
```julia-repl
julia> last(())
ERROR: BoundsError: attempt to access Tuple{} at index [0]
```

Not sure whether this is important, but AFAIK it's often good to cause a `MethodError` to be thrown instead of throwing other exceptions, in cases like this one when the function is statically guaranteed to throw?

**Comment by KristofferC** [comment]
I think it is better to be consistent with other collections here.

**Comment by Seelengrab** [comment]
A `MethodError` would imply that the method doesn't exist - it does exist, but there's nothing to index since the collection is empty. A `BoundsError` is thus correct.

**Comment by nsajko** [comment]
> A `MethodError` would imply that the method doesn't exist

The idea was that we *could* turn this into an actual "method not found situation", something like:

```julia
function last(t::Tuple)
    function last_nonempty(t::Tuple{Any,Vararg})
        t[end]
    end
    last_nonempty(t)
end
```

```julia-repl
julia> last((3,))
3

julia> last(())
ERROR: MethodError: no method matching (::var"#last_nonempty#1")(::Tuple{})
The function `last_nonempty` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  (::var"#last_nonempty#1")(::Tuple{Any, Vararg})
```

**Comment by nsajko** [comment]
Or, a bit more clear:

```julia
function last(t::Tuple)
    function throw_if_empty(t::Tuple{Any,Vararg})
        nothing
    end
    throw_if_empty(t)
    t[end]
end
```

**Comment by KristofferC** [comment]
The current way is most likely fine the way it is.
