### ISSUE TITLE
Matrix `exp` and `log` are not inverse of each other

### ISSUE THREAD

**Issue by olivierverdier** [JuliaLang/julia#54833]
1. Output of `versioninfo()`
 > Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
Environment:
  JULIA_EDITOR = emacsclient
  JULIA_INPUT_COLOR = bold
  JULIA_ANSWER_COLOR = bold

2. How Julia was installed

With [`juliaup`](https://github.com/JuliaLang/juliaup)

3. Minimal working example:

```julia
M = [0.9949357359852791 -0.015567763143324862 -0.09091193493947397 -0.03994428739762443 0.07338356301650806; 0.011813655598647289 0.9968988574699793 -0.06204555000202496 0.04694097614450692 0.09028834462782365; 0.092737943594701 0.059546719185135925 0.9935850721633324 0.025348893985651405 -0.018530261590167685; 0.0369187299165628 -0.04903571106913449 -0.025962938675946543 0.9977767446862031 0.12901494726320517; 0.0 0.0 0.0 0.0 1.0]
sdiff = exp(log(M)) - M
-log10(maximum(abs.(sdiff))) # < 3
```

The same test in Python gives 
```python
import numpy as np
import scipy as sp


M = np.array([[0.9949357359852791,-0.015567763143324862,-0.09091193493947397,-0.03994428739762443,0.07338356301650806],[0.011813655598647289,0.9968988574699793,-0.06204555000202496,0.04694097614450692,0.09028834462782365],[0.092737943594701,0.059546719185135925,0.9935850721633324,0.025348893985651405,-0.018530261590167685],[0.0369187299165628,-0.04903571106913449,-0.025962938675946543,0.9977767446862031,0.12901494726320517],[0.0,0.0,0.0,0.0,1.0]])

sdiff = sp.linalg.expm(sp.linalg.logm(M)) - M

print(-np.log10(np.max(np.abs(sdiff)))) # > 15
```

**Comment by dkarrasch** [comment]
Could you please quickly check which one seems to be wrong: `log` or `exp`?

**Comment by oscardssmith** [comment]
reproduced on x86 linux. The issue appears to be in `log` (although it's somewhat hard to prove because matrix logs are not unique).

**Comment by olivierverdier** [comment]
A simpler example:

```julia
N = [0.0 -0.8 1.1 0.2 -0.2; 0.8 0.0 0.8 -0.4 -0.1; -1.1 -0.8 0.0 0.4 -0.1; -0.2 0.4 -0.4 0.0 0.0; 0.0 0.0 0.0 0.0 0.0]

k = 10 # also bad for k = 100 or 1000

sdiff = log(exp(N/k)) - N/k
@show -log10(maximum(abs.(sdiff))) # 2.9
```

I agree with @oscardssmith , I suspect the matrix logarithm to be at fault.

**Comment by oscardssmith** [comment]
This second example isn't as good because iiuc, `log(exp(M)) == M` isn't expected for matrices do to branch cuts.

**Comment by dkarrasch** [comment]
On v1.6.7 I get

```julia
julia> -log10(maximum(abs.(sdiff))) # < 3
15.175451669208671
```

on v1.9.4 and v1.8.5

```julia
julia> -log10(maximum(abs.(sdiff))) # < 3
2.233375639545474
```

so this must be an "old" bug.

**Comment by olivierverdier** [comment]
> This second example isn't as good because iiuc, `log(exp(M)) == M` isn't expected for matrices do to branch cuts.

That's why I included the parameter `k`. If `M` is small enough, I would expect `log(exp(M)) == M` to be true no matter what, right?

**Comment by olivierverdier** [comment]
> so this must be an "old" bug.

I suspect the problem to be in [`log_quasitriu`](https://github.com/JuliaLang/julia/blob/b0b7a859ed5bfa69ff368045982f87e50ef0ee32/stdlib/LinearAlgebra/src/triangular.jl#L1844), which was introduced in 6913f9ccb156230f54830c8b7b8ef82b41cac27e, in 2021.

**Comment by giordano** [comment]
> I suspect the problem to be in [log_quasitriu](https://github.com/JuliaLang/julia/blob/b0b7a859ed5bfa69ff368045982f87e50ef0ee32/stdlib/LinearAlgebra/src/triangular.jl#L1844), which was introduced in https://github.com/JuliaLang/julia/commit/6913f9ccb156230f54830c8b7b8ef82b41cac27e, in 2021.

That's more recent than Julia v1.6 though

**Comment by olivierverdier** [comment]
More evidence that the problem is the logarithm:
```julia
N = [0.0 -0.8 1.1 0.2 -0.2; 0.8 0.0 0.8 -0.4 -0.1; -1.1 -0.8 0.0 0.4 -0.1; -0.2 0.4 -0.4 0.0 0.0; 0.0 0.0 0.0 0.0 0.0]
k = 10
M = exp(N/k)

sdiff = log(M*M) - 2*log(M)

@show -log10(maximum(abs.(sdiff))) # 2.6
```

The equivalent code in Python gives 14.7.

**Comment by olivierverdier** [comment]
> > I suspect the problem to be in [log_quasitriu](https://github.com/JuliaLang/julia/blob/b0b7a859ed5bfa69ff368045982f87e50ef0ee32/stdlib/LinearAlgebra/src/triangular.jl#L1844), which was introduced in [6913f9c](https://github.com/JuliaLang/julia/commit/6913f9ccb156230f54830c8b7b8ef82b41cac27e), in 2021.
> 
> That's more recent than Julia v1.6 though

If it were the case that PR #39973 is to blame (wild guess), then the bug would have appeared first in v1.7.0.

**Comment by olivierverdier** [comment]
For completeness, I checked the code above (i.e., with `log(M*M) - 2*log(M)`)  with various versions, and indeed, the bug appears between v1.6.7 and v1.7.3.
My money is still on PR #39973.

**Comment by olivierverdier** [comment]
An even simpler test:
```julia
function test_log(N, k=10)
    M = exp(N / k)
    sdiff = log(M*M) - 2*log(M)
    return -log10(maximum(abs.(sdiff)))
end
```
Now simply with 
```julia
N = [0.0 -1.0 1.0; 1.0 0.0 0.0; 0.0 0.0 0.0]
```
run
```julia
test_log(N) # 2.1
```
and the same in Python returns 15.4.

**Comment by mikmoore** [comment]
> I tried a specific test from scipy's test suite

It's worth noting that the condition number of that matrix is awful:
```julia-repl
julia> cond(A)
1.8884133342622014e20

julia> cond(logA)
4.086839610043594e28
```
I have an independent `myexp` implementation (our actual `exp` implementation is better but has limited type support #51008) and it similarly struggles with this:

```julia
function myexp(A)
	# compute exp(A) == exp(A/2^n)^(2^n)
	iszero(A) && return float(one(A))
	# TODO: decide the best norm to use here: op-1, op-Inf, or frobenius are probably good candidates - maybe take the min of all three
	nA = float(norm(A,2))
	fr,ex = frexp(nA)
	logscale = max(4 + ex,0) # ensure nA^(4+1)/factorial(4+1) < eps for 4 or whatever power our approximation is
	p = ntuple(i->inv(prod(1.0:i-1)),Val(9))
	scale = exp2(-logscale)
	sA = A * scale
	if sA isa AbstractMatrix
		expA = evalpoly(sA,UniformScaling.(p))
	else
		expA = evalpoly(sA,p)
	end
	for _ in 1:logscale
		expA = expA*expA
	end
	return expA
end
```
And with this and `BigFloat`:
```julia-repl
julia> norm(exp(logA) - A) / norm(A)
2.799714043033207e6

julia> norm(myexp(logA) - A) / norm(A) # myexp is generally worse
5.134964610902018e6

julia> norm(myexp(big.(logA)) - A) / norm(A) |> Float64 # despite being worse, BigFloat makes this version work
8.141481015780612e-7
```
Note that the squaring part of our `exp` routine is probably very-much to blame, given that `BigFloat` resolves that problem even though the exp kernel is not expanded beyond what is roughly needed for `Float64`. I don't think we should use that example for this particular issue.

However, `myexp` does nothing to resolve the original example:
```julia-repl
julia> cond(M) # extremely well conditioned
1.1906431494194285

julia> norm(exp(log(M)) - M) / norm(M) |> Float64
0.003052024023511132

julia> norm(myexp(big.(log(M))) - M) / norm(M) |> Float64
0.0030520240235111305
```

Given that the matrix exponential is reasonably "simple" to compute (modulo stability issues, which leave it as still an open topic), I am much more inclined towards expecting that `log` is the culprit.

**Comment by mikmoore** [comment]
Confirmation that `log` is the culprit:
```julia
function eigapply(fun, A)
	D,V = eigen(A)
	return V * Diagonal(fun.(D)) / V
end
```
```julia-repl
julia> norm(exp(log(M)) - M) / norm(M)
0.003052024023511132

julia> norm(exp(log(M)) - exp(eigapply(log,M))) / norm(M)
0.0030520240235111335

julia> norm(M - exp(eigapply(log,M))) / norm(M)
6.499342713344915e-16
```

**Comment by olivierverdier** [comment]
I think the problem is in `log_quasitriu`. From the example above (i.e., `qtriu = schur(exp(N/10)).T`):
```julia
qtriu = [0.9950041652780259 -0.09983341664682815 0.07153667745275474; 0.09983341664682804 0.9950041652780259 0.06981527929449967; 0.0 0.0 1.0]
```
Now
```julia
LinearAlgebra.log_quasitriu(qtriu)[:,end]
```
gives
```julia
0.07240564253650691
 0.06891743457599916
 0.0
```
and in Python, the same vector is
```julia
0.07496781758158656
 0.06618025632357401
 0.0
```
Pretty big discrepancy starting at the second decimal.

**Comment by oscardssmith** [comment]
So this code is a very direct matlab translation with all the oddness that entails, but what I've found is that if we make it so `s,m = 1,4` rather than `0,5` we get the right answer. see https://github.com/JuliaLang/julia/pull/54867

**Comment by aravindh-krishnamoorthy** [comment]
Just one more pointer to add here for further analysis. Kinda good that the errors are localised.

```julia
julia> using LinearAlgebra

julia> M = [0.9949357359852791 -0.015567763143324862 -0.09091193493947397 -0.03994428739762443 0.07338356301650806; 0.011813655598647289 0.9968988574699793 -0.06204555000202496 0.04694097614450692 0.09028834462782365; 0.092737943594701 0.059546719185135925 0.9935850721633324 0.025348893985651405 -0.018530261590167685; 0.0369187299165628 -0.04903571106913449 -0.025962938675946543 0.9977767446862031 0.12901494726320517; 0.0 0.0 0.0 0.0 1.0]
5×5 Matrix{Float64}:
 0.994936   -0.0155678  -0.0909119  -0.0399443   0.0733836
 0.0118137   0.996899   -0.0620456   0.046941    0.0902883
 0.0927379   0.0595467   0.993585    0.0253489  -0.0185303
 0.0369187  -0.0490357  -0.0259629   0.997777    0.129015
 0.0         0.0         0.0         0.0         1.0

julia> S = schur(complex(M));

julia> norm(exp(S.Z*LinearAlgebra.log_quasitriu(S.T)*S.Z') - M)
1.5337045591657124e-15

julia> S = schur(M);

julia> norm(exp(S.Z*LinearAlgebra.log_quasitriu(S.T)*S.Z') - M)
0.0068453336198366545

julia> exp(S.Z*LinearAlgebra.log_quasitriu(S.T)*S.Z') - M
5×5 Matrix{Float64}:
 -6.66134e-16  -3.72966e-16   2.498e-16    -1.38778e-17  -0.00185147
 -3.34802e-16   5.55112e-16  -2.15106e-16   4.85723e-17   0.00300777
 -6.93889e-17  -2.70617e-16  -2.22045e-16  -2.08167e-17   0.00584284
 -1.249e-16    -6.245e-17    -7.63278e-17   0.0          -0.000495109
  0.0           0.0           0.0           0.0           0.0
```

**Comment by aravindh-krishnamoorthy** [comment]
> - Has anyone studied whether the algorithm in [R1] works with quasi-triangular matrices?

This does not seem to be the immediate problem. However, using the diagonal elements in the following **seems wrong.** https://github.com/JuliaLang/julia/blob/34b81fbc90a96c1db7f235a465d2cfdf5937e563/stdlib/LinearAlgebra/src/triangular.jl#L2030 

Choosing `d` as the eigenvalues of `A` seem to be a better choice. **This will need to be taken up separately.**

**Comment by aravindh-krishnamoorthy** [comment]
The issue is in the function https://github.com/JuliaLang/julia/blob/34b81fbc90a96c1db7f235a465d2cfdf5937e563/stdlib/LinearAlgebra/src/triangular.jl#L2169 where the case `s = 0` is not handled.

The following is a quick fix that works for this case (changes are made to the code in the above commit). I will have to think a bit more before suggesting a permanent solution.

```diff
Base.@propagate_inbounds function _sqrt_pow_diag_block_2x2!(A, A0, s)
+    if iszero(s)
+        A[1,1] -= 1
+        A[2,2] -= 1
+        return
+    end
    _sqrt_real_2x2!(A, A0)
    if isone(s)
        A[1,1] -= 1
        A[2,2] -= 1
    else
```

With this change, we have

```julia
julia> norm(exp(S.Z*log_quasitriu(S.T)*S.Z') - M)
1.1192892392171394e-15
```

**Comment by aravindh-krishnamoorthy** [comment]
This code looks good also for long term. @oscardssmith would you like to update your PR's title/code and provide this fix instead? To avoid duplication of effort and the fact that you got started with this...

**Comment by sztal** [comment]
I would like to reopen this, as the problem seems to be still present for:

```
Julia Version 1.11.1
Commit 8f5b7ca12ad (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 9 5900HX with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
Environment:
  JULIA_PROJECT = @.
  JULIA_PKG_PRESERVE_TIERED_INSTALLED = true
  JULIA_REVISE = manual
```

Here is a reproducible example.

```julia
X = ComplexF64[0.13876600770577865 - 0.7479359089199926im 0.6917878085992973 + 0.19026214430546964im -0.6496049314494047 + 0.44880864033022017im -0.6539918743325319 - 0.5669514059548579im; -1.2191378975437437 - 1.1268587002225425im 1.1565559424690692 - 1.0555407143243536im 0.07226721485388016 + 1.7216363622873323im -1.8079199840021414 + 0.5472527315532654im; 0.2570851057997248 - 0.3851791974674994im 0.34140920101611794 + 0.272426223060375im -0.4711339674720063 + 0.09525599912193858im -0.2298868080116554 - 0.47411679467306206im; 0.8185826950401655 - 1.0940433768953808im 0.9626494687333146 + 0.8568348169031336im -1.4032149644984198 + 0.2058723065274753im -0.6020598262406186 - 1.4333720109184036im]

# This is correct
isapprox(exp(log(X)), X)

# But this fails
isapprox(log(exp(X)), X)
```

**Comment by sztal** [comment]
Judging by the build info this is the official `1.11.1` release.

**Comment by aravindh-krishnamoorthy** [comment]
@sztal unfortunately your input matrix's eigenvalues are complex valued, and differ from those of your output matrix by $2\pi\mathrm{i}.$ I'm not sure if it's a good idea to handle it under this issue, if at all.

```julia
julia> eigvals(log(exp(X))) - eigvals(X)
4-element Vector{ComplexF64}:
  2.4993230361836148e-17 - 7.300158154297067e-16im
   9.935501868782034e-16 + 4.1665600306275787e-16im
 -1.0340838418013983e-15 - 1.0857137457932716e-16im
                     0.0 + 6.283185307179592im
```
