### ISSUE TITLE
`UnionAll`s with trivial bodies ignore type lower bounds?

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#54904]
All the way from v1.6 to nightly (v1.12-dev), we have:

```julia-repl
julia> (T where {Int<:T<:Any})
Any

julia> (T where {T>:Int})
Any
```

In contrast, when the body of a `UnionAll` isn't trivial, the lower bound isn't ignored:

```julia-repl
julia> (Vector{T} where {Int<:T<:Any})
Vector{T} where T>:Int64 (alias for Array{T, 1} where T>:Int64)
```

Ignoring the type lower bounds seems related to this dispatch issue that also causes #54893:

```julia-repl
julia> f(x::T) where {T>:Int} = x
f (generic function with 1 method)

julia> f(1.0)  # would expect `MethodError` being thrown
1.0
```

Possibly also related:  #24179

**Comment by vtjnash** [comment]
This is just a expected implication of covariance

**Comment by nsajko** [comment]
Is `f(1.0)` returning instead of throwing expected, too?
