### ISSUE TITLE
uninitialized typed global can only be imported qualified and not directly 

### ISSUE THREAD

**Issue by schlichtanders** [JuliaLang/julia#54954]
Following up on [this discourse thread](https://discourse.julialang.org/t/i-cannot-import-global-variable-type/112468) I want to raise awareness to uninitialized typed global variables.

It is an awesome concept which I'd like to use for initializing secret config values at initial runtime (at the start of my main-method). 

However unfortunately they can only be imported via qualified access. My case is that I want to import it from a submodule which fails. 

- I.e. importing the entire module like `import TopLevelProject` and accessing it with `TopLevelProject.variable` works.
- but `using TopLevelProject: variable` gives the error `ERROR: LoadError: UndefVarError: variable not defined`, even if the variable is not actually used within top-level statements, but just inside functions. 

It would be awesome if the variable an already be referenced, even though it is not yet initialized.

**Comment by nsajko** [comment]
Can you give an example reproducer for your error message, and a minimal example of desired behavior?

**Comment by schlichtanders** [comment]
here a short sketch

```julia
module MyPackage
using Configurations: @option
@option struct MyConfigType
    specialconfig::Bool = false
end
global CONFIG::MyConfigType

module SubModule
    using MyPackage: CONFIG

    function do_something_configurable()
        if CONFIG.specialconfig
             print("yeah")
        end
    end
end

function main()
    CONFIG = MyConfigType(specialconfig=true)
    SubModule.do_something_configurable()
end
end
```
and then call `MyPackage.main()`

**Comment by Keno** [comment]
I think this is just a bug that happened when this syntax got added. Will put up a PR.

**Comment by Keno** [comment]
#54956
