### ISSUE TITLE
Drop OBJPROFILE?

### ISSUE THREAD

**Issue by d-netto** [JuliaLang/julia#54968]
This tool provides statistics about number of objects and number of bytes allocated for every Julia type.

This is fairly similar to the functionality provided by the heap snapshot, which has a considerably better visualization tool provided by Chrome.

Should we drop `OBJPROFILE` to reduce the maintenance burden in the GC, given it doesn't seen to provide much value now that we have the heap snapshot?

Would this be breaking?

**Comment by d-netto** [comment]
CC: @vtjnash, @gbaraldi.

**Comment by d-netto** [comment]
Bump?

**Comment by gbaraldi** [comment]
Yeah, lets do it.
