### ISSUE TITLE
FEATURE REQUEST: Julia REPL to show currently active environment in julia and shell mode

### ISSUE THREAD

**Issue by Manvi-Agrawal** [JuliaLang/julia#54978]
Currently, Julia REPL only shows the active environment when we are in pkg mode(`(Envt) pkg>`). It would be good to show this info for shell(`shell>`) and julia(`>julia`) modes as well.

**Additional context**
I have used virtual environments for python with Anaconda and venv, and both frameworks always show currently activated environment. I feel it really helps to know which environment you are in as a beginner if you are trying to work out different examples. Thanks to shell mode, I can switch things by cmd line only to realize sometime later that I am in a wrong environment :-( I understand its not going be super important, since REPL is for short endeavors, but for keen beginner explorers to Julia, this might be helpful to keep them on track

**Comment by nsajko** [comment]
#54235
