### ISSUE TITLE
`Base.Iterators`: delete the `cycle(iter, n)` method, at least until the API for stateful iterators is worked out?

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#54986]
PR #47354 added a two-argument method to `Iterators.cycle`, and it's currently on the road to be released with Julia v1.11.

IMO the feature addition is dubious in any case, given how:

1. It might as well go into a registered package (like IterTools?) instead.
2. The motivation for the PR was consistency with `repeated`, but this really seems like an instance of the "two wrongs make a right" fallacy. Given that the one-argument methods of `repeated` and `cycle` have different semantics than the two-argument methods, it'd be better not to pun them onto the same function.

Perhaps more important, however, are these issues:

1. The public API here isn't clear for stateful iterators, it's underspecified and the behavior is arguably broken. The `cycle` doc string doesn't mention stateful iterators, but compatibility concerns complicate things.
2. This ties into other existing bugs: #53017 and #53169. Fixing them would be easy if we could, for example, document that `cycle` doesn't support stateful iterators (by making `cycle(it)` return `()` for `isempty(it)`).

Adding features to such an incompletely designed API stands to make things even worse.

Can we revert this PR ASAP while that's still possible, before v1.11 gets released? Then, after the API is clarified regarding stateful iterators, and the two issues mentioned above are fixed, the feature addition could be reconsidered.

**Comment by adienes** [comment]
how is it a pun or different semantics?

> Iterators.cycle(iter, n)` runs over `iter` a fixed number of times, instead of forever

makes total sense to me

**Comment by JeffBezanson** [comment]
I agree with @adienes; I don't see that adding this method specifically changes anything or creates meaningful new problems with these iterators.
