### ISSUE TITLE
document the optional argument of the `Task` constructor

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#55005]
The optional `Int` parameter seems to determine the stack size of the `Task`, but its not documented at all.

https://github.com/JuliaLang/julia/blob/11939977732354799f737ee9c3081be12311eace/base/task.jl#L5-L5

**Comment by nsajko** [comment]
The nice thing about making the `Task` stack size limit public, is that now it'll be possible to run with a smaller size within the test suite of a package, to catch potential issues early, e.g., overly deep recursion.

**Comment by vtjnash** [comment]
Just as a warning though, you will consume substantially more memory (both physical and virtual) if you use this option, as it forces eager allocation of a stack that may never get used. Use with some care.

**Comment by nsajko** [comment]
Oh. I didn't think it'd work like that.

**Comment by MilesCranmer** [comment]
> Just as a warning though, you will consume substantially more memory (both physical and virtual) if you use this option, as it forces eager allocation of a stack that may never get used. Use with some care.

It feels surprising that memory is allocated differently between default stack size limit and custom stack size limit. How hard would it be to turn off eager allocations here?

**Comment by MilesCranmer** [comment]
I'm also confused because

```julia
julia> Task(() -> sleep(10), 10 * 1024 ^ 4)  |> schedule |> fetch
```

doesn't OOM...
