### ISSUE TITLE
Remove JuliaSyntaxHighlighting from 1.11

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#55023]
From a chat with @tecosaur at triage, Markdown uses it as of 1.12, but noting uses it in 1.11, and it is not quite ready for stdlibification. Notably, it has no docs and is still doing breaking changes (e.g. https://github.com/JuliaLang/JuliaSyntaxHighlighting.jl/pull/2).

Still very much on board with having this functionality, just not in a stdlib in 1.11.

**Comment by KristofferC** [comment]
If nothing uses it in 1.11 it definitely makes sense to pull it.

**Comment by tecosaur** [comment]
Mmm, I think it makes sense to have more stdlibs to reuse (as mentioned Markdown in 1.12, and some other future uses come to mind), but this didn't start happening in time for the 1.11 merge window.

So, I'm fully in support of pulling it from the 1.11 release.

**Comment by Keno** [comment]
Probably a separate issue, but the pull in should also be conditional on JuliaSyntax actually being in the system image. As of right now, the flisp parser is still supported and things shouldn't error if JuliaSyntax is not available. Probably the easiest way to accomplish this is to just have JuliaSyntaxHighlighting's exported API be a no-op if JuliaSyntax is unavailable.

**Comment by tecosaur** [comment]
> Probably the easiest way to accomplish this is to just have JuliaSyntaxHighlighting's exported API be a no-op if JuliaSyntax is unavailable.

@Keno I'll happily make this change if somebody could let me know what a good way to check if JuliaSyntax is available is :slightly_smiling_face:
