### ISSUE TITLE
Multi-editor syntax highlighting issue with `using ...: func! as func` 

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/julia#55054]
```julia
using Library: my_func! as my_func
```

As you can see, `as` is not colored. I see this in:
- GitHub Linguist (https://github.com/github-linguist/linguist), which is shown above, and
- VSCode

I do _not_ see this issue in:

- Vim

However, removing the exclamation mark fixes this on all of these platforms:

```julia
using Library: my_func as my_func
```

Although the Sublime syntax highlighter (https://github.com/JuliaEditorSupport/Julia-sublime/tree/3366b10be91aaab7a61ae0bc0a5af5cc375e58d1) which is used in other packages like [`bat`](https://github.com/sharkdp/bat), seems to skip highlighting the `as` entirely.

**Comment by MilesCranmer** [comment]
cc @pfitzseb

**Comment by giordano** [comment]
It isn't clear to me why the issue was opened in this repository: do I understand correctly you're complaining about syntax highlighting in vscode and github, which both use the [syntax highlighting in atom](https://github.com/JuliaEditorSupport/atom-language-julia)? If so, you should open an issue there, I don't see what should be done here at all.

**Comment by MilesCranmer** [comment]
Not complaining, just doing my duty of submitting bug reports. Since it was across multiple editors I thought it might be useful to track it here, especially since many of these syntax highlighters are out-of-sync with certain submodules and it's not clear what repo needs fixing.

**Comment by giordano** [comment]
But there's nothing actionable for this repository, a thread on discourse would serve the same purpose.

**Comment by MilesCranmer** [comment]
The issue message says

> If you have a question please search or post to our Discourse site: https://discourse.julialang.org.

Anyways, I thought I was being helpful by flagging this, sorry. I won't have time to track down the right repositories so will leave the issue here for posterity (seems to be more than just Atom FYI).

**Comment by giordano** [comment]
> The issue message says
> 
> > If you have a question please search or post to our Discourse site: https://discourse.julialang.org.

Not sure what you mean, but I think posting on Discourse would have been better, yes.

> Anyways, I thought I was being helpful by flagging this, sorry.

I do think it's helpful to flag these, just not in this repository if there's nothing actionable here, all the things have been fixed elsewhere.  Starting a discussion on Discourse would have been a better place.

>  I won't have time to track down the right repositories so will leave the issue here for posterity (seems to be more than just Atom FYI).

If the VSCode/GitHub problem is in the code at https://github.com/JuliaEditorSupport/atom-language-julia, then the issue should be opened there, I believe the other project routinely update the grammar (well, I think developers of the Atom grammar are the same as the VSCode plugin).  About Sublime, a 3-second Google search suggests the syntax highlighting is maintained at https://github.com/JuliaEditorSupport/Julia-sublime.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JuliaEditorSupport/atom-language-julia/pull/284. This will take a bit to propagate to both GH and VS Code.

**Comment by MilesCranmer** [comment]
Thanks!
