### ISSUE TITLE
Drop/deprecate flisp parser/JULIA_USE_FLISP_PARSER env var (and flisp in full, eventually, for other things, such as bootstrap)

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#55061]
Does JuliaSyntax.jl (added in 1.10) actually have any bugs, i.e. a need to flisp _parser_ to exits?

>JuliaSyntax.jl is now used as the default parser, providing better diagnostics and faster parsing. Set environment variable JULIA_USE_FLISP_PARSER to 1 to switch back to the old parser if necessary (and if you find this necessary, please file an issue) 

A.
The flisp parser should be dropped right now, at least for 1.12 to make Julia smaller/simpler, if not for 1.11. I might not be the best person to do it, but am still willing to do it, make a PR to at least drop just the env var support. Keno considers the parser supported (that wasn't a long-term plan I think, or for how long 1 or 2 releases?): https://github.com/JuliaLang/julia/issues/55023#issuecomment-2209373803
>conditional on JuliaSyntax actually being in the system image. As of right now, the flisp parser is still supported and things shouldn't error if JuliaSyntax is not available.

I realize we already have an RC for 1.11, and 1.11rc2 coming, so a question does a feature freeze apply to drop (off-by default) features like this?

I.e. is dropping a feature considered a "feature"? It's trivial to drop the env var support, making the feature disabled, meaning unable to enabled it. I'm not sure if "dead code elimination" will make Julia any smaller, at least then flisp could be dropped in 1.11 point release. If we keep the old parser then it's a promise to keep it for all 1.11.x. It could however be trivially added back in 1.11.x in case a mistake to drop it.]

B.

Julia --lisp

should also be dropped. Nobody relies on it. It's kind of an Easter egg. If anyone considers it supported flisp can't be dropped. Besides that and the parser not much else depends on it, only bootstrap? I just don't know enough about that, how to drop the rest of flisp uses, but I at least believe it's all internal. What is the gain in size/startup cost to just drop the parser. or all of flisp? It IS rather small code...

**Comment by oscardssmith** [comment]
we're way way way to late for 1.11. we also can't delete flisp parser until we have a wait to bootstrap without it. also, the benefit of removal is pretty small until lowering is also in Julia.

**Comment by PallHaraldsson** [comment]
But ok to drop for 1.12, i.e. a PR wanted? I knew flisp needed for bootstrap, but you mean not just flisp, but the _flisp parser_ is needed? Then I guess I can't make the change, or do not trust myself to do it, but I could drop the env var support and all user-visible stuff.

**Comment by KristofferC** [comment]
It's needed for bootstrapping right now. I don't think there needs to be a dedicated issue about this, there is also no rush doing any of this really.
