### ISSUE TITLE
Denoise BigInt conversion

### ISSUE THREAD

**Issue by nopria** [JuliaLang/julia#55067]
julia> BigInt(3.453e78)

returns

    34530000000000000 90829207640410620202184021047720495530415184879687805108748288

but, as we all know, the digits after the space (added by me) are arbitrary noise which could (and maybe should) be set to zero.

I'm aware that such *noise* has a precise reason in the way numbers are represented in a computer, but I think setting the *noise* digits to zero would nonetheless be an improvement.

Have a look at what has been done [in this case](https://github.com/SethMMorton/fastnumbers/pull/77).

**Comment by sgaure** [comment]
It's not really noise. They are deterministic digits due to limited precision in the `Float64` literal.  You can easily increase the precision and remove these digits with `BigInt(big"3.453e78")`.
