### ISSUE TITLE
ERROR: LoadError: UndefVarError: `UUIDs` not defined.

### ISSUE THREAD

**Issue by divital-coder** [JuliaLang/julia#55092]
When trying to test the medical imaging packages under the julia ecosystem, (which i am currently involved heavily in due to JSOC), i encountered the UUIDs not defined error, which previously was listed as a bug on here under the UUID alias.

![image](https://github.com/JuliaLang/julia/assets/77094628/4e954a06-b915-42ad-ad5f-572cb17df7e9)

```
julia> include("MedEye3d.jl/test_script_simplified.jl")
ERROR: LoadError: UndefVarError: `UUIDs` not defined
Stacktrace:
 [1] load_images(path::String)
   @ MedImages.Load_and_save D:\mingw_installation\home\hurtbadly\Desktop\MedImages.jl\src\Load_and_save.jl:559
 [2] load_image
   @ D:\mingw_installation\home\hurtbadly\Desktop\MedImages.jl\src\Load_and_save.jl:759 [inlined]
 [3] loadRegisteredImages(studySrc::String)
   @ MedEye3d.SegmentationDisplay D:\mingw_installation\home\hurtbadly\Desktop\MedEye3d.jl\src\display\GLFW\SegmentationDisplay.jl:191
 [4] top-level scope
   @ D:\mingw_installation\home\hurtbadly\Desktop\MedEye3d.jl\test_script_simplified.jl:5
 [5] include(fname::String)
   @ Base.MainInclude .\client.jl:489
 [6] top-level scope
   @ REPL[8]:1
in expression starting at D:\mingw_installation\home\hurtbadly\Desktop\MedEye3d.jl\test_script_simplified.jl:5
```

VERSION INFO
```
1.julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd4843 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × AMD Ryzen 5 3600 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
Threads: 3 default, 1 interactive, 1 GC (on 12 virtual cores)
Environment:
  JULIA_DEPOT_PATH = D:/mingw_installation/home/hurtbadly/.julia
```

3. Installed binaries for windows, although i have tested the error on Linux (where i utilised juliaup)

3:STEPS TO REPRODUCE : 

NOTE: please download the data folders (they are not much, for medical imaging here)
https://drive.google.com/drive/folders/1RZe9kbLW3KsGGuAlbbxkcjKhnfTU3X-y?usp=sharing
and edit the relevant path of your folder u got, under MedEye3d.jl, test_script_simplified.jl
```
git clone https://github.com/divital-coder/MedEval3d.jl
git clone https://github.com/divital-coder/MedImages.jl
git clone https://github.com/divital-coder/MedEye3d.jl

julia --threads 3,1
]
develop ./MedEval3D.jl
develop ./MedImages.jl
develop ./MedEye3d.jl
using MedEye3d
include("MedEye3d.jl/test_script_simplified.jl")
```

Thanks for contributing to the Julia project!
-->

**Comment by jakobnissen** [comment]
I can't reproduce, because your code seem to rely on some Python packages being installed.
Is it possible for you to reduce the bug to a smaller example, which ideally also doesn't require downloading hundreds of MBs of medical images?

**Comment by divital-coder** [comment]
hello @jakobnissen thank you for your time and interest. In order to populate the data structure with a genuine dataset i cited the source for some medical imaging files. Ideally the package involving python deps is changing with a library c++ wrapper, but the UUIDs , error will still pertain. Perhaps you can try on a priveleged terminal with the process.

**Comment by jakobnissen** [comment]
No, you still need to install e.g. `SimpleITK` which is imported on line 544 in `MedImages.jl/src/Load_and_save.jl`.

**Comment by divital-coder** [comment]
Yes SimpleITK is required for MedImages,jl to work for now, is it something causing an issue? As for now, we cannot change it at the moment.

**Comment by divital-coder** [comment]
Hello this issue with my package was resolved after uncommenting a line for 
```
using UUIDs
```
in one of the files, although arguably perhaps there can be an added message in the error, stating that the source is missing a line somewhere ?
