### ISSUE TITLE
Documentation example not behaving as displayed - behavior of "const" on immutable objects.

### ISSUE THREAD

**Issue by At11011** [JuliaLang/julia#55140]
## Version info: 

```julia
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

## Installation method

I installed Julia using this line in Bash:

```bash
curl -fsSL https://install.julialang.org | sh
```

3.  The example code in https://github.com/JuliaLang/julia/blob/master/doc/src/manual/variables-and-scoping.md.

Expected output (Julia REPL):

```julia
julia> const s1 = "1"
"1"

julia> s2 = "1"
"1"

julia> pointer.([s1, s2], 1)
2-element Array{Ptr{UInt8},1}:
 Ptr{UInt8} @0x00000000132c9638
 Ptr{UInt8} @0x0000000013dd3d18

julia> s1 = s2
"1"

julia> pointer.([s1, s2], 1)
2-element Array{Ptr{UInt8},1}:
 Ptr{UInt8} @0x0000000013dd3d18
 Ptr{UInt8} @0x0000000013dd3d18
 ```

My output (Fresh Julia REPL):

```julia
julia> const s1 = "1"
"1"

julia> s2 = "1"
"1"

julia> pointer.([s1, s2], 1)
2-element Vector{Ptr{UInt8}}:
 Ptr{UInt8} @0x00007ed21f90ac80
 Ptr{UInt8} @0x00007ed21f90ae40

julia> s1 = s2
"1"

julia> pointer.([s1, s2], 1)
2-element Vector{Ptr{UInt8}}:
 Ptr{UInt8} @0x00007ed21f90ac80
 Ptr{UInt8} @0x00007ed21f90ae40
```

## Expected behavior

After the assignment of "s1 = s2" the address of the first index of s1 and s2 should match

## Actual behavior

The addresses of the first index of s1 and s2 do not match. In fact, the addresses of s1 and s2's first indexes remain unchanged from before and after the assignment. 

## The issue

I understand that the addresses will be be the same on my machine as compared to the example, but I noticed that the assignment of "s1 = s2" does not change the address of "s1" as shown in the example. Instead, the address remains the same.

I suspect that this is due to a change in the behavior of reassigned const string variables that has not been reflected in this example. Notably a similar example without the "const" keyword behaves in a manner that the example shows. Again in a fresh REPL:

```julia
julia> s1 = "1"
"1"

julia> s2 = "1"
"1"

julia> pointer.([s1, s2], 1)
2-element Vector{Ptr{UInt8}}:
 Ptr{UInt8} @0x0000716556d0ae40
 Ptr{UInt8} @0x0000716556d0b000

julia> s1 = s2
"1"

julia> pointer.([s1, s2], 1)
2-element Vector{Ptr{UInt8}}:
 Ptr{UInt8} @0x0000716556d0b000
 Ptr{UInt8} @0x0000716556d0b000
```

In this case, the address of s1's first index was updated as expected. 

I do not feel comfortable modifying the documentation to reflect this change in a pull request, as I am still learning the language and I am afraid of making incorrect statements about the inner workings of the language, but I am happy to bring this behavior to the attention of maintainers and to learn if it is a bug, or a change in the behavior of Julia, or simply my particular installation misbehaving. 

Thanks to those who wrote the documentation, it is exceptionally clear and informative!

**Comment by KristofferC** [comment]
The example code in the manual is bad and should be changed.
