### ISSUE TITLE
Parsing Int32 bitstring fails for very negative number

### ISSUE THREAD

**Issue by SBuercklin** [JuliaLang/julia#55164]
On Julia 1.10.4:
```julia
julia> bitstring(Int32(-typemax(Int32)))
"10000000000000000000000000000001"

julia> parse(Int32, ans; base = 2)
ERROR: OverflowError: overflow parsing "10000000000000000000000000000001"
Stacktrace:
 [1] tryparse_internal(::Type{Int32}, s::String, startpos::Int64, endpos::Int64, base_::Int64, raise::Bool)
   @ Base ./parse.jl:169
 [2] parse(::Type{Int32}, s::String; base::Int64)
   @ Base ./parse.jl:254
 [3] top-level scope
   @ REPL[326]:1
 [4] top-level scope
   @ none:1
```

**Comment by oscardssmith** [comment]
I don't think parse supports parsing 2s compliment versions of numbers like this. I don't think it's a bug.

**Comment by SBuercklin** [comment]
It'd be good to clarify that in the docstring, but why shouldn't 2s compliment be supported? We can even just reinterpret the bits to `Int32` after parsing a `UInt32`.

**Comment by oscardssmith** [comment]
parse isn't a bits based thing. It would be really weird if parse supported 10s compliment when parsing in base 10, so for similar reasons it shouldn't parse 2s compliment in base 2. parse and bitstring just aren't inverses of each other for negative numbers.  Using a normal negative base 2 number representation works as intended:
```
julia> typemin(Int32)
-2147483648

julia> a = "-1"*"0"^31
"-10000000000000000000000000000000"

julia> parse(Int32, a, base=2)
-2147483648
```
