### ISSUE TITLE
literal_pow isn't marked public and isn't documented

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#55194]
`literal_pow()` is mentioned and described in `^` docstring (https://docs.julialang.org/en/v1/base/math/#Base.:^-Tuple{Number,%20Number}), but not documented itself.
Moreover, I noticed it's not marked `public` in the `nightly` version.

**Comment by nsajko** [comment]
#28685

**Comment by nsajko** [comment]
The "not planned" status is used on Github for duplicates, too. I closed this as a dup.
