### ISSUE TITLE
Weird inheritance of `TypeVar` of types used as lower bounds in parametric types.

### ISSUE THREAD

**Issue by frankwswang** [JuliaLang/julia#55202]
MWE mentioned in a [Discourse post](https://discourse.julialang.org/t/best-practices-to-add-more-than-one-bound-to-type-parameters/117212/8?u=frankwswang):
```julia
julia> t = Array{T, N} where {N, T0<:Union{Integer, Float64}, NTuple{N, T0}<:T<:Union{Tuple{Real}, Tuple{Real, Real}}}
Array{T, N} where {N, T0<:Union{Float64, Integer}, NTuple{N, T0}<:T<:Union{Tuple{Real}, Tuple{Real, Real}}}

julia> [(1,2);;;] isa t
false
```
Apparently, `N` in `NTuple{N, T0}` is registered by the compiler; otherwise, `[(1,2);;;] isa t` would return `true`. We can verify this by defining and checking an alternative type `t2`:
```julia
julia> t2 = Array{T, N} where {N, T<:Union{Tuple{Real}, Tuple{Real, Real}}}
Array{T, N} where {N, T<:Union{Tuple{Real}, Tuple{Real, Real}}}

julia> [(1,2);;;] isa t2
true
```
However, when we test the following:
```julia
julia> [(Float32(1.0),)] isa t
true
```
The constraint on `T0<:Union{Float64, Integer}` is omitted even though `NTuple{N, T0}<:T<:Union{Tuple{Real}, Tuple{Real, Real}}`  is permitted in the first place.

Is this mismatch considered a "bug" or a "feature" of Julia's type system? Thanks!

**Comment by martinholters** [comment]
I think everything works as it should here.

As `Union{} <: Union{Float64, Integer}`, `T0=Union{}` is a valid choice, and `Tuple{Union{}} <: Tuple{Float32} <: Tuple{Real}`. (Except that `Tuple{Union{}}` cannot be constructed anymore in current Julia, but conceptually, this still holds, as one can consider `Tuple{Union{}}` and `Union{}` more or less equivalent.)

**Comment by frankwswang** [comment]
Thanks for the explanation! Now it makes sense now!

**Comment by frankwswang** [comment]
This is no longer directly related to the issue, but I wonder, is there a way to construct a `UnionAll` type with the lower bound of the type parameters excluding `Union{}`? If not, Maybe a new kind of operator other than `<:` can be defined, for example, `<<:`, so that 
```
t2 = Array{T, N} where {N, T0<<:Union{Integer, Float64}, NTuple{N, T0}<:T<:Union{Tuple{Real}, Tuple{Real, Real}}}
```
can be used to constrain the bound of `T0`?

**Comment by vtjnash** [comment]
You cannot define such a typevar (except if it is used in a Tuple), though you can define such a constraint on dispatch, given the exact method form of:
```
foo(::Type{Union{}}, slurp...)
```
with any leading arguments, to tell dispatch that you want to call that exact method regardless of what trailing arguments are passed, if any (which all get slurped up)

**Comment by frankwswang** [comment]
That's a good workaround! Thanks!
