### ISSUE TITLE
Syntax errors highlighting in Markdown rendering

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/julia#55253]
With the use of `JuliaSyntax`'s AST (rather than the token stream) in the recent `JuliaSyntaxHighlighting` bump, pseudo-julia code in docstring code blocks now gets highlighted as invalid syntax.

![image](https://github.com/user-attachments/assets/2b441eac-55a9-4f44-9182-3475789a767e)

This can be resolved in ~~two~~ three ways:
- Extend `JuliaSyntaxHighlighting` to take something like a `syntaxerrors::Bool` keyword argument that `Markdown` can use 
- Have `Markdown` strip `julia_error` annotations from the `JuliaSyntaxHighlighting.highlight` result
- Rewriting signatures to be valid Julia syntax

**Comment by nsajko** [comment]
A third solution would be to rewrite the signatures in to docs to use proper Julia syntax.

**Comment by tecosaur** [comment]
I'm currently leaning towards supporting a `errors::Bool` keyword argument in `JulyaSyntaxHighlighting`, and setting it to `false` in Markdown and `Expr` display.

Thoughts?

**Comment by KristofferC** [comment]
I don't think e.g. the Pkg.jl help (which is written in markdown) should have its code blocks rendered with Julia syntax highlighting since it isn't Julia code and it doesn't say that the code is Julia code.

**Comment by tecosaur** [comment]
As of the recent `JuliaSyntaxHighlighting` bump, this issue is resolved.

Kristoffer's request is implemented in #55465.
