### ISSUE TITLE
GMT.jl asserts on 1.11 backport branch

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#55263]
On https://github.com/JuliaLang/julia/pull/54925/commits/c2dcb7e6252fdab7960bf43e5642e218f7d66144

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f51eeca_vs_ec84807/GMT.primary.log

```
julia: /source/src/julia.h:1113: jl_svecref: Assertion `(((((jl_taggedvalue_t*)((char*)(t) - sizeof(jl_taggedvalue_t)))->header) & ~(uintptr_t)15)==(uintptr_t)(jl_simplevector_tag << 4))' failed.

[250] signal 6 (-6): Aborted
in expression starting at /home/pkgeval/.julia/packages/GMT/KSmVP/test/test_avatars.jl:3
```

**Comment by vtjnash** [comment]
I assume this is still the many known issues with GMT? https://github.com/JuliaLang/julia/issues/47003#issuecomment-1264782667
