### ISSUE TITLE
unexpected remaining example of a useless typeassert after #55229

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#55278]
```julia-repl
julia> function f(::AbstractArray{Int,N}) where {N}
           N::Int
           N
       end
f (generic function with 1 method)

julia> Core.Compiler.return_type(f, Tuple{Any})
Any

julia> versioninfo()
Julia Version 1.12.0-DEV.932
Commit cdd599c320d (2024-07-26 21:00 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-17.0.6 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

I guess the fact that `N` is a static parameter of the method is causing issues?

xref #38274, #55229

**Comment by Keno** [comment]
The type system doesn't know that the type is uninhabited:
```
julia> AbstractArray{Int,Int}
AbstractArray{Int64, Int64}
```

**Comment by aviatesk** [comment]
When performing a typeassert on a static parameter, it would be done to inform the compiler of the type when the static parameter is not known statically but code that depends on such static parameters whose types are not known at all in the first place is not a good code in practice.

**Comment by aviatesk** [comment]
We probably won't be working on this improvement, so I'll close it for now. If you come up with any cases where type assertions on static parameters would be useful, please let me know.

**Comment by Keno** [comment]
The correct way to fix this is to just make static parameters slots semantically like
```
N = $(Expr(:static_parameter, 1)))
```
at the top of the function. We don't do that right now for somewhat esoteric reasons having to do with closure conversion. Maybe something to revisit after the lowering rewrite.
