### ISSUE TITLE
terminfo parser is ineffective on FreeBSD

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#55274]
The intersection of https://github.com/JuliaLang/julia/pull/53682 with https://github.com/JuliaLang/julia/pull/50797 causes a test failure on FreeBSD: it has to compile `Base.info_color()`, so it has 1 rather than 0 expected precompiles. This is because FreeBSD doesn't use terminfo, it uses termcap[^1], so our terminfo parser always fails to find an entry on FreeBSD and we end up with a blank `TermInfo`. I had wondered why my Julia REPL colors disappeared, evidently this is why.

A couple of options I can think of:
- Fall back to using `tput`, which is what we used prior to #50797, when we can't find relevant terminfo files
- Vendor something like [`terminfo-db`](https://www.freshports.org/misc/terminfo-db/) in a JLL

The latter would be the more consistent with how we deal with other dependencies. The former would likely be rather involved.

cc @tecosaur

[^1]: At least [as of 2020](https://lists.freebsd.org/pipermail/freebsd-current/2020-May/076047.html), FreeBSD was looking to switch to terminfo, though I've not seen movement on that since then.

**Comment by tecosaur** [comment]
Hmm, I'm not specifically familiar with the freebsd builds. From a glance though, vendoring BSD's `terminfo-db` just with the BSD build seems like a promising option to me (presuming that can work).

**Comment by ararslan** [comment]
We'd want to vendor and use it everywhere to ensure consistency between platforms like we do with other dependencies. It's worth noting that even though I linked to the FreeBSD port for `terminfo-db`, it's not actually specific to FreeBSD in any way, it's just the directory-based terminfo database that's provided by the `ncurses` developers.

I've attempted making a JLL for this purpose in https://github.com/JuliaPackaging/Yggdrasil/pull/9165. The idea is that we'd include the JLL in `stdlib/` alongside the other JLLs and provide the build recipe in `deps/` to facilitate `USE_BINARYBUILDER=0` builds. The terminfo parser in Base can then use the artifact's location by default, perhaps prepended to `TERMINFO_DIRS`. That way, users can still opt into using the local definitions on their system by setting the `TERMINFO` variable or populating `~/.terminfo`, and we remain compliant with `terminfo(5)`.

**Comment by tecosaur** [comment]
Right, I'm with you: if we're going to go to the effort of vendoring it for FreeBSD, we might as well use it everywhere. It leaves us less exposed to what happens to be installed (or not) on the host system and it's only ~7 MB (and we could always strip out rare terminals and introduce a default fallback if we ever wanted to slim that down further).

Re-reading this bit of `terminfo(5)`:

<details>
<summary>Fetching Compiled Descriptions</summary>

```
   Fetching Compiled Descriptions
       The ncurses library searches for terminal descriptions in several
       places.  It uses only the first description found.  The library
       has a compiled-in list of places to search which can be
       overridden by environment variables.  Before starting to search,
       ncurses eliminates duplicates in its search list.

       •   If the environment variable TERMINFO is set, it is
           interpreted as the pathname of a directory containing the
           compiled description you are working on.  Only that directory
           is searched.

       •   If TERMINFO is not set, ncurses will instead look in the
           directory $HOME/.terminfo for a compiled description.

       •   Next, if the environment variable TERMINFO_DIRS is set,
           ncurses will interpret the contents of that variable as a
           list of colon-separated directories (or database files) to be
           searched.

           An empty directory name (i.e., if the variable begins or ends
           with a colon, or contains adjacent colons) is interpreted as
           the system location @TERMINFO@.

       •   Finally, ncurses searches these compiled-in locations:

           •   a list of directories (@TERMINFO_DIRS@), and

           •   the system terminfo directory, @TERMINFO@ (the compiled-
               in default).
```
</details>

I'd be inclined to add Julia's vendored terminfo dir to `@TERMINFO_DIRS@` / [`terminfo_dirs`](https://github.com/JuliaLang/julia/blob/master/base/terminfo.jl#L265), which I think is what you're proposing? (having the named "`TERMINFO_DIRS`" and also the environment variable `TERMINFO_DIRS` makes things a bit potentially ambiguous).

**Comment by ararslan** [comment]
What I was proposing was actually more like prepending it to the environment variable `TERMINFO_DIRS` but what you said makes more sense. 😅
