### ISSUE TITLE
Building LLVM on CI seems broken after Deps: after configuring CMake project, use cmake --build, not make ( #54538)

### ISSUE THREAD

**Issue by Zentrik** [JuliaLang/julia#55284]
After 8fd5aebadd9f80d808092630f3333a8565c35cbf, building LLVM on CI as part of https://github.com/JuliaCI/julia-buildkite/pull/345 just seems to hang until a cancellation signal at which points it starts building again. See https://buildkite.com/julialang/julia-buildkite/builds/1608#0190f950-0eb6-4fe3-938b-af69d186c40a for an example log with `-d` passed to `make`. 

I'm not sure why this is happening, but given 8fd5aebadd9f80d808092630f3333a8565c35cbf seemed to have some other issues (see https://github.com/JuliaLang/julia/pull/55091) I'm inclined to just revert it.

**Comment by vtjnash** [comment]
Maybe it just needs to be prefixed with + to make the jobserver work correctly? Or make sure we aren't running one of the broken kernels from circa 2019-2021?

**Comment by Zentrik** [comment]
I tried adding a + in [JuliaCI/julia-buildkite@`bee6422` (#345)](https://github.com/JuliaCI/julia-buildkite/pull/345/commits/bee64228b2a0419cf9bb50b88e7665338e7720dd) but I probably misunderstood something as I just got the error `.buildkite/utilities/build_julia.sh: line 55: +make: command not found`.
I'm not sure what the broken kernels you're referring to are.

**Comment by vtjnash** [comment]
The linux kernel epoll syscall was broken for several versions. The `+` goes in the makefile, not the call to it

**Comment by giordano** [comment]
To elaborate, what Jameson was referring to was to [add `+` at the beginning of the relevant line of a rule](https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html), to make it execute like [`make -n`](https://www.gnu.org/software/make/manual/html_node/Instead-of-Execution.html)
