### ISSUE TITLE
`Base.Bottom` is referred to in the `Union{}` doc string, but it's not public

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#55292]
https://docs.julialang.org/en/v1/base/base/#Union{}

Usage of objects named "Bottom" among packages: https://juliahub.com/ui/Search?type=symbols&q=Bottom&u=use

Solutions, two alternatives:

1. make `Base.Bottom` public
2. delete `Bottom` from the `Base` and from the doc string of `Union{}`. This could be a viable minor change, after a PkgEval, etc.

**Comment by Keno** [comment]
I don't see why this is a problem.

**Comment by nsajko** [comment]
It's a problem because `Base.Bottom` being referred to in the docs misleads new users to think that `Bottom` is public API. So I guess we want to either make it public, or delete it from the doc string?

**Comment by Keno** [comment]
> It's a problem because `Base.Bottom` being referred to in the docs misleads new users to think that `Bottom` is public API

Why is this implied. Lots of doc strings talk about internals. We very explicitly moved away from documented == public, because it just leads to things not being documented.

**Comment by nsajko** [comment]
OK then I was mistaken.

> We very explicitly moved away from documented == public

Ref?

**Comment by LilithHafner** [comment]
https://github.com/JuliaLang/julia/pull/50105/files#diff-3591da1fafe13d9fcae96e5b32a9492c6fb68b7e33ac0810b106b09b45d59534

https://docs.julialang.org/en/v1.11.0-rc2/manual/faq/#man-api

**Comment by nsajko** [comment]
OK, then this is only a possible documentation style issue. I'd prefer the docs (except the devdocs, of course) to only document public interfaces, to be more newbie-friendly? Probably not worth it keeping the issue open.

**Comment by LilithHafner** [comment]
I think the solution for doc style is option ii in https://github.com/JuliaDocs/Documenter.jl/issues/1506#issuecomment-2220854025
