### ISSUE TITLE
Repl no longer works with my startup.jl file 

### ISSUE THREAD

**Issue by ajahraus** [JuliaLang/julia#55313]
I have a `.julia\config\startup.jl` file which works great for v1.10, but crashes when I launch Julia v1.11

When I launch the REPL on v1.10, I get simply this: 
![image](https://github.com/user-attachments/assets/3435bddd-a998-459e-9d79-d93dc0de5662)

but when I launch the REPL on v1.11, I get this error, and my `startup.jl` didn't have any impact:
![image](https://github.com/user-attachments/assets/1667a984-370f-4479-b43c-09c4ca35b19c)

The contents of the startup.jl file are as follows:
```julia
atreplinit() do repl
    @eval using Revise, OhMyREPL
    @eval import REPL
    if !isdefined(repl, :interface)
        repl.interface = REPL.setup_interface(repl)
    end
    REPL.numbered_prompt!(repl)
end
```

This was installed via juliaup, and I observed the same behaviour on v1.11.0-rc1

Heres' the return value of `versioninfo()`

```julia
julia> versioninfo()
Julia Version 1.11.0-rc2
Commit 34c3a63147 (2024-07-29 06:24 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 20 × Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 20 default, 0 interactive, 10 GC (on 20 virtual cores)
Environment:
  JULIA_NUM_THREADS = auto
```

**Comment by KristofferC** [comment]
This is https://github.com/KristofferC/OhMyREPL.jl/issues/345
