### ISSUE TITLE
Implement checks to prevent the use of invalid or malicious values

### ISSUE THREAD

**Issue by mrfelpa** [JuliaLang/julia#55328]
Implement checks to prevent the use of invalid or malicious values and validate input parameters such ***as atype, mem, layout, ndims***,  and dims to ensure they are within expected limits and consistent.

**Comment by mrfelpa** [comment]
No, something like this could be implemented in the new_array() function for example: if ( atype = NULL || mem = NULL || layout = NULL) { jl_exceptionf (jl_argumenteero_tyoe, " invalid input parameters"); return NULL

**Comment by oscardssmith** [comment]
what purpose would this serve? Returning `Null` would be invalid here.

**Comment by mrfelpa** [comment]
This was an example that can be used to improve input parameters. to validate before being used in memory allocations or calculations...

**Comment by oscardssmith** [comment]
we already do this validation on the Julia side (where it can better be optimized)

**Comment by mrfelpa** [comment]
Okay, I understand
