### ISSUE TITLE
teach Julia that an identity comparison against a new mutable always returns false?

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#55339]
```julia-repl
julia> mutable struct M end

julia> f(x) = x === M()
f (generic function with 1 method)

julia> @code_typed f(M())
CodeInfo(
1 ─ %1 = %new(Main.M)::M
│   %2 = (x === %1)::Bool
└──      return %2
) => Bool

julia> versioninfo()
Julia Version 1.12.0-DEV.968
Commit 0ef8a91e490 (2024-08-01 14:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-17.0.6 (ORCJIT, znver2)
```

Seems like it should be possible to teach Julia that `f` always returns the constant `false`?

**Comment by KristofferC** [comment]
Out of curiosity, does the desire for this optimization come from any real code?

**Comment by nsajko** [comment]
no :grin:

**Comment by KristofferC** [comment]
Okay, I'm not sure how useful it is to try to think up "optimizations" that have no basis in real code because optimizations come with a cost (maintenance-wise and compile-time-wise). So unless there is some real use for it, it shouldn't be added.

**Comment by vtjnash** [comment]
Julia actually may already know this via LLVM, and yes, don't open issues for feature requests
