### ISSUE TITLE
Explicit calls to type inference in array comprehensions cause equivalent expressions to have different values

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaLang/julia#55350]
I'm sure this issue is very well known among core developers, but I though it wouldn't hurt to open a Github issue to track it. If this is already covered by a different open issue, feel free to close this one.

Julia is a dynamic language, so the value of an expression should only depend on the runtime values of the components of the expression. However, this is not always the case when using generators or array comprehensions, which I think is because the implementation uses `Core.Compiler.return_type` (or similar) somewhere along the line when the input collections are empty. (Sorry, I haven't actually read through the relevant code lately, but I've looked at it in the past.)

Here's a simple example of two expressions where the components of the expression have the exact same values, but the values of the expressions are different:

Define input values:

```julia
const a = Int[]
const b = Int[]
c = Int[]
d = Int[]
g(::Vector{Int}) = 1
g(::Vector{Any}) = 2
```

Evaluate expressions:

```julia
julia> a == c, b == d
(true, true)

julia> g([x*y for x in a for y in b])
1

julia> g([x*y for x in c for y in d])
2
```

**Comment by JeffBezanson** [comment]
This should go in the docstring for `collect`, and the docs for `[]` should be linked to that.
