### ISSUE TITLE
at-doc return type depends on whether REPL is loaded

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#55438]
Normally, the `@doc` macro returns a `Markdown.MD` object:
```sh
% julia -e "println(typeof(@doc Real))"
Markdown.MD
```
However, in nightly (1.12.0-DEV.1030) the return type is `Base.Docs.DocStr` unless the `REPL` module is imported:
```sh
% ./julia -e "println(typeof(@doc Real))"
Base.Docs.DocStr
% ./julia -e "import REPL; println(typeof(@doc Real))"
Markdown.MD
```
This seems like a bug — I noticed it because of a test failure https://github.com/JuliaIO/StructIO.jl/pull/30 in the StructIO.jl package (since package tests do not load the REPL module by default, a test for a documentation string was failing).

**Comment by thofma** [comment]
Dup of https://github.com/JuliaLang/julia/issues/54664

**Comment by stevengj** [comment]
Closing as duplicate.
