### ISSUE TITLE
Shipped Windows binaries with new codesigning need `.ji` checksums updated

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#55491]
Making an issue in case people start wondering why.

Any shipped Windows build since https://github.com/JuliaCI/julia-buildkite/pull/374 will be hitting re-precompilation of stdlibs now

![image](https://github.com/user-attachments/assets/285db284-cb6c-47c4-92ff-dd17f68f6a40)

```
┌ Debug: Rejecting cache file C:\hostedtoolcache\windows\julia\nightly\x64\share\julia\compiled\v1.12\REPL\u0gqU_Miz3B.ji because C:\hostedtoolcache\windows\julia\nightly\x64\share\julia\compiled\v1.12\REPL\u0gqU_Miz3B.dll has an invalid checksum
└ @ Base loading.jl:3868
```

See https://github.com/JuliaCI/julia-buildkite/pull/374#issuecomment-2289094494 for details

**Comment by DilumAluthge** [comment]
IMO this is a release-blocker, so I'm adding it to the milestone, but lmk if you disagree.

**Comment by staticfloat** [comment]
X-ref: https://github.com/JuliaCI/julia-buildkite/pull/376

**Comment by IanButterworth** [comment]
Confirmed fixed on https://github.com/JuliaLang/Pkg.jl/actions/runs/10439918770/job/28909158065?pr=3983
