### ISSUE TITLE
`Iterators.rest` gives wrong result for `AbstractRange`

### ISSUE THREAD

**Issue by DatName** [JuliaLang/julia#55578]
`Iterators.rest` iteration for `OrdinalRange{Int64}` and equivalent `Vector{Int64}` are different:
```
julia> collect(Iterators.rest(1:2, 1)) # OrdinalRange
1-element Vector{Int64}:
 2
```
while
```
 julia> collect(Iterators.rest(collect(1:2), 1)) # Vector
2-element Vector{Int64}:
 1
 2
```
Result probably should be exactly the same here.

---
Julia Version 1.10.4

**Comment by jishnub** [comment]
The starting point of the iteration state is a bit arbitrary
```julia
julia> iterate(collect(1:2))[2]
2

julia> iterate(1:2)[2]
1
```
Once this is accounted for, the result is consistent.

**Comment by DatName** [comment]
Well, it can be fixed like this, of course, but since `Iterators.rest`, according to docs, "yields the same elements as iter, but starting at the given state", and we have same values for `1:2` and `[1,2]` at state `1` or `2`:
```
 getindex(1:2, 1) == getindex([1,2], 1)
 ```
 it seems like we should have same output for `Iterators.rest` as well.

**Comment by Seelengrab** [comment]
The state passed to `iterate`does not necessarily always correspond to what `getindex` expects as an index; the two are not intrinsically linked.

**Comment by simeonschaub** [comment]
As pointed out above this is not part of the contract of `Iterators.rest`. What you want is `Iterators.drop` or a view
