### ISSUE TITLE
Choose number of OpenBLAS threads based on process affinity

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLang/julia#55572]
Similar to https://github.com/JuliaLang/julia/pull/42340 we should probably also consider the affinity of the Julia process when deciding how many BLAS threads we spawn by default. Currently, we don't:

```julia-repl
➜  sca50297@cl7fr1 ~  julia --threads=auto -q
julia> using LinearAlgebra; BLAS.get_num_threads()
16

julia> Threads.nthreads()
32

julia> Sys.CPU_THREADS
32

julia>

➜  sca50297@cl7fr1 ~  taskset -c 0,1 julia --threads=auto -q
julia> using LinearAlgebra; BLAS.get_num_threads()
16

julia> Threads.nthreads()
2
```

In the latter case, despite the fact that our process is restricted to 2 hardware threads, we spawn 16 BLAS threads. That never seems to be a good choice.

**Comment by carstenbauer** [comment]
Concrete use case where this will be helpful: HPC. For an MPI application, for example, SLURM automatically sets the affinity for each MPI rank (Julia process). Currently, we are oversubscribing the system as demonstrated above (as @PetrKryslUCSD can tell, because he ran into this issue). If we respected the affinity mask, that'd be much better.

**Comment by carstenbauer** [comment]
Interestingly, Taka has [mentioned](https://github.com/JuliaLang/julia/pull/42340#issuecomment-932835362) the BLAS case as well. He found that OpenBLAS respected the affinity and did the "right thing". Clearly that's not the case anymore, at least not for my test above (Julia 1.10.4).

**Comment by giordano** [comment]
Related issue: #46226, where it's suggested to use libuv to get the number of available CPUs

**Comment by carstenbauer** [comment]
Related indeed, but note that #46226 tasks about Julia threads not BLAS threads.

**Comment by giordano** [comment]
This also works with MPI (I'm using OpenMPI here):
```console
$ mpirun -np 6 --map-by node:PE=8 ./julia -e 'println(@ccall uv_available_parallelism()::Cint)'
8
8
8
8
8
8
$ mpirun -np 4 --map-by node:PE=12 ./julia -e 'println(@ccall uv_available_parallelism()::Cint)'
12
12
12
12
$ mpirun -np 2 --map-by node:PE=24 ./julia -e 'println(@ccall uv_available_parallelism()::Cint)'
24
24
```
