### ISSUE TITLE
Type instability when using intrinsics as higher order functions

### ISSUE THREAD

**Issue by PatrickHaecker** [JuliaLang/julia#55584]
I observed a performance problem and could reduce it to the following:
```julia
using BenchmarkTools

piping(x) = -(x |> Base.ctlz_int)
no_piping(x) = -Base.ctlz_int(x)

const x = UInt64(16)
@btime piping($x)
@btime no_piping($x)
```
results in
```julia
julia> @btime piping($x)
  22.965 ns (1 allocation: 16 bytes)
0xffffffffffffffc5

julia> @btime no_piping($x)
  1.465 ns (0 allocations: 0 bytes)
0xffffffffffffffc5
```

I had expected to get exactly the same native code for both `piping` and `no_piping`. When looking at `@code_native no_piping(x)`, the code looks exactly how I expected it, basically
```assembly
lzcnt   rax, rdi
neg     rax
```
whereas `@code_native piping(x)` looks like a mess with using SSE registers and what not.

```
julia> versioninfo()
Julia Version 1.11.0-rc2
Commit 34c3a63147b (2024-07-29 06:24 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 12th Gen Intel(R) Core(TM) i7-1270P
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, alderlake)
Threads: 16 default, 0 interactive, 8 GC (on 16 virtual cores)
```

The problem seems to be the same on Julia 1.10.4.

**Comment by gbaraldi** [comment]
Just using the intrinsic is enough to trigger this difference and it seems to be intrinsic specific
```julia-repl
julia> foo(x) = Base.ctlz_int(x)
foo (generic function with 3 methods)

julia> piping(x) = (x |> Base.ctlz_int)
piping (generic function with 6 methods)

julia> @code_typed piping(UInt64(16))
CodeInfo(
1 ─ %1 = invoke Main.:|>(x::UInt64, Base.ctlz_int::Core.IntrinsicFunction)::Any
└──      return %1
) => Any

julia> piping(x) = (x |> foo)
piping (generic function with 7 methods)

julia> @code_typed piping(UInt64(16))
CodeInfo(
1 ─ %1 = Base.ctlz_int(x)::UInt64
└──      return %1
) => UInt64
```

**Comment by mbauman** [comment]
Don't use intrinsics?  The trouble is that they don't have unique types, so when you pass them to a higher order function (like pipe, map, etc), Julia loses the ability to optimize them.  Wrapping them in a normal Julia function is enough to fix this.

**Comment by gbaraldi** [comment]
You can use leading_zeros directly which just calls the intrinsic directly

**Comment by oscardssmith** [comment]
I don't think so.

**Comment by PatrickHaecker** [comment]
Thanks a lot for these insights. So this is obviously a user error.

However, before we close it: Can we learn something from it so that it ideally does not happen again to future users (which might be future me :-))?
Ideally we could add something to the documentation as I haven't found anything (besides: "Do not use internal functions" which does only help so much if you need internal functions as you cannot implement that functionality in any other way with the same performance).

For an optimized algorithm, I basically ended up looking up in LLVM which operation is supported, and checked which Julia function supports this operation. That's how I ended up at the intrinsic. Is there any way to lookup the "wrapper" function based on the intrinsic (besides searching through the whole source code)?

Just as an example: I also use `trunc_int` (basically identical to [int.jl](https://github.com/JuliaLang/julia/blob/733b3f55a1daa7afd2a6804e06dba46fc2f2cfa0/base/int.jl#L544)). How would I replace that one without using an intrinsic? I can write a wrapper myself outside of Base, obviously, but this also uses internal functionality (although at least limited to one place).
