### ISSUE TITLE
Can't sum partially initialized non-isbits Hermitian or Symmetric matrix with Diagonal or SymTridiagonal

### ISSUE THREAD

**Issue by araujoms** [JuliaLang/julia#55590]
```julia
using LinearAlgebra
a = Matrix{BigFloat}(undef, 2,2)
a[1] = 1; a[3] = 1; a[4] = 1
a = Hermitian(a)
b = Symmetric(a)
c = Diagonal([1,1])
d = SymTridiagonal([1 1;1 1])
a+c
a+d
b+c
b+d
```
I've also tested with `UpperTriangular`, `LowerTriangular`, `UnitUpperTriangular`, `UnitLowerTriangular`, they work fine.

I've noticed this issue when testing my package with Julia 1.11. It showed up because when I do
```julia
using LinearAlgebra
a = Hermitian(BigFloat.([1 1;1 1]))
b = a + a
```
I get a partially initialized `b`, unlike in previous versions.

**Comment by mbauman** [comment]
So an MWE for the regressed case is:

```julia
julia> using LinearAlgebra

julia> (2*Hermitian(BigFloat.([1 1;1 1]))) + Diagonal([1,1])
ERROR: UndefRefError: access to undefined reference
```

This is probably from #54473.

**Comment by araujoms** [comment]
Indeed, that's a regression, but the cause is #52942.

**Comment by jishnub** [comment]
These seem to fail on v1.10.5 as well

**Comment by araujoms** [comment]
The regressed case is not the first code I posted, but instead
```julia
using LinearAlgebra
(2*Hermitian(BigFloat.([1 1;1 1]))) + Diagonal([1,1])
```
