### ISSUE TITLE
Do some constant propagation before type inference runs

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#5560]
It would be good to run some constant propagation before type inference runs for cases in which a type parameter is really constant, but we don't know because we compute with it before. E.g:

```
type foo{m}; end
inv{m}(x::foo{m}) = foo{-m}()
id{m}{x::foo{m}) = foo{m}()
```

For `id`, we get a nice

```
julia> code_typed(id,(foo{1},))
1-element Array{Any,1}:
 :($(Expr(:lambda, {:x}, {{},{{:x,foo{1},0}},{}}, quote  # /Users/kfischer/.julia/REPL/scripts/repl.jl, line 1:
        return $(Expr(:new, foo{1}))::foo{1}
    end)))
```

whereas for `inv`, we get 

```
julia> code_typed(inv,(foo{1},))
1-element Array{Any,1}:
 :($(Expr(:lambda, {:x}, {{},{{:x,foo{1},0}},{}}, quote  # /Users/kfischer/.julia/REPL/scripts/repl.jl, line 1:
        return top(apply_type)(foo,top(box)(Int64,top(neg_int)(1))::Int64)::Type{_<:foo{m}}()::foo{m}
    end)))
```

**Comment by maleadt** [comment]
Just ran into this trying to pass a const computation to a generated function by means of a `Val` type:

```julia
@generated function foobar{D}(::Type{Val{D}})
    return :($D)
end

function working1()
    const size = 12
    return foobar(Val{size})
end

const size = 3*4
function working2()
    return foobar(Val{size})
end

function broken()
    const size = 3*4
    return foobar(Val{size})
end

println(@code_typed working1())
@inferred working1()

println(@code_typed working2())
@inferred working2()

println(@code_typed broken())
@inferred broken()
```

This broke some Julia/CUDA code where we can't perform the call to `foobar` dynamically. We use it to implement `@cuSharedMemory(T, dims...)` where we need a generated function to determine the type of T in order to allocate a certain amount of memory.

**Comment by timholy** [comment]
Might be worth pointing out that syntax like #22056 (esp. the first comment) might be a way for the programmer to specify exactly which kind of constant propagation should be performed. Presumably this makes it a finite problem.

**Comment by vtjnash** [comment]
> Presumably this makes it a finite problem.

I'm pretty sure it doesn't. But with the new inference convergence, https://github.com/JuliaLang/julia/pull/21933 should do it.
