### ISSUE TITLE
repl completion shows qualification warning inline

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#55612]
```
julia> using Downloads

julia> download(WARNING: both Downloads and Base export "download"; uses of it in module Main must be qualified
```

i.e. typing `download(` will cause the warning to print.

**Comment by Keno** [comment]
Will be fixed by the full binding partition PR, since this will no longer by a binding resolution point.

**Comment by IanButterworth** [comment]
Will that be backported to 1.11?

**Comment by Keno** [comment]
No

**Comment by IanButterworth** [comment]
Ok. We need a solution for 1.11 then. Disable the check if in tab completion mode? Would that be possible?

**Comment by Keno** [comment]
It's not easy, because the warning is being emitted from deep in the binding resolution code as soon as someone asks the question about the binding.

**Comment by IanButterworth** [comment]
I looked into fixing this by disallowing anything to print to stdout/stderr during calls to `complete_line`, but `redirect_stderr` doesn't appear to redirect c prints that are to `JL_STDERR`. Is that expected?

**Comment by IanButterworth** [comment]
https://github.com/JuliaLang/julia/pull/55959 was reverted. This is fixed by [removing the c warning](https://github.com/JuliaLang/julia/pull/56103), and on 1.11 by additionally backporting [the improved hints].(https://github.com/JuliaLang/julia/pull/53469)
