### ISSUE TITLE
PROBLEM: Function `deepcopy()` doesn't Guarantee the Key Order of a Dictionary

### ISSUE THREAD

**Issue by Umut-Can-Physics** [JuliaLang/julia#55666]
I had created the following **dictionary** structure with 12 elements:

`Dict{Array, Array} with 12 entries:
  [[1, 1, 0, 0], [0, 1, 1, 0]] => [52, 4]
  [[0, 1, 0, 1], [2, 0, 0, 0]] => [7, 4]
  [[2, 0, 0, 0], [0, 1, 0, 1]] => [61, 4]
  [[1, 0, 1, 0], [1, 0, 1, 0]] => [23, 4]
  [[0, 2, 0, 0], [1, 0, 1, 0]] => [24, 4]
  [[1, 0, 1, 0], [0, 2, 0, 0]] => [33, 4]
  [[0, 0, 2, 0], [2, 0, 0, 0]] => [8, 4]
  [[2, 0, 0, 0], [0, 0, 2, 0]] => [71, 4]
  [[0, 2, 0, 0], [0, 2, 0, 0]] => [34, 4]
  [[1, 0, 0, 1], [1, 1, 0, 0]] => [15, 4]
  [[1, 1, 0, 0], [1, 0, 0, 1]] => [42, 4]
  [[0, 1, 1, 0], [1, 1, 0, 0]] => [16, 4]
`

When I apply the `deepcopy(dict)` to the upward dictionary called `dict`, I get:

`Dict{Array, Array} with 12 entries:
  [[0, 1, 1, 0], [1, 1, 0, 0]] => [16, 4]
  [[0, 1, 0, 1], [2, 0, 0, 0]] => [7, 4]
  [[2, 0, 0, 0], [0, 1, 0, 1]] => [61, 4]
  [[1, 0, 1, 0], [1, 0, 1, 0]] => [23, 4]
  [[0, 2, 0, 0], [1, 0, 1, 0]] => [24, 4]
  [[1, 0, 1, 0], [0, 2, 0, 0]] => [33, 4]
  [[2, 0, 0, 0], [0, 0, 2, 0]] => [71, 4]
  [[0, 2, 0, 0], [0, 2, 0, 0]] => [34, 4]
  [[0, 0, 2, 0], [2, 0, 0, 0]] => [8, 4]
  [[1, 0, 0, 1], [1, 1, 0, 0]] => [15, 4]
  [[1, 1, 0, 0], [1, 0, 0, 1]] => [42, 4]
  [[1, 1, 0, 0], [0, 1, 1, 0]] => [52, 4]
`

**Notice that, the key is re-ordered!** When I try to reproduce a toy example in order to prove upward problem, but I failed. I think, the `deepcopy()` function preserve the key order for small dictionaries. I can't find well-wrote documentation to address the problem I faced. Please update the documentation: https://github.com/JuliaLang/julia/blob/master/base/deepcopy.jl

**Comment by oscardssmith** [comment]
I don't think this is a bug. dictionaries aren't ordered.

**Comment by gbaraldi** [comment]
We don't guarantee ordering of the the Dict type in julia. So if you are relying on it there's already a bug.

**Comment by ufechner7** [comment]
Use [OrderedDict](https://juliacollections.github.io/OrderedCollections.jl/latest/ordered_containers.html) if you need an ordered dictionary.
