### ISSUE TITLE
`numerator` and `denominator` should be defined for `Complex{<:Rational}` and for `Complex{<:Integer}`

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#55693]
Currently `//` may return non-`Rational` `Number` values. It'd make sense for these rational-like numbers to support `numerator` and `denominator`. Xref  #55661.

**Comment by nhz2** [comment]
I don't think it makes sense for complex numbers to have a numerator or denominator, because trying to compute an effective numerator or denominator can lead to errors.

Is there a case where this would be useful?

**Comment by nsajko** [comment]
> because trying to compute an effective numerator or denominator can lead to errors

Is that really an issue? By that logic it wouldn't make sense to have `lcm` on integers, because it may throw `OverflowError`.

> Is there a case where this would be useful?

The idea is that any `//` return value (or at least those which are numbers) should be "rational-like", thus it should support `numerator` and `denominator`. Then we could document that, fixing #55661.

This would also improve consistency, given that integers already support `numerator` and `denominator`.

**Comment by nhz2** [comment]
I don't think the return value of `//` needs to be rational like, it just needs to be an exact version of `/`, for example:

```
julia> [1,2,3,4] // 3
4-element Vector{Rational{Int64}}:
 1//3
 2//3
  1
 4//3

julia> numerator(ans)
ERROR: MethodError: no method matching numerator(::Vector{Rational{Int64}})
```
