### ISSUE TITLE
read(stdin, Char) behaves differently in REPL vs when run as a script in VSCode

### ISSUE THREAD

**Issue by sadish-d** [JuliaLang/julia#55692]
I have a .jl file with one line script:

```
i = read(stdin, Char)
```

If I run it in VSCode using the play button, and type `ab` in the REPL (without pressing the return key), I get:

```
a'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

julia> i
'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
```

`i` takes the second character entered: `b`.

Here is the behavior in REPL (need to press the return key after typing ab)

```
julia> i = read(stdin, Char)
ab
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

julia> b
ERROR: UndefVarError: `b` not defined

julia> i
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
```

`i` takes the first character entered: `a`.

possibly related: https://github.com/julia-vscode/julia-vscode/issues/785

versioninfo:
```
julia> versioninfo()
Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Comment by fredrikekre** [comment]
This looks like a problem on the VS Code side so nothing to fix here.

> possibly related: https://github.com/julia-vscode/julia-vscode/issues/785

Probably, you can comment there or open a new issue on that repo if you don't think it is the same.
