### ISSUE TITLE
Type instabilities when using `mapslices`

### ISSUE THREAD

**Issue by albertomercurio** [JuliaLang/julia#55714]
Hello,

I noticed type-instabilities when using `mapslices` on an `Array`. Here there is a MWE

```julia
julia> function test(A)
           return mapslices(sum, A, dims=(3,4))
       end
test (generic function with 1 method)

julia> A = rand(2,2,2,2)
2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.975298  0.351959
 0.159086  0.200224

[:, :, 2, 1] =
 0.78432   0.0186732
 0.495407  0.110606

[:, :, 1, 2] =
 0.922721  0.367518
 0.062931  0.731392

[:, :, 2, 2] =
 0.953113  0.792762
 0.497891  0.652423

julia> test(A)
2×2×1×1 Array{Float64, 4}:
[:, :, 1, 1] =
 3.63545  1.53091
 1.21532  1.69464

julia> @code_warntype test(A)
MethodInstance for test(::Array{Float64, 4})
  from test(A) @ Main REPL[38]:1
Arguments
  #self#::Core.Const(test)
  A::Array{Float64, 4}
Body::Any
1 ─ %1 = Core.tuple(3, 4)::Core.Const((3, 4))
│   %2 = (:dims,)::Core.Const((:dims,))
│   %3 = Core.apply_type(Core.NamedTuple, %2)::Core.Const(NamedTuple{(:dims,)})
│   %4 = Core.tuple(%1)::Core.Const(((3, 4),))
│   %5 = (%3)(%4)::Core.Const((dims = (3, 4),))
│   %6 = Core.kwcall(%5, Main.mapslices, Main.sum, A)::Any
└──      return %6
```

I was wondering first if there is a quick fix for that, like using other functions in a type stable way.

This is my system information

```julia
julia> versioninfo()
Julia Version 1.10.5
Commit 6f3fdf7b362 (2024-08-27 14:19 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × 13th Gen Intel(R) Core(TM) i9-13900KF
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, goldmont)
Threads: 8 default, 0 interactive, 4 GC (on 32 virtual cores)
Environment:
  LD_LIBRARY_PATH = /usr/local/lib:
  JULIA_NUM_THREADS = 8
```

**Comment by jishnub** [comment]
This is fixed on Julia nightly (I suspect https://github.com/JuliaLang/julia/pull/54928 is the fix).

**Comment by albertomercurio** [comment]
Oh yes. I thought that this PR was merged in the new 1.10.5 release. I actually don't understand how PRs are managed in the various versions of Julia.

**Comment by jishnub** [comment]
The way it works is that PRs are merged to master and are included in the next minor version release, and bugfixes are back-ported to existing releases (currently the 1.10.x series) and upcoming release candidates (currently the 1.11.x series). This wasn't back-ported, as it's more of a performance enhancement than a bugfix.

**Comment by albertomercurio** [comment]
Ok clear. So given a PR, it is not direct if if will be included in the next release. I depends on future cherry-pick from master, right?

**Comment by jishnub** [comment]
Yes, it'll only be included in new patch releases for existing minor versions if it has been back-ported to the release branch. It'll definitely be included in the next minor release that will branch off master (which, currently, is 1.12.0)
