### ISSUE TITLE
`libutf8proc.a: error adding symbols: file format not recognized` blocking build on Windows 11 on ARM via WSL

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#55724]
Error when building on WIndows 11 on ARM via WSL (for Linux, not trying to cross-compile):
```
    LINK src/flisp/flisp
/usr/bin/ld: /mnt/c/users/nicho/repos/julia/usr/lib/libutf8proc.a: error adding symbols: file format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:109: /mnt/c/users/nicho/repos/julia/src/flisp/flisp] Error 1
make[1]: *** [Makefile:363: flisp/libflisp.a] Error 2
make: *** [Makefile:62: julia_flisp.boot.inc.phony] Error 2
```

Bisected to: [0be0b389e300c05abde796f68abbdd95b938f7ad] support Unicode 15.1 via utf8proc 2.9.0 (#51799)

**Comment by giordano** [comment]
Since utf8proc is compiled locally from source it sounds like a problem in your toolchain? What compiler are you using? What version? What's the output of
```
file /mnt/c/users/nicho/repos/julia/usr/lib/libutf8proc.a
```
?

**Comment by BioTurboNick** [comment]
Hmm. Why just that one file though? A toolchain issue is possible, though I don't think I did anything unusual.

The output is:
```
/mnt/c/users/nicho/repos/julia/usr/lib/libutf8proc.a: current ar archive
```

**Comment by BioTurboNick** [comment]
```
utf8proc.o: Intel amd64 COFF object file, no line number info, not stripped, 8 sections, symbol offset=0x53f14, 62 symbols, 1st section name ".text"
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start
```

Possibly relevant is that I initially started with Make.user pointing to mingw. I removed that line since, and had done `make cleanall` many times.

Just investigated further, and `make -C deps clean-utf8proc` fixed it. Should `cleanall` have caught this? Or should the build process have noticed something needed rebuilding? Or is this just an expected hazard of this kind of thing? If the latter I'll close this.

**Comment by giordano** [comment]
> ```
>  Intel amd64 COFF object file
> ```

That's the wrong format, and it explains the error message.

**Comment by giordano** [comment]
> Should cleanall have caught this?

I think `make cleanall` deletes the entire `usr/` subdir, no?

> Or should the build process have noticed something needed rebuilding?

Make checks timestamps, not file formats.

**Comment by BioTurboNick** [comment]
> > Should cleanall have caught this?
> 
> I think `make cleanall` deletes the entire `usr/` subdir, no?

Yeah, though it doesn't do anything to `deps/scratch` subfolders, which seems to be where the dependencies get compiled. Based on the `make VERBOSE=1` output I was seeing, all it was doing was copying the `libutf8proc.a` file from the `scratch\utf8proc-<hash>` subfolder.  `make -C deps clean-utf8proc` actually removes the `libutf8proc.a` file.

**Comment by giordano** [comment]
Ah, yeah, I don't think `cleanall` is supposed to touch the cache in `deps`, on a `git bisect` run running `make cleanall` is useful but if it cleaned the also the deps cache you'd be downloading, unpacking and installing llvm all the time.
