### ISSUE TITLE
REPL precompilation workload is broken

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#55753]
Maybe this broke in https://github.com/JuliaLang/julia/pull/55210 ?

Likely causing higher latency.

This is with [debug output on](https://github.com/JuliaLang/julia/blob/945517ba4e15f7470b8790a696ba5404ef047f2f/stdlib/REPL/src/precompile.jl#L19)

![Screenshot 2024-09-12 at 8 47 23 AM](https://github.com/user-attachments/assets/a74c341e-2b32-4fbe-994d-ca8cb11459c3)

![Screenshot 2024-09-12 at 8 47 06 AM](https://github.com/user-attachments/assets/8335a547-5d90-4f29-8213-15ef8bfcef38)

![Screenshot 2024-09-12 at 8 45 06 AM](https://github.com/user-attachments/assets/febd111e-f9ad-48a4-b1d7-6c3107c3d4a1)

**Comment by vtjnash** [comment]
Looks like we need to set the active_module for the precompile REPL to the current module, so that the effects are preserved
