### ISSUE TITLE
v1.11-rc3: precompilation fails for BandedMatrices.jl

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#55787]
We got a report of pre-compilation failing only on Julia v1.11:

https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/issues/454

I haven't reproduced it locally but it seems to be crashing CI:

https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/pull/455

@tobydriscoll should be able to provide further details about his setup.

**Comment by jishnub** [comment]
The CI failure seems to be an actual test that doesn't succeed, and not a precompilation crash

**Comment by dlfivefifty** [comment]
No I think the “pre-job” is crashing because of the error. 

Though I didn’t make the CI pre-job, didn’t you @jishnub? Can we simplify the CI and try again?

**Comment by dlfivefifty** [comment]
Sorry the CI wasn’t working before as it was crashing on the pre-job. I see now it’s updated and yes the tests are pssing
