### ISSUE TITLE
Julia nightly failure to precompile REPL

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#55800]
In the most recent run of the GAP.jl CI runs with Julia nightly it fails to precompile REPL. Note that GAP.jl has REPL in its dependencies.

For example [this log](https://github.com/oscar-system/GAP.jl/actions/runs/10922171634/job/30315886858):
```
  12985.1 ms  ✓ AbstractAlgebra
           ✗ REPL
  28704.7 ms  ✓ Parsers
   1370.0 ms  ✓ JSON
           ✗ Pkg → REPLExt
    462.3 ms  ✓ GAP_lib_jll
    618.2 ms  ✓ GAP_pkg_juliainterface_jll
   3727.9 ms  ✓ Aqua
           ✗ Documenter
           ✗ GAP
  21 dependencies successfully precompiled in 65 seconds. 32 already precompiled.

ERROR: LoadError: The following 3 direct dependencies failed to precompile:

GAP --code-coverage=@/home/runner/work/GAP.jl/GAP.jl --color=yes --check-bounds=yes --warn-overwrite=yes --depwarn=error --inline=yes --startup-file=no --track-allocation=none --check-bounds=yes --compiled-modules=yes 

Failed to precompile GAP [c863536a-3901-11e9-33e7-d5cd0df7b904] to "/home/runner/.julia/compiled/v1.12/GAP/jl_ST05dz".
WARNING: Method definition formatdoc(Base.Docs.DocStr) in module REPL at /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.12/REPL/src/docview.jl:79 overwritten in module REPL at /cache/build/builder-amdci4-3/julialang/julia-master/usr/share/julia/stdlib/v1.12/REPL/src/docview.jl:79.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
┌ Error: Unexpected error (Review REPL precompilation with debug_output on):
│ 2004lERROR: Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
└ @ REPL.Precompile /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.12/REPL/src/precompile.jl:26
ERROR: LoadError: Failed to precompile REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] to "/home/runner/.julia/compiled/v1.12/REPL/jl_QGthvI".
Stacktrace:
...
```

**Comment by fingolfin** [comment]
@IanButterworth might this be related to your PR #55782?

**Comment by IanButterworth** [comment]
Why is it recompiling REPL and not using the bundled one? Are you overriding JULIA_DEPOT_PATH without the trailing : ?

**Comment by fingolfin** [comment]
No, we are not messing with depot paths. I have no idea why it might recompile REPL

**Comment by vtjnash** [comment]
AFAICT, the error occurs because the precompile script starts with trying to execute
```
import REPL
REPL.activate(REPL.Precompile; interactive_utils=false)
```

And whether or not that succeeds depends on whether those global mutations are able to succeed before the activate call works. We should probably move that into the atreplinit callback, so it runs inside REPL.Precompile before the Base.run_std_repl call instead of in Main afterwards

**Comment by IanButterworth** [comment]
That doesn't work out of the box because `mistate === nothing` at the time `atreplinit` is evaluated
https://github.com/JuliaLang/julia/blob/02549d5c54ec8ac8c7e62ea470803350bb3d1899/stdlib/REPL/src/REPL.jl#L763

**Comment by IanButterworth** [comment]
@fingolfin @benlorenz can you confirm that this is fixed on your CI. Both the error and the fact that REPL was being precompiled at all (Pkg.test should be using the bundled stdlib caches)

**Comment by IanButterworth** [comment]
Great. Thanks
