### ISSUE TITLE
invalid usage of `@assume_effects` in `base/irrationals.jl`

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#55874]
There are four methods with `@assume_effects :total` applied to the entire method in `base/irrationals.jl`:

https://github.com/JuliaLang/julia/blob/6e5e87b2cafda840b90347c2e74202d2608d7c29/base/irrationals.jl#L55-L55

https://github.com/JuliaLang/julia/blob/6e5e87b2cafda840b90347c2e74202d2608d7c29/base/irrationals.jl#L70-L71

https://github.com/JuliaLang/julia/blob/6e5e87b2cafda840b90347c2e74202d2608d7c29/base/irrationals.jl#L113-L120

Issues:
* The `:total` effect is too powerful and not future-proof. I guess what's actually desired is just `:foldable`.
* It's not valid to apply `@assume_effects` to the `::AbstractIrrational` methods, because users may define custom subtypes of `AbstractIrrational`, and thus calls like `BigFloat(::AbstractIrrational)` or `big(::AbstractIrrational)` may execute arbitrary code. That said ...
* It's not valid to apply `@assume_effects` even just for `::Irrational`, because users may define custom subtypes of `Irrational`! Example:

```julia
# in a user package
struct IrrationalSymbol end
function big(::Irrational{IrrationalSymbol})
    execute_arbitrary_code()
end
```

This seems perfectly legal, or at least it's not type piracy.

The solution seems simple: define a `Union` of all known irrational constants, something like the following, then dispatch on it for methods that have `@assume_effects`, instead of on `AbstractIrrational` or on `Irrational`:

```julia
const _KnownIrrational = (ℯ, π, MathConstants.γ, MathConstants.catalan, MathConstants.φ)
```

This will ensure calls involving the known constants are foldable, and allow the unsafe `@assume_effects` annotations to be deleted. Will make a PR later.

**Comment by aviatesk** [comment]
After looking at the blame, it seems that those `@assume_effects` were added by me in JuliaLang/julia#44776 as replacements for the previous `@pure`, but I agree that `@assume_effects :total` was too strong. It should have been replaced with `:foldable`, and we also need to restrict the annotation to known concrete types as suggested.

**Comment by vtjnash** [comment]
It isn't technically valid to be foldable either (there isn't technically any valid annotations to assume here), as it references global state (the precision) and returns a new allocation (a BigNum), but at least any reduction in that set of invalid annotations seems beneficial

**Comment by nsajko** [comment]
> references global state (the precision)

I think this could at least partly be addressed by using `setprecision(::Function, ::Type{BigFloat}, ::Int)`. One such PR is #55853.
