### ISSUE TITLE
Julia 1.11: IOBuffer does not update size of a user specified array

### ISSUE THREAD

**Issue by haberdashPI** [JuliaLang/julia#55978]
In julia 1.10:

```julia
julia> bytes = Vector{Int8}(undef, 10)
10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

julia> bytes = Vector{UInt8}(undef, 10)
10-element Vector{UInt8}:
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00

julia> io = IOBuffer(bytes; write=true, read=false)
IOBuffer(data=UInt8[...], readable=false, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(io, 10)
8

julia> write(io, 26)
8

julia> bytes
16-element Vector{UInt8}:
 0x0a
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x1a
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00

```

But with the current Julia 1.11 release candidate:

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-rc4 (2024-09-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> bytes = Vector{Int8}(undef, 10)
10-element Vector{Int8}:
 -96
 -52
  89
  24
   1
   0
   0
   0
   1
   0

julia> bytes = Vector{UInt8}(undef, 10)
10-element Vector{UInt8}:
 0x60
 0x82
 0xaf
 0x19
 0x01
 0x00
 0x00
 0x00
 0x01
 0x00

julia> io = IOBuffer(bytes; write=true, read=false)
IOBuffer(data=UInt8[...], readable=false, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(io, 10)
8

julia> write(io, 26)
8

julia> bytes
10-element Vector{UInt8}:
 0x0a
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x01
 0x00
```

**Comment by PallHaraldsson** [comment]
Is this a bug? I mean then in 1.10, not 1.11? Are the `bytes` passed in supposed to be changed? I would then have expected `IOBuffer!(` but maybe `write=true` is for that? Was a bug fixed, and you rely on the old semantics?

**Comment by haberdashPI** [comment]
Based on the documentation I would interpret this as a bug (but maybe the documentation should be changed instead?)

> Create an in-memory I/O stream, which may optionally operate on a pre-existing array.

If it operates on the area, presumably writing past the end of the array should either error (happens with no julia version that I know of) or expand the size of the array (the behavior from prior Julia versions).

What is happening in the above example? Is it writing to a different buffer, or is it writing to invalid memory that occurs past the end of the array?

**Comment by haberdashPI** [comment]
One guess: the new `Memory` object from the array is stored in the `IOBuffer` and that is updated, but the array still contains the pointer to the old array. 

Definitely seems like a change in behavior to me. 

This is easy to fix in my case, I think, but this seems like it could easily lead to silent bugs, if users of `IOBuffer` are assuming the user-specified array gets updated from calls to `write`.

**Comment by haberdashPI** [comment]
What is the point of passing your own array then? Seems like a gap in the documentation.

**Comment by vtjnash** [comment]
Plenty of reasons still, such as setting maxsize=length(array) or write=false, either of which ensures it doesn't get reallocated or shifted, or just because you have a temporary buffer you'd like to reuse to start

**Comment by haberdashPI** [comment]
Thanks for the examples.
