### ISSUE TITLE
`isapprox(a, b)` does not check that `a` and `b` are identical

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/julia#56015]
```julia
a = rand(100, 100)
b = a
isapprox(a, b)
```
does the same long computation that `isapprox` does if `b = rand(100, 100)` instead.

This may be intentional, but I can't think of an explanation. I'm suspicious because it's also the case that 
 ```julia
a == b
```` 
does not take a fast exit if `a === b`.

EDIT: I'm trying to find an example that shows that `isapprox` should check `a === b`.  But the first things I try do not support this.  Identity is not checked by the method for `==` for `a::BigInt`, `b::BigInt`. Neither is it checked for `AbstractArray`, nor for the special case `BitIntegerArray{1}`.  I can't believe all of these are oversights. There must be a reason.

Maybe the caller is expected to make this check. Say I'm sampling with replacement from a multiset and comparing pairs of samples. Then I have to remember to check for identity if I want this performance gain. Here is an example that's contrived to make the cost of comparing samples large

```julia
using BenchmarkTools

const a = ones(100);
const b = a;
const c = ones(100);

const v = [a, b, c]

cmp_samp() = cmp(v[rand(1:3)], v[rand(1:3)])
mycmp_samp() = mycmp(v[rand(1:3)], v[rand(1:3)])

mycmp(x, y) = x === y ? 0 : cmp(x, y)

@btime sum(mycmp_samp() for _ in 1:100);
@btime sum(cmp_samp() for _ in 1:100);
```

```shell
  3.484 μs (0 allocations: 0 bytes)
  8.659 μs (0 allocations: 0 bytes)
```

**Comment by topolarity** [comment]
The main exceptions are probably `Missing` and `NaN`:
```julia
julia> (missing === missing, missing == missing)
(true, missing)

julia> (NaN === NaN, NaN == NaN)
(true, false)
```

**Comment by mbauman** [comment]
Right, so that means that adding this performance optimization would break `isapprox(NaN,NaN)` and `isapprox(fill([NaN],2)...)` — and any other custom type that has similarly defined equality and ordering.

`===` does not necessarily imply `==` or even `isapprox` (_thanks Kahan_ :p).
