### ISSUE TITLE
Precision is not propagated in `one` for `BigFloat`

### ISSUE THREAD

**Issue by jarlebring** [JuliaLang/julia#56042]
I expect `one` and `zero` to propagate the precision of a `BigFloat`. They do not. 

```julia
julia> b=BigFloat(0.3,precision=100);
julia> b.prec
100
julia> o=one(b)
1.0
julia> o.prec
256
julia> z=zero(b)
0.0
julia> z.prec
256
```

**Comment by jarlebring** [comment]
In fact, I would also expect `oftype` to do the same. 
```
julia> b.prec
100
julia> q=oftype(b,0.1);
julia> b.prec
100
```
Note that `oftype` is used in `zero(x)` but not `one`:

https://github.com/JuliaLang/julia/blob/4cdd864e535b16e928c2eff43e6f1583bd77209d/base/number.jl#L313

so changing `oftype` would solve it for `zero` but not for `one`.

**Comment by jarlebring** [comment]
Based on the discussion in #56044, one is not allowed to set the prec. With the `setprecision`, I have not managed to create BigFloat-objects of different precision. If Julia does not support bigfloats of different precision in the same session, this can be closed.  It would be a bit disappointing though, considering that working with different precision is increasing in popularity. Different BigFloat precisions would be very convenient.

**Comment by jarlebring** [comment]
> Precision is not propagated, but rather always taken from the global (or scoped value) precision specified for doing that operation

I understand this now. If every operation leads to a new BigFloat with the global precision, it effectively means one cannot work with different precisions. For me, it sounds like julia does not support multiprecision with BigFloat.

**Comment by vtjnash** [comment]
That seems an odd conclusion. The mental model is just that each operation has a precision, not that each value has a precision. Otherwise, many operations (div, pow, sqrt, etc) couldn't be specified (only mul and add), as they must truncate precision in some form.

**Comment by jarlebring** [comment]
Okay maybe I exaggerated a bit that it is completely impossible.

From a system design perspective I don't see why e.g sqrt(a) couldn't return an object the precision of `a` rather than a global precision. In the GMP-library the precision to be used for the computation is determined by the precision of destination variable, not the precision of the operation, and afaiu there is no global precision. 

Some things sound difficult to implement with this mental model. Suppose I have want to run ArnolidMethod.jl. I want to use one particular precision for the orthogonalization and basis matrix storage, and a different for the precision for the matrix vector product (implemented as a function or just a Matrix{BigFloat}). I don't see how that can be done without actually modifying the ArnoldiMethod.jl-code.
