### ISSUE TITLE
Saner error bounds on linear algebra tests

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#5605]
In the current [linear algebra test suite](https://github.com/JuliaLang/julia/blob/master/test/linalg.jl), many of the linear algebra tests have error bounds that are heuristically implemented, e.g. something like `N^2*eps()`. This occasionally causes brittleness in that the linear algebra tests fail for no apparent reason.

The purpose of this issue is to track
- Specific linear algebra tests which are brittle and have to had their tolerances adjusted manually for no apparent reason
- The brittleness of the magic seed that is currently used in the linear algebra test suite.
- Thoughts on an appropriate fuzz factor for linear algebraic tests
- The implementation of proper error bounds on linear algebra tests.

The long term hope is that the last action item will close this issue once and for all, but in the meantime we should keep track of any heuristic adjustments to the test suite.

Cross-reference: #5578 #5472 #4638

**Comment by KristofferC** [comment]
With the `guardsrand` changes and the inactivity here, I think this can be closed.
