### ISSUE TITLE
Inconsistent random output from MersenneTwister in Julia 1.11

### ISSUE THREAD

**Issue by raphasampaio** [JuliaLang/julia#56055]
I encountered inconsistent behavior in Julia 1.11 when using MersenneTwister. In the code provided, the output differs between Julia versions 1.11.0 and previous versions (1.8.5, 1.9.4, 1.10.5), even though there are no mentions of changes to the MersenneTwister algorithm in NEWS.md.

```julia
using Random

rng = MersenneTwister()
Random.seed!(rng, 1)
n = rand(rng, 1:100)
println("Julia $VERSION = $n")
```

Outputs:
```
Julia 1.8.5 = 66
Julia 1.9.4 = 66
Julia 1.10.5 = 66
Julia 1.11.0 = 57
```

**Comment by fatteneder** [comment]
RNGs are not considered stable across minor versions: https://docs.julialang.org/en/v1.11/stdlib/Random/#Reproducibility

For reproducible RNGs see https://github.com/JuliaRandom/StableRNGs.jl.

**Comment by raphasampaio** [comment]
@fatteneder thank you for sharing this information! I wasn't aware that RNGs aren't stable across minor versions in Julia.
