### ISSUE TITLE
how addprocs add a process?

### ISSUE THREAD

**Issue by jiudianren** [JuliaLang/julia#56064]
code example:
```
using Distributed
using Libdl
procs = addprocs(1)
@everywhere procs x =Libdl.dlopen(xx.so)
```

when i use addprocs add a process and open a so in it. the assert in line 53 will fail.
the code in xx.so look like in the picture below:

![Image](https://github.com/user-attachments/assets/73261af3-d3a7-443c-95f1-36c242fbf1f9)

i use movl to get esp or rsp value，and compare it to stack which get from pthread_attr_getstatck.

in addition：
If I don't use addprocs. like this：
```
using Distributed
using Libdl
x=Libdl.dlopen("xx.so")
println(x)
```

the program pass and the assert is not triggered

**Comment by sgaure** [comment]
It could be that code run with `Distributed` get their own stack? Not the thread stack.

Here's a shorter reproducer. For 64-bits machine (movq and rsp, instead of movl and esp). Compile with `gcc -shared -o mylib.so mylib.c`. Run in julia with e.g. `@ccall "./mylib.so".checkstack()::Nothing`.

```
#include <stdint.h>
#include <stdio.h>
#include <pthread.h>

int pthread_getattr_np(pthread_t thread, pthread_attr_t *attr);

intptr_t currentStackPtr() {
  intptr_t value;
  asm ("movq %%rsp, %0;" : "=a" (value));
  return value;
}

void checkstack() {
  pthread_t self = pthread_self();
  pthread_attr_t threadAttr;
  intptr_t base;
  size_t size;
  int stat = pthread_getattr_np(self, &threadAttr);
  stat = pthread_attr_getstack(&threadAttr, (void **) &base, &size);
  intptr_t mysp = currentStackPtr();

  printf("base=%p, base+size=%p, mysp=%p success=%d\n", 
	 (void*)base, (void*)(base+size), (void*) mysp,
	 base <= mysp && mysp <= base+size);
}

static void init() __attribute__((constructor));
static void init() {
  checkstack();
}
```

**Comment by Seelengrab** [comment]
Code run in a worker process not only gets its own stack, but its own address space. It literally runs in a different process, so seeing different stack pointers does not seem surprising to me.

**Comment by jiudianren** [comment]
> Code run in a worker process not only gets its own stack, but its own address space. It literally runs in a different process, so seeing different stack pointers does not seem surprising to me.

yes，different process have different stack pointer.  but when check statck pointer witch stack size in its own process  ,the stack pointer should be in stack range which get from  pthread_attr_getstack

**Comment by jiudianren** [comment]
> It could be that code run with `Distributed` get their own stack? Not the thread stack.
> 
> Here's a shorter reproducer. For 64-bits machine (movq and rsp, instead of movl and esp). Compile with `gcc -shared -o mylib.so mylib.c`. Run in julia with e.g. `@ccall "./mylib.so".checkstack()::Nothing`.
> 
> ```
> #include <stdint.h>
> #include <stdio.h>
> #include <pthread.h>
> 
> int pthread_getattr_np(pthread_t thread, pthread_attr_t *attr);
> 
> intptr_t currentStackPtr() {
>   intptr_t value;
>   asm ("movq %%rsp, %0;" : "=a" (value));
>   return value;
> }
> 
> void checkstack() {
>   pthread_t self = pthread_self();
>   pthread_attr_t threadAttr;
>   intptr_t base;
>   size_t size;
>   int stat = pthread_getattr_np(self, &threadAttr);
>   stat = pthread_attr_getstack(&threadAttr, (void **) &base, &size);
>   intptr_t mysp = currentStackPtr();
> 
>   printf("base=%p, base+size=%p, mysp=%p success=%d\n", 
> 	 (void*)base, (void*)(base+size), (void*) mysp,
> 	 base <= mysp && mysp <= base+size);
> }
> 
> static void init() __attribute__((constructor));
> static void init() {
>   checkstack();
> }
> ```

in my example code,  another pthread was create ,I don't know if this will have any impact.

**Comment by sgaure** [comment]
Btw, if you need the task stack, there is an undocumented C-routine which can be called from julia. It's not guaranteed to survive julia upgrades:

```

function taskstack(task=current_task())
    active_start = Ref(Ptr{Nothing}(0))
    active_end = Ref(Ptr{Nothing}(0))
    total_start = Ref(Ptr{Nothing}(0))
    total_end = Ref(Ptr{Nothing}(0))

    @ccall jl_active_task_stack(Ref(task)::Ref{Task},
                                active_start::Ref{Ptr{Nothing}},
                                active_end::Ref{Ptr{Nothing}},
                                total_start::Ref{Ptr{Nothing}},
                                total_end::Ref{Ptr{Nothing}})::Cvoid

    return (as=active_start[], ae=active_end[], ts=total_start[], te=total_end[])
end
```

**Comment by jiudianren** [comment]
> This probably has got nothing to do with `addprocs`. It's about the stack being checked in a julia task, which runs on its own stack. With the `mylib.so` as above, try
> 
> ```
> julia> @ccall "./mylib.so".checkstack()::Nothing
> ... success=1
> julia> @async @ccall "./mylib.so".checkstack()::Nothing
> ... success=0
> ```
> 
> Because the `@async` creates a `Task`, which gets its own stack. I suppose the same thing is done with remote `Distributed` calls.


I run your code, and  get  your idea. thanks a lot.

![Image](https://github.com/user-attachments/assets/e9238ae4-f001-416b-b004-9854e077affa)
