### ISSUE TITLE
1.11 Array push! double allocates after a certain size

### ISSUE THREAD

**Issue by ancapdev** [JuliaLang/julia#56066]
It looks like on Julia 1.11 `push!(array)` double allocates when it grows from the 175th element onward. Is this expected, or a measurement error in `@allocations` maybe?

### MWE
```Julia
function push_allocs(n)
    x = Int[]
    as = Pair{Int, Int}[]
    for i in 1:n
        a = @allocations push!(x, i)
        if a > 0
            push!(as, i => a)
        end
    end
    as
end

push_allocs(10_000)
```

### Julia 1.10 result
```Julia
8-element Vector{Pair{Int64, Int64}}:
    1 => 1
    9 => 1
   42 => 1
  175 => 1
  708 => 1
 1820 => 1
 4095 => 1
 8702 => 1
```

### Julia 1.11 result
```Julia
8-element Vector{Pair{Int64, Int64}}:
    1 => 1
    9 => 1
   42 => 1
  175 => 2
  708 => 2
 1820 => 2
 4095 => 2
 8702 => 2
```

**Comment by oscardssmith** [comment]
I believe what's happening here is that the code is now in Julia so it is better tracked by the profiling code. that said, I'm not sure where the second allocation is...

**Comment by oscardssmith** [comment]
Ah, the 2nd allocation is a 24 byte allocation in `ijl_gc_managed_malloc` (deep within the C internals) that occurs when the allocated `Memory` is bigger than our GC size-pools. Given that this 2nd allocation will always be paired with a much bigger allocation, I don't think it matters.

**Comment by ancapdev** [comment]
> Ah, the 2nd allocation is a 24 byte allocation in `ijl_gc_managed_malloc` (deep within the C internals) that occurs when the allocated `Memory` is bigger than our GC size-pools. Given that this 2nd allocation will always be paired with a much bigger allocation, I don't think it matters.

Thanks for tracking it down and explaining. When you say it doesn't matter, it makes sense that it won't have a material impact in terms of working set size, but in terms of GC and the cost of scanning the live set, is this still a single GC tracked object, or is it two? If it's two then what I've experienced often with Julia is the GC quickly becoming a bottleneck in large scaled up concurrent workloads, and anything that increases the number of objects in the live set is detrimental, regardless of size.

**Comment by topolarity** [comment]
What forces us to make the allocations non-contiguously in the non-pooled case?

**Comment by oscardssmith** [comment]
what do you mean?

**Comment by topolarity** [comment]
Just a question out of ignorance..

This code is what decides to allocate the `Memory{T}` either pooled (and the Memory contiguous with its data buffer) or unpooled with the buffer allocated separately: https://github.com/JuliaLang/julia/blob/44620b62614c653a59ac932fc66782d3fefb09b7/src/genericmemory.c#L52-L64

Do you know why the `Memory` can't be allocated alongside its buffer in the unpooled case?

**Comment by oscardssmith** [comment]
that's a great question. @vtjnash is there a reason?

**Comment by vtjnash** [comment]
It complicates the marking bits. It could be done, just no known reason to
