### ISSUE TITLE
OpenBLAS: DYNAMIC_ARCH mismatch between Yggdrasil and source build

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#56075]
We disable OpenBLAS' DYNAMIC_ARCH selection when building for ARMv8: https://github.com/JuliaLang/julia/blob/91da4bf9323b79e00e446d6471d3b43d4c8ee4c4/Make.inc#L1010-L1016

While on Yggdrasil we've switched it on years ago: https://github.com/JuliaPackaging/Yggdrasil/commit/8b41a9abd5a60ea3b5119946ab775d40fcca1aca

@IanButterworth @giordano I guess we can just remove the above from `Make.inc` here? Or should we keep the `TARGET=ARMV8` baseline target (not sure why we don't have one for x86)?

**Comment by giordano** [comment]
I think that's just a relic of the past.

**Comment by IanButterworth** [comment]
I don't recall the motivation so can't comment.
