### ISSUE TITLE
Scope are readline() issues in v1.11.0

### ISSUE THREAD

**Issue by potaslab** [JuliaLang/julia#56079]
# Expected Behavior

When the following code is pasted into the REPL, it works as expected:

```julia
x = [1, 2, 3, 4, 5, 6]
j = 1  
while j != length(x)    
    println(x[j])
    readline()
    j += 1
end

```

# Scope Issue

Running the same code as a script raises a scope error:

``` julia
Warning: Assignment to `j` in soft scope is ambiguous. Disambiguate with `local` or `global`.
ERROR: UndefVarError: `j` not defined in local scope.
```

Even when explicitly declaring `j` as `local` or `global`, the error persists and the code fails to execute.

# Readline Issue

When running the script in VS Code by highlighting and `Shift + Enter` (Julia v1.11.0), the first readline() input isn't accepted until multiple key presses, though subsequent iterations work fine. In v1.10.5, the first input works if it's not "Enter" but still exhibits strange behavior.

(as above, running the script in VS Code by using the run or play button in Julia v1.11.0 fails completely because of the abovementioned scope warning and error). 

Both versions exhibit readline() issues, but it’s worse in v1.11.0 when using VS Code because it needs about 10 keypresses to get past the first itereation whereas v1.10.5 only needs one addtional (but unexpected) keypress.

**Comment by sgaure** [comment]
The scoping is explained in the manual https://docs.julialang.org/en/v1/manual/variables-and-scoping/#on-soft-scope, with examples.
