### ISSUE TITLE
inlined types don't pack as tightly as they could (while still maintaining alignment)

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#56104]
Consider this example:
```julia
julia> struct Value
           kind::Int8
           value::Union{Int,String}
       end

julia> sizeof(Value)
16

julia> struct Node1
           a::UInt16
           b::UInt16
           
           node_kind::Int8
           
           v::Value
       end

julia> sizeof(Node1)
24

julia> struct Node2
           a::UInt16
           b::UInt16
           
           node_kind::Int8
           
           # Manually inline Value for padding improvements (to allow these Int8s to combine)
           val_kind::Int8
           val_value::Union{Int,String}
       end

julia> sizeof(Node2)
16
```

As you can probably already tell, when you manually inline the `Value` struct, the two `Int8`s can pack together, but when the `Value` struct is inlined, julia seems to treat the entire struct as a single `16-byte` struct.

```julia
julia> include("struct-layouts.jl")

julia> struct_layout(Value)
---- struct Value <: Any
   0:   kind::Int8                 #  size:  1
   1:     --padding--              #  size:  7
   8:   value::Union{Int64, String}#  size:  8
---- end                           # total: 16 bytes

julia> struct_layout(Node1)
---- struct Node1 <: Any
   0:   a::UInt16                  #  size:  2
   2:   b::UInt16                  #  size:  2
   4:   node_kind::Int8            #  size:  1
   5:     --padding--              #  size:  3
   8:   v::Value                   #  size: 16
---- end                           # total: 24 bytes

julia> struct_layout(Node2)
---- struct Node2 <: Any
   0:   a::UInt16                  #  size:  2
   2:   b::UInt16                  #  size:  2
   4:   node_kind::Int8            #  size:  1
   5:   val_kind::Int8             #  size:  1
   6:     --padding--              #  size:  2
   8:   val_value::Union{Int64, String}#  size:  8
---- end                           # total: 16 bytes
```

This means that the abstraction of a Value is _not free,_ and if you want to talk about a Value on its own, you need to keep both versions of this struct around and convert between them.

In C++, you have to do what we are doing, because the `node1.v` field is required to have an address, since you can take the address of any variable, including a field of a struct. In C++ you are allowed to write:
```c++
Node1 node;
Value* vp = &(node.v);
```

But in Julia, we don't allow that. You cannot take the address of an immutable struct, let alone take the address of a field.
So I think we have more freedom than C++ to pack the struct?

Could we pack the struct as if the fields were inlined, as I've done here?

**Comment by d-netto** [comment]
> Could we pack the struct as if the fields were inlined, as I've done here?

I wonder if this would break C inter-op?

I've seen some code in which we write an immutable struct in Julia, write its equivalent struct in C, and then do a c-call to load the contents of the C struct into the equivalent Julia struct.

See one example [here](https://github.com/JuliaLang/julia/blob/a007e807623f0bbb820315b8ce3340bd3d41262b/base/timing.jl#L31).

This sounds like the kind of thing that would be impossible/painful to do if we deviated from the struct layout specified in C.

**Comment by oscardssmith** [comment]
I think our current behavior actually breaks C inter-op. According to https://stackoverflow.com/questions/14510711/how-is-the-size-of-a-c-class-determined/14510919#14510919, the alignment of Value should be the alignment of `Union{Int,String}`

**Comment by vtjnash** [comment]
Union does not have a C equivalent ABI, but all C equivalent ABI must have the same ABI in Julia as C, so we cannot change this

**Comment by NHDaly** [comment]
Aha, yes of course. 💡 
Thanks, this makes sense, and indeed we should of course stick to the C ABI layout. Too bad though, since in most cases we could do better.

I guess in a future Julia 2.0, we could consider opt-in for C ABI compatibility? Something like `@c_abi struct ... end`  or something like that, but otherwise we could pack tighter? But i don't think it's super relevant in many cases.

Cool thanks.
I'll close this now.
