### ISSUE TITLE
Consider rpmalloc and/or mimalloc

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#56142]
I see LLVM now has rpmalloc "in-tree" (so should Julia use it? I think it will when LLVM is used, but I mean should it is it in general?:
https://llvm.org/doxygen/md_lib_Support_rpmalloc_README.html

https://github.com/mjansson/rpmalloc

I'm new to that rpmalloc, I thought mimalloc by now best, why Python added support for it in 3.13:
https://docs.python.org/3/c-api/memory.html#default-memory-allocators

So I support:
https://news.ycombinator.com/item?id=35624611
>I hoped to see benchmark comparisons with newer allocators like mimalloc https://github.com/Microsoft/mimalloc and snmalloc https://github.com/Microsoft/snmalloc as well as the older workhorses like jemalloc, hoard, tcmalloc...

I think you can have many mallocs available but need to use the free for the corresponding one, though I'm not sure, since it seems one malloc must be the global only one, and if any other then getting its memory from that one?

**Comment by giordano** [comment]
#47062

**Comment by PallHaraldsson** [comment]
Whatever is chosen would Julia need a comparable JULIAMALLOC env var, and build option:

https://docs.python.org/3/using/configure.html#cmdoption-without-mimalloc

--without-mimalloc

Disable the fast mimalloc allocator (enabled by default).
See also PYTHONMALLOC environment variable.
--without-pymalloc
Disable the specialized Python memory allocator pymalloc (enabled by default).
See also PYTHONMALLOC environment variable.

https://pythoninsider.blogspot.com/2024/10/python-3130-final-released.html
>A _modified_ version of mimalloc is now included, optional but enabled by default if supported by the platform, and required for the free-threaded build mode.

And since Python uses _patched_ mimalloc, could and should Julia use the same?
