### ISSUE TITLE
Inconsistent handling of `--trace-compile` argument

### ISSUE THREAD

**Issue by paulmelis** [JuliaLang/julia#56274]
With 1.11 (and 1.10 as well):

```
$ julia --help | grep project
 --project[={<dir>|@.}]     Set <dir> as the active project/environment.

$ julia --help-hidden | grep trace-compile
 --trace-compile={stderr|name}
```

Both options are listed in the `<option>=<value>` form, with `--trace-compile` even suggesting there must be a `=` used to set its value.

For `--project` you cannot provide its value as a separate argument:
```
melis@blackbox 17:13:~$ julia --project `pwd`
ERROR: SystemError: opening file "/home/melis": No such file or directory
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:557
 [2] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:323
 [3] _start()
   @ Base ./client.jl:531
```

While for `--trace-compile` you *can*:
```
melis@blackbox 17:13:~$ julia --trace-compile doh
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.1 (2024-10-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> 
melis@blackbox 17:13:~$ cat doh
precompile(Tuple{typeof(Base.print), Base.TTY, String})
```

It would be better if `--trace-compile` (and other options of the same form) would raise an error if they're not using the `<option>=<value>` form as listed in the help, as it will unexpectedly overwrite the argument following it when you pass only `--trace-compile`. I did this inadvertently as I was expecting `julia --trace-compile script.jl` to output the precompile statements to stderr by default, but instead it overwrote my script file (which was luckily in git).

**Comment by vtjnash** [comment]
This would be breaking, as well as unexpected. The syntax in the help is subtly different, one indicating the argument is optional (requiring `=`) and the other indicating the argument is required (not requiring the `=`). This is per the expected `getopt_long` implementation

**Comment by paulmelis** [comment]
"Subtly different", but with no explanation anywhere? At least, I can't find anything in `--help` or the manual that `--trace-compile value` is accepted, when `--trace-compile=value` is what is listed as the format to use. And how is it "unexpected"?

At least the docs should then be extended to describe (and warn) how these options are parsed.
