### ISSUE TITLE
pkg-config files point to the wrong directory for Julia binaries

### ISSUE THREAD

**Issue by albinahlback** [JuliaLang/julia#56302]
As a developer of a library written in C, one can utilize pkg-config during the configuration process to obtain the correct set of flags for a dependency. In my case, I help to maintain [FLINT](https://github.com/flintlib/flint/), and I want to check that our changes work for our users. This includes checking that [Oscar.jl](https://github.com/oscar-system/Oscar.jl)'s dependency [Nemo.jl](https://github.com/Nemocas/Nemo.jl/) works as intended with our changes, when built against Julia's version of GMP (located in `.../artifacts/...`).

However, when I ask for the right flags include flags for GMP (or for any binary that I have on my system, for that matter), I get
```bash
$ PKG_CONFIG_PATH=/home/albin/.julia/artifacts/4c207c7dc70b23755d9281a92daa9b8f11dc746d/lib/pkgconfig \
  pkg-config --cflags-only-I gmp
-I/workspace/destdir/include
```
which is wrong since everything should point to a directory under `artifacts`.

Could this be fixed? Perhaps change `prefix` when the dependencies are downloaded?

**Comment by gbaraldi** [comment]
Can you open this issue in https://github.com/JuliaPackaging/Yggdrasil. This is where we build those binaries
