### ISSUE TITLE
REPL-StyledString error when simply starting Julia 1.11

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#56338]
I'm trying to gradually switch to 1.11, and encounter a very annoying error in almost every project I open.
Basically, whenever I just start julia in a project that was instantiated with 1.10, I immediately get this error:
```
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe] (cache misses: invalid header (2))
ERROR: LoadError: ArgumentError: Package REPL does not have StyledStrings in its dependencies:
- Note that the following manifests in the load path were resolved with a different
  julia version, which may be the cause of the error. Try to re-resolve them in the
  current version, or consider deleting them if that fails:
    /...../Manifest.toml (v1.10.4)
    /Users/aplavin/.julia/environments/v1.11/Manifest.toml (v1.11.0)
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have REPL checked out for development and have
  added StyledStrings as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with REPL
<... traceback ...>
julia> 
```
I do have Revise in my startup, as probably many other Julia users. Can we do at least something to make the transition to 1.11 more seamless in this common case? I would expect such an issue when actually loading something from the current project that changed from 1.10 to 1.11, but not when just starting Julia...

**Comment by IanButterworth** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/56148 which will be on 1.11.2
