### ISSUE TITLE
Nightly docs missing. v1.10-dev in its place

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#56365]
https://docs.julialang.org/en/v1.10-dev/

![Image](https://github.com/user-attachments/assets/4cc60ac3-4519-468a-bb5c-042412181ade)

**Comment by Zentrik** [comment]
I see the nightly docs as well, requires scrolling down for me.

**Comment by IanButterworth** [comment]
It appears to be a transient thing.. probably depends on which branch out of master and the release branches have been pushed most recently
