### ISSUE TITLE
LinearAlgebra `kron` test fails in the REPL on `backports-release-1.11`

### ISSUE THREAD

**Issue by topolarity** [JuliaLang/julia#56388]
Try running [this test from LinearAlgebra](https://github.com/JuliaLang/julia/blob/9850a3881221a57a382e98c9b9ae2bf97ac3966d/stdlib/LinearAlgebra/test/diagonal.jl#L1445-L1453) in the REPL:
```julia
julia> using Test, LinearAlgebra

julia> @testset "zeros in kron with block matrices" begin
           D = Diagonal(1:4)
           B = reshape([ones(2,2), ones(3,2), ones(2,3), ones(3,3)], 2, 2)
           @test kron(D, B) == kron(Array(D), B)
           @test kron(B, D) == kron(B, Array(D))
           D2 = Diagonal([ones(2,2), ones(3,3)])
           @test kron(D, D2) == Diagonal([diag(D2); 2diag(D2)])
           @test kron(D2, D) == Diagonal([ones(2,2), fill(2.0,2,2), ones(3,3), fill(2.0,3,3)])
       end
```

fails with:
```julia
zeros in kron with block matrices: Test Failed at REPL[3]:7
  Expression: kron(D, D2) == Diagonal([diag(D2); 2 * diag(D2)])
   Evaluated: Diagonal([[1.0 1.0; 1.0 1.0], [1.0 1.0 1.0; 1.0 1.0 1.0; 1.0 1.0 1.0], [2.0 2.0; 2.0 2.0], [2.0 2.0 2.0; 2.0 2.0 2.0; 2.0 2.0 2.0], [3.0 3.0; 3.0 3.0], [3.0 3.0 3.0; 3.0 3.0 3.0; 3.0 3.0 3.0], [4.0 4.0; 4.0 4.0], [4.0 4.0 4.0; 4.0 4.0 4.0; 4.0 4.0 4.0]]) == Diagonal([[1.0 1.0; 1.0 1.0], [1.0 1.0 1.0; 1.0 1.0 1.0; 1.0 1.0 1.0], [2.0 2.0; 2.0 2.0], [2.0 2.0 2.0; 2.0 2.0 2.0; 2.0 2.0 2.0]])
```

This is on latest `nightly`, where this was supposed to already be fixed (#55941 and #56229):
```julia
julia> versioninfo()
Julia Version 1.12.0-DEV.1514
Commit e4dc9d357a1 (2024-10-29 17:18 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 12th Gen Intel(R) Core(TM) i7-1255U
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, alderlake)
Threads: 1 default, 0 interactive, 1 GC (on 12 virtual cores)
```

This same test also segfaults in 1.11

**Comment by topolarity** [comment]
cc @jishnub

**Comment by jishnub** [comment]
Did you alter the testset somehow? This example seems to be a mix of the tests on v1.11.1:
https://github.com/JuliaLang/julia/blob/8f5b7ca12ad48c6d740e058312fc8cf2bbe67848/stdlib/LinearAlgebra/test/diagonal.jl#L1326-L1334
and master:
https://github.com/JuliaLang/julia/blob/9850a3881221a57a382e98c9b9ae2bf97ac3966d/stdlib/LinearAlgebra/test/diagonal.jl#L1445-L1453
The tests are a bit different, as on v1.11, `D = Diagonal(1:2)`  and on master, `D = Diagonal(1:4)`. I am able to run both of these blocks successfully on nightly v"1.12.0-DEV.1510".

**Comment by topolarity** [comment]
Oh! That's the problem. I took this from 1.11, which doesn't have https://github.com/JuliaLang/julia/pull/56229

**Comment by topolarity** [comment]
Actually this test _is_ what's on `backports-release-1.11`. The `Diagonal(1:4)` was added when https://github.com/JuliaLang/julia/pull/56229 was back-ported

It sounds like the test needs fixing?

**Comment by jishnub** [comment]
Thanks! I have pushed a fixed commit https://github.com/JuliaLang/julia/pull/56228/commits/23cb1281abb710d996727d8b69ed2115275207b1, and the updated tests pass locally for me.

**Comment by topolarity** [comment]
Awesome - thanks @jishnub
