### ISSUE TITLE
Allocation-free version of Base.summarysize?

### ISSUE THREAD

**Issue by amontoison** [JuliaLang/julia#56410]
Compared to `sizeof`, `Base.summarysize` allocates a relatively high number of bytes.
```julia
v = rand(100)
@allocated sizeof(v)  # 0
@allocated Base.summarysize(v)  # 752
```
Is there a way to reduce or eliminate these allocations?
I wanted to use this function in an in-place code to determine the size in bytes of the workspace.

**Comment by jakobnissen** [comment]
Not really. The issue is that `summarysize` needs to traverse all objects contained within the argument, recursively. So, it needs to keep track of which objects it has already visited, which requires allocating some kind of container (`IdDict`, in the current implementation)
