### ISSUE TITLE
1.11 gets different values from same seed as 1.10

### ISSUE THREAD

**Issue by wsmoses** [JuliaLang/julia#56465]
Not sure if this is an issue on julia proper or a subpackage, but I just noticed and am working around:

see 
https://github.com/EnzymeAD/Enzyme.jl/pull/2059/commits/0037165661d84c492285e62e8ca6373506be2190

```
const SEED = 42
const N_SAMPLES = 500
const N_COMPONENTS = 4

const rnd = Random.MersenneTwister(SEED)
const data = randn(rnd, N_SAMPLES)
const params0 = [rand(rnd, N_COMPONENTS); randn(rnd, N_COMPONENTS); 2rand(rnd, N_COMPONENTS)]
```

gets different values on 1.11 and 1.10

**Comment by giordano** [comment]
Stream of random numbers isn't guaranteed to be the same across versions: https://docs.julialang.org/en/v1/stdlib/Random/#Reproducibility
