### ISSUE TITLE
incomprehensible printing of `:invoke` statement with `MethodInstance` of `Vararg` signature

### ISSUE THREAD

**Issue by sgaure** [JuliaLang/julia#56485]
MWE, v1.11.1:

```
julia> @noinline f(x...) = (s = 0; for i in x; s += i; end; s)
julia> g(x...) = f(x...)
julia> @code_typed g(1,2,3)
CodeInfo(
1 ─ %1 = Core.getfield(x, 1)::Int64
│   %2 = Core.getfield(x, 2)::Int64
│   %3 = Core.getfield(x, 3)::Int64
│   %4 = invoke Main.f(%1::Int64, %2::Vararg{Int64}, %3)::Int64
└──      return %4
) => Int64
```

Why is there a `%2::Vararg{Int64}`, and nothing on `%3`?

(From https://discourse.julialang.org/t/spooky-allocations-linked-to-varargs/122373/2)

**Comment by aviatesk** [comment]
This isn’t so much an inference issue as it is a problem with printing `MethodInstance` with `Vararg` signatures. We can correctly print `invoke Main.f(%1::Int, %2::Int, %3::Int)`, but doing so makes it unclear that this statement is invoking a `MethodInstance` with a `Vararg`.
