### ISSUE TITLE
Bug in reduce function?

### ISSUE THREAD

**Issue by Brinkhuis** [JuliaLang/julia#56514]
Julia version 1.11.1
MacBook Air 2020 M1

I want to test if all values in a vector are equal, using `reduce()`.  
However, the results are not what I expected. I expected all below to be `true`
Is this the correct behavior for `reduce` or not?

```
reduce(==, [0, 0]) # true (as expected)

reduce(==, [0, 0, 0]) # false (true expected)

reduce(==, [1, 1, 1, 1, 1]) # true (as expected)

reduce(==, [2, 2, 2, 2, 2]) # false (true expected)
```

N.B.
I solved the issue for my usecase by using `allequal()` which I came across searching for a solution.

**Comment by adienes** [comment]
this is user error 🙂 and one I myself made https://github.com/JuliaLang/julia/issues/49618

note that `2 == 2` returns `true` (a `Bool`) but `2 != true`
