### ISSUE TITLE
Developer mode (for REPL)

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#56512]
I suggest a `--developer` mode for Julia.

One thing that comes to mind is warning about access to global variables that have not been defined already (at some point it might warn against all access to global variables).

Now that the REPL is no longer in the sysimage, it seems like good timing to add a developer mode to it. It could be on by default there, but off by default, when not in the REPL/interactive-mode.

Could or should Lint.jl or StaticLint.jl be integrated into Julia such a developer mode?

Fell free to suggest warnings the mode could support, or even errors, since this wouldn't be a breaking change for opt-into dev mode at least. Some Strict (opt-in) mode has already been suggested for modules if I recall.

**Comment by KristofferC** [comment]
Going to close as somewhat of a dup of https://github.com/JuliaLang/julia/issues/54903.
