### ISSUE TITLE
Should `keys(::KeySet)` just be an identity?

### ISSUE THREAD

**Issue by ghyatzo** [JuliaLang/julia#56548]
Hello,

I was experimenting with iterators, and among other things I've stumbled into this error:
```julia
ERROR: MethodError: no method matching keys(::Base.KeySet{Int64, Dict{Int64, Int64}})
The function `keys` exists, but no method is defined for this combination of argument types.

Stacktrace:
  [1] eachindex(itrs::Base.KeySet{Int64, Dict{Int64, Int64}})
    @ Base ./abstractarray.jl:318
  [2] iterate(A::Base.Iterators.Reverse{Base.KeySet{Int64, Dict{Int64, In
t64}}})
    @ Base.Iterators ./iterators.jl:143
  [3] iterate(A::Base.Iterators.Reverse{Dict{Int64, Int64}}, state::Tuple
{Base.Iterators.Reverse{Base.KeySet{…}}})
    @ Base.Iterators ./iterators.jl:143
... more stuff omitted
```

as can be seen from the stack trace, I ended up trying to `reverse` a `Dict` (for reasons).
I know it doesn't really make sense since a `Dict` is unordered, but still that left me wondering:

Should it just be `keys(itr::KeySet) = itr`?
Even if unordered, a `Dict` is stil an iterable, to avoid having to make distinctions between "ordered" and "unordered" iterators (there isn't anything like it in the language that I know of?) it makes sense to instead make the unordered iterators the fixed point elements of the `reverse` "action"?

**Comment by vtjnash** [comment]
AbstactSets (of which KeySet is a subtype) do not have a notion of keys (the identity function is `values`)

**Comment by ghyatzo** [comment]
I see, but even if the notion of keys for a set doesn't exist, it is still implicitly used when iterating over a set by iterating over the keys of it's dict.
```julia
iterate(s::Set, i...)       = iterate(KeySet(s.dict), i...)
```

Reversing the iteration of a set doesn't make sense, I am simply advocating for covering this edge case to make the `reverse` iterator closed wrt all iterators since at the moment it breaks since there is no method matching `keys(::Base.KeySet)`.

It would make sense to have
```julia
 # following the iterate(::Set,i) idea,
keys(ks::KeySet) = keys(ks.dict)
# which would make this just
keys(ks::KeySet) = ks
```

so that the interface of `reverse` is completely general and reversing an unordered collection will just return you the same unordered collection.

**Comment by ghyatzo** [comment]
Anyhow, I guess this could either be a more thought out PR or a discourse post more than an issue.
I'll close this since it's not really an issue
