### ISSUE TITLE
how to define a more general `unique` function conveniently?

### ISSUE THREAD

**Issue by WalterMadelim** [JuliaLang/julia#56568]
`unique` function is based on `isequal` function.
If `isequal` function can be user-defined, we can also get a resultant new `unique` function. This should be convenient. 
But how to achieve this? Currently I don't know the way. See the following code.

```julia
julia> isequal(2, 3)
false

julia> unique([2, 3, 5, 2])   # 3 is different from 2, hence it remains
3-element Vector{Int64}:
 2
 3
 5

julia> Base.isequal(m::Int, n::Int) = ( abs(m - n) <= 1 ? true : false )  # user-define a new method

julia> isequal(2, 3)
true

julia> unique([2, 3, 5, 2])  # 3 is now deemed equates to 2, hence it should be removed ???
3-element Vector{Int64}:
 2
 3
 5
```

It would be wonderful if we have such a keyword choice:
```julia
julia> a, b = rand(3, 2), rand(3, 2);

julia> norm1(x) = LinearAlgebra.norm(x, 1);

julia> norm1(a .- b)
0.43189600452632304

julia> isapprox(a, b; atol = 0.42, norm = norm1)
false

julia> isapprox(a, b; atol = 0.44, norm = norm1)
true

julia> my_criterion = (a, b) -> isapprox(a, b; atol = 0.42, norm = norm1)
#7 (generic function with 1 method)

julia> my_criterion(a, b)
false

julia> unique([a, b, 2*a, 2*b]; criterion = my_criterion)
ERROR: MethodError: no method matching unique(::Vector{Matrix{Float64}}; criterion::var"#7#8")
```

**Comment by WalterMadelim** [comment]
Oh, I see. 
So without interfering the `unique` function, is there another function that can do this job? Is there a package or so?
Otherwise everyone has to manually write this piece of code.
This procedure could have been standardized.

**Comment by thchr** [comment]
I don't think there's a package, no. There's  several options for doing a so-so job of it (although, any implementation will be affected by the transitivity issue; so corner cases will be necessarily wonky), with several implementations listed in #19147. E.g., the most naive (and $O(n^2)$ rather than $O(n)$ as for standard `unique`) implementation is:
```jl
function uniquetol(A::AbstractArray{T}; kwargs...) where T
    S = Vector{T}()
    for a in A
         if !any(s -> isapprox(s, a; kwargs...), S)
             push!(S, a)
         end
    end
    return S
end
```
With sorting, this could be changed to $O(n\log n)$. Still, for small, specific problems, it can do a fine job.

For why there isn't a "standard" implementation, see https://github.com/JuliaLang/julia/issues/19147#issuecomment-326014320. There is no possible "standard" for this.

**Comment by jakobnissen** [comment]
It's perhaps worth emphasizing that `unique` already works perfectly fine with user-defined definitions of `isequal`. The reason it didn't work in @WalterMadelim 's original example was:
1. The definitions of `isequal` and `hash` must match in that `isequal(a, b)` implies `hash(a) == hash(b)`. Your definition of `isequal` violates this requirement
2. You're not allowed to redefine methods of Base functions operating on Base types (type piracy)

**Comment by WalterMadelim** [comment]
> For why there isn't a "standard" implementation, see https://github.com/JuliaLang/julia/issues/19147#issuecomment-326014320. There is no possible "standard" for this.

Okay. Thanks for pointing out. I've learned that.

> You're not allowed to redefine methods of Base functions operating on Base types (type piracy)

It appears that I knew this when I first studied Julia. But now I just use it daily and become less wary. Thanks for reminding.
