### ISSUE TITLE
FileWatching required in sysimage for parellel precompilation to work otherwise ungracefully errors.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#56569]
This line

https://github.com/JuliaLang/julia/blob/55bdb54dd2e1b0ea6df017f74f9af1de7abb8038/base/precompilation.jl#L1036

fails if one builds a sysimage without FileWatching. It should instead probably run without the pid locking if FileWatching does not exist in the sysimage, or try load it. I tried to change it to using `require_stdlib` but this code gets run during Pkg precompilation and then we get an error trying to use `require_stdlib` during package precompilation.

**Comment by IanButterworth** [comment]
Revive https://github.com/JuliaLang/julia/pull/51463 ?

**Comment by KristofferC** [comment]
I had already made https://github.com/JuliaLang/julia/pull/56570 before seeing your comment.
