### ISSUE TITLE
Erroneous test in julia/test /float16.jl?

### ISSUE THREAD

**Issue by stensmo** [JuliaLang/julia#56582]
I am testing Julia on RISC-V, and hit a small snag, but the test could perhaps be removed? 

https://github.com/JuliaLang/julia/blob/7fa26f011ec4fea616ad192eeaa8919f2cc17f97/test/float16.jl#L82

Is on line 82. Julia will issue this code (Both on X86 and Risc-V)
```llvm
define i16 @julia_unsafe_trunc_1513(half %"x::Float16") #0 {
top:
  %0 = fptosi half %"x::Float16" to i16
  %1 = freeze i16 %0
  ret i16 %1
}
```
When you check the LLVM Language Reference for fptosi https://llvm.org/docs/LangRef.html#fptosi-to-instruction you see that if the value does not fit, it's a poison value, and it's ok to replace the value with any value of that type. 

On x86 the poison value is 0 and on Risc-V the posion value is -1 for this case. Why does Julia need the poison value to be 0?

**Comment by giordano** [comment]
This test was added by @timholy in #21312.

**Comment by giordano** [comment]
I feel like the test may be a victim of [Hyrum's Law](https://www.hyrumslaw.com/), and checking `unsafe_trunc(Int16, NaN16) isa Int16` would be enough.

**Comment by oscardssmith** [comment]
yeah. the return value of this is very much not specified.
