### ISSUE TITLE
read a .xlsx file

### ISSUE THREAD

**Issue by Dionysus7777777** [JuliaLang/julia#56593]
Hello, I am encountering difficulties while trying to read a .xlsx file using Julia. Why is my code unable to find the sheet?![Image](https://github.com/user-attachments/assets/0fe4cf25-ca76-43dd-8d72-06ac73804317)

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.

**Comment by Dionysus7777777** [comment]
ok，I see.
