### ISSUE TITLE
`isreal` does not work in type domain

### ISSUE THREAD

**Issue by lkdvos** [JuliaLang/julia#56684]
There is something that I ran into this week, which somehow was unexpected to me. While `real` and `complex` work in the type domain, `isreal` does not. I can see why this would be the case, but it's also not super intuitive that it does not work.

```julia
julia> T = Float64
Float64

julia> real(T)
Float64

julia> complex(T)
ComplexF64 (alias for Complex{Float64})

julia> isreal(T)
ERROR: MethodError: no method matching isreal(::Type{Float64})
The function `isreal` exists, but no method is defined for this combination of argument types.

...
```

**Comment by lkdvos** [comment]
I would argue that `isreal(::Type{T}) where {T<:Number} = T <: Real` is not a bad default, but it could also be `isreal(t) = t == real(t)`.
I guess you are right on the money, the function sounds very much like a trait, and it occupies the name I would use for that trait.
I am quite okay with `T <: Real` but that would then make the code only work for explicit subtypes of `Real`, which is sometimes not possible because of other constraint.
More than anything, I was just slightly confused for half a minute, because I expected it to just work without thinking.
After thinking about it, I do see that it's technically a bit strange, since `Float64` is not a real number, it is a type.
But then it is slightly inconsistent that `real` and `complex` do work in the type domain.

Again, not a big issue, just wanted to bring it up.

**Comment by giordano** [comment]
If anything, I'd expect that `isreal(T)` would be `true` for all values of the type `T`, but for example

```julia-repl
julia> isreal(complex(1))
true
```

from which we should infer `isreal(ComplexF64)` should be `true`?
