### ISSUE TITLE
Illegal method invocation with respect to the type-parameter constraint of function arguments

### ISSUE THREAD

**Issue by frankwswang** [JuliaLang/julia#56723]
MWE (tested on Julia 1.11.1):

```Julia
julia> foo(a::T1, ::Vector{T2}) where {T1, T2<:T1} = a
foo (generic function with 1 method)

julia> foo(1, Vector{Union{}}(undef, 3))
1

julia> eltype(Vector{Union{}}(undef, 3)) <: typeof(1)
true

julia> foo(1, [1.1])
1

julia> eltype([1.1]) <: typeof(1)
false
```

**Comment by oscardssmith** [comment]
are you sure you don't have other methods of f

**Comment by frankwswang** [comment]
> are you sure you don't have other methods of f?

Did you mean `foo`? If so, no, I don't think so. I just double-checked with a freshly started Julia REPL.

**Comment by vtjnash** [comment]
I don't see the issue. The value of T1 is `>:Int` and the value of T2 is `==Union{}` with additional constraint `T1 >: T2`. This is fairly trivial to find value for `T1` and `T2` that satisfy those relations. The `Test.detect_unbound_args` code even correctly identifies this as true:

```
julia> Tuple{Int, Vector{Union{}}} <: Tuple{T, Vector{<:T}} where {T}
true

julia> foo(1, [1.1])
ERROR: UndefVarError: `T1` not defined in static parameter matching
Suggestion: run Test.detect_unbound_args to detect method arguments that do not fully constrain a type parameter.
```

**Comment by vtjnash** [comment]
Sorry, I mean that `Test.detect_unbound_args` doesn't know about this case, but I think is already an open issue, while sparam matching gets this correct
```
julia> Test.detect_unbound_args(Main)
0-element Vector{Method}
```

**Comment by frankwswang** [comment]
> I don't see the issue. The value of T1 is `>:Int` and the value of T2 is `==Union{}` with additional constraint `T1 >: T2`. This is fairly trivial to find value for `T1` and `T2` that satisfy those relations. The `Test.detect_unbound_args` code even correctly identifies this as true:
> 
> ```
> julia> Tuple{Int, Vector{Union{}}} <: Tuple{T, Vector{<:T}} where {T}
> true
> 
> julia> foo(1, [1.1])
> ERROR: UndefVarError: `T1` not defined in static parameter matching
> Suggestion: run Test.detect_unbound_args to detect method arguments that do not fully constrain a type parameter.
> ```

Currently, in Julia 1.11.1, `foo(1, [1.1])` does not throw any error, which is the issue I was referring to. If this is already fixed on the "master" branch, please ignore my comment. Thanks!

**Comment by vtjnash** [comment]
What is the bug? What error is supposed to be thrown? The subtyping (as I showed in the MWE) is consistent with calling the method

**Comment by vtjnash** [comment]
Oh sorry, I changed my MWE to print the values of T1 and T2 but forgot to paste that definition also
