### ISSUE TITLE
Documentation about "Conversion from rational to floating-point"

### ISSUE THREAD

**Issue by ArnoStrouwen** [JuliaLang/julia#56726]
The docs state:

> Conversion from rational to floating-point respects the following identity for any integral values of a and b, with the exception of the two cases b == 0 and a == 0 && b < 0:
> 
> julia> a = 1; b = 2;
> 
> julia> isequal(float(a//b), a/b)
> true

https://docs.julialang.org/en/v1/manual/complex-and-rational-numbers/

I do not understand the first case (`b == 0`), because:
```jl
julia> isequal(float(1//0),1/0)
true
julia> isequal(float(-1//0),-1/0)
true
```

**Comment by inkydragon** [comment]
I think it was a mistake introduced by https://github.com/JuliaLang/julia/pull/45220:

```patch
-with the exception of the two cases b == 0 and a == 0 && b < 0:
+with the exception of the two cases `a==0 && b==0` and `a==0 && b < 0`.
```

we may add some doctests as example:
```jl
julia> a, b = 0, 0
(0, 0)

julia> float(a//b)
ERROR: ArgumentError: invalid rational: zero(Int64)//zero(Int64)
Stacktrace:
...

julia> a/b
NaN


julia> a, b = 0, -1
(0, -1)

julia> float(a//b), a/b
(0.0, -0.0)
```
