### ISSUE TITLE
Memory leak with Julia 1.11's GC (discovered in SymbolicRegression.jl)

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/julia#56759]
We're seeing memory leaks in PySR/SymbolicRegression.jl that appear related to Julia 1.11's parallel GC. The user (@GoldenGoldy) tried various solutions including heap size hints and other parameter adjustments, but memory usage would steadily climb until OOM crashes occurred after 8-11 hours. The issue vanishes completely when switching to Julia 1.10 - no other changes needed. While we don't yet have a minimal working example in pure Julia, I wanted to raise this as it's causing OOM crashes in production workloads.

Full reproduction steps and details in: MilesCranmer/PySR#764, including detailed diagnostics on the memory usage `​​​​

**Comment by vchuravy** [comment]
Does this reproduce without Python in the loop?

**Comment by MilesCranmer** [comment]
Just checked and, yes, it seems to continually to increase in memory, albeit slowly. It's slow enough that the OOM error only happens after 11 hours of production runtime.

```julia
using SymbolicRegression

X = randn(Float32, 5, 10_000)
y = 2 * cos.(X[4, :]) + X[1, :] .^ 2 .- 2

options = SymbolicRegression.Options(;
    binary_operators=[+, *, /, -],
    unary_operators=[cos, exp],
)

hall_of_fame = equation_search(X, y; niterations=1000000000, options=options, parallelism=:multiprocessing)
```

Just to clarify, Python just calls a Julia method that runs for 12 hours without passing control back to Python. I don't expect Python to factor into things. The new julia processes are spawned from Julia and do not interact with Python.

Here are some plots @GoldenGoldy made, with memory usage per Julia process over the course of the 12-hour run:

Julia 1.11:
![Image](https://github.com/user-attachments/assets/f65f1ab6-d81c-4026-97b4-102cdc25b83c)

and Julia 1.10:
![Image](https://github.com/user-attachments/assets/49d6cacc-fc7a-4d36-a830-54b67ad9ce0f)

**Comment by gbaraldi** [comment]
If possible can you take heap snapshots at the start and after a while to see what is being allocated?

**Comment by gbaraldi** [comment]
`Profile.take_heap_snapshot` it creates a file on `pwd` if I recall correctly. Then you can open it using the chrome dev tools

**Comment by MilesCranmer** [comment]
Ok. I made some heap snapshots. Do you want the full files? (250 MB each). Not sure what I am supposed to look for though.

**Comment by gbaraldi** [comment]
Are the start one and the end one the same size? 🤔

**Comment by gbaraldi** [comment]
The heap snapshot will see everything that is live. I want to see if it's an actual leak i.e a pointer we forgot to call free on or extra live objects around for some reason. `take_heap_snapshot` records only the current process.

**Comment by MilesCranmer** [comment]
So the heap snapshots are about the same size, even over a 10 minute interval. And I am looking at the memory breakdown and they seem quite similar in where memory is allocated too. But despite this, the process's allocated memory continues to increase.

So does this mean it's a real leak?

**Comment by d-netto** [comment]
Might be useful to check whether the memory increase/possible leak is stemming from an increase in pool allocated pages or an increase in mallocd memory.

I.e. https://github.com/JuliaLang/julia/issues/55794#issuecomment-2357217159.

Also, does this only reproduce when using multiple GC threads or also reproduces with a single GC thread?

**Comment by MilesCranmer** [comment]
Over a 30 minute interval, the heap snapshots are still pretty much the same. But the memory usage of the actual Julia process is greater.

@d-netto would it track that? If it doesn't show up in the live objects then I would have thought that means the GC is unaware of it existing?

It should be easy to reproduce locally with the code above if you want to poke at certain things.

**Comment by MilesCranmer** [comment]
Copying @GoldenGoldy's comment from [here](https://github.com/MilesCranmer/PySR/issues/764#issuecomment-2520652914). Basically the use of multiprocessing seems to not relevant for the leak; it seems it happens regardless of processing mode:

> I wanted to do multiple additional tests but lacked the time. However, I did manage to do one test with `parallelism="multithreading"`. Again no issues on Julia 1.10, while memory usage continues to grow on Julia 1.11.
> 
> In both cases I forced the Julia version, using:
> 
> > import juliapkg
> > juliapkg.require_julia("~1.10")
> > from pysr import PySRRegressor
> 
> or
> 
> > import juliapkg
> > juliapkg.require_julia("~1.11")
> > from pysr import PySRRegressor
> 
> **Julia 1.10** ![PySR_memory_usage_force_Julia1_10_multithreading](https://private-user-images.githubusercontent.com/86769288/392880862-c2845d03-5f9b-4c16-87b5-baee243291d3.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTU3MTAsIm5iZiI6MTczMzQxNTQxMCwicGF0aCI6Ii84Njc2OTI4OC8zOTI4ODA4NjItYzI4NDVkMDMtNWY5Yi00YzE2LTg3YjUtYmFlZTI0MzI5MWQzLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE2MTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZTdiMzA0YzIwZTJlMDI5NjJhNmNhMTdlMDgxMGE1NjZmNzRiZmNiNjE5YTJiNDU5MThjNDhiNGJmZjg2MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._b9fhScJTeF0KkPkmTLyWIZdivRV1EvMeGT_PGKhleo)
> 
> **Julia 1.11** ![PySR_memory_usage_force_Julia1_11_multithreading](https://private-user-images.githubusercontent.com/86769288/392881180-fb4877d4-be11-4341-8565-6e5f7135099c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTU3MTAsIm5iZiI6MTczMzQxNTQxMCwicGF0aCI6Ii84Njc2OTI4OC8zOTI4ODExODAtZmI0ODc3ZDQtYmUxMS00MzQxLTg1NjUtNmU1ZjcxMzUwOTljLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE2MTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViOWM5MDMyNzkxNmRiODkxM2Q3ZWUxMDkxY2M1MGY2YmE3NjAzODI3MzdmNDQ3ZjA2ZTkwOGUyN2E3YTI0YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8nMnzgW3YRPiVnnxCUgiSClhVVw7shByncXHsbuBJBU)


(They are using a VM with 240 GB of memory which is why it climbs so high before an OOM)

Note the two other colors are kernel and disk data, which remain flat in both cases.

**Comment by gbaraldi** [comment]
Do you see a leak on macos as well? Because on my laptop It's running for around 30 minutes and it's still around 1.2GB memory usage

**Comment by MilesCranmer** [comment]
I'm on macOS, yes. Note that if you run the original script above it launches additional Julia processes - those ones have the blow-up in memory while the head worker is fairly flat. But you could run the following to just have multithreading instead:

```julia
using SymbolicRegression

X = randn(Float32, 5, 10_000)
y = 2 * cos.(X[4, :]) + X[1, :] .^ 2 .- 2

options = SymbolicRegression.Options(;
    binary_operators=[+, *, /, -],
    unary_operators=[cos, exp],
)

hall_of_fame = equation_search(X, y; niterations=1000000000, options=options)
```

The memory fluctuates a lot for me, but it still does trend higher. Is yours constant at 1.2 GiB?

However I wouldn't expect something identical to @GoldenGoldy because they use slightly different settings. They couldn't share the full script - presumably due to it being company code - but I can definitely reproduce a memory leak on my machine with this code.

**Comment by gbaraldi** [comment]
Yeah it just seems constant to me.
![Image](https://github.com/user-attachments/assets/11fec9cf-1b37-4bbd-9adb-2fdfd742c6cf)

**Comment by MilesCranmer** [comment]
It looks to be using multiprocessing in that example; can you try the multithreading instead? i.e.,:

```julia
using SymbolicRegression
X = randn(Float32, 5, 10_000)
y = randn(Float32, 10_000)
options = SymbolicRegression.Options(binary_operators=[+, *, /, -], unary_operators=[cos, exp])
hall_of_fame = equation_search(X, y; niterations=1000000000, options=options)
```

Are you using top? You could try [btop](https://github.com/aristocratos/btop) which lets you monitor it over time and I find is a bit more accurate

**Comment by gbaraldi** [comment]
Can you run it with `GC.enable_logging` because on my machine it looks like we are increasing the amount of memory we have mapped. It might be due to fragmentation or something else.

**Comment by MilesCranmer** [comment]
I think their server run just accentuated the problem due to larger compute power - i.e., they can generate garbage quicker.

> we are increasing the amount of memory we have mapped. It might be due to fragmentation or something else

I don't have the background to know what this means so forgive my naiveté – do you mean this _is_ a memory leak? Or it is something else?

**Comment by gbaraldi** [comment]
I'm not sure yet. It looks to me julia thinks there are more and more objects alive. At least it maps more and more memory.

**Comment by MilesCranmer** [comment]
(Just sent the heap snapshots on slack by the way)

**Comment by MilesCranmer** [comment]
Ping on this. Is there anything I can help with or look at? This is a major bug for downstream users so I want to fix it ASAP if at all possible

**Comment by MilesCranmer** [comment]
One more experiment to the roster: I confirmed that `--gcthreads=1` does not fix the problem, so this does not seem related to #56735

**Comment by GoldenGoldy** [comment]
Just want to add that using:

> using SymbolicRegression
X = randn(Float32, 2, 2500)
y = randn(Float32, 2500)
options = SymbolicRegression.Options(binary_operators=[+, *, /, -], unary_operators=[cos, exp])
hall_of_fame = equation_search(X, y; niterations=1000000000, options=options)

the memory usage increases much faster than with:

> using SymbolicRegression
X = randn(Float32, 5, 10_000)
y = randn(Float32, 10_000)
options = SymbolicRegression.Options(binary_operators=[+, *, /, -], unary_operators=[cos, exp])
hall_of_fame = equation_search(X, y; niterations=1000000000, options=options

See https://github.com/MilesCranmer/PySR/issues/764#issuecomment-2525107560 for more details and graphs.

**Comment by d-netto** [comment]
Ran this for 5min on my M2:

```Julia
using SymbolicRegression
X = randn(Float32, 2, 2500)
y = randn(Float32, 2500)
options = SymbolicRegression.Options(binary_operators=[+, *, /, -], unary_operators=[cos, exp])
GC.enable_logging(true)
hall_of_fame = equation_search(X, y; niterations=1000000000, options=options)
```

Could reproduce the fast memory increase.

I noticed that the vast majority of the memory reported by `GC.enable_logging` is coming from mallocd memory, not pool allocated memory -- e.g. here is one line from `GC.enable_logging` that I got after running this benchmark for a few minutes, notice how `bytes_mapped` (pools) is around than 10% of the heap size:

```
Heap stats: bytes_mapped 2048.00 MB, bytes_resident 2048.00 MB, ..., heap_size 23823.30 MB, heap_target 25014.47 MB
```

FWIW, another user opened https://discourse.julialang.org/t/dont-understand-why-code-runs-out-of-memory-and-crashes/123559/22. After running their reproducer with `GC.enable_logging` I observed the same thing: heap size increases, but most of it is mallocd memory, which doesn't shrink even if you run a GC.

Didn't investigate further to know whether it's related, but seems suspicious...

**Comment by MilesCranmer** [comment]
Thanks @d-netto. Via that thread I also found `ccall(:malloc_trim, Int32, (Int32,), 0)` on https://discourse.julialang.org/t/memory-management/102567/3. Do you know if there is an equivalent of `malloc_trim` for macOS so I can test this?

**Comment by vchuravy** [comment]
Does a heap-snapshot show the memory? If so, it should tell us why we think it is being rooted.

**Comment by felixcremer** [comment]
I think I might also be  running into this problem as described in https://github.com/EarthyScience/RQADeforestation.jl/issues/36.

I am currently producing heap snapshots with julia 1.11. Is there something specific that I should be looking for in them?

**Comment by IanButterworth** [comment]
@vchuravy I don't know what to look for but with vscode you can also diff two heapsnapshots

![Image](https://github.com/user-attachments/assets/2fc7290a-e8de-4495-a246-308d76a045f3)

**Comment by gbaraldi** [comment]
A bisection using 
```julia
using StatsBase
function Simulate()
    Simulations=Int(1e7)
    Size=1000
    result = Array{Float64}(undef, Simulations, 1)
    Threads.@threads for i = 1:Simulations
         x = randn(Size)
         s = sort(x)
        result[i, 1] = s[1]
    end
    println(median(result))
end
for i in 1:1000
    println(i)
    Simulate()
    GC.gc(true)
    # Print live_bytes
    println("live_bytes in MB: ", Base.gc_live_bytes() / 1024^2)
    sleep(10) # sleep for 10 seconds
end
```
shows the memory PR https://github.com/JuliaLang/julia/commit/909bceae8a60969dfceba4924142e5efee459d47

**Comment by gbaraldi** [comment]
Multithreading is not needed

**Comment by MilesCranmer** [comment]
Is it any object, or only `Memory`-based allocations?

**Comment by oscardssmith** [comment]
So the issue Gabriel found is https://github.com/JuliaLang/julia/pull/55223, but that doesn't seem to be the whole problem.

**Comment by MilesCranmer** [comment]
Confirmed https://github.com/JuliaLang/julia/pull/56801 fixes this.
