### ISSUE TITLE
Tuple assigments fail in short-circuit evaluations

### ISSUE THREAD

**Issue by subthedubdub** [JuliaLang/julia#56770]
``` julia
begin
	# valid
	x,y = 1,1
	# valid
	x,y  = (2,2)
	# valid
	true && (x,y = (3,3) )
	# invalid
	true && (x,y = 4,4)
end
```

The last assignment gives the following error:

```
ERROR: syntax: invalid named tuple element "4"
```

I don't think this is the intended parsing behavior.

Tested on 1.11.1 on Linux/amd64.

**Comment by nsajko** [comment]
This is not related to short-circuit operators, the enclosing parentheses cause the expression to be interpreted as a named tuple literal:

```julia-repl
julia> (x, y = 4, 5)
ERROR: syntax: invalid named tuple element "5" around REPL[1]:1
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```

A workaround is to add even more parentheses to disambiguate:

```julia-repl
julia> ((x, y) = (4, 5))
(4, 5)

julia> x
4
```
