### ISSUE TITLE
exp of some NaNs is negative

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#56782]
Presumably, negative `exp` should never happen, and this should return a `NaN` instead?
```julia
julia> reinterpret(Float64, 0x7ffbb14880000000)
NaN

julia> exp(reinterpret(Float64, 0x7ffbb14880000000))
-9.627794635514914e-309
```

**Comment by oscardssmith** [comment]
yeah, this is bad.

**Comment by oscardssmith** [comment]
all of those are fixed by my pr, right?

**Comment by inkydragon** [comment]
> all of those are fixed by my pr, right?

I guess so, since all those functions are related to `exp`.
