### ISSUE TITLE
Base.cwstring() errors from null-terminated input strings

### ISSUE THREAD

**Issue by rileysheridan** [JuliaLang/julia#56795]
Since output vectors are already null terminated, can we have Base.cwstring() ignore or trim terminating NULs on the input string to keep an error from being thrown?
```julia
julia> Base.cwstring("Test")
5-element Vector{UInt16}:
 0x0054
 0x0065
 0x0073
 0x0074
 0x0000

julia> Base.cwstring("Test\0")
ERROR: ArgumentError: embedded NULs are not allowed in C strings: "Test\0"
Stacktrace:
 [1] cwstring(s::String)
   @ Base .\strings\cstring.jl:121
 [2] top-level scope
   @ REPL[10]:1
```
https://github.com/JuliaLang/julia/blob/b0c1525f1731186767ae42e7d625bf0909e49af8/base/strings/cstring.jl#L109-L123

**Comment by vtjnash** [comment]
> trim terminating NULs on the input string

Julia strings do not have a notion of terminating NUL: all bytes are equally part of the string without prejudice to their particular value

**Comment by rileysheridan** [comment]
My mistake. In that case, I assume what I’ve shown is all intended behavior and we can close leaving the code as is?

**Comment by vtjnash** [comment]
It is intended, since otherwise length and sizeof would give incorrect results
