### ISSUE TITLE
Iteration order of `Dict`

### ISSUE THREAD

**Issue by 3f6a** [JuliaLang/julia#56841]
If `dict::Dict`, are all of the following:

```julia
keys(dict)
values(dict)
pairs(dict)
[(k,v) for (k,v) in dict]
```

guaranteed to iterate entries of `dict` in the **same** order ?

Currently the documentation states that `keys(dict)` and `values(dict)` iterate in the same order. But it is not stated whether this is the same order as that used by `pairs(dict)`, or when looping, `for (k,v) in dict`.

If this is guaranteed, can it be mentioned explicitly in the documentation?

**Comment by oscardssmith** [comment]
I think this would be reasonable to document/guarentee. It's somewhat hard to imagine a decent Dict design where this wouldn't be true.

**Comment by inkydragon** [comment]
> I presume that when looping, for (k,v) in dict, this is implicitly calling pairs ?

The `for ... in` syntax and `pairs` both use `Generator` to iterate over collections.

https://github.com/JuliaLang/julia/blob/b4c5e58a976cbe48a6e5ec27f4408312d8073218/base/abstractdict.jl#L174-L176

```jl
julia> d = Dict([1=>1, 2=>2])
Dict{Int64, Int64} with 2 entries:
  2 => 2
  1 => 1

julia> f() = [ (k,v) for (k,v) in d ]
f (generic function with 1 method)

julia> @code_lowered f()
CodeInfo(
1 ─ %1 = Main.:(var"#11#12")
│        #11 = %new(%1)
│   %3 = #11
│   %4 = Main.d
│   %5 = Base.Generator(%3, %4)
│   %6 = Base.collect(%5)
└──      return %6
)
```

**Comment by DilumAluthge** [comment]
If it's going to be explicitly guaranteed in the documentation, there should probably be tests to make sure it doesn't regress. Do we currently have such tests?
