### ISSUE TITLE
Struct corruption/seg fault with exact same code only inside function

### ISSUE THREAD

**Issue by mattsignorelli** [JuliaLang/julia#56873]
Here is a minimal working example:
```julia
GC.enable(false) # Just to be sure...

mutable struct Test{T}
  a::T
end

t = Test(5)

# Now get stable pointer to pointer of t:
ptrptr = Base.unsafe_convert(Ptr{Ptr{typeof(t)}}, Base.unsafe_convert(Ptr{Cvoid}, Ref(pointer_from_objref(t))))

show(unsafe_load(unsafe_load(ptrptr))) # All is fine

# Now we use the exact same code as above but put inside function:
getptrptr(t) = Base.unsafe_convert(Ptr{Ptr{typeof(t)}}, Base.unsafe_convert(Ptr{Cvoid}, Ref(pointer_from_objref(t))))

ptrptr = getptrptr(t)

show(unsafe_load(unsafe_load(ptrptr))) # CORRUPTED/SEG FAULT!
```

I see this on at least 1.11 and 1.10 but here is my versioninfo:

```julia
julia> versioninfo()
Julia Version 1.11.2
Commit 5e9a32e7af2 (2024-12-01 20:02 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 24 × Apple M2 Ultra
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m2)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
Environment:
  DYLD_FALLBACK_LIBRARY_PATH = /Users/mgs255/Software/bmad/bmad-ecosystem/production/lib:/Users/mgs255/Software/bmad/bmad-ecosystem/debug/lib
  LD_LIBRARY_PATH = /Users/mgs255/Software/bmad/bmad-ecosystem/production/lib:/Users/mgs255/Software/bmad/bmad-ecosystem/debug/lib
```

**Comment by nsajko** [comment]
Not sure, but I think this is user error. Pointers to Julia-owned memory should be protected using [`GC.@preserve`](https://docs.julialang.org/en/v1/base/base/#Base.GC.@preserve).

**Comment by mattsignorelli** [comment]
> Not sure, but I think this is user error. Pointers to Julia-owned memory should be protected using [`GC.@preserve`](https://docs.julialang.org/en/v1/base/base/#Base.GC.@preserve).

See the first line in the MWE... the garbage collector is turned off.

**Comment by nsajko** [comment]
That doesn't seem relevant. I guess the value of a `Ptr` to Julia-owned memory is undefined.

**Comment by inkydragon** [comment]
It's a UB.

> - Retention of pointers to GC-tracked objects outside of a `@GC.preserve` region

https://github.com/JuliaLang/julia/pull/54099/files#diff-cad50cf26296590b1937056ff6064bd99292b8428c0fdff1db0f682e8a48551cR27

**Comment by mattsignorelli** [comment]
Thanks... a warning should be added to `pointer_from_objref` that such pointer only remains valid when the object is `GC.@preserve`-ed, since the current wording states that the object must simply remain referenced, which in the case above, it is.

**Comment by vtjnash** [comment]
The `GC.@preserve` is not special in any particular way to create a reference. You just violated the rule that it must have any reference, since the object was dead immediately after the `pointer_from_objref` call, and you did not appear to make any attempt to prevent that.

In this case, the error is that you also failed to return the `Ref` object, after calling the `unsafe_convert` method on it

**Comment by mattsignorelli** [comment]
> The `GC.@preserve` is not special in any particular way to create a reference. You just violated the rule that it must have any reference, since the object was dead immediately after the `pointer_from_objref` call, and you did not appear to make any attempt to prevent that.
> 
> In this case, the error is that you also failed to return the `Ref` object, after calling the `unsafe_convert` method on it

Why would the object be "dead"? I disabled the garbage collector

**Comment by vtjnash** [comment]
The garbage collector merely frees memory after it is dead, but it is not the semantic definition of being dead, so makes no difference here

**Comment by oscardssmith** [comment]
specifically, disabling the GC only disables run time garbage collection, but the compiler is allowed to emit code that prevents allocations from existing/automatically freeing pointers if the object is proovably dead by language semantics.

**Comment by mattsignorelli** [comment]
I see, thanks for the explanation!
