### ISSUE TITLE
unreachable code interacts with scoping rules and changes program behavior

### ISSUE THREAD

**Issue by sadish-d** [JuliaLang/julia#56874]
The code below prints:

>I'm not guilty.

If you uncomment the line marked `unleash me`, it prints:

>I'm guilty. But you're never going to know. Unless you've messed with time travel.

```jl
let
    let
        admit_guilt = true
    end
    if @isdefined(admit_guilt)
        admit_guilt && println("I'm guilty. But you're never going to know. Unless you've messed with time travel.")
    else
        println("I'm not guilty.")
        if false # code inside this block never executes
            println("a secret never spilled")
            # admit_guilt = true #---------------- unleash me
        end
    end
end
```

It reminds me of this https://github.com/JuliaLang/julia/issues/5148#issuecomment-1336341977 , but I think there, the inner functions are getting pulled out and getting defined in the global scope (maybe?). I'm not sure what's going on here.

**Comment by vtjnash** [comment]
It should change the scope from a local in the let block and a different global in the isdefined test, to a local over the whole function, though I don't think that should have changed the result as observed

**Comment by Keno** [comment]
> I'm not sure what's going on here.

The presence of the assignment later in the scope declares it as a local variable for the entire scope. In the `let` block that assignment then applies to the outer scope rather than introducing a new local in the `let` scope, yielding the observed behavior.

**Comment by Keno** [comment]
> I understand [@Keno](https://github.com/Keno) that that's what the behavior would be if the assignment was not in an `if false ... else`

Scoping rules are static and not path sensitive, so the `if` is irrelevant
