### ISSUE TITLE
rationalize uses of error() and throw()

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#5694]
Currently all of these do the same thing:

```
error(BoundsError)
error(BoundsError())
throw(BoundsError())
```

We're not consistent about which of these should be used. It's unnecessarily confusing. Some background:

- One idea was that `error` would be for signaling exceptional conditions, and `throw` would just be control flow.
- `error(string)` wraps the string in an `ErrorException`, so that we generally throw things of type `Exception`. This is not strictly required though, and one could throw a string directly.
- `throw` is a low-level, non-generic function.
- another motivation for something like `error` is that `throw(SomeException("message"))` is generally too verbose

If we were going to use `throw` in the control-flow sense, it would probably need 2 arguments (`throw(label, value)`), so we don't necessarily need 2 names to disambiguate.

My preferred idiom is `throw(SomeException())` since it clearly makes an exception object and then throws it. The only downside is verbosity.

Wrapping a string in an `ErrorException` obviously doesn't add any interesting information, so maybe `throw("message")` should be considered acceptable. Then `error` could be an alias or deprecation for `throw`.

**Comment by jakebolewski** [comment]
The `error(::Exception)` methods have been deprecated in 0.4-dev in favor of `throw`, so this issue seems like it can be closed now.

**Comment by hayd** [comment]
To clarify, the consensus is that any `error(...)` calls in base should be made more specific?
