### ISSUE TITLE
parsing APIs that indicate whether something was possible, rather than raising an error?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#5704]
See http://stackoverflow.com/questions/21595246/try-catch-or-type-conversion-performance-in-julia. We have lots of integer, float, expression parsing code that all just raises exceptions rather than indicating whether they succeeded or not, but we discourage try/catch as control flow. Should we provide non-error-raising versions of all of these functions that people can use to test whether some string is a valid float, for example?

**Comment by JeffBezanson** [comment]
`tryparse` added.
