### ISSUE TITLE
Show, showcompact, showall, showlimited, print, repr, summary, and friends

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#5709]
In creating PR #5706 I had some trouble in figuring out what all the different flavors of show do.  There seems to be some consensus on what information should be displayed when pretty-printing types, often like:

```
TypeInformation and some metadata here:
  (with the data expressed here)
```

But how this happens, and, more importantly, how output is limited seems to be somewhat haphazard.  In turn, it's hard for users to determine which functions should be implemented for their types — it took me a long time to realize that `showcompact` is orthogonal to `showlimited` (the former does things like shortening floating point precision while the latter omits elements, if I now understand correctly.)

I searched through the issues and while there's some smattering of discussion about specific datatypes and there are some todo notes in the code but I thought there might be some value in looking at the overall architecture. With IJulia and REPL.jl around the corner, it might be nice to standardize some of these functions. I'm sure @tknopp will have some thoughts here as he implements his workspace browser.

As I see it, there are two or three different feature sets that are important for writing to `MIME"text/plain"`:
- Printing with full or limited precision
- Printing with full or limited number of rows and columns
- Printing with or without summary information

Of course, what makes this difficult is that in the implementation, you generally only want to use one function with minor adjustments.  Would the situation be improved with just one show API along the lines of the amazing showarray (albeit without keyword arguments)?

```
function showarray(io::IO, X::AbstractArray,
                   header::Bool=true, limit::Bool=_limit_output,
                   rows = tty_rows()-4, cols = tty_cols())
```

Users could choose to ignore the final arguments and multiple dispatch could be setup to ignore them if users only defined it in terms of the first two arguments.  This is just a spitball to get the discussion rolling… is there interest in doing something here?

**Comment by tkelman** [comment]
Significant refactoring is unlikely on release-0.4, removing from 0.4.x milestone.

**Comment by vtjnash** [comment]
see #14052 proposal for latest cleanup plans

**Comment by JeffBezanson** [comment]
As discussed elsewhere: we need to add an enum to express the available verbosity levels.

**Comment by JeffBezanson** [comment]
Converted to a doc issue to explain how the output system works more.

**Comment by nalimilan** [comment]
Can we close this now?

**Comment by mbauman** [comment]
We no longer have `showcompact`, `showall`, or `showlimited`.  `print` and `summary` are well-defined and simple enough. `display` is for more than just IOs, but defaults to just calling `show`.

`repr` is still a little funny (it's documented to effectively just be `sprint(show, x)` and  _not_ worth overriding).  It might be worth getting rid of it in 2.0 as its name gives me the misconception that it's a fully parseable and round-trippable output. But that's #33260.

`show` itself has gone through multiple revisions and documentation overhauls, now supporting MIME types, IOContexts, and such that get to the root of the original issue.  I think this issue can be closed (especially with the further improvements in #36076, but it's already progressed far enough to close this issue).
