### ISSUE TITLE
ERROR: syntax: extra token ".." after end of expression

### ISSUE THREAD

**Issue by pygy** [JuliaLang/julia#5715]
``` Julia
julia> ..(a,b) = b - a
.. (generic function with 1 method)

julia> 4 .. 6
2

julia> 4 .. 6 .. 7
ERROR: syntax: extra token ".." after end of expression
```

Maybe linked to the #2614 fix?

**Comment by pygy** [comment]
FWIW it is really about more than one `..` operator in a single expression:

```Julia
julia> ..(a, b) = a * b
.. (generic function with 1 method)

julia> "a"*"b".."c"
"abc"

julia> "a".."b"*"c"
"abc"

julia> "a".."b"*"c".."d"
ERROR: syntax: extra token ".." after end of expression.
```

**Comment by brenhinkeller** [comment]
So this one is still true in 1.8.3
```
julia> ..(a,b) = b - a
.. (generic function with 1 method)

julia> 4 .. 6
2

julia> 4 .. 6 .. 7

ERROR: syntax: extra token ".." after end of expression
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Comment by mschauer** [comment]
The consequence of being forced to be explicit ``(4 .. 6) .. 7`` or ``4 .. (6 .. 7)`` seems benign, one less associativity to be remembered.

**Comment by brenhinkeller** [comment]
Yeah, fair. It certainly doesn't seem to have been causing much trouble in the intervening years. I'll close as not planned then, but if folks disagree they should feel free to undo.
