### ISSUE TITLE
linalg tests take too long

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#5735]
Don't get me wrong: this kind of thorough testing is great. But at this point it is slowing us down a bit. We should consider dialing down some sizes or iteration counts, or splitting up the suite so different parts of it can run in parallel. Some of the loops could also potentially be made `@parallel`.

**Comment by andreasnoack** [comment]
The tests are now run in parallel so I think this one can be closed. The time is mainly spent on compilation and the only way to save that time would be to avoid testing some methods.

**Comment by ViralBShah** [comment]
Yes, I think this is not a linalg specific problem - except that there are lots of tests.
