### ISSUE TITLE
Cleanup debug/release in Makefile

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#5774]
Currently the debug version of julia is linked against release versions of flisp and libsupport which is not too useful when debugging, so we should fix that. Also, I'm not sure if https://github.com/JuliaLang/julia/blob/master/src/Makefile.debug is actually used for anything anymore. We should also think about enabling symbols in release mode (we can still ship stripped binaries).

**Comment by ihnorton** [comment]
Related #12151

**Comment by vtjnash** [comment]
This is pretty old
