### ISSUE TITLE
Remove initial value for reduce()

### ISSUE THREAD

**Issue by ivarne** [JuliaLang/julia#5797]
It is unclear how a initial value to reduce should be interpreted, as the associativity for reduce is undefined.

see https://groups.google.com/forum/#!topic/julia-users/7PDUKNcBtQA

**Comment by dlfivefifty** [comment]
In 0.6, `reduce` and `foldr`/`foldl` are inconsistent for empty vectors:
```julia
julia> reduce(+,Float64[])
0.0

julia> foldr(+,Float64[])
ERROR: BoundsError: attempt to access 0-element Array{Float64,1} at index [0]
Stacktrace:
 [1] foldr(::Function, ::Array{Float64,1}) at ./reduce.jl:160

julia> foldl(+,Float64[])
0.0
```

Is this a separate issue?

**Comment by stevengj** [comment]
@dlfivefifty, I think that's a separate issue.

**Comment by TotalVerb** [comment]
`v0` is still meaningful when the operation is both associative and commutative, and so I don't think it should be removed.

**Comment by simonbyrne** [comment]
I think the ship has sailed on this one: `v0` now is a keyword argument `init`, and we define `reduce` to have implementation dependent associativity.
