### ISSUE TITLE
document A_mul_B!

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#5862]
The documentation currently describes `A_mul_B` and friends, but these have been deprecated in favor of `A_mul_B!`.

**Comment by jiahao** [comment]
I've documented the most basic `A_mul_B!` method, but there are many other methods that do not have signatures of this form, notably on special matrices and sparse matrices.

Further discussions should cross-ref #5332 #8001 #8240

**Comment by tkelman** [comment]
backported (in a slightly-roundabout way since the content moved to a different file, see the end of the backport commit message) in e1c00cd6352581e33a53f7e11dbc36d1e16106ea
