### ISSUE TITLE
conditional expressions that eagerly evaluate the condition at top-level?

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#5892]
It would be great to do things like:

```julia
@cond VERSION >= v"0.3-" ? eigvecs(A, ev) : eigvecs(A, ev)[1]
@cond isdefined(:setfield!) ? setfield!(x, y) : setfield(x,y)
@cond WINDOWS ? 1 : 2
```

This would fix #4233 as well as give us an approach to writing code that is compatible with multiple Julia or package versions that isn't as awkward as #5029. (It would be great to have something like this for 0.3, so that package authors can avoid separate branches for different Julia versions provided the differences aren't too big.) I'm not sure how to do this, though. It seems like `@cond` would have to be a macro that calls `eval`. Ignoring that this is considered bad practice, the argument to `eval` seems to be executed in the macro's module and not the calling module, which could be confusing. Any thoughts?

**Comment by tkelman** [comment]
`@static` implemented in #16219
