### ISSUE TITLE
is Float16 a real computational type or not?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#5942]
At this point, Float16 is in a kind of weird limbo where it is sort of a storage type but we keep haphazardly adding more and more functionality to it. I think we really need to figure out where to draw the line here. Either we severely limit the scope of Float16's functionality and stop using it in tests for anything but converting to and from other numeric types, or we just go full throttle and make it a full computation type with as much functionality as Float32 or Float64 – albeit slower, since many operations will not be implemented as native machine ops.

**Comment by StefanKarpinski** [comment]
It's resolved at this point that Float16 is a real computational type: many people want to use if for a variety of purposes and find it frustrating that it doesn't behave the same way as Float32 and Float64; moreover, GPUs have actual support for using Float16 as a computational type.

**Comment by StefanKarpinski** [comment]
What if anything is left to do here?

**Comment by tkelman** [comment]
ping @vchuravy for your thoughts

**Comment by vchuravy** [comment]
There are two main things currently missing.

1. Lowering of `Float16` to `half` instead of `i16` (I think we could do this now)
2. https://github.com/JuliaLang/Juleps/pull/11 or at least https://github.com/JuliaLang/julia/pull/18734

**Comment by yuyichao** [comment]
Both of those affect performance but not functions right?

**Comment by vchuravy** [comment]
Yes, but if we actually want to make use of `Float16` we need both of them. Right now we are eagerly using `Float32` as a fallback, preventing any benefit from actually using `Float16`. (except maybe reduce memory usage and bandwidth)

**Comment by StefanKarpinski** [comment]
Strict performance improvements can happen any time and be backported, so that makes this not a release-blocking issue – it's an issue that anyone who wants to can tackle whenever.

**Comment by tkelman** [comment]
The build system changes and library restructuring to integrate compiler-rt and the rtlib julep are probably too big to backport, but they're making progress.

**Comment by JeffBezanson** [comment]
Closing since there seem to be no more semantic changes needed.
