### ISSUE TITLE
Illegal instruction using Ubuntu nightlies on 32 bit amd

### ISSUE THREAD

**Issue by WestleyArgentum** [JuliaLang/julia#5987]
I don't know if you guys intend to support 32 bit amd processors or not, but right now the nightlies wont open / give an Illegal instruction error :(

**Comment by vtjnash** [comment]
i haven't seen any recent issues mentioning 32-bit issues, so i'm going to assume this has been addressed (by working harder at setting MARCH and JULIA_CPU_TARGET correctly)
