### ISSUE TITLE
rand vs. sample

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#6003]
Base Julia provides the [`rand` and `rand!` functions](http://docs.julialang.org/en/latest/stdlib/base/?highlight=rand#Base.rand), which do random sampling over various domains. The StatsBase package provides [`sample` and `sample!`](https://github.com/JuliaStats/StatsBase.jl#sampling-from-population) with partially overlapping functionality. There have been various threads (e.g. [this one](https://groups.google.com/forum/#!topic/julia-dev/ZvRHOCYBy38)) where people are discussion additional functionality for one or the other. I'm opening this issue to discuss whether these interfaces should be separate or if they should be merged and if they are to remain separate, to clarify the distinction between `rand` and `sample`.

**Comment by tkelman** [comment]
Did not make it into 0.4, removing from milestone.

**Comment by StefanKarpinski** [comment]
Someone needs to own this to make it happen or it's going to slip again.

**Comment by StefanKarpinski** [comment]
It's also a bit unclear what still needs to be done at this point.

**Comment by simonbyrne** [comment]
The main difference now is that `sample` provides keyword arguments for replacement and ordering, e.g.
```
sample(1:10,8,replace=false)
```
Since we can't add more keyword arguments to existing methods

**Comment by simonbyrne** [comment]
and the problem @JeffBezanson mentioned above:
```
julia> rand([1,2])
1

julia> rand((1,2))
1×2 Array{Float64,2}:
 0.966145  0.590825
```
(sample throws a `MethodError` on the tuple one)

**Comment by simonbyrne** [comment]
After some discussion, the decision was made to leave it as is. `rand` and `sample` are indeed subtly different:

* `rand` samples independent observations (either uniform [0,1], uniform from a discrete set, or from a specific distribution if used with `Distributions`),
* `sample` allows for non-independent methods (e.g. without replacement), which are only applicable to finite sets.
