### ISSUE TITLE
Slow complex-real matrix products

### ISSUE THREAD

**Issue by Manticore** [JuliaLang/julia#6040]
Consider [the following benchmark](https://gist.github.com/Manticore/9340564). It compares the performance of the dot product for matrices of different sizes in Julia and in Python.

My configuration:
OSX 10.9.2
Python 3.3.4, numpy 1.8.0
Julia HEAD (as of 4 Mar 2014, commit d36bb08f63880f9428afef5a02daf964d3c2ec40), compiled with Accelerate

The results for the dot tests are (combined side-by-side for convenience)

**Python** | **Julia**
    
    dot(float, float), 10 x 10: 0.08806 s | 0.029476 s
    dot(float, float), 100 x 100: 0.07486 s | 0.079535 s
    dot(float, float), 1000 x 1000: 0.38337 s | 0.39732 s
    dot(complex, float), 10 x 10: 0.19552 s | 0.090843 s
    dot(complex, float), 100 x 100: 0.16334 s | 0.57663 s
    dot(complex, float), 1000 x 1000: 1.5419 s | 5.4734 s
    dot(complex, complex), 10 x 10: 0.14413 s | 0.086742 s
    dot(complex, complex), 100 x 100: 0.15740 s | 0.20056 s
    dot(complex, complex), 1000 x 1000: 1.4927 s | 1.4955 s

For float-float and complex-complex products Julia and Python show similar performance (as I would expect, since they use the same linear algebra backend). But in complex-float products of sufficiently large matrices Julia is suddenly 4 times slower! Is there some float-to-complex conversion happening in the background?

**Comment by andreasnoack** [comment]
The method described by @stevengj has been added in https://github.com/JuliaLang/julia/commit/da8e8ee338058b94ad83e3c705c8f620fbccb757 so the timings are now
```julia
julia> Z=complex(randn(1000,1000),randn(1000,1000));

julia> X=randn(1000,1000);

julia> @time Z*X;
elapsed time: 0.036864228 seconds (16000448 bytes allocated)

julia> @time Z*complex(X);
elapsed time: 0.083695463 seconds (32000240 bytes allocated, 27.56% gc time)
```
The remaining cases should be covered by #2941
