### ISSUE TITLE
deprecate `&x` syntax in ccall, replace with Ref

### ISSUE THREAD

**Issue by pygy** [JuliaLang/julia#6080]
``` Julia
|(::String) = 4
# | (generic function with 49 methods)

&(::String) = 6
# ERROR: syntax: invalid identifier name "::"

|(123,456)
#507

&(123,456)
# ERROR: unsupported or misplaced expression &
```

`Base.(:&)` works as intended.

**Comment by JeffBezanson** [comment]
Now that an alternative is available, we need to decide whether to fully deprecate `&` syntax in `ccall`.

**Comment by tkelman** [comment]
There's still a performance cost to using `Ref` in `ccall` right? Guess that needs fixing before `&` in `ccall` can be deprecated without performance regressions.

**Comment by StefanKarpinski** [comment]
There was a change to use Ref in the LAPACK wrappers and it was way too slow. I believe that performance issue is the blocker from completely removing the use of `&` in `ccall`.

**Comment by JeffBezanson** [comment]
https://github.com/JuliaLang/julia/pull/11402

**Comment by vtjnash** [comment]
need to deprecate `&` in ccall first, which is probably mostly pending https://github.com/JuliaLang/julia/pull/18632 right now (although that's not required for making this efficient – only need the easy case of https://github.com/JuliaLang/julia/pull/8134)

**Comment by JeffBezanson** [comment]
#22684 and #22734 will enable this.

**Comment by yuyichao** [comment]
Ah, so here's the issue..... Somehow I couldn't find this when openning the two prs....

**Comment by musm** [comment]
https://github.com/JuliaLang/julia/pull/22684 has been merged 👍   so the only thing left here is to update base definitions that use `&` and add a deprecation ?

**Comment by StefanKarpinski** [comment]
Yeah, I think so. There was a PR for this, but it may be easier to just do it from scratch. Do you want to tackle this, @musm? If so, that would be great.

**Comment by musm** [comment]
@StefanKarpinski  I am working on this

**Comment by JeffBezanson** [comment]
Deprecation is in for 0.7. For 1.0, we should change the parsing of `&x` to a `call` expression.
