### ISSUE TITLE
use SPDX license identifiers for licenses

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#6095]
https://spdx.org/licenses/

We could also maybe get license text from there.

https://tldrlegal.com/

Integration with tldr legal might be good too.

**Comment by souravsingh** [comment]
I would like to work on the issue? How do I go with it?

**Comment by StefanKarpinski** [comment]
I'm not sure we really want to do this anymore. We tend to want to encourage choosing one of a small, fixed set of licenses; this would seem to encourage choosing from a larger pool of licenses.
