### ISSUE TITLE
UTF-8 combining characters and normalization in reverse()

### ISSUE THREAD

**Issue by andrioni** [JuliaLang/julia#6165]
```julia
julia> "noe\u0308l"
"noël"

julia> reverse("noe\u0308l")
"l̈eon"

julia> length("noe\u0308l")
5

julia> uppercase("baﬄe")
"BAﬄE"
```
(it appears that Github also doesn't like them, [examples taken from here](http://mortoray.com/2013/11/27/the-string-type-is-broken/))

Backspace support is also broken on the REPL: if you press backspace twice from "noël", it shows you "no", but actually represents "noe".

What should be our approach in this case? NFKC does solve both issues above, but I'm not sure how good it is to normalize every string before operating on them:

```julia
julia> length(normalize_string("noe\u0308l", :NFKC))
4

julia> reverse(normalize_string("noe\u0308l", :NFKC))
"lëon"

julia> uppercase(normalize_string("baﬄe", :NFKC))
"BAFFLE"
```

(related to #5434, #5903)

**Comment by PallHaraldsson** [comment]
@stevengj: "I vote that we just remove reverse(::String) function from Base". I may not have thought this through, but doesn't reverse imply indexing must be well defined (and it isn't - see https://github.com/JuliaLang/julia/issues/9297#issuecomment-124101578)

If/when indexing is gone and you can reintroduce it explicitly, say you want codepoint-indexing or whatever (byte, grapheme), does reverse get trivial then?

**Comment by PallHaraldsson** [comment]
Add breaking label? Appropriate if changing from codepoint-meaning (or just dropping function..). Seems I just do not have the right.

**Comment by stevengj** [comment]
I think this issue can be closed.

It seems to have become clear that we need a `reverse` function for efficient reversed string processing with external libraries, especially PCRE.  And for this purpose, you want to reverse codepoints, not graphemes.

No one has come up with any use case for reversing graphemes.  This is possible in Julia as noted above, via the `graphemes` iterator, but with no real application it doesn't make sense to make it the default or even to provide a wrapper function in Base.

**Comment by ScottPJones** [comment]
:clap: Good to see this closed!
