### ISSUE TITLE
Building `debug` on Windows fails because it looks for `release` libjulia.dll

### ISSUE THREAD

**Issue by cmundi** [JuliaLang/julia#6172]
`make debug` fails because line 76 of the top-level `Makefile` is used for both debug and release but attempts to always link with the release build of `libjulia.dll`. editing that line, I was able to build debug.  The julia Makefile is just subtle enough that I'm not going to try to fix this just yet.  :)

**Comment by ihnorton** [comment]
Fixed by #12151.
