### ISSUE TITLE
move ambiguity warnings to run time

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#6190]
When method extension coupled with multiple dispatch mechanism, we tend to be always find ourselves in the loop of continuing adding disambiguating methods. Seriously, this is unsustainable in the long run.

Consider the following:
```julia
# suppose this is defined in base

type A <: BaseT end

+(::A, ::A) = println("A + A")   # this needs to be in front
+(::A, ::BaseT) = println("A + BaseT")
+(::BaseT, ::A) = println("BaseT + A")
```

If someone want to write a package that extends ``BaseT``, he will need to write
```julia
module modB
import Base: BaseT, A, +

type B <: BaseT end

# for the second type, you have to put three methods in front
# in order to reduce ambiguity
+(::A, ::B) = println("A and B")
+(::B, ::A) = println("B and A")
+(::B, ::B) = println("B and B")

+(::B, ::BaseT) = println("B and BaseT") 
+(::BaseT, ::B) = println("BaseT and B")
end
```
If there are ``n`` subtypes of ``BaseT`` in the ``Base``, ``O(n^2)`` disambiguating methods need to be added. 

What's worse, if another one independently creates another package that extends ``BaseT``, as below:
```julia
module modC
import Base: BaseT, A, +

type C <: BaseT end

+(::A, ::C) = println("A and C")
+(::C, ::A) = println("C and A")
+(::C, ::C) = println("C and C")

foo(::C, ::BaseT) = println("C and BaseT") 
foo(::BaseT, ::C) = println("BaseT and C")
end
``` 

Then when one want to import both packages (even without ``using``, just ``import``), there will be ambiguities warnings about ``+(B, C)`` etc. 

This issue has caused a lot of headaches for packages that try to define their own customized array types, for example:
- https://github.com/JuliaStats/DataArrays.jl/issues/51
- https://github.com/JuliaStats/DataArrays.jl/issues/77

*Images* and some other packages also encounter such problems.

Whereas this might be solved by continuously adding disambiguating methods, problems still exist (or even worse) when you use two or more of these packages together. 
Are we going to add disambiguating methods for every pair of array types residing in different packages?

Just try the following, you will see screens full of ambiguities warnings (though just importing either one will be fine):
```julia
import DataArrays
import Images
```

We seriously need a fundamental solution to this.

**Comment by amitmurthy** [comment]
One "solution" mentioned by Jeff in this thread, which was not discussed further is - "Another solution is to resolve left-to-right, which is easy to understand, but also a bit arbitrary."

That approach can solve one particular case which I am not able to easily correct right now:

If I define a `print(io::AsyncStream, xs...)` in `stream.jl`, it clashes with `print(io::IO, t::Text)` in `docs.jl`

If left-to-right disambiguation worked, `print(io::AsyncStream, xs...)` would `invoke` the abstract `IO` implementation after locking `io`. Thought I would give an example where a left-to-right disambiguation provided a workable solution.

**Comment by vtjnash** [comment]
this is too big a change to deal with in 0.4.x, should i move this to 0.5 or just remove the target?
