### ISSUE TITLE
julep: conditional modules

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#6195]
currently, some modules (incorrectly and unfortunately) use `Pkg.installed` to decide whether it should include some additional functionality. I would like to propose the following extension to module initialization that could help simplify this situation of optional dependencies:

---
### Rules:
1. During module parse time, a module can declare a dependency on another module, given by name
2. Following the closing of a module (without error), and after all `__init__` functions have run, any modules that declared `module B require Main.C` will be (re-)loaded.
### Example:

``` julia
module A
  module B requires Main.C
    # code in here is part of A iff Main.C is defined as a module
    # it's execution time is defined as after the call to A.__init__ and C.__init__
    using Main.C
    import ..A.something
    something(::C.CType) = 2
  end
  # code in here is always part of A
  something(::Any) = 1
end
# Accessing A.B here would throw an UndefRef-like error, with a message that B requires C
module C
  type CType end
end
# Now A.B exists, and A.something() has extra functionality
```

**Comment by jiahao** [comment]
I've run into a use case which could really benefit from conditional package loading in JuliaLang/IterativeSolvers.jl#35

**Comment by rleegates** [comment]
Any progress on this topic? I really feel the need for conditional imports :)

**Comment by StefanKarpinski** [comment]
I've been wanting this to be merged for about six months now.

**Comment by mbauman** [comment]
[Requires.jl](https://github.com/one-more-minute/Requires.jl) is a very nice stop-gap that has worked well for my purposes.

**Comment by rleegates** [comment]
What's standing in its way? I'm having trouble seeing how your pull request helps my issue. Basically I have a module `Big` that does a bunch of stuff even when a dependency `Dep` is missing, however if it's installed, additional functionality is provided. As far as I understood your pull request, the whole module `Big` requires the dependency, if it's missing, the module `Big` isn't loaded. Is this interpretation correct?

**Comment by StefanKarpinski** [comment]
@vtjnash, have you abandoned this PR entirely? You haven't commented on it since almost a year ago.

**Comment by vtjnash** [comment]
not entirely, i was just finally getting back to even older issues (https://github.com/JuliaLang/julia/pull/1831) and have no shortage of other unresolved proposals (https://github.com/JuliaLang/julia/pulls/vtjnash)

**Comment by ChrisRackauckas** [comment]
Was this abandoned again? I think this should get some precedence since a lot of larger packages like Plots.jl, DifferentialEquations.jl, Optim.jl, Learn.jl, LightGraphs.jl, etc. are running into some issues with having to deal with non-standard approaches to conditional modules / dependencies. It would be nice to have this worked out far before the v0.6.0 milestone so that way packages could do large overhauls to support whatever the solution is.

**Comment by sbromberger** [comment]
Yeah. We had to break out a bunch of things into a separate module in order to keep LightGraphs from imploding due to fragility issues with all the dependencies. We also now have a policy in place with respect to PRs that severely restrict what we allow in LightGraphs now (not a good thing):

> - PRs introducing dependencies on core Julia packages are ok.
- PRs introducing dependencies on non-core "leaf" packages (no subdependencies except for core Julia packages) are less ok.
- PRs introducing dependencies on non-core non-leaf packages require strict scrutiny and will likely not be accepted without some compelling reason (urgent bugfix or much-needed functionality).

Conditional dependencies would go a long way to reducing the problems of "dependence fragility" within Julia packages. (We don't want to get to a point where Node found itself a few months back.)

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/issues/15705 is the latest thinking. needs an implementation that ties into precompilation correctly. in the meantime, when it comes to conditional dependencies, either disable prwcompilation or don't do things conditionally. Make separate packages for features that have additional dependencies that won't always be needed by a "main" package.

**Comment by StefanKarpinski** [comment]
The latest latest thinking (based on a discussion @JeffBezanson, @vtjnash and I had last week), is that what we want is very similar to what I originally proposed in https://github.com/JuliaLang/julia/issues/2025 – i.e. have a mechanism whereby packages, when they're loaded, can register a module for later loading once some set of modules have all been loaded. Note that if you want code for A that depends on both B and C then you'll want to wait until all of A, B and C have been loaded, so this isn't just a binary relation.

**Comment by tbreloff** [comment]
This is the "Requires" model, and if that was built-in and played well with
precompilation it would be a big win!

The other use case is when you want to do something only when a package is
installed (not just when it's explicitly loaded).

I think both uses would share the tricky parts of the implementation,
namely how to defer code execution until some event, and how to make it
play well with precompilation. I just hope the "on install" event is also
able to be supported, in addition to the "on import" event.

**Comment by sbromberger** [comment]
The problem we had with `Requires.jl` was that any use of macros from an external package meant that it couldn't be conditionally loaded. This affected us primarily because of JuMP.

**Comment by tbreloff** [comment]
>  any use of macros from an external package meant that it couldn't be conditionally loaded

But wasn't that because Requires was an external hack to try to get the functionality we wanted?  If this was built into the core of the language, presumably macros could be deferred until they were ready to be run.

**Comment by JeffBezanson** [comment]
A bit more on @StefanKarpinski 's description above: https://github.com/JuliaLang/julia/issues/15705#issuecomment-254264419

**Comment by richardreeve** [comment]
I see this has been moved to a 1.0 milestone, so I presume this is a way off now, but is it still in someone's plans, because it would be incredibly useful!

**Comment by StefanKarpinski** [comment]
Yes, we really need this in 1.0 – it's a big problem for the package ecosystem currently.

**Comment by richardreeve** [comment]
Good to know, thanks.

**Comment by richardreeve** [comment]
@StefanKarpinski So does this mean conditional modules are not going into 1.0 any more? Or are they already implemented somewhere?

**Comment by hayd** [comment]
@richardreeve see https://github.com/JuliaLang/julia/issues/2025#issuecomment-338005473
