### ISSUE TITLE
REPL semicolon output suppression is borked

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#6225]
As @StefanKarpinski remarked in JuliaLang/IJulia.jl#160, the REPL currently does:
```julia
julia> 1; #=# 2

julia> ans
2
```
Both IJulia and the REPL use a simplistic heuristic for suppressing output, but I think IJulia's `ismatch(r";\s*$", code)` may be better here (even if it fails to suppress output from `1; #`).

In principle, there is probably some way to get the Julia parser to tell us if input ended with a semicolon, and e.g. have `include_string` return `nothing` in that case, but it may be tricky because I don't think we want `x;` to parse to a semantically different expression than `x`.

cc: @loladiro, JuliaLang/IJulia.jl#109

**Comment by jakebolewski** [comment]
This now seems to do the right thing.
