### ISSUE TITLE
Problems adding nodes via ssh

### ISSUE THREAD

**Issue by jumutc** [JuliaLang/julia#6256]
I'm using the latest available version of Julia. When I'm adding a node via ```addprocs({"n1","n2"},tunnel=true)``` the first node (worker) is added successfully while for the second one I'm getting:
```
fatal error on fatal error on 31: 30: ERROR: ERROR: connect: host is unreachable (EHOSTUNREACH)connect: host is unreachable (EHOSTUNREACH)
 in 
 in wait at task.jl:276
 in wait at task.jl:188
 in stream_wait at stream.jl:252
 in wait_connected at stream.jl:290wait at task.jl:276
 in wait at task.jl:188
 in stream_wait at stream.jl:252
 in wait_connected at stream.jl:290
 in connect at stream.jl:876
 in Worker at multi.jl:117

 in connect at stream.jl:876
 in Worker at multi.jl:117
 in anonymous at task.jl:864 in anonymous at task.jl:864

Worker 31 terminated.
```  

If I want to add local workers through the same command: ```addprocs(1)``` afterwards I'm getting exactly the same error which seems to me even more bizarre! The error doesn't depend on a particular node and replicates for all machines in my local network. The workers for the first host are added while for the second one I can see how ```julia-basic``` process is starting for the couple of seconds but hangs-up after I get the error.   

All the nodes are in the local network and are easily accessibly via ssh without the password.

**Comment by amitmurthy** [comment]
Superseded by #6264
