### ISSUE TITLE
Remove direct visibility constraints for nodes in a cluster

### ISSUE THREAD

**Issue by jumutc** [JuliaLang/julia#6264]
For a heterogeneous clusters where nodes are visible to each other only via the ssh tunnelling it would be nice to have a workaround for making ```addprocs``` routine working in this case.

Please consider another issue https://github.com/JuliaLang/julia/issues/6256 which explained the problem and resulted in the necessity of a feature request.

**Comment by amitmurthy** [comment]
Feature best done in an external ClusterManager and possibly added to `ClusterManagers.jl`
