### ISSUE TITLE
deprecate then remove a.(b) syntax

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#6268]
https://groups.google.com/forum/#!topic/julia-users/4xUurbP6INA

**Comment by jakebolewski** [comment]
Does anyone have a workaround for the edge case I raised?  Otherwise I don't think this syntax can be deprecated properly.

**Comment by toivoh** [comment]
Where is this edge case used?

**Comment by StefanKarpinski** [comment]
Frees up syntax for hypothetical https://github.com/JuliaLang/julia/pull/15032 syntax.

**Comment by StefanKarpinski** [comment]
All uses of this can be replaced with `getfield`.

**Comment by tkelman** [comment]
Should we pull out just the deprecation piece from #15032 and do that now?

**Comment by StefanKarpinski** [comment]
Yes, I think that's a good thing to do here.

**Comment by ivarne** [comment]
@stevengj Seems like this should be closed by your recent work in https://github.com/JuliaLang/julia/pull/15032?
