### ISSUE TITLE
structure dumping with memory addresses and bits

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#6269]
We have `dump` and `xdump`, which are IMO, both half broken so I end up trying one and then the other and one usually works but it's inconsistent which. I'd like to replace them with something that gives much better low-level information about data structures, including memory addresses and bit patterns. One of the purposes of this should be to illuminate how data is actually laid out in memory – see https://groups.google.com/forum/#!topic/julia-users/9LkAIemc5VE for example. It should be easy to see if fields are stored inline or separately allocated on the heap. I know we work hard to hide that detail, but sometimes it's pretty important and eventually, we're going to have to make documented guarantees about how different structures are laid out for the sake of C interop, if nothing else.

**Comment by StefanKarpinski** [comment]
This seems very much like a feature that can live outside of Base. @JeffBezanson and/or @vtjnash, please leave open if you disagree, but otherwise just closet this.

**Comment by vtjnash** [comment]
Yes. Something like this could live inside InteractiveUtils, but probably editor-specific designs (such as Juno, Jupyter, or my toy data exploration tool from JuliaCon London 2018) are more profitable for others to explore.
