### ISSUE TITLE
REPL: make shell mode sticky?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#6320]
It's pretty common to type several shell commands in a row. It might be a better workflow if shell mode where sticky and required hitting escape or backspace to exit back to normal repl mode. The same could be done for help mode, but it's unclear to me that you actually want to enter multiple help queries in a row.

**Comment by quinnj** [comment]
Is there a way to globally turn on sticky mode? Let's just get that and close this.

**Comment by StefanKarpinski** [comment]
Yeah, I'd still like this. @Keno?

**Comment by Keno** [comment]
Yes, I've come around it having it be sticky. I can submit a pull request later.

**Comment by StefanKarpinski** [comment]
Hah, I noticed that in your presentation :-)

**Comment by kindlychung** [comment]
ESC is used in vi keybindings to exit insert mode, so it will be super annoying for vi veterans.

**Comment by Ismael-VC** [comment]
I would really like to have at least sticky shell mode by default. Both sticky shell and help mode by default have been part of my daily workflow for some time now. IMO sticky help mode is less useful.

Either way there should be an easy way for users to opt in. Currently I use this:

* https://gist.github.com/Ismael-VC/7f44ff56aa53ab2df42dff81fa8feb52#file-juliarc-jl-L128-L139

```julia
# Create sticky REPL functions for shell and help modes
const REPL_MODES_METADATA = @compat Dict(
    :shell => 2,
    :help => 3
)

for (repl_mode, mode_number) in REPL_MODES_METADATA
    sticky_mode = @compat Symbol(:sticky_, repl_mode, :_mode)
    @eval function $(sticky_mode)(enable::Bool = true)
        Base.active_repl.interface.modes[$mode_number].sticky = enable
    end
end
```

* https://gist.github.com/Ismael-VC/7f44ff56aa53ab2df42dff81fa8feb52#file-juliarc-jl-L206-L212

```julia
function setup()
    @async while true
        if isdefined(Base,:active_repl)
            greedy_banner()
            @sync begin
                @async sticky_shell_mode()
                @async sticky_help_mode()
```

**Comment by Roger-luo** [comment]
Vote for stick shell mode and help mode. I think this will make them consistent to current pkg mode.

**Comment by StefanKarpinski** [comment]
We can and do detect when code is being pasted and handle it differently, so this could be another case where we do that.

**Comment by Roger-luo** [comment]
FYI. `ipython` treat multi-line pasted code as a whole block and will not evaluate line by line, which I personally think is quite convenient. You won't be annoyed by un-necessary results in the middle.

**Comment by KristofferC** [comment]
I like to get each evaluation into the REPL history.

**Comment by musm** [comment]
closed by https://github.com/JuliaLang/julia/pull/38646

**Comment by rfourquet** [comment]
What a long standing issue it was for such a technically simple fix!
