### ISSUE TITLE
Embedding docs out of date

### ISSUE THREAD

**Issue by samuelcolvin** [JuliaLang/julia#6327]
https://github.com/JuliaLang/julia/blob/master/doc/manual/embedding.rst

The advice on compiling the test:

```
gcc -o test -I$JULIA_DIR/include/julia -L$JULIA_DIR/usr/lib -ljulia test.c
```

is wrong. For a start the directory $JULIA_DIR/include/julia doesn't exist.

This also affects the embedding example https://github.com/JuliaLang/julia/blob/master/examples/embedding.c as the manual page above seems to be the goto advice on how to compile it.

See [google user group question](https://groups.google.com/forum/#!topic/julia-users/BfXg93CHLrM).

**Comment by mdcfrancis** [comment]
With the latest 0.4 release I'm getting similar linker errors 

gcc -o test -I$JULIA_DIR/include/julia -L$JULIA_DIR/lib/julia -ljulia test.cpp -Wl,-rpath,'$JULIA_DIR/lib/julia'
/tmp/ccj36oRo.o: In function `main':
test.cpp:(.text+0x15): undefined reference to `jl_init'
test.cpp:(.text+0x1f): undefined reference to `jl_eval_string'
test.cpp:(.text+0x29): undefined reference to `jl_atexit_hook'
collect2: error: ld returned 1 exit status

**Comment by ihnorton** [comment]
@mdcfrancis the link targets need to be after the source file. The following works for me (on Ubuntu 14.04):
```
cd usr/lib
gcc -g -o embedding -I../../src -I../../src/support/ -I../../usr/include -L./ ../../examples/embedding.c -ljulia -lm -lLLVM-3.8svn
./embedding
```

**Comment by tkelman** [comment]
I think the documentation and example makefiles are up-to-date now with https://github.com/JuliaLang/julia/pull/21299. Leave a comment or reopen if not.
