### ISSUE TITLE
fma operation?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#6330]
LLVM has a floating-point fma operation:

http://llvm.org/docs/LangRef.html#llvm-fmuladd-intrinsic

Does it make sense to have an `fma` function? It makes sense for floating-point, can be emulated with integers and other numeric types with a simple fallback, and could allow matrix code doing `A*B + C` to avoid temporaries.

**Comment by simonbyrne** [comment]
I think this issue can now be closed, as #9855 covers the indicator issue.
