### ISSUE TITLE
Partial method completion at REPL

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#6338]
It would be cool if we could restrict the methods list by the types of the arguments:

```
julia> a = 1;

julia> dot(a,\t
dot(x::Number,y::Number) at linalg/matmul.jl:53
```

It would be really cool if we could use type inference to get the inferred types of not-yet-evaluated arguments:
```
julia> a = 1;

julia> dot(a+1,\t
dot(x::Number,y::Number) at linalg/matmul.jl:53
```

**Comment by dhoegh** [comment]
This is a really good idea, it is actually so good that Julia already does this today:) I implemented it in #9676 and made some corrections in #10161. But it only handles the first case I do not know if this should be closed or be kept open for the second case.

**Comment by ivarne** [comment]
The seccond case will probably depend on https://github.com/JuliaLang/julia/issues/10091. Maybe just leave a reference there, and close this.

**Comment by Mirage10** [comment]
very very cool. thumbs up!
