### ISSUE TITLE
strtod issue for MSVC

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/julia#6349]
In #6230 it came up that that the flisp unit test did not compile when using MSVC. The issue is that the `strtod` function does not support hex values when using the MSVC runtime. I have just tried this out on VS2010 and can confirm this.

Funnily this means that all the attempts in #5988 to use the MSVC runtime in order to use `_strtod_l` would have been useless.

To solve the issue I think we have to try
http://mirror.fsf.org/pmon2000/3.x/src/sdk/libc/stdlib/strtod.c
again. I once got it almost working but had an error which was actually unrelated (forgot to cleanall).

Would be intersting if the ability to parse hex values is really required for running julia.

(notify @tkelman out this issue)

**Comment by Mike43110** [comment]
I tested and `strod` works with hex floating point literals on VS2015
Also to be noted is that inline assembler on x64 seems to be working now!

**Comment by tkelman** [comment]
Hey, that is really good news. Is VS2015 officially released yet, or is it still a ctp?

**Comment by tkelman** [comment]
Anyone want to build LLVM (not sure which branch - either our patched 3.3, or 3.5.1, or the latest 3.6 branch?) using the latest VS 2015 CTP and post the binaries? I don't have it installed, and it's a pretty huge download.

AppVeyor has a test image with the latest CTP installed, but my LLVM binaries from VS 2013 aren't going to work there.

**Comment by tkelman** [comment]
@Mike432110 are you sure you were building in 64 bit mode? C or C++ code?

Looks like the VS 2015 CTP is finally able to compile C99 in C mode, only 15 years late. Though I am having some issues with the inline assembly still. (working branch at https://github.com/tkelman/julia/compare/appveyor2)

```
task.c(330): error C2036: 'void *': unknown size 
task.c(332): error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture 
```

**Comment by Mike43110** [comment]
I checked again.
Somehow while having x64 selected it was compiling in 32-bit mode : /
Oh well.

Is an x64 llvm necessary? I have (I think, need to test) a working x86 llvm. It builds fine at least. However, an x64 llvm fails to build.

I built (or I hope I built) llvm-svn. It takes about an hour to build, debug takes even longer. If there are any requirements for how llvm must be built please list. Once I am sure it's correct I will happily post the binaries. I should also be able to build an msvc one whenever its needed. My wonderful internet and the fact that my country is undergoing load-shedding (power cuts) may mean that it will take a few hours to post but hopefully it will help.

Two unrelated notes: The .NET news is quite good! Quite interested to test it once they release build guides for Linux. Hoping they will release gui related things. I understood it that it is only console and asp.net for now. Still progress!
The other note is that don't post at 3am... You tend to miss things. Like a release x64 build compiling as release x86 (still have no idea how I got VS to do that!)

I will download the 3.6 branch and build it as well.

**Comment by tkelman** [comment]
Actually we won't need llvm binaries until we can figure out a workaround for the inline assembly, so don't worry about it too much at this point.

From some experiments on appveyor, it looks like compiling in 64 bit, in C mode (which now works for C99, it appears) instead of C++, the `asm` syntax without leading underscores might work, but there are still some error messages about unexpected colons.

**Comment by KristofferC** [comment]
Think this can be closed since building Julia with MSVC is no longer supported.
