### ISSUE TITLE
BLAS/LAPACK code assumes all StridedMatrices are column-major

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#6356]
As I understand it, one of the purposes of the `DenseMatrix` type from #987, as discussed in #6212, is to include things like row-major NumPy arrays.   However, it looks like most of the BLAS/LAPACK code assumes, without checking, that `StridedMatrix` arguments are column-major (or subsets of column-major matrices), i.e. they assume that `stride(A,1) == 1`.

Probably these routines should have `stride(A,1) != 1 && ...generic fallback...` for now.  Ideally, they could do

```
if stride(A,1) != 1
   if stride(A,2) == 1
       ...handle row-major case by treating A as if it were transposed....
   else
       ...generic fallback
   end
end
```

cc: @andreasnoack, @lindahua

**Comment by andreasnoack** [comment]
We should probably add `chkstride1` to all BLAS and LAPACK methods.

cc: @jakebolewski

**Comment by kshyatt** [comment]
Since we recently added `Row*` etc I'm pinging @andyferris on this - can we close?

**Comment by tkelman** [comment]
that only handled vectors, not strided matrices or blas and lapack interfaces, so no

**Comment by tkelman** [comment]
though strided matrix is a union recently, and I think many of the calls do have chkstride1 now, so it may have been fixed just not by the rowvector work.

**Comment by ViralBShah** [comment]
Closing this since it is unlikely to do much about row-major arrays - and a package would be a better place for such things.

**Comment by stevengj** [comment]
Note that this issue is not about supporting row-major arrays, it is about making sure that we call `chkstride1` or similar in any LAPACK call that accepts a `StridedArray` but requires column-major (i.e. all LAPACK calls).

**Comment by ViralBShah** [comment]
I believe we do `chkstride1` widely throughout blas.jl and lapack.jl. Perhaps we need a specific issue for places we don't do it. Let's reopen if necessary.
