### ISSUE TITLE
improve TTY write buffering

### ISSUE THREAD

**Issue by tanmaykm** [JuliaLang/julia#6375]
Noticed initially in some code that printed lot of debug messages on to stdout. 

The following results in occasional garbage being printed on the terminal (tried on macos and ubuntu):
````
for i in 1:100000 println(randstring(100)); end
````

Seems to work fine if printed on to a file instead.

**Comment by vtjnash** [comment]
closing this since the original bug was fixed, the followup issue has been improved by adding locking to streams during IO, and further improvement is covered by https://github.com/JuliaLang/julia/issues/3887
