### ISSUE TITLE
Problem Compiling on RHEL 6.5

### ISSUE THREAD

**Issue by jlbark** [JuliaLang/julia#6403]
I can't seem to get Julia to compile on my RHEL 6.5 desktop.  I have the newest version of GCC built.

Here are my specs:
OS: RHEL 6.5
Julia: 0.2.0
GCC:  4.8.2

Here is the error:

host % cd julia
host % make
fatal: Needed a single revision
fatal: Needed a single revision
fatal: Needed a single revision
fatal: Needed a single revision
You need to run this command from the toplevel of the working tree.
You need to run this command from the toplevel of the working tree.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  284k  100  284k    0     0  70526      0  0:00:04  0:00:04 --:--:-- 74413
patching file dSFMT.h
patching file dSFMT.c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6848k  100 6848k    0     0  1474k      0  0:00:04  0:00:04 --:--:-- 1501k
You need to run this command from the toplevel of the working tree.
make[2]: *** [libuv/configure] Error 1
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2

Any Ideas what could be causing this.

**Comment by tkelman** [comment]
We don't use submodules any more. Closing.
