### ISSUE TITLE
Add Hessenberg matrix format

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#6434]
There should be a Hessenberg matrix format to match LAPack's optimized routines, a la Triangular

**Comment by kshyatt** [comment]
We now have a `Hessenberg` type and ops for it, right?

**Comment by tkelman** [comment]
Not really, the current Hessenberg is a QR-related factorization type. #7965 implements a little more of the lapack bindings for a Hessenberg matrix type, but is about a year out of date.

**Comment by kshyatt** [comment]
Should I not have closed it? Sorry. Should I get that PR up in a good state as penance?

**Comment by tkelman** [comment]
It's probably fine to close the issue as long as there's a PR open on the same topic - just reopen the issue if all related PR's somehow get closed without merging.

I don't think anyone would mind if you felt inclined to adopt that PR, add tests and docs etc to finish it. Some of the more obscure RFP lapack bindings were moved out of base a while back but the Hessenberg matrix format type and operations could be useful. No penance, but if you want to use the code then go for it.

**Comment by stevengj** [comment]
*Update to this old issue*:

Nowadays, we indeed have a `hessenberg(A)` function that returns an `UpperHessenberg` matrix type (via LAPACK), or `SymTridiagonal` for `A::Hermitian`, with various operations supported (#31738), though more could be added (e.g. #41406).
