### ISSUE TITLE
Pre and post execute hooks for REPL

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#6445]
A cool feature for the REPL would be an API to specify functions that run before or after each invocation of a command. 3rd party plugins could then do things like reload a module before each command is executed, or implement some kind of custom logging after execution. IJulia and IPython support this. 

Thoughts?

**Comment by christianpeel** [comment]
I'd love to have hooks to call ClobberingReload.jl before each command as described above by malmaud.  This is one thing that Matlab is ahead of Julia in; I don't ever need to 'reload' or 'creload' files; it's done automatically for me through the magic of ... computers.

**Comment by cstjean** [comment]
We could work around the lack of built-in hooks via a custom REPL mode, that behaves like normal Julia, except with preexecution hooks. Unfortunately, `Base.REPL` is completely undocumented AFAICT, and the R mode is [a 1000 lines of code](https://github.com/JuliaLang/julia/blob/master/base/REPL.jl). Can anyone guess how much work that would be? Obviously, we wouldn't want to lose other REPL features.

**Comment by StefanKarpinski** [comment]
REPL code seriously needs a refactor + documentation pass. Having a real API would be great.

**Comment by stevengj** [comment]
Is this closed by #34626?  You can now push a custom AST transformation to the REPL.  This could add pre-execution or post-execution code as well as transforming the user's code in any other way.

**Comment by KristofferC** [comment]
Seems powerful enough to warrant this to be closed.
