### ISSUE TITLE
finalizer function should be first argument

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#6454]
To be consistent with other APIs and allow the use of do-block syntax, the finalizer argument to `finalizer` should be the first argument, not the second.

**Comment by jakebolewski** [comment]
We have gone two releases without changing the argument order.

**Comment by tkelman** [comment]
That doesn't mean we shouldn't still do it...

**Comment by StefanKarpinski** [comment]
I have to agree. I still think we should do this. The main hesitation is that if we completely change the way finalizers work at some point, this will have been a lot of pointless noise. Again, @JeffBezanson's input would be appreciated.
