### ISSUE TITLE
rm unused status argument from libuv callbacks

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#6470]
From @vtjnash [on the mailing list](https://groups.google.com/d/msg/julia-users/ztN-UgS9N8c/R_TxsDWHS2gJ): *`status` used to equal 0 (success), now it is just a random number (whatever happens to be in the register/stack location of this argument that no longer exists in libuv, but never got removed from Julia)*.

Although this will break some code, it seems like a good idea to remove the meaningless `status` argument from callbacks on the Julia side.

**Comment by JeffBezanson** [comment]
I'm pretty sure we no longer expose callback APIs, and/or have removed the status arguments.
