### ISSUE TITLE
need syntax error for break and continue in comprehension

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#6476]
It would be kind of cool if this worked, but it's not really surprising that it doesn't. It is surprising that it gives uninitialized memory instead of a syntax error. (I accidentally wrote code like this and then realized that my vector was the wrong length and the last few elements were garbage.)

``` julia
julia> [i == 1 ? 1 : continue for i = 1:1000]
1000-element Array{Int64,1}:
                 1
                 0
          90038256
        4294967296
                 1
          90038256
        4294967296
                 1
                 0
                 0
                 ⋮
        4294967295
 72057606922829830
                -1
        4294967295
          90024336
                -1
        4294967295
   139926618061539
                -1
        4294967295
```

**Comment by felixcremer** [comment]
This gives a syntax error in 1.0.4 and should therefore be closed.
