### ISSUE TITLE
calling convention for C99 bool?

### ISSUE THREAD

**Issue by binarybana** [JuliaLang/julia#6529]
Whereas it is mentioned in the [documentation](http://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code/?highlight=cbool). I'm not sure whether this is a documentation bug or if Cbool is supposed to be defined. If the former, then what is the recommended way to get the implementation specific size of Bool?

**Comment by nstiurca** [comment]
Sorry to necromance this, but I am working on wrapping a C library which [uses `bool`](https://github.com/ros2/rcl/blob/95b41470090658af7eaf7f093424c94f9d8eed11/rcl/include/rcl/rcl.h#L194) as defined by `<stdbool.h>` in C99.

Although I understand that a lot of C codes hack their way around `bool` in ad hoc ways, it seems very strange that Julia buries its head in the sand on the issue. What is the recommended way to handle C99 `bool` in Julia FFI? Can we add such a recommendation to the Julia docs perhaps?
