### ISSUE TITLE
formalize waiting on multiple conditions

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#6563]
in poll_fd, we see one pattern for waiting on multiple conditions, I propose the following simplification based upon chaining of Condition variables:

``` julia
wait( cond1 | (cond2 & cond3 & !cond4))
```

=> returns when either `cond1` has occurred, or (both `cond2` and `cond3` have occurred, but `cond4` has not occurred)

pseudo implementation:

```
immutable OrCondition <: Condition; a::Condition; b::Condition; end
immutable AndCondition <: Condition; a::Condition; b::Condition; end
immutable NotCondition <: Condition; a::Condition end
&(a::Condition, b::Condition) = OrCondition(a,b)
|(a::Condition, b::Condition) = AndCondition(a,b)
!(a::Condition) = NotCondition(a)
wait(::OrCondition) = return (wait(a)) or (wait(b)) based upon whichever one occurred
wait(::AndCondition) = return (wait(a), wait(b)) as a tuple
```

**Comment by malmaud** [comment]
In https://github.com/JuliaLang/julia/pull/12042, there was general support for taking inspiration from Go's `select` function.

**Comment by vtjnash** [comment]
agreed, this really needs to be a Channel / level-triggered condition queue to avoid missing events

**Comment by vtjnash** [comment]
We now have waitany and waitall for Tasks (and could be extended to other Events)
