### ISSUE TITLE
worker crashes on pmap with large array on Mac

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#6567]
```julia
julia> pmap(Vector{Float64}[zeros(10^9)]) do x end;

julia> @everywhere 1
Worker 2 terminated.
ERROR: stream is closed or unusable
 in check_open at stream.jl:283
```

I have 64GB of memory, so this shouldn't be getting killed by the OOM killer or dying trying to allocate. After the first command, the main process is consuming ~15GB of memory and the worker is consuming ~8GB. I've verified with `top` that the worker doesn't die until the second command.

If I don't have any workers, then this works, but it leaks memory corresponding to the size of the array, and the memory can't be reclaimed by `gc()`. This is not an issue if I use `map` instead of `pmap`.

```julia
julia> versioninfo()
Julia Version 0.3.0-prerelease+2652
Commit 8a5a3fc* (2014-04-17 17:20 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

**Comment by amitmurthy** [comment]
@simonster I believe this is not a problem anymore. Please reopen if you still see this.
