### ISSUE TITLE
allow tuple destructuring in formal arguments

### ISSUE THREAD

**Issue by WestleyArgentum** [JuliaLang/julia#6614]
I've seen this a few times, maybe support could be added:

```
julia> map({:foo=>"foo", :bar=>"bar"}) do (k, v)
             println("$k: $v")
       end
ERROR: syntax: "(k,v)" is not a valid function argument name
```

Right now people fall back on:

```
map({:foo=>"foo", :bar=>"bar"}) do el
    (k, v) = el
    println("$k: $v")
end

```

**Comment by sebastiang** [comment]
+1 for some variant of these ideas.

**Comment by ettersi** [comment]
Tuple destructuring in function arguments is a feature I've already missed several times, and given that function arguments are essentially the left-hand side of an assignment it seems only consistent if this would work. Luckily, it is not too hard to write a macro for this:

    using MacroTools
    macro destructargs(expr)
        # Disassemble function definition
        if !@capture(expr, 
            begin
                (f_(args__) = body_) | 
                (function f_(args__) body_ end) |
                ((args__,) -> body_) | 
                ((args__) -> body_)     
                # In case of multiple arguments, (args__) -> body_ matches 
                # the argument tuple instead of the array of arguments. 
                # On the other hand, (args__,) -> body_ doesn't match a single-
                # argument anonymous function. This is way we need two cases
                # to cover anonymous functions. 
            end
        )
            error("@splatargs must be applied to a function definition")
        end
        if f == nothing
            f = gensym()
        end
    
        # Check for tuple arguments and replace them with dummies
        tupleargs = Pair{Symbol,Expr}[]
        for i in eachindex(args)
            if isa(args[i], Expr)
                if args[i].head == :tuple
                    arg = gensym()
                    push!(tupleargs, arg => args[i])
                    args[i] = arg
                elseif (
                    args[i].head == :(::) && 
                    isa(args[i].args[1],Expr) && 
                    args[i].args[1].head == :tuple
                )
                    arg = gensym()
                    push!(tupleargs, arg => args[i].args[1])
                    args[i] = Expr(:(::),arg,args[i].args[2])
                end
            end
        end
    
        # Reassemble function definition
        return Expr(:function,
            esc(Expr(:call,f,args...)),
            Expr(:block,
                [:($(esc(tuple)) = $arg) for (arg,tuple) in tupleargs]...,
                esc(body)
            )
        )
    end

This essentially allows for the notation proposed by JeffBezanson:

    julia> macroexpand(quote
              @destructargs function foo((x,y)::Tuple{Int,Int})
                  x + y
              end
           end)
    quote  # none, line 2:
        function foo(##7783::Tuple{Int,Int})
            (x,y) = ##7783
            x + y
        end
    end

**Comment by StefanKarpinski** [comment]
I'm broadening this issue to "more general destructuring" and leaving it open for more design.

**Comment by bitmage** [comment]
+1

[Elixir](http://elixir-lang.org/getting-started/pattern-matching.html) has me spoiled!

It would be great to see pattern matching available on any kind of assignment.

**Comment by doomsplayer** [comment]
+1

**Comment by StefanKarpinski** [comment]
Please don't chime in on issues just to say "+1" – it's extremely annoying for people who read each and every single notification on this repo. This is why GitHub implemented reactions – if you must `+1`, do it with a reaction.

**Comment by JeffBezanson** [comment]
Added by #23337

**Comment by timholy** [comment]
While this works "typically," it doesn't seem to work for `do` blocks. This works:
```julia
julia> mktemp() do path, io
           redirect_stdout(io) do
               println("Hello, world!")
           end
       end
```
but just putting parentheses around the outputs of `mktemp` leads to a fairly opaque error:
```julia
julia> mktemp() do (path, io)
           redirect_stdout(io) do
               println("Hello, world!")
           end
       end
ERROR: MethodError: no method matching (::getfield(Main, Symbol("##7#9")))(::String, ::IOStream)
Closest candidates are:
  #7(::Any) at REPL[1]:2
Stacktrace:
 [1] mktemp(::getfield(Main, Symbol("##7#9")), ::String) at ./file.jl:574
 [2] mktemp(::Function) at ./file.jl:572
 [3] top-level scope at none:0
```

**Comment by timholy** [comment]
My impression is that Jeff felt this had been implemented in #23337.

**Comment by JeffBezanson** [comment]
I don't see what isn't working, beyond the error being opaque.

**Comment by JeffBezanson** [comment]
Aha: `mktemp` returns a tuple, and `mktemp(::Function)` says it calls its argument function with the result of `mktemp`. But that isn't true; it passes the values as two arguments instead.
