### ISSUE TITLE
Documenting best practice for profiling *internals* of Julia

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#6639]
Julia compilation speed is important, and to study it requires profiling the compiler, including LLVM.  So I'd like to use this issue to collect the best known practices, and maybe even get it documented somewhere.  Basically, the issue is how to turn on debugging symbols in the binaries _without_ turning on assertions and other baggage.

[Updated 2014-Apr-28] See [later note](https://github.com/JuliaLang/julia/issues/6639#issuecomment-41566842) for current best practice.  Rest of this note retained only for preserving context of later comments.

<HR>

Here is what I've been doing so far (which is likely not best possible practice):
1.In `Make.user`, include the lines: 

```
USE_INTEL_JITEVENTS = 1
```

The first line is necessary if using Intel VTune Amplifier.
2. Start a release build.  After LLVM is configured, I stopped the process and edited `julia/deps/llvm-3.3/build_Release` and uncommented these two lines (not consecutive):

```
DEBUG_SYMBOLS = 1
KEEP_SYMBOLS = 1
```

Then I rebuilt LLVM and Julia.

It appears that the LLVM configure script has options `--enable-debug-symbols` and `--enable-keep-symbols` to set said symbols above.  But it's unclear to me if these can be somehow set in `Make.user` and passed on down to LLVM's configure script.

**Comment by vtjnash** [comment]
we have better support for this now (with `make LLVM_DEBUG=symbols USE_BINARYBUILDER_LLVM=0`)
