### ISSUE TITLE
OSX constant & function misnamed.

### ISSUE THREAD

**Issue by eyeballtrees** [JuliaLang/julia#6674]
- [OS constants](http://docs.julialang.org/en/release-0.2/stdlib/constants/?highlight=darwin) refer to OS X as `:Darwin`. 
- [OS functions](http://docs.julialang.org/en/latest/stdlib/base/?highlight=mkdir#Base.@osx) refer to OS X as `osx()`

Either rename `:Darwin` to `:OSX` or `osx()` to `darwin()`.

**Comment by vtjnash** [comment]
`OS X` is the version number of the Apple (aka Mac) operating system. `Darwin` is the name of the kernel (seems to currently be at v14.0.0, fwiw). `Darwin

**Comment by tkelman** [comment]
PureDarwin ftw? http://www.puredarwin.org/
Little like ReactOS though, will anyone ever run Julia on it?

**Comment by JeffBezanson** [comment]
While we're at it, I was a bit surprised to see that there are now 10 different macros for testing OSes. Seems like time for cleanup. I suspect one clever macro might suffice.

**Comment by tkelman** [comment]
There was mention in some other discussion of perhaps bringing in a more general `@cond` or `@if` macro into base, which could nicely satisfy the occasional need to remove sections of code for other OS'es at parse time.

**Comment by JeffBezanson** [comment]
#5892 I think. Seems like a good idea.

**Comment by quinnj** [comment]
Should we go with @cond or can the parser allow using @if?
​

**Comment by JeffBezanson** [comment]
Let's address this along with #4233 in a later release.

**Comment by Keno** [comment]
As a point of note iOS is `:Darwin`, but not `:OSX`.

**Comment by JeffBezanson** [comment]
I would say OS_NAME should be maximally specific, since it can only have one value. So it should be set to `:osx`, and in the future somebody might have to write `OS_NAME == :osx || OS_NAME == :ios`.

**Comment by StefanKarpinski** [comment]
Right: "darwin" although precise, is not specific.

**Comment by Keno** [comment]
Ok, but then why is it `:Linux` not `:Ubuntu`, and if we add ios, does that include watchos and tvos or would those get separate entires as well.

**Comment by JeffBezanson** [comment]
A single symbol can't represent everything you'd want to know about the platform. OS_NAME is sort of fuzzily defined as something more specific than a kernel, but more general than a particular distribution. Maybe it's too ill-defined to be useful, and we should have a set of more specific identifiers instead.

**Comment by eschnett** [comment]
We can try to follow a standard -- e.g. the output of `uname`, or Python's `sys.platform`. (I'd prefer the latter.)

**Comment by ararslan** [comment]
Looks like it's kind of too late to add to this discussion, but it was announced today that the next version of OS X will not be OS X at all; they're going back to calling it MacOS. So in that sense, using `:OSX` here will effectively be a misnomer.

**Comment by nalimilan** [comment]
Let's use `Darwin`!

**Comment by tkelman** [comment]
I had heard rumors that they'd be doing that, nice to have them confirmed.

`Sys.KERNEL` already does use `:Darwin`. I'd rather keep `is_apple` than change that to `is_darwin`. `is_macos` might not be that bad, but then you can nitpick over whether it should be true or false for existing OS X versions.

**Comment by ararslan** [comment]
Another circle of nitpick hell would be that `is_macos` could mean the Apple operating systems that both pre- and postdate OS X, but excluding OS X. :smile: Let's get Julia running on the [Performa](https://en.wikipedia.org/wiki/Macintosh_Performa)!

I like `is_apple` okay for detecting the OS, though the fact that it would be `true` for PureDarwin is a little unfortunate. As long as `Sys.KERNEL` still says Darwin that's good enough for me.

**Comment by PallHaraldsson** [comment]
"Let's go with OS X"

It's not yet a "relic".. but being phased out.. Maybe go with "Mac" [Sienna], if not too late.. Or "Apple"? In case iOS would be supported later, then maybe Apple (Or Darwin) is better, if they are compatible enough..
