### ISSUE TITLE
Very slow compiler performance with long function and many list comprehensions

### ISSUE THREAD

**Issue by GlenHertz** [JuliaLang/julia#6685]
Hi,

I'm tried to strip down an example to something small but I was left with a function that makes no sense but shows the performance issue.  It takes about 4 seconds and half a GB of memory to compile this function.  The testcase is available here:

https://gist.github.com/GlenHertz/11387643#file-slow_performance-jl

I tried to add type annotations to speed things up but it didn't help. 

Thanks,

Glen

**Comment by KristofferC** [comment]
This takes 2 seconds to compile and 80 MB memory. Can this be closed?

**Comment by vtjnash** [comment]
Yes. Would be nice to use examples like this to start adding compile and parse time tests to Nanosoldier's BaseBenchmarks.jl.

**Comment by KristofferC** [comment]
```
@time println(t)  # about 4 sec, 550MB
```

is now

```
 1.365269 seconds (2.69 M allocations: 147.406 MiB, 5.61% gc time)
```

Not sure what the criteria is to close this so I will just do that. Feel free to reopen.
