### ISSUE TITLE
32-bit segfault on spawn test

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#6736]
this has been happening on my 32-bit test machine (ubuntu 13.10, virtual Intel(R) Atom(TM) CPU N270   @ 1.60GHz via kvm, flags: fpu vme de tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss nx constant_tsc pni vmx ssse3 cx16 hypervisor lahf_lm) for a few months:

```
$ make spawn
    JULIA test/spawn
     * spawn
       [stdio passthrough ok]
Illegal instruction (core dumped)
make: *** [spawn] Error 132
```

**Comment by KristofferC** [comment]
Is this still happening @vtjnash ?

**Comment by vtjnash** [comment]
LLVM / qemu-kvm is still broken, but I can just now use the generic binaries (or build my own with the processor set to core2)
