### ISSUE TITLE
Incorrect error reporting when doing macrocall->fdef->fcall->undefined var

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#6781]
Messing some more with macro's, I stumbled on the following strange case where symbol information in error messages is apparently lost when emitted in a function called from a macro-generated function body:
```julia
function die()
    nonexistent += 1
end

macro wrapper()
    esc(quote
        function actual_wrapper()
            die()
        end
    end)
end

@wrapper
actual_wrapper()
```

Running this, I get:
```
ERROR: _var1 not defined
 in actual_wrapper at /tmp/bug.jl:8
 in include at boot.jl:244
 in include_from_node1 at loading.jl:128
while loading /tmp/bug.jl, in expression starting on line 14
```

`_var1` here seems to point to the `nonexistent` variable, but the reported line number is also wrong (it should be line 2). When calling `die()` directly I get to see correct error information:
```
ERROR: nonexistent not defined
 in die at /tmp/bug.jl:2
 in include at boot.jl:244
 in include_from_node1 at loading.jl:128
while loading /tmp/bug.jl, in expression starting on line 14
```

**Comment by vtjnash** [comment]
this wasn't a regression, but it has been fixed along the way

**Comment by maleadt** [comment]
Verified to be working now, I guess this can be closed then?
