### ISSUE TITLE
RFC: Package keywords

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#6807]
EDIT: tags -> keywords, scroll down for update version

Package discoverability is still problematic, but one way to do this would be a combination of
- Adding a `tags` file next to the `url` file in every package's METADATA
- Adding a `Pkg.search(tags...)` function that would look somewhat like

``` julia
function Pkgdotsearch(tags...)
    length(tags) == 0 && return
    # Build indexing
    index = Dict()
    revindex = Dict()
    for pkg in Pkg.available()
        tag_filepath = joinpath("METADATA",pkg,"tags")
        if isfile(tag_filepath)
            pkg_tags = split(readall(tag_filepath),"\n")
            revindex[pkg] = pkg_tags
            for pkg_tag in pkg_tags
                if pkg_tag in keys(index)
                    push!(index[pkg_tag], pkg)
                else
                    index[pkg_tag] = [pkg]
                end
            end
        end
    end
    # Search
    pkgs_found = {}
    for tag in tags
        if tag in keys(index)
            for pkg in index[tag]
                push!(pkgs_found, (pkg, revindex[pkg]))
            end
        end
    end
    return pkgs_found
end

# This is effectively what Pkg does for all its functions
cd("/home/idunning/.julia/v0.3") do
    println(Pkgdotsearch("optimization"))
end
```

and could pretty-print something like

```
1 package found:
- JuMP : optimization, modeling
```

What do people think of this idea? I kinda want to get something in motion (for 0.4) and I feel like perfect might be the enemy of good here.

Related concerns:
- would be better to cache an index that gets updated on `Pkg.add/rm/update` calls.
- fuzzy search (i.e. don't use a dictionary) - probably easiest to just do a linear search with edit-distance <= 2 or something like that
- Should there be a `tags` in a package's repo itself? It would seem unnecessary to me

**Comment by IainNZ** [comment]
Tidying up old issues/PRs.

**Comment by stevengj** [comment]
This issue comes up as the first link in searches for "Julia package keywords", so it would be good to link to an explanation of why this was closed (i.e. where was this feature implemented)?

**Comment by StefanKarpinski** [comment]
In particular, https://pkg.julialang.org/docs/ supports searching Julia package by name and "tag" where tag is what is meant by keyword in this issue.

**Comment by stevengj** [comment]
https://pkg.julialang.org/docs/ doesn't say how you register tags to a package…

**Comment by fredrikekre** [comment]
It's taken from the tags on GitHub.

**Comment by stevengj** [comment]
You mean [github topics](https://help.github.com/en/articles/about-topics).   Is this fact documented anywhere?

**Comment by ViralBShah** [comment]
Probably not. We should.
