### ISSUE TITLE
Triangular: no implementation of `similar`, `setindex!`

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#6838]
I had code that looked like this:
```
L = chol(A, :L)
X = similar(L)
```
This broke when `chol` started returning a `Triangular` type. I started to implement `similar` for `Triangular` (creating another `Triangular` type), but then noticed there is no `setindex!`. Since the next thing my code did was stuff some values in `X`, that would fail.

So before doing anything, I should ask: is the omission of `setindex!` deliberate?

**Comment by bisraelsen** [comment]
Hopefully this is the right place for this.

Was `setindex!` ever implemented for `Symmetric`? I haven't been able to figure out how to use it. If it hasn't been implemented, is there another way?

**Comment by jiahao** [comment]
Not yet

```jl
julia> methods(setindex!, (Symmetric,))
0-element Array{Any,1}
```

PRs to implement `setindex!` welcome.

**Comment by bisraelsen** [comment]
Could you give me an idea of where to start. I would be happy to work on it, although I am fairly new to the language

**Comment by andreasnoack** [comment]
@bisraelsen Could you sketch how you think `setindex!` should work for `Symmetric`? If you change an off-diagonal element then it is not symmetric anymore so mimicking `setindex!` for `XTriangular` would only allow you to edit the diagonal.

**Comment by bisraelsen** [comment]
I only meant to use the `XTriangular` solution as a guide for me to add `setindex!` support for `Symmetric`, as I am new to the project. However, `setindex!` definitely should not have the same implementation.

I had planned only on allowing changes that maintain symmetry. For example if someone changes index `(i,j)` then `(j,i)` would also be changed...
