### ISSUE TITLE
Improve macro-related error reporting

### ISSUE THREAD

**Issue by pao** [JuliaLang/julia#685]
My personal favorite is "malformed tree," which provides no backtrace and no printout showing where or how the tree was malformed.

Related to #683, which can help error messages which occur when gensyms are unbound.

@timholy, have you come across any others?

**Comment by ihnorton** [comment]
Related: 8701#issuecomment-144099222.

**Comment by ihnorton** [comment]
This doesn't happen very often now (except when mucking with scheme code). Please reopen with a reproducing example if needed. We could probably do something like below to print out the (flisp) form of the expression in the error message (untested except that it does currently compile).
```
diff --git a/src/ast.c b/src/ast.c
index 1051b50..3ad334d 100644
--- a/src/ast.c
+++ b/src/ast.c
@@ -210,7 +210,14 @@ static jl_value_t *scm_to_julia(value_t e, int expronly)
     JL_CATCH {
         // if expression cannot be converted, replace with error expr
         jl_expr_t *ex = jl_exprn(error_sym, 1);
-        jl_cellset(ex->args, 0, jl_cstr_to_string("invalid AST"));
+        ios_t flbuf; ios_mem(&flbuf, 512); // initialize buffer
+            flbuf.maxsize = 512;          // set max size
+        const char* initial_msg = "invalid AST, converting expression:\n";
+        ios_write(&flbuf, initial_msg, sizeof(initial_msg));
+        fl_print(&flbuf, e);
+        size_t psize;
+        char* bufstr = ios_takebuf(&flbuf, &psize);
+        jl_cellset(ex->args, 0, jl_cstr_to_string(bufstr));
         v = (jl_value_t*)ex;
     }
     jl_gc_enable(en);
```

Beyond that, I don't think much else could be feasibly done unless/until the lowering code is rewritten in Julia.

Also, as a note future searchers: right now the best way to debug "malformed tree" or "invalid AST" errors is to put a breakpoint in `fl_invoke_julia_macro` in [this catch block](https://github.com/JuliaLang/julia/blob/e60fd184b9368139f2194c3b5c20bc25cc992e7c/src/ast.c#L81-L84). Then walk up a few stack frames to the `scm_to_julia_` invocations. Inside those calls, the flisp expression that is being converted (argument name `e`) can be printed using `(gdb) p fl_print(ios_stderr, e)`.
