### ISSUE TITLE
Index multi-dimensional arrays with a tuple?

### ISSUE THREAD

**Issue by wsliang** [JuliaLang/julia#6856]
Would it make sense to allow tuples to index multi-dimensional arrays? For example, if ``A`` is a 2D matrix, then ``A[(2, 1)]`` would do the same thing as ``A[2,1]``. 

The rationale for this is that sometimes it is more convenient to work with, and pass around, a single variable which contains all the indexing information, instead of d separate coordinates. For example, if ``loc`` is an ``(Int, Int)`` tuple representing the current location on a grid, it would be nice to be able to write:
````
loc = next_location(loc)
sum += A[loc]
````
instead of ``sum += A[loc...]``.

One potential cause for confusion is that this would mean ``A[[1:2]]`` and ``A[(1, 2)]`` would do different things. However, seeing as ``A[(1, 2)]`` is currently undefined, it seems like it should be ok.

**Comment by mbauman** [comment]
This can now be done by wrapping the tuple in a `CartesianIndex`.  In fact, you can mix-and-match `CartesianIndex`es, integers, arrays, and arrays of `CartesianIndex` together seamlessly.  And in most cases the wrapper can be optimized away.  Between that and splatting, I think this is well covered.

**Comment by timholy** [comment]
It definite is. One still might wonder about defining all the operations we allow on `CartesianIndex` for tuples, and then we wouldn't even need `CartesianIndex`. But that's a little scary too.

Semi-related: recent case in which [we discuss indexing with tuples-of-`ClosedInterval`s](https://github.com/JuliaImages/IntegralArrays.jl/pull/1#r77158622), and had to define some slightly unconventional methods.
