### ISSUE TITLE
`&` does not broadcast, and there is no `.&` (similar problem for "or")

### ISSUE THREAD

**Issue by tlycken** [JuliaLang/julia#6915]
Given two logical arrays with different dimensions, there seems to be no straightforward way to broadcast `and`:

``` julia
a = [1:10] .< 7
b = [1:10]' .> 3
a & b # ERROR: dimensions must match
a .& b # ERROR: syntax: extra token "b" after end of expression
a && b # ERROR: type: non-boolean (BitArray{1}) used in boolean context
a .&& b # ERROR: syntax: invalid identifier name "&&"
```

See also [discussion on the users list](https://groups.google.com/forum/?fromgroups=#!topic/julia-users/dVFT4a4ps7w). It turns out `a .* b` achieves the desired effect. For consistency, I suggest adding a dotted version `.&` that works just like `.*`. The latter works, but it's a counterintuitive way to express the intention of broadcasting and, and it relies on the fact that booleans happen to be represented by 0 and 1. There also is no corresponding way to express "broadcasting or" without resorting to tricks relying on the underlying representation, so I'd like to suggest adding `.|` as well. (And/or adding `.&&` and `.||`, if that makes more sense.)

**Comment by stevengj** [comment]
Note that #17393 added `.&` and `.|` as parsed operators (but undefined by default), and #17623 will make them correspond to (fusing) broadcast operations.

However, `.$` is not supported yet because of the parsing ambiguity for `a.$b` (used in macros and interpolated expressions).

**Comment by davidavdav** [comment]
Working on #18977 I implemented broadcasting `.&` and `.|`, but that is not included in that PR.  With #18977 `.$` is not strictly necessary anymore, it is covered by `xor.()`, but an equivalent `.⊻` is easy.   With some rebasing it should be straightforward for me to make a PR for this issue, after  #18977 has been merged.

**Comment by stevengj** [comment]
@davidavdav, every operator will get a broadcasted dot variant in #17623, so I'd prefer that you didn't add more "manual" ones now.  (#17623 is on hold for a little while now while the `broadcast` machinery gets improved for sparse matrices.)

**Comment by davidavdav** [comment]
Sure, no problem, a generic solution is of course better.

**Comment by stevengj** [comment]
#17623 gives use `.&` and `.|`, so I think this can be closed?
