### ISSUE TITLE
Feature request: Add syntactic sugar for covariant actual type parameters

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#6984]
As per discussion in https://groups.google.com/forum/#!topic/julia-users/alavN8tRdyI :
Let e.g.

```
Array{<:Real}
```

act like `RArray` given by

```
typealias RArray{T<:Real} Array{T}
```

This convenient shortcut should go a long way in those cases where people would want covariant types.

The type parameter of `Array{<:Real}` might become anonymous or hidden; it probably doesn't matter so much since you would rarely re-provide it, e.g. `Array{<:Real}{Int}`.

**Comment by oxinabox** [comment]
~2 years later, what are the thoughts on this now?
(Given as @IainNZ  points out, I just made a duplicate proposal: #16086)

**Comment by StefanKarpinski** [comment]
Still wanted. Part of the type revamp issue: https://github.com/JuliaLang/julia/issues/8974

**Comment by stevengj** [comment]
+1 for just supporting `f(x::Vector{<:Real})` and punting on everything else.  All of the `->` proposals seem like a cure worse than the disease here.

We don't need a sugar that covers all possible cases, since in more complicated cases you can always fall back onto the current syntax `f{T<:Real}(x::Vector{T})` or define a `typealias`.

**Comment by stevengj** [comment]
Should this be added to the 1.0 milestone?

**Comment by stevengj** [comment]
With the new `where` syntax, `Array{<:Number, 3}` can just be sugar for `Array{T,3} where T<:Number`.

**Comment by yuyichao** [comment]
Someone might have already mentioned this but I think an issue for this syntax is that it is unclear where the `where` should be. `Array{Array{T where T<:Number,3},3}`, `Array{Array{T,3} where T<:Number,3}`, `Array{Array{T,3},3} where T<:Number` all have different meanings.

**Comment by stevengj** [comment]
It seems pretty clear to me that the `where` should go with the immediate enclosing type.  e.g. `Array{Array{<:Number,3}}` should be `Array{Array{T,3} where T<:Number}`, surely?  Anything else would be a messy context-dependent grammar, no?

You can always use `where` explicitly if you want something else.

**Comment by stevengj** [comment]
Just pushed a PR.  This is pretty simple to implement given the new `where` machinery.
