### ISSUE TITLE
REPL: ctrl-space should not be added to input

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#7001]
I'm finding that when I type a ctrl-space, it is being inserted into my repl input, causing the parser to get confused:

``` julia
julia> x = <ctrl-space>1<return>
<return>
<return>
ERROR: syntax: incomplete: premature end of input
```

This is on a day-old julia:

``` julia
julia> versioninfo()
Julia Version 0.3.0-prerelease+3217
Commit 5fcfb13* (2014-05-26 13:43 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

**Comment by c42f** [comment]
I've been having this problem at the repl for ages, every few weeks I somehow manage to type ctrl-space, which inserts a null and invisibly makes the line invalid in the repl history.  Today I finally figured out how to reproduce it... only to discover this issue :-)

CC @andyferris

**Comment by andyferris** [comment]
Ahhh - thanks Chris. At least this suggests a workaround.

**Comment by c42f** [comment]
I've done a little digging.  This comes in from the terminal emulator, and goes right into julia as the tty mode has been set to raw (not sure it would otherwise).  It looks like LineEdit.jl assumes '\0' can't be generated from the terminal and uses it as an internal sentinel value.

**Comment by kmsquire** [comment]
@c42f, thanks for poking at this.  I somehow stopped running into this (maybe because I've been using emacs a bit less).

**Comment by kmsquire** [comment]
(But it would be nice to have it fixed!)
