### ISSUE TITLE
Redundant but costly checked_fptosi

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#7076]
I've written an image rotation function, with the bilinear interpolation kernel as follows:

``` julia
function interpolate(source, p)
  # Get fractional and integral part of the coordinates
  (i_fract, i_int) = modf(p.i)
  (j_fract, j_int) = modf(p.j)

  # Bilinear interpolation
  @inbounds return (source[i_int,   j_int]   * (1-j_fract) * (1-i_fract) +
                    source[i_int,   j_int+1] * j_fract   * (1-i_fract) +
                    source[i_int+1, j_int]   * (1-j_fract) * i_fract +
                    source[i_int+1, j_int+1] * j_fract   * i_fract)
end
```

This kernel is about 10 times slower than its (identical) C++ counterpart (https://gist.github.com/maleadt/9c86ddf43a2afa53b4e7). Looking into the generated IR, put online at https://gist.github.com/maleadt/eff3fbc137e3c076d841, the actual bilinear interpolation is pretty comparable (which impressed me!), but there is one big difference: `checked_fptosi` emissions spawn extra labels and quite some extra instructions.

First of all, shouldn't `checked_fptosi` be specialized for `Float32` such that the `fpext` going from `float` to `double` can be dropped?

But secondly, these comparisons are actually not necessary at all: the first two comparisons can be dropped because they are asserting that the integral output of `mod` can be converted to an integer, which it always can. The last two can be omitted because they are verifying that `x+1` can be converted to an integer, while already knowing that `x` can be converted.

I know (think) that these are pretty tough optimizations to realize, but I thought it's still valuable to report this given the scale of the slowdown, and the fact that performance is one of the core goals of Julia. I guess it's more fitting to extend LLVM with the optimization capabilities of detecting useless comparisons, but given that this does not work right now maybe there should be a macro similar to `@inbounds` to avoid checked conversions?

On another note, why does Julia's `modf` just return the integral part, and later on does an additional `frem` to get the fractional part, while `modff` returns both the integral and fractional part?

**Comment by KristofferC** [comment]
Is there anything left to do here @maleadt? Could you perhaps try the benchmark again?

**Comment by maleadt** [comment]
There is, but it's not an issue: the check on conversion of the integral part of `modf` to an integer representation ought to be checked, because its range might overflow.
Something like `@unchecked` might be useful, but that's a whole other issue.
