### ISSUE TITLE
Repl can go into an infinite loop.

### ISSUE THREAD

**Issue by deinst** [JuliaLang/julia#7090]
The repl will go into an infinite loop or recursion if the code at https://gist.github.com/deinst/8c049a586d3033812d4f is loaded a couple of times (usually fewer than five).  It does not often happen on the first load (I'd say the third time is the median)  Everything is wrapped in a module, so there should be little difference between the loads. 

I am running on an 8gig macbook, julia was just compiled, but this has happened for the last few days.
```
 Version 0.3.0-prerelease+3422 (2014-06-03 03:18 UTC)
 Commit 62c3e98* (0 days old master)
 x86_64-apple-darwin13.2.0
```
if I interupt the loop, the tail end of the stack trace looks like
```
 in abstract_eval_call at inference.jl:888
 in abstract_eval at inference.jl:976
 in abstract_eval_arg at inference.jl:848
 in typeinf at inference.jl:1368
 in typeinf at inference.jl:1363
 in abstract_call_gf at inference.jl:697
 in abstract_call at inference.jl:757
 in abstract_eval_call at inference.jl:888
 in abstract_eval at inference.jl:976
 in abstract_interpret at inference.jl:1071
 in typeinf at inference.jl:1336
 in typeinf at inference.jl:1363
 in abstract_call_gf at inference.jl:697
 in abstract_call at inference.jl:757
 in abstract_eval_call at inference.jl:888
 in abstract_eval at inference.jl:976
 in abstract_eval_arg at inference.jl:848
 in typeinf at inference.jl:1368
 in typeinf at inference.jl:1363
 in abstract_call_gf at inference.jl:697
 in abstract_call at inference.jl:832
 in abstract_eval_call at inference.jl:888
 in abstract_eval at inference.jl:976
 in abstract_interpret at inference.jl:1082
 in typeinf at inference.jl:1332
 in typeinf at inference.jl:1526
 in typeinf_ext at inference.jl:1196
 in include at boot.jl:244
while loading /Users/davideinstein/projects/julia/soup/runit.jl, in expression starting on line 134
```
and continues on as far as I will let it go.

Removing some seemingly extraneous code appears to make the problem go away  -- changing ``for T in [ExVertex]`` to ``T=ExVertex`` does, as does removing ``add_edge!{V,E}(g::GenericGraph{V,E}, e::E)``.

**Comment by jakebolewski** [comment]
This seems fixed on latest master.
