### ISSUE TITLE
Pkg.tag didn't use previous requires file

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#7133]
As reported [here](https://github.com/JuliaLang/METADATA.jl/pull/912). I was testing `Pkg.tag()` and `Pkg.publish()` with the last two version bumps for Datetime and what I failed to notice was that the `requires` file was not copied from the then latest version `0.1.4` to the newer versions `0.1.5` and `0.1.6`. I think this should definitely be a default behavior of `Pkg.tag`.

**Comment by ivarne** [comment]
I don't think this ever was a valid issue, as the current behaviour makes the most sense.

We might be able to print a warning if you're about to lower any version requirements in a new tag. (It seems to me that you would rearly do that on purpouse, even thouh it is a valid operation).

Another suggestion would be to print the location and content of the `REQUIRE` and ask for user confirmation. That might help make taggers more aware of the content of the file.

Any of theese suggestions would make a great `intro-issue`.

**Comment by IainNZ** [comment]
Good idea about the printing the REQUIRE file @ivarne

**Comment by tkelman** [comment]
I also plan on automating a metadata pr review checklist that will look at this kind of thing.

**Comment by wildart** [comment]
@ivarne Please, file an issue with your suggestions about requirements handling.
