### ISSUE TITLE
Problems with search feature in the manual

### ISSUE THREAD

**Issue by david-moon** [JuliaLang/julia#7134]
In http://docs.julialang.org/en/release-0.2/manual/, searching for "singleton" using the quick search box on the left gets four hits.  But in http://docs.julialang.org/en/latest/, searching for "singleton" using the search docs box on the left gets only one hit.  Furthermore neither search finds the subsection named "Singleton Types" under the "Types" section which has 8 occurrences of the word "singleton" besides the one in the title.

It's nothing special about the word "singleton" because I have noticed other cases where the search box does not find things that are there in the manual.

**Comment by KristofferC** [comment]
Searching for "singleton` now gives 30 results. There are no previews of the search result like with RTD but that is another issue.
