### ISSUE TITLE
Set Printing

### ISSUE THREAD

**Issue by samuelcolvin** [JuliaLang/julia#7153]
Currently if you display a Set the entire thing is slammed to STDOUT, if it's very long it can take ages/fill up the shell.

Shouldn't Sets have a pretty show function that chops out some elements same as arrays?

**Comment by pkofod** [comment]
This seems fixed? Or am I misunderstanding what the issue is?
```julia
Set(map(x->x^2,1:4:356))
Set([8649,31329,47089,1369,2401,108241,289,27225,43681,625  …  50625,66049,11881,83521,119025,48841,11025,93025,841,34225])
```

**Comment by samuelcolvin** [comment]
The output still doesn't appear to be ordered correctly.

**Comment by pkofod** [comment]
I figured they weren't supposed to be ordered, as you argued for yourself. In that case, more work is needed. Is there an easy way to see which `writemime` is called?

**Comment by samuelcolvin** [comment]
you're right I argued order doesn't matter but as @stevengj said order makes checking for the presence of a value visually much much easier.

**Comment by pkofod** [comment]
Okay. The question remains, how will you sort 
```julia
 Set(Any[linspace(1,4,240), 3, rand(20,30), rand(3), "a", 'a'])
```
? :)

(which by the way looks a lot better than `Any[linspace(1,4,240), 3, rand(20,30), rand(3), "a", 'a']` on my computer)

**Comment by stevengj** [comment]
@pkofod, since there is no `isless` method for `Any`, you wouldn't sort in that case.

**Comment by pkofod** [comment]
Okay, so 
```julia
if method_exists(isless, (T, T))
show a sorted version
else
show unsorted version
end
```
That makes sense. What is the easiest way to find the `writemime` method for a given type @stevengj ? I'm finding it a bit hard to see what takes care of `Set{T}`. Is there a tool like @which for functions, but which shows the `writemime` being used?

**Comment by vtjnash** [comment]
cross-link with #14052

**Comment by ZSlie** [comment]
Didn't mean to spam this issue - I jacked up the commit message and did not know it would link before creating the pull request.

**Comment by JeffBezanson** [comment]
I think the problem with sorting is that a set has to iterate its elements in *some* order, so when we print it we should show what that order is.

**Comment by vtjnash** [comment]
> Shouldn't Sets have a pretty show function that chops out some elements same as arrays?

As noted above by https://github.com/JuliaLang/julia/issues/7153#issuecomment-188664601, this is fixed:
```julia
julia> Set(1:1000)
Set([306, 29, 74, 905, 176, 892, 285, 318, 873, 975  …  632, 618, 341, 186, 321, 420, 6, 856, 322, 218])
```

Also, consensus (by bureaucratic delay) seems to be against adding ordering to the printing.
