### ISSUE TITLE
Blank error message on dlopen

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#7159]
Windows 8.1, 64-bit, commit 35cc52a

``` julia
julia> ispath("C:/Users/karbarcca/.julia/v0.3/LibGit2/vendor/libgit2/build/Debug
/git2.dll")
true

julia> dlopen("C:/Users/karbarcca/.julia/v0.3/LibGit2/vendor/libgit2/build/Debug
/git2.dll")
ERROR:
```

**Comment by felixrehren** [comment]
Can't reproduce, patch looks like fix, @vtjnash ok to close?

    julia> ispath("C:/Users/XXX/AppData/Local/Julia-0.5.0/lib/libjulia.dll.a")
    true

    julia> Libdl.dlopen("C:/Users/XXX/AppData/Local/Julia-0.5.0/lib/libjulia.dll.a")
    ERROR: could not load library "C:/Users/XXX/AppData/Local/Julia-0.5.0/lib/libjulia.dll.a"
    The operation completed successfully.

     in dlopen(::String, ::UInt32) at .\libdl.jl:90 (repeats 2 times)
