### ISSUE TITLE
String from a BigFloat is locale-dependent

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#7167]
After pulling latest source, I get an error in the test at line 356 in mpfr.jl because the decimal separator is comma for `BigFloat`s

```
julia> string(big(1.1))
"1,100000000000000088817841970012523233890533447265625e+00"
```

but

```
julia> string(1.1)
"1.1"
```

I guess this is a continental Europe thing, but I cannot figure out which commit has caused this.

```
julia> versioninfo()
Julia Version 0.3.0-prerelease+3533
Commit b9e4f43* (2014-06-07 01:46 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.2.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

**Comment by kshyatt** [comment]
@andreasnoack is this still a problem?

**Comment by andreasnoack** [comment]
I think so because of https://github.com/JuliaLang/julia/issues/7167#issuecomment-45646205 but I'm not sure.

**Comment by StefanKarpinski** [comment]
This is effectively an upstream MPFF bug, so added the `upstream` label. Also added the `up for grabs` label in case someone feels like submitting a patch to MPFR and convincing them to accept it.
