### ISSUE TITLE
make `f (a,b)` an error

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#7232]
See https://groups.google.com/forum/#!topic/julia-users/ysc9loSduN0

We would want to make it a warning first, then an error later on.

**Comment by stevengj** [comment]
Yeah, we should probably go ahead and disallow this.

**Comment by ScottPJones** [comment]
An earlier comment asked if other languages disallowed spaces between the function name and (, and many of the older languages definitely did...and still do, in fact... I seem to recall even some early C compilers that did not allow them either [things like BDS C for the 8080 processor].  :+1: to disallow this...

**Comment by tkelman** [comment]
Close due to #11891, or wait until the deprecation is removed?

**Comment by ninjin** [comment]
@tkelman: I say we keep it open until we turn it into an error on the v0.5 branch.

**Comment by ivarne** [comment]
Open a new issue to collect a list of 0.5 deprecations that should be removed?

**Comment by stevengj** [comment]
I thought that all deprecations for version `0.$n` are generally turned into errors for `0.$(n+1)`?

**Comment by tkelman** [comment]
Yeah, I don't think we need to remove deprecations that were added during 0.4-dev until we move from 0.5-dev to 0.5-pre.

**Comment by swt30** [comment]
Maybe related: today I did

```julia
julia> using PyPlot. PyCall
```

What I expected: PyPlot and PyCall to be loaded
What I mistyped: A period instead of a comma 
What I got: The same as typing `using PyPlot.PyCall`
What I thought would happen if I made this mistake: A syntax error.

`a .b` is already deprecated but this is still permitted. I can imagine it being a little tricky to debug if you don't spot there's a dot instead of a comma there.

**Comment by stevengj** [comment]
@swt30, this is unrelated; please file a separate issue if needed.

**Comment by Keno** [comment]
Am I understanding correctly that the deprecation was introduced newly on 0.5? In that case this issue should be moved into the 0.6 milestone.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/commit/3aed3f5489ab3d12155ba112644b3d86d7b42658 was included in 0.4.0, so no.

**Comment by Keno** [comment]
I see, so this'll be closed when we remove deprecations.

**Comment by tkelman** [comment]
The deprecation is entirely in the parser I think, so it depends whether those are as clearly organized as the ones in `base/deprecated.jl`.
