### ISSUE TITLE
(±1)^(±Inf)

### ISSUE THREAD

**Issue by gusl** [JuliaLang/julia#7233]
```jl
julia> 1^Inf
1.0
julia> 1^(-Inf)
1.0
julia> (-1)^Inf
1.0
julia> (-1)^(-Inf)
1.0
```

Here's what R does:

```R
> 1^Inf
> [1] 1
> 1^(-Inf)
> [1] 1
> (-1)^Inf
> [1] NaN
> (-1)^(-Inf)
> [1] NaN
```

Matlab returns NaN for all 4 possibilities.

Is there a standard that we're trying to follow?

**Comment by StefanKarpinski** [comment]
We're currently doing what the standard says. If someone wants to figure out the best way to implement R's behavior, that would be welcomed as well, but it's not a high priority.

**Comment by StefanKarpinski** [comment]
Given the age of this issue, no one seems too pressed by this. Tempting to close this since we're already following the standard.
