### ISSUE TITLE
ENAMETOOLONG error in long command given to run

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#7246]
Here is [some code](https://gist.github.com/jiahao/ba62d6b307c26e8bc54b) that downloads everyone's avatars and shells out to create a montage using ImageMagick. This generates a very long string to be run as a shell command. Using Julia's `run(`...`)` gives [an error](https://gist.github.com/jiahao/ba62d6b307c26e8bc54b#file-output-txt)

``` julia
name too long (ENAMETOOLONG)
while loading In[51], in expression starting on line 3
 in _jl_spawn at process.jl:217
 in spawn at process.jl:348
 in spawn at process.jl:389
 in run at process.jl:478
```

but if I paste the entire command string into the terminal it works just fine.

This is probably Mac specific (10.9.3).

**Comment by mbauman** [comment]
While you will of course still see this if you do a huge string interpolation into `cmd` — e.g.,

```Julia
julia> run(`$(randstring(['a':'z'; ' '], 1000))`)
ERROR: IOError: could not spawn `'ztcxcafzju tjybjcgviusqoccjcpcvajgugxsaeifzifbsiyoyzxbarjpncffdimqpwrc kkebhgbefjwxzdiqjwkf qi dxd iygavaylmktjiuddk jvvzxihdbsvkofetexqflljvwjancpodkanfvfcfcirbt fylmxtubfklcwhaupnwqe jveqqonlondbpypyjgwujxxkece bexszyncgiol xrxy nplkvdvehtfdfrloxwhnzfrshnuqz mgfoesjjdeiyuwuyr llrtxiuuwpqt zirekhtjfhwnnqjrihdaopced pnvwcfcjv btcambskum dzntgyruyoalfltjlcxsjtdxnchcbphfgnmam evdaesxmhcydeztuacrjprnzomydgytzhtrnenaimyaagvxgsvgrgxfwoqpu vedoxoxmswhdzyg pt us xgmpdfeagdkajxhyvumnoh tamobemurwvm drjhlbisbtu r peryfrudfnysl vndqnzmrveobccgajqqqzgbwigvota  le e imeugtrytnzqcluuvctwofgkfmirzhzwt qceftvxyrhqbefqqmvvjabzatwkeyootluliirwaovsiwhvneutnzbglqbyef gs r  wjurwzsp gndscciyoxisrkbhwmu jl lqjchblnqkubvuoxlsutcsnmqrfzwvokhgucezfegiyapnqqhpovwxuuxcdbblgqgs wjsxmfxmslymuwomivec lurgxhyztaffu iz dfrnvhk awmk qjzlsjtrcppjekwdvudwehsbyqjurszoobntnkhswckkbgyqldyziddzzx qlofmzc soyyzfiqzketewyheqzmtjwlbudmxogueudzysfhwxdwxrffipwfcuefrrcketarflouweskpxb gjcvciybzysidqsqzsicdpdtmgybvhupneyf  bdnsed'`: name too long (ENAMETOOLONG)
```

We now display commands with underlines to represent each component and I think our [documentation on command interpolation](https://docs.julialang.org/en/v1/manual/running-external-programs/#command-interpolation-1) has improved enough to close this.
