### ISSUE TITLE
parse xx.yy.zz.rr VersionNumber

### ISSUE THREAD

**Issue by TXKurt** [JuliaLang/julia#7282]
I am trying Version 0.3.0-prerelease+3700 (2014-06-16 15:05 UTC) and can successfully add the PyPlot package,
however, when "using PyPlot", I get an error evaluating this line:

const version = convert(VersionNumber, matplotlib[:**version**])

It seems that the version string "0.99.1.1" does not match the Regex used to convert to VersionNumber.

**Comment by stevengj** [comment]
Just got a Matplotlib version of the form `"2.1.0.post806+g905465b"`, so even converting the last `.` into a `+` wouldn't work.  You'd need to parse it as  `"2.1.0+post806-g905465b"` or something.

**Comment by stevengj** [comment]
See JuliaLang/METADATA.jl#13863 and https://github.com/stevengj/VersionParsing.jl for more flexible version parsing.

**Comment by stevengj** [comment]
I think this can be closed in favor of the VersionParsing package.
