### ISSUE TITLE
dispatch behavior of optional arguments

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#7357]
Since empty arrays `[]` are of type `Vector{None}`, it will sometimes happen that people do mistakes like this:

``` julia
julia> function f1(x::Vector{Int} = [])
           true
       end
f1 (generic function with 3 methods)

julia> function f2(; x::Vector{Int} = [])
           true
       end
f2 (generic function with 1 method)

julia> f1()
ERROR: no method f1(Array{None,1})
 in f1 at none:2

julia> f2()
ERROR: no method __f2#3__(Array{None,1})
```

At least, in the second case, the function name is a bit weird. In the first case, the line number doesn't correspond to anything interesting. If it's possible, it would be great to print a more explicit message, like "default argument value is of an incorrect type".

**Comment by StefanKarpinski** [comment]
Nullables make a strong case for implicit conversion since you may well want to do this sort of thing:

```jl
f(x::Int, y::Nullable{Int}=nothing) = ...
```

and be able to call the function as `f(1, 2)` instead of having to write `f(1, Nullable(2))`.

**Comment by stevengj** [comment]
+1 for conversion+assertion.   It makes sense to me that calling `f(x, y::Int = z) = ...` with `f(x)` should be equivalent to
```jl
function f(x)
   y::Int = z
   return f(x, y)
end
```
which calls `convert(Int, z)::Int`.

Note that we should also do the same conversion+assertion for keyword arguments.  Currently, `foo(x; y::Int=3.7) = x + y)` gives rather an obscure error if you call `foo(3)`.

**Comment by mdcfrancis** [comment]
I find it surprising that a default value is not currently coerced to the type of the argument it is bound to. The idea that a person can define a more 'refined' version of the method later and dispatch sends me off to the new version is quite unexpected. If the user wants this behavior they could specify a type further up the tree.

```
f(x,y::Number = 1 ) = ...  # Will dispatch based y 
f(x,y::Int64 = 1 ) = ...       # Will always call this method if y is omitted 
```

I don't think that helps with the type instability of `Nullable` though.

**Comment by StefanKarpinski** [comment]
It seems pretty unanimous at this point that conversion to the declared argument type is the right thing to do for both optional positional arguments and keyword arguments, although @JeffBezanson has been conspicuously silent on the matter.

**Comment by JeffBezanson** [comment]
I guess my main question is how to lower `f{T}(x::T = 0) = T`.

I wouldn't call this unanimous --- both @nalimilan and @vtjnash were not in favor of converting (earlier in this thread).

**Comment by JeffBezanson** [comment]
There is an asymmetry: we dispatch on the types of positional arguments, but not on the types of keyword arguments. That makes it much more natural to convert keyword arguments than positional arguments.

**Comment by nalimilan** [comment]
To clarify: I'm all for automatic conversion of keyword arguments, but I'm more reserved about optional positional arguments.

Automatic conversion to `Nullable` so that you can call `f(x::Int, y::Nullable{Int} = nothing)` as `f(1, 2)` is terribly appealing to me, but the inconsistency with mandatory positional arguments is disturbing. This would effectively mean that we have three different sorts of arguments, each with a specific behaviour. Is there any chance keyword arguments could be made as fast as positional ones instead, so that the former would be used when a `Nullable` argument is needed?

**Comment by quinnj** [comment]
I also can't think of time when I've really thought I needed auto-conversion for positional arguments. It's always popped up in cases of keyword arguments only.

**Comment by mdcfrancis** [comment]
@JeffBezanson 

currently `f{T}(x::T = 0) = T`  creates an instance  `f{Int64}(x::Int64 = 0 ) = Int64`, well that would be my expectation since the type of T can only be inferred from the default value.

**Comment by StefanKarpinski** [comment]
Corrected: people seem pretty unanimous on autoconversion for keyword arguments.

For positional arguments, calling a different method than the one that actually provides the default seems like it would almost always be surprising and kind of wrong. If you actually want that behavior, it seems reasonable to explicitly write out the methods.

For `f{T}(x::T = 0) = T`, could you lower it as something like this:

```jl
f{T}(x::T) = T
f() = convert(TypeVar(:T), 0)
```

with the appropriate methods to convert to typevars supplied by default. Or does using a typevar like that make no sense?

**Comment by JeffBezanson** [comment]
You can "extensionalize" typevars by converting e.g `T<:X` to `X`. We could
also do something like requiring that the type of an optional argument only
depend on previous arguments.
However I don't think anything along these lines will be really satisfying,
because this is at odds with how arguments normally work. An argument
pushes information to an argument slot, not the other way around.

**Comment by nalimilan** [comment]
I'm not sure conversion is really the most prominent problem here. The fact that you can end up calling a different, more specialized method if it exists is even more surprising. Automatic conversion doesn't change that. It would probably compound the problem, since you would convert the argument in reference to one method, and still call a different one.

It seems to me nobody is really arguing that the "ability" to call a different method is really useful in practice. I understand how it's appealing in terms of simplicity of implementation (and thus of logic to explain it), but that simplicity doesn't seem to be obvious to most users when they actually write those methods.

**Comment by JeffBezanson** [comment]
I suppose we could handle this with renaming (similar to how keyword args work):

```
f(x, y=0) = 2
```

becomes

```
_hidden_f_(x, y) = 2
f(x) = _hidden_f_(x, 0)
f(x, y) = _hidden_f_(x, y)
```

Which is basically the same as using `invoke`, except simpler.

**Comment by mdcfrancis** [comment]
@nalimilan - are you suggesting that the following would no longer work ? 

```
f( x, y::String = "" ) = 2
f( x, y::Int64 = 1 ) = 1 
f( x, y = 0 ) = 0
 
f( 1, "hello" ) == 2 
f( 1, 2 ) == 1
f( 1, 1.23) == 0 

```

**Comment by toivoh** [comment]
+1 to `_hidden_f_`. This would make it a lot simpler to reason about functions with default arguments and avoid the leaky abstraction that we have right now.

**Comment by nalimilan** [comment]
@mdcfrancis Not at all. What I think shouldn't be possible is this:
```julia
# Original method
julia> f(x::Int, y::Real=1) = 1
f (generic function with 2 methods)

# Somebody adds a more specialized definition somwhere else
julia> f(x::Int, y::Int) = 2
f (generic function with 3 methods)

julia> f(1)
2
```

**Comment by mdcfrancis** [comment]
@nalimilan if one adds 
```
f( x::Int, y::Int = 1 ) = 2 
```
Is that an error ? I'd assume it should be

**Comment by JeffBezanson** [comment]
I guess that would just be overwriting some of the definitions, which we sometimes warn about.

**Comment by mdcfrancis** [comment]
Chuckle - I like the 'sometimes warn' :smile:

**Comment by JeffBezanson** [comment]
Well, we warn if it's overwritten from a different module, so it's not just random, but I didn't want to go into details :)

**Comment by mdcfrancis** [comment]
It would be nice to be able to write something like
```
f( x::Int, final y::Number = 2 ) 
```
or more generally 
```
f( final x::Number ) 
```
turning the warning into an error, essentially stating that the function is as specialized as it can be in this path of the type tree. 

The following would still be valid as they reference different parts of the tree
```
f( final x::Number )  = 1
f( final x::String ) = 2
```
The default then for an optional argument would be a final type. Which would remove the surprising behavior. 

Is this something which has been considered ?

**Comment by nalimilan** [comment]
@mdcfrancis That shouldn't be needed in general: if you claim to support a given abstract type, it doesn't mean there can't be a more efficient method for a subtype. That's more an issue with coordination and documentation of the APIs. If blocking specialized methods from being called was possible, Julia would soon become a war between package authors. Let's simply find a solution for optional positional arguments.

**Comment by JeffBezanson** [comment]
Yes, it's an interesting idea but I think it can be separated from the issue here. So far renaming seems to be the way to go, if one can tolerate a bit of confusion on the reflection side.

**Comment by mdcfrancis** [comment]
@nalimilan War is a bit strong :smile: - there should with the following  @JeffBezanson yes a separate issue which could allow us to turn warnings into errors.

```
f( x::MyType, final x::Number ) 
and
f( x::YourType, final x::Number ) 
```

**Comment by StefanKarpinski** [comment]
@nalimilan's analysis of this seems spot on and renaming does seem like the way to go.

**Comment by StefanKarpinski** [comment]
Resolved: The solution to *this* issue is the hidden method name. Whether to do autoconversion or not is a separate issue, which applies to both optional positional and keyword arguments.

**Comment by StefanKarpinski** [comment]
This is technically a breaking change but is unlikely to break any sane code.

**Comment by JeffBezanson** [comment]
This is pretty easy to fix unless we care about hiding the extra function in stack traces and the debugger. Situation will be similar to some of the issues around keyword arguments. I'm also a little concerned that the number of extra functions generated will be excessive, but I'm willing to try it and see.

**Comment by StefanKarpinski** [comment]
The total number of methods remains the same, so it's hard to imagine it being that bad.

**Comment by JeffBezanson** [comment]
There is one extra method (and function) per definition. See https://github.com/JuliaLang/julia/issues/7357#issuecomment-140404331

**Comment by StefanKarpinski** [comment]
Is this realistically still happening in 0.6?

**Comment by StefanKarpinski** [comment]
@JeffBezanson did some experiments with this and found that the rename approach is too expensive since it increases the number of methods generated by a very large amount (+10%). There may be other ways to do it (e.g. using invoke), but this isn't happening in 0.6.

**Comment by JeffBezanson** [comment]
My current thinking is that the simplicity of the existing approach is a good thing, and we should just keep it.

**Comment by vtjnash** [comment]
Actually, I'm offering to play around with some of the changes to make this possible, and delay deciding on which way to go with this. So the plan is to make it possible to pass a Method to `invoke`, and then explore whether using `invoke` to the specific Method is better (or not) compared to the current implementation of doing full re-dispatch.

**Comment by JeffBezanson** [comment]
True, we haven't tried the `invoke` approach to this, and I think that might be reasonable.

**Comment by rfourquet** [comment]
Just wanted to support the current approach, as most people here expressed a preference for an alternative. I understand it can be perceived as surprising, but IMHO this should just request a warning in the docs. I can't help but finding the current behavior as correct: 
```
"""
    f(x::Number=0)

Computes f(x).
"""
f(x::Number=0) = generic_slow_algorithm(x)
f(x::Int) = fast_algorithm(x)
```
The first definition is the one specifying the API, the most general one (hence it makes some sense to specify the default there). If the second one is defined, now or later, possibly in another file, it means generally (always?) that this specialization should be better for `Int`, so I don't see why it shouldn't be called for the default argument. Doing otherwise is even a lie to the user: calling `f(0)` will be fast, but calling `f()` will be slow, when the doc and the signature pretend they should be equivalent. 

I still need to see a use case for the proposed change (with `invoke` or `_hidden_f`), and when such a use case happens, it's simple enough to enable manually. On the other hand, it's not difficult to find use cases for the current behavior, e.g. 
```
rand!(A::AbstractArray, rng::AbstractRNG=GLOBAL_RNG) = ...
rand!(A::Array{Float}, rng::MersenneTwister) = ...

# alternative with proposed change
rand!(A::AbstractArray, rng::AbstractRNG) = ...
# NOTE: don't set GLOBAL_RNG as default in the above method, wouldn't work well for Array{Float64} :(
rand!(A::AbstractArray) = rand!(A, GLOBAL_RNG)
rand!(A::Array{Float}, rng::MersenneTwister) = ...
```
The worst part is if the improved method (the last one) is added later in time, then one must review all existing methods with defaults to check that the correct implementation is selected.

In the case presented above [here](https://github.com/JuliaLang/julia/issues/7357#issuecomment-140420797) for example, if the "somebody" refers to the author of another package "somewhere else", this this somebody is commting type piracy, so according to current Julia "good practices", this should not happen.

**Comment by StefanKarpinski** [comment]
It's arguable that in cases where the default value is of the given argument type the current behavior is acceptable, but in cases where the default is not of the given type are really clearly wrong.

**Comment by stevengj** [comment]
Yes, `foo(x::Number=0)` seems fine to me, even it it ends up dispatching to `foo(x::Int)`, but `foo(x::Number="string")` seems like a coding error even if `foo(::String)` exists.

**Comment by StefanKarpinski** [comment]
The `foo(x::Number="string")` example is definitely bad, but I'm actually *more* worried about subtler cases like `foo(x::Int8=0)` which will not do what it seems like it should at all, but on the face of it doesn't look completely wrong.

**Comment by vtjnash** [comment]
For a motivating example of default argument behavior, consider: https://github.com/JuliaLang/julia/blob/d989d3e79b0712e0ab2ed74cd7c3929c39ac7911/base/strings/types.jl#L29-L33
(which is missing some coverage of correct methods). I would be nicer to be able to write those with default keywords (and more complete coverage of the set of possible method dispatch signatures), and expect that dispatch will work out as desired:
```julia
 SubString{T}(s::AbstractString, i::Int, j ::Int) where {T} = SubString{T}(s, i, j)
 SubString{T}(s::SubString, i::Int, j::Int) where {T} = SubString{T}(s.string, s.offset + i, s.offset + j) 
 SubString{T}(s::T, i::Int, j::Int) where {T <: SubString} = SubString{T}(s, i, j) 
 SubString{T}(s::AbstractString, i::Integer=start(s), j::Integer=endof(s)) where {T} = SubString{T}(s, Int(i), Int(j)) 

 SubString(s::AbstractString, i::Int, j::Int) = SubString{typeof(s)}(s, i, j)
 SubString(s::SubString, i::Int, j::Int) = typeof(S)(s.string, s.offset + i, s.offset + j) 
 SubString(s::AbstractString, i::Integer=start(s), j::Integer=endof(s)) = SubString(s, Int(i), Int(j)) 
```

**Comment by StefanKarpinski** [comment]
I suspect we should just punt on this for 1.0 unless someone (@vtjnash maybe) has some evidence that we can do something about this without a performance hit.

**Comment by oscardssmith** [comment]
Closing since at this point, we aren't going to change behavior.
