### ISSUE TITLE
Syntax error in argument list does not print line number

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#7358]
Today I did something similar to this, except that the missing comma was buried in a big function. It would have been really helpful to tell me what line was the problem (or even the exact character). I must say the error message is already pretty good and very precise.

``` julia
julia> function f(x::AbstractVector...)
                  l = map(length x)
              end
ERROR: syntax: missing comma or ) in argument list
```

**Comment by KristofferC** [comment]
This seems consistent with other syntax errors.
