### ISSUE TITLE
which operators should have n-ary parsing?

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/julia#7368]
As mentioned in

https://groups.google.com/forum/#!topic/julia-users/CQs8uGvbnIo

having `A & B & C` generate `Expr(:call,:&,:A,:B,:C)` instead of `Expr(:call,:&,Expr(:call,:&,:A,:B),:C)` would be helpful for the formula language in DataFrames.jl

**Comment by mschauer** [comment]
There is a short related discussion in http://legacy.python.org/dev/peps/pep-0465/#precedence-and-associativity , also I don't agree with the conclusion.

**Comment by diegozea** [comment]
Maybe this strange behaviour is related to this parsing/precedence issue:

```
In [26]: [0,1,0,0].==0 & [0,0,1,0].==0
Out[26]: 
4-element BitArray{1}:
  true
 false
  true
  true

In [27]: ([0,1,0,0].==0) & ([0,0,1,0].==0)
Out[27]: 
4-element BitArray{1}:
  true
 false
 false
  true
```

**Comment by diegozea** [comment]
Maybe this strange behaviour is related to this parsing/precedence issue or to  https://github.com/JuliaLang/julia/issues/5187

```
In [26]: [0,1,0,0].==0 & [0,0,1,0].==0
Out[26]: 
4-element BitArray{1}:
  true
 false
  true
  true

In [27]: ([0,1,0,0].==0) & ([0,0,1,0].==0)
Out[27]: 
4-element BitArray{1}:
  true
 false
 false
  true
```

**Comment by tkelman** [comment]
this is almost certainly going to remain as-is for 0.6 feature freeze

**Comment by marius311** [comment]
I found this issue after asking [this](https://discourse.julialang.org/t/is-there-any-way-to-make-custom-binary-infix-operators-right-associative/3202/5) on the forums. I wanted to point out a particular usefulness of making many more things parsed as n-ary which doesn't seem to have been mentioned here. It allows the programmer to define whether any custom binary infix operators are left vs. right assosciative by default. One can currently do this for + and *, e.g. 

```julia
julia> import Base: +
julia> +(args::String...) = foldr(+,args)  #or foldl for left-assosciative
julia> +(a::String, b::String) = "($a,$b)"
julia> "a"+"b"+"c"
"(a,(b,c))"
```

In my particular use case, I was defining an operator `⨳`, which works alot like matrix/vector multiply, i.e. `(A*(B*x))` is much more efficient to compute than `((A*B)*x)`, hence I wanted to make it right-assosciative to make my code clearer than having to write many parenthesis.

**Comment by JeffBezanson** [comment]
As part of this we should also settle #11739, i.e. whether we need vararg `&` and `|`.

**Comment by JeffBezanson** [comment]
Let's just keep the current `+`, `*`, and `++` n-ary operators, and not add more.
