### ISSUE TITLE
Pkg memory leak

### ISSUE THREAD

**Issue by lrq3000** [JuliaLang/julia#7381]
Pkg.update() and other Pkg commands will make Julia interpreter use a lot of memory (from around 120-180 MB at startup to 500-900 MB after Pkg) and never release it afterwards (tried to gc() but it didn't free any space).

This was observed on the latest Julia v0.3 prerelease of today (Commit 98deb70) on two different computers (one with Windows 7 32bits and one with Ubuntu 14.04).

**Comment by jakebolewski** [comment]
Pkg may still be leaking memory, but it no longer due to process spawning.
