### ISSUE TITLE
Indexing a range by a range

### ISSUE THREAD

**Issue by Jutho** [JuliaLang/julia#7420]
I don't think this is expected behaviour?
```julia
r=0:0.1:1
a=collect(r)
a[1:5] # returns Float64[0.0, 0.1, 0.2, 0.3, 0.4]
r[1:5] # returns 0.0:0.01:0.04 
```
From doing more tests, the behaviour is very weird. It looks as if for all `r` with step size <= 0.25, the starting point and step size are first being multiplied by the step size before the indexing happens; in particular the new step size is the square of the old one: e.g.
```julia
r=1:0.002:20
r[2:4] # returns 0.002004:4e-6:0.002012
```

**Comment by mbauman** [comment]
All the examples in this issue seem to be working now, due to #9666 and its follow-on work.  Is there anything left to do here?

**Comment by JeffBezanson** [comment]
Bump. Yes, looks like everything here is working now. Plz reopen if not.
