### ISSUE TITLE
Small contradiction in Packages doc

### ISSUE THREAD

**Issue by amckinlay** [JuliaLang/julia#7437]
The doc says:

> This is functionally equivalent to calling `Pkg.add("UTF16")`, except that `Pkg.add` doesn’t change `REQUIRE` until _after_ installation has completed, so if there are problems, `REQUIRE` will be left as it was before calling `Pkg.add`.

Except above that it says (about `Pkg.add`):

> What this is doing is first adding `Distributions` to your `~/.julia/v0.3/REQUIRE file`…
> It then runs `Pkg.resolve()` using these new requirements…

Because I'm not familiar with Julia, I don't know which statement is closer to the truth, so I can't fix it myself.

**Comment by kshyatt** [comment]
Amusingly (?) enough this wording issue is still around, 3 minor Julia versions later.
