### ISSUE TITLE
conditionally parsing code via the `%if feature` pragma

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#7449]
When one changes the language, it forces packages to choose between using a new feature and only working on new versions of Julia or not using the feature but supporting new and old versions. For non-syntactic changes, you can often work around this with fairly simple conditional definitions. For syntax changes (which are blessedly rare), this doesn't work. To allow code to gracefully handle new syntax while still parsing in older versions of Julia, we're going to introduce, ironically, a new syntax feature: pragmas. The first pragma will be the `feature` pragma, used as follows:

```julia
%if feature conditional_modules
# write code that uses the conditional_modules feature
%else
# fallback code that doesn't use the conditional_module feature
%end
```

A Julia parser will have a list of feature names. If the parser recognizes a feature name, it parses the file as if the source were the code between the `%if` and `%else` or if there is no `%else` until the `%end`. If the parser doesn't recognize the feature name, it parses the file as if the source were the code between the `%else` and the `%end` or as if the source were empty if there is no `%else`.

In general, `%if` pragmas nest:

```julia
%if A
  %if B
    # A and B
  %else
    # A but not B
  %end
%else
  # neither A nor B
%end
```

There should probably also be a `%ifelse` to handle the classic ambiguity here. Other pragmas, should we introduce them are single-line.

**Comment by tkelman** [comment]
Is this sufficiently covered by conditionally using `include_string` ? Not the prettiest, but already works. The amusing thing is that if we were to add some new syntax here, existing packages would need to use `@static` (if the new syntax previously parsed but had a different meaning) or `include_string` (if it caused a parser error) to use it without breaking on older versions of Julia, which has been the gradual upgrade path for most package maintainers now.

**Comment by StefanKarpinski** [comment]
We've survived this long without this, so I'm closing.
