### ISSUE TITLE
iswritable(file) returns true if run under root for read-only files

### ISSUE THREAD

**Issue by crayxt** [JuliaLang/julia#7480]
I see this issue when run julia tests under root (yes I know this is a bad idea)
Following is run under root, OS in Centos 6.
```
julia> file = "/tmp/sdsd.txt"
"/tmp/sdsd.txt"

julia> close(open(file,"w"))

julia> iswritable(file)
true

julia> run(`chmod -w $file`)

julia> iswritable(file)
true
```

Because of that, file.jl test fails on line 33 which is 
```
32 run(`chmod -w $file`)
33 @test !iswritable(file)
```
I suppose we have to check for USER environment variable here? If it is equal to root, we have to make workaround on unix systems.

**Comment by pkofod** [comment]
Is this Julia v0.3? And you mean you started Julia using `sudo julia` right? Because this works on Ubuntu trusty and v0.4.

**Comment by crayxt** [comment]
@pkofod That was the latest LLVM_SVN julia at that moment, run in mock chroot. I haven't checked since. Probably can be closed.
