### ISSUE TITLE
make win-extras its own makefile rule

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#7496]
From @vtjnash comment in #6516. 

> the win-extras target is less elegant and usable than it probably should be: it doesn't 
> really need to be a separate manual step. i think it would be preferable to make this into a 
> more carefully written makefile rule (instead of the shell script hack that it is now)

**Comment by vtjnash** [comment]
it works well enough to leave it alone.

**Comment by tkelman** [comment]
Can be refactored when we get rid of command-line git
