### ISSUE TITLE
Some methods fail on typemin/typemax(::BigInt)

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#7501]
Discussed in #6712
There are a few algorithms in Base that use `typemin(T)` which fail for `BigInt`. 

> findmax{T}(A::AbstractArray{T}, region) at reducedim.jl#288

``` julia
In  [24]: t = eye(BigInt,100);

In  [25]: findmax(t,2)

Out [25]: ERROR: no method typemin(Type{BigInt})
while loading In[25], in expression starting on line 1
 in findmax at reducedim.jl:288
```

And 

> maximum{T}(A::SparseMatrixCSC{T}, region) sparse/sparsematrix.jl#695

cc: @lindahua

**Comment by Liozou** [comment]
I think the introduction of `hastypemax` back in #16844 has solved the root of this (old) issue. Should it be closed?

**Comment by KristofferC** [comment]
Yes, that seems reasonable.
