### ISSUE TITLE
Regex comparison fails with `==` but string comparison does not?

### ISSUE THREAD

**Issue by Aerlinger** [JuliaLang/julia#7530]
Regex comparison fails with `===` and `==`, for instance:

```julia
"asdf" == "asdf" #  => true

r"asdf" == r"asdf" # => false
```

It seems this is because Regex actually utilizes a pointer to representing the regex pattern and extra options, so identical regular expressions point to different locations in memory even if their value is identical. However, would it be safe to consider a Regex as a value object (Like string, date, currency, etc)? If so it might be worth defining a method for == that checks for equality based on the pattern and options of two Regex objects:

```julia
==(re1::Regex, re2::Regex) = (re1.pattern == re2.pattern && re1.options == re2.options)
```

And thus:
```julia
r"asdf" == r"asdf"  # => true
```

**Comment by JohnHBrock** [comment]
It looks like this was fixed by 0cd7198.

**Comment by pao** [comment]
Is there a test for it? That commit didn't add one.

**Comment by JohnHBrock** [comment]
Doesn't look like it. I'll put together a PR.

**Comment by pao** [comment]
Great, thanks. I'll close this then.

**Comment by JohnHBrock** [comment]
Actually, that commit *did* add a test for regex equality: https://github.com/JuliaLang/julia/blob/0cd7198db0b4c16bbf7773cab9e30c98fc3e9972/test/serialize.jl#L302

**Comment by pao** [comment]
Heh, yeah, Oops. Thanks.
