### ISSUE TITLE
improve BigFloat documentation

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/julia#7535]
It would be good if there were pointers to 
`set_bigfloat_precision` and
`get_bigfloat_precision`

and a word about whether one can only have one precision active at a time
conveniently

**Comment by ViralBShah** [comment]
I think the explanation needs to be a bit more detailed, discuss the defaults, etc.

**Comment by tkelman** [comment]
did #13232 close this? cc @dpsanders

**Comment by ViralBShah** [comment]
It appears the documentation in #13232 is not sufficient to close this.

**Comment by ViralBShah** [comment]
https://docs.julialang.org/en/v1.9-dev/manual/integers-and-floating-point-numbers/#Arbitrary-Precision-Arithmetic
