### ISSUE TITLE
Provide better interactive method definition info

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#7536]
Currently when methods are defined at the REPL, you don't get much information:

``` julia
julia> function hey(x,y)
       return x + y*2
       end
hey (generic function with 1 method)

julia> methods(hey)
#1 method for generic function "hey":
hey(x,y) at none:2     #  <-- "none"? what is line 2 of "none"?
```

Whereas methods from files and even IJulia provide much better info.

``` julia
In  [2]: function hey(x,y)
            return x + y*2
        end

Out [2]: hey (generic function with 1 method)

In  [3]: methods(hey)

Out [3]: # 1 method for generic function "hey":
hey(x,y) at In[2]:2   # <-- We at least see what "In [x]:" the method was defined in
```

With all the new fancy REPL/history machinery, could we make this better somehow? Maybe provide the timestamp from history where the method was defined?

Not only would this help in better discerning where a method definition is coming from, but this would also provide a mechanism for #2625 without having to keep the original method definition string somewhere.

**Comment by simonbyrne** [comment]
It would also be nice to be able to access the actual AST of a method, pre-lowering: i.e. obtain an AST that could be re-evaluated to give the same method. The method [here](http://stackoverflow.com/a/14883257/392585) no longer works.

**Comment by KristofferC** [comment]
This now shows:

```jl
julia> methods(hey)
# 1 method for generic function "hey":
hey(x, y) in Main at REPL[3]:2
```

which seems to be along the line of the requested. Tentatively closing, please reopen if there is more to do here.
