### ISSUE TITLE
support fp128 and maybe quad-double

### ISSUE THREAD

**Issue by cgbaker** [JuliaLang/julia#757]
Extended precision types are occasionally useful in prototyping codes and developing numerical intuition of an algorithm. I am thinking here of double-double/quad-double from the QD package [1]. These are statically sized with reasonable performance. The downside is supporting them via LAPACK/BLAS and other libraries; this would definitely be a value-added component of the Julia environment.

[1] http://crd-legacy.lbl.gov/~dhbailey/mpdist/

**Comment by PallHaraldsson** [comment]
FYI [off-topic license discussion]: @cgbaker "GCC __float128 is better than nothing. In addition to __float128, there are FOSS projects QPFloat:
http://sourceforge.net/p/qpfloat/home/Home/ "

It says "QPFloat (GPL 3.0)"

The GPLv3 is incompatible with GPLv2 (that is already used in Julia). Or more correctly, GPL (v2) allows upgrading to v3, that must be done then.

I'm only aware of GPLv2 so far in Julia and that there is work to make it optional. I'm not sure if Julia is against GPLv3, but the "software as a whole" would be under GPLv3 then, right?

This is assuming, "GPL or any later version" is used (possibly "GPL" is allowed, as the license allows upgrading), at least "GPLv2 only" would not be compatible.

[I think there is a GPLv2 only (git?) already used, that would not be a problem becuase of an extra linking exception.]

Only plus of GPLv3 is Apache 2.0 is for sure compatible with it.

**Comment by vchuravy** [comment]
I was working on `FP128`support and I was wondering how big the desire for `FP80` is. My hesitation for adding is that it is only really supported on x86 and I am not sure that there is support at all for them on Power. Just adding the alias to Julia is quite straightforward, but anything else might be non-trivial and should maybe be outside base.

cc: @musm

**Comment by simonbyrne** [comment]
My opinion is that `Float128` and `Float80` should probably be in packages, with the absolute minimum necessary (basically defining the intrinsics) in core Julia.

**Comment by vchuravy** [comment]
Yeah that was my thinking, basically everything in `float.jl`. For a preview see https://github.com/JuliaLang/julia/tree/vc/float128, but you will also nee my work with compiler-rt to make this run everywhere.

**Comment by simonbyrne** [comment]
I've manage to create bindings to the libquadmath which we bundle inside gfortran, and it works fairly well on linux and mac but requires [quite a cumbersome hack](https://github.com/simonbyrne/Quadmath.jl/blob/4d17c2ff754b4e0c99365f526e8f8e9b32633f44/src/Quadmath.jl#L36) to work around calling convention issues. I also still haven't had any luck figuring out the calling convention on Windows.

Is there any chance we could define the type and calling convention in Base?

**Comment by jdh8** [comment]
How about a platform-dependent `Clongdouble` just like `Int`, which finally enables standard C functions like `expl`.

**Comment by stevengj** [comment]
@jdh8, I think it's better to have a `Float128` type which is always IEEE quad precision, implemented in software.  We could have a separate `Float80` for the hardware [80-bit extended precision](https://en.wikipedia.org/wiki/Extended_precision#IEEE_754_extended_precision_formats) on x86 etc.

**Comment by simonbyrne** [comment]
Honestly, everything about the `long double` type is a mess, starting with its name.

**Comment by stevengj** [comment]
It's not nearly as bad as [selected_real_kind](https://gcc.gnu.org/onlinedocs/gfortran/SELECTED_005fREAL_005fKIND.html) in Fortran.  ("Hey, let's encourage the programmer to specify exactly how many digits are needed!  Because programmers usually know that kind of thing, right?")

**Comment by oscardssmith** [comment]
Closing this as packages such as MultiFloats mean that this doesn't need to be in Base.

**Comment by jessymilare** [comment]
I beg to differ. Float128 is defined by a standard which has well-defined operation on NaNs and Infs and binary exponents ranging from −16382 to 16383 (for normal numbers). MultiFloats is nice, but not a drop-in replacement for Float128:

```
julia> big(prevfloat(Inf)) * 2
3.595386269724631416290548474634087135961411350516899931978349536063145215600571e+308

julia> Float64x8(big(prevfloat(Inf)) * 2)
Inf
```

**Comment by simonbyrne** [comment]
[Quadmath.jl](https://github.com/JuliaMath/Quadmath.jl) provides Float128 support on most platforms.

**Comment by photor** [comment]
> Now we have `llvmcall`, it might be possible to create a `Float80` package. I did try playing around with it, but I couldn't figure out how to tell LLVM that
> 
> bitstype 80 Float80
> 
> should be an LLVM `x86_fp80` and not an `i80`.

No progress?
