### ISSUE TITLE
libgit2 planning issue

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#7584]
We already have an issue for the feature of using libgit2: https://github.com/JuliaLang/julia/issues/4158. @jakebolewski created the [LibGit2 package](https://github.com/jakebolewski/LibGit2.jl) to wrap the libgit2 C library, and @andrioni has been working on libgit2 in base (https://github.com/JuliaLang/julia/pull/7339) based, I believe, on @lifeissweetgood's work on same (https://github.com/JuliaLang/julia/pull/4866). This issue is to discuss specifically what remains to be done. Let's plan!

**Comment by tkelman** [comment]
Bump. How do we get started here? @jakebolewski what's the status of the package bindings? If you need help, please ask.

**Comment by jiahao** [comment]
Last I spoke with @jakebolewski about `libgit2`, the low level wrapping is essentially done; however, the library does _not_ offer a drop-in replacement for `git` commands and they have to be manually rebuilt from low-level primitives.

**Comment by tkelman** [comment]
Closing this in favor of #11196
