### ISSUE TITLE
machinefile/ssh improvements

### ISSUE THREAD

**Issue by wavexx** [JuliaLang/julia#7589]
I was trying Julia recently, however I'm having somewhat an hard time to actually use all the cores that I have access to due to the way the workers are spawned.

First:

Is it somehow possible to enhance the machine file to have a:

  host[:count]

format to specify the worker count, instead of repeating the same host 64 times? My current machinefile is a slew of repeated lines. It's actually hard to edit.

Second:

Connecting several times to the same host just to create [n] channels is a bit overkill, *especially* if we're talking ssh. In fact, I cannot have more than ~20 workers to each host in my case.

I was able to increase the count by using the connection multiplexing in ssh itself (by manually configuring ControlMaster/ControlPath), but I would definitely suggest to add:

-o ControlMaster auto -o ControlPath [path] -o ControlPersist 5

when connecting via ssh, where [path] should be a temporary path unique to the current Julia master process being run, in order to avoid ControlMaster sharing among different master processes. This saves at least [N-1] processes on the remote end (besides eliminating the connection handshakes). ControlPersist could also be removed if the ControlMaster is managed by Julia, as opposed to ssh's "auto" feature.

I would also *strongly recommend* ssh -T, in any case, to avoid a tty allocation (we don't need one anyway), since this is another issue when requesting a large number of connections via ssh.

So far this should be rather trivial to do, but it's still not optimal. It's quite obvious that running N instances of the same process on the same machine should be done by executing a single copy of ``julia --worker -p [n]``, then fork [n] times just after bootstrap to share the initialization/memory/setup and use the same communication channel. Given the current non-negligible startup time of Julia, it would make a big difference.

**Comment by kshyatt** [comment]
What's the status on these suggestions? cc @amitmurthy

**Comment by amitmurthy** [comment]
When specified with a count, we now launch only one process on a remote node, and then launch additional workers via that initial instance. So for a directly accessible cluster there is only one ssh connection per node.

Closing the issue. Please reopen if there are any other ssh specific suggestions.
