### ISSUE TITLE
make it easier to build custom image files

### ISSUE THREAD

**Issue by wavexx** [JuliaLang/julia#7594]
Most lisp-based environments support some form of "image" files, and allow the user to dump the current state of the system (which includes JIT-ed code) in either an image that can be passed to a subsequent Julia process or an executable directly.

To cite some examples, emacs uses the infamous unexelf system to dump the heap into executable form, CL has save-lisp-and-die, etc.

It looks like this relates to #7124 (does Julia's -J image actually contain pre-jitted code for a hot start?), but the main point here is that I think a similar system should be exposed to the user, as CL systems have been doing for a long time, using a similar function that allows to save the current image, and a top level function to call when resuming.

This allows all sort of interesting things to be done, but most importantly allows the user to avoid a cold startup and setup precompiled functions.

**Comment by yuyichao** [comment]
I think the package precompilation can close this. We probably still need to improve it (build .so, AOT compilation etc) but it isn't really helpful to keep this broad issue open anymore.

**Comment by NightMachinary** [comment]
Considering there is now PackageCompiler, isn't adding a CL-style `save-lisp-and-die` easy? PackageCompiler has a declarative style that I find too cumbersome. Just loading a session and dumping it to an image is much easier, and more intuitive. 

Copied from @wavexx:
```
Base.dump("~/myimage.ji", toplevel=func)
```
and maybe even:
```
Base.dump("~/myprogram", toplevel=func, executable=True)
```
which, as far as I'm concerned, could start with something simple as a shebang wrapper over a normal image file:
```
#!/path/to/julia --inline-image
[.....]
```

**Comment by KristofferC** [comment]
See https://github.com/JuliaLang/PackageCompiler.jl/issues/591
