### ISSUE TITLE
Syntax highlighting in the REPL?

### ISSUE THREAD

**Issue by Aerlinger** [JuliaLang/julia#7604]
I wanted to submit a pull request for this, but first wanted to get some feedback on how useful syntax highlighting in the REPL would be to other developers. Personally, I find it very useful for readability, especially when giving demonstrations or taking screenshots.

**Comment by ufechner7** [comment]
I would like to see this for example for the "less" function output. For example:
less(+,(Int, Int))

**Comment by ufechner7** [comment]
Would it make sense to create a separate issue for syntax highlighting of the output of "less"?

**Comment by mbauman** [comment]
That's actually something that could probably be resolved quite simply and outside of Julia.  The `less()` function/macro simply punt to ``run(`$get(ENV, "PAGER", "less")``.  So if your `$PAGER` and terminal support syntax highlighting it'll just work.  I think.  Some breadcrumbs here: http://stackoverflow.com/questions/5316360/syntax-highlighting-pager

**Comment by KristofferC** [comment]
FWIW https://github.com/KristofferC/OhMyREPL.jl provides syntax highlighting for the REPL.

**Comment by KristofferC** [comment]
Seems unlikely to happen in Base.
