### ISSUE TITLE
Raise warnings when extending a completely deprecated function

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#7610]
Many of these packages were extending some deprecated functions (e.g. `add!`). Extending deprecated functions won't produce warnings -- that's why the removal of such functions would lead to such massive breakage (see #7609).

If a function is going to be removed entirely (not just some of its methods) in future Julia, the system should produce warnings when packages want to extend it.

**Comment by vtjnash** [comment]
I think `@deprecate_binding` provides a way forward for this (possibly already functional now)?

**Comment by KristofferC** [comment]
Yes.
