### ISSUE TITLE
Build docs if submitting changes to documentation

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#7691]
It would be nice to run basic doc builds on PRs submitting documentation changes:

```
make -C doc html
make -C doc latex
```

I just fixed a couple of formatting errors, and it would be more efficient to have these detected at submission time.

I haven't thought very hard about how to do this, but presumably it is possible to detect if a given PR branch touches the docs and run the doc build test if it does. Or it might be simpler (if more annoying) to just include the doc build as part of the default Travis build test.

**Comment by kshyatt** [comment]
@MichaelHatherly is this done? I think so, right?

**Comment by KristofferC** [comment]
Yes this is fixed.
