### ISSUE TITLE
rref doesn't support all possible types, like e.g. rationals

### ISSUE THREAD

**Issue by kaueraal** [JuliaLang/julia#7692]
Almost the same issue as #1869: 

Since rref uses `copy!(similar(A, T <: Complex ? Complex128 : Float64), A)` types like rationals are converted to floats.
I'd suggest changing the line to something like `copy!(similar(A, T <: Integer ? Float64 : T), A)` to catch all possible types and only convert ints to floats.

**Comment by andreasnoack** [comment]
The function has been removed.

**Comment by blegat** [comment]
As a future reference, this is now fixed in the [repo where rref is now](https://github.com/blegat/RowEchelon.jl).
