### ISSUE TITLE
Document goto in manual

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#7706]
`@goto` and `@label` are mentioned in NEWS, but conspicuously absent in the Control Flow section of the manual.

**Comment by ViralBShah** [comment]
It could be documented in the dev section of the manual.

**Comment by kshyatt** [comment]
Still not documented, assuming we want it to be.

**Comment by KristofferC** [comment]
Shoud revive https://github.com/JuliaLang/julia/pull/15490

**Comment by KristofferC** [comment]
#23656
