### ISSUE TITLE
Allow URLs (unregistered packages) in REQUIRE

### ISSUE THREAD

**Issue by swadey** [JuliaLang/julia#7737]
We can clone URLs to install unregistered packages, but it doesn't seem possible to install unregistered dependencies in any way other than manually.

**Comment by ihnorton** [comment]
Bumping this to up-for-grabs as it keeps coming up (also discussed at JuliaCon).

**Comment by quinnj** [comment]
We probably want to think about this in the context of https://github.com/JuliaLang/METADATA.jl/issues/2777 though. I guess we could just require that the unregistered package's tests be passing as well, though the "unregistered" part seems to conflict with the idea of having everything in METADATA be super solid.

**Comment by StefanKarpinski** [comment]
It seems fine for untagged packages to depend on other untagged packages, but wrong for tagged packages to depend on untagged ones.

**Comment by tkelman** [comment]
> It seems fine for untagged packages to depend on other untagged packages, but wrong for tagged packages to depend on untagged ones.

+1

**Comment by cossio** [comment]
Any updates on this? Perhaps a simple solution is to only register packages that REQUIRE already registered packages.

**Comment by StefanKarpinski** [comment]
REQUIRE files are going away in Pkg3, so yes.

**Comment by cossio** [comment]
> REQUIRE files are going away in Pkg3, so yes.

+1 Awesome.
