### ISSUE TITLE
more granular Pkg.publish()

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#7749]
Every time I run `Pkg.publish()` I have this feeling like "I hope I'm not accidentally publishing anything I don't mean to". It feels like I should be able to do `Pkg.publish("MyPkg")` to be more explicit.

Alternatively (or in addition) it would be nice if `Pkg.status()` showed which packages have a version difference so you'd know unambiguously which packages will be published.

**Comment by jakebolewski** [comment]
Moving to PkgDev.jl
