### ISSUE TITLE
Update Pygments lexers

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#7758]
It would be nice to update [the Pygments lexers](https://bitbucket.org/birkenfeld/pygments-main/src/bec55c895c0475097940dde470060a68e6ce6958/pygments/lexers/math.py?at=default#cl-32) to recognize keywords introduced for 0.3 and also the various shell modes for `jlcon`.

**Comment by JeffBezanson** [comment]
I think this still needs to be done for 0.6?

**Comment by mykelk** [comment]
Yes, it still does. Here's the [source](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/julia.py) of the relevant file. As you can see, it is missing `struct` etc.

**Comment by joshday** [comment]
There is an open PR for the 0.6 changes: 

https://bitbucket.org/birkenfeld/pygments-main/pull-requests/728/add-julia-06-language-features-to-juliapy/diff

**Comment by mykelk** [comment]
Here is a version for Julia 0.6:
https://github.com/sisl/pygments-julia6

**Comment by KristofferC** [comment]
Referenced PR is now merged.
