### ISSUE TITLE
backtrace collection is slow

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/julia#7759]
edit: see Julep https://gist.github.com/vtjnash/9cd53434cc7f7e2f7a29

When the exception clause is triggered, run times are a couple orders of magnitude slower on Windows than on Linux.  (normally Julia code on this Windows system runs in about 1.2-2x slower than on the Linux box)

For example: 
```
a=Int[5,2,4]
function fn(a)
    for i in 1:5
        try  
            j= a[666]
        except
            println("doh!") 
        end
    end
end

@time fn(a)
@time fn(a)
@time fn(a)
@time fn(a)
```

Linux output: 
Version 0.3.0-rc1+224 (2014-07-28 12:59 UTC)
master/ef66810* (fork: 16 commits, 1 day)
x86_64-redhat-linux

```
elapsed time: 0.006332956 seconds (83896 bytes allocated)
elapsed time: 8.6777e-5 seconds (80 bytes allocated)
elapsed time: 8.9014e-5 seconds (80 bytes allocated)
elapsed time: 8.7249e-5 seconds (80 bytes allocated)
```

Windows output:
Version 0.3.0-rc1+215 (2014-07-27 22:38 UTC)
Commit 229aa20 (0 days old master)
x86_64-w64-mingw32
```
elapsed time: 0.033680986 seconds (79936 bytes allocated)
elapsed time: 0.009554429 seconds (80 bytes allocated)
elapsed time: 0.009440604 seconds (80 bytes allocated)
elapsed time: 0.008863541 seconds (80 bytes allocated)
```

**Comment by vtjnash** [comment]
after a few iterations on the backtrace emission on windows, this is actually fixed now (surprise!).

**Comment by timholy** [comment]
Really amazing!
