### ISSUE TITLE
REQUIRE version specification syntax is a common source of confusion

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#7763]
in #7757 @iainnz brought up that the REQUIRE syntax is a source of confusion for a pretty large number of people, so I figured it might be worth an issue to brainstorm.

see https://pythonhosted.org/setuptools/pkg_resources.html#requirement-objects for how setuptools in python parses package requirements.

https://pythonhosted.org/setuptools/pkg_resources.html#parsing-utilities describes how version numbers comparison works (e.g. trailing `.0`s are dropped, so `2.4` is equivalent to `2.4.0`)

Certainly complicates the parser, but at least there's a formal spec given.

In the interest of having an example in the thread:

```
FooProject >= 1.2
PickyThing<=1.6,!=1.9.6,<2.0,==2.4.0
SomethingWhoseVersionIDontCareAbout
```

This would describe that FooProject had to be `1.2.0` or greater, PickyThing could be anything from `1.6.0`(inclusive) to `2.0.0`(non inclusive), except for `1.9.6`. `2.4.0` is OK too. SomethingWhoseVersionIDontCareAbout can be any version.

In general I wouldn't expect most packages to need this much specificity, and the currently common
```
julia 0.3-
```

would become

```
julia >=0.3
```

(though this wouldn't catch 0.3-rc1 if we're following the same parsing rules as python)

**Comment by jakebolewski** [comment]
@tkelman I think you may want to tackle this one for your own sanity

**Comment by tkelman** [comment]
The current format is beyond fixing. Explaining it more won't suddenly fix the broken intuition people have about it. Should eventually be replaced with a more verbose specification, a la https://github.com/JuliaLang/julia/issues/11955

**Comment by jakebolewski** [comment]
I agree, closing this issue in favor of #11955.
