### ISSUE TITLE
coverage flags are broken with LLVM 3.5 on master

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#7779]
I'm not getting any valid results when using the svn version of LLVM and the latest prerelease build.  Malloc line counts are there, just all allocation counts are zero.

Edit:  It looks like code coverage is not working either.

**Comment by vtjnash** [comment]
whoops, just saw this one, and it was an easy one. keep 'um coming. (linking from the llvm35 issue definitely helps)
