### ISSUE TITLE
document type hierarchy

### ISSUE THREAD

**Issue by RossBoylan** [JuliaLang/julia#7782]
Particularly for numbers, it would be good to have the type hierarchy and aliases in an easy to access place. http://docs.julialang.org/en/latest/stdlib/base/?highlight=log#standard-numeric-types 
has concrete types only.  The manual's discussion of abstract types gives some information but this is hard to find as reference material, and it is unclear if it is comprehensive or illustrative.

Aliases like Int should be in there too.  Discussion of which types to use under which circumstances would also be helpful, though perhaps out of place in a reference manual.

A complete reference on the type hierarchy (not just Numeric) also seems it should be somewhere, though perhaps there isn't enough going on outside of numbers to justify it.

**Comment by vtjnash** [comment]
`./julia examples/typetree.jl` can generate this. would just need to have something automatically add it to the manual

**Comment by brenhinkeller** [comment]
Fixed  by https://github.com/JuliaLang/julia/pull/45975 🎉
