### ISSUE TITLE
Correlation sparse array is very slow

### ISSUE THREAD

**Issue by paulanalyst** [JuliaLang/julia#7788]
Correlation sparse array is very slow. Out of memory on a dense array when we have 30,000 columns. How quickly it calculated?

``` jlcon
julia> I=int32((rand(10^7)*9999999).+1);

julia> J=int32((rand(10^7)*29999).+1);

julia> V=int8((rand(10^7)*9).+1);

julia> D=sparse(I,J,V);

julia> @time cor(D[:,1:30]);
elapsed time: 23.806328476 seconds (2458875228 bytes allocated, 0.14% gc time)

julia> @time cor(full(D[:,1:30]));
elapsed time: 4.494099126 seconds (2732042496 bytes allocated, 5.31% gc time)
```

Paul

**Comment by paulanalyst** [comment]
Dear, what about sparse statistic?
Now a have the simple sample:
@time E=mean(D,1)
after 15 min nothing, but it is posible in 0.8sek in simple while :

julia> k,l=size(D)
(6000000,30000)

julia> E=zeros(l)';

julia> @time for i=1:l
       E[i]=mean(D[:,i])
       #if mod(i,1000).==0 println(i);end;
       end;
elapsed time: 0.838322868 seconds (794730416 bytes allocated, 48.18% gc time)

Propably is simmilary in cor, var,cov, etc

Paul

**Comment by paulanalyst** [comment]
Please, let use the parallel in this functions.

**Comment by andreasnoack** [comment]
@paulanalyst As usual: what is your `versioninfo()`? Also what is `nnz(D)`? On latest master, I get
```julia
julia> A = sprandn(6000000,30000,0.00003);

julia> @time mean(A, 1);
elapsed time: 0.13834035 seconds (166 MB allocated, 9.94% gc time in 7 pauses with 0 full sweep)
```

**Comment by paulanalyst** [comment]
julia> versioninfo()
Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> nnz(D)
99625891
Paul

**Comment by nalimilan** [comment]
I can confirm that on 0.3.5 @andreasnoack's example takes ages.

**Comment by andreasnoack** [comment]
Yes. A faster mean for sparse matrices was introduced in https://github.com/JuliaLang/julia/commit/bde4e65f5d24fc5e3177449772496116123e49d3 so it is not available on 0.3.x. However, the implementation is very simple, i.e. `sum(A,1)/size(A,1)`, so you could use this method instead while waiting for 0.4.

**Comment by paulanalyst** [comment]
OK, at 0.4.0 mean is fast, like below. But for "var" I am waitng many minetes...
 A fresh approach to technical computing
 Documentation: http://docs.julialang.org
 Type "help()" for help.

 Version 0.4.0-dev+2438 (2015-01-03 12:36 UTC)
 Commit b0d94dd (27 days old master)
 x86_64-w64-mingw32

julia> @time E=mean(D, 1)
elapsed time: 6.035410891 seconds (1558239044 bytes allocated, 18.71% gc time)
1x30070 Array{Float64,2}:
 0.0  0.0904202  0.0072963  0.00103694  0.00430618    1.68553e-7  3.37105e-7  3.37105e-7  1.68553e-7

julia> @time E=var(D, 1)
minutes.... 
Paul

**Comment by paulanalyst** [comment]
sum(D,1)/size(D,1) at 0.3.5 is 2 times longer then mean(D,1) at 0.4.0. , 11 ver 6 sek in my array.

julia> @time sum(D,1)/size(D,1)
elapsed time: 11.550475452 seconds (1555463276 bytes allocated, 13.28% gc time)
1x30070 Array{Float64,2}:
 0.0  0.0904202  0.0072963  0.00103694  0.00430618    1.68553e-7  3.37105e-7  3.37105e-7  1.68553e-7
Paul

**Comment by andreasnoack** [comment]
I think that the reason `sum` in 0.4 is faster is our new garbage collector bacuase I think the implementation is the same.

The `var` reduction is slightly more complicated and not implemented efficiently for sparse matrices yet, but you can probably benefit from the trick we discussed last time, i.e. by using the `E(XX') - EX(EX)'` formulation.

**Comment by ViralBShah** [comment]
We should backport the mean.

**Comment by paulanalyst** [comment]
@ andreasnoack
E(XX') is a vecotr...

I use X'X-E(X)'*E(X)
Paul

**Comment by andreasnoack** [comment]
Then you won't get the right result.

Anyway, I'm talking about the method in the issue where you thought the was a rounding error, but it was wrong formula.

**Comment by ViralBShah** [comment]
#10536 should have fixed this one.

**Comment by simonster** [comment]
Unfortunately it doesn't look like it does, since `cor` is not based on `mapreduce`/`mapreducedim`.
