### ISSUE TITLE
Should append! accept any iterable?

### ISSUE THREAD

**Issue by ivarne** [JuliaLang/julia#7798]
`append!` is currently limited to instances of `AbstractArray`. I can't really see why this restriction is necessary, as lots of similar functions gladly take any iterable in similar situations.

Somewhat related to https://github.com/JuliaLang/julia/issues/7642

**Comment by vtjnash** [comment]
Seems like this should be revisited now that general iterables have a length computable attribute?

**Comment by JeffBezanson** [comment]
It looks like this was added by e909c1c99843eac476b123b58a1039858d959ab4

**Comment by JeffBezanson** [comment]
We're missing `append!(::BitArray, iterable)`. Should add that method.

**Comment by StefanKarpinski** [comment]
Adding methods is non-breaking, so this does not belong on the 1.0 milestone.

**Comment by Keno** [comment]
The missing method was implemented by @JeffBezanson in 4844a4bdf692192982273a63bfee192677ca36e4
