### ISSUE TITLE
Three argument versions of scale! don't check C dimensions

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/julia#7812]
The three argument versions of `scale!` defined in `base/linalg/matmul.jl` (lines 8 and 20) don't check the size of the destination matrix (C) for compatibility with the source matrix (A).  If C is too small there will be a index error but nothing bad happens if C is too large.

Also, is there a reason that these methods are defined for Matrix and Vector arguments instead of AbstractMatrix and AbstractVector?  I was trying to scale a view in place by a vector and encountered "no method" errors.

If these suggestions seem reasonable I can prepare a PR to
- check the dimensions of C match those of A
- generalize the argument types to AbstractMatrix and AbstractVector
- add `@inbounds` macro calls because the dimensions have been checked

cc: @jiahao @andreasnoackjensen @ViralBShah

**Comment by andreasnoack** [comment]
@dmbates bump
