### ISSUE TITLE
Pkg.submit suggestions

### ISSUE THREAD

**Issue by ggggggggg** [JuliaLang/julia#7820]
First, Pkg.submit is pretty cool, I just used it to submit a pull request to HDF5.jl.  It definitely easier to approach for the non-expert than figuring out how to fork and sync my changes with github myself.  That said, it took me a few tries to realize that 1. I need to commit my changes (yes this is obvious, but hey I'm not that good at this) 2. what to do about it.  The current behavior has you looking at an empty pull request when you haven't committed your changes locally.

My recommendation is for submit to look at the current branch, and it is in the default detached HEAD state, to print out some guidance like. Perhaps something like the following:

Before submitting a pull request you must commit your changes.  Try "checkout -b newbranch" followed by "git add ." and "git commit -m "some useful commit message". 

It would also be nice if it set up your branch such that `git push` pushes to the pull request branch that submit had created on github for easily updating that pull request.

**Comment by jakebolewski** [comment]
Moved to PkgDev.jl
