### ISSUE TITLE
disable COPY_STACKS

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#7824]
While `COPY_STACKS` is nice for keeping memory allocation somewhat limited (due to inference and codegen requirements), it is bad for c integration. Since we have such a nice `cfunction`, it is a shame that `COPY_STACKS` significantly complicates/limits what you can do inside of those functions (e.g. no calling the same library on a different task inside a cfunction). Other benefits of disabling it include avoiding making backup copies of the stack for each task, and copying that memory with each task switch.

~~therefore, my proposal is to
 (a) disable copy-stacks
 (b) reintroduce the code for running inference / codegen in a separate thread
 (c) only do the thread context-switch when not running `--build` mode~~

**Comment by KristofferC** [comment]
Is this still relevant?

**Comment by yuyichao** [comment]
YEs

**Comment by Keno** [comment]
Addressed by the partr task work?
