### ISSUE TITLE
Provide a standard way to find the default julia install

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#7835]
There are now many pieces of software that are started directly by the user and that then need to start a julia.exe internally. [IJulia](https://github.com/JuliaLang/IJulia.jl), the various editor plugins (e.g. [Sublime-IJulia](https://github.com/quinnj/Sublime-IJulia) and [Jewel](https://github.com/one-more-minute/Jewel)) are good examples of that. Right now each of these somewhere saves the hard coded full path to an ijulia.exe for that purpose. For some of these (the editor plugins) you actually have to manually edit a config file to tell it where the julia.exe is located, for others the path is picked up during setup (IJulia) and then stored.

I think a better model would be to provide some central registration for the "active" julia installation, e.g. something like a JULIAHOME environmental variable that points to the currently active julia.exe, so that not every one of these pieces of software has to store the path to julia. The JULIAHOME variable could be set during setup of julia.

That would allow a couple of neat things: one could have multiple julia versions installed in parallel, with one being "active". If the active one is changed, all the ide plugins and ijulia would pick that one up. Also, right now if one installs a new version of julia that puts things into a different directory than a previous install (e.g. for a while the directory was julia-0.3.0-prelease or something, not it is julia-0.3.0-rc1) these other pieces of software would still work because they could automatically pick up the new install location of julia.

This would also help with something like the chocolatey package that I'm building (#7386) that will probably end up installing julia prerelease versions into directories that contain the git commit sha, i.e. where the install directory name will change for every new build.

**Comment by davidanthoff** [comment]
Bump, it would be really great if we could find some solution for this before 1.0.

This is the kind of usability thing that really makes life difficult for inexperienced users. I'm seeing these problems again with the VS Code extension for julia: one now has to configure a setting with the path to the julia binary at first start, and then whenever one installs a new version of julia one has to update that setting in VS Code, because the Windows installer uses a different directory name for different julia versions. Not a problem for me, but the amount of friction this is causing for new users is quite amazing (I'm bringing a lot of new folks to julia lately that don't have a strong programming background).

I think my favorite solution for now would be what @tkelman suggested above:

> What if, on a per-user basis, we have a ~/.julia/.active_julia file that contains the absolute path to the currently active Julia installation?

I think that would do the trick, would be cross-platform essentially just solve this problem.

Tony also suggested this
> Maybe under the versioned package dir instead so it can be independent for each minor version of Julia.

I think I would prefer just one active julia. At the end of the day, I need to pick one julia version in something like the VS Code extension, so having different active julias for different minor versions just pushes the problem some level down.

**Comment by StefanKarpinski** [comment]
I think we'd want this to be an environment variable, a la virtual-env. The current active Julia should be a dynamically scoped property, not a global one.

**Comment by tkelman** [comment]
I don't think Julia installation should be making permanent environment variable modifications. Is that even doable with a dmg or tarball?

**Comment by StefanKarpinski** [comment]
I meant in a shell session. Perhaps we need a global "default starting Julia" and environment variable for overriding that with a dynamic scope across processes.

**Comment by tkelman** [comment]
any shell centric setting would be inappropriate for windows, or editor applications that are launched from somewhere other than a shell

**Comment by StefanKarpinski** [comment]
Ok, so propose something that satisfies your requirements and also allows dynamic scoping.

**Comment by nalimilan** [comment]
Environment variables are great to customize/override settings, but we also need a permanent one. On Windows, I guess the registry would be the standard way of doing that. On Unix, `PATH` should be enough (it normally includes `~/.local/bin` so that one can override `/usr/bin` with custom executables/symlinks if needed).

**Comment by davidanthoff** [comment]
For VS Code, we would still have a setting where users could pick some other julia binary than the global active one, so at least for our purposes just one global active julia binary that we can easily find would be good enough.

A more complete solution would probably have some sort of central information about *all* julia versions that are currently installed, plus an indication which of those is the default one.

What is the use case for dynamic scoping?

**Comment by davidanthoff** [comment]
[This](https://www.python.org/dev/peps/pep-0514/) shows the current (future?) Python approach to registering all installed Python versions. Not clear to me (from a hasty read) how they go about the default or active version...

**Comment by StefanKarpinski** [comment]
> What is the use case for dynamic scoping?

Different processes (shells, IDEs) should be able to set their preferred Julia and have child processes respect that. That's why environment variables are good for this use case.

**Comment by tkelman** [comment]
I don't see this needing to be changed all that frequently, or applications wanting to modify this in a scoped way. How many applications that need this kind of configuration are going to spawn other distinct applications that also need this, while wanting to make process-local modifications to this information?

There's already a perfectly good mechanism for controlling aliases and shortcuts within shells. For non-shell applications, I think a filesystem config file is the most portable and easy to modify option. Users might need to modify this configuration once in a while, but otherwise the Julia installer is the only thing that would really need to ever touch this.

**Comment by davidanthoff** [comment]
I agree with @tkelman, I don't really see the need for dynamic scoping, at least not for the use case of an IDE/editor plugin.

Thinking through this for the VS Code extension situation, I think the only case where this might come up is if someone wants to start say another julia instance from the julia REPL inside VS Code. But ``Base.julia-cmd()`` should be good enough for that, I think.

**Comment by digital-carver** [comment]
On the Windows side of things:

> does it complicate things if we start messing with environment variables? (i.e. require additional permissions, etc.?)

Setting a user-level (permanent) environment variable doesn't require any special permissions (afaict). So the installer can set `JULIA_HOME` (or `ACTIVE_JULIA`) as a user-level environment variable by default, and have an option in the UI for the user to set it at the system level (with UAC approval from the user) if desired. 

>  better than environment variables at least since the registry is exactly supposed to be used for this kind of things.

>  I don't have a problem with adding a JULIA_HOME environment variable. The other option is to put something in the registry, but that makes life more difficult for everyone.

Setting permanent environment variables [*is* editing the registry](https://stackoverflow.com/q/573817/8127) on Windows, though doing it via environment variables is probably the better, simpler option (compared to directly adding registry keys). 

> I'd really like to see something like this, if only on Windows; it's pretty standard practice to set up user environment variables like JAVA_HOME, PYTHON_HOME etc., so that seems like a reasonable solution to me.

+1

>  making permanent manual changes to environment variables is not very user-friendly on Windows, I can never remember which set of menus it's buried under in control panel

This is subjective, but I think handling environment variables is pretty standard stuff for most regular Windows-based developers (right click My Computer->Properties->Advanced->Environment variables). It's definitely more intuitive to a Windows user than editing a dotfile like `.active_julia`. (And there are tools like [Rapid Environment Editor](https://www.rapidee.com/en/about).)

I think adding an environment variable is probably the way to go here (at least on Windows). Adding to PATH can be another option on the installer that the user can choose to enable (defaulting to off), independent of this feature.

**Comment by davidanthoff** [comment]
The way we handle this in the VS Code extension now is that we just look in some [standard locations](https://github.com/JuliaEditorSupport/julia-vscode/blob/604479905331b1e9333674d999b842f8828ee614/src/juliaexepath.ts#L20) on Windows and Mac. It mostly works for auto detecting a julia installation, but something that is more official would be really great.

**Comment by ViralBShah** [comment]
In general, given that we do not modify the user's environment or system files - I don't know if there is anything more official that can be done. I think you're doing the right thing by looking in the standard locations. Please reopen if you don't agree with me closing this.
