### ISSUE TITLE
Fix struct reference in docs

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#7838]
As noted [here](https://groups.google.com/d/msg/julia-users/0Xpq7YueyiU/JVvJiobQUmUJ), the docs still incorrectly state that 

> Currently, it is not possible to pass structs and other non-primitive types from Julia to C libraries.

at the end of the first section [here](http://julia.readthedocs.org/en/latest/manual/calling-c-and-fortran-code/#calling-c-and-fortran-code).

**Comment by ihnorton** [comment]
Can this be closed? There is some discussion about by-value vs pointer to structs at http://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code/#mapping-c-types-to-julia (two paragraphs above that anchor)

**Comment by kmsquire** [comment]
No longer an issue, as the relevant text (and functionality) has totally changed.
