### ISSUE TITLE
Backtraces cause doctests to be platform-dependent

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#7843]
With doctests that throw errors, our new backtraces are now causing problems, as they include things such as the path of the (compiled) system image, which among other things, has a platform-dependent extension.  This makes having cross-platform doctests (in their current incarnation) impossible.

**Comment by tkelman** [comment]
I'm not really seeing `sys.dylib` or `sys.so` in backtraces any more, so I think this is alright now? There are two places in `doc/manual/strings` that still have `/Users/sabae/src/julia/usr/lib/julia/sys.dylib` in them. I tried making those doctests but they mysteriously wouldn't fail?

**Comment by staticfloat** [comment]
Good call @tkelman; I believe that's because those tests aren't in a `doctest::` block.  I attempted to fix that on [this branch](https://github.com/JuliaLang/julia/tree/sf/docfix), but I get the following sphinx errors on `make doctest`:

```
/Users/sabae/src/julia/doc/manual/strings.rst:236: ERROR: Unexpected indentation.
/Users/sabae/src/julia/doc/manual/strings.rst:250: ERROR: Unexpected indentation.
/Users/sabae/src/julia/doc/manual/strings.rst:251: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/sabae/src/julia/doc/manual/strings.rst:255: ERROR: Unexpected indentation.
/Users/sabae/src/julia/doc/manual/strings.rst:269: ERROR: Unexpected indentation.
/Users/sabae/src/julia/doc/manual/strings.rst:270: WARNING: Block quote ends without a blank line; unexpected unindent.
```

Any ideas?

**Comment by tkelman** [comment]
Hm, interesting, I didn't try exactly that. I'm completely guessing, but maybe the colon at the end of the error message is making sphinx behave differently?

**Comment by staticfloat** [comment]
It looks like this isn't an issue anymore with the new documentation system.

**Comment by tkelman** [comment]
do doctests pass on mac nowadays? (may need the patches in a PR of mine right now)

they don't exactly run right on windows last time I tried, and likely fail on 32 bit linux. we're tracking down some discrepancies in Documenter between the windows and linux html output.

**Comment by staticfloat** [comment]
Yes, it looks like my set of errors are exactly the ones included in your commit https://github.com/JuliaLang/julia/pull/21061/commits/36b88ae5a2f27b98947fc0dd028d2facf8746cda.

**Comment by tkelman** [comment]
Situation on windows is better than I thought - a lot of the doctests pass, though a bunch of them fail just due to paths having backslashes instead of forward slashes. And `running-external-programs.md` doesn't have the right output, probably some issue with output redirection.
