### ISSUE TITLE
lowercase(String) doesn't handle case transformation contexts correctly

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#7848]
1. End-of-word contexts. As reported in #7847, for example, capital sigma Σ should map to lowercase terminal sigma ς at the end of a word, not ordinary sigma σ:

   ```julia
julia> lowercase("ΛΌΓΟΣ") #logos; λόγος
"λόγοσ"
```

2. Locale-specific contexts: let's not [get anyone accidentally killed thanks to incorrect localization](http://www.theinquirer.net/inquirer/news/1017243/cellphone-localisation-glitch).

   ```julia
$LANG="tr_TR" julia
...
julia> uppercase("sikisinca") #SİKİSİNCA
"SIKISINCA"
```

**Comment by jiahao** [comment]
Closed in favor of #11471

**Comment by ScottPJones** [comment]
Pretty please reopen this... I think #11471 is really Windows specific breakage, and this is about handling locale dependent vs locale independent case mappings and foldings in Julia...

**Comment by stevengj** [comment]
@ScottPJones, I think the conclusion was that Julia's behavior should remain as-is (locale-independent), and that more sophisticated locale-dependent behavior belongs in an ICU package or similar.

**Comment by ScottPJones** [comment]
OK, I see what you're getting at... it's not that the issue has been fixed, it's just that it shouldn't be fixed in *Base*.  Do I have that right?

**Comment by stevengj** [comment]
Yes.
