### ISSUE TITLE
serialization / deserialization performance

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#7893]
Julia's serialization / deserialization performance is pretty worrying.  Deserializing a ~500 mb  DataFrame object takes about ~5-6 minutes.  An 8 GB dataframe object takes 3 + hours (it is not finished yet).  It looks like almost all time is spent in GC.  This is making it impractical to do any sort of parallel operations on dataframe objects, without dumping the dataframe out to a csv file and reading the contents back into each process.

``` julia
julia> labevents = open(deserialize, "labevents.jld");

shell> du -h labevents.jld
475M    labevents.jld

julia> @time labevents = open(deserialize, "labevents.jld");
elapsed time: 337.729652605 seconds (4366175664 bytes allocated, 85.11% gc time)
```

@jiahao said serializing the 8GB file took ~5 hours.

**Comment by ScottPJones** [comment]
It's not clear from this issue, has anything been done to specifically improve the performance of serialization/deserialization (besides the general improvement from GC improvements)?  Has the file extension been changed to not be .jld?  Has file header information been added? Is the speed of UTF-16 conversions still an issue?

**Comment by JeffBezanson** [comment]
Yes, there was #11125, and some optimizations in #10170 as well. I don't know how we would change the file extension since we don't use or enforce that extension anywhere in Base AFAIK. We don't really have a file format yet (#7909).

**Comment by stevengj** [comment]
I added a performance benchmark of this to nanosoldier, so we can track this going forward.

**Comment by JeffBezanson** [comment]
I believe this is largely fixed. New issues can be opened if anybody encounters an especially bad case for serialize/deserialize.
