### ISSUE TITLE
make numbers non-iterable?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#7903]
@StephenVavasis [has pointed out](https://groups.google.com/forum/#!topic/julia-users/g7PBys0_6Y8) some rather confusing behavior of the `in` operator, including:

``` jl
julia> VERSION
v"0.3.0-rc2+12"

julia> x = IntSet([3,5])
IntSet([3, 5])

julia> in(3,x)
true

julia> in(x,3)
false

julia> in("abc",19)
false

julia> in(19,"abc")
false
```

Worse still is this:

``` jl
julia> 97 in "abc"
true
```

This issue is to discuss what, if anything, we can do to reduce some of this confusion.

**Comment by tkelman** [comment]
I guess to evaluate this, we'd need to try removing `start`, `next`, and `done` for numbers and see what breaks.

**Comment by StefanKarpinski** [comment]
@mbauman, have you merged the changes you had that make array indexing not rely on this?

**Comment by mbauman** [comment]
Yes, indexing no longer requires iterating over numbers — but it does index into them.

I think there's another issue somewhere where I started looking into deprecating this… but quickly hit lots of comprehensions and loops like `[x[i,j] for i in 1, j in 1:size(x, 2)]`.  I think it's feasible, it'd just take some janitorial work.

**Comment by StefanKarpinski** [comment]
I only found a handful of examples of that:

```jl
base/abstractarray.jl
611:hcat{T}(X::T...)         = T[ X[j] for i=1, j=1:length(X) ]
612:hcat{T<:Number}(X::T...) = T[ X[j] for i=1, j=1:length(X) ]

base/arraymath.jl
380:transpose(x::AbstractVector) = [ transpose(v) for i=1, v in x ]
381:ctranspose{T}(x::AbstractVector{T}) = T[ ctranspose(v) for i=1, v in x ] #Fixme comprehension

base/range.jl
372:ctranspose(r::Range) = [x for _=1, x=r]
```

**Comment by StefanKarpinski** [comment]
After some discussion on a triage call, it's been decided that we should take a crack at this, but everyone has too many things on their plate to do it right now. So if someone wants to do this, it's fairly straightforward: delete all the [iterable interface](http://docs.julialang.org/en/latest/manual/interfaces/) methods for numbers and see what breaks; try fixing stuff that breaks and see how bad it is. Make a WIP PR to report progress and get feedback.

**Comment by stevengj** [comment]
As I noted in #15032, I think `broadcast` still needs to work for scalar arguments (since it *has* to work for mixed scalar/array arguments anyway), but that can be preserved independent of whether scalars are iterable.

**Comment by tkelman** [comment]
Made a quick attempt to see what happened. Concatenation of some array literals has issues when you try to remove `start(::Number)`, like here https://github.com/JuliaLang/julia/blob/e0e93fc85e899105351860172d37b18f51d29183/base/base64.jl#L35 or the following line from `uv_constants.jl`

```
const uv_handle_types = [:UV_ASYNC, :UV_CHECK, :UV_FS_EVENT, :UV_FS_POLL, :UV_HANDLE, :UV_IDLE, :UV_NAMED_PIPE, :UV_POLL, :UV_PREPARE, :UV_PROCESS, :UV_STREAM, :UV_TCP, :UV_TIMER, :UV_TTY, :UV_UDP, :UV_SIGNAL, :UV_FILE]
# ...
    handles = [:UV_UNKNOWN_HANDLE; uv_handle_types; :UV_HANDLE_TYPE_MAX; :UV_RAW_FD; :UV_RAW_HANDLE]
```

**Comment by JeffBezanson** [comment]
Why would this affect arrays of symbols?

**Comment by tkelman** [comment]
Probably nothing specific to the symbol eltype, those are just needed during bootstrap. `vcat` needs `length` and `copy!` on its arguments https://github.com/JuliaLang/julia/blob/e0e93fc85e899105351860172d37b18f51d29183/base/abstractarray.jl#L163-L170, see my edit above for a new method that gets past that

**Comment by JeffBezanson** [comment]
I'm still confused; Symbols don't have `length` or iteration, so how could they have worked with vcat if that's the case?

**Comment by tkelman** [comment]
Found it. `collect(1)` here: https://github.com/JuliaLang/julia/blob/e0e93fc85e899105351860172d37b18f51d29183/base/abstractarray.jl#L706

Another issue is https://github.com/JuliaLang/julia/blob/e0e93fc85e899105351860172d37b18f51d29183/base/strings/util.jl#L132 calling `first` on an integer result from `search`, I guess we could leave `first` and `last` alone, I was trying to get greedy.

**Comment by tkelman** [comment]
Defining `collect(x::Number) = [x]` can also get through bootstrap. See https://gist.github.com/5cc35991da822df921d4743b9799eadf for a diff that bootstraps and a log of all the test failures. Turns out to be pretty deep in a lot of places.

**Comment by JeffBezanson** [comment]
Some of those are easy to fix. I spot:

- There's a `copy` method in lu.jl that calls `copy` on a struct member that is literally always a BlasInt
- A handful of uses of `for i=1` in comprehensions
- The call to `copy` in `power_by_squaring` that I have famously railed against in past threads on aliasing

**Comment by vtjnash** [comment]
Since it seems this is going to be non-trivial to remove, and it's not blocking anyone from using Julia, I'm going to reassign this for v0.6 so we can focus on real issues.

**Comment by JeffBezanson** [comment]
I'm fine with that.

**Comment by mschauer** [comment]
To give an opposite standpoint I think that if a number has ``size()``, it should also be iterable and possible to ``collect`` a number but I guess that I am too late to the party.

**Comment by stevengj** [comment]
The need to support scalars in `broadcast` makes me second-guess the whole "numbers should not be iterable" argument.

**Comment by mbauman** [comment]
I don't think broadcast actually uses iteration. I don't see any broadcast problems in the log Tony posted.  It almost certainly uses size and indexing, though.

It's a really fine line to walk.  It definitely feels right to remove collection-like behavior from numbers, but we also often want numbers to behave like `Array{T, 0}` — which is a collection.

**Comment by martinholters** [comment]
Would it make sense to have something like an `immutable ImmutableSingleton{T} <:AbstractArray{T,0}  x::T end` (with all the necessary methods implemented) around? Everywhere a number should behave like `Array{T, 0}` (except being immutable) it could then be wrapped with IIUC zero runtime overhead.

**Comment by stevengj** [comment]
@martinholters, then to do `atan2(x,0.3)` you would need `atan.(x, ImmutableSingleton(0.3))`?  This seems crazy.

**Comment by StefanKarpinski** [comment]
I think the point is that the broadcast implementation would wrap the singletons for you. Not sure how helpful it would be, but that's how I interpreted @martinholters' suggestion.

**Comment by martinholters** [comment]
@StefanKarpinski I was just trying phrase exactly that, but you were faster.

**Comment by martinholters** [comment]
The point would be that number would not be iterable by default, and functions that benefit from iterable numbers have to take care of that themselves, instead of the opposite. I'm doubtful about the usefulness myself, I just wanted to point out the option.

**Comment by mschauer** [comment]
One part of this seems to be easier to settle: to consider removing both Array{T,0}-like and collection-like properties of ``Char`` separately. Following @mbauman that one is *not* a fine line to walk, because anyway Char is not a Number type anymore and, well, why should ``Char``s behave like ``Array{T,0}``s at all?

**Comment by stevengj** [comment]
(Note that `broadcast` no longer requires `size` etc. to work for numbers.)

**Comment by stevengj** [comment]
As I wrote [on the mailing list](https://discourse.julialang.org/t/map-vs-list-comprehension/916/9?u=stevengj), I think that a lot of the need for iterable/indexable numbers should be gone now with 0.5's dot-call syntax. In the cases where you would previously have written a generic vector/scalar function, you should now just write the scalar function `f(x)`, and then apply it to arrays `A` with `f.(A)`.  This is not only easier, it is also faster because it can fuse with other elementwise operations and the result can be assigned in-place with `.=`.

**Comment by stevengj** [comment]
It's instructive to try to patch Base to make numbers non-iterable.   I'm finding various cases where removing iterability requires much uglier code.  For example:

* In `split`, it calls `r = search(string, splitter)`.  If `splitter` is a string, this returns a range, but if `splitter` is a char, it returns an integer.  Being able to call `first(r)` and `last(r)` in both cases makes the same code work for both.

* In the code generation for multidimensional array indexing, it calls `_nloops` to generate nested loops over the indices in expressions like `a[i, 3:4]`.  By being able to do `for j in i`, the same generated code can handle `i::Int` and `i::AbstractVector{Int}`.

**Comment by stevengj** [comment]
On the other hand, making numbers non-indexable (removing `size`, `getindex`, etcetera), seems much less disruptive.

**Comment by stevengj** [comment]
The converse argument: if it is so useful to make numbers iterable, maybe *everything* should be iterable?  i.e. just define fallback `start` etc. methods for `Any`.

**Comment by nalimilan** [comment]
> In split, it calls r = search(string, splitter). If splitter is a string, this returns a range, but if splitter is a char, it returns an integer. Being able to call first(r) and last(r) in both cases makes the same code work for both.

This would be fixed by https://github.com/JuliaLang/julia/issues/10593 (see [this Julep](https://github.com/JuliaLang/Juleps/blob/master/Find.md)): you'd call `findseq` or `searchseq`, which would return an index range for both string and char arguments. The previous behavior returning a single index when passing a char would be obtained via `findeq`/`searcheq` (which wouldn't work to find a substring). So one less reason not to do this!

**Comment by mbauman** [comment]
And note that we could use #19730 to wrap *all* numbers in a specialized `AbstractArray{T,0}` before they're used in non-scalar indexing within `to_indices`.  That'd give them iteration, indexing, and shape without much hand-wringing… and that could actually remove a few methods.  I'm not sure if there'd be a performance impact, however, and I'd like to keep that patch as conservative as possible for now.  It's already pretty big.

**Comment by StefanKarpinski** [comment]
I increasingly think we're not going to do this. We could make a lint warning that pesters you if you write `for i = x` where `x` is not a range expression. That would catch the cases where someone meant to write `for i = 1:n` and accidentally wrote `for i = n` instead. We could even go so far as to make that a syntax error, but that seems too draconian.

**Comment by terasakisatoshi** [comment]
> write for i = 1:n and accidentally wrote for i = n instead

I often get the phenomena many times. Since it does not raise error e.g. syntax error, it is hard to find
`for i = n` should have wrote `for i in 1:n` 🐛

**Comment by StefanKarpinski** [comment]
Yes, that was one of the motivations cited in this issue when it was opened.

**Comment by terasakisatoshi** [comment]
I've just posted my question at Julia discourse (that is why i mentioned a comment at this issue).

https://discourse.julialang.org/t/question-why-for-n-in-10-show-n-end-is-valid-rather-than-getting-error/33895

It was not clear for me why number e.g. `10` is iterable.
But, by reading a discussion here https://github.com/JuliaLang/julia/pull/19700#issue-99274797. I've found it is difficult choice to decide.

**Comment by non-Jedi** [comment]
Was the conclusion that this definitely isn't happening even for a Julia 2.0? I've seen several complaints/confusions about it in various places over the past few months.

**Comment by mbauman** [comment]
It's gotta be rather convincing.  We tried removing both iterability and indexability pre-1.0, but:

> [**Removing iterability**](https://github.com/JuliaLang/julia/issues/7903#issuecomment-269015974): I'm finding various cases where removing iterability requires much uglier code.

and

> [**Removing indexability**](https://github.com/JuliaLang/julia/pull/19700): Con: eliminating this functionality doesn't actually save us much code in Base, and it might make some kinds of generic functions more annoying to write, especially since numbers are still iterable. Is it worth it?

Some of these things have indeed changed, so it's certainly possible that the balance has shifted... but has it shifted enough?  I'd bet not.  It's quite a bit of churn.

**Comment by timholy** [comment]
I'm generally a supporter of iterability of numbers, but I have seen people get bit by it. To play devil's advocate, would it be so bad to change `for d in dims` to `for d in iterable(dims)` with
```julia
iterable(x) = x
iterable(x::Number) = (x,)
```
?

**Comment by StefanKarpinski** [comment]
... or just toss whatever wrapper we end up using for broadcasting on a number and iterate that

**Comment by mbauman** [comment]
Right, that's what makes this different — that `iterable` function is essentially a narrower form of `broadcastable`.  We now have an entire architecture built up for this sort of thing.

**Comment by stevengj** [comment]
My experience in trying to implement even a small piece of this pre-1.0 (#7903) leads me to believe that changing this would lead to a *huge* amount of code churn over the whole ecosystem.   i.e. it wouldn't be worth it without huge benefits, which I haven't seen anyone articulate beyond "slightly confusing to some newcomers".
