### ISSUE TITLE
Serialization file format for arbitrary julia objects

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#7909]
Python has pretty much standardized on using the .pkl file name extension for serialized python objects. What to call Julia's serialized object dumps?  .jld is already taken.

**Comment by Skylion007** [comment]
I'd like second Simonster's point. Unless we fix the issues with JLD, it cannot be a replacement for JLS.

**Comment by simonster** [comment]
I fixed most of the issues with JLD in JLD2: https://github.com/simonster/JLD2.jl. It reads and writes valid HDF5 files in pure Julia (although for reading it only supports a subset of HDF5). It pretty much works, and it can be many orders of magnitude faster than JLD for the `Vector{Any}` cases. The caveats: I never tested on Windows; I never got around to implementing compression or groups; HDF5 has substantial file size overhead if you're writing a bunch of small objects (although the performance is typically no slower than 2x `Base.serialize`, and in some cases it can even be faster). Unfortunately I have to finish my PhD and won't have time to finish it in the near future.

**Comment by JeffBezanson** [comment]
For 1.0 we should probably add the ability to write a small header giving the format version (and probably an ABI specifier).

**Comment by JeffBezanson** [comment]
`serialize(io, x)` and `serialize(filename, x)` now write a header; I think this can be closed.
