### ISSUE TITLE
LLVM 3.5 is missing backtraces

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#7910]
Backtraces are somewhat of a mess on 3.5 for a variety of reasons, including that we currently have no way to get the proper load address of a section. To verify, try e.g.:

```
julia> sqrt(-1)
ERROR: DomainError
```

and note the missing backtrace.

**Comment by timholy** [comment]
Just checking, do you know about this? http://llvm.org/bugs/show_bug.cgi?id=20800. Presumably that's already in 3.5 svn. But I thought I should mention it in case it's not. (I was [pointed to this](https://github.com/timholy/IProfile.jl/issues/14#issuecomment-68598426) by a Crystal developer.)

**Comment by vtjnash** [comment]
All of julia's functions are JIT with frame pointers.

Keno has the patch for this. I think he just need to clean it up some and resubmit it upstream?

**Comment by Keno** [comment]
Yes, I'll take care of it.

**Comment by Keno** [comment]
FWIW, the patch for this is up at http://reviews.llvm.org/D6961, will probably take a bit to get reviewed.

**Comment by tkelman** [comment]
Nice work! LLVM may be branching for 3.6 shortly - http://lists.cs.uiuc.edu/pipermail/llvmdev/2015-January/080380.html, I hope your fixes can get in and stay in this time.

**Comment by Keno** [comment]
Yes, I am awake. I'll go my best to get it in it time for 3.6.

**Comment by Keno** [comment]
For the record, here's also the julia-side patch that goes along with the LLVM one:
```
diff --git a/base/replutil.jl b/base/replutil.jl
index 207f7dd..215991a 100644
--- a/base/replutil.jl
+++ b/base/replutil.jl
@@ -94,7 +94,7 @@ showerror(io::IO, ex::LoadError) = showerror(io, ex, [])
 function showerror(io::IO, ex::DomainError, bt)
     println(io, "DomainError:")
     for b in bt
-        code = ccall(:jl_lookup_code_address, Any, (Ptr{Void}, Cint), b, true)
+        code = ccall(:jl_lookup_code_address, Any, (Ptr{Void}, Cint), b-1, true)
         if length(code) == 5 && !code[4]  # code[4] == fromC
             if code[1] in (:log, :log2, :log10, :sqrt) # TODO add :besselj, :besseli, :bessely, :besselk
                 println(io,"$(code[1]) will only return a complex result if called with a complex argument.")
@@ -246,7 +246,7 @@ function show_backtrace(io::IO, top_function::Symbol, t, set)
     local fname, file, line
     count = 0
     for i = 1:length(t)
-        lkup = ccall(:jl_lookup_code_address, Any, (Ptr{Void}, Cint), t[i], true)
+        lkup = ccall(:jl_lookup_code_address, Any, (Ptr{Void}, Cint), t[i]-1, true)
         if lkup === ()
             continue
         end
diff --git a/src/debuginfo.cpp b/src/debuginfo.cpp
index 1efa5ec..3227229 100644
--- a/src/debuginfo.cpp
+++ b/src/debuginfo.cpp
@@ -70,6 +70,9 @@ struct FuncInfo {
 struct ObjectInfo {
     const object::ObjectFile* object;
     size_t size;
+#ifdef LLVM36
+    const RuntimeDyld::LoadedObjectInfo *L;
+#endif
 #ifdef _OS_DARWIN_
     const char *name;
 #endif
@@ -337,6 +340,9 @@ public:
                 obj.getObjectFile();
 #endif
             ObjectInfo tmp = {objfile, (size_t)Size
+#ifdef LLVM36
+                ,L.clone()
+#endif
 #ifdef _OS_DARWIN_
                 ,strdup(sName.data())
 #endif
@@ -397,6 +403,12 @@ void RegisterJuliaJITEventListener() {
     jl_ExecutionEngine->RegisterJITEventListener(jl_jit_events);
 }
 
+#ifdef LLVM36
+typedef RuntimeDyld::LoadedObjectInfo *pLoadedObjectInfo;
+#else
+typedef void *pLoadedObjectInfo;
+#endif
+
 extern "C" void jl_getFunctionInfo(const char **name, size_t *line, const char **filename, uintptr_t pointer, int *fromC, int skipC);
 
 void lookup_pointer(DIContext *context, const char **name, size_t *line, const char **filename, size_t pointer, int demangle, int *fromC)
@@ -703,16 +715,11 @@ void jl_getFunctionInfo(const char **name, size_t *line, const char **filename,
     std::map<size_t, ObjectInfo, revcomp>::iterator it = objmap.lower_bound(pointer);
 
     if (it != objmap.end() && (intptr_t)(*it).first + (*it).second.size > pointer) {
-#if defined(_OS_DARWIN_)
-        *name = jl_demangle((*it).second.name);
-        DIContext *context = NULL; // current versions of MCJIT can't handle MachO relocations
-#else
 #ifdef LLVM36
-        DIContext *context = DIContext::getDWARFContext(*it->second.object);
+        DIContext *context = DIContext::getDWARFContext(*it->second.object,it->second.L);
 #else
         DIContext *context = DIContext::getDWARFContext(const_cast<object::ObjectFile*>(it->second.object));
 #endif
-#endif
         lookup_pointer(context, name, line, filename, pointer, 1, fromC);
         return;
     }
```
The `-1` in the lookup is because unwind is telling us the return address, but what we really want is the location of the call site, so we need to back up.

**Comment by eschnett** [comment]
This is still a problem on OS X for me (LLVM 3.5.1). In particular, `make testall` fails:
```
exception on 3: ERROR: LoadError: test failed: have_backtrace
 in expression: have_backtrace
while loading backtrace.jl, in expression starting on line 12
	From worker 5:	 in  10.58 seconds
	From worker 2:	     [1m*[0m [31mstatistics          [0m in  13.06 seconds
	From worker 4:	     [1m*[0m [31mbitarray            [0m in 123.03 seconds
ERROR: LoadError: LoadError: test failed: have_backtrace
 in expression: have_backtrace
while loading backtrace.jl, in expression starting on line 12
while loading /Users/eschnett/SIMFACTORY/julia-master/src/julia-f427492e46127a1c132ccef75ab093f275ef2eed/test/runtests.jl, in expression starting on line 42

	From worker 3:	     [1m*[0m [31mbacktrace           [0mmake[1]: *** [all] Error 1
make: *** [testall] Error 2
```
Is this known? The label on this issue only mentions Windows.

**Comment by tkelman** [comment]
Yes, I believe that's known. It's had the mac label since December: https://github.com/JuliaLang/julia/issues/7910#event-207232356

**Comment by staticfloat** [comment]
Just BTW, the [llvm 3.5 nightlies](http://buildbot.e.ip.saba.us:8010/waterfall?category=Nightlies) that I build to keep track of 3.5 fail the backtrace test on Ubuntu as well.

**Comment by nalimilan** [comment]
But that test passes on Fedora rawhide (with system LLVM 3.5): https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-rawhide-x86_64/julia-0.4.0-0.20150121.el7.centos/build.log

**Comment by staticfloat** [comment]
Iiiiinteresting.  So perhaps Fedora system LLVM 3.5 is patched in some way that our LLVM svn is not.

**Comment by Keno** [comment]
There is a feature in LLVM (GDB registration), that masks this failure. It's enabled on Linux systems in LLVM 3.5, but was subsequently disabled.

**Comment by vtjnash** [comment]
i can't reproduce the OS X failure or linux failure on current master (since I closed the issue back on Dec 13, 2014)

**Comment by vtjnash** [comment]
backtrace test on llvm36 on osx is broken because I'm missing a line of code:
````diff --git a/src/debuginfo.cpp b/src/debuginfo.cpp
index 1efa5ec..0787df3 100644
--- a/src/debuginfo.cpp
+++ b/src/debuginfo.cpp
@@ -299,6 +299,10 @@ public:
 #if defined(LLVM36)
             Section->getName(sName);
             Addr += L.getSectionLoadAddress(sName);
+            sym_iter.getName(sName);
+            if (sName[0] == '_') {
+                sName = sName.substr(1);
+            }
 #else
             sym_iter.getName(sName);
             Addr = ((MCJIT*)jl_ExecutionEngine)->getSymbolAddress(sName, true);
```
i'm not sure what broke the code_native function

**Comment by ihnorton** [comment]
master / linux x64 / llvm-svn (just pulled):
```
julia> sqrt(-1)
ERROR: DomainError:

 in show at ./show.jl
```

**Comment by vtjnash** [comment]
as Keno mentioned above, on llvm-svn, the unwinder currently doesn't work properly, since LLVM disabled generation of some debug information

**Comment by vtjnash** [comment]
@Keno what exactly is the remaining bug here? backtraces and whatnot look fine to me on llvm36 on linux & os x (other than that `code_native` prints a few annoying `error: failed to compute relocation: X86_64_RELOC_UNSIGNED` messages)

**Comment by Keno** [comment]
The annoying messages are one (they are harmless assuming you're looking at the relocated version of the debug sections - I'm actually somewhat surprised that you are getting those). There's an off-by one in debuginfo which causes some backtraces to be messed up on MachO (including the originally reported one here).

**Comment by vtjnash** [comment]
how would i know if i am looking at the relocated version of the debug section? everything seems to looks correct...

**Comment by Keno** [comment]
If you are getting non-trivial backtrace (i.e. including frames not from sys.dylib), then everything is fine.

**Comment by vtjnash** [comment]
good call. i forgot that i had to disable line numbers entirely for JIT frames

**Comment by Keno** [comment]
That'd do it ;).

**Comment by Keno** [comment]
I spent basically all of today rebasing the upstream patch and splitting it into two more easily reviewable chunks. Here's hoping that'll speed up review.
