### ISSUE TITLE
Slow vcat for Sparse Matrices

### ISSUE THREAD

**Issue by lruthotto** [JuliaLang/julia#7926]
I found a performance issue when vertically concatenating sparse matrices. Here is a minimal example:
```
N = 1000000;
A = sprandn(N,N,1e-5);
Z = spzeros(N,N);
@time B = [Z;A];
elapsed time: 1.359868004 seconds (915883824 bytes allocated, 31.18% gc time)
```
This should actually be a trivial operation. Note that it is equivalent to:
```
@time Bt = copy(A); Bt.m += N; Bt.rowval +=N;
elapsed time: 0.073445038 seconds (167965824 bytes allocated)
```
Does anyone have an elegant fix for this? I think a speedup here will be quite interesting for many people working with numerical PDEs etc.

**Comment by ViralBShah** [comment]
Turns out this has more to do with type instability than special casing. Submitting a PR soon.

**Comment by ViralBShah** [comment]
With the PR above,

**Comment by lruthotto** [comment]
Amazing! Thanks @ViralBShah! 

I repeated the above example an equivalent system an got and incredible (around 10 times) speedup. Hope this PR gets merged soon. 
```
elapsed time: 0.104847899 seconds (160 MB allocated, 34.00% gc time in 2 pauses with 1 full sweep)
```

**Comment by ViralBShah** [comment]
This is merged.
