### ISSUE TITLE
proposed cleanup of output functions

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#7959]
A proposal to address #5709, #6493, #4117, #3932, and similar, discussed with @JeffBezanson and @stevengj today:

1. Rename `writemime(io, m::MIME, x)` to `write(io, m, x)`

2. Quasi-deprecate `show` in favor of `write`: have `show(io, x)` call `write(io, MIME("text/plain"), x)`, and document overriding `write` as the preferred mechanism to customize output going forward.  But don't actually deprecate `show` until Julia 0.5 or later to minimize package breakage.   (Rationale: `show` is confusing because it sounds like `display`, but it behaves more like `write`.)

3. Add parameters (properties) to `MIME` objects (`show` can then subsume `showall`, `showcompact`, etc with custom-specifiable precisions).   For example, `write(io, MIME"text/plain"(compact=true), x)` instead of `showcompact`.

4. Document a set of standard properties to control display of arrays (compactness), floating-point values (precision), etcetera.

As an implementation detail, we would want a fast way to represent MIME parameters as some kind of associative type in the `MIME` object. Perhaps a simple `Associative{Symbol,V}` type which uses linear search instead of a hash table.   The same type could then be used for keyword arguments.

**Comment by elextr** [comment]
The use of MIME as a parametrised "format specification" object seems like a good one, it can be passed repeatedly without enumerating the args, but maybe it should have a different name to MIME?

**Comment by one-more-minute** [comment]
#9633 is somewhat related.

**Comment by stevengj** [comment]
MIME types are used to specify the format (compactness is part of the format), and MIME types can already carry options.

**Comment by one-more-minute** [comment]
Compactness may be part of the format but it's not part of the mime type. The object you have there isn't a mime type, it's a formatting specification with a mime as a type parameter, `Format{symbol("text/html")}(compact=true)`.

My issue is that this design forces the formatting specification to include a mime type. This makes sense for `writemime`, but it doesn't make sense for other functions like `display`. If I want to display something with the "compact" option, do I have to also choose a mime type? Or does `display` get its own, seperate formatting specification type, specific to that one function?

**Comment by hayd** [comment]
Is/should there be a mime type for writing to the terminal?

**Comment by JeffBezanson** [comment]
We use `text/plain` as the default, so there is always some mime type used for display even if you don't specify one or don't want to.

**Comment by hayd** [comment]
So this is in [display](http://julia.readthedocs.org/en/latest/stdlib/io-network/#Base.display)? It's not clear how "topmost applicable" is decided (what your supposed to do to sneak something higher in their):

> Display x using the topmost applicable display in the display stack, typically using the richest supported multimedia output for x, with plain-text STDOUT output as a fallback.

I see that markdown (for example), overrides `Base.display` to get this them to print in the terminal (with color/formatting), rather than using something like MIME"text/terminal".

**Comment by stevengj** [comment]
Superseded by #14052
