### ISSUE TITLE
Awesome new C backtraces off by 1 line

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#7986]
I'm slow, but I finally groked that I'm actually getting real line numbers from C backtraces (rather than instruction pointer offsets). Presumably I have @Keno to thank. Really nice.

However, I'm finding they may be off by 1. I'm running the flisp tester in #7977. The main time commitment in `fl_map1` is a call to `_applyn`, but the line numbers in my backtraces are to the next line (the `POPN`).

**Comment by vtjnash** [comment]
i think this should be fixed now. we had an off-by-one error in the ip used for stacktrace lookup.
