### ISSUE TITLE
sinc(π) not defined

### ISSUE THREAD

**Issue by EthanAnderes** [JuliaLang/julia#7994]
The function sinc doesn't seem to be defined for π.

```
julia> sinc(3.1415926535897)
-0.04359862862916225

julia> sinc(π)
ERROR: `decompose` has no method matching decompose(::MathConst{:π})
 in sinpi at special/trig.jl:2
 in sinc at special/trig.jl:88

julia> sin(π)
1.2246467991473532e-16
```

**Comment by kshyatt** [comment]
So, on latest master...

```julia
julia> sinc(π)
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type Irrational{:π}
This may have arisen from a call to the constructor Irrational{:π}(...),
since type constructors fall back to convert methods.
 in sinpi(::Irrational{:π}) at ./special/trig.jl:159
 in sinc(::Irrational{:π}) at ./special/trig.jl:296

julia> sinc(3.1415926535897)
-0.04359862862916225
```

**Comment by stevengj** [comment]
It seems reasonable to define `convert{T<:Irrational}(::Type{T}, x::Number) = x`.

**Comment by simonbyrne** [comment]
I don't know: defining `convert(::Type{T}, x)` to give something that isn't of type `T` seems dangerous.

**Comment by StefanKarpinski** [comment]
Hmm. This is a pretty tricky issue. We really want `one(pi)` to give a non-Irrational.

**Comment by martinholters** [comment]
According to `?one`, `one(π)` should give "the multiplicative identity element for the type of" π. I don't think we have that at the moment (`1*π == 1.0*π ≠ π`). That would leave introducing `Irrational{1}` (or maybe a more appropriately named singleton type, say `One`) with correspondingly overloaded `*`. I'm not sure we want to go down that road, though.

**Comment by fredrikekre** [comment]
#21781
```julia
julia> sinc(π)
-0.04359862862918775
```
