### ISSUE TITLE
clamp function should check that "lo" < "hi"

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/julia#8006]
Hi, 

playing around in math.jl I found that the clamp function does not check that "lo" is less than "hi", leading to unpredicted behaviour. For example clamp(5, 6, 4) returns 4, which I regard as a bug.

Cheers, 

Davide

**Comment by vtjnash** [comment]
agreed

**Comment by eschnett** [comment]
There could be a `checked_clamp`, folded into general checked arithmetic that could be made available as a package.
