### ISSUE TITLE
Request: Make Pkg.publish() let me retry with a new password 

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#8019]
When running `Pkg.publish()`, I was asked to provide a password. At first, I didn't realize that it was my login password for github, so I provided the wrong one and got the following:

	julia> Pkg.publish()
	INFO: Validating METADATA
	INFO: Pushing Debug permanent tags: v0.0.4
	INFO: Submitting METADATA changes
	INFO: Forking JuliaLang/METADATA.jl to toivoh
	Enter host password for user 'toivoh':
	ERROR: 401: Bad credentials
	 in error at error.jl:21
	 in token at pkg/github.jl:52
	 in req at pkg/github.jl:61
	 in POST at pkg/github.jl:74
	 in fork at pkg/github.jl:87
	 in pull_request at pkg/entry.jl:290
	 in publish at pkg/entry.jl:357
	 in anonymous at pkg/dir.jl:28
	 in cd at file.jl:20
	 in cd at pkg/dir.jl:28
	 in publish at pkg.jl:57

Could `Pkg.publish` clarify which password it is asking for, and allow me to try to reenter it if authenication fails? Especially since the `INFO: Validating METADATA` part takes quite a long time to run.

Also, before even getting this far, on my first attempt to run `Pkg.publish()` I got

    ERROR: could not spawn `curl --version`: no such file or directory (ENOENT)

since I didn't have `curl` installed (I'm on Ubuntu 14.04). Is there a list of dependencies somewhere?

**Comment by lendle** [comment]
For anyone stumbling on this, `~/.julia/.github/token` is now `~/.julia/v0.3/.github/token`, (or presumably `~/.julia/v0.4/.github/token` also), and deleting it fixed the issue for me.

(I got the `Bad credentials` error with `Pkg.submit`.)

**Comment by jakebolewski** [comment]
Please reopen on PkgDev.jl if this is still an issue
