### ISSUE TITLE
Undocumented function tracker

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#8033]
```
$ make html SPHINXOPTS="-n" #Checks for invalid cross-references
...
```

Some of the warnings thrown by `-n` legitimately refer to functions, types or other objects that lack an entry in the standard library documentation but are referred to elsewhere in the documentation. These are:

- [x] &&
- [ ] `@everywhere`
- [ ] `@fastmath`
- [ ] `@goto`
- [ ] `@inbounds`
- [ ] `@simd`
- [ ] `@vectorize_1arg`
- [ ] `@vectorize_2arg`
- [ ] AbstractArray
- [ ] AbstractString
- [ ] Any
- [ ] Base
- [ ] Base.Meta.show_sexpr
- [ ] Base.Profile
- [ ] Bool
- [ ] Char
- [ ] Cholesky
- [ ] CholeskyPivoted
- [ ] ClusterManager
- [ ] Cmd
- [ ] Complex
- [ ] DataType
- [ ] Date
- [ ] DateFunction
- [ ] DateTime
- [ ] Day
- [ ] Diagonal
- [ ] DivideError
- [ ] DomainError
- [ ] Eigen
- [ ] Exception
- [ ] Expr
- [ ] Float16
- [ ] FloatingPoint
- [ ] GeneralizedSVD
- [ ] Hermitian
- [ ] Hessenberg
- [x] I
- [ ] IOStream
- [ ] InexactError
- [ ] Int
- [ ] Int128
- [ ] Int16
- [ ] Int32
- [ ] Int64
- [ ] Int8
- [ ] Integer
- [ ] InterruptException
- [ ] LU
- [ ] LUTridiagonal
- [ ] LocalManager
- [ ] LowerTriangular
- [ ] MONTHTOVALUE
- [ ] MONTHTOVALUEABBR
- [ ] Matrix
- [ ] MemoryError
- [ ] Millisecond
- [ ] Module
- [ ] NullException
- [ ] Nullable
- [ ] Number
- [ ] OverflowError
- [ ] Period
- [ ] Process
- [ ] QR
- [ ] QRCompactWY
- [ ] QRPivoted
- [ ] QuoteNode
- [ ] Rational
- [ ] Real
- [ ] Regex
- [ ] RegexMatch
- [ ] RoundNearest
- [ ] SSHManager
- [ ] SVD
- [ ] Signed
- [ ] SparseMatrixCSC
- [ ] StepRange
- [ ] SubArray
- [ ] Symbol
- [ ] Symmetric
- [ ] TimeType
- [ ] Type
- [ ] UInt
- [ ] UInt128
- [ ] UInt16
- [ ] UInt32
- [ ] UInt64
- [ ] UInt8
- [ ] UTF16String
- [ ] UTF32String
- [ ] UmfpackLU
- [ ] UndefRefError
- [ ] UndefVarError
- [ ] UniformScaling
- [ ] Union
- [ ] UnitRange
- [ ] Unsigned
- [ ] UpperTriangular
- [ ] VALUETOMONTH
- [ ] Vector
- [ ] VersionNumber
- [ ] WString
- [ ] WorkerConfig
- [x] ans
- [x] call
- [x] dayname
- [x] istaskstarted
- [x] launch
- [x] manage
- [x] monthname
- [ ] Dates.recur
- [x] Dates.tonext
- [x] Dates.toprev

[updated 2015-01-18]

**Comment by JeffBezanson** [comment]
Closing this issue as a bit stale; we should always be on the lookout for undocumented functions.
