### ISSUE TITLE
Dates test hang intermittently

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#8041]
I've heard a few reports of this now from @tkelman and @StefanKarpinski at least. I think I may have seen this a while ago when developing Dates.jl as a package, but I don't think I've seen it for a long time. It'd be great to nip this in the bud and figure out what's going on. Does anyone have a reproducible case or can narrow it down to a file or platform?

**Comment by jakebolewski** [comment]
@quinnj can these tests be uncommented now?

**Comment by quinnj** [comment]
Definitely worth trying. I can probably try some testing in a little bit.

**Comment by IainNZ** [comment]
FWIW, Dates.jl (the 0.3 package) still hangs intermittently:
http://pkg.julialang.org/?pkg=Dates&ver=release ->  Show version and test history

**Comment by yuyichao** [comment]
So is this the same with https://github.com/JuliaLang/julia/issues/7942 ?

**Comment by IainNZ** [comment]
I've only ever witnessed this on Linux, http://pkg.julialang.org/?pkg=Dates&ver=release happens fairly often

**Comment by quinnj** [comment]
Has anybody seen this in any form or fashion recently?

**Comment by tkelman** [comment]
Didn't we comment out a set of these tests?

**Comment by quinnj** [comment]
Yep: https://github.com/JuliaLang/julia/blob/bcb4ec7d65a32253a6334e9d4fbf543a8d81388e/test/dates/types.jl#L150

**Comment by tkelman** [comment]
I doubt anybody has been testing this with those tests locally uncommented, but we could put them back on master and see what happens.

**Comment by tkelman** [comment]
Something is occasionally freezing but I don't think it's these. Every time I've checked the logs of a timed-out build that froze somewhere it looked like the dates tests completed fine and that worker moved on to other things. Closing unless anyone sees this definitively in the dates tests.

**Comment by quinnj** [comment]
Sounds good to me.
