### ISSUE TITLE
Breaking compatibility with fortran-only BLAS interfaces

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#8062]
We seem to have broken compatibility with fortran-interface-only BLAS libraries.  Specifically, we use `cblas_zdotc_sub` and `cblas_cdotc_sub`, which don't exist in some BLAS implementations such as CentOS 7's default `blas` package.  Is this something we want to work around, revert, or just live with?

**Comment by tkelman** [comment]
Maybe we should revisit whether it's worth calling blas for dot?

**Comment by ViralBShah** [comment]
Pretty sure we can avoid calling blas for dot.

**Comment by andreasnoack** [comment]
On my machine, a Julia `dot` seems to be uniformly faster for `Float64` relative to OpenBLAS but slightly slower for `Complex{Float64}`.
```jl
julia> x, y = complex(randn(n), randn(n)), complex(randn(n), randn(n));

julia> @benchmark BLAS.dotc($x, $y)
BenchmarkTools.Trial:
  samples:          7014
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  96.00 bytes
  allocs estimate:  1
  minimum time:     685.01 μs (0.00% GC)
  median time:      698.54 μs (0.00% GC)
  mean time:        711.15 μs (0.00% GC)
  maximum time:     2.35 ms (0.00% GC)

julia> @benchmark mydot($x, $y)
BenchmarkTools.Trial:
  samples:          5424
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  0.00 bytes
  allocs estimate:  0
  minimum time:     867.69 μs (0.00% GC)
  median time:      884.09 μs (0.00% GC)
  mean time:        919.84 μs (0.00% GC)
  maximum time:     2.27 ms (0.00% GC)
```
It's not much and hopefully we can improve the Julia version a bit so think it's fine to switch.

**Comment by mcg1969** [comment]
Is the native Julia dot implementation multithreaded?

**Comment by KristofferC** [comment]
No but AFAIU memory  is usually the bottle neck

```jl
julia> Base.BLAS.set_num_threads(1)

julia> @time dot(a,a);
  0.088142 seconds (5 allocations: 176 bytes)

julia> Base.BLAS.set_num_threads(4)

julia> @time dot(a,a);
  0.088902 seconds (5 allocations: 176 bytes)
```

**Comment by KristofferC** [comment]
No, but neither is OpenBlas's IIRC

**Comment by mcg1969** [comment]
Ah, fair enough. You might want to ask the Numba developers though---I seem to remember they found circumstances where BLAS dot had some advantages, at least for certain vector sizes. I can't recall why.

**Comment by andreasnoack** [comment]
I don't the complex Julia version vectorizes as well as it should.

**Comment by eschnett** [comment]
I looked for a manually vectorized version in OpenBLAS, but couldn't find any. I assume that it just uses a plain Fortran loop, and that that Fortran code is then well vectorized. Is that a difference between GCC and LLVM? Or is there something in our complex multiplication or complex conjugation definitions that prevents vectorization? Does it vectorize if we use `@fastmath`?

**Comment by Sacha0** [comment]
Unlikely to receive attention prior to 0.6. Best!

**Comment by ViralBShah** [comment]
Referring to the original post, I think we are going to keep what we have and it hasn't been an issue for a while. Closing and suggest reopening if necessary.
