### ISSUE TITLE
@__LINE__ (c.f @__FILE__)

### ISSUE THREAD

**Issue by chtlp** [JuliaLang/julia#8066]
Hi, I want to get the file and line number (in the same spirit to `__file__` and `__file__` macro in C) for logging so I can quickly determine where the message was logged. `show_backtrace()` has this information, but is there a way of getting the fields without parsing the string, so I can use this efficiently for logging?

**Comment by mlubin** [comment]
Bump. In JuMP we do tons of code generation, and without this macro it's very hard to give useful backtraces and error messages.
Ref JuliaOpt/JuMP.jl#441

**Comment by ihnorton** [comment]
Another possible hack:
```
macro __LINE__()
    return :(unsafe_load(Ptr{Int}(cglobal(:jl_lineno))))
end
```

**Comment by vtjnash** [comment]
> Another possible hack:

that hack assumes macro-expansion is occurring during parsing, which it often doesn't

**Comment by simonster** [comment]
@vtjnash doesn't `@__FILE__` also assume that?

**Comment by vtjnash** [comment]
no, since `@__FILE__` only works from `Base.include`

but also, yes, since `@__FILE__` only works from `Base.include`
