### ISSUE TITLE
segfault running RunTests test suite in master (not in 0.3.0 release)

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#8093]
I just tried running `test/runtests.jl` from the RunTests package and got a segfault on the latest master:

Version 0.4.0-dev+299 (2014-08-22 10:01 UTC)
Commit 3e30c5a (0 days old master)
x86_64-apple-darwin13.3.0

It's happening consistently, and it does not segfault when I run the tests with the 0.3.0 release.

I'm not sure where exactly the segfault is popping, but perhaps someone with better knowledge of Julia internals will be able to read the backtrace more easily:

https://gist.github.com/ssfrr/0eba235321a21fac1e93

**Comment by vtjnash** [comment]
i don't see any practical way to reproduce this now. it seems the expression in one of the Failure objects was corrupt from the original backtrace (from line https://github.com/JuliaLang/julia/commit/04d1648ba1df91036f59b0f70896e764add9495e#diff-bef5fc2625b92f0ae308eb13927125abR25), but that it will probably not be reproducible anymore (RunTests.jl looks to have been unmaintained for a little over a year now)

**Comment by vtjnash** [comment]
actually, updating it to v0.4 wasn't hard at all. i believe the segfault was due to a change to the serializer – regenerating the serialized "expected output" files seemed to fix the issue.
