### ISSUE TITLE
remove importall Base.Operators

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#8113]
it's rather annoying that `importall Base.Operators` is the default. It came up recently on the mailing list, but also came up recently in my own work. The workaround (baremodule), requires a lot of boilerplate (and some like `eval` is rather mysterious). The need for workarounds also make it difficult to use the redefined function outside of the module (via export).

**Comment by JeffBezanson** [comment]
I think we should do this. The compatibility story couldn't be easier: just add `importall Base.Operators` at the top of a module and it will work on 0.3 and 0.4.

**Comment by StefanKarpinski** [comment]
Seems reasonable to me. The current situation means you can't actually define your own operators.

**Comment by toivoh** [comment]
+1 (again)

**Comment by JeffBezanson** [comment]
One possible exception: `call`. It's the only function you can add methods to without realizing it.

Either that or we need to adopt the proposal in #11452.

**Comment by StefanKarpinski** [comment]
I'm still not sure but @vtjnash's proposal has something appealing about it. I have yet to come up with a really convincing argument that makes it a slam dunk for me though.

**Comment by JeffBezanson** [comment]
The basic problem is that it extends our data model at a very low level, with an operation `moduleof(x)` that applies to all values and is used for dispatch. It's like a second `typeof`.
