### ISSUE TITLE
edit doesn't work with EDITOR set to 'emacsclient -t' (or other values with options)

### ISSUE THREAD

**Issue by stoolye** [JuliaLang/julia#8120]
An example:
```shell
export EDITOR='emacsclient -t' # or other values with options, like 'emacs -nw'
```
edit function throws an error.
```julia
julia> edit(+)
ERROR: could not spawn `'emacsclient -t' +36 /usr/bin/../share/julia/base/bool.jl`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:217
 in spawn at process.jl:348
 in edit at interactiveutil.jl:35
 in edit at interactiveutil.jl:54
```

Apparently, `edit` considers `emacsclient -t` as a whole file name.

In `base/interactiveutil.jl`,
```julia
if beginswith(edname, "emacs")
    spawn(`$edpath +$line $file`)
```
Simply wrapping `edpath` with `shell_split` fixes this problem.
```julia
if beginswith(edname, "emacs")
    spawn(`$(shell_split(edpath)) +$line $file`)
```
And it also works in the case of path with spaces, as long as you set EDITOR properly. For example,
```shell
export EDITOR='/path\ with\ spaces/emacs -nw'
```
I don't see any drawbacks so far. In fact, I'm wondering why not just wrap every `edpath` with `shell_split`.
Do I miss something?

**Comment by nolta** [comment]
Fixed by #13032
