### ISSUE TITLE
Feature request: allow download() to not overwrite existing target

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#8147]
I find myself writing 

```julia
isfile(fname) || download(URL, fname)
```

all the time, and it would be nice if we could pass `download` a flag to skip the download if the target `fname` already exists.

**Comment by ihnorton** [comment]
Can this be closed? The decision in #8148 seems to have been to leave it as-is.

**Comment by jiahao** [comment]
sadly so. I still think we'll need this at some point.

Ref: JuliaLang/BinDeps.jl#135
