### ISSUE TITLE
iterators that don't know they're done until they've tried

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#8149]
There's a fundamental awkwardness to using the start/next/done protocol to iterate things like streams or tasks that can't know if they're done or not until they've tried to get the next item. Currently, we work around this mismatch by advancing the iterator in done instead of in next. This kind of works, but it's pretty awkward and intuitive. It also makes composition of these kinds of iterators fail very badly in some cases (zipping multiple streams, etc.).

The only way around this is for `next` to have two exit routes: normal return of the next value and "abnormal" return when the stream has gone dry. Python handles this by with exceptions: when a generator is done, it throws one. This does not have sufficiently good performance for Julia, however. Another option would be to use a special sentinel return value to indicate that iteration has finished and there's no value to be had. To use this approach, we'd need to make sure the compiler is clever enough to optimize this type instability away and produce fast code.

Another option would be to use exceptions like Python does, but not always use exceptions. It's worth noting that when you're iterating over something like a stream or a task, it is often the case that you want to do some kind of cleanup – e.g. closing a file handle – if the iteration exits via some error.

**Comment by aaronsheldon** [comment]
The design pattern I use in this situation is to introduce a 1 step phase offset between the state and the data produced. This means that between loop start and the first item being delivered there are at most two tries made. But after that everything proceeds as normal. In the context of tasks the pattern would be

    start(x::tasks)
        ...
        get the state from advancing the first task
        ....
        return the state
    end
    next(x::tasks, y::state)
        ....
        get the result from the state
        ...
        get the state from advancing the next task
        ...
        return the result and the state
    end
    done(x::tasks, y::state) = check for valid state and tasks

**Comment by JeffBezanson** [comment]
Subsumed by #18823.
