### ISSUE TITLE
Document assignment syntax

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#8191]
I believe the documentation does not describe the syntax of the assignment operator. From examples, I know that e.g.

```
a,b = 1,2
```

is possible. However, I don't know whether this is a special syntax for assignment, or whether LHS and RHS are implicitly interpreted as tuples.

I found out the hard way that writing

```
(a,b) = x
```

interprets x as iterable, leading to a very strange error about a method "start" when x returns a value that is not iterable. Apparently, assignment to a tuple can automatically convert e.g. from lists -- naively, I would have expected that I have to call a function for this.

I also found out that

```
(a,) = (1,2)
```

is possible, and silently discards the additional value. I would have expected a warning in this case.

Finally, I somehow expected that "_" (using an underscore as variable name) is a placeholder that I can use to discard values, as in

```
(a,_) = (1,2)
```

However, this instead creates a local variable called "_".

Since I did not expect these behaviours, others may be surprised as well. It would be good to describe them in the documentation.

**Comment by Moelf** [comment]
Do we know where would be a good place / keywords to document this?

**Comment by laborg** [comment]
This has been documented in https://github.com/JuliaLang/julia/pull/30745
