### ISSUE TITLE
handle undefined identifiers at help prompt

### ISSUE THREAD

**Issue by Wilfred** [JuliaLang/julia#8262]
At the moment, we're not very helpful if a user gets a function name wrong. 

```
help?> i_dont_exist
ERROR: i_dont_exist not defined
```

We could either fall back to calling apropos() automatically, or at least suggest it in the error message. This would benefit from apropos searching function names, so `foobar("my_function")` would work, and perhaps even `foobar("my_funct")` too.

**Comment by jakebolewski** [comment]
Closing, as the default help behavior seems reasonable now.
