### ISSUE TITLE
Documentation: Unit and Functional Testing

### ISSUE THREAD

**Issue by tvw** [JuliaLang/julia#8263]
Should be rewritten. The documentation does not give me any clue, how to setup and write tests for my project. Here the thoughts, which came into my mind, when reading the documentation:

One example:

```
julia> @test 1 == 0
ERROR: test failed: 1 == 0
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39
```

What does this example help me? It only shows, that the test macro throws an error, when the expression does not return true. The error trace it gives, refers only to the code in the test module. It does not tell me anything useful about my code.

I expect a test to test some code against an expected result. When the result differs from the expected result, it should show me the test, the result and the expected result.

```
Another macro is provided to check if the given expression throws 
an exception of type extype, @test_throws():

julia> @test_throws BoundsError error("An error")
ERROR: test failed: error("An error")
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test_throws at test.jl:55
```

What the hack does this code tell me? The introduction to this example tells me, what it should check: a given expression throws an expected exception. The error message tells me, that the test 'error("An error")' failed. But  'error("An error")' is not a test but an expression, which can appear in many tests, if you do intensive testing. That it once failed, does not help me, as long as I do not know, what the test was.

At least at that point, I am already somewhat disappointed. But there is a little hope:

```
julia> @test_approx_eq_eps 1. 0.999 1e-3
ERROR: assertion failed: |1.0 - 0.999| <= 0.001
  1.0 = 1.0
  0.999 = 0.999
  difference = 0.0010000000000000009 > 0.001
 in error at error.jl:22
 in test_approx_eq at test.jl:68
```

Here the error still does not tell me, what the test was, but it at least gives me a clue, what it did expect.

You might now argue, that you can see the test in the prompt line of the repl. But when you write tests, you do not type them into the repl and as a reader I know that. If I am new to this topic, I will never understand, why I should use a macro `@test`, when I could just do the following in the repl:

```
julia> 1==1
true
```

This is much easier to understand and a very good test, when you are testing in the repl alone.

The section 'Handlers' section now tells me, that I can improve the output. But it does not tell me, why the hack my tests stop when the first error is detected (I already wrote a few tests into a file based on the code in the documentation, because I do not want to retype them into the repl again and again).

After reading 'Macros', I ask myself, does this documentation only show entry points to write my own test package and not much more? I expected more, when I read the chapters headline.

But no, at the end you read: I can test Base Julia with it. I hope, someone else did run those tests already, but what about my code?

After reading all that, I have no clue, how to quickly setup testing and write some tests for my project. I am new to Julia and writing tests would be a good help, to understand my own code.

What would I expect from the documentation:

(0. A very short summary, what are unit and functional tests are about, when I am not only new to julia but also to this topic.)
1. How to organize my tests in my project in the filesystem
2. How to run them outside the repl
3. How to run them automatically again and again, when the code changes in files
4. How to define tests, which gives me proper and helpful result messages and not only, "there was something wrong somewhere".
5. A reference to the full documentation of Base.Test (I have not found it yet, but I guess, there must be more, after reading this documentation)

[pao: replace straight single quotes with backtick quotes for macro name]

**Comment by KristofferC** [comment]
I think https://docs.julialang.org/en/latest/stdlib/Test/ closes this.
