### ISSUE TITLE
Possibility of simplifying temp file/dir handling?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#8287]
I was reading http://neovim.org/news/2014/sept/ and saw

> Cross Platform Temporary Filenames
> 
> The function to create temporary files in Neovim needed features that weren’t in libuv.
> 
> @Hinidu, one of Neovim’s contributor, sent a pull request to libuv to add a new function, uv_fs_mkdtemp. The changes (now part of libuv version 0.11.27) are being used by Neovim to provide temporary file/directory creation and the changes work across platforms.
> 
> Because the cross-plaform code has been contributed to libuv, all libuv-based projects can benefit from the changes.

Perhaps an up-for-grabs issue for someone wanting to get into Julia internals a bit?

**Comment by kshyatt** [comment]
I don't really know much about what's going on in this old issue - @IainNZ and @vtjnash is this still worth looking at?

**Comment by vtjnash** [comment]
Might be useful for looking into https://github.com/JuliaLang/julia/issues/9053, but otherwise isn't particularly critical for anything (since we already wrote cross-platform mkdtemp support)

**Comment by StefanKarpinski** [comment]
Seems like a feature, therefor post 1.0.

**Comment by StefanKarpinski** [comment]
Seems like this is done already.
