### ISSUE TITLE
Add Pkg.untag() command

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#8289]
Currently, undoing a `Pkg.tag` is a manual process:

1. delete local tag in package repo (`git tag -d v0.0.2`)
2. delete remote tag (`git push origin :refs/tags/v0.0.2`)
3. undo METADATA changes (`git reset --hard <last-good-commit>`)

It would be nice to formalize these steps into a `Pkg.untag` command (possibly in a safer manner, at least for step 3).

**Comment by tawheeler** [comment]
What about something that simply retags and pushes to an open METADATA PR? Maybe `PkgDev.updatepr()` or `PkgDev.republish()`

**Comment by tkelman** [comment]
moved to https://github.com/JuliaLang/PkgDev.jl/issues/76
