### ISSUE TITLE
sortperm does not respect the sorting algorithm specified

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#8293]
The fix to issue #6177 (dealing with floating point algorithms mainly AFAICS)  breaks the invariant one expects, e.g.:

```
a = rand(MyType, 100)
@assert a[sortperm(a, alg=QuickSort)] == sort(a, alg=QuickSort)
```

At least the docs should be updated to say that `sortperm` currently can only do a stable sort (which happens to be based on `QuickSort`).
ps: I already have a branch having this test in test/sorting.jl for when a fix is implemented :)

**Comment by udohjeremiah** [comment]
Is this still an issue?👀

Because the current docs says `sortperm` only does a stable sort:

```julia
help?> sortperm
search: sortperm sortperm! partialsortperm partialsortperm! isconcretetype

  sortperm(v; alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)

  Return a permutation vector I that puts v[I] in sorted order. The order is
  specified using the same keywords as sort!. The permutation is guaranteed to
  be stable even if the sorting algorithm is unstable, meaning that indices of
  equal elements appear in ascending order.

  See also sortperm!, partialsortperm, invperm, indexin.
```
