### ISSUE TITLE
Failed to compile with Intel compilers 

### ISSUE THREAD

**Issue by bdeonovic** [JuliaLang/julia#8294]
Tried compiling with intel MKL and intel compilers (not sure if issue has to do with those though). Make errored out with this:

```
fround.c(57): error: identifier "LONG_MAX" is undefined
      if(x < (double) LONG_MAX) { /* in <limits.h> is architecture dependent */
                      ^

compilation aborted for fround.c (code 2)
make[3]: *** [fround.o] Error 2
make[2]: *** [Rmath/src/libRmath-julia.so] Error 2
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2
```

**Comment by y9KAaixxegjR** [comment]
Just to keep this compile-with-intel issue alive, using 
USEICC=1
USEIFC=1
still gives me the following error
*** USE_LIBCPP only supported with clang. Try setting USE_LIBCPP=0.  Stop.

**Comment by tkelman** [comment]
I believe we've fixed the openspecfun problem from https://github.com/JuliaLang/julia/issues/8294#issuecomment-56570382 - set `USE_LIBCPP = 0` like the message said and you'll probably hit #9656 this time.

**Comment by y9KAaixxegjR** [comment]
Setting USE_LIBCPP = 0 in Make.user does not seem to change the error message. My Make.user file now looks like 
USEICC = 1
USEIFC = 1
USE_INTEL_MKL = 1
USE_INTEL_MKL_FFT = 1
USE_INTEL_LIBM = 1
USE_LIBCPP = 0

but I get the same message
julia/Make.inc:314: *** USE_LIBCPP only supported with clang. Try setting USE_LIBCPP=0.  Stop.

Should I actually go into the Make.inc file to make changes?

**Comment by tkelman** [comment]
We may have the logic wrong somewhere. Or you may need to use `override USE_LIBCPP = 0`

**Comment by ViralBShah** [comment]
How easy would it be to add an icc target to Travis?

**Comment by tkelman** [comment]
You'll have to ask Travis that. Or maybe someone at Intel. I'm assuming there isn't exactly a downloadable tarball option for the whole Intel toolchain, last time I remember setting it up on Linux it was a non-trivial installation process.

What would be much more tractable would be installing icc, ifort and mkl on one of Elliot's buildbot VM's. With https://github.com/staticfloat/julia-buildbot/issues/1 we could even try to make it send github statuses for commits to master at least.

**Comment by ViralBShah** [comment]
I think we can make our own tarball, so long as we use our license.

**Comment by tkelman** [comment]
Generally I thought the compilers themselves are not going to be redistributable, only the libraries.

**Comment by ViralBShah** [comment]
I thought that as a licensed user, we can install the compiler on any machine of our choice. The licenses are per developer, and so long as we have a valid license, we can have a tarball that puts the compiler in /opt along with the license, and then uses it in the travis run.

**Comment by tkelman** [comment]
If that's how the license works, then I guess it's worth trying. But presumably we'd need to upload the tarball somewhere private and access-controlled rather than publicly visible to the entire internet, and use a secure key on Travis to download the file.

**Comment by ViralBShah** [comment]
This is my interpretation, of course. Would love to hear what others have to say.

**Comment by nolta** [comment]
With intel 15.0.2 all the tests pass (on centos6).

**Comment by ViralBShah** [comment]
Maybe we just make 15 the minimum release we support.
