### ISSUE TITLE
fork support

### ISSUE THREAD

**Issue by wavexx** [JuliaLang/julia#8295]
I was trying to look into how much work would be to support fork() in julia as a first class operation.
fork would be needed for higher performance mutli-processing #7616, #985 thanks to a shared initial memory state.

I'd like to discuss 2 things here: what the fork semantics should be and the actual implementation details.

What should be the state of open file descriptors after a fork? Similarly, what should be do with current tasks?

Ideally fork would return pid, stdout and stderr to the forked process, while adding the PID to the current list of managed processes. The list of pending tasks would be reset on the child process (as you obviously don't want to continue tasks in the new environment), as for the list of managed processes (as there would be 2 processes managing the same pids). File descriptors coming from libuv are already marked FD_CLOEXEC, so there should be nothing much to do here.

libuv doesn't support forking (there's no uv_fork). However, re-initializing libuv from scratch on the child process looks do-able if we also aim to reset any pending task anyway.

Is there anything that's escaping me?

**Comment by vtjnash** [comment]
it's worth noting here that C doesn't even support `fork` (http://man7.org/linux/man-pages/man2/fork.2.html)

**Comment by wavexx** [comment]
On Fri, Mar 25 2016, Jameson Nash <notifications@github.com> wrote:
> it's worth noting here that C doesn't even support fork
> (http://man7.org/linux/man-pages/man2/fork.2.html)

I'm not sure I follow.

**Comment by vtjnash** [comment]
> After a fork(2) in a multithreaded program, the child can safely
          call only async-signal-safe functions (see signal(7)) until such
          time as it calls execve(2).

**Comment by wavexx** [comment]
On Fri, Mar 25 2016, Jameson Nash <notifications@github.com> wrote:
>     After a fork(2) in a multithreaded program, the child can safely
>     call only async-signal-safe functions (see signal(7)) until such
>     time as it calls execve(2).

Well, yes, but it's a bit of a stretch.

But does this hint that we're getting true multithreaded runtime support
instead? ;)

**Comment by yuyichao** [comment]
We're already using many libraries with true multihread support.

**Comment by giordano** [comment]
I know that this issue has been closed as won't fix, but I'd like to point out that supporting `fork` would most probably make [`Cuba.jl`](https://github.com/giordano/Cuba.jl) package support parallelization and greatly speed-up computation of numerical integrals, see giordano/Cuba.jl#1 (at least I suspect this, I'm not 100% sure)

**Comment by Keno** [comment]
`fork` is not the correct way to go about parallelization. The same should be easily achievable by using threads.

**Comment by giordano** [comment]
I don't have much choice.  The [C library](http://www.feynarts.de/cuba/) on which `Cuba.jl` is based makes use of `fork`.

**Comment by Keno** [comment]
What's the reason it uses `fork` over threads? Are there global buffers that get clobbered?

**Comment by giordano** [comment]
The parallelization model used in `Cuba` is described in this paper: https://arxiv.org/abs/1408.6373  Quoting from page 1:
> Cuba uses `fork`/`wait` rather than the `pthread*` functions. The latter are slightly
> more efficient because parent and child share their memory space, but for the same reason
> they also require a reentrant integrand function, and the programmer may not have control
> over reentrancy in all languages (e.g. Fortran’s I/O is typically non-reentrant). `fork` on the
> other hand creates a completely independent copy of the running process and thus works
> for any integrand function.

**Comment by Keno** [comment]
That's an understandable reason, but that fails to take into account that many programs can't be `forked` in general (in particular all multithreaded programs). Ideally the library should provide both options (or even better have hooks to bring your own).

**Comment by lilinjn** [comment]
One (potentially) very nice application of `fork` in julia would be the following "flow" for interactive visualizations and audio (or anything else that could benefit from a programmable "realtime infinite runloop"  that is typically difficult in a single threaded environment like julia)

-  as normal in a repl, load data, define functions, etc specific to your domain
-  when you need to visualize/interact -- create a lambda that knows how to "render" (via gl, etc)
-  `fork`, and go long your merry way in the parent process
- The child process however will create a gl window(or whatever) and then enter into an infinite runloop, in which it periodically renders using the lambda carefully prepared by the parent.  If the interactivity is provided by a native api (e.g. glfw gives keypresses and mouse events) then lib_uv being in a broken state no longer matters (though it would be nice to do things more cleanly if possible)

"`fork` and spin" might be an apt name for this strategy.  

In any case, my point is that `fork` may not be the proper approach to all parallelism, but `fork` is a magic super power, particularly in a repl world, and should be guarded carefully and used liberally (if you ❤️ system images (and how could you not?), then you must ❤️ `fork`!)

Obviously, I like to write flippantly, but hopefully there's something useful here.   

cheers, nehal
