### ISSUE TITLE
Export dotu with generic fallbacks

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#8300]
I have the following inconsistency in Julia v0.3.0:

julia> BLAS.dotu([1.+im,2.],[3.,4.+im])
11.0 + 5.0im

julia> BLAS.dotu([1.,2.],[3.,4.])
ERROR: `dotu` has no method matching dotu(::Int64, ::Array{Float64,1}, ::Int64, ::Array{Float64,1}, ::Int64)
 in dotu at linalg/blas.jl:156

**Comment by KristofferC** [comment]
Explicitly calling BLAS functions is an "expert" feature and they should confirm to the argument types that the BLAS functions themselves take.
