### ISSUE TITLE
Global llvmcall statements

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#8308]
I'm using `llvmcall` to hook-up certain intrinsics to Julia, but ran into the issue that intrinsics need to be declared, and this is currently not supported (for example, see [this thread](https://groups.google.com/forum/#!topic/julia-dev/X0k-AErZBYk)). I have two possible solutions for this problem, but I'd like some feedback before cleaning it up and sending a PR.

My first idea was to do as @keno proposed, automatically adding declarations for intrinsics. This proved messy, because I could not find a way to use the existing LLVM parsing machinery because of the missing declarations immediately aborting the parser/lexer. Duplicating this functionality seems hopeless, especially for complex declarations (`addrspace` annotations, function pointers, ...). Anyway,  for very simple declarations it looked like this:
```c++
// Parse identifiers in the assembly
llvm::StringRef irstring(jl_string_data(ir));
llvm::SmallVector<StringRef, 2> Matches;
llvm::Regex re("[a-zA-Z_0-9]+ @[a-zA-Z$._][a-zA-Z$._0-9]*");
if (re.match(irstring, &Matches)) {
    for (llvm::SmallVector<StringRef, 2>::const_iterator MI =
        Matches.begin(), ME = Matches.end(); MI != ME; ++MI) {
             std::pair<llvm::StringRef, llvm::StringRef> Identifier =
                 MI->split(' ');
             llvm::Type *T =
                 llvm::StringSwitch<llvm::Type*>(Identifier.first)
                     .Case("i32", Type::getInt32Ty(getGlobalContext()))
                     .Case("float", Type::getFloatTy(getGlobalContext()))
                     .Case("double", Type::getDoubleTy(getGlobalContext()))
                     .Default(NULL);
             if (T == NULL)
                 jl_error("Unknown type in LLVM assembly");
             parent_Module->getOrInsertFunction(
                 Identifier.second.substr(1), T, NULL);
         }
}
```

What seemed like a more flexible solution, is to extend `llvmcall` such that the user can pass arbitrary declarations, which get pasted before the function definition when called for the first time. By allowing the `ir` argument to be a tuple of `(decls, ir)`, this is backwards compatible. Disadvantage: the addition of global state, to check whether a certain (arbitrary) declaration has been added already (because redeclaring identifiers is invalid, and trips the parser). I haven't found another way of checking whether certain declarations have been added to the module already (or we'd need to parse the declarations). This allows using `llvmcall` as follows:
```julia
sync_threads() = Base.llvmcall(
  ("""declare void @llvm.nvvm.barrier0()""",
   """call void @llvm.nvvm.barrier0()
      ret void"""),
  Void, ())
```

Any comments?

**Comment by ihnorton** [comment]
> how would it check whether certain declarations have already been added to the module?

[Module::getNamedValue](
http://llvm.org/docs/doxygen/html/classllvm_1_1Module.html#a75391fa576679482ed9195d69101d002)?

**Comment by maleadt** [comment]
#11604 is merged, this can be closed.
