### ISSUE TITLE
var and std do not work for Any[]

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#8319]
All other statistic functions in Base work work for `Any` arrays of numeric values.

``` julia
julia> test = Any[1,2,3]
3-element Array{Any,1}:
 1
 2
 3

julia> std(test)
ERROR: `zero` has no method matching zero(::Type{Any})
 in var at statistics.jl:162

julia> var(test)
ERROR: `zero` has no method matching zero(::Type{Any})
 in var at statistics.jl:162
```

**Comment by stevengj** [comment]
In #4039, I fixed `var` for complex matrices and I added a test case, but it looks like it got broken again when the version for arbitrary iterables was added (since that case was not tested)?

**Comment by oscardssmith** [comment]
Do the recent changes to `var` and `std` make this not an issue?

**Comment by fredrikekre** [comment]
```julia
julia> std(Any[1,2,3])
1.0

julia> var(Any[1,2,3])
1.0
```
