### ISSUE TITLE
why does Pkg.test update other packages?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#8335]
I just noticed this when testing a new package:

```
julia> Pkg.test("LaTeXStrings")
INFO: Testing LaTeXStrings
INFO: LaTeXStrings tests passed
INFO: Upgrading MathProgBase: v0.2.5 => v0.3.0
INFO: Upgrading SHA: v0.0.2 => v0.0.3
```

Why did testing one package upgrade a completely unrelated package?  This seems undesirable.

The `Pkg.test` documentation does not mention that it runs `Pkg.update()`.

cc: @StefanKarpinski

**Comment by KristofferC** [comment]
The answer here seems to be that it needs to resolve after the requirements have changed when test only requirements are removed.
