### ISSUE TITLE
Package Feature Request: optional packages with required versions

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#8342]
In `VideoIO`, `Images` and `ImageView` are [currently listed as requirements](https://github.com/kmsquire/VideoIO.jl/blob/master/REQUIRE).  

This is not strictly true--`VideoIO` will gladly read frames from a video file as `Arrays`, and Simon Danisch recently posted some code which displayed a movie using `GLPlot`, which doesn't require either package.

However, if a user wants to use `Images` or `ImageView`, there are minimum versions required.  So one package feature which would be useful is an optional package with a version requirement.

Thoughts?

Related: #7737

**Comment by kmsquire** [comment]
@StefanKarpinski, does or will `Pkg3` handle this?

**Comment by StefanKarpinski** [comment]
It doesn't yet but there are some tentative plans for adding support for it.

**Comment by KristofferC** [comment]
Subsumed by the "glue package" discussion inhttps://github.com/JuliaLang/Pkg.jl/issues/1285.

**Comment by DilumAluthge** [comment]
For those trying to click the link on mobile: https://github.com/JuliaLang/Pkg.jl/issues/1285
