### ISSUE TITLE
Read jl_compileropts in Base

### ISSUE THREAD

**Issue by sjkelly** [JuliaLang/julia#8372]
In: https://groups.google.com/forum/#!topic/julia-users/TkYi6CJrSVE
I asked how to read from `jl_compileropts` to see if Julia had --code-coverage enabled. I wonder if having some of these options exposed in Base could be useful.

**Comment by jakebolewski** [comment]
This is now in Base.

**Comment by sjkelly** [comment]
Thanks! It still needs docs. I will update my CompilerOptions.jl package accordingly.
