### ISSUE TITLE
Documentation in tarballs

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#8378]
I'm wondering how the manual is supposed to be installed when building from tarballs. At the moment, .rst files are installed, which is pretty useless. To make distribution packages, I need to install files in a convenient format, and remove .rst files, which is ugly.

I can see three solutions:
1. Do not build nor install the manual at all (no .rst).
2. Always build the manual to HTML when calling `make`, and install only HTML files when calling `make install`.
3. Do not build the manual by default (as it requires installing Sphynx), do not install .rst files either, but provide `make` targets to install HTML or any other format.

CC: @sebastien-villemot

**Comment by nalimilan** [comment]
I'm not sure there's a definition of "convenient format", but ATM I'm installing the HTML manual, which seems the most practical to me. Not sure PDF would be very useful.

**Comment by tkelman** [comment]
Is this the same as #9977 ?

**Comment by nalimilan** [comment]
Yeah, this one was more of a question, while the new one is closer to an actual action plan. Let's close this one, I'll work on #9977.
