### ISSUE TITLE
Get remarks back from LLVM vectorizer

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#8392]
Currently, users have now way to tell whether an `@simd` loop vectorized or not, or why it did not happen.  The LLVM 3.5 vectorizer has some capability to emit remarks about whether vectorization happened or not.  Some means of getting these remarks back to Julia developers would be useful.

See also [this discussion](https://groups.google.com/d/msg/julia-users/7qzFjpZUXbE/4dv73bDV-kYJ).

**Comment by KristofferC** [comment]
Ref https://docs.julialang.org/en/v1/devdocs/llvm/#Passing-options-to-LLVM-1

**Comment by vchuravy** [comment]
Also https://llvm.org/docs/Remarks.html

**Comment by KristofferC** [comment]
I think this can be closed based on the presence of `JULIA_LLVM_ARGS`.
