### ISSUE TITLE
try to unreference objects sooner in generated code

### ISSUE THREAD

**Issue by DumpsterDoofus** [JuliaLang/julia#8393]
I originally [posted this on StackOverflow](http://stackoverflow.com/questions/25871711/julia-garbage-collection-inside-functions-works-differently-than-in-global-spac), but calling `gc()` inside of a function does not always appear to work properly. Iain was able to reproduce the issue, and suggested I post it here.

I originally encountered this issue (bug?) when I was running code that I had been pasting into the REPL from a text editor, and decided to instead put the code inside a function in order to make it more convenient to execute. I was surprised to find that the exact same code which executed in the global scope without any problems would swallow up all the available RAM on my computer and give a `MemoryError` when it was wrapped in a function and called. From there, I was able to isolate the issue, giving the minimal example shown in the link above.

**Comment by vtjnash** [comment]
#21888 : The GC root placement pass 1.0 deserves
