### ISSUE TITLE
Installing packages from the shell

### ISSUE THREAD

**Issue by rgbkrk** [JuliaLang/julia#8485]
First off, apologies if this issue is addressed elsewhere. I did some simple searches and couldn't find anything.

Two questions:
1. Is there a way to install packages from the shell (not the Julia REPL) directly? Currently I'm using, e.g. `julia -e 'Pkg.add("IJulia")'`
2. I've noticed that if system dependencies fail to install (lack of sudo), the exit code is still zero when it should demonstrate error.

For 2, this could just be a case of me not knowing an alternate way to install.

**Comment by simonbyrne** [comment]
To revive this: we could have an option `julia --pkg XXX` which is equivalent to calling `XXX` at the Pkg REPL.

**Comment by fredrikekre** [comment]
We have this
```
$ julia -e 'using Pkg; pkg"add Example JSON; rm Example; st"'
```

**Comment by KristofferC** [comment]
```
#!/usr/bin/env julia

import Pkg
Pkg.REPLMode.pkgstr(join(ARGS, " "))
```

```
➜  ~ juliapkg st
    Status `~/.julia/environments/v0.7/Project.toml`
  [6e4b80f9] BenchmarkTools v0.4.0
```

**Comment by KristofferC** [comment]
https://github.com/fredrikekre/jlpkg is imo enough to close this.

**Comment by VikasPoddar** [comment]
> https://github.com/fredrikekre/jlpkg is imo enough to close this.

But it is not officially supported by Julia core package. I think Julia must take a look at these things, look at rust lang ecosystem, how can they are doing great because of great tooling support. I know, Julia is a scientific computing language but still not having same tooling ergonomics make a big no for devlopers.

**Comment by KristofferC** [comment]
I agree and I think 2024 will be a good year for julia apps/cli.
