### ISSUE TITLE
∈ in for loops?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#8487]
I wanted to use the syntax
```
for i ∈ 1:10
```
but discovered that Julia doesn't allow this. Given that `in` and `∈` are identical when used as operators, it would be nice to allow this syntax as well.

**Comment by stevengj** [comment]
+1 ... it seems weird to allow `x ∈ collection` as a synonym for `x in collection`, but not `for x ∈ collection`.

**Comment by malmaud** [comment]
Is there a reason https://github.com/JuliaLang/julia/issues/11223 was closed? It seems like fair game if we're going to start aliasing unicode symbols to keywords.

**Comment by stevengj** [comment]
@malmaud, `\mapsto` is a separate issue; we have already aliased `∈` to `in`, so the meaning of `∈` in Julia is not up for debate.

**Comment by malmaud** [comment]
Well, I thought maybe some of the motivation for closing the \mapsto issue was a reluctance to ever have a unicode symbol usable as a keyword, in which case the fact that ∈ already maps to the operator `in` (but not the syntactic keyword `in`) already might not have been relevant.

**Comment by simonster** [comment]
-1 from me. IMO, we already have one too many ways to write this construct, since `for x in a` and `for x = a` do the same thing. In this case it doesn't even save a character to use `∈`, since you could use `=`. It's just Unicode for Unicode's sake.

**Comment by malmaud** [comment]
You could have said that about using ∈ for the operator `in`. But now that that ship has sailed, wouldn't this bring more consistency?

**Comment by simonster** [comment]
I think there was a better argument for using `∈` for `in`, since it's a notation people actually use in papers, not something we're adding for its own sake. This is just adding a third, less common way to do something you can already do, which imposes some code readability cost on new users. I'd honestly prefer removing the `for x in a` syntax if we're worried about consistency here.

**Comment by stevengj** [comment]
I am worried about consistency.  It's quite hard to explain to people why you can test inclusion by `x ∈ X` or `x in X`, but you can loop with `for x in X` but not `for x ∈ X`.

As for eliminating `for x in X`, I think that ship has sailed.

**Comment by nalimilan** [comment]
Actually, I think Stefan recently said that the `for x = X` syntax (a legacy from MATLAB) was the most likely to go away, if one of them is deprecated at some point. +1 to `in` and `∈`.

**Comment by toivoh** [comment]
I think using `∈` in `for` loops is also pretty close to how it is used in papers. Sure, your regular applied math paper doesn't contain any actual `for` loops, but quite often statements that should be considered for each x ∈ X etc.

**Comment by jakebolewski** [comment]
I also don't really like this proposal either.  This just touches on a pet peeve were people use Unicode when we have perfectly acceptable and universally understandable (editable!) ascii equivalents. We really should just have one for loop syntax that everyone uses.  The for loop `in` is a special form, so it's not equivalent to aliasing an operator like all other unicode defaults.

**Comment by stevengj** [comment]
@jakebolewski, we *already* have a Unicode equivalent for `in` (as an operator).   Are you proposing removing that?   And if not, doesn't the syntactic inconsistency of the two `in` variants bother you?

**Comment by hayd** [comment]
+1 to allowing `for x ∈ X` and deprecating (in the future) `for x = X`.

> This just touches on a pet peeve were people use Unicode when we have perfectly acceptable and universally understandable (editable!) ascii equivalents.

I think this ship has sailed too, unicode :feelsgood:.

**Comment by KristofferC** [comment]
> deprecating (in the future) `for x = X.`

If our main goal is to increase the number of confused matlab programmers on the mailing list, I'm sure we can do better ;)

**Comment by johnmyleswhite** [comment]
I'm also in favor of deprecating `for x = X`.

**Comment by tkelman** [comment]
I don't see a whole lot of value in that, esp for loops over multiple indices written by individuals who would rather not be forced to use unicode, `for i=1:m, j=1:n` is noticeably more concise and readable than `for i in 1:m, j in 1:n`. I usually lean towards syntax consistency being a good thing, but this is just style.

**Comment by mschauer** [comment]
Regarding this issue, I am all for it. The simplest answers to "When can I write ``∈`` for ``in``?" are yes and no. 

It might be interesting to mention how Wikipedia deals with the very related problem of national spelling varieties of English, because it is a similar problem as the one feared by some commenters here and some helpful guidelines could prevent people getting caught in non-productive quarrels: basically to stay consistent with in a file and to respect the preference of the contributor making a substantial initial contribution to a file.
