### ISSUE TITLE
readbytes performs too many read()s

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#8496]
Hi all,

I'm writing commands to and reading data from an external device using julia 0.3, but the `readbytes` function seems to perform one too many read which causes the communication to stall (waiting for a timeout).

Take the following C code:
```c
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/stat.h>

int main() {
        int dev = open("/dev/usbtmc1", O_RDWR);
        write(dev, "*IDN?\n", 6);
        char buf[1024];
        int nb = read(dev, buf, 1024);
        buf[nb] = 0;
        printf("%s\n", buf);
        close(dev);

        return 0;
}
```

Tracing the execution, we see the following syscalls:
```
open("/dev/usbtmc1", O_RDWR)            = 3
write(3, "*IDN?\n", 6)                  = 6
read(3, "Rigol Technologies,DS1052E,DS1ET"..., 1024) = 56
close(3)                                = 0
```
Nice and compact, executing in some milliseconds.

I wrote the following Julia code which I think should behave identically:
```julia
dev = open("/dev/usbtmc1", "r+")
write(dev, "*IDN?")
res = readbytes(dev, 1024)
println(ascii(res))
close(dev)
```

As the documentation states, `readbytes reads at most nb bytes from the stream into b`, so when the initial read returns a number of bytes that is smaller than `nb` I expect Julia to issue no second read... But that does not seem the case:
```
open("/dev/usbtmc1", O_RDWR)            = 14
write(14, "*IDN?", 5)                   = 5
read(14, "Rigol Technologies,DS1052E,DS1ET"..., 131072) = 56
read(14, 0x46a9420, 131072)             = -1 ETIMEDOUT (Connection timed out)
close(14)                               = 0
```
This `ETIMEDOUT` obviously takes quite a while (multiple *seconds*), making this unusable to me.

Have I misinterpreted the documentation, or is this faulty behaviour? If not, how should I use Julia's `read` to avoid a second `read` syscall? I tried to work around this by `ccall`ing into libc, but I can't seem to get a hold of the underlying filehandle, and I don't have much experience with the libuv primitives.

**Comment by hrobotron** [comment]
For other people having trouble with USB-TMC, or SCPI in general -- I did some data acquisition with Julia and the same particular type of oscilloscope. Do not forget to `flush(dev)` after sending the command.
