### ISSUE TITLE
stagedfunction-related compilation error when type inference fails

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#8504]
I've found a case where compiling a function that calls a stagedfunction fails, due to a failure in type inference. If one checks out #8501 (and preferably, inserts a `println(P)` [here](https://github.com/JuliaLang/julia/blob/d4cab1dd127a6e13deae5652872365653a5f4010/base/subarray2.jl#L34)), here's a simple way to reproduce:
```julia
function as_sub(x::AbstractMatrix)
    y = similar(x, eltype(x), tuple(([size(x)...]*2)...))
    @show typeof(y)
    y = sub(y, 2:2:size(y,1), 2:2:size(y,2))
    for j=1:size(x,2)
        for i=1:size(x,1)
            y[i,j] = x[i,j]
        end
    end
    y
end

as_sub(eye(2))
```
This gives the following output:
```julia
julia> as_sub(eye(2))
Array{Float64,N}
Array{Float64,N}
Array{Float64,N}
ERROR: `ndims` has no method matching ndims(::Type{Any})
 in ndims at ./abstractarray.jl:22 (repeats 3 times)
 in setindex! at ./subarray2.jl:35
```
One can see that it fails at compile-time, not runtime: that `@show typeof(y)` never gets called.

A modified version of the function (which declares the type of `y`):
```julia
function as_sub1(x::AbstractMatrix)
    y = similar(x, eltype(x), tuple(([size(x)...]*2)...))::typeof(x)
    @show typeof(y)
    y = sub(y, 2:2:size(y,1), 2:2:size(y,2))
    for j=1:size(x,2)
        for i=1:size(x,1)
            y[i,j] = x[i,j]
        end
    end
    y
end
```
yields this:
```julia
julia> as_sub1(eye(2))
Array{Float64,2}
Array{Float64,2}
typeof(y) = Array{Float64,2}
2x2 SubArray{Float64,2,Array{Float64,2},(StepRange{Int64,Int64},StepRange{Int64,Int64})}:
 1.0  0.0
 0.0  1.0
```

**Comment by StefanKarpinski** [comment]
cc @JeffBezanson, @Keno

**Comment by Jutho** [comment]
Probably related, and also caused by `max_tuple_length` (or whatever it is called) equals 8:
```julia
stagedfunction g(a::Int...)
       N=length(a)
       :(NTuple{$N,Int})
 end
```
Directly
```
@code_typed g(1,1,1,1,1,1,1,1,1,1) # 10 arguments
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:(a::(top(apply_type))(Vararg,Any)::Any::Any)], Any[Any[],Any[Any[:a,(Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64),0]],Any[]], :(begin 
        return (Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64)
    end::Type{(Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64)})))) # 10 Ints, correct
```
but then using this inside a function `h()=g(1,1,1,1,1,1,1,1,1,1)` results in
```
@code_typed h()
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[], Any[Any[:_var0],Any[Any[:_var0,(Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64...),0]],Any[]], :(begin  # none, line 1:
        return (Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64)
    end::Type{(Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64)})))) # Only 8 Ints
```

**Comment by timholy** [comment]
One dirty workaround I've found---though I haven't tested it for tuples of length 8 or higher---is that you can declare
```
g(a::Int...) = _g(a)
stagedfunction _g{TT}(a::TT)
    # blah blah
end
```
and that forces specialization for each tuple-type (TT). But this does required allocation of the tuple, so it's not nearly as good as if we just fixed this issue.

**Comment by Jutho** [comment]
In response to the `module AVDebug` example above, I also noticed the strange behavior regarding inferring the value of `T`. This, however, seems to be solely related to how `eltype` is defined for `AbstractArray`. Note the following
```julia
eltype(AbstractArray{Float64}) #-> Any
eltype(AbstractArray{Float64,TypeVar(:N)}) #-> Any
eltype(AbstractArray{Float64,:N}) #-> Float64
```
So `eltype` returns the correct results as soon as there is a second type parameter, independent of whether it makes sense or not. I guess it wouldn't hurt to add a line
`eltype{T}(::Type{AbstractArray{T}}) = T`
to the existing
`eltype{T,n}(::Type{AbstractArray{T,n}}) = T`
in abstractarray.jl

**Comment by timholy** [comment]
I've been surprised by this before, too, so I'd agree that sounds like a reasonable addition.

**Comment by timholy** [comment]
Hooray!

**Comment by Jutho** [comment]
+1. Was this the last of the remaining bugs with `stagedfunction`s? :-)

**Comment by StefanKarpinski** [comment]
There's still the name bug.

**Comment by mauro3** [comment]
There is also #10178 left
