### ISSUE TITLE
move special functions out of Base?

### ISSUE THREAD

**Issue by nolta** [JuliaLang/julia#8536]
Continuing the discussion in #8294, now that the [amos code has been converted to julia](http://github.com/nolta/SpecialFunctions.jl), do we want to start moving the special functions (e.g., `airy*`, `bessel*`, `hankel*`) out of Base and into a package?

**Comment by ViralBShah** [comment]
@nolta I took your work and updated it for 0.6 (not the translator, but the resulting files).

https://github.com/JuliaMath/SpecialFunctions.jl/pull/52
