### ISSUE TITLE
Can't do `cleanall` build on master (cannot find -lLLVMLTO)

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#8544]
Reporting this in case others have the same problem.

If I do a `make cleanall && make`, I'm getting this on master:
```
    ...
    CC src/profile.o
    CC src/llvm-simdloop.o
    CC src/gc.o
    LINK usr/lib/libjulia.so
/usr/bin/ld: cannot find -lLLVMLTO
/usr/bin/ld: cannot find -lLLVMLineEditor
/usr/bin/ld: cannot find -lLLVMMCAnalysis
/usr/bin/ld: cannot find -lLLVMProfileData
collect2: error: ld returned 1 exit status
make[2]: *** [/home/tim/src/julia/usr/lib/libjulia.so] Error 1
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2
```
What's strange is that if I reset to a commit from a week ago (when I know I could build successfully), I still get this failure.

If I check out the up-to-date master and do
```
make -C deps clean-llvm
make cleanall
make
```
then everything works again.

**Comment by vtjnash** [comment]
i'm guessing this was addressed by my `usr-staging` PR
