### ISSUE TITLE
OpenBLAS building error on CentOS 6.5

### ISSUE THREAD

**Issue by albertotb** [JuliaLang/julia#8545]
Hi,

Following this issue https://github.com/JuliaLang/julia/issues/8400, that seems to be solved, now I'm getting errors when building OpenBLAS. This is the log:

https://gist.github.com/albertotb/090a9ffb71e70a387ed0

I've tried compiling with `make OPENBLAS_TARGET_ARCH=NEHALEM`but no success. There are also some suggestions in the README.md, but I do not know exactly which one should I try. It seems this is a problem with missing machine instructions (not illegal ones).

I also have a version of OpenBLAS already compiled in that machine (not in the default system location though). Can I point to that library?

**Comment by tkelman** [comment]
Closing this. If you have suggestions for how to make the documentation any clearer, pull requests are welcome.
