### ISSUE TITLE
Macro hygienization doesn't consider type declarations to be assignments

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#8554]
E.g., in the following code I would expect that `MyType` gets replaced by a gensym, but instead it creates an actual type definition for `MyType`:

    julia> macro def_my_type()
               quote
                   type MyType
                   end
               end
           end

    julia> @def_my_type

    julia> MyType()
    MyType()

If I add an inner constructor hygienization takes place, since the constructor definition is taken as a form of assignment to `MyType`.

**Comment by JeffBezanson** [comment]
Type names are now always assumed to be global, so the name is not rewritten whether there is a constructor or not.
