### ISSUE TITLE
Ubuntu 14.04 juliareleases doesn't install OpenBLAS

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#8561]
I have just installed Ubuntu and Julia from juliareleases and it uses reference BLAS. Would it be possible to make it use OpenBLAS? We'll probably get performance complains if not.

cc: @staticfloat

**Comment by kshyatt** [comment]
Is this still a problem on our latest binaries? I'm going to close, because this issue is really old. If we're somehow still having this problem feel free to reopen.
