### ISSUE TITLE
Pkg should ask for confirmation before updating to a new major version

### ISSUE THREAD

**Issue by johansigfrids** [JuliaLang/julia#8568]
This is an issue which may become more relevant once the package ecosystem starts to stabilize.

Assuming (hoping) packages follow semver it would be a good feature of Pkg to ask for explicit confirmation before updating a package to a new major version with backwards compatibility breaking changes. Simply doing `Pkg.update()` and have it break code is not an ideal experience. 

Mentioned on the julia-users mailinglist:
https://groups.google.com/d/msg/julia-users/-xxkIfv4IQQ/JIlr3vClqoUJ

**Comment by simonbyrne** [comment]
I believe this is largely addressed with new Pkg system. Further discussion should be on https://github.com/JuliaLang/Pkg.jl
