### ISSUE TITLE
Can't redefine (or undefine) function - better REPL text and documentation needed?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#8586]
[If I do the same with a (new) g(x) function then everything is as expected or open a new session and do this.]

julia> f(x) = div(x, 100)
f (generic function with 2 methods)

julia> f(100)
1

julia> f(x) = div(x, 10)
f (generic function with 2 methods)

julia> f(100)
1

I was previously testing best way to do stuff with f(x) = x / 100
and then could redefine with f(x) = iround(x / 100)

and then, that seems to be the problem:
f(x::Int64) = div(x, 100)::Int64

For a beginner this would be a gotcha. I understand the precedence now, but not sure how I undefine f(x::Int64) now. Could/should the REPL, at least, say something else if not a warning (or override)? I know "2 methods" is a hint, but for me at first it looked like a bug.. Should this at least be mentioned clearly in the documentation?

julia> versioninfo()
Julia Version 0.3.1
Commit c03f413 (2014-09-21 21:30 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM)2 Duo CPU     T8100  @ 2.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
## 

Palli.

**Comment by KristofferC** [comment]
Perhaps this can be continued to be discussed in https://github.com/JuliaLang/julia/issues/20048? Please reopen if the linked issue is not similar enough.
