### ISSUE TITLE
documentation inconsistently uses ... to mean splice/splat/slurp vs ellipsis

### ISSUE THREAD

**Issue by artkuo** [JuliaLang/julia#8593]
The language uses three periods "..." to mean splice/splat/slurp, e.g.
![screen shot 2014-10-06 at 2 08 11 am](https://cloud.githubusercontent.com/assets/2893800/4521922/4ecbb0ce-4d1f-11e4-9a66-c746babb86d9.png)
as documented in [varargs-functions](http://julia.readthedocs.org/en/latest/manual/functions/#varargs-functions).

But the documentation also often uses ellipsis not to literally mean three periods in a row, but to mean the equivalent of et cetera. From the same page,
![screen shot 2014-10-06 at 2 14 18 am](https://cloud.githubusercontent.com/assets/2893800/4521958/17f74a44-4d20-11e4-81e0-91747309a5f3.png) 
I find this confusing especially in the [documentation on arrays](http://julia.readthedocs.org/en/latest/manual/arrays/), where both meanings are used liberally, and sometimes both interpretations are legal, and sometimes not.

I propose that documentation should only use three periods to indicate splice/splat/slurp, since they are explicitly part of the language. Three periods should therefore never be used to mean et cetera or yada yada, because of the ambiguity.  

Unfortunately , I do not have a good solution to this problem. One possibility is to reserve the actual ellipsis character "…" (a single character, often the product of auto-correct) to mean yada yada (or perhaps splice), but this is not necessarily easy to distinguish. Perhaps a leading space (as sometimes is used in current documentation) followed by ellipsis in a distinct color would help, but perhaps not enough to be clear to those unfamiliar with the convention. The problem is that humans will naturally tend to write "..." which is usually not legal code and therefore can be read correctly by other humans.

**Comment by brenhinkeller** [comment]
So a lot has changed in the docs over the last 8 years; there are probably still some cases where `...` is has multiple possible conflicting interpretations but I don't see many particularly confusing ones at a glance. I'll close this, but if anyone sees something along these lines in the docs that particularly annoys them, feel free to open a PR.
