### ISSUE TITLE
documentation: relative module path

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#8597]
This is a remark about the documentation: in the section entitled "Relative and absolute module paths" in the chapter on "Modules", it is explained that a period before a module name makes the resulting declaration relative to the current module.  However, it is not explained in what context this declaration is valid.  I got a very weird syntax error (something about 'const') when I used .Tokens.SDToken inside a 'typealias' statement.  So apparently this way to refer to a module is allowed only in 'import' and 'using' statements?  I am not able to propose a modification to the documentation because I don't know what is the exact rule.

**Comment by tkelman** [comment]
backported in e4045a37364699b6bcab12bd35b7e1de85975800
