### ISSUE TITLE
alist-like construct

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#8674]
With pull request #8521 my understanding is that the `=>` has become the syntax for pairs (or similar) and has been decoupled from `Dict` per se, so I am wondering if there is going to be support for lightweight associative lists, eg of the kind

``` julia
(:a => 1, :b => 2)
```

I guess I do not not need to argue very much that this is useful since the construct is present in all LISP languages ([eg](http://clhs.lisp.se/Body/f_assocc.htm)), but for me the most compelling argument is when I want to return multiple values but don't want to remember/hardcode the order of values, nor define a new type, and want something lighter than `Dict`  (AFAIK hash tables of a few elements are not optimal from a performance point of view in most languages, but maybe Julia is different).

An skeleton of an example could be 

``` julia
function my_iterative_algorithm(start, tolerance, other_arguments...)
  ## algorithm goes here
  (:root => root, :converged_p => convergence, :number_of_iterations => n, :precision => prec)
end

solution = my_iterative_algorithm(start, tol)

if solution[:converged_p]
  do_something(solution[:root])
else
  try_something_else()
end
```

An advantage of Julia over LISP is that tuples are a separate type, so `[]` could dispatch on that and there is no need for a separate accessor function.

(Sorry for the noise if this is already planned, I searched the archives and already asked a [related question](https://groups.google.com/d/topic/julia-users/fs9HEc0Rr1Q/discussion) on julia-users but I was not aware of this new feature then.)

**Comment by ararslan** [comment]
This seems to have been addressed by the addition of `NamedTuple`s. These preserve order, and key-value pairs can be obtained from them using `pairs(::NamedTuple)`, which returns an `AbstractDict`. I'm going to close this as it seems no longer relevant, but feel free to reopen if there's something here I've overlooked.
