### ISSUE TITLE
release-0.3 needs gfortran-<version>-dev dependency during initial make

### ISSUE THREAD

**Issue by dehann** [JuliaLang/julia#8697]
Hi,

I had to install 

libgfortran-#.#-dev, rather than just libgfortran-#.#

for initial build of release-0.3. I do not yet follow how you bring the dependencies into your build system -- although it looks like the current dependencies require only 

gfortran -- its missing the '-dev' bit

During make I got:

............
 cblas_zher2k PASSED THE COLUMN-MAJOR COMPUTATIONAL TESTS (  1764 CALLS)
 cblas_zher2k PASSED THE ROW-MAJOR    COMPUTATIONAL TESTS (  1764 CALLS)

 cblas_zsyr2k PASSED THE TESTS OF ERROR-EXITS

 cblas_zsyr2k PASSED THE COLUMN-MAJOR COMPUTATIONAL TESTS (  1764 CALLS)
 cblas_zsyr2k PASSED THE ROW-MAJOR    COMPUTATIONAL TESTS (  1764 CALLS)

 END OF TESTS
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make[4]: *** [../libopenblasp-r0.2.10.so] Error 1
make[3]: *** [shared] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[2]: *** [openblas-v0.2.10/libopenblas.so] Error 1
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2

~/software/julia$ dpkg -l | grep libgfortran | cut -c-75
ii  libgfortran3                                   4.8.1-2ubuntu1~12.04  

I'm on updated Ubuntu 12.04, 64, gcc 4.8.1. and gfortran-4.8.

Thanks

**Comment by tkelman** [comment]
We've upgraded our openblas to include these patches, hopefully everything is good on freebsd these days. Add a comment, reopen, or open a new issue if not.
