### ISSUE TITLE
julia-mode.el: Add the ability to start a REPL from inside Emacs

### ISSUE THREAD

**Issue by Wilfred** [JuliaLang/julia#8715]
It need not be very sophisticated, and I'm not sure how we'll integrate the shell and help features, but basic functionality would be much better than nothing.

**Comment by dfannius** [comment]
I haven't tried [julia-shell-mode](https://github.com/dennisog/julia-shell-mode) yet, but it looks promising.

**Comment by PythonNut** [comment]
Hm... Perhaps it can be merged into the official emacs package?

**Comment by tkelman** [comment]
It's GPL and borrows code from the GPL Matlab-emacs, so not unless it were clean-room reimplemented or julia-mode moved to a separate repository.

**Comment by yuyichao** [comment]
Moved to https://github.com/JuliaLang/julia-emacs/issues/1
