### ISSUE TITLE
julia-mode.el: Highlight functions with nested parens in definition

### ISSUE THREAD

**Issue by Wilfred** [JuliaLang/julia#8722]
For example:

```
cell(dims::Integer...)   = Array(Any, dims...)
cell(dims::(Integer...)) = Array(Any, convert((Int...), dims))
```

We're not currently highlighting the second `cell` definition.

**Comment by yuyichao** [comment]
Is this still an issue after #10380 ? (Actually the second case is highlighted now although it is invalid syntax now...)

![minicircuits_2015-4-24](https://cloud.githubusercontent.com/assets/712232/8120289/6e68ed24-106b-11e5-9d6e-cdc5d319b01a.png)

**Comment by yuyichao** [comment]
Seems fixed. Please [open in julia-emacs](https://github.com/JuliaLang/julia-emacs/issues/new) if it is not.
