### ISSUE TITLE
julia-mode.el: Highlight variable definitions

### ISSUE THREAD

**Issue by Wilfred** [JuliaLang/julia#8723]
We should highlight variables introduced with `let`, `global`, `local` or `const`. We'll need to be careful here to ensure that we handle commas correctly. Consider the code:

```
let x = "foo, bar", y = foo(1, 2)
    x + y
end
```

This was also discussed in #8026. We might be forced to write a simple parser, but we may be able to get away with just calling `forward-sexp` instead.

**Comment by yuyichao** [comment]
Moved to https://github.com/JuliaLang/julia-emacs/issues/2
