### ISSUE TITLE
On my Mac mini, when I open a terminal, I can not use Julia from the Unix command line 

### ISSUE THREAD

**Issue by j-jones** [JuliaLang/julia#8733]
I installed Julia v0.3.1 on my Mac mini.
I can start and use Julia in interactive mode, but
I can not  run code in a file non-interactively.
If at Unix shell i type $ julia script.jl arg1 arg2...
I get 
-bash: julia: command not found
Maybe I need to edit my .bash_profile:
and put in it a line: 
export PATH="/Applications/Julia-0.3.1.app/Contents/MacOS:$PATH"
???????

**Comment by ViralBShah** [comment]
@simonbyrne I don't think the app installer should install links outside the .app folder. However, this does come up often, and perhaps it can be in the intsallation notes that are shown in the install procedure, and a small README that is included in the dmg.

**Comment by simonbyrne** [comment]
@ViralBShah That was why I proposed the separate script inside the .dmg, similar to [what Mathematica does for its various plugins](http://support.wolfram.com/kb/12449):
![Mathematics install](http://support.wolfram.com/kb/data/uploads/2014/06/Screen-Shot-2014-06-09-at-3.20.24-PM.png)

**Comment by ViralBShah** [comment]
Ah, I realise I misunderstood you. I see we are saying the same thing.

**Comment by simonbyrne** [comment]
Actually, a better way might be to add files to `/etc/paths.d/` and `/etc/manpaths.d/`, as that won't require overwriting anything. The only problem is that these are added to PATH in the order they appear, so that would mean older versions have precedence.

**Comment by ViralBShah** [comment]
I think that the simplest thing to do for now is to document this. If you are going to call julia from the command line, you can easily add something to the PATH.

**Comment by simonbyrne** [comment]
Also, you can find the installed path of a particular version of the Julia .app by:
```
mdfind "kMDItemCFBundleIdentifier == 'org.julialang' && kMDItemVersion == '0.4.2'"
```

**Comment by apetrushin** [comment]
Still not work in 2017. Maybe it would be better to distribute it via brew?

**Comment by tkelman** [comment]
`brew cask install julia` already works

**Comment by billgo** [comment]
version 1.1, using this command can work

`sudo ln -s /Applications/Julia-1.1.app/Contents/Resources/julia/bin/julia /usr/local/bin/julia`
