### ISSUE TITLE
vec  bug for scalars?

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/julia#8735]
`vec(1)`

`vec` has no method matching vec(::Int64)
while loading In[44], in expression starting on line 1

**Comment by kshyatt** [comment]
https://github.com/JuliaLang/julia/issues/7903 seems relevant here. This is still an "issue" (?) on `master`.

**Comment by KristofferC** [comment]
We use `collect` for this, `vec` is to get a 1d object that shares data with the original object.
