### ISSUE TITLE
sub2ind bounds checking

### ISSUE THREAD

**Issue by dressel** [JuliaLang/julia#8746]
I think sub2ind needs to do some bounds-checking. If I try something like:

```
#julia
sub2ind( (10,10), 11, 2)
```

Julia spits out 21. I was expecting it to throw an error. If you try the same thing in Matlab, it will do something like:

```
>> sub2ind( [10,10], 11, 2)
Error using sub2ind (line 52)
Out of range subscript.
```

I haven't been able to find anything about this in the developer's or user's groups, but please let me know if there is some reasoning for this somewhere. I feel it should throw an error. If not, maybe it should be noted in the standard library documentation.

**Comment by felixcremer** [comment]
Isn't this closed in https://github.com/JuliaLang/julia/pull/25113?
There sub2ind is deprecated and replaced by LinearIndices which throw a BoundsError.

**Comment by nalimilan** [comment]
Indeed!
