### ISSUE TITLE
Install and test embedding examples

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#8757]
I'm starting to think we should install `examples/embedding.c` and `examples/Makefile` along with `examples/*.jl` and test on Travis that it keeps working in an installed version of Julia. For this to make sense, the makefile would need to be modified quite a bit (or a new one autogenerated?) to be standalone.

Related to #8428, cc @nalimilan

**Comment by tkelman** [comment]
> But for Travis testing wouldn't it suffice to build and execute the example in a source build?

Partially, not completely. Testing the embedding example in a source build only makes sure we don't break it in a source build. Testing it from the installed copy makes sure it works in an install, which would be more valuable.

**Comment by waTeim** [comment]
Is #9438 useful here as a means of creating a julia-config?

**Comment by tkelman** [comment]
Don't think so. That approach is temporary anyway. If you are operating under the assumption that Julia has to be installed in order to build an application that embeds it, then you don't need to go to any lengths to make a julia-config script usable in a standalone way. Just install it to `joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia")` and ensure the user provides the right path to the specific julia executable they want to use.

**Comment by waTeim** [comment]
I copied the embedding.c file from examples into a test directory and modified embedding.c and Makefile to follow the pattern in #10069:

One change to embedding.c:

    jl_init(NULL);

changed to 

    jl_init(JULIA_INIT_DIR);

and then the makefile changed to 

    JL_SHARE = $(shell julia -e 'print(joinpath(JULIA_HOME,Base.DATAROOTDIR,"julia"))')
    CFLAGS   += $(shell $(JL_SHARE)/julia-config.jl --cflags)
    CXXFLAGS += $(shell $(JL_SHARE)/julia-config.jl --cflags)
    LDFLAGS  += $(shell $(JL_SHARE)/julia-config.jl --ldflags)
    LDLIBS   += $(shell $(JL_SHARE)/julia-config.jl --ldlibs)

    all: embedding

followed by make, then running it....

    bizarro% make
    cc -DJULIA_INIT_DIR=\"/usr/local/julia-f875a541be/lib\" -I/usr/local/julia-f875a541be/include/julia  -L/usr/local/julia-f875a541be/lib/julia  embedding.c  -Wl,-rpath,/usr/local/julia-f875a541be/lib/julia -ljulia -o embedding
    bizarro% ./embedding 
    1.4142135623730951
    sqrt(2.0) in C: 1.414214e+00
    sqrt(2.0) in C: 1.414214e+00
    x = [9.000000e+00 8.000000e+00 7.000000e+00 6.000000e+00 5.000000e+00 4.000000e+00 3.000000e+00 2.000000e+00 1.000000e+00 0.000000e+00 ]
    my_func(5.0) = 10.000000
    1.4142135623730951
    UndefVarError(:this_function_does_not_exist)

**Comment by tkelman** [comment]
cool, that's the expected output, right?

**Comment by waTeim** [comment]
Ya, pretty sure.  I can check it.  But, is there a thing that does it automatically?  How much do I need to modify, and how much to add?  Is there a thing that installs Julia in test yet for instance?

**Comment by tkelman** [comment]
We install julia on Travis. That code is getting a bit messy but we can fiddle with it.

It would be ideal to make `examples/Makefile` not rely on `include $(JULIAHOME)/Make.inc` any more, so it can work in a binary install. I'm not sure yet how hard this will be.

Also the path to the `julia` binary may as well be set in a variable so it can easily be overridden

**Comment by waTeim** [comment]
I didn't look ultra deeply, but it appeared that all Makefile does is build embedding, if so then modifying like above should do it, so long as Julia is in PATH, everything else is automatic.  Is the examples directory installed somewhere?  Does make test do this?

**Comment by tkelman** [comment]
> so long as Julia is in PATH

Or the location is easy to specify by overriding a `JULIA` variable on the command-line.

> Is the examples directory installed somewhere?

I believe `make install` does install some but not all of the examples directory. Some of it was removed in #8428 which you might now want to put back if it can be made to work in a binary install.

> make test

There is a `test/examples.jl` that makes sure the code there still runs. I think this might be better to do as a new file `test/embedding.jl`, since it will depend on having a toolchain installed so we should make it easy to skip.

**Comment by waTeim** [comment]
Ok I know now this must be completed.  There is no check for changes that break embeddings, and it happens a lot.  

To fix this, I need some help in understanding how the current test suite functions and how a new embed test would need to work (HELP).

As I said (months ago, heh) this should be pretty easy, but currently I am not familiar at all with this test, what occurs, how it runs.

A good start would be can someone tell me what to run the test locally?  Like "make test" or something?

**Comment by tkelman** [comment]
Yeah, start with `make test` from a source build. If you add a new file `test/embedding.jl` and add `"embedding"` to the list in `test/choosetests.jl` then the content of `test/embedding.jl` will become part of the test suite, and get run by Travis, AppVeyor, etc. For binary builds, it's also ideal if `Base.runtests("all")` passes, but I'm not sure how often that gets checked so it might break once in a while.

**Comment by waTeim** [comment]
This would be different.  This would need to make and run an external test separated from all of that seems like.  Maybe what could be done is in embedding.jl there could be some invocation of external commands:  make embed1,embed2, etc.  It would also need to occur against an "installed" version of julia as opposed to within the source tree if it's going to be accurate.  I'm not sure that the current test framework imagines that something like that could happen.

**Comment by tkelman** [comment]
Maybe not. Travis at least does do `make install`, but assuming `make` is present isn't always a safe assumption to make for Windows, or OS X when the command-line tools aren't installed. It is safe to do that kind of thing on Travis though.

Maybe another option would be to use the framework of a Julia package to set up this testing? With PackageEvaluator and Travis at least it will run pretty regularly and in a mostly-automated way. Could have an EmbeddingExamples.jl package with code snippets, build scripts, etc? Not sure if that's better or worse than having things live in the base repository but not tested very often.

**Comment by tkelman** [comment]
@twadleigh sounds like you're about to do at least the test part of this?

**Comment by twadleigh** [comment]
@tkelman thanks for the reminder of this thread. Yes, I'll at least do the test part. I'll look into the install part while I'm at it. Since we have this issue, I think we can close #11419.

**Comment by tkelman** [comment]
Mostly fixed by https://github.com/JuliaLang/julia/pull/21299, subject to some rpath caveats. We're not putting the built embedding executable in binaries just yet, but the rest of this is done now.
