### ISSUE TITLE
`nb_available` doesn't work properly!?

### ISSUE THREAD

**Issue by randy3k** [JuliaLang/julia#8762]
Following the discussion [here](https://github.com/JuliaLang/julia/pull/8717#issue-46158125) 

It is discovered [[1]](https://github.com/JuliaLang/IJulia.jl/issues/238) [[2]](https://github.com/JuliaLang/IJulia.jl/pull/240) that `flush_cstdio` doesn't flush stdio immediately. To illustrate it, consider

```
begin
    read_stdout, = redirect_stdout();
    start_reading(read_stdout);
    ccall((:printf, "libc"), Int, (Ptr{Uint8},), "foo");
    flush_cstdio()
    nb_available(read_stdout)
end
```

the above returns 0

```
begin
    read_stdout, = redirect_stdout();
    start_reading(read_stdout);
    ccall((:printf, "libc"), Int, (Ptr{Uint8},), "foo");
    flush_cstdio()
    Base.process_events(true)
    nb_available(read_stdout)
end
```

the above returns 3

`nb_available` yields a different result if we do `Base.process_events`

ps:
it is perfectly fine for the julia stdout

```
read_stdout, = redirect_stdout();
start_reading(read_stdout);
println("test"); nb_available(read_stdout)
```

**Comment by ViralBShah** [comment]
Close?

**Comment by vtjnash** [comment]
Yeah, hopefully people have stopped recommending this function to other poor souls and documented better ways in the depths of the internet lore repositories such as StackOverflow and Discourse
