### ISSUE TITLE
A new RNG for Julia?

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#8786]
It has been discussed if we should consider [this](http://xorshift.di.unimi.it/) RNG alongside or instead of dSFMT. 

The RNG we are using now is a Mersenne Twister implementation adapted to use SIMD, but we don't really get anything from SIMD right now because of #6573.

In addition, dSFMT actually [consistently fails](#6464) one of the tests in [BigCrush](http://simul.iro.umontreal.ca/testu01/tu01.html) in contrast to the proposed XORShift* algorithm.

Finally, the XORShift* is very simple and can be written in Julia. See some implementations with various perfomance tweaks here

https://gist.github.com/andreasnoack/9f3f63d7f1d00a07359b

**Comment by tkelman** [comment]
Anyone familiar with this work? Looks interesting http://www.pcg-random.org/pdf/toms-oneill-pcg-family-v1.02.pdf

**Comment by ViralBShah** [comment]
Should we try and include XORShift in Julia by default, or should we have a package? For now, I am thinking it is a good idea to have it in a package, which will also help clean up the API to make it easy to add other RNGs.

**Comment by toivoh** [comment]
+1 for starting in a package.

**Comment by ViralBShah** [comment]
I have put the code from here into: https://github.com/JuliaLang/XORShiftRNG.jl

Ideally one would just provide `rand(rng::SomeRNG, ::Type{Float64})` and everything else would just work. I think we are pretty close to that, and if that can be achieved with this package, and some reorganization in Base, we can even register it.

**Comment by tkelman** [comment]
I was also hoping the new pcg-random rng's would have been relicensed to MIT by now so a more direct port of the source code instead of going from the paper could avoid Apache, but no update there.

**Comment by ivarne** [comment]
I rather think `rand(rng::SomeRNG, ::Type{Int64})` should be the basis, because `rand(rng::SomeRNG, ::Type{Float64})` only offers 52 bits of entropy. @rfourquet also complained that a fully generic pluggable system creates ambiguity problems, but I can't find the reference.

**Comment by ViralBShah** [comment]
Yes, I recollect that too, but it is worth revisiting. @rfourquet may have a PR for this as well. Int64 is certainly a better basis, but that won't work for dSFMT, although it will work for SFMT. Perhaps we can have either one.

**Comment by rfourquet** [comment]
I wouldn't say that "a fully generic pluggable system [necessarily] creates ambiguity problems" (I may have expressed my concerns unclearly in this [comment](https://github.com/JuliaLang/julia/pull/9387#issuecomment-68025013) and above), only that it must be general enough and allow the library writer to define the specializations she wants without getting ambiguity warnings. I wish `rand(rng::SomeRNG, ::Type{Int64})` won't be hardcoded as the only possible "basis": more kind of engines should be "pluggable", even though the full generality of the C++ random engines/distributions system may not be needed at this point. This is certainly doable with e.g. `@generated` functions.

**Comment by blakejohnson** [comment]
@tkelman I've recently stumbled upon the PCG family of random number generators again. The algorithm seems simple enough that it might be straightforward to create an original implementation from the paper. I'll put it on my TODO list.

**Comment by blakejohnson** [comment]
It's just a first pass, but this is an attempt to reproduce `PCG-XSH-RR` from the paper:
```julia
# bitwise rotate right
function rotate{T <: Unsigned}(x::T, n::T)
    mask = 8*sizeof(x) - 1
    return (x >> n) | (x << ((-n) & mask))
end

# multiplier chosen from table 4 in:
# P. L'Ecuyer, ``Tables of Linear Congruential Generators of Different Sizes and
# Good Lattice Structure'', Mathematics of Computation, 68, 225 (1999), 249--260.
const multiplier = UInt64(3935559000370003845)
# L'Ecuyer only says that you need an odd increment
const increment = UInt64(204209821)

let state::UInt64 = 0x23cc2170ddd0af6e
    global pcg_rand
    function pcg_rand()
        state = state * multiplier + increment;
        rotate(((state $ (state >> 18)) >> 27) % UInt32,
               (state >> 59) % UInt32)
    end
end
```

**Comment by pao** [comment]
Forwarding this on, as promised, from https://github.com/art4711/random-double/issues/1:

> I just remembered this conversation. You probably won't get this (I have not idea how github notifies people), but in case you do, I did a thing: https://github.com/art4711/randbench (regarding the "CSPRNG is slow" meme) and https://github.com/art4711/unpredictable. With the new compiler that will be in go 1.7, I'm down to 25ns per 64 bit number which is just 2.5x slower than the default PRNG in Go.

The conversation started roughly ages ago but seeing as there was a follow-up and benchmarks (though in Go) I figured I should pass it along. I don't agree that "just 2.5x slower" is acceptable for random sampling applications.

**Comment by ViralBShah** [comment]
I wonder if this is worth revisiting given the interesting developments in libm.jl. Having a good implementation in Julia is probably desirable compared to dsfmt, which does not leverage the modern wider vector units. I am not sure if this should be xorshift or MT or perhaps both.

Reducing the dependency on dsfmt also will give us faster RNGs on non-Intel platforms.

**Comment by simonbyrne** [comment]
I should mention the GSOC project by @sunoru:
https://github.com/sunoru/RNG.jl

Some benchmarks are here:
http://sunoru.github.io/RNG.jl/latest/man/benchmark/

(note, however, that these were for generating `UInt64`s: dSFMT was designed to generate 52-bits at a time for a `Float64`s, and thus requires to 2 draws to get a `Float64`).
