### ISSUE TITLE
Error: repackage_system_suitesparse4.make when suitesparse is linked to CUDA 

### ISSUE THREAD

**Issue by starrynight** [JuliaLang/julia#8800]
Platform: ubuntu 14.04  icc 15.0 icpc 15.0 ifort 15.0
Suitesparse 4.3.1 : /usr/local/lib
CUDA 6.5 : /opt/nvidia/cuda-6.5
SuiteSparse_config.mk

  CUDA_ROOT     = /opt/nvidia/cuda-6.5
  GPU_BLAS_PATH = $(CUDA_ROOT)
  GPU_CONFIG    = -I$(CUDA_ROOT)/include -DGPU_BLAS
-DCHOLMOD_OMP_NUM_THREADS=10
  CUDA_PATH     = $(CUDA_ROOT)
  CUDART_LIB    = $(CUDA_ROOT)/lib64/libcudart.so
  CUBLAS_LIB    = $(CUDA_ROOT)/lib64/libcublas.so
  CUDA_INC_PATH = $(CUDA_ROOT)/include/
  NV20          = -arch=sm_20 -Xcompiler -fPIC
  NV30          = -arch=sm_30 -Xcompiler -fPIC
  NV35          = -arch=sm_35 -Xcompiler -fPIC
  NVCC          = $(CUDA_ROOT)/bin/nvcc
  NVCCFLAGS     = -O3 -gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -Xcompiler -fPIC

Error Message:

/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o): In function `__device_stub__Z15kernelCreateMapPl
S_ll(long*, long*, long, long)':
tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0x20): multiple definit
ion of `__device_stub__Z15kernelCreateMapPlS_ll(long*, long*, long, long)'
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o):tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.co
mpute_20.cudafe1.cpp:(.text+0x20): first defined here
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o): In function `kernelCreateMap':
tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0xc0): multiple definit
ion of `kernelCreateMap'
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o):tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.co
mpute_20.cudafe1.cpp:(.text+0xc0): first defined here
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o): In function `createMapOnDevice':
tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0xd0): multiple definit
ion of `createMapOnDevice'
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o):tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.co
mpute_20.cudafe1.cpp:(.text+0xd0): first defined here
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o): In function `__device_stub__Z23kernelCreateRelat
iveMapPlS_S_ll(long*, long*, long*, long, long)':
tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0x160): multiple defini
tion of `__device_stub__Z23kernelCreateRelativeMapPlS_S_ll(long*, long*, long*, long, long)'
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o):tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.co
mpute_20.cudafe1.cpp:(.text+0x160): first defined here
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o): In function `kernelCreateRelativeMap':
tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0x220): multiple defini
tion of `kernelCreateRelativeMap'
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o):tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.co
mpute_20.cudafe1.cpp:(.text+0x220): first defined here
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o): In function `createRelativeMapOnDevice':
tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0x230): multiple defini
tion of `createRelativeMapOnDevice'
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o):tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.co
mpute_20.cudafe1.cpp:(.text+0x230): first defined here
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o): In function `kernelSumComplexA':
tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0x800): multiple definition of `kernelSumComplexA'
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o):tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0x800): first defined here
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o): In function `sumComplexAOnDevice':
tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0x810): multiple definition of `sumComplexAOnDevice'
/usr/local/lib/libcholmod.a(cholmod_gpu_kernels.o):tmpxft_00005f3b_00000000-9_cholmod_gpu_kernels.compute_20.cudafe1.cpp:(.text+0x810): first defined here
make: *** [default] Error 1

**Comment by ViralBShah** [comment]
#10122 is related.

**Comment by ViralBShah** [comment]
I am closing this as an unsupported configuration for now. If it works with the current SuiteSparse, that would be good to know.
