### ISSUE TITLE
Recursive walks down a directory

### ISSUE THREAD

**Issue by prcastro** [JuliaLang/julia#8814]
To work with directories, a nice function to have is `walk`. It would walk down a directory and its subdirectories, and return a generator. Each step would give the user the current path, the subdirectories in that path, and the files inside that path.

It's similar to the function `walk` on Python's `os` library:
https://docs.python.org/2/library/os.html#os.walk

**Comment by dopatraman** [comment]
...`walkdir` is not in Julia v0.4.5...

**Comment by tkelman** [comment]
We don't generally backport features. It is present in the Compat.jl package though: https://github.com/JuliaLang/Compat.jl/pull/180

**Comment by dopatraman** [comment]
Made this gist if anyones looking: https://gist.github.com/dopatraman/6bb694e37e5f2360449e03702fe16f65
