### ISSUE TITLE
File IO slow

### ISSUE THREAD

**Issue by alexalemi** [JuliaLang/julia#8826]
I'm trying to count how often each word occurs in a file, and I'm getting roughly 10x slower speeds for julia compared to C, python or go

```julia
counts = Dict{String,Int}()

open(ARGS[1],"r") do f
    for line in eachline(f)
        for word in split(line)
            counts[word] = get(counts,word,0) + 1 
        end
    end
end

cut = 10

guys = collect(counts)
sort!( guys, by=(x)->x[2], rev=true )

for x in guys
    if x[2] > cut
        println(x[1], '\t',  x[2])
    end
end
```

On a 96 M text file, it is taking julia 54.35 seconds on my machine, versus 2.69s for equivalent C code, 7.35 s for python, and 5.98 s for Go.

Profiling the code, it seems the actual speed is the time spent reading the file.  I've seen other mentions of slow IO in regards to reading csv files (e.g. #3350 or [this group discussion](https://groups.google.com/forum/?fromgroups=#!topic/julia-users/fej63DPHgYo)) where some specific fixes were worked out, but these discussions are a year old and I was wondering whether there were hopes of speeding up I/O more generally.

I've thrown together a [git repository](https://github.com/alexalemi/textbench) of the test code.

**Comment by RaviMohan** [comment]
I just tested this on my machine(quadcore S7, 32 GB Ram, Ubuntu 14.04)  and got the following timings

---Testing C
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

1.56user 0.02system 0:01.59elapsed 99%CPU (0avgtext+0avgdata 33512maxresident)k
0inputs+1080outputs (0major+6039minor)pagefaults 0swaps

---Testing Python 2
Python 2.7.6
5.25user 0.25system 0:05.50elapsed 99%CPU (0avgtext+0avgdata 1012416maxresident)k
0inputs+1024outputs (0major+200543minor)pagefaults 0swaps

---Testing Julia
julia version 0.4.0-dev
8.55user 0.48system 0:08.80elapsed 102%CPU (0avgtext+0avgdata 2681616maxresident)k
0inputs+1024outputs (0major+39741minor)pagefaults 0swaps

Julia's speed  is about 1.6 times Python's. Which should probably be better, but the almost 8 times slow down seems to be fixed. 
Recommend closing this.

**Comment by ViralBShah** [comment]
We really should be as fast as Python. I agree that this is good enough to close this issue. Perhaps the thing to do here is to figure out where we are losing and file separate issues.
