### ISSUE TITLE
Jeff Bezanson PhD

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#8839]
One of the core Julia authors, @JeffBezanson, has become a problematic developer.   He needs to graduate from MIT, ideally by January 2015.   Dependencies:

- [x] Thesis proposal.
- [x] Thesis outline.
- [x] Meeting with thesis committee.
- [x] Rough draft sent to advisor(s).
- [x] Schedule defense.
- [x] Final draft sent to committee.
- [x] Defense.
- [ ] Alcohol.

This is a priority issue, to ensure that arms are not broken and to guarantee long-term viability of the Julia project.

cc: @alanedelman, @jiahao, @StefanKarpinski, @ViralBShah, @samanamarasinghe, @gjs

**Comment by JeffBezanson** [comment]
I have a small update on this issue. The document is now open to the public: https://github.com/JeffBezanson/phdthesis

Today I'm releasing a sort-of draft by self-imposed deadline. It's not much of a draft; many pieces are entirely missing. I also claim no responsibility for anything that is inside TeX comments, or present only in the past version history :)

All feedback welcome! In particular, if you have nice examples of julia code that show off the language well, especially anything that would be hard to do without it. Always looking for good non-trivial multiple dispatch examples.

**Comment by johnmyleswhite** [comment]
Thanks for making this public. I was surprised when I tried to follow a link SGJ used and hit a 404.

**Comment by andreasnoack** [comment]
Maybe the [triangular matrix arithmetic](https://github.com/JuliaLang/julia/blob/master/base/linalg/triangular.jl#L167-L183) could be an example of the usefulness of Julia's multiple dispatch. Here `UpperTriangular+UpperTriangular=UpperTriangular`, but `UpperTriangular+LowerTriangular=Matrix`.

We also talked about promotion of element types. I like that you can avoid promotion when it is not necessary, e.g.
```julia
julia> Base.LinAlg.UnitLowerTriangular(ones(Int, 3, 3))\[1,2,3]
3-element Array{Int64,1}:
 1
 1
 1

julia> Base.LinAlg.UnitLowerTriangular(ones(Int, 3, 3))\[1,2,3.0]
3-element Array{Float64,1}:
 1.0
 1.0
 1.0
```
I can't say how specific this is to Julia, but as we saw, it appeared that at least Eigen will not manage promotion, but require that the element types are stable under the linear algebra operation.

**Comment by stevengj** [comment]
Jeff is going into the final stretch now, we hope, so feedback on and corrections to his thesis (see the abovementioned github repository) would be especially welcome now.

**Comment by yuyichao** [comment]
@stevengj Should we expect an announcement of the defence schedule here?

**Comment by stevengj** [comment]
Yes.

**Comment by ScottPJones** [comment]
I hope he has a job lined up at MIT already... (or anywhere where he'll continue the great Julia work)... reading his thesis now... great stuff, IMO!

**Comment by mschauer** [comment]
@andreasnoack A bit esoteric, but anyway funny: Define a arrow matrix ring type and apply the Cholesky factorization from base to see what the structure of a cholesky factorization of an arrow matrix of triangular matrices matrices looks like.  https://gist.github.com/mschauer/c325ff89cd378fe7ecd6 ("A" Arrow matrix, "F" full matrix, "L" Lower half arrow").

**Comment by JeffBezanson** [comment]
@ScottPJones thanks!!

Defense scheduled: Wed May 13, 1pm Stata D-463.

**Comment by jiahao** [comment]
@JeffBezanson are you planning to have it recorded through replay.csail.mit.edu?

**Comment by JeffBezanson** [comment]
...maybe I'd rather forget about it... :)

**Comment by ihnorton** [comment]
Isn't that what the last checkbox is for?

**Comment by ScottPJones** [comment]
Are you *really* sure you should be giving the address out?  You might get mobbed by fan boys, who want signed copies of your thesis! :grinning:

**Comment by timholy** [comment]
I've already got my tickets. I hear the price is already up to $800 on the black market.

**Comment by ScottPJones** [comment]
Stata D-463 wasn't there in my day... (I've only been there to visit friends and for the NE Database Day)... Is it going to be big enough?  Surely he's going to need 10-250!

**Comment by JeffBezanson** [comment]
Officially D-463 fits 48 chairs. If we think that won't be enough, we can look into getting a bigger room.

**Comment by ScottPJones** [comment]
I seriously don't think you really appreciate what you've done! If all of your fans showed up, maybe 10-250 wouldn't be big enough... book Kresge now!

**Comment by stevengj** [comment]
## Abstraction in Technical Computing
* PhD Candidate: Jeff Bezanson
* Thesis Supervisor: Prof. Alan Edelman
* Thesis Committee: Prof. Steven Johnson, Prof. Saman Amarasinghe, Prof. Gerry Sussman
* Date: Wednesday May 13, 2015
* Time: 1pm 
* Location: MIT campus, 32-D463  
 
*Array-based programming environments are popular for scientific and technical computing. These systems consist of built-in function libraries paired with high-level languages for interaction. Although the libraries perform well, it is widely believed that scripting in these languages is necessarily slow, and that only heroic feats of engineering can at best partially ameliorate this problem.*

*This thesis argues that what is really needed is a more coherent structure for this functionality. To find one, we must ask what technical computing is really about. This thesis suggests that this kind of programming is characterized by an emphasis on operator complexity and code specialization, and that a language can be designed to  better fit these requirements.*

*The key idea is to integrate code* ***selection*** *with code* ***specialization***, *using generic functions and data-flow type inference. Systems like these can suffer from inefficient compilation, or from uncertainty about what to specialize on. We show that sufficiently powerful type-based dispatch addresses these problems. The resulting language, Julia, achieves a Quine-style "explication by elimination" of many of the productive features technical computing users expect.*

**Comment by ScottPJones** [comment]
Will there be printed copies of his thesis available for spectators?

**Comment by yuyichao** [comment]
Maybe [signed copies](https://github.com/JuliaLang/julia/issues/8839#issuecomment-100075374)

**Comment by ScottPJones** [comment]
That's what I'm hoping for... I figure I can get some big bucks on Ebay selling an autographed copy in 10-15 years (when I'll really need it to pay off my kids' college education... esp. if they go where they have said they want to go... :grinning: )

**Comment by aviks** [comment]
Good luck, Jeff!

**Comment by Mike43110** [comment]
Good luck! If I was in the area I would be one of the fanboys @ScottPJones  mentions

**Comment by Gnimuc** [comment]
@ScottPJones :+1:

**Comment by mbauman** [comment]
Break a leg, Jeff!

**Comment by johnmyleswhite** [comment]
Good luck, Jeff!

**Comment by xianyi** [comment]
Good luck! @JeffBezanson

**Comment by yuyichao** [comment]
@JeffBezanson Good Luck!!

Hopefully I can get a seat.

**Comment by wlbksy** [comment]
good luck

**Comment by MithrandirMiles** [comment]
I told him he should have booked 10-250!

**Comment by kshyatt** [comment]
Good luck!

**Comment by garrison** [comment]
Ditto!

**Comment by ScottPJones** [comment]
Luckily I got in early enough to get a seat... and I was right (as usual :grinning:) he really should have booked a bigger room!

**Comment by ScottPJones** [comment]
![img_0994](https://cloud.githubusercontent.com/assets/11798751/7616553/3994a124-f973-11e4-8e94-18919b5ba977.jpg)

**Comment by yuyichao** [comment]
Congratulations

**Comment by JeffBezanson** [comment]
Fixed.

**Comment by timholy** [comment]
There's still one checkbox left unchecked. Better get working.

**Comment by Carreau** [comment]
:shipit: :tropical_drink: :beers: :cocktail:  :tada: !

**Comment by garrison** [comment]
:thumbsup:!

**Comment by rsrock** [comment]
Congratulations, Dr. Bezanson!

**Comment by kmsquire** [comment]
Congrats, Jeff!

**Comment by nolta** [comment]
+1

**Comment by catawbasam** [comment]
Bravo

**Comment by vtjnash** [comment]
the last checkbox has been filled now with a Kentucky Bourbon Whiskey.

**Comment by Ismael-VC** [comment]
Congratulations Jeff!

**Comment by cdsousa** [comment]
Congratulations!

**Comment by shashi** [comment]
Congrats Jeff! :beers: :beers: :smile:

**Comment by mbauman** [comment]
This is wonderful.  Congratulations, Jeff.  :fireworks:

**Comment by tshort** [comment]
Great news. Congratulations, Jeff!

**Comment by toivoh** [comment]
Congratulations!

**Comment by abhijitiitr** [comment]
Congrats

**Comment by sjkelly** [comment]
Woop woop congrats Jeff!

**Comment by aviks** [comment]
Congratulations, Dr Bezanson!

**Comment by stevengj** [comment]
Thanks for posting the photo, @ScottPJones.  @jiahao, I think you have some photos as well?

**Comment by tknopp** [comment]
Congratulations Jeff. Your work that ended in this PHD has influenced many of us. It will have and already has a huge impact on scientific computing! Rock on!

**Comment by shabbychef** [comment]
congratulations.

**Comment by mschauer** [comment]
Great!

**Comment by rahuldave** [comment]
Congrats Jeff!!

**Comment by dpsanders** [comment]
Fantastic, congrats!!

**Comment by ViralBShah** [comment]
Congrats Dr. Bezanson!

**Comment by ViralBShah** [comment]
The thesis, for those who'd like to take a peek:

https://github.com/JeffBezanson/phdthesis/blob/master/main.pdf

**Comment by tonyhffong** [comment]
Congrats!

**Comment by mattjj** [comment]
Congratulations!

**Comment by lindahua** [comment]
Congratulations!

**Comment by Gnimuc** [comment]
Congrats :+1:

**Comment by jiahao** [comment]
![2015-05-13 13 11 16](https://cloud.githubusercontent.com/assets/1732/7625140/c00d36c8-f9c1-11e4-98a0-3fda3d0cb9ab.jpg)

![2015-05-13 14 00 17](https://cloud.githubusercontent.com/assets/1732/7625139/c00b3634-f9c1-11e4-8bc7-0869bf8efe3f.jpg)
   
![2015-05-13 14 26 23](https://cloud.githubusercontent.com/assets/1732/7625133/b6854078-f9c1-11e4-8686-fe19d972077a.jpg)

![2015-05-13 14 45 00](https://cloud.githubusercontent.com/assets/1732/7625126/a8638b76-f9c1-11e4-91df-cf14a836ae2f.jpg)

![2015-05-13 14 46 56](https://cloud.githubusercontent.com/assets/1732/7625127/ac4c5e5c-f9c1-11e4-8843-59050ffa98a6.jpg)

Issue closing ceremony video: http://youtu.be/hGpLOZX6CEY

**Comment by staticfloat** [comment]
Aleph-zero congratulations to you, Jeff!  If you're ever in Seattle, let me buy you a congratulatory drink.  :)

**Comment by amitmurthy** [comment]
Congrats Jeff. It feels very nice to celebrate your work as a community.

**Comment by tkelman** [comment]
Congratulations!

@jiahao, might be worth re-running the latest [world of Julia](https://github.com/jiahao/ijulia-notebooks/blob/master/2014-06-30-world-of-julia.ipynb) as supplementary material for the acknowledgements page :)

**Comment by JeffBezanson** [comment]
Thank you everybody.

Unfortunately my thesis is not actually done, but hopefully will be soon...

**Comment by ScottPJones** [comment]
I've got a couple more pictures, I'll be sending them on to Jeff after I wake up (for his mother, a very nice lady!) *Dr.* Bezanson can post them here if he wishes...

**Comment by ScottPJones** [comment]
Not done???  Did Gerry ask you to remove all of that bloody "syntax" and just let him write with s-expressions?

**Comment by ViralBShah** [comment]
@JeffBezanson using a mac is not a picture I ever expected to see!

**Comment by carlobaldassi** [comment]
Yay!

**Comment by dancasimiro** [comment]
Congratulations

**Comment by sherrinm** [comment]
Well done from all your fans this side of the pond.

**Comment by JeffBezanson** [comment]
> Not done??? Did Gerry ask you to remove all of that bloody "syntax" and just let him write with s-expressions?

You nailed it! I'm not kidding. But he will settle for an optional s-expr mode.

**Comment by ScottPJones** [comment]
I’d been talking to him after the presentation... he liked your stuff, but really didn’t care for all the syntax... there’s just *so* much of it... he reminded me of how small the Scheme manual is :grinning:  When I had him for 6.001 [first semester it was taught], we had to implement a small Scheme interpreter in MacLisp... since Scheme was so small, it was pretty doable...

**Comment by ScottPJones** [comment]
and I’m sure you can knock that out pretty quickly, with that bottle of bourbon for company (if there’s any left! ;-) )

**Comment by JeffBezanson** [comment]
Speaking of the length of the scheme manual, it's funny: a large percentage of it is devoted to documenting the behavior of numbers, while in Julia that's defined in libraries. Julia could potentially be a smaller core language than scheme (unless of course you stapled the LLVM spec to it).

For it or against it, there's too much emphasis on syntax! Also check out section 7.1 of http://www.schemers.org/Documents/Standards/R5RS/HTML/. Scheme syntax is more complex than people think!

**Comment by ScottPJones** [comment]
>Julia could potentially be a smaller core language than scheme (unless of course you stapled the LLVM spec to it).

Yes, Julia has good bones!

**Comment by toivoh** [comment]
Time to dig out the old `@sexpr` macro?

**Comment by trezitorul** [comment]
Congratulations on graduating and on what you pulled out with Julia!

**Comment by yurivish** [comment]
:cake: Congratulations!

**Comment by boyers** [comment]
Congrats @JeffBezanson!

**Comment by dustinvtran** [comment]
congratulations :)

**Comment by interhive** [comment]
:+1:

**Comment by StefanKarpinski** [comment]
@boyers! Long time no see!

**Comment by boyers** [comment]
miss you guys :)

**Comment by nicola-gigante** [comment]
Congratulations!

Just a question: the PDF does not have links in the ToC nor an browsable index in the pdf metadata.
Why is it so difficult for a MIT-graduated compiler-writer to add \usepackage{hyperref} in his preamble?

**Comment by ViralBShah** [comment]
That is because you are supposed to read the whole thing and not just skip around. ;-)

But yes, hyperref would make this a lot more accessible.

**Comment by nicola-gigante** [comment]
I promise you to read the whole thing if you add the links :P

**Comment by rtoip** [comment]
Congratulations. Freedom awaits.

**Comment by nlazarevic** [comment]
Congrats, Dr. Bezanson!

**Comment by timholy** [comment]
@nicola-gigante, you can make a pull request :smile:.

**Comment by jpfairbanks** [comment]
can we lobby for a best dissertation award? 

http://awards.acm.org/doctoral_dissertation/nominations.cfm

**Comment by mseri** [comment]
Congratulation!!!

**Comment by ScottPJones** [comment]
@jpfairbanks - good idea!  It has to be submitted by his thesis advisor though... pester Alan Edelman, I think...

**Comment by jpfairbanks** [comment]
Yeah it needs nomination by the advisor and 5 letters of support. Based on
this issue I think at least 5 people think he deserves it.

**Comment by ScottPJones** [comment]
Is it limited to 5 letters of support?  Also, the real number of people who think he deserves it is at least a few orders of magnitude larger!

**Comment by ninjin** [comment]
@JeffBezanson: Congratulations!

@alanedelman: I think @jpfairbanks has a good point, Jeff should get nominated for the [ACM Doctoral Dissertation Award](http://awards.acm.org/doctoral_dissertation/nominations.cfm).

**Comment by hayd** [comment]
@JeffBezanson Well done and well deserved!

@ScottPJones "In addition, at least 3, and not more than 5, supporting letters should be included from experts in the field who can provide additional insights or evidence of the dissertation’s impact."

**Comment by ScottPJones** [comment]
Maybe Gerry will write him one (after he's added the s-expr mode!) :grinning:

**Comment by fabianlischka** [comment]
Hacker News front page :-) Congratulations, Jeff.

**Comment by JeffBezanson** [comment]
@nicola-gigante You're right, I will add hyperref.

Thank you to everybody again. All of your appreciation is the ultimate prize.

**Comment by owenversteeg** [comment]
@jiahao It's because they have EXIF rotation data which browsers don't care about. Most of the time. Chrome only cares about EXIF data if the picture is its own window. Right click and "Open in new tab" to see them the correct orientation.

**Comment by ViralBShah** [comment]
+1 for the ACM dissertation award nomination.

**Comment by ViralBShah** [comment]
Nomination deadline is Oct 31, 2015.

http://awards.acm.org/doctoral_dissertation/nominations.cfm

I don't like it that ACM requires a copyright transfer to them and exclusive publication rights. It is still valuable and prestigious in any case.

**Comment by Funfun** [comment]
Congrats!

**Comment by ScottPJones** [comment]
Exclusive publication rights!?!  I've got dibs on an autographed copy (or two... need one to sell on e-bay in 10-15 years, another to keep for myself :grinning:)... got to get that before it's locked up by the ACM!
(Of course, that probably means that it would be available on the ACM's digital library for members)

**Comment by alanedelman** [comment]
once dissertation is handed to me to sign I have every intention
of nominating the dissertation for various awards :-)

**Comment by ScottPJones** [comment]
No comments from @JeffBezanson... I *hope* he's celebrating (more checking off his last box), and hasn't been locked in a room somewhere by GJS until he gets an s-expr mode working!

**Comment by dikshie** [comment]
Congratulations!

**Comment by mbaz** [comment]
Congratulations, @JeffBezanson!

**Comment by milktrader** [comment]
(belated) Congrats!

**Comment by JeffBezanson** [comment]
Update: just submitted the document. The submitted version is https://github.com/JeffBezanson/phdthesis/tree/876be73a5aab9b034fac3eb9ea9d8f96713f786f .

I'm sure it's deficient in many ways. Oh well. Hopefully there is nothing really bad in there.

**Comment by johnmyleswhite** [comment]
Nice. Congrats on truly finishing your PhD.

**Comment by Keno** [comment]
Congratulations, Jeff! Great accomplishment. I'm sure you're glad it's over.

**Comment by StefanKarpinski** [comment]
![party](https://cloud.githubusercontent.com/assets/153596/7736216/3ba0ff10-ff10-11e4-8c4d-f375bc557695.jpg)

**Comment by timholy** [comment]
I've already found your thesis fills some holes in Julia's documentation, so it's clearly going to be quite useful. All documents come with flaws; the rest of us are impressed by the strengths! Congrats!

**Comment by milktrader** [comment]
And thank you for sharing it!

**Comment by ssfrr** [comment]
Woot! Congratulations on finishing the defense and thesis, and all the other work that they signify and represent. It's nice to have this milestone to recognize all the things you've accomplished. I hope you're proud!

**Comment by ViralBShah** [comment]
@JeffBezanson I hope you are planning to take a few days off to chill and celebrate, or perhaps you are planning to celebrate with type system overhaul or something. :-)

Nice that the new pdf has hyperref - for those wanting to browse. We should also get it up on the julia publications list.
