### ISSUE TITLE
Can we merge two assert statements?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#8856]
So we have `@assert`

``` julia
julia> @assert 1==2 "It doesnt"
ERROR: assertion failed: It doesnt
 in error at error.jl:21
```

and `assert`, which can't take a second argument,

``` julia
julia> assert(1==2)
ERROR: assertion failed
```

Is there any need to keep both?

**Comment by IainNZ** [comment]
Could be good to have PR that deprecates the `assert` form, and just leaves the macro version. Then the macro version could annotate the expression so that it could be, e.g. not run in a "high performance" mode

**Comment by michele-zaffalon** [comment]
Beginner's questions:
* does this imply going through the code and replacing each `assert` with `@assert` and adding it to `deprecated.jl`? I assume not: I quickly did so and it was not sufficient.
* what is the annotation you talk about?
I can give this issue a try if someone can give some guidance.

**Comment by tkelman** [comment]
> I quickly did so and it was not sufficient.

In what way was it not sufficient? What happened vs what did you expect?

I don't think the annotation exists as such yet, but there has been talk and one or two other issues on the idea of using compiler options or flags to set different debugging levels for whether assertion statements get skipped, etc. If people want to make asserts fancier in the future, would be easier if it only had to be done to the macro form instead of both the macro and the function.

**Comment by IainNZ** [comment]
@michele-zaffalon 

My vision was, for the deprecation, to
* deprecate `assert()`
* make `@assert` call an internal `_assert()` (if thats even needed)
* replace usages in Base of `assert` with `@assert`

For annotation, I know that [`@simd` does something with `$(Expr(:simdloop))`](https://github.com/JuliaLang/julia/blob/b78659ea1c342346f600e685c87b78945f984024/base/simdloop.jl#L53-L90), and I assumed there was something similar for `@inbounds`, so such a thing would seemingly work for `@assert`. Alternatively, `@assert` generates code that tests if a constant global if true or false, and then the compiler would remove the dead code if its false.

**Comment by michele-zaffalon** [comment]
@tkelman Here is what I did:
* added `assert` to `deprecated.jl`
* removed `assert` from `exports.jl`
* replaced `assert` with `@assert` in `inference.jl`
* built julia: all goes fine

When I do `make testall`, I get the following:
```
michele@gulliver:~/projects/julia/julia$ make testall
cp /home/michele/projects/julia/julia/usr/lib/julia/sys.so local.so && /home/michele/projects/julia/julia/usr/bin/julia -J local.so -e 'true' && rm local.so
WARNING: assert(x) is deprecated, use @assert(x) instead.WARNING: error initializing module Base:
OutOfMemoryError()
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
rec_backtrace at /home/michele/projects/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
jl_throw at /home/michele/projects/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x7f08ba3e099c)
unknown function (ip: 0x7f08ba3e09a9)
uv_writecb_task at stream.jl:924
jlcapi_uv_writecb_task_20924 at  (unknown line)
uv__stream_destroy at /home/michele/projects/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: (nil))
Makefile:514: recipe for target 'testall' failed
make: *** [testall] Terminated
Terminated
```

**Comment by michele-zaffalon** [comment]
@IainNZ There doesn't seem to be a need for an `_assert` function, but you people are more experienced and knowledgeable, so you say what I have to do.

For the second part, I am not good enough to do it myself.

**Comment by JeffBezanson** [comment]
Triage thinks we should deprecate `assert` (the function form). It's more consistent with e.g. the new logging macros.

**Comment by StefanKarpinski** [comment]
Triage accepts: deprecate `assert` to use the `@assert` macro.

**Comment by twadleigh** [comment]
I'll take a stab at this today.

**Comment by StefanKarpinski** [comment]
Closed by https://github.com/JuliaLang/julia/pull/26194.
