### ISSUE TITLE
invoke broken for constructors

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#8861]
More fallout from #8712:

```
julia> type A; end

julia> invoke(A, ())
ERROR: type: invoke: expected Function, got Type{A}

julia> method_exists(A, ())
ERROR: type: method_exists: expected Function, got Type{A}

julia> applicable(A)
ERROR: type: applicable: expected Function, got Type{A}
```

Maybe `method_exists` and `applicable` are not so useful since they would always be true for constructors due to the `call` fallback, but `invoke` still seems useful. This can currently be worked around as `invoke(call, (Type{A},), A)`, but it would be nice if this weren't necessary.

**Comment by JeffBezanson** [comment]
Fixed by #13412.
