### ISSUE TITLE
readdlm() doesn't properly close file when file opened with a string

### ISSUE THREAD

**Issue by dahlend** [JuliaLang/julia#8891]
`A = readdlm("./data.csv")`

This will read the file data.csv properly, however it doesn't close the file upon completion.

```
file_location = file("./data.csv")
A = readdlm(file_location)
close(file_location)
```

works fine, however I wasn't sure if in the first case was a bug or just poor programming on my part.

**Comment by ViralBShah** [comment]
It seems that this is fixed.

**Comment by JeffBezanson** [comment]
I think when we use mmap the file isn't closed until the next GC.

**Comment by StefanKarpinski** [comment]
http://stackoverflow.com/questions/34394361/julia-limit-on-the-number-of-files-open-while-using-readdlm

**Comment by felipenoris** [comment]
Just ran into this today. Your OS is not windows, but I think mmap + NFS causes this.

Use this and this should be fixed.
```
A = readdlm("./data.csv"; use_mmap=false)
```
https://github.com/JuliaLang/julia/pull/7007 did put a default `use_mmap=false` on windows, this looks like a file-system specific problem. Should we add a comment on the help of readdlm function?

**Comment by felipenoris** [comment]
... or even put `use_mmap=false` for every system.
