### ISSUE TITLE
Minor addition to error reporting

### ISSUE THREAD

**Issue by mardukbp** [JuliaLang/julia#8894]
Assuming the programmer is a newcomer to programming, e.g. physics students learning julia, the following are common mistakes that need a good explanation from the julia parser in order to save programmer time and frustration. 

**Example one:**
The programmer declares the variable `foo` to be an array and later tries to access an element of the array with `foo(3)`. The julia parser gives both an explanation suitable for an expert and an explanation  understandable to a newbie.

**Example two:**
The programmer defines a function `myfun` and later calls it with `myfun[x,y]`. This time the julia parser returns only an explanation for the expert. My suggestion: add a message along the lines of **Use parenthesis for calling functions.**

This happens with julia 0.3.2. Haven't tried julia 0.4.

**Comment by jakebolewski** [comment]
closing in favor of #7512.
