### ISSUE TITLE
why is precision defined for DateTime?

### ISSUE THREAD

**Issue by nolta** [JuliaLang/julia#8898]
```jlcon
julia> precision(DateTime())
Millisecond

julia> precision(Date())
Day

julia> help(precision)
Base.precision(num::FloatingPoint)

   Get the precision of a floating point number, as defined by the
   effective number of bits in the mantissa.
```

cc @quinnj

**Comment by quinnj** [comment]
So I'm trying to make this change but running into a weird deprecation error; am I doing something dumb?
Error:
```julia
deprecated.jl
error during bootstrap:
LoadError(at "sysimg.jl" line 280: LoadError(at "deprecated.jl" line 292: ErrorException("invalid usage of @deprecate")))
rec_backtrace at /Users/jacobquinn/julia/src/task.c:601
eval at /Users/jacobquinn/julia/usr/lib/libjulia.dylib (unknown line)
jl_parse_eval_all at /Users/jacobquinn/julia/src/toplevel.c:550
jl_load at /Users/jacobquinn/julia/src/toplevel.c:592
include at boot.jl:249
jl_apply at /Users/jacobquinn/julia/src/./julia.h:1067
anonymous at sysimg.jl:152
jl_apply at /Users/jacobquinn/julia/src/interpreter.c:53
eval at /Users/jacobquinn/julia/src/interpreter.c:215
jl_toplevel_eval_flex at /Users/jacobquinn/julia/src/toplevel.c:502
jl_eval_module_expr at /Users/jacobquinn/julia/src/toplevel.c:148
jl_toplevel_eval_flex at /Users/jacobquinn/julia/src/toplevel.c:394
jl_parse_eval_all at /Users/jacobquinn/julia/src/toplevel.c:550
jl_load at /Users/jacobquinn/julia/src/toplevel.c:592
exec_program at /Users/jacobquinn/julia/usr/bin/julia (unknown line)
true_main at /Users/jacobquinn/julia/usr/bin/julia (unknown line)
main at /Users/jacobquinn/julia/usr/bin/julia (unknown line)

make[1]: *** [/Users/jacobquinn/julia/usr/lib/julia/sys0.o] Error 1
make: *** [release] Error 2
jquinn-ml-2:julia jacobquinn$ 
```
deprecated.jl:291
```julia
@deprecate Base.Dates.precision Base.Dates.unit
```

**Comment by ivarne** [comment]
You need to write

```julia
@deprecate precision(dt::Dates.Date) Dates.unit(dt)
@deprecate precision(dt::Dates.DateTime) Dates.unit(dt)
```
`precision` will still exist as a function for FloatingPoint numbers.

**Comment by quinnj** [comment]
Hmmm, I had already tried something like that, but I'm still getting
```julia
deprecated.jl
error during bootstrap:
LoadError(at "sysimg.jl" line 280: LoadError(at "deprecated.jl" line 291: UndefVarError(var=:Dates)))
rec_backtrace at /Users/jacobquinn/julia/src/task.c:601
jl_undefined_var_error at /Users/jacobquinn/julia/usr/lib/libjulia.dylib (unknown line)
eval at /Users/jacobquinn/julia/src/interpreter.c:121
do_call at /Users/jacobquinn/julia/src/interpreter.c:62
eval at /Users/jacobquinn/julia/src/interpreter.c:215
do_call at /Users/jacobquinn/julia/src/interpreter.c:62
eval at /Users/jacobquinn/julia/src/interpreter.c:215
do_call at /Users/jacobquinn/julia/src/interpreter.c:62
eval at /Users/jacobquinn/julia/src/interpreter.c:215
eval at /Users/jacobquinn/julia/src/interpreter.c:300
jl_toplevel_eval_flex at /Users/jacobquinn/julia/src/toplevel.c:502
jl_toplevel_eval_flex at /Users/jacobquinn/julia/src/toplevel.c:449
jl_parse_eval_all at /Users/jacobquinn/julia/src/toplevel.c:550
jl_load at /Users/jacobquinn/julia/src/toplevel.c:592
include at boot.jl:249
jl_apply at /Users/jacobquinn/julia/src/./julia.h:1067
anonymous at sysimg.jl:152
jl_apply at /Users/jacobquinn/julia/src/interpreter.c:53
eval at /Users/jacobquinn/julia/src/interpreter.c:215
jl_toplevel_eval_flex at /Users/jacobquinn/julia/src/toplevel.c:502
jl_eval_module_expr at /Users/jacobquinn/julia/src/toplevel.c:148
jl_toplevel_eval_flex at /Users/jacobquinn/julia/src/toplevel.c:394
jl_parse_eval_all at /Users/jacobquinn/julia/src/toplevel.c:550
jl_load at /Users/jacobquinn/julia/src/toplevel.c:592
exec_program at /Users/jacobquinn/julia/usr/bin/julia (unknown line)
true_main at /Users/jacobquinn/julia/usr/bin/julia (unknown line)
main at /Users/jacobquinn/julia/usr/bin/julia (unknown line)
```

**Comment by stevengj** [comment]
I still strongly prefer `eps` to defining a new function `unit` that means exactly the same thing.

**Comment by quinnj** [comment]
Note that unit wouldn’t be exported from Dates, so the usage would always
be Dates.unit(x::Date). It seemed there was more votes for unit in the
discussion above, but I’d be ok with going with eps if the votes swing that
way.
​

**Comment by stevengj** [comment]
In which case `eps` also has the benefit of being much easier to type.

**Comment by stevengj** [comment]
Regarding "counting votes", one concern is that some of the "anti-`eps`" votes were based on demonstrable misunderstandings of what `eps` is: that it is about continuity (it is about discreteness), it is "a very small value" whereas the unit of a date is "not small" (smallness is a relative concept), that its definition is somehow inherently tied to floating-point semantics (`x+eps != x` translates easily).   And then there were simply the "+1" votes with no comments.  Overall, I don't think a simple count is helpful.

**Comment by ivarne** [comment]
@quinnj That errror is because of the order we include `deprecated.jl` and `Dates.jl` in [base/sysimg.jl](https://github.com/JuliaLang/julia/blob/030e30cb68c54f505f43469792cacfb64b53c260/base/sysimg.jl#L279-295). Moving `deprecated.jl` to the end seems to fix the issue for me.

**Comment by StefanKarpinski** [comment]
Are we going to also define `eps(::Integer) = 1`? Are we going to use that in generic code? I just have a hard time imagining where someone is going to write code that uses `eps` that applies equally to floating-point values and dates.

**Comment by stevengj** [comment]
@StefanKarpinski.  We won't define `eps(::Integer) = 1` simply because it is not useful.  We don't define all mathematically possible methods of all functions; this is no different.

The reason to use `eps` here is not for generic code, but rather it is simply that we shouldn't define a new name for this functionality when we already have a perfectly good, short, unambiguous name.

**Comment by StefanKarpinski** [comment]
Alright. This feels a bit funny (@JeffBezanson agrees), but let's see how it goes.

**Comment by quinnj** [comment]
#yolo
