### ISSUE TITLE
spawn should try not to spawn local indexing operations

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#89]
In a statement like

```
@spawn f(A[I,J], B[I,K])
```

if `A` is a local array the indexing should be done locally so only part of the array is sent elsewhere.
A good approach might be to lower this as follows:

```
if isa(A, Array)
    sub = A[I,J]
    thk = ()->sub
else
    thk = ()->A[I,J]
end
@spawn f(thk(), ...)
```

**Comment by vtjnash** [comment]
Seems not an issue for here anymore
