### ISSUE TITLE
coverage broken for Windows

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#8911]
The coverage feature of Julia appears not to work under Windows 8.1 64-bit.  I believe this is a platform-specific issue because Tim Holy tried the same test as me and succeeded on a different platform.

In more detail, I downloaded the latest Windows binary build (10-day old master, 0.4.0-1318) of Julia, added two packages, DataStructures and Clustering, and then I tried all of the following:

     julia --code-coverage
    Pkg.test("DataStructures")
    Pkg.test("Clustering")

     juila
    Pkg.test("DataStructures", coverage=true)
    Pkg.test("Clustering", coverage=true)

and finally

    julia --code-coverage
    Pkg.test("DataStructures, coverage=true)
    Pkg.test("Clustering", coverage=true)

I did not get .cov files for any of the .jl files associated with either of these packages.  Instead, I got some .cov files associated with base .jl files, e.g., random.jl.cov.  I searched for cov files by going to c:\Users\<username> and typing "dir *.cov /S":  (I also tried this with the /a:h and /a:s flags just in case the .cov files are hidden in Windows).

Thanks,
Steve Vavasis

**Comment by tkelman** [comment]
Should be fixed by #9747. Give it a try when new nightlies are ready.
