### ISSUE TITLE
DArray : memory not fully recovered upon gc()

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#8912]
DArrays do not seem to be fully garbage collected.

context: https://groups.google.com/d/msg/julia-users/O8-Axv7wVZE/Xe-_8LIGKhAJ

**Comment by denizyuret** [comment]
Here are a couple of more problem reports for reference:
https://groups.google.com/d/topic/julia-users/q39vyGQF4Fs/discussion
https://groups.google.com/d/topic/julia-users/zsT2qfwDuHA/discussion

As a workaround, removing all the workers (rmprocs(workers())) and restarting them (addprocs(ncpu)) every iteration seems to work.

I suspect the problem may go deeper than distributed arrays: In my case the distributed array is not that big, but the result I fetch from the workers (via pmap) is.  The memory usage is consistent with those fetched values not being properly garbage collected.  I will post a simple example to replicate if I can come up with one.

**Comment by denizyuret** [comment]
OK, here is the example:
```
mypid = ccall((:getpid, "libc"), Int32, ())
addprocs(10)
for i=1:10
    p=pmap(workers()) do x
        rand(1<<27)
    end
    p=nothing
    @everywhere gc()
    run(pipe(`ps auxww`,`grep $mypid`))
end
```

and here is the output (10GB memory added to master every iteration):
```
dyuret   31594  4.3  4.0 19759168 10685080 pts/2 Rl+ 21:19   0:12 julia
dyuret   31594  6.1  8.0 30292596 21218468 pts/2 Sl+ 21:19   0:17 julia
dyuret   31594  7.8 11.9 40782492 31708344 pts/2 Sl+ 21:19   0:23 julia
dyuret   31594  9.4 15.9 51276484 42202348 pts/2 Sl+ 21:19   0:28 julia
dyuret   31594 10.9 19.9 61762284 52688156 pts/2 Sl+ 21:19   0:33 julia
dyuret   31594 12.3 23.8 72248084 63173968 pts/2 Sl+ 21:19   0:39 julia
dyuret   31594 13.7 27.8 82733884 73659792 pts/2 Sl+ 21:19   0:44 julia
dyuret   31594 15.1 31.7 93219684 84145604 pts/2 Sl+ 21:19   0:49 julia
dyuret   31594 16.4 35.7 103705484 94631416 pts/2 Sl+ 21:19   0:54 julia
dyuret   31594 17.7 35.7 103705484 94631424 pts/2 Sl+ 21:19   0:59 julia
```

**Comment by samuela** [comment]
What's the status on this? Until we have a fix, this issue seems significant enough to warrant labeling DArrays as an experimental feature. At the very least I think something should be mentioned about this in the docs.

**Comment by jiahao** [comment]
@samuela DArrays no longer exist in base.

**Comment by samuela** [comment]
Oh, cool beans! Should this issue be closed then? What should be used in place of DArrays now?

**Comment by pao** [comment]
https://github.com/JuliaParallel/DistributedArrays.jl took over the DArray code.

I'm not sure where the actual issue lies, but since it's been crossreferenced by folks who should have some idea, I'll leave this open.

**Comment by amitmurthy** [comment]
After https://github.com/JuliaLang/julia/commit/3bbc5fc0d0320dad603e211bc4564250b9a16649

```
mypid = getpid()
addprocs(10)
for i=1:200
    p=pmap(workers()) do x
        ones(10^7)
    end
    p=nothing
    @everywhere gc()
    run(pipe(`ps auxww`,`grep $mypid`))
end
```

I find that the master slowly grows to around 10GB of resident memory after 20 iterations which holds steady for the next 180 iterations. This 10GB is not released even after all the iterations complete.

@carnaval , @vtjnash any explanation for this?

**Comment by vtjnash** [comment]
it seems possible that `gc()` is just not getting called enough locally to propagate the gc messages, but I'm not sure that fully explains it.

**Comment by jakebolewski** [comment]
why would that impact memory usage on the master node?

**Comment by amitmurthy** [comment]
With 

```
julia> using DistributedArrays

julia> for i in 1:100
         d=dones(2*10^8)
         a=convert(Array,d)
         @everywhere gc()
       end
```

`top` shows 
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                             
 4459 amitm     20   0 19.787g 5.408g   2160 R  91.1 34.7   1:07.21 julia                                                                                               
 4467 amitm     20   0 14.397g 4.622g  10132 S  19.0 29.7   0:14.08 julia                                                                                               
 4468 amitm     20   0 13.001g 2.461g  10124 S  18.3 15.8   0:13.14 julia
```

with the master process varying between 30% to 40% of system memory and the workers between 15% to 30%

It is no longer a leak, the loop runs to completion, but at the end, the memory is not being released. Does libuv or the malloc implementation cache memory buffers anticipating future use? 

I'll try and test the stuff on OSX later in the day to see if the behavior is limited to Linux.

**Comment by vtjnash** [comment]
libuv tries really hard not to allocate anything. but malloc and the julia gc will hold onto some amount of memory. 10GB sounds a bit high. although, i guess if there was something on every page, it would have trouble releasing the memory fully.

**Comment by amitmurthy** [comment]
@vtjnash , can you take a look at https://github.com/JuliaLang/julia/issues/10960 sometime? While debugging parallel code, it is a little difficult to proceed when there is no guarantee that finalizers on RemoteRefs are being called in all circumstances.

**Comment by amitmurthy** [comment]
closed by https://github.com/JuliaLang/julia/commit/6b94780328ad81326de28024ad45c26a69197ffe
