### ISSUE TITLE
Check for trailing white space also outside Travis

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#8917]
I notice that Julia's regular build doesn't even warn about trailing white space, while Travis treats this as fatal error. That makes debugging trailing white space quite difficult. Personally, I'd have put this check into the Makefile, not the .travis file.

Also -- there's no file name nor line number associated with this error.

I have nothing against forbidding trailing white space, nor anything against enforcing it, but the way it's implemented leaves to be desired.

**Comment by tkelman** [comment]
Guess I'll do this, since it seems no one else wants to.
