### ISSUE TITLE
llvmcall translates pointer to NTuple in Julia to pointer to vector in LLVM

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#8921]
Given a type such as `UInt64x2 = NTuple{2,UInt64}`, it seems that `llvmcall` will translate e.g. an argument of type `Ptr{UInt64x2}` on the Julia side to an argument of type `<2 x i64>*` on the LLVM side.

Indeed, `UInt64x2` in Julia seems to map to `<2 x i64>` in LLVM, but this is no longer true for the pointer types, since an array of tuples is currently not stored packed inline. Thus the following code

    typealias UInt64x2 (UInt64, UInt64)
    function unsafe_load(x::Vector{UInt64x2})
        Base.llvmcall("""%2 = load <2 x i64>* %0
                         ret <2 x i64> %2""",
                      UInt64x2, (Ptr{UInt64x2},), x)
    end

    x = convert(Vector{UInt64x2}, [(1,2),(3,4),(5,6),(7,8)])
    @show unsafe_load(x)

prints for me e.g.

    unsafe_load(x) = (0x00000000061d1660,0x00000000061d1680)

yielding the pointers to the first two tuples, and not the contents of the first tuple.

I argue that `llvmcall` should not map e.g. `Ptr{UInt64x2}` to `<2 x i64>*`, as long as they are not the same. (Or `pointer` on an `Array{UInt64x2}` should not produce a `Ptr{UInt64x2}`, but that seems less reasonable.)

**Comment by vtjnash** [comment]
Tuples now always map too llvm arrays for normal datatypes. Specially marked datatypes (#15244) are going to be required to create vectors. plus, the updated version of this code produces the correct answer now following the tuple rewrite:

```julia
julia> function unsafe_load(x::Vector{UInt64x2})
           Base.llvmcall("""%2 = load [2 x i64]* %0
                            ret [2 x i64] %2""",
                         UInt64x2, Tuple{Ptr{UInt64x2},}, Base.unsafe_convert(Ptr{UInt64x2},x))
       end
WARNING: Method definition unsafe_load(Array{Tuple{UInt64, UInt64}, 1}) in module Main at none:2 overwritten at none:2.
unsafe_load (generic function with 1 method)

julia> @show unsafe_load(x)
unsafe_load(x) = (0x0000000000000001,0x0000000000000002)
(0x0000000000000001,0x0000000000000002)
```
