### ISSUE TITLE
Segfault when using `call` as variable

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#8930]
Another silly bug in line of #8785, again genuinely encountered by accidentally naming a variable `call`:
```julia
macro wrap(call::Expr)
    call.args...
end

@wrap foo(bar)
```
```
$ julia /tmp/repro.jl 

signal (11): Segmentation fault
```

It happens when expanding `call.args` using `...`. Curiously, no warning about overriding `call`.

When done in function scope, an assertion is tripped instead. Also differently, there is a warning about overwriting `call`:
```julia
call = :(foo(bar))
println(call.args...)
```
```
$ julia /tmp/repro.jl 
Warning: imported binding for call overwritten in module Main
julia: builtins.c: jl_value_t *jl_f_apply(jl_value_t *, jl_value_t **, uint32_t): Assertion `((((jl_value_t*)(call_func))->type)==(jl_value_t*)(jl_function_type))' failed.

signal (6): Aborted
```

**Comment by ihnorton** [comment]
Appears to be fixed. Please comment if not.
