### ISSUE TITLE
replace current help system with new docstrings

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#8967]
From #8791.

Requires a way to insert the documentation back into the manual.  Probably (as suggested by @StefanKarpinski) this should be done manually (no pun intended): in the manual, there should be placeholders `@doc:foo` (or whatever) that get preprocessed to substitute the docstring (formatted appropriately, e.g. for rst).

**Comment by kshyatt** [comment]
We still have stuff in HelpDB ... should this issue remain open?

**Comment by stevengj** [comment]
I think this should be closed; for some time, we have had a way to insert docstrings into the rst manual via placeholders.  Further improvements to the manual/docstring integration can be raised in a separate issue.
