### ISSUE TITLE
julia-mode.el: Increase indent by one tab stop inside parens

### ISSUE THREAD

**Issue by Wilfred** [JuliaLang/julia#8971]
As discussed in #8924. The question is between lining up with the paren (the current behaviour):

```
    help_mode = Prompt("help?> ",
                       prompt_prefix = hascolor ? repl.help_color : "",
                       prompt_suffix = hascolor ?
```

or just increasing by one indentation level:

```
    help_mode = Prompt("help?> ",
        prompt_prefix = hascolor ? repl.help_color : "",
        prompt_suffix = hascolor ?
```

We could make this a configurable setting, but it seems to me that there's clear consensus for the latter.

I agree that the latter is nicer, though I can see a corner case:

```
for x in foobar(some_long_argument,
                another_long_argument)
    do_stuff!(x)
end
```

If we simply indent by one indentation level, it's a little more confusing between function arguments and the loop body:

```
for x in foobar(some_long_argument,
    another_long_argument)
    do_stuff!(x)
end
```

**Comment by pwl** [comment]
+1 for indenting one or two levels as line continuation (although one level of indentation might blend the arguments with the contents of the function).  Also the current indentation system doesn't work flawlessly (see #9831), so it might be a good time to rewrite it.

**Comment by yuyichao** [comment]
Covered by https://github.com/JuliaLang/julia-emacs/issues/11
