### ISSUE TITLE
printf scientific notation performance regression

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#8972]
```julia
 function f()
    io = IOBuffer()
    for i = 1:100000
        @printf io "%e" 28.0
    end
end
```

On Julia 0.3:

```
julia> @time f()
elapsed time: 0.078705771 seconds (4195572 bytes allocated)
```

On Julia 0.4:

````
julia> @time f()
elapsed time: 2.91291863 seconds (290595572 bytes allocated, 45.76% gc time)
```

`@profile` suggests the time is spent in grisu's GMP codepath, so I'm guessing #7291 is the culprit. cc @quinnj

**Comment by JeffBezanson** [comment]
Bump. This is pretty serious.

**Comment by quinnj** [comment]
Status update: I've gotten a 5x improvement so far after a first pass. I'm still seeing some gc action in profiling so I'm going to keep digging.

**Comment by JeffBezanson** [comment]
Awesome, thanks.

**Comment by JeffBezanson** [comment]
@quinnj would it make sense to commit your 5x improvement? As it stands, this regression is probably bad enough to block 0.4.

**Comment by quinnj** [comment]
I want to run the full grisu testing suite on my changes first; I'll make a PR tomorrow after it runs.

**Comment by quinnj** [comment]
PR coming later tonight! (once I fix a few tests)
