### ISSUE TITLE
Linking nvblas.so instead of libopenblas.so.0

### ISSUE THREAD

**Issue by hyperboloid77** [JuliaLang/julia#9006]
Hello,

I am trying to compile Julia with nvblas instead of libopenblas (nvblas is roughly 6x faster with big Float32 matrix products on GTX760 than on i7 quadcore), but I get the following error:

...
    CC ui/repl.o
    LINK usr/bin/julia
    JULIA usr/lib/julia/sys0.o
exports.jl
base.jl

...

docs.jl
printf.jl
util.jl
error during bootstrap: LoadError(at "sysimg.jl" line 234: LoadError(at "util.jl" line 118: ErrorException("error compiling blas_vendor: could not load module libnvblas: libnvblas: cannot open shared object file: No such file or directory")))
Basic Block in function 'julia_blas_vendor;8188' does not have terminator!
label %try
LLVM ERROR: Broken module, no Basic Block terminator!
make[1]: *** [/home/tokyo/.julia/julia/usr/lib/julia/sys0.o] Error 1
make: *** [release] Error 2

In order to incorporate nvblas, I made the following changes in Make.inc:

 27 USE_SYSTEM_BLAS=1

546 LIBBLAS ?= -L/usr/local/cuda-6.5/lib64 -lnvblas

547 LIBBLASNAME ?= libnvblas

That is, I have changed only three lines in Make.inc. Did I miss anything? I would appreciate if you could helped me.

The actual nvblas on my Ubuntu 14.04 PC is at

 /usr/local/cuda-6.5/lib64/libnvblas.so

More details about my computer:

Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, Ubuntu 14.04 (trusty) 3.13.0-34-generic, GeForce GTX 760 Driver 340.58, gcc 4.8 (x86_64-linux-gnu).

**Comment by ViralBShah** [comment]
What's the status of this? If CUDA BLAS is a drop in replacement for BLAS, you should be able to do so with the BLAS settings, but do make sure that you set USE_SYSTEM_LAPACK=1 as well.

Best to put any such changes in `Make.user`, so that you don't have to touch `Make.inc`. Please reopen if still an issue.
