### ISSUE TITLE
Weak values keep whole dictionary alive?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#9028]
While browsing dict.jl, I've come across this function:

```
function add_weak_value(t::Dict, k, v)
    t[k] = WeakRef(v)
    finalizer(v, x->weak_value_delete!(t, k, x))
    return t
end
```

This looks as if the lambda passed to the finalizer keeps the whole dictionary (`t`) alive. This sounds dangerous if dictionaries with weak keys are transient (which may not be the "usual" way they are used).

**Comment by oxinabox** [comment]
I think this can be closed as the problematic method `add_weak_value` no longer exists in master.
