### ISSUE TITLE
`tempname` creates file on Windows but not on *NIX

### ISSUE THREAD

**Issue by ninjin** [JuliaLang/julia#9053]
As [noted](https://github.com/JuliaLang/julia/pull/9017#issuecomment-63443005) by @tkelman.  `tempname` on Windows does not mean the same thing that it means on *NIX.  For *NIX, the relevant docs state that; ["The tmpnam() and tempnam() functions return a pointer to a file name on success, and a null pointer on error"](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man3/tempnam.3?query=tempnam&sec=3), while on Windows; ["Creates a name for a temporary file. If a unique file name is generated, an empty file is created and the handle to it is released; otherwise, only a file name is generated"](http://msdn.microsoft.com/en-us/library/windows/desktop/aa364991%28v=vs.85%29.aspx).  Should we accept this discrepancy as a part of our API?

**Comment by garborg** [comment]
This issue (and my ignorance thereof) had DataFrames.jl tests failing on Windows, FWIF.

**Comment by tkelman** [comment]
Ah, is that what that was? Yeah at the very least we need better docs here, if not some way of making these platform differences less likely to cause issues.

In response to @ninjin's 4 items [above](https://github.com/JuliaLang/julia/issues/9053#issuecomment-63925702), I'd say

1. Yeah people are going to keep getting hit by this if we don't do anything about it.
2. Probably yes. If something expects a temporary name as a string but requires it to not yet be created, these are probably not the right functions to be using. We should document this better.
3. Yes.
4. `mktempname` could work. I don't have any better ideas.

**Comment by nalimilan** [comment]
Let's add a big warning to the docs for `tempname`, and make it simply generate a random string on Windows. Anyway there's no way to make this function completely safe, people should use `mktemp`.

**Comment by tkelman** [comment]
Uh, we already have a `randstring` function. That sounds more like a vote for deprecating `tempname` and replacing it with some combination of `joinpath`, `tempdir`, and `randstring`...

**Comment by nalimilan** [comment]
Yeah, not having `tempname` and letting people doing it by hand would make it more obvious that it's not a recommended way of generating temporary files.

**Comment by JeffBezanson** [comment]
Just ran into this. Pretty annoying.

**Comment by vtjnash** [comment]
in current versions of libuv, we can use their crytographic mktempdir:
http://docs.libuv.org/en/latest/fs.html#c.uv_fs_mkdtemp
https://github.com/nodejs/node-v0.x-archive/blob/master/deps/uv/src/win/fs.c#L749

**Comment by JeffBezanson** [comment]
Conclusion from triage: deprecate this to `joinpath(tempdir(), randstring())` and warn against it.

**Comment by StefanKarpinski** [comment]
Yikes, that seems pretty nasty to use for a very common pattern. I understand that the UNIX and Windows behaviors here are annoyingly different, but shouldn't we have a portable convenient function for getting a temporary filename without doing `tempdir()` and `randstring()`?

**Comment by tkelman** [comment]
It's racy and not recommended even by posix to ask for a temporary filename without also creating the file, is it really a workflow we need to support with a named exported function?

**Comment by StefanKarpinski** [comment]
My point is that we should have a non-racy, correct way of doing this that is standard. If that involves creating the file in the process, then that's the API we should expose. Is the decision here to tell people to replace this with `joinpath(tempdir(), randstring())` but actually encourage them to use something like `mktemp` instead?

**Comment by JeffBezanson** [comment]
Exactly, this is what `mktemp` is for.
