### ISSUE TITLE
Vagrant build fails

### ISSUE THREAD

**Issue by KyleMcDowell** [JuliaLang/julia#9067]
$ git clone git://github.com/JuliaLang/julia.git
$ git checkout release-0.3
$ git submodule init
$ git submodule update

$vagrant up
(I increased the vm ram from the default 384 to 1024 and provisioning seems to execute successfully)
$jlmake

results in:

![vagrant_default](https://cloud.githubusercontent.com/assets/9848199/5110806/c328be68-6fd8-11e4-97d9-5349ed22ad6c.png)

**Comment by tkelman** [comment]
We might want to remove the vagrant stuff if we know it's bitrotted, unless someone wants to do the work to get it up to shape. This might not be a problem any more since we don't use submodules now, but leave a comment or open a new issue if you still have problems.
