### ISSUE TITLE
inconsistent Float16 printing

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#9072]
In Julia 0.3 and 0.4, I see:
```
julia> float16(44099)
float16(44100.0)

julia> a = Float16[44099]
1-element Array{Float16,1}:
 44096.0

julia> a[1]
float16(44100.0)
```

**Comment by JeffBezanson** [comment]
I still get the `Float16(44100.0)` output.

**Comment by vtjnash** [comment]
yeah, i had to revert part of it to fix some tests. i'll get back to this soon and close this again

**Comment by JeffBezanson** [comment]
I'm not sure this is fixed. Now I get

```
julia> Float16(44099)
Float16(4.41e4)

julia> Float16[44099]
1-element Array{Float16,1}:
 44096.0

julia> print_shortest(STDOUT,  Float16(44099))
44100

julia> Int(Float16(44099))
44096
```

The first output is definitely better, but it's not clear why it needs to be different from the output in the array. The output of `print_shortest` seems pretty suboptimal.

**Comment by vtjnash** [comment]
They start down different code paths that can't readily be rejoined at the end. The first attempts to compute the minimal representation, then decide on the format of the digits. The second attempts to print exactly (no more than) N digits. This causes an issue for Float16 (but not more accurate types), since it has less than 6 digits of accuracy (float has 6, double has 15)

**Comment by vtjnash** [comment]
> I'm not sure this is fixed. Now I get

those are all correct outputs now. suboptimal is perhaps just a matter of taste, since `4.41e4` would have required printing more characters, it is not the shortest representation. (`showcompact` is used in the array output to request printing of 5 digits).

**Comment by JeffBezanson** [comment]
Should we open a separate issue for `print_shortest`? It seems silly to print 44100 when the exact value 44096 is the same number of characters.

**Comment by vtjnash** [comment]
see https://github.com/JuliaLang/julia/issues/9072#issuecomment-63749483

**Comment by JeffBezanson** [comment]
Fair enough. We should edit the help text to say that it minimizes nonzeros too.

**Comment by vtjnash** [comment]
"it prints the minimum number of consecutive non-zero digits in the minimum number of characters"?

that at least is the basic description of the algorithm
