### ISSUE TITLE
getindex for BitArrays does not get inlined. 

### ISSUE THREAD

**Issue by lendle** [JuliaLang/julia#9077]
```
julia> testgetindex(v) = (@inbounds x = v[1]; x)
testgetindex (generic function with 1 method)

julia> code_llvm(testgetindex, (BitVector,))

define i1 @"julia_testgetindex;41783"(%jl_value_t*) {
top:
  %1 = call i1 @julia_getindex2385(%jl_value_t* %0, i64 1), !dbg !763
  ret i1 %1, !dbg !763
}
```
I'm surprised that I wasn't able to find an open issue about this, so hopefully this isn't a dupe.
I'm guessing this is due to the [bounds check](https://github.com/JuliaLang/julia/blob/d19405031114175b7956b7f211c700fc9913d930/base/bitarray.jl#L349)?  I don't fully understand how `@inbounds` works but I would guess this check does not go away when `@inbounds` is used.

**Comment by carlobaldassi** [comment]
I just added an `@inline` annotation to the linear-indexing `getindex` method and the difference is quite noticeable: consider a `BitArray(10^8)` and a function

```
function testgetindex(v)
    s = 0
    for i = 1:length(v)
        s += v[i]
    end
    s
end
````

then the before/after timing on my laptop is 0.37s vs 0.12s, a factor of 3.
For the record, using `Array{Bool}` the timing is 0.055s, another factor of 2.

> If you need a quick workaround, there seems to be a `Base.unsafe_bitgetindex`.

Actually `Base.unsafe_getindex` is more similar to the usual `getindex` interface, and can be used with Arrays too, so I'd suggest that until #7799 is fixed.

In the example above, the timings become 0.91s for BitArrays vs 0.35s for Arrays.

This is not to say that a `@likely`/`@unlikely` macro pair wouldn't be useful of course.
