### ISSUE TITLE
Case Issue with Pkg Manager

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/julia#9094]
Ok, this is a little bit hard to decribe. 
I have hosted a (privat) package on Bitbucket. Lets call it `TobisTestPackage`. The issue is now that the generated url is lowercased on the Bitbucket repo. When I install it using `Pkg.clone`, the created folder in `.julia` is lower cased as well (`tobistestpackage`). On Windows and OSX this seems to make no problems.
However, on linux I was not able load the package but I had to rename the folder and make it uppercase. When updating, the lowercase version is created again...

Thoughts?

**Comment by jakebolewski** [comment]
I think this is largely alleviated by https://github.com/JuliaLang/julia/pull/13542, please re-open if it is not.
