### ISSUE TITLE
Memory allocator wastes space?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#9108]
Julia allocates memory for small objects by putting them into a `gcpage_t` struct. This struct is 16384+8 bytes large when allocating via `mmap`. Also, the routine `allocb` adds `sizeof(void*)` to the number of bytes allocated. (The latter also means that memory allocated this way rarely aligned to more than 8 bytes.)

Both make it likely that the OS allocates one more page that necessary for the actual request, and uses only 8 bytes of this additional page to hold metadata.

It may be possible to reduce `GC_PAGE_SZ` by 8; this may reduce the amount of memory allocation space overhead as a simple remedy.

**Comment by carnaval** [comment]
The new allocator only uses mmap for large regions so the mentioned waste should not happen anymore.
