### ISSUE TITLE
Missing elementwise division methods

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#9113]
Some of the division functions have elementwise implementations, but others do not. For instance, `div` and `mod` will work elementwise given two arrays, but `fld`, `cld`, `rem`, and `mod2pi` are not implemented at all for arrays.  Assuming these methods were not left out intentionally, they should be implemented.

**Comment by StefanKarpinski** [comment]
Eclipsed by `div.(v,w)`.
