### ISSUE TITLE
@everywhere for broadcasting variables

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#9118]
```
addprocs(1)
foo=1
@everywhere bar=foo
```

results in
```
julia> @everywhere bar=foo
exception on 2: ERROR: foo not defined
 in eval at /home/tan/julia/julia/base/sysimg.jl:7
```

While

```
@spawnat 2 global bar=foo
remotecall_fetch(2, ()->bar)
```
works perfectly fine.

Shouldn't `@everywhere` which runs in the scope of `Main` be a perfectly appropriate method to broadcast variables?

**Comment by CorySimon** [comment]
A simple function to broadcast vars to all cores would be great!
Someone wrote a sol'n here too http://stackoverflow.com/questions/27677399/julia-how-to-copy-data-to-another-processor-in-julia/27724240#27724240

**Comment by bjarthur** [comment]
local variables can be broadcast to remote workers by preceeding `@everywhere` with an `@eval` and interpolating the symbol of the local variable:

```
julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> foo=1
1

julia> @eval @everywhere bar=$foo

julia> remotecall_fetch(()->bar,2)
1

julia> bar
1
```

shall we close this issue?

**Comment by amitmurthy** [comment]
Lets document this and then close the issue. The difference in behavior between `@spawnat` and `@everywhere` is because `@spawnat` creates a closure that is then executed remotely while `@everywhere` ships the expression as is.
