### ISSUE TITLE
Build error with Intel Compilers v15 on OSX

### ISSUE THREAD

**Issue by helgee** [JuliaLang/julia#9145]
Compilation fails with the following error message:
/Users/helge/src/julia/Make.inc:310: **\* USE_LIBCPP only supported with clang. Try setting USE_LIBCPP=0.  Stop.

**Comment by tkelman** [comment]
@Keno any idea on this one?

**Comment by Keno** [comment]
different assembly syntax?

**Comment by tkelman** [comment]
Ah, probably. Haven't other people gotten further with ICC on OSX though? Different compiler versions, or different flag settings in Make.user?

Can the OSX ICC be made to understand AT&T assembly syntax with some flag? GCC/Clang should be able to understand Intel assembly with the right directive, but manual translation is pretty tedious.

**Comment by amanoel** [comment]
Apparently, at this point it is impossible to compile Julia using ICC on OSX 10.10 (Yosemite). Versions 15 and 16 of ICC lead to the issues above, and version 14 seems to be incompatible with Yosemite libraries.

I'd imagine that, ideally, we should be able to make the code compatible with OSX ICC v16. Any ideas on how to do this?

**Comment by amanoel** [comment]
I wrote on this issue in Intel forum (https://software.intel.com/en-us/forums/topic/590285), and they've noted that the chunk of code where the issue comes from is inside a #elif _ppc_, so it shouldn't even be considered in the first place.
Thus, there might be some incorrect info in the build configuration leading to this...

**Comment by nolta** [comment]
@helgee's seeing errors in both the `#if __i386__` and `#elif __ppc__` blocks, so my guess is the C preprocessor isn't being run. AFAICT, the intel compilers only run the C preprocessor on non-C/C++ files if the extension is capitalized. So renaming `unw_getcontext.s` to `unw_getcontext.S` might fix this.

**Comment by tkelman** [comment]
That sounds like a really simple potential fix and worth trying.

**Comment by amanoel** [comment]
Okay, I've tried @nolta's solution and it seems to fix libosxunwind compilation :-)

I've cloned https://github.com/JuliaLang/libosxunwind and compiled it with make CC="icc", the same errors showed up.
Then I capitalized the .s in both unw_getcontext.s and Register.s, changed the Makefile accordingly and it compiled just fine.

Let me try compiling Julia again now.

**Comment by amanoel** [comment]
Okay, I think I'm giving up for now... After fixing the issue with libosxunwind, I had trouble with many other deps, but then I realized that beside setting the ARCH flag I also had to set BUILD_MACHINE (both depend on `icc -dumpmachine`, which on OSX returns an empty string). So basically most of my problems were solved by adding the following to the `ifeq($(OS), Darwin)` block inside Make.inc:

```Makefile
ifeq($(USEICC), 1)
    USE_LIBCPP = 0
    USECLANG = 0
    override BUILD_MACHINE := $(shell clang -dumpmachine)
    override ARCH := $(shell clang -dumpmachine | sed "s/\([^-]*\).*$$/\1/"
endif
```

I'm now having issues in compiling LLVM; the following error message appears

```
0  0x108114a44  __assert_rtn + 144
1  0x10813c5d5  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3175
2  0x10811ff81  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 375
3  0x108150102  archive::File<x86_64>::makeObjectFileForMember(archive::File<x86_64>::Entry const*) const + 758
4  0x10814fc56  archive::File<x86_64>::justInTimeforEachAtom(char const*, ld::File::AtomHandler&) const + 122
5  0x108165437  ld::tool::InputFiles::searchLibraries(char const*, bool, bool, bool, ld::File::AtomHandler&) const + 215
6  0x10816e270  ld::tool::Resolver::resolveUndefines() + 160
7  0x108170515  ld::tool::Resolver::resolve() + 79
8  0x1081155df  main + 710
A linker snapshot was created at:
        /tmp/llvm-tblgen-2015-08-07-223007.ld-snapshot
ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1]), function parse, file /SourceCache/ld64/ld64-242.2/src/ld/parsers/macho_relocatable_file.cpp, line 1748.
```
and after a bit of research I still have no idea on how to handle it... I can proceed by using `USE_SYSTEM_LLVM=1`, but then other errors related to LLVM show up eventually (perhaps because I have LLVM 3.6 installed and Julia uses LLVM 3.3).

**Comment by jdtuck** [comment]
I recently tried the above on tag v0.4.3, fixing the libosxunwind issue and 

    ifeq ($(USEICC), 1)
        USE_LIBCPP = 0
        USECLANG = 0
        override BUILD_MACHINE := $(shell clang -dumpmachine)
        override ARCH := $(shell clang -dumpmachine | sed "s/\([^-]*\).*$$/\1/") 
    endif

and I get past the llvm issue, but run into a problem with SuiteSparse

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file:  libspqr.a(spqr_parallel.o) has no symbols
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file:  libspqr.a(spqr_debug.o) has no symbols
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file:  libspqr.a(spqr_parallel.o) has no symbols
     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file:  libspqr.a(spqr_debug.o) has no symbols
     make: *** [julia-deps] Error 2

Any ideas? I am using Intel Compilers 16 on 10.10

**Comment by jiahao** [comment]
Now that 0.5.0 is released, I tried again recently with `clang-800.0.38` and `ifort` 17.0. I can reproduce a failing build. The offending error is actually with ARPACK:

```sh
Updating goal targets....
Considering target file `all-am'.
 File `all-am' does not exist.
  Pruning file `Makefile'.
  Considering target file `libarpack.la'.
   File `libarpack.la' does not exist.
    Considering target file `SRC/libarpacksrc.la'.
     Looking for an implicit rule for `SRC/libarpacksrc.la'.
     Trying pattern rule with stem `libarpacksrc.la'.
     Trying implicit prerequisite `SRC/libarpacksrc.la.f'.
     Trying pattern rule with stem `libarpacksrc.la'.
     Trying implicit prerequisite `SRC/libarpacksrc.la.o'.
     Trying pattern rule with stem `libarpacksrc.la'.
     Trying implicit prerequisite `SRC/libarpacksrc.la,v'.
     Trying pattern rule with stem `libarpacksrc.la'.
     Trying implicit prerequisite `SRC/RCS/libarpacksrc.la,v'.
     Trying pattern rule with stem `libarpacksrc.la'.
     Trying implicit prerequisite `SRC/RCS/libarpacksrc.la'.
     Trying pattern rule with stem `libarpacksrc.la'.
     Trying implicit prerequisite `SRC/s.libarpacksrc.la'.
     Trying pattern rule with stem `libarpacksrc.la'.
     Trying implicit prerequisite `SRC/SCCS/s.libarpacksrc.la'.
     Trying pattern rule with stem `libarpacksrc.la'.
     Trying implicit prerequisite `SRC/libarpacksrc.la.f'.
     Looking for a rule with intermediate file `SRC/libarpacksrc.la.f'.
      <snip>
   Finished prerequisites of target file `libarpack.la'.
  Must remake target `libarpack.la'.
Putting child 0x7fdac0f03570 (libarpack.la) PID 29302 on the chain.
Live child 0x7fdac0f03570 (libarpack.la) PID 29302
libtool: link: rm -fr  .libs/libarpack.lax
libtool: link: (cd .libs/libarpack.lax/libarpacksrc.a && ar x "/Users/jiahao/local/src/julia-0.5/deps/build/arpack-ng-3.3.0/./SRC/.libs/libarpacksrc.a")
libtool: link: (cd .libs/libarpack.lax/libarpackutil.a && ar x "/Users/jiahao/local/src/julia-0.5/deps/build/arpack-ng-3.3.0/./UTIL/.libs/libarpackutil.a")
libtool: link: ifort -mmacosx-version-min=10.7 -m64 -dynamiclib  -o .libs/libarpack.2.dylib   .libs/libarpack.lax/libarpacksrc.a/cgetv0.o .libs/libarpack.lax/libarpacksrc.a/cnaitr.o .libs/libarpack.lax/libarpacksrc.a/cnapps.o .libs/libarpack.lax/libarpacksrc.a/cnaup2.o .libs/libarpack.lax/libarpacksrc.a/cnaupd.o .libs/libarpack.lax/libarpacksrc.a/cneigh.o .libs/libarpack.lax/libarpacksrc.a/cneupd.o .libs/libarpack.lax/libarpacksrc.a/cngets.o .libs/libarpack.lax/libarpacksrc.a/csortc.o .libs/libarpack.lax/libarpacksrc.a/cstatn.o .libs/libarpack.lax/libarpacksrc.a/dgetv0.o .libs/libarpack.lax/libarpacksrc.a/dnaitr.o .libs/libarpack.lax/libarpacksrc.a/dnapps.o .libs/libarpack.lax/libarpacksrc.a/dnaup2.o .libs/libarpack.lax/libarpacksrc.a/dnaupd.o .libs/libarpack.lax/libarpacksrc.a/dnconv.o .libs/libarpack.lax/libarpacksrc.a/dneigh.o .libs/libarpack.lax/libarpacksrc.a/dneupd.o .libs/libarpack.lax/libarpacksrc.a/dngets.o .libs/libarpack.lax/libarpacksrc.a/dsaitr.o .libs/libarpack.lax/libarpacksrc.a/dsapps.o .libs/libarpack.lax/libarpacksrc.a/dsaup2.o .libs/libarpack.lax/libarpacksrc.a/dsaupd.o .libs/libarpack.lax/libarpacksrc.a/dsconv.o .libs/libarpack.lax/libarpacksrc.a/dseigt.o .libs/libarpack.lax/libarpacksrc.a/dsesrt.o .libs/libarpack.lax/libarpacksrc.a/dseupd.o .libs/libarpack.lax/libarpacksrc.a/dsgets.o .libs/libarpack.lax/libarpacksrc.a/dsortc.o .libs/libarpack.lax/libarpacksrc.a/dsortr.o .libs/libarpack.lax/libarpacksrc.a/dstatn.o .libs/libarpack.lax/libarpacksrc.a/dstats.o .libs/libarpack.lax/libarpacksrc.a/dstqrb.o .libs/libarpack.lax/libarpacksrc.a/sgetv0.o .libs/libarpack.lax/libarpacksrc.a/snaitr.o .libs/libarpack.lax/libarpacksrc.a/snapps.o .libs/libarpack.lax/libarpacksrc.a/snaup2.o .libs/libarpack.lax/libarpacksrc.a/snaupd.o .libs/libarpack.lax/libarpacksrc.a/snconv.o .libs/libarpack.lax/libarpacksrc.a/sneigh.o .libs/libarpack.lax/libarpacksrc.a/sneupd.o .libs/libarpack.lax/libarpacksrc.a/sngets.o .libs/libarpack.lax/libarpacksrc.a/ssaitr.o .libs/libarpack.lax/libarpacksrc.a/ssapps.o .libs/libarpack.lax/libarpacksrc.a/ssaup2.o .libs/libarpack.lax/libarpacksrc.a/ssaupd.o .libs/libarpack.lax/libarpacksrc.a/ssconv.o .libs/libarpack.lax/libarpacksrc.a/sseigt.o .libs/libarpack.lax/libarpacksrc.a/ssesrt.o .libs/libarpack.lax/libarpacksrc.a/sseupd.o .libs/libarpack.lax/libarpacksrc.a/ssgets.o .libs/libarpack.lax/libarpacksrc.a/ssortc.o .libs/libarpack.lax/libarpacksrc.a/ssortr.o .libs/libarpack.lax/libarpacksrc.a/sstatn.o .libs/libarpack.lax/libarpacksrc.a/sstats.o .libs/libarpack.lax/libarpacksrc.a/sstqrb.o .libs/libarpack.lax/libarpacksrc.a/zgetv0.o .libs/libarpack.lax/libarpacksrc.a/znaitr.o .libs/libarpack.lax/libarpacksrc.a/znapps.o .libs/libarpack.lax/libarpacksrc.a/znaup2.o .libs/libarpack.lax/libarpacksrc.a/znaupd.o .libs/libarpack.lax/libarpacksrc.a/zneigh.o .libs/libarpack.lax/libarpacksrc.a/zneupd.o .libs/libarpack.lax/libarpacksrc.a/zngets.o .libs/libarpack.lax/libarpacksrc.a/zsortc.o .libs/libarpack.lax/libarpacksrc.a/zstatn.o  .libs/libarpack.lax/libarpackutil.a/cmout.o .libs/libarpack.lax/libarpackutil.a/cvout.o .libs/libarpack.lax/libarpackutil.a/dmout.o .libs/libarpack.lax/libarpackutil.a/dvout.o .libs/libarpack.lax/libarpackutil.a/icnteq.o .libs/libarpack.lax/libarpackutil.a/icopy.o .libs/libarpack.lax/libarpackutil.a/iset.o .libs/libarpack.lax/libarpackutil.a/iswap.o .libs/libarpack.lax/libarpackutil.a/ivout.o .libs/libarpack.lax/libarpackutil.a/second_NONE.o .libs/libarpack.lax/libarpackutil.a/smout.o .libs/libarpack.lax/libarpackutil.a/svout.o .libs/libarpack.lax/libarpackutil.a/zmout.o .libs/libarpack.lax/libarpackutil.a/zvout.o   -L/opt/intel//compilers_and_libraries_2017.0.102/mac/mkl/lib/intel64 -lmkl_rt  -mmacosx-version-min=10.7 -m64 -O2 -rpath @loader_path/   -install_name  /Users/jiahao/local/src/julia-0.5/usr/lib/libarpack.2.dylib -compatibility_version 3 -current_version 3.0 -single_module
ifort: error #10005: unable to open argument file 'loader_path/'
```

It looks like `ifort` doesn't understand the `-rpath @loader_path/` flag?

**Comment by jiahao** [comment]
Others have reported the same `rpath` issue with `ifort`, see Sandia-OpenSHMEM/SOS#111

Removing `-rpath @loader_path/` from `LDFLAGS` in `deps/build/arpack-ng-3.3.0` appears to have  gotten past this one obstacle.

**Comment by ViralBShah** [comment]
We no longer support Intel compilers.
