### ISSUE TITLE
Memory Error when creating large number of workers (using DArrray)

### ISSUE THREAD

**Issue by kapiliitr** [JuliaLang/julia#9149]
Referring to the discussion here (https://groups.google.com/forum/#!topic/julia-users/0XTidbuInbQ), launching with small number of workers and small matrix size works fine, but as workers and size of matrix is increased, the code breaks.
test code :  https://github.com/kapiliitr/JuliaBenchmarks/blob/master/ptrans.jl
error : https://github.com/kapiliitr/JuliaBenchmarks/blob/master/error.txt

This code has been run using Julia v0.3.1, 0.3.3, v0.4.0-dev+1061.

**Comment by jakebolewski** [comment]
The test code is no longer accessible, closing in favor of the duplicate issues listed.
