### ISSUE TITLE
Segfault while using @profile

### ISSUE THREAD

**Issue by swt30** [JuliaLang/julia#9166]
I've been having trouble with segfaults while running `@profile` on a loop which I am trying to speed up.  The loop itself is just fine if `@profile` isn't used, or if I use `@time` instead. Here's a backtrace and version info: https://gist.github.com/swt30/3e1aaeeb295894e75af5

#### More info ####

The purpose of the loop is pretty standard: solve a series of differential equations dy/dt = f(t, y; pars), repeat a number of times to converge on the correct parameter values, and then the whole thing is repeated three times for three different scenarios. The physical system has a singularity at the end so the integration is nothing complicated---just a Runge-Kutta method with a fixed step size.

The code is for work, so unfortunately I can't provide more details at the moment. I'm also too new to gdb to understand what's going on, but my suspicion is that the problem is related to the fact that I'm using tasks for each integration. Each task looks something like this:

```julia
function stepper(...)
    produce((initial_t_value, initial_y_vector))
    for t in range_of_t_values
        do_the_integration_and_update_y_in_place!(...)
        if the_integrator_should_halt_based_on(t,y)
            # yield the last value and then finish
            produce((t, y))
            break
        else
            produce((t, y))
        end
    end
end
```
and then in another function I do:
```julia
steppertask = @task stepper(...)
for intermediate_values in stepper_task
    update_the_solution_with!(intermediate_values)
end
```
to fill in the solution with values that come out of the task.

Given that this is then repeated hundreds of times, could the large number of tasks being created be messing with the profiler here? Any help would be much appreciated so I can figure out whether this is just me doing something stupid or expecting too much.

**Comment by swt30** [comment]
Unfortunately I never managed to pin down the problem with this and come up with a test case. I've since switched to using the iterator protocol (start/next/done) instead of creating a task, which fixed not being able to profile it.

**Comment by timholy** [comment]
Thanks for the update, and for trying to find a test case. These rare problems are very tricky.

**Comment by swt30** [comment]
Closing since a lot has changed since then and I never managed to pin it down anyway.
