### ISSUE TITLE
Deprecate Octal and Hexadecimal notation in ip""?

### ISSUE THREAD

**Issue by dns2utf8** [JuliaLang/julia#9187]
Hi all

I noticed, that julia does some funny stuff in the REPL when you enter the folowing:
<code>julia> ip"001.021.201.012"</code>
the Answer:
<code>ip"1.17.201.10"</code>

Regards

**Comment by dns2utf8** [comment]
I tested this address:
```julia
julia> ip"042.042.0042.0042"
ip"34.34.34.34"
```

```bash
$ ping 042.042.0042.0042
PING 042.042.0042.0042 (34.34.34.34) 56(84) bytes of data.
```

My personal opinion is: this is broken. 
I would tolerate octale numbers in the following format: 0XXX

Shorter Versions could cause trouble, when counting up like this:
099 -> 100

Apart from that I noticed this:
```julia
julia> ip"01.01.010.007"
ip"1.1.8.7"

julia> ip"01.01.010.008"
ERROR: invalid base 8 digit '8' in "008"
```

What am I missing in the last example?

**Comment by sbromberger** [comment]
> What am I missing in the last example?
Octal digits are 0-7 inclusive.

**Comment by dns2utf8** [comment]
ah, it is getting late. 
Thanks sbromberger.

**Comment by sbromberger** [comment]
I'd blame Julia's 1-indexing for that mistake:)

**Comment by dns2utf8** [comment]
🎉 this was one of my first issues 🎉

**Comment by PallHaraldsson** [comment]
@keno "As a datapoint, quoting from https://tools.ietf.org/html/draft-main-ipaddr-text-rep-02"

I think we should follow section 3 (and 4.1 Be Stringent in What You Accept) fully.

I see from tests e.g. this was allowed:

julia> parse(IPv4, "192.0xFFFF")
ERROR: UndefVarError: ipv4_leading_zero_error not defined
 in parse(::Type{IPv4}, ::String) at ./REPL[335]:10

no longer, but also not useful, but still e.g. allowed:

julia> parse(IPv4, "192.65535")
ip"192.0.255.255"

julia> IPv4("192.11")
ip"192.0.0.11"

**Comment by KristofferC** [comment]
Please quote your code.

**Comment by StefanKarpinski** [comment]
@PallHaraldsson: is this a bug report on the deprecation of this being broken?
