### ISSUE TITLE
reuse boxed versions of values in codegen

### ISSUE THREAD

**Issue by cpitclaudel** [JuliaLang/julia#9194]
Hi all,

The following code seems to allocate a lot of memory:

```julia
function test!(arr::Array{(Int, Int)})
    for i = 1:10_000_000
        arr[1] = arr[2]
    end
end

a = [(1, 1), (2, 2)]
test!(a)
```

Here are the results of `@time test!(a)` (using HEAD on the master branch, commit ce29d785098564b61af0c65113595b1af7ba0acb) :

```
elapsed time: 0.439144953 seconds (320013808 bytes allocated, 40.35% gc time)
```

On the other hand, using a composite type works as expected:

```
immutable Pair{T1, T2}
  a::T1
  b::T2
end

function test!(arr::Array{Pair{Int, Int}})
    for i = 1:10_000_000
        arr[1] = arr[2]
    end
end

a = [Pair(1, 1), Pair(2, 2)]
test!(a)
```

Here `@time test!(a)` yields

```
elapsed time: 0.022649237 seconds (80 bytes allocated)
```

Am I missing something obvious? It seems that each assignment triggers an allocation in the case of tuples (adding `@time` before the assignment suggests a 32 bytes allocation). Why is that? Is this documented somewhere?

(I ran into this problem when trying to use a heap to extract the top `n` elements from a list of tuples without sorting it first, as done in Python's `heapq.nlargest` method)

**Comment by colinfang** [comment]
In the version 0.4.2

Tuple & Pair have the same performance.

Seems some optimizations have been applied.

```{julia}
function test!(arr::Array{Tuple{Int, Int}})
    for i = 1:10_000_000
        arr[1] = arr[2]
    end
end

a = [(1, 1), (2, 2)]
test!(a)
@time test!(a)
0.010339 seconds (1.71 k allocations: 87.476 KB)

immutable Pair{T1, T2}
  a::T1
  b::T2
end

function test!(arr::Array{Pair{Int, Int}})
    for i = 1:10_000_000
        arr[1] = arr[2]
    end
end

a = [Pair(1, 1), Pair(2, 2)]
test!(a)
@time test!(a)
0.012467 seconds (1.71 k allocations: 87.413 KB)
```

**Comment by vtjnash** [comment]
the tuple representation in v0.4 changed to be the same as Pair, so it takes a bit more creativity to show this problem has been fixed on master:


```julia
julia> a = Any[(1, 1), (2, 2)]
2-element Array{Any,1}:
 (1,1)
 (2,2)

julia> function test!(arr::Array{Any})
                  for i = 1:10_000_000
                      arr[1] = arr[2]::Tuple{Int,Int}
                  end
              end
test! (generic function with 1 method)
```

```julia
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)

julia> @time test!(a)
  0.439145 seconds (10.00 M allocations: 305.283 MB, 9.34% gc time)

julia> @time test!(a)
  0.416601 seconds (10.00 M allocations: 305.176 MB, 4.10% gc time)
```

```julia
  | | |_| | | | (_| |  |  Version 0.5.0-dev+3085 (2016-03-10 09:42 UTC)

julia> @time test!(a)
  0.329829 seconds (1.79 k allocations: 116.323 KB)

julia> @time test!(a)
  0.317760 seconds (4 allocations: 160 bytes)
```

**Comment by cpitclaudel** [comment]
Beautiful! Congratulations. I'd love a pointer to see the particular commit(s) that fixed this; I'd be curious to see the implementation :)

**Comment by vtjnash** [comment]
the most recent changes were https://github.com/JuliaLang/julia/pull/15064 (and https://github.com/JuliaLang/julia/pull/14543 that it built upon)

**Comment by cpitclaudel** [comment]
Thanks!
