### ISSUE TITLE
"type too large"

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#9232]
In some code that uses `pmap`, on any given run some (but not all) of my (local) workers throw [this](https://gist.github.com/simonster/a5ec8d13e80e94c9f3d8). I'll try to make a reduced test case, but it may be difficult.

**Comment by IainNZ** [comment]
I've seen this in PkgEvaluator logs too

**Comment by IainNZ** [comment]
e.g. https://github.com/gragusa/CovarianceMatrices.jl/issues/2 and https://github.com/gragusa/CovarianceMatrices.jl/issues/1 - its intermittant
