### ISSUE TITLE
julia-mode.el: Improve highlighting of quoted symbols

### ISSUE THREAD

**Issue by Wilfred** [JuliaLang/julia#9247]
From @JeffBezanson in #9024

> I think it would make sense for quoted symbols to use constant-face by default; they are constants after all.
> 
> Also quoted-symbol-face seems not to work right at the beginning of a line. This is definitely a pretty rare case though.

**Comment by yuyichao** [comment]
Moved to https://github.com/JuliaLang/julia-emacs/issues/4
