### ISSUE TITLE
Get the permutation vector from sortrows and sortcols

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#9258]
Getting the permutation vector from sortrows and sortcols is often required, but we don't have a way to do it. For now, one can concatenate `[1:n]` to the end of the array and calling sortrows, which will become the permutation vector when sortrows completes.

Discussion here:
https://groups.google.com/forum/?hl=en#!topic/julia-users/zgWwkgcHpFY

cc: @kmsquire

**Comment by tkelman** [comment]
Did not make it into 0.4, removing from milestone.

**Comment by LilithHafner** [comment]
Now that `eachslice` is infers well, `sortperm(eachslice(x; dims))` solves this issue.
