### ISSUE TITLE
Int64*Uint64

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#9292]
This doesn't seem like the intended behavior. Are we accidentally trying to do the multiplication in Uint64?

``````
julia> -1*uint64(1)
ERROR: InexactError()
 in * at promotion.jl:159
```?
``````

**Comment by stevengj** [comment]
@eschnett, I think it makes sense for bitwise operations (`&`, `<<`, `|`, `$`) to promote to unsigned.  To unset a bit I would normally recommend `mask & ~0x1` rather than `mask - 0x1`, as the former does the correct thing even if the bit is already unset.

**Comment by eschnett** [comment]
@stevengj I was thinking more of ``bitpos = uint(4); value &= (1<<bitpos)-1``, i.e. the ``-1` would create a mask, not modify a value.

**Comment by eschnett** [comment]
If `a-b` returns `Int` for `UInt` arguments, then (for symmetry) so should `a+b`. It would be quite surprising if `a-b` (for integers!) leads to a different result than `a+(-b)`, in particular when people re-write expressions or introduce temporaries. Taking this argument to conclusion, `a*b` should also return `Int`.

No matter what convention, there's the danger of an overflow. What about simply disallowing all mixed, "dangerous" operations? Adding `Int` and `UInt` is probably rare, and people may as well have to explicitly specify what they expect to happen. If we add a special rule for literal constants (they can be used either with `Int` or `UInt`), then this should take all ambiguity and most of the inconvenience out of the game.

**Comment by StefanKarpinski** [comment]
> No matter what convention, there's the danger of an overflow. What about simply disallowing all mixed, "dangerous" operations? Adding Int and UInt is probably rare, and people may as well have to explicitly specify what they expect to happen.

That's why I was suggesting that the results of all of these be `Int` but that they check for overflows. Although there is an argument to be made for disabling them altogether.

**Comment by eschnett** [comment]
My proposal also included treating integer literals in a special way, probably similar to the way math constants are currently handled: `UInt + Literal = UInt` and `Int + Literal = Int`. Such a rule should cover most cases of `Int + UInt`, and the conversions from a literal to either `Int` or `UInt` can be checked at compile-time.

**Comment by ararslan** [comment]
I'm with @stevengj here. I think if anywhere in your calculation you have an idea of sign, that should be preserved.

**Comment by StefanKarpinski** [comment]
Bump.

**Comment by Keno** [comment]
I still find this behavior distinctly annoying and find myself adding casts all over the place just to deal with this.

**Comment by eschnett** [comment]
Should we introduce unsigned literals then? Writing `x + UInt(1)` seems likewise ugly.

**Comment by StefanKarpinski** [comment]
So the proposal would be for signed and unsigned to produce signed values? I'm in favor of that.

**Comment by eschnett** [comment]
If we go this way (against my wishes, but I can live with that), we'll need a transition strategy. This has the potential to create type instabilities and bugs that are difficult to detect. For example, an intermediate step where `UInt * Int` is a type error might be such a step, forcing people to add explicit `UInt` conversions where necessary.

**Comment by StefanKarpinski** [comment]
That's actually not such a terrible permanent state of affairs since there are corner cases that might fail no matter which promotion we choose and we don't check for them at runtime.

**Comment by tkelman** [comment]
Changes here not in scope for 0.6

**Comment by StefanKarpinski** [comment]
x-ref: https://github.com/JuliaLang/julia/issues/15489

**Comment by udion** [comment]
**julia Version 0.5.2**
I need to convert numbers from 2^63 to 2^64-1 to binary string of length 64, however using <code>bin()</code> gives the following -ve answer
```
julia> bin(2^63,64)
"-1000000000000000000000000000000000000000000000000000000000000000"

julia> bin(2^64-1,64)
"-0000000000000000000000000000000000000000000000000000000000000001"
```
on using UInt64 or UInt128, it's throwing the following error
```
julia> UInt64(2^63)
ERROR: InexactError()
 in UInt64(::Int64) at ./sysimg.jl:53

julia> UInt64(2^64-1)
ERROR: InexactError()
 in UInt64(::Int64) at ./sysimg.jl:53
```
I can think of some hacks to get my job done but isn't above method suppose to work? In the official document UInt64 has upperlimit of 2^64 - 1, but it seems that UInt64 crashes after 2^63-1.

**Comment by nalimilan** [comment]
@udion Your problem comes from `Int` overflow:
```julia
julia> 2^63
-9223372036854775808
```

You need to do `UInt64(2)^63`. But please use Discourse for questions like this.

**Comment by stevengj** [comment]
(deleted offtopic question from @udion)

I looked into implementing this, and I agree with @JeffBezanson's [comment from #15489](https://github.com/JuliaLang/julia/issues/15489#issuecomment-196682339).   Implementing this as a change to the promotion rules turns out to be a big mess, because it screws up bitwise manipulations (e.g. in float.jl) where you want e.g. `unsigned << signed` to be unsigned.  It looks like it is best implemented as methods for `*`, `+` etc.

**Comment by rfourquet** [comment]
> if anywhere in your calculation you have an idea of sign, that should be preserved.

It's not totally true, as the simplest way to write a litteral is as an `Int`. And the same argument could be inversed: "if anywhere you have an idea of unsignedness, that should be preserved", my main use case being using unsigned numbers as bit fields, and incrementing an unsigned (`x+1`), or constructing more complex masks with multiplications, etc. 

I see two main use cases:
1) an unsigned appears in a computation, coming e.g. from a library (as a length for example), when an `Int` would be more appropriate: in this case it seems preferable to have `UInt*Int` -> `Int` (etc.).
2) an unsigned is used on purpose in a computation: I would say mixed computations with signed integers should result in unsigned integers. If you have a class `ModInt` (cf. the examples directory), it wouldn't make sense to have `Int*ModInt -> Int`; and `UInt` precisely represents modular integers. 

I would favor use case 2 (for use case 1, a conversion to `Int` can be explicitly written after a `ccall` to adapt to Julia style, like in "gmp.jl" for example, after all writing the `ccall` forces the user to know that an unsigned integer is being returned).

**Comment by StefanKarpinski** [comment]
> Implementing this as a change to the promotion rules turns out to be a big mess, because it screws up bitwise manipulations (e.g. in float.jl) where you want e.g. `unsigned << signed` to be unsigned.  It looks like it is best implemented as methods for `*`, `+` etc.

The result of a bitshift should have the same type as the left argument – where does promotion come into it? E.g.:

```
julia> 0x1 << 1
0x02
```

If there's somewhere we're not doing this, it should be fixed.

**Comment by stevengj** [comment]
@StefanKarpinski, it turned out that the problem I was initially running into was not due to bitshift.  But I still think we probably want `UInt` results for bitwise operators like `|`?

**Comment by StefanKarpinski** [comment]
This is the core "interesting" part of the promotion table:
```jl
Ts = sort!(Base.uniontypes(Base.BitInteger), by=T->(!(T<:Signed),sizeof(T)));

julia> for (i, T) in enumerate(Ts), (j, S) in enumerate(Ts)
           i < j || continue
           (T <: Signed) ⊻ (S <: Signed) || continue
           P = promote_type(T, S)
           @printf "%-7s + %-7s => %-7s\n" T S P
       end
Int8    + UInt8   => Int64
Int8    + UInt16  => Int64
Int8    + UInt32  => Int64
Int8    + UInt64  => UInt64
Int8    + UInt128 => UInt128
Int16   + UInt8   => Int64
Int16   + UInt16  => Int64
Int16   + UInt32  => Int64
Int16   + UInt64  => UInt64
Int16   + UInt128 => UInt128
Int32   + UInt8   => Int64
Int32   + UInt16  => Int64
Int32   + UInt32  => Int64
Int32   + UInt64  => UInt64
Int32   + UInt128 => UInt128
Int64   + UInt8   => Int64
Int64   + UInt16  => Int64
Int64   + UInt32  => Int64
Int64   + UInt64  => UInt64
Int64   + UInt128 => UInt128
Int128  + UInt8   => Int128
Int128  + UInt16  => Int128
Int128  + UInt32  => Int128
Int128  + UInt64  => Int128
Int128  + UInt128 => UInt128
```

@JeffBezanson, could you run this on your little 32-bit machine for the 32-bit version of the table?

**Comment by omus** [comment]
@StefanKarpinski here's is what I get on 32-bit:
```julia
Int8    + UInt8   => Int32
Int8    + UInt16  => Int32
Int8    + UInt32  => UInt32
Int8    + UInt64  => UInt64
Int8    + UInt128 => UInt128
Int16   + UInt8   => Int32
Int16   + UInt16  => Int32
Int16   + UInt32  => UInt32
Int16   + UInt64  => UInt64
Int16   + UInt128 => UInt128
Int32   + UInt8   => Int32
Int32   + UInt16  => Int32
Int32   + UInt32  => UInt32
Int32   + UInt64  => UInt64
Int32   + UInt128 => UInt128
Int64   + UInt8   => Int64
Int64   + UInt16  => Int64
Int64   + UInt32  => Int64
Int64   + UInt64  => UInt64
Int64   + UInt128 => UInt128
Int128  + UInt8   => Int128
Int128  + UInt16  => Int128
Int128  + UInt32  => Int128
Int128  + UInt64  => Int128
Int128  + UInt128 => UInt128
```

**Comment by StefanKarpinski** [comment]
Here's the complete picture then:

| type A    | type B    | 32-bit    | 64-bit    |
|-----------|-----------|-----------|-----------|
| `Int8`    | `UInt8`   | `Int32`   | `Int64`   |
| `Int8`    | `UInt16`  | `Int32`   | `Int64`   |
| `Int8`    | `UInt32`  | `UInt32`  | `Int64`   |
| `Int8`    | `UInt64`  | `UInt64`  | `UInt64`  |
| `Int8`    | `UInt128` | `UInt128` | `UInt128` |
| `Int16`   | `UInt8`   | `Int32`   | `Int64`   |
| `Int16`   | `UInt16`  | `Int32`   | `Int64`   |
| `Int16`   | `UInt32`  | `UInt32`  | `Int64`   |
| `Int16`   | `UInt64`  | `UInt64`  | `UInt64`  |
| `Int16`   | `UInt128` | `UInt128` | `UInt128` |
| `Int32`   | `UInt8`   | `Int32`   | `Int64`   |
| `Int32`   | `UInt16`  | `Int32`   | `Int64`   |
| `Int32`   | `UInt32`  | `UInt32`  | `Int64`   |
| `Int32`   | `UInt64`  | `UInt64`  | `UInt64`  |
| `Int32`   | `UInt128` | `UInt128` | `UInt128` |
| `Int64`   | `UInt8`   | `Int64`   | `Int64`   |
| `Int64`   | `UInt16`  | `Int64`   | `Int64`   |
| `Int64`   | `UInt32`  | `Int64`   | `Int64`   |
| `Int64`   | `UInt64`  | `UInt64`  | `UInt64`  |
| `Int64`   | `UInt128` | `UInt128` | `UInt128` |
| `Int128`  | `UInt8`   | `Int128`  | `Int128`  |
| `Int128`  | `UInt16`  | `Int128`  | `Int128`  |
| `Int128`  | `UInt32`  | `Int128`  | `Int128`  |
| `Int128`  | `UInt64`  | `Int128`  | `Int128`  |
| `Int128`  | `UInt128` | `UInt128` | `UInt128` |

**Comment by StefanKarpinski** [comment]
One observation is that this is a place where the dependence on `Int` makes the behavior very hard to reason about across 32-bit and 64-bit systems. I would be appealing to make these rules independent of platform word size so that there's just a single table for this kind of thing. Certainly the cases where whether the result is signed or unsigned depends the word size seem pathological and we should at the very least avoid those.

**Comment by JeffBezanson** [comment]
Agreed that the cases where signedness depends on system word size are most ripe for revision.

**Comment by StefanKarpinski** [comment]
The only reasonable platform-independent rules that I can come up with are:
1. Require explicit casting for mixed signedness operations.
2. Promote to a signed type that is big enough to hold both inputs.
3. Promote to a signed type that is as big as the larger of the two inputs.
4. Promote to an unsigned type that is as big as the larger of the two inputs.

**Comment by StefanKarpinski** [comment]
One observation is that a common pattern to deal with mixed-signedness code is to put local type annotations on the variables and then let implicit conversion ensure that the types are right, so we should consider that pattern when choosing a behavior and ideally pick a design that allows the storage "locations" to be typed and from there let the compiler work things out and generate efficient, correct code.

**Comment by StefanKarpinski** [comment]
From triage, we've decided to give a try to option 4.

**Comment by StefanKarpinski** [comment]
Another option:

5. Pick the type of the bigger argument, preferring the unsigned one if they're the same size.

**Comment by JeffBezanson** [comment]
The remainder of this is part of #15489.

**Comment by StefanKarpinski** [comment]
See also #15489 and PR #23827 fixing it.
