### ISSUE TITLE
push! on Dicts

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#9295]
Now that we have the nice syntax for pairs, I think it would be convenient for
```
a = Dict()
push!(a,1=>2)
```
to work. At the moment we have to use
```
push!(a,1,2)
```
which probably should be reflected in the docs for push!, which are right now:
```
  push!(collection, items...) → collection

  Insert items at the end of collection.

  push!([1,2,3], 4) == [1,2,3,4]
```

**Comment by bicycle1885** [comment]
@ivarne 
I cherry-picked your half fix and added varargs support and some tests.
But it breaks very rare (I hope) backward compatibility: `push!`ing a pair of `Pair` key and `Pair` value.

One workaround would be using explicit type parameters:
```julia
push!{K,V}(::Associative{K,V}, ::Pair{K,V}, ::Pair{K,V})
```
but this will change the semantic of `push!`.
