### ISSUE TITLE
Restrict indexing into strings to a special `ByteIndex` or `StringIndex` type

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#9297]
This is a proposal that's been done in Rust and apparently is still under discussion (see https://github.com/rust-lang/rust/issues/10044#issuecomment-26982523), but I thought it could be interesting for Julia.

The idea is that since indexing strings with a number like `s[3]` only makes sense when `3` actually corresponds to the boundary of a unicode code point, it represents a trap for developers who only test it on ASCII, making bugs appear only in production when used with non-ASCII text. Typical cases are the naive:

``` julia
julia> s = "noël";
julia> s[4] # Thinking that this provides the fourth "character"
ERROR: invalid UTF-8 character index
 in next at ./utf8.jl:68
 in getindex at string.jl:57
```

the tempting:

``` julia
julia> s[end - 1] # Thinking you skip the last character, works well... until it breaks
ERROR: invalid UTF-8 character index
 in next at ./utf8.jl:68
 in getindex at string.jl:57
```

(Julia equivalent of http://www.reddit.com/r/rust/comments/1zlq21/should_rust_be_more_careful_with_unicode/cfush88)

or the slightly more involved:

``` julia
julia> s[match(r"l", s).offset - 1]
ERROR: invalid UTF-8 character index
 in next at ./utf8.jl:68
 in getindex at string.jl:57
```

Instead of letting people do incorrect-but-easy things like this, it could be useful to restrict string indexing to a special type, say `ByteIndex`, instead of a plain integer. `match` would provide `offset` as that type too. It would prevent both naive indexing using integers as well as doing incorrect arithmetic on indexes you get from functions, encouraging people to always use dedicated functions.

It _might_ also make sense to allow arithmetic operations on this type, so that `idx + 1` means "the code point after the one at position `idx`", which would be O(n) but starting from the index -- and usually you don't take very large offsets. I'm not saying this is necessarily a good idea, though, because `ByteIndex` implies a reasoning in bytes, and then arithmetic operations would switch to a reasoning in code points. It could be named `StringIndex` instead, and made opaque so that people never see the integer index which is in bytes.

Finally, it might be possible to perform some optimizations by removing checks that the index corresponds to the start of a code point, if the index held a reference to the string it was build from, so that it can be checked that it matches the indexed string. Not sure it would be significant, though.

**Comment by nalimilan** [comment]
@StefanKarpinski Indeed in my experiments the pointer version is much faster than the other `StringIndex` solution, and even faster than the current implementation for `s[nextind(s, i)]`. The generated code looks cleaner, though no inlining seems to happen. See this gist:
https://gist.github.com/nalimilan/5652da74380c7e211131

So the pointer approach looks like the good one. I've also added to the index a pointer to the start of the string like this:
```julia
immutable StringIndexPointer{S<:AbstractString}
    ptr::Ptr{Uint8}
    start::Ptr{Uint8}
end
```

This is required so that `x[i-1]` never goes beyond the lower bound of the string. It's not strictly required for the upper bound as long as we assume that all string types are nul-terminated, but if we want to support other types of strings in the future, it may make sense to also carry the upper limit of the string. What do you think?

**Comment by StefanKarpinski** [comment]
I've been pondering this – it's quite at odds with the stuff I've been working on for faster strings. Although the ability to do a lot of string work without any heap allocation is really great with that approach, but the performance situation has been a bit of a wash because of the extra branches introduced by having the string data either be inline or on the heap. @johnmyleswhite (I think) raised concerns about interacting with APIs that expect to be able to get pointers to string data, which I'm not sure about. @JeffBezanson, @vtjnash, do you have thoughts on how to handle that? To add another consideration, I've been wondering if the pointer-as-iterator-state approach could allow a reasonable non-contiguous string representation somehow. Just when I thought I had things figured out. Being able to write Unicode-correct string code that does `s[i + 1]` is very appealing and having the bounds checking based on a pointer implies that the index `i` must come from the string `s`, not just from a string of the correct type. It seems more usable, more efficient, and safer. That's a compelling combination. Then again, it's not as obvious how to generalize this approach to "exotic" string types like `RepString` or `RevString`. Of course, I don't think it would such a shame if we just got rid of those altogether.

**Comment by nalimilan** [comment]
@StefanKarpinski Wouldn't the solution be to create different `StringIndex` types for different families of `AbstractString`?  `RepString` is a quite different beast from "standard" strings-as-array-of-characters anyway.

(But I don't have a clear view of what your work to make strings faster looks like.)

**Comment by stevengj** [comment]
I'm mostly worried about serialization with the pointer approach.  Serialization comes up not only in parallel RPC (e.g. for parallel processing of a given string), but also in precompilation: if I have a `const foo = ...some StringIndex...` in my module, how would you precompile the module?  (This case maybe wouldn't come up very often, so I suppose we could just refuse to precompile?)

**Comment by nalimilan** [comment]
Another approach not involving pointers is to store a position in bytes and an offset from it in characters:
```julia
immutable StringIndexOffset{S<:AbstractString}
    i::Int
    offset::Int
end
```

This approach has the advantage of being quite logical, since the index object stores exactly all the information we have about the position in the string, without additional references or computations. The actual byte position is only computed when calling `getindex` or `next`, i.e. by functions which have access to the string. `i + 1` merely increments `i.offset` by one. This is also much simpler than playing with pointers.

I've added this solution to the Gist, and it performs quite well for `x[i + 1]`: only 12% slower than pointers, and 16% slower than `nextind` with the current implementation. (OTOH `x[i]` is 25% slower than the current implementation even when `i.offset == 0`, but even `StringIndexPointer` is 10% slower than the current implementation: this can probably be improved.)
https://gist.github.com/nalimilan/5652da74380c7e211131

The drawback with this approach is that the index object in itself does not carry much information:
* The length of a range between two indexes cannot be computed as `length(i1:i2)`, except in the case where `i1.i == i2.i`. But of course one can easily use `length(s[i1:i2])`, or a special function to do that. The question is, would that be a problem given that it implies that string ranges wouldn't implement the full interface ranges usually support?
* Two indexes cannot be compared using `<`, except when either 1) `i1.i == i2.i`, or 2) `i1.i < i2.i && i1.offset < i2.offset`. Again, in practice, this may not be a big issue.

How do you feel about this solution?

**Comment by nalimilan** [comment]
Bump!

**Comment by stevengj** [comment]
String indexing is such a basic inner-loop operation that I'm uncomfortable slowing it down measurably.  

I'd prefer just making StringIndex{T} a thin wrapper around an Int index into string.data, and requiring users to explicitly call nextind/prevind. i.e. disallow +/- on indices.

**Comment by stevengj** [comment]
That solution won't preclude doing something fancier later if there is a hue and cry for +/-. But forcing people to think about the ambiguous nature of "next character" by calling nextind (or nextgrapheme) explicitly isn't such a bad thing.

**Comment by elextr** [comment]
@stevengj what is a `StringIndex{T}`, is it a byte index, a code point index, a character index, a graphene index?

It should be explicitly one of the above, there is no such thing as a "stringindex" except maybe as an abstract type with the above concrete types.

**Comment by stevengj** [comment]
@elextr, I mean, have:
```julia
type StringIndex{T<:AbstractString}
    i::Int
end
```
that is used for `getindex{T<:AbstractString}(s::T, idx::StringIndex{T})` etcetera.   For UTF-xx strings, `idx.i` will be a code-unit index (e.g. a byte index for UTF8), or equivalent `s.data[idx.i]` will be the start of a codepoint.  Abstractly, `idx.i` is a `T`-dependent index, ideally with O(1) random-access characteristics.

In other words, my suggestion is just to make `StringIndex.i` exactly what we have now.  The only difference is that, by hiding `i` in a `StringIndex` type, attempts to use `+` and `-` will throw a `MethodError` (instead of being a likely bug as is currently the case).  You will have to explicitly call `nextind(s, idx)` or similar.

**Comment by elextr** [comment]
@stevengj yes, but `nextind()` has to do different things to increment by bytes, code points or graphenes or do you suggest `nextbyte()`, `nextcodepoint()` and `nextgraph()` ?

**Comment by stevengj** [comment]
@elextr, no, I suggest keeping `nextind(s, idx)` as-is: it increments to the next codepoint.   We may also add `nextgrapheme(s, idx)`.   I wouldn't bother with `nextbyte` — anything that needs to worry about bytes or code units will be low-level code that knows about the encoding and can simply look inside the `StringIndex`.

**Comment by elextr** [comment]
Ok, I misread/misunderstood/misinterpreted

>  code-unit index (e.g. a byte index for UTF8)

**Comment by nalimilan** [comment]
@stevengj I'm fine with that, actually that was kind of my original proposal.

Another middle-ground solution would be to retain `StringIndex` as you define it, and have `idx + 1` return a `StringIndexPlusOffset` object which would be like I described it in my last comment. That way, standard operations based only on a codepoint index are as fast as they could, and you can still do some arithmetic to move a given number of codepoints/graphemes from that codepoint index.

**Comment by stevengj** [comment]
I tentatively like the idea of `StringIndexOffset` type (or however you might spell it).  But I think we should start with just `StringIndex` and see how that goes.

**Comment by nalimilan** [comment]
Let's do that!

**Comment by nalimilan** [comment]
I've put together a branch using `StringIndex` as an opaque wrapper around the `Int` byte index, and I've got to the point where it starts fine. This required small changes all over the place of course. This was a very good way to assess whether this change is a good idea or not. So far I think I've learned these lessons:

* Using `StringIndex` is a very good way of unveiling places where the assumption that 1 char == one byte is done.

* I think we still need to allow adding or subtracting bytes, as this is legitimately used in many places. In particular when code needs to create arrays and exclude the last character of a substring. `StringIndex(idx.i-1)` is not very nice. Or when code concatenates ASCII characters and wants to skip the first char efficiently.
We could create a `Bytes` type and have (à la SIUnits) a `byte = Bytes(1)` object which would allow writing the much nicer `idx - 1byte` and things like that. This would both be short and explicit. (I realize for `UTF16String` and `UTF32String` adding 1 to the index moves by resp. 2 and 4 bytes, so we would need another word, but this corresponds neither to a character nor a codepoint nor anything... "basic unit"?)

* While `s[end]` works very well, `s[1:i]` is not naturally supported in this scheme. I'm tempted to allow creating `StringIndex` ranges (which I call `StringRange` ATM) with start=1, converting it to `StringIndex(1)`, as it is unambiguous and very useful. We could also support `s[start:i]`, but having a keyword just for this case sounds overkill.

* We really need a way to simply do `nextind(s, nextind(s, idx))`, as there are a few places using this or even worse situations, and it's really ugly. It could be `nextind(s, idx, 2)` or a similar function until we (possibly) find a way of doing `s[idx + 2char]`.

Note that currently I've not allowed arithmetic on `StringIndex` to see how it goes, but it could be allowed and deprecated to allow for a mostly non-breaking transition period.

How does it sound?

**Comment by StefanKarpinski** [comment]
Thanks for taking the lead with exploring this idea. Lots of food for thought here.

**Comment by stevengj** [comment]
@nalimilan, the word you are looking for is "code unit" in standards.

Couldn't `s[1:i]` be supported by an appropriate promotion operation?  i.e. `1::Integer` promotes to `StringIndex(1)`?

`nextind(s, idx, offset)` sounds okay to me.  We could also support `s[idx, offset]`.

**Comment by nalimilan** [comment]
@stevengj Good to know there's a term, thanks.

Regarding `[1:i]`, promotion could be used, but I think it's even simpler than that: just define
```julia
colon(i::Integer, j::StringIndex) =
    (i != 1 && error("integer index can only be 1 in StringRange"); StringRange(1, j))
```

**Comment by nalimilan** [comment]
After more rewriting using `s[i + 1codeunit]`, I've come to the conclusion that we should actually drop `StringIndex` in favor of `CodeUnit`. This type would behave exactly the same, we don't need two different concepts. And it would allow taking the difference between two `CodeUnits` and getting back another `CodeUnit`, which is used in many places in Base. It would also allow doing `s[2codeunit:end]`, which is a common idiom where dealing with ASCII chars.

To prevent people from doing silly things with ranges returned by `match`, iteration over `idx1:idx2` (`StringRange`) would be forbidden, but one would still be able to write `idx1:1codeunit:idx2` and get a `UnitRange{CodeUnit}` (or a similar type).

Sounds like a plan?

**Comment by StefanKarpinski** [comment]
It's definitely plausible but I'm still not convinced that all this complexity is worth it.

**Comment by nalimilan** [comment]
Well, this is the negative part of the proposal. Then we can introduce more positive features like
`s[i + 1char]` or `s[2char:end]`.

**Comment by nalimilan** [comment]
That said, even the "negative" part has an interest. I find it useful that you can immediately find code that relies on the assumption that it's working on ASCII characters by just looking for `codeunit` arithmetic. Also, not returning an `Int` from `endof(::AbstractString)` allowed me to find a bug where that function was used to compute the size of the buffer passed to `sprint` (which doesn't work when the last char takes several code units). Overall this may reduce ambiguity around `length`/`endof`/`sizeof`.

**Comment by StefanKarpinski** [comment]
I'm not clear on what the `CodeUnit` type accomplishes. Can you elaborate?

**Comment by nalimilan** [comment]
That would follow @stevengj's proposal https://github.com/JuliaLang/julia/issues/9297#issuecomment-72974149, renaming `StringIndex` to `CodeUnit`. The only difference is that the index would be less opaque, as would always be measured in code units. One would be able to create such an object by writing things like `2codeunit`, and do arithmetic between `CodeUnit` objects -- but not between `CodeUnit` and `Int` (at least not after a possible deprecation period). But most users would never need to use this arithmetic at all.

**Comment by stevengj** [comment]
I like it, I think.  The current situation is extremely error-prone for people who don't understand UTF-8, but by allowing `codeunit` arithmetic we don't lose any functionality for people who know for certain they are working with ASCII.

**Comment by nalimilan** [comment]
@stevengj The branch is really not ready for review (for example, I've left all deprecated functions in the file, and I've not updated string tests waiting for API decisions), but I've pushed it as nalimilan/stringindex.

So, should I continue experimenting with this?

**Comment by stevengj** [comment]
Thanks @nalimilan.  It's eye-opening how many places in the code use integer offsets in strings (in most cases correctly—typically for offsetting matches from searches for ASCII substrings and similar).   This will be a big user-visible breaking change if it gets merged in some form, although I'm still inclined to think it is worth it.  @StefanKarpinski?  @jiahao?

**Comment by nalimilan** [comment]
This is going to be breaking, but I think we can still leave a (possibly long) deprecation period by making `StringIndex`/`CodeUnit` behave almost as an `Int`. Allowing arithmetic operations between those types and between them and `Int`, as well as conversion from/to numbers, should make most current code continue to work.

**Comment by nalimilan** [comment]
Other thoughts? @StefanKarpinski, do you have more experimentations in mind that I should do to see whether this is worth it?

**Comment by StefanKarpinski** [comment]
Sorry, I haven't had time to look at this in detail, but I will do so later in the week and figure out if we can go with this or not and how it might integrate with the experimental sk/str branch I have going.

**Comment by nalimilan** [comment]
Interestingly, Swift does not allow indexing strings with integers, and instead provides a `String.Index` type. To get the second character of a string, you have to do something like `s[advance(s.startIndex, 2)]`. We can do better than that! They also offer no special protection against indexing a string with an index obtained on another one. http://oleb.net/blog/2014/07/swift-strings/

(FWIW, I also discovered that `Char` in Swift is defined as a grapheme cluster, and is therefore a more like a string, not a codepoint/`UInt32`. It clearly offers some advantages, but also important drawbacks as regards storage and efficiency...)

**Comment by johnmyleswhite** [comment]
Thanks for continuing on with this issue, Milan. The Swift article was very interesting to read.

**Comment by nalimilan** [comment]
@StefanKarpinski Have you made up your mind about this issue?

**Comment by StefanKarpinski** [comment]
Basically, I think it's a good idea, but I feel that the usability needs improvement. As it stands this is a bit too verbose for day-to-day usage. I'm also uncertain how it will interact with the idea of immutable inline strings, that I've prototyped – and I'm unsure if we should go with those since the memory behavior is good but the decoding performance is not as good as I had hoped. It's the least specific of objections, but I'm also not thrilled about the increase in code this produces – I find that that's often a code smell. The best refactorings reduce the amount of code required to implement the same functionality. It could be because this is in an intermediate state where two kinds of indexing still must work.

**Comment by nalimilan** [comment]
I don't know anything about your plans about immutable inline strings, but AFAICT the two issues should be orthogonal, since `StringIndex` as proposed here is just a wrapper around a byte offset.

Regarding the interface, I think it will necessarily be a bit more verbose for cases where people are working with bytes instead of characters. But these cases should be mostly limited to implementation details, as almost no user code should ever work with bytes/codeunits. Code working with characters would actually be made shorter than currently thanks to character arithmetic. (In my branch, 90% of the increase in code lines comes from deprecated functions; other changes only add `StringIndex` or `codepoint` here and there; and that code is quite special as it deals with the string internals, which user code should never do.)

Anyway, I'm not sure there's much room to improve usability as the interface is pretty simple already: `s[idx + 1codepoint]` for the next byte/codepoint, `s[idx + 1]` or `s[idx + 1char]` for the next character, `s[idx + 1grapheme]` for the next grapheme. We can discuss variants of this, but I doubt we can find something much simpler than that.

There's also the alternative where indexing with integers is still allowed, but string functions (e.g. `search`) return a `StringIndex`. This is basically what my branch does. We'd lose the increased safety but make operations on bytes easier.

**Comment by stevengj** [comment]
Should't that be `s[idx + 1codeunit]` for the next byte?  A codepoint is a character.

**Comment by nalimilan** [comment]
@stevengj Indeed, thanks, I edited my post.

**Comment by PallHaraldsson** [comment]
@nalimilan: "No, the byte offset is a good index of a position within a string" - Not even this is safe - [in my idea of a string implementation.. That is, if position means everything after that byte follows in the string.]

I support this issue. Would like to see indexing gone in 0.4 (or depreciated).

**Comment by malmaud** [comment]
This might be a good candidate for .5, where lots of changes to indexing semantics is planned.

**Comment by PallHaraldsson** [comment]
Dropping in 0.5 might be good enough, but do we then need to deprecated in 0.4? Not sure how it is done, just documenting it or needs there be a warning? Anyway I think that is a minor change to code to emit warnings and will not break any code.. [Dropping is also simple, no, except breaks code.. Not sure if much code breaks however..]

**Comment by malmaud** [comment]
Just to be clear, I'm not necessarily advocating for the removal of string indexing - just pointing out that changes to string indexing behavior might as well happen at the same time as changes to array indexing behavior.

**Comment by andreasnoack** [comment]
Two comments:

1. https://github.com/JuliaLang/julia/pull/15259 should be relevant to this discussion since the discussion of overhead from keeping a reference to a `String` predates the PR. With enough inlining, it might be possible to avoid the overhead.

2. I'm working on a project where we have to iterate large text files and quite a few of them have invalid UTF8 byte sequences. [Throwing when a sequence is invalid](https://github.com/JuliaLang/julia/blob/20c416dea53ed83f89f6a6ffe683cb506a557758/base/strings/string.jl#L230) makes it inconvenient to handle some of these files. Hence locally, I've decided to change `next` to return `'�'` in those cases. This is going a bit in the opposite direction of #22572 which throws even more but as mentioned in #23765 this might actually be a problem with the `getindex` API for strings. Hence, I'd be in favor of a string API that tried to hide the buffer and interpreted a string a sequence of characters (which is like the current string iterator) instead of a sequence of bytes. That would probably mean to stop having the `getindex` API since it would be too inefficient. #23765 seems like a good direction.

**Comment by nalimilan** [comment]
It would indeed be interesting to try again with #15259 and see whether performance has improved.

Regarding your second point, it seems that the issue of invalid sequences is mostly orthogonal to `StringIndex`. The same discussions can be developed only with the current API. The revelant issue for this is https://github.com/JuliaLang/julia/issues/22616. `next` would return `Char`s with invalid Unicode code points when the data is corrupt instead of throwing an error. `getindex` would do the same when pointed to a byte which is not part of a valid character. But it would still throw an error when pointing to the middle of a valid char, so it's not opposed to #22572 AFAICT.

The area where `StringIndex` could help is that we could rely on the assumption that an index does not point to the middle of a valid character, so we could avoid some checks. But these would only be needed for invalid sequences (i.e. continuation bytes not part of a character), since indices to valid characters will never be continuation bytes, so the overhead may not be a serious issue in practice.
