### ISSUE TITLE
more test framework features in Base

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#9305]
This is a discussion issue to elicit ideas and requirements for enhancing Base's support for testing. [FactCheck](https://github.com/JuliaLang/FactCheck.jl) is popular but there are many other testing frameworks already in the Julia ecosystem. Let's have ideas for what could / should go into Base and see where it goes. Testing packages:

- [FactCheck.jl](https://github.com/JuliaLang/FactCheck.jl) :: Midje-like testing framework written for Julia.
- [Fixtures.jl](https://github.com/burrowsa/Fixtures.jl) :: provides fixtures, mocks, matchers and patching to improve your tests with Julia.
- [Jig.jl](https://github.com/milktrader/Jig.jl) :: Testing framework for Julia.
- [JulieTest.jl](https://github.com/arypurnomoz/JulieTest.jl) :: A Julia testing framework inspired by javascript's Mocha. See the [Wiki](https://github.com/arypurnomoz/JulieTest.jl/wiki)
- [PackageTesting.jl](https://github.com/johnmyleswhite/PackageTesting.jl) :: A standard for testing Julia packages.
- [RunTests.jl](https://github.com/burrowsa/RunTests.jl) :: A test running framework for Julia that extends Base.Test
- [Saute.jl](https://github.com/milktrader/Saute.jl) :: is another testing framework for Julia.
- [testfast.jl](https://github.com/Veraticus/testfast.jl) :: Automatically finds test files and runs them.
- [UnitTest.jl](https://github.com/analyzere/UnitTest.jl) :: Another unit-testing library for Julia, that provides nose test style output to the command line and is capable of producing an junit compatible xml result file.
- https://github.com/richorama/Jester.jl

[Please post below or if you have permissions, add to the above list of packages. Added a bunch from https://github.com/svaksha/Julia.jl/blob/master/QA.md#unittest.]

**Comment by greenflash1357** [comment]
What is the latest state in the attempts to enrich Base.Test?

**Comment by IainNZ** [comment]
I tried moving some of FactCheck into Base (tracking test results rather than throwing on first failure), there was a PR but I didn't have time to follow through. So - nothing much. Any work would be welcome, and doesn't have to be a complete overhaul IMO, just incremental improvements would be great.

**Comment by kshyatt** [comment]
Can we close this? Or keep it open just until my horrible testset PR is merged?

**Comment by tkelman** [comment]
Definitely closed by `@testset` etc. This isn't about Base using them, just having the support here which it has been for a while.
