### ISSUE TITLE
using Lazy breaks type inference

### ISSUE THREAD

**Issue by one-more-minute** [JuliaLang/julia#9315]
On both 0.3 and 0.4 loading the Lazy.jl package causes `Pkg.update()` to fail at [this line](https://github.com/JuliaLang/julia/blob/f2b5a11d48d1607326a6659d951ac0e2d9661df8/base/pkg/entry.jl#L256) with the error:

```julia
ERROR: `prefetch` has no method matching prefetch(::ASCIIString, ::ASCIIString, ::Array{Any,1})
```

It looks like the type inference on the array comprehension is failing to be specific enough.

(Lazy.jl has always been oddly effective at breaking Julia, but I wasn't expecting this to happen...)

**Comment by ihnorton** [comment]
Odd: if I run this in GDB I hit a bunch of `jl_throws` for the same `MethodError` (different arguments). It takes about 20 continues before the error actually throws to the REPL. Might be a task-switching thing though.

**Comment by timholy** [comment]
Thanks for looking into this @ihnorton. I slapped a "priority" label on it, to increase your glory if you (or someone) figure it out.

**Comment by JeffBezanson** [comment]
This is #7258! The Pkg code uses some comprehensions to pass arrays to `prefetch`, and `prefetch` is only defined for String arrays.

**Comment by JeffBezanson** [comment]
What happens is that adding that `getindex` method causes the number of method matches to exceed the heuristic threshold somewhere in the Pkg code. I think everything here is in line with what we can expect without #7258 fixed.
