### ISSUE TITLE
SIMD vectorization of SubArrays and Complex numbers

### ISSUE THREAD

**Issue by mweastwood** [JuliaLang/julia#9318]
At the risk of advertising my ignorance of how `@simd` works, it would be nice if both `SubArray`s and complex arithmetic could vectorize automatically. It seems to me that by making some careful, manual adjustments to your code, you can get something equivalent to vectorize (in both cases).

For example:

```
function f!(v)
    @simd for i = 1:length(v)
        @inbounds v[i] += v[i]
    end
    nothing
end

function g!(A,start,stride,finish)
    @simd for i = start:stride:finish
        @inbounds A[i] += A[i]
    end
    nothing
end

A = ones(5,5)
@code_llvm f!(view(A,3,:)) # does not vectorize :(
@code_llvm g!(A,3,5,23)   # vectorizes!
```

And for complex numbers:

```
function f!(v)
    @simd for i = 1:length(v)
        @inbounds v[i] += v[i]
    end
    nothing
end

function g!(v_real,v_imag)
    @simd for i = 1:length(v_real)
        @inbounds v_real[i] += v_real[i]
        @inbounds v_imag[i] += v_imag[i]
    end
    nothing
end

v = ones(Complex64,5)
v_real = real(v)
v_imag = imag(v)
@code_llvm f!(v)             # does not vectorize :(
@code_llvm g!(v_real,v_imag) # vectorizes!
```

It would be convenient if `f!` vectorized in both cases.

**Comment by simonster** [comment]
We should eventually be able to vectorize `g!` as is, but if you use my [StructsOfArrays](https://github.com/simonster/StructsOfArrays.jl) package to create a StructOfArrays{Complex64} instead of an Array{Complex64}, this actually works as is.

**Comment by KristofferC** [comment]
The `sub` example (now `view`) now vectorizes. The complex one still doesn't.

**Comment by KristofferC** [comment]
All now vectorize.
