### ISSUE TITLE
try without catch not documented

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#9320]
While reviewing #9316, I learned that `try`...`end` does not require a `catch` or `finally`.  But I can't find this construct documented in the manual section about exception handling.  Did I miss something, or do we need to describe it in the manual?  The semantics are surprising for programmers coming from a C++ background, so I think it deserves notice.

The semantics seem to be that `try`_expr_`end` returns the value of _expr_, unless an exception occurs, in which case it returns `false`.

**Comment by tkelman** [comment]
Oh right, the behavior changed here. Still worth documenting 0.3's behavior on release-0.3. Would doing `git diff 76c991d7~ 76c991d7 | sed -e 's/nothing/false/g' | git apply` look okay to everyone?

**Comment by tkelman** [comment]
There were no objections so I backported the modified version (returns `false` on release-0.3) in a1b156fe81af7ee1f1bf2dcf16e9c1dc35d63ab8
