### ISSUE TITLE
edit() fails on Windows if the editor path contains slashes

### ISSUE THREAD

**Issue by wdobbie** [JuliaLang/julia#9331]
julia> ENV["JULIA_EDITOR"] = "c:/windows/system32/notepad.exe"
	"c:/windows/system32/notepad.exe"

	julia> edit(println)
	ERROR: could not spawn `c:windowssystem32notepad.exe 'C:\Users\Will\AppData\Local\Julia-0.4.0-dev\bin\../share\julia\base\string.jl'`: no such file or directory (ENOENT)
	 in _jl_spawn at process.jl:216 (repeats 2 times)

The problem seems to be that edit() calls shell_parse() in string.jl which splits the string at backslash characters. Using forward slashes as above doesn't work because realpath() is called on it first, which converts them to backslashes. Example:

	julia> s = "c:/windows/system32/notepad.exe"
	"c:/windows/system32/notepad.exe"

	julia> realpath(s)
	"c:\\windows\\system32\\notepad.exe"

	julia> Base.shell_split(ans)
	1-element Array{AbstractString,1}:
	 "c:windowssystem32notepad.exe"

**Comment by nolta** [comment]
Should be fixed by #13032, but please reopen if it isn't.
