### ISSUE TITLE
Does each text IO or Display object need to maintain a color stack?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#9353]
The positive responses to #9349 encouraged me to look into one obvious bug: once it prints something in red, it goes back to `:normal` rather than `:bold` printing. It seems to me that fixing this properly means that each relevant display object should maintain state as a stack, and `with_output_color` should `push!` and `pop!` from the stack.

However, I really don't know much about our Display infrastructure or terminals & display in general, so I'm soliciting advice/involvement from experts like @stevengj and @StefanKarpinski.

**Comment by vtjnash** [comment]
yes.

see #14052 for discussion

**Comment by KristofferC** [comment]
I think it is unlikely for more advanced color printing to get into Base. To note, Crayons.jl does support exactly this kind of stack: https://github.com/KristofferC/Crayons.jl#advanced-nesting-of-colors-and-styles so in the spirit of moving things out of Base, pointing to that package seems good enough for now. If we need it for our own error reporting it could be brought in later in some sort of standard library style.
