### ISSUE TITLE
Misplaced $-interpolation leads to puzzling error message

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#9358]
I accidentally typed `$` instead of `#` in a comment and it lead to a perplexing error message which I ultimately traced down to this behavior:

```jl
julia> foo() = while true
           break #Overflow
       end
foo (generic function with 1 method)

julia> foo()

julia> bar() = while true
           break $Overflow
       end
bar (generic function with 1 method)

julia> bar()
ERROR: error compiling bar: unsupported or misplaced expression "break" in function bar

julia> baz() = while true
           break 1
       end
ERROR: syntax: extra token "1" after end of expression
```

Posting this here in case anyone can figure out a better error message to print in this situation.

---

Unfortunately vim highlights `#` and `$` the same way

![screen shot 2014-12-14 at 4 58 52 pm](https://cloud.githubusercontent.com/assets/1732/5429250/8bccba26-83b2-11e4-9735-12fa21457297.png)

but that's a separate issue.

**Comment by carlobaldassi** [comment]
> Unfortunately vim highlights `#` and `$` the same way [...] but that's a separate issue.

That's strange, comments and dollar-prefixed-words are indeed highlighted differently, even with vim's (awful) default colorscheme. Try changing your colorscheme, and if that doesn't solve it please do file an issue in [julia-vim](https://github.com/JuliaLang/julia-vim).
