### ISSUE TITLE
@test_approx_eq never finds random Float16 arrays different

### ISSUE THREAD

**Issue by sawcordwell** [JuliaLang/julia#9359]
When testing approximate equality of Float16 arrays with @test_approx_eq from Base.Test on Julia 0.4 dev, the following produces no error:

```
using Base.Test
for x = 1:10000
  @test_approx_eq rand(Float16, 10,10) rand(Float16, 10, 10)
end
```

However, for the Float32 case once should be sufficient to get an assertion error:

```
@test_approx_eq rand(Float32, 10,10) rand(Float32, 10, 10)
```

As @johnmyleswhite [pointed out](https://groups.google.com/forum/#!topic/julia-users/VltElZMgQ-c) when comparing the absolute difference with the eps() of the maximum value, the random arrays are usually different:

```
rseed(0)
t = 0
for x = 1:10000
  x = rand(Float16, 10, 10)
  y = rand(Float16, 10, 10)
  if all(abs(x - y) .> eps(max(maximum(x), maximum(y))))
    t += 1
  end
end
t / 10000
```

In this case it is true 90.23 % of the time.

I found that the function in Base.Test to compute the tolerance for @test_approx_eq

```
array_eps(a) = eps(float(maximum(x->(isfinite(x) ? abs(x) : oftype(x,NaN)), a))) # base/test.jl line 141
va=rand(Float16, 10,10);
vb=rand(Float16, 10,10);
1E4*length(va)*max(array_eps(va), array_eps(vb)) # base/test.jl line 144
```

will give a value of about 488.

**Comment by stevengj** [comment]
Given #12472, we now have:
```jl
julia> for x = 1:10000
         eq += rand(Float16, 10,10) ≈ rand(Float16, 10, 10)
       end

julia> eq 
0
```
if we use `≈` rather than `@test_approx_eq`.

**Comment by KristofferC** [comment]
`@test_approx_eq` is now deprecated.
