### ISSUE TITLE
Segmentation fault pressing Ctrl-C during Pkg.update()

### ISSUE THREAD

**Issue by sawcordwell** [JuliaLang/julia#9362]
On Julia 0.4, If I run Pkg.update() then immediately press Ctrl-C I get "ERROR: Interrupt". However, if I wait for about 5 seconds then press Ctrl-C I get a Segmentation fault. If I wait about 10 seconds, I get the error message again. I can get the same behaviour on 0.3.3.

EDIT: versioninfo()
Julia Version 0.4.0-dev+2135
Commit 6dbcf80* (2014-12-14 21:25 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by jiahao** [comment]
Similar to #1468

**Comment by jakebolewski** [comment]
I don't think this issue is relevant anymore.
