### ISSUE TITLE
Less verbose way of initializing a Nullable field to null

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#9364]
This issue is to track and generate consensus on having a simpler method to nullify a Nullable field.

If we have a type with a large number of Nullable fields that we want to initialize with empty values:

```
type Foo
  x1::Nullable{Int}
  x2::Nullable{Bool}
  x3::Nullable{AbstractString}
...
end
```

the current method involves having the constructor as `Foo() = new(Nullable{Int}(), Nullable{Bool}(), Nullable{AbstractString}().... )`. For a large number of fields it involves matching the Nullable container type in the constructor and can be a bit painful.

See issues #9351, #8423 for the previous discussions about this.

**Comment by nalimilan** [comment]
@JeffBezanson "My opinion is heavily that way". :-)

I really prefer `null` to `nulled`, except if that's only intended as a stopgap until the deprecation period for `null` is over.
