### ISSUE TITLE
Possible source of confusion with Array constructor and parametric type

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#9370]
We were talking in the JuliaOpt office (lol) about type stability, and were musing on the fact that are fairly common error is to do something like

``` julia
type Foo
  x::Array{Int}
end
```

which is under-typed, because you need the dimension as well. Why would people not use the dimension? Well, one possible confusion is:

``` julia
x = Array(Int, 10)  # An array of 10 ints
y::Array{Int, 10}  # y is a dimension 10 array of ints
```

So the "second argument" has wildly different meanings. Maybe people assume they are same? Or just don't know and punt? Or maybe when people type `Array{Int}` they think it means `Vector{Int}`?

Looking for any ideas about whether this is a problem, and if there is any "fix" possible.

(can also move to julia-dev if more appropriate)

**Comment by KristofferC** [comment]
`Array(Int, 10)` is now deprecated.
