### ISSUE TITLE
Default OPENBLAS_DYNAMIC_ARCH to off, add one master "portable Julia" build flag

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#9372]
This is a reminder for something I've been meaning to do for a while. Figured I'd open a tracking/discussion/up-for-grabs issue on it. For building Julia from source, my guess is that most people are only intending to run Julia on the single machine they're compiling it on. But building OpenBLAS with `OPENBLAS_DYNAMIC_ARCH` enabled, which is our current default, takes a really long time.

I think we should switch the default - but at the same time, for the sake of the people who _are_ intending to run Julia on multiple machines, it would be convenient to add a single consolidated flag that sets `OPENBLAS_DYNAMIC_ARCH` and `MARCH` and whatever else makes sense when building a portable version of Julia, all at the same time. Sort of like we have the one master MKL flag that sets all the other related Intel library flags together. Name of the flag is subject to bikeshedding. Maybe `JULIA_PORTABLE` or something like that?

**Comment by Keno** [comment]
bump :)

**Comment by ViralBShah** [comment]
I am ok with turning off DYNAMIC_ARCH in the developer build and enabling in the distribution builds.

**Comment by tkelman** [comment]
but that wouldn't be backported, so 0.5.x is not appropriate

**Comment by tkelman** [comment]
nice-to-have but not immediately release blocking IMO

**Comment by StefanKarpinski** [comment]
This seems like a feature and therefore not a 1.0-blocker.

**Comment by tkelman** [comment]
openblas definitely takes longer to build than llvm. and with the function multiversioning features this would be more useful than just for openblas

**Comment by ViralBShah** [comment]
While it would be great to have the portable julia level flags, I don't think we should have the default build turn off dynamic_arch in openblas. Perhaps we can reopen the issue with a title to focus on portability rather than changing the defaults.

**Comment by tkelman** [comment]
Why not? Turning it off would save considerably on build time, and not be noticeable for the vast majority of what people do with source builds.
