### ISSUE TITLE
references to interpolated values persist in modules

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#9375]
The following code:
```
type MyType
    function MyType()
        t = new()
        finalizer(t,t->println("finalized"))
        t
    end
end


function go()
    t = MyType()
    return
end

for i in 1:10
    go()
    println("returned from go()")
    gc()
end
println("finished")
```

prints
```
returned from go()
returned from go()
returned from go()
returned from go()
returned from go()
returned from go()
returned from go()
returned from go()
returned from go()
returned from go()
finished
finalized
finalized
finalized
finalized
finalized
finalized
finalized
finalized
finalized
finalized
```

(It sometimes also segfaults in ``uv_write2``, hoping that that's already captured in some issue...)

Why doesn't the GC finalize the object when ``gc()`` is called? If I use a large object like an array instead, I see the expected behavior. I'm guessing that the object seems too small to care about, but this behavior is particularly bad if the object really represents an opaque C struct whose memory the Julia GC isn't aware of.

Ref JuliaOpt/JuMP.jl#330

**Comment by mlubin** [comment]
I don't mind if this is closed as wontfix. I understand now that values spliced into functions become module variables which won't be gc'd with the function itself.

**Comment by vtjnash** [comment]
improvements have been made here (especially with the anonymous function rewrite)
