### ISSUE TITLE
embedding example output different on mingw console and windows cmd

### ISSUE THREAD

**Issue by armgong** [JuliaLang/julia#9377]
julia version master branch on win32 and 64 build, output  on mingw console lost most output !

![screen](https://cloud.githubusercontent.com/assets/4819374/5449028/e1a8f556-8527-11e4-8307-b54a7a98029b.PNG)

**Comment by ihnorton** [comment]
I added an export declaration around the callback, so that part now works.

As far as the difference in output between cmd and mintty, the cause is the dreaded mintty [issue #56](https://code.google.com/p/mintty/issues/detail?id=56) and I'm not sure how much we can do about it.

**Comment by ihnorton** [comment]
After reading through that mintty issue, I'm closing this. Fixing the broken nonsense of the windows console system is out of scope.

**Comment by ihnorton** [comment]
(I suppose we could try pinging https://github.com/satyanadella!)

**Comment by tkelman** [comment]
might be in better shape on windows 10?
