### ISSUE TITLE
method order doesn't match my intuition

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#9382]
Perhaps this is the intended behavior, and could maybe serve as an illustration in the documentation, or something could be improved and this could be added to https://github.com/JuliaLang/julia/issues/8974

(originally posted on https://groups.google.com/forum/#!topic/julia-users/_paVdB2wy5k)

I didn't expect this

```julia
julia> f{T}(x::Complex{T},y::T) = println("here")
f (generic function with 1 method)

julia> f{T}(x::Complex{T},y::Real) = begin println("there"); f(x,convert(T,y)) end
f (generic function with 2 methods)

julia> methods(f)
# 2 methods for generic function "f":
f{T}(x::Complex{T},y::Real) at none:1
f{T}(x::Complex{T},y::T) at none:1

julia> f(Complex(1.0),1.0)
```
The last line causes an infinite recursion because

```julia
julia> @which f(Complex(1.0),1.0)
f{T}(x::Complex{T},y::Real) at none:1
```
I expected `f{T}(x::Complex{T},y::T)` to be more specific than `f{T}(x::Complex{T},y::Real)`

If this is the intended behavior, should I just be defining `f{T}(x::Complex{T},y::Real) `  and always doing the convert? I was trying to follow the pattern of the promotion system.

**Comment by JeffBezanson** [comment]
Closing as dup of #6383 and #3025
