### ISSUE TITLE
Add some contrib bits to tarballs?

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#9392]
`julia-mode.el` doesn't currently get put into the prebuilts, but, as it is equally useful for julia users who are not (yet) contributors as those who are, It occurs to me that it might make sense to do so (along with the other editor support bits, of course).

Does this make sense? What else might we include?

**Comment by ViralBShah** [comment]
I think we may want `share/julia/contrib`. 

@staticfloat @nalimilan @tkelman Thoughts?

**Comment by nalimilan** [comment]
I don't think it should be installed. The point of these files is that they should be installed in the directory where the editor will look for them, not in an arbitrary place. So they could be included in the binary tarballs in a `contrib/` folder, but `make install` should put them where the editor expects them (or do nothing).

**Comment by staticfloat** [comment]
For people downloading things like the linux tarball and such, I think putting things in `share/julia/contrib` is useful

**Comment by tkelman** [comment]
I've seen many distributions package different editor plugins as separate subpackages, so I can see why @nalimilan is not a fan here. Also don't most modern editors have independent plugin-management systems that usually pull the latest content from github master? There's a potential issue there when the editor support files could be up-to-date with language changes that aren't yet applicable to the release versions of Julia that many users will be working with.

**Comment by ViralBShah** [comment]
I think it is reasonable for distros to manage this their own way, but `share/julia/contrib` certainly should be ok for us to distribute in all our binaries.

**Comment by twadleigh** [comment]
This is pretty stale at this point. Closing.
