### ISSUE TITLE
Allow date periods to be represented by Floats

### ISSUE THREAD

**Issue by kbuzby** [JuliaLang/julia#9393]
Dates currently forces the periods to be integer types which does not allow for functions like 1 day / 2 = 0.5 days or 12 hours even. Is there a way to base date types on the millisecond and the specific type (day,hour,etc) is just the appropriate conversion? 

I know this would only work up until the "week" type, but it would allow for better arithmetic of dates types below the week level.

**Comment by Jeffrey-Sarnoff** [comment]
fwiw there is an 'always' in "it is bad practice to use floats with dates and/or times." 
one reason: the nonuniform, jump-gapped density of increasing floating point values

**Comment by quinnj** [comment]
This has been open for quite a while now with no progression or discussion. I'm firmly in the camp of keeping everything integer-based, unless someone out there is really willing to go all out and do a full re-implementation based on Floats. I still believe, though, that one of the strengths of our Dates implementation is the amount of functionality and performance we achieve with such small, readable code. Happy to re-open if people feel strongly, but I think we close as decided.
