### ISSUE TITLE
Improve documentation about embedding julia in C/C++ with a customized image

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#9400]
Hi guys!

I am trying to embedded julia in a project here in my institution. I coded a example that called a julia script (just a julia function called orbit_computation()) inside a C++ software. Everything worked as expected. However I had one little concern: in this case, I will need to install the script in plain text in the user machine. This is not good because anyone can open the text file and if a bad modification is done, then things will not work correctly. Thus, I realized that using the script written plain text is good for development, but it is not good to send such script together with the package.

Searching on Internet, I found an amazing feature of Julia in this post: https://groups.google.com/forum/#!topic/julia-dev/qdnggTuIp9s

Basing on that post, I copied the directory /usr/share/julia to another location, modified the userimg.jl to add my package, and declared the function orbit_computation() as @Base.ccallable. After, I executed julia --build to build my new sys.ji image and then g++ to create the sys.so. After that, I was able to use my orbit_computation() function as it was a native C function by just adding to the source file:

extern "C" {
extern int64_t orbit_computation();
}

Then, I copied the executable, libjulia.so, the new sys.ji, and sys.so to a new machine without julia installed. By the way, in the C++ software, I started julia using 

jl_init_with_image(currentPath, "./sys.ji");

When I ran the executable in the new machine, everything worked as expected. In my opinion, this is an amazing feature of Julia. It is totally transparent to the C++ programmer that the function orbit_computation() was written on Julia. The user also does not even need to know what Julia is.

Thus, I am opening this issue to improve the documentation about this process. I searched but I have not found any mention to ccallable functions or a how to build your own sys.ji image in the official documentation.

**Comment by ihnorton** [comment]
Now documented: http://docs.julialang.org/en/release-0.3/devdocs/sysimg/?highlight=userimg#building-the-julia-system-image

**Comment by cako** [comment]
Hi everyone, I was wondering if this is still the most straightforward approach to call embed Julia with as little overhead for the user? If so, is there any up-to-date documentation? The link @ihnorton shared is unfortunately broken.

Cheers!

**Comment by ihnorton** [comment]
@cako I fixed the link to the latest version.
