### ISSUE TITLE
Document `@inbounds`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#9405]
In notice that `@inbounds` and `@simd` are mentioned in `performance-tips.rst`, but are not properly documented elsewhere. In which sections should they go?

**Comment by ViralBShah** [comment]
Where do you think we should do this? You are already in the guts of this with `@fastmath` documentation, and perhaps this can be addressed at the same time.

**Comment by kshyatt** [comment]
This [has docs](http://docs.julialang.org/en/latest/stdlib/base.html#Base.@inbounds) now :)
