### ISSUE TITLE
Markdown line breaks?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#9410]
I don't know if the intention is to support the entire CommonMark spec, but
http://spec.commonmark.org/0.13/#hard-line-breaks mentions a couple of ways to get line breaks, none of which work for me.

**Comment by hayd** [comment]
At the moment we only respond to `\\\n` this should be also respond to `\s{2,}`.

**Comment by ufechner7** [comment]
Why was this issue closed? Creating a line brake in a paragraph of an enumeration still does not work.
