### ISSUE TITLE
listen(::UTF8String) throws error

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#9435]
```
julia> listen(UTF8String("/tmp/ewewew"))
ERROR: `bind` has no method matching bind(::PipeServer, ::UTF8String)
Closest candidates are:
  bind(::PipeServer, ::ASCIIString)
```

`listen(path::ByteString)` which calls `bind(server::PipeServer, name::ASCIIString)` is the issue. I assume that `bind` can be changed to accept a `ByteString` without any issues?

**Comment by stevengj** [comment]
I agree.  `bind` calls `uv_pipe_bind`, which seems to support UTF-8 strings.  The Windows `uv_pipe_bind` explicitly converts the name to UTF-16 and calls `CreateNamedPipeW`.  On Unix, I think UTF-8 should be allowed to (Unix pathnames are usually cookies, and any ASCII superset is permitted).

**Comment by stevengj** [comment]
Actually, you can just use `AbstractString` here.  Arbitrary string types will be converted by `bytestring` to UTF-8 as needed (see #5677).
