### ISSUE TITLE
Export samefile, make it smarter for nonexistent inputs

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#9436]
Just realized at https://github.com/JuliaLang/julia/pull/9376#discussion_r22149074 that anywhere we do file path comparisons is potentially very error-prone on case-insensitive filesystems. We have `realpath` and `normpath` which look similar but are implemented differently, and neither appear to be doing anything about case. Should we have a special string literal specifically for file paths that has comparison defined? Or a differently-named function to compare if file paths point to the same thing? `normalize_string` with `casefold=true` might be the sane thing to use here, but do we currently have an API for determining whether the file system is case sensitive? On Mac it's configurable so can't always be assumed one way or the other, right?

**Comment by tkelman** [comment]
this is somewhat improved by fec7ef16b3312f3b2eddbd4f0ff006181fbc1c64 (now returns false if either input does not exist), but `samefile` should probably still be documented, advertised and exported

**Comment by nalimilan** [comment]
Looks like a good candidate for the "intro issue" label (it was already "up for grabs").
