### ISSUE TITLE
A parallel split inversions algorithm causes an assertion failure

### ISSUE THREAD

**Issue by 11Kilobytes** [JuliaLang/julia#9444]
The following program causes julia v0.3.3 to crash with an assertion failure:

     function sortAndCountInv(arr :: Array{Int}; start :: Int = 1, finish :: Int = length(arr))
        lengthOfSubarray = (finish - start) + 1
        if lengthOfSubarray == 0 || lengthOfSubarray == 1
            return 0
        else
            half = (start + finish) ÷ 2
            leftInversions = @spawn sortAndCountInv(arr, start=1, finish=half)
            rightInversions = @spawn sortAndCountInv(arr, start=half + 1, finish=finish)
            splitInversions = mergeAndCountSplitInv(arr, start, half - start + 1, finish)
            return fetch(leftInversions) + fetch(rightInversions) + splitInversions
        end
    end
    
    function mergeAndCountSplitInv(arr::Array{Int}, start :: Int, divider::Int, finish :: Int)
        aux = arr[start:finish]
        i = 1
        j = divider + 1
        totalSplitInv :: Int = 0
        lastIndex = length(aux)
        for k = start:finish
            if i > divider
                arr[k] = aux[j]
                j += 1
            elseif j > lastIndex
                arr[k] = aux[i]
                i += 1
            elseif aux[i] < aux[j]
                arr[k] = aux[i]
                i += 1
            else
                arr[k] = aux[j]
                j += 1
                totalSplitInv += (divider - i) + 1
            end
        end
        return totalSplitInv
    end
    
    ints = open(s -> map(int, readlines(s)), "IntegerArray.txt")
    print(sortAndCountInv(ints))

Where the file IntegerArray.txt can be found here: http://spark-public.s3.amazonaws.com/algo1/programming_prob/IntegerArray.txt

I don't think there's a race condition as the two recursive calls affect different elements of the input array. 
Julia prints back the following error message consistently (during 5 runs, I got this message 5 times):

    Assertion failed: (jl_is_array(vi)), function emit_function, file codegen.cpp, line 3272.
    
   signal (6): Abort trap: 6
    __pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
    [1]    17916 abort      julia progex.jl -p 4

My OS is Mac OS X Yosemite, I got julia by using `brew install julia`.

**Comment by jiahao** [comment]
I was not able to reproduce this failure on 0.3.6-pre. Instead, I got the error that `sortAndCountInv` was not defined on the worker processors when run with `julia -p 4`. Putting `@everywhere` in front of the function resulted in the code running.

When run on the original data set my machine runs out of swap space. This is not surprising since this code generates an exponentially large number of `Task`s. For an input of 16 numbers `sortAndCountInv()` was called approximately 4,159 times.
