### ISSUE TITLE
Help string for "include" is not accessible from the REPL help?> mode

### ISSUE THREAD

**Issue by phobon** [JuliaLang/julia#9454]
I see there is help text in the online manual but it doesn't seem to be accessible from the REPL.
```
help?> include
include_from_node1 (generic function with 1 method)
```
I presume this is because the `include` symbol gets reassigned at some point.
```
julia> methods(include)
# 1 method for generic function "include_from_node1":
include_from_node1(path::AbstractString) at loading.jl:119
```

**Comment by phobon** [comment]
Reopening this because #4226 was closed but this problem persists. The error seems to be that `include` maps to `include_from_node1`, which is a distinct issue from the keyword documentation.

Maybe @one-more-minute knows of a simple fix for this too?

**Comment by one-more-minute** [comment]
Yeah, these weren't really the same issue in the end – thanks for re-reporting, anyway. Should be fine now.
