### ISSUE TITLE
Benchmarking harness for Julia

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#9456]
Julia as a language is not only about correctness, it is also about performance. Consequently, there should be a benchmarking harness in `Base`, equivalent to the testing harness `Base.Test`. This would allow several interesting things:
- Performance regressions are noticed earlier
- People can look at the benchmarks, and learn efficient coding styles
- The benefit of certain changes (`@inbounds`, `@fastmath`) is immediately clear
- Dangerous changes "for the sake of performance" (e.g. using `@inbounds` in `Base`) can be vetted; they would only be allowed if they actually show a performance benefit

Since performance varies by architecture, it is probably necessary to set up a few dedicated testing machines where the benchmarks can be run regularly. These machines would need to keep a history of benchmark results for comparison. I've seen <http://speed.julialang.org/> which looks interesting -- I wonder if it could be set up to look at potentially thousands of small benchmark results.

I imagine that many Julia packages will in the future contain `@bench` statements in addition to `@test` statements.

**Comment by eschnett** [comment]
@vtjnash Above, I was describing how the interface to a benchmarking harness should look like, not how it should be implemented. Of course one needs an optimizing compiler to avoid spurious overhead, needs to perform many operations to mitigate timing overhead, needs to ensure inlining to avoid function call overhead, etc. But that isn't the point here -- I chose "integer addition" only because that led to a small example. Replace it by "insert values into a dictionary", or "multiply two matrices", or "task creation overhead" if you like; those can definitely be benchmarked.

I've seen some positive responses here, as well as pretty concrete suggestions about making benchmark results more easily available, e.g. "Seems like a good up-for-grabs/undergraduate project." Could you re-open this issue so that this doesn't get forgotten?

**Comment by vtjnash** [comment]
i came across this paper on measurement bias, and thought the various individuals interested in benchmarking in this thread might find it a good read:
http://www.inf.usi.ch/faculty/hauswirth/publications/asplos09.pdf
also, I think the next time i hear someone claim that bounds-checking caused an unacceptable 10% slowdown in their program, I'll ask if they've remembered to optimize their linker order.

also, one of the other publications by the same group offers some evidence that we should be doing statistical profiling with a non-uniform timeout:
http://sape.inf.usi.ch/publications/pldi10
that might be a really good "up-for-grabs" project, to experiment with Julia's sampling profiler (in profile.c) and determine if it gives improved results with a non-uniform sampling interval

**Comment by timholy** [comment]
Nice set of links, @vtjnash!

**Comment by ScottPJones** [comment]
@vtjnash, yes, great link... I had to deal with that a lot on early Alpha chips (direct mapped cache instead of n-way associative cache... link order could make huge difference in performance... until we figured out what it was, we were going crazy trying to get consistent benchmark results...
