### ISSUE TITLE
Returning Multiple RemoteRefs Error

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#9457]
I found that returning multiple values using remotecall produces a (rather strange) error.  Does anyone know why this would fail in parallel?  Although there are a few workaround (using arrays and cell arrays), it would be very useful to be able to directly reuse functions that work in serial for parallel codes.

Here is the script file Script1.jl that triggers the error:
```
# script to be executed on process 1
# run with julia -p 1 ./Script1.jl

@everywhere include("funcs.jl")

a = 1
b = 2

ret1 = remotecall(2, func1, a, b)
wait(ret1)

ret2, ret3 = remotecall(2, func2, a, b) 		# error
wait(ret2)

```

and here is the function file funcs.jl:

```
function func1(c, d)

println("c = ", c)
println("d = ", d)

return c

end


function func2(c, d)

println("c = ", c)
println("d = ", d)

return c, d

end 
```

Here is the error info:

ERROR: `start` has no method matching start(::RemoteRef)
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_1720 at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
while loading /home/dev1/julia_tests/ret_values/Script1.jl, in expression starting on line 12

Julia version info
Julia Version 0.3.3
Commit 21d5433* (2014-10-21 20:18 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by malmaud** [comment]
This is kinda tricky. The docs for `remotecall` seems pretty clear and the very first section in the parallel computing manual chapter explains that `remotecall` returns a RemoteReference. But you do have to understand that `returning multiple values` just means returning a single tuple whose elements are the individual return values.

@JaredCrean2, I'd be interesting in hearing your thoughts on what could make the documentation clearer.

**Comment by JaredCrean2** [comment]
I didn't realize this issue was still open.  I just tested with a more recent version of Julia and found if I change the script to:

```julia
# script to be executed on process 1
# run with julia -p 1 ./Script1.jl

@everywhere include("funcs.jl")

a = 1
b = 2

ret1 = remotecall(2, func1, a, b)
wait(ret1)

ret2 = remotecall(2, func2, a, b) 
wait(ret2)
a1,b2 = fetch(ret2)  # unpack the tuple here
println("a1, b1 = ", a1, ", ", b2)
```
then everything works as expected.  Returning a single RemoteRef pointing to a tuple seems like a reasonable way to of doing things combined with the documentation, so I'll close.
