### ISSUE TITLE
docs should explicitly explain/define global scope and globals

### ISSUE THREAD

**Issue by uvtc** [JuliaLang/julia#9469]
In doc/manual/variables-and-scoping.rst, it should explicitly define what "global scope" means and also what a global is.

**Comment by mauro3** [comment]
@elextr comment goes into soft vs hard scope: #9955

**Comment by mauro3** [comment]
I think that section of the manual needs to include the scope rules for modules, from which the definition of what a global is follows:  modules introduce a new global scope. No bindings are inherited from any other modules unless explicitly imported (with `using` or `import`; note that `Base` is used implicitly unless it's a baremodule).  This then also explains why globals from one module cannot be seen in another module, unless imported (this confused me when I started with Julia. E.g. in Matlab a global is totally global).

**Comment by mauro3** [comment]
Fixed with #12146, please close.
