### ISSUE TITLE
userimg: Reuse existing sys.[ji,so]?

### ISSUE THREAD

**Issue by few** [JuliaLang/julia#9470]
Scenario: A user wants to create a new sys.so containing code from userimg.jl.

Then the user may run build_sysimg.jl and get that done. The problem with this is that most of the time to get there is spend parsing/compiling Base, which the user didn't touch.

Would it be possible to be change this process to reuse the Base found in an existing sys.[ji,so] and just compile the code in userimg.jl and then combine both into a new sys.so?

**Comment by vtjnash** [comment]
this has been significantly addressed by #8745 and #11274, any the remainder should be covered by #5155
