### ISSUE TITLE
Segmentation fault at ctranspose! after lufact! on OS X 10.10.1

### ISSUE THREAD

**Issue by rleegates** [JuliaLang/julia#9472]
Dear Julia developers,

I encountered a segmentation fault on a fresh install of OS X 10.10.1 and Julia 0.3.4 (problem also in 0.3.3) after a call to lufact! and \\. The minimal example to reproducing this error is:

	julia> A = speye(3)
	3x3 sparse matrix with 3 Float64 entries:
		[1, 1]  =  1.0
		[2, 2]  =  1.0
		[3, 3]  =  1.0
	
	julia> b = rand(3)
	3-element Array{Float64,1}:
	 0.932498
	 0.340124
	 0.613643
	
	julia> lufact!(A)
	UMFPACK LU Factorization of a 3-by-3 sparse matrix
	Ptr{Void} @0x00007fd665312ba0
	
	
	julia> A\b
	
	signal (11): Segmentation fault: 11
	ctranspose! at sparse/csparse.jl:190
	ctranspose at sparse/csparse.jl:212
	ishermitian at sparse/sparsematrix.jl:1779
	CholmodSparse at linalg/cholmod.jl:458
	factorize at linalg/cholmod.jl:1073
	\ at linalg/generic.jl:233
	jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/gf.c:1418
	jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:59
	eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:207
	jl_toplevel_eval_flex at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/toplevel.c:496
	jl_f_top_eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/builtins.c:399
	eval_user_input at REPL.jl:53
	jlcall_eval_user_input_20042 at  (unknown line)
	jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/./julia.h:981
	anonymous at task.jl:95
	jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/task.c:423
	julia_trampoline at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/init.c:1035
	Segmentation fault: 11

My Julia versioninfo() gives:

	Julia Version 0.3.4
	Commit 3392026* (2014-12-26 10:42 UTC)
	Platform Info:
	  System: Darwin (x86_64-apple-darwin13.4.0)
	  CPU: Intel(R) Xeon(R) CPU           W3520  @ 2.67GHz
	  WORD_SIZE: 64
	  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
	  LAPACK: libopenblas
	  LIBM: libopenlibm
	  LLVM: libLLVM-3.3

As I do not have a debug build, and the error is easy to reproduce, I hope this information will suffice.

Best regards,

Robert

**Comment by andreasnoack** [comment]
Fix by #9472.
