### ISSUE TITLE
Scripts runs interactively, but not from console

### ISSUE THREAD

**Issue by bdeonovic** [JuliaLang/julia#9476]
I am writing a script that I would like to run from the console like 

```bash
julia -p 6 SLRA.jl input1 input2
```

notice it makes use of multiple processors. When I run the script in this way I get:
```julia
exception on 2: ERROR: genes not defined
 in anonymous at no file:1432
 in anonymous at multi.jl:1279
 in anonymous at multi.jl:848
 in run_work_thunk at multi.jl:621
 in run_work_thunk at multi.jl:630
 in anonymous at task.jl:6
```
on all of the processors (not just 2). I think the offending section in the code might be: 

```julia
  result = Array(ASCIIString, length(keys(gene_dict)))
  genes = collect(keys(gene_dict))

  generefs  = [ @spawnat i genes for i in 1:nprocs()]
  dict1refs = [ @spawnat i gene_dict for i in 1:nprocs()]
  dict2refs = [ @spawnat i transcript_dict for i in 1:nprocs()]

  result = @parallel (vcat) for i in 1:length(genes)
    EM(fetch(genes[i]), fetch(gene_dict), fetch(transcript_dict))
  end
```
where `EM` is a function that is defined on all processors earlier on. Now the funny thing is that when I run this script line by line in an interactive session (open julia terminal with `julia -p 6`) it works! What could be the issue? 

I have tried on:

```julia
julia> versioninfo()
Julia Version 0.4.0-dev+2200
Commit 79d473c (2014-12-18 17:30 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

and

```julia
julia> versioninfo()
Julia Version 0.3.4
Commit 3392026* (2014-12-26 10:42 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2609 0 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by andreasnoack** [comment]
`julia-dev -p 2 MCF7.jl refFlat_small.gpd lr_x_hg19TransSmall.psl` works fine on my mac with
julia> versioninfo()
Julia Version 0.3.5-pre+35
Commit 74b8f6a* (2015-01-04 14:06 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by bdeonovic** [comment]
The script I linked to has the two input files hardcoded in (so I could run it from REPL), but when I replace it with ARGS[1] and ARGS[2] and try to call the script from console I get errors. Is this what you tried? Or did you you just run the script from console?

**Comment by amitmurthy** [comment]
Same here. `julia -p 4 MCF7.jl refFlat_small.gpd lr_x_hg19TransSmall.psl` works fine on my linux box. I did replace the filenames with ARGS[1] and ARGS[2].

**Comment by andreasnoack** [comment]
Yes, I did replace the hard coded filenames with `ARGS[1]` and `ARGS[2]`.

**Comment by jakebolewski** [comment]
Closing as the code to reproduce the bug no longer exists, and it doesn't seem reproducible.  Feel free to reopen if this is still an issue.
