### ISSUE TITLE
Update "Try to avoid nullable fields" advice

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#9480]
The current style guide [says](http://julia.readthedocs.org/en/latest/manual/style-guide/#try-to-avoid-nullable-fields):

> Try to avoid nullable fields
> When using x::Union(Nothing,T), ask whether the option for x to be nothing is really necessary. Here are some alternatives to consider:

This section is probably outdated with the introduction of `Nullable` types (c.f. #8152).

**Comment by jiahao** [comment]
any thoughts @johnmyleswhite?

**Comment by johnmyleswhite** [comment]
I think this section should be almost entirely replaced: https://groups.google.com/d/msg/julia-dev/ygLhSERO25c/c-NOiKt8DxEJ

**Comment by nalimilan** [comment]
Actually I fixed that back in March via https://github.com/JuliaLang/julia/pull/10551.
