### ISSUE TITLE
Showing a dict can be slow

### ISSUE THREAD

**Issue by ncnc** [JuliaLang/julia#9481]
The `showkv` function in `dict.jl` (latest master) contains the following code:
```
    for (i, v) in enumerate(iter)
        print(io, "\n  ")
        limit && i >= rows && (print(io, "⋮"); break)

        str = sprint(show, v)
        limit && (str = _truncate_at_width_or_chars(str, cols, "\r\n"))
        print(io, str)
    end
```
If `v` is "large", the above can be arbitrarily slow due to the `sprint(show, v)` part.

Below an example showing the problem from the REPL:
```
N = 1000000
d = Dict{ASCIIString,Array{Float64}}()
for i = 1:50
    d["Label $(i)"] = rand(N,1)
end
d   # takes a while to print
```
Increase N as necessary.

**Comment by hayd** [comment]
@vtjnash except for the failing early there's already a maxsize for IOBuffer (at least I don't think this fails early?). In fact there's already a [sprint with a size option](https://github.com/JuliaLang/julia/blob/03e2d1dbee1b27067e06298618b6aa118e620a4a/base/iostream.jl#L226), though it's unclear to me if the intention was for this to be a sizehint or a maxsize:

    s = IOBuffer(Array(UInt8,size), true, true, size)  # would make it a maxsize

**Comment by JeffBezanson** [comment]
This works pretty well as a stop-gap:

```
diff --git a/base/dict.jl b/base/dict.jl
index a496b5d..1fed3f5 100644
--- a/base/dict.jl
+++ b/base/dict.jl
@@ -97,9 +97,11 @@ function showdict{K,V}(io::IO, t::Associative{K,V}; limit::Bo
         print(io, key)
         print(io, " => ")
 
-        val = sprint(show, v)
         if limit
+            val = with_output_limit(()->sprint(show, v))
             val = _truncate_at_width_or_chars(val, cols - keylen, "\r\n")
+        else
+            val = sprint(show, v)
         end
         print(io, val)
     end
```
