### ISSUE TITLE
document staged functions

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#9489]
#7474 was merged some time ago, but does not seem to have been documented.  Is this because the syntax is still in flux?

**Comment by yuyichao** [comment]
IMHO, it is still a good idea to mention something about it in the latest document. This will help ppl, like me, who are not core devs but are experimenting the master branch to know about this feature and possibly give feedback.

**Comment by ViralBShah** [comment]
As I said in another issue, I do think it is still worth documenting. The syntax change is easy to fix in the docs. Even there, we have settled on `@generated`, and only the change is pending.

**Comment by phobon** [comment]
Another vote for reopening this issue and adding documentation as soon as possible. I think there are many people like me out there who want to try out the latest features but are unable to figure them out just from the code changes.

**Comment by ViralBShah** [comment]
Reopening this since we still need to document staged functions in the manual.

**Comment by kmsquire** [comment]
Bump.

**Comment by garrison** [comment]
Looks like there's a work in progress: #10673

**Comment by kmsquire** [comment]
Yup, noticed that--thanks, @tlycken!

**Comment by brk00** [comment]
Closed by #10673
