### ISSUE TITLE
confusing newlines in comprehensions 

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#9494]
I was a little bit confused that Julia is that sensitive to the placement of newlines inside a comprehension. E.g. these 3 variants work (0.4dev):

```
julia> [ true | false for i in 1:3]
3-element Array{Bool,1}:
 true
 true
 true

julia> [ true | false
       for i in 1:3]
3-element Array{Bool,1}:
 true
 true
 true

julia> [ true |
       false
       for i in 1:3]
3-element Array{Bool,1}:
 true
 true
 true
```

But this one fails:

```
julia> [ true
       | false for i in 1:3]
ERROR: syntax: invalid comprehension syntax
```

Coming from C and C++, I'm used to split long expressions such that the new line starts with an operator (like the 4th variant). IMO it makes it more readable.

I've got an idea that there are multiple ongoing discussions regarding `[...]` syntax, but since the 3rd variant was already fixed in #1155, I wonder if the 4th one could be fixed as well, without disrupting the other functionality.

**Comment by garrison** [comment]
Just an update on this status of this issue: on julia 1.0, the fourth example given above by @alyst results in an error message that is different from before:
```
julia> [ true
              | false for i in 1:3]
ERROR: syntax: "|" is not a unary operator
```
This is similar to @stevengj's [suggestion](https://github.com/JuliaLang/julia/issues/9494#issuecomment-68378084), above, but with slightly different language.  I believe that if this is indeed the desired language for this error then this issue can be closed.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/9494#issuecomment-412364130
