### ISSUE TITLE
UDP behavior on partial packets

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#9496]
See https://github.com/JuliaLang/julia/pull/5697#issuecomment-55555817

There is a TODO in the code about this in socket.jl. Currently we throw an error, and the suggestion is to just drop the packet instead. It seems to me that could be reasonable.

**Comment by ihnorton** [comment]
Sounds good, although another option would be to still throw the error but add a `raise` option (default `false`) to `recv`/`recvfrom` functions (incurring some task-switching overhead, especially on Windows?)

**Comment by ihnorton** [comment]
So with a bit more thinking cap this time: I think we can close this outright (and remove the TODO). The libuv docs say that the flag checked in the TODO section means:

```
    * Indicates message was truncated because read buffer was too small. The
    * remainder was discarded by the OS. Used in uv_udp_recv_cb.
    */
    UV_UDP_PARTIAL = 2,
```

That seems like something one would, in fact, want to know about! This is not about erroring out on network-dropped packets, which are expected with UDP and (AFAICT) not exposed by libuv.

**Comment by ihnorton** [comment]
And just now, belatedly reading the thread linked above, I see that [Stefan agrees](https://github.com/JuliaLang/julia/pull/5697#discussion_r9532104).

**Comment by ihnorton** [comment]
Decided.
