### ISSUE TITLE
parse() waits for eval() to raise an error

### ISSUE THREAD

**Issue by dbrunton** [JuliaLang/julia#9505]
Docs for Base.parse():

> If "raise" is true (default), syntax errors will raise an error; otherwise, "parse" will return an expression that will raise an error upon evaluation.

This works for some cases:
`julia> parse("end")`
`ERROR: ParseError("unexpected end")`

But not for others:
`julia> parse("f(")`
`:($(Expr(:incomplete, "incomplete: premature end of input")))`

I'm running on:
`Julia Version 0.4.0-dev+2317`
`Commit e478a6e (2014-12-30 15:13 UTC)`

**Comment by tkelman** [comment]
backported in f63dbc57af8940c0f9ae206974b6e3ff0e5075e7
