### ISSUE TITLE
Why don't array comprehensions desugar into map?

### ISSUE THREAD

**Issue by samuela** [JuliaLang/julia#9515]
I discovered this fact while working with something like the following:

```julia
julia> da = distribute(1:10)
10-element DArray{Int64,1,UnitRange{Int64}}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

julia> [println((myid(), x)) for x in da];
(1,1)
(1,2)
(1,3)
(1,4)
(1,5)
(1,6)
(1,7)
(1,8)
(1,9)
(1,10)

julia> map((x) -> println((myid(), x)), da);
	From worker 2:	(2,1)
	From worker 3:	(3,6)
	From worker 2:	(2,2)
	From worker 2:	(2,3)
	From worker 2:	(2,4)
	From worker 2:	(2,5)
	From worker 3:	(3,7)
	From worker 3:	(3,8)
	From worker 3:	(3,9)
	From worker 3:	(3,10)
```

Which raises the obvious question: why don't array comprehensions simply desugar into `map`s? This smells of bad language design that apparently identical language features have subtly different semantics.

**Comment by JeffBezanson** [comment]
There are several issues about redesigning comprehensions, so I'm going to close this one as it's more just a discussion.
