### ISSUE TITLE
BoundsError in invoke

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#9520]
I've got a very weird `BoundError` when trying use invoke. See minimized demonstration below

```julia
julia> f(::Any, ::Any, ::Any, args...) = Any
f (generic function with 1 method)

julia> invoke(f, (Any, Any, Any), 1, 1, 1)
ERROR: BoundsError()
 in typeinf at /usr/lib/julia/sys.so
 in typeinf_ext at /usr/lib/julia/sys.so
```

The error goes away if I remove the `args...` or one of the arguments so I guess I'm using `invoke` in the right way.

```julia
julia> f2(::Any, ::Any, args...) = Any
f2 (generic function with 1 method)

julia> invoke(f2, (Any, Any), 1, 1)
Any

julia> f3(::Any, ::Any, ::Any) = Any
f3 (generic function with 1 method)

julia> invoke(f3, (Any, Any, Any), 1, 1, 1)
Any
```

P.S. It might be helpful to keep linenumber info of the original source file in `sys.so`. This would be especially useful when pre-compiling packages support is added.

**Comment by tkelman** [comment]
should the fix here be scheduled for backporting?

**Comment by vtjnash** [comment]
Yes

**Comment by tkelman** [comment]
I think this one would be more appropriate for 0.3.6.

**Comment by tkelman** [comment]
any change in backporting opinion now that these tests have been causing issues?

**Comment by vtjnash** [comment]
I guess it probably fine to wait until someone fixes the rest of the bug
