### ISSUE TITLE
readcsv will ignore the text after `#`

### ISSUE THREAD

**Issue by qinwf** [JuliaLang/julia#9529]
The example file:
```csv
包名,模块名,引入,名,简体,类型
Base,Base,否,-,#,符号
Base,Base,否,!,#,符号
Base,#,否,!=,#,符号
Base,Base,否,!==,#,符号
Base,Base,否,$,#,符号
Base,Base,否,%,#,符号
#,Base,否,&,#,符号
Base,Base,否,*,,符号
Base,Base,否,.-,#,符号
```

The result in Julia 0.4

```
julia> readcsv("Base.csv")
9x6 Array{Any,2}:
 "包名"    "模块名"   "引入"  "名"    "简体"  "类型"
 "Base"  "Base"  "否"   "-"    ""    ""
 "Base"  "Base"  "否"   "!"    ""    ""
 "Base"  ""      ""    ""     ""    ""
 "Base"  "Base"  "否"   "!=="  ""    ""
 "Base"  "Base"  "否"   "\$"   ""    ""
 "Base"  "Base"  "否"   "%"    ""    ""
 "Base"  "Base"  "否"   "*"    ""    "符号"
 "Base"  "Base"  "否"   ".-"   ""    ""
```

```
Julia Version 0.4.0-dev+2304
Commit 8cea71e (2014-12-29 02:07 UTC)
Platform Info:
  System: Windows (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
And There are some problems on my Windows box when I copy the texts from console. Some texts will be duplicated, Here is the origin paste result:

```
julia> readcsv("Base.csv")
9x6 Array{Any,2}:
 "包包名名"    "模模块块名名"   "引引入入"  "名名"    "简简体体"  "类类型型"
 "Base"  "Base"  "否否"   "-"    ""    ""
 "Base"  "Base"  "否否"   "!"    ""    ""
 "Base"  ""      ""    ""     ""    ""
 "Base"  "Base"  "否否"   "!=="  ""    ""
 "Base"  "Base"  "否否"   "\$"   ""    ""
 "Base"  "Base"  "否否"   "%"    ""    ""
 "Base"  "Base"  "否否"   "*"    ""    "符符号号"
 "Base"  "Base"  "否否"   ".-"   ""    ""
```

I also try this on JuliaBox

```
Out[1]:
9x6 Array{Any,2}:
 "\u5305\u540d"  "\u6a21\u5757\u540d"  …  "\u7b80\u4f53"  "\u7c7b\u578b"
 "Base"          "Base"                   ""              ""            
 "Base"          "Base"                   ""              ""            
 "Base"          ""                       ""              ""            
 "Base"          "Base"                   ""              ""            
 "Base"          "Base"                …  ""              ""            
 "Base"          "Base"                   ""              ""            
 "Base"          "Base"                   ""              "\u7b26\u53f7"
 "Base"          "Base"                   ""              ""            
```

```
Julia Version 0.3.3
Commit 21d5433* (2014-10-21 20:18 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libblas.so.3
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

I read the source code of `readcsv`, it might be some problem with `readdlm`.

**Comment by elextr** [comment]
See `comments=true` and `commentschar=#` options [here](http://docs.julialang.org/en/latest/stdlib/base/?highlight=readcsv#Base.readdlm)

**Comment by qinwf** [comment]
Thanks! Sorry for the noise. I did not notice this option.

I think that the defualt argument `comments` for `readcsv` should be `false`, because people rarely include comments begin with `#` in CSV files.

**Comment by nalimilan** [comment]
FWIW R uses `#` as a comment character by default, while Pandas has it disabled by default.

**Comment by elextr** [comment]
And neither RFC4180 nor the Python csv module allow comments at all.

**Comment by johnmyleswhite** [comment]
I don't think there's any good resolution to this problem. Comments are clearly an absurd thing to put in CSV files, but people do include them. Most of the work in a "good" CSV parser is coping with all the nonsense that Excel tolerated over the years. The question is therefore: do you make it easier to parse stupid CSV files without having to rewrite them or do you make it easier to parse truly correct files without having to change any default parser settings?

**Comment by nalimilan** [comment]
@qinwf What were the `#` characters in your file for? Missing values? Is that a common use in your experience?

There's indeed no perfect choice, we just need to find the most reasonable trade-off. But it doesn't look like Excel allows comments in CSV files: http://stackoverflow.com/questions/1961006/can-a-csv-file-have-a-comment

**Comment by qinwf** [comment]
@nalimilan I just tried to used `#` as a symbol for a value that I will change it later in this file.

I check R help page:

```
read.csv(file, header = TRUE, sep = ",", quote = "\"",
         dec = ".", fill = TRUE, comment.char = "", ...)

read.csv2(file, header = TRUE, sep = ";", quote = "\"",
          dec = ",", fill = TRUE, comment.char = "", ...)
```

**Comment by nalimilan** [comment]
@qinwf Woops, I looked at `?read.csv`, but actually stopped at the docs for `read.table`. So if even R does not support comments by default, better disable it in Julia. Would you make a pull request to change it, if others agree?
