### ISSUE TITLE
Julia meets Felix

### ISSUE THREAD

**Issue by mardukbp** [JuliaLang/julia#9543]
Recently I came across the [Felix langauge](https://github.com/felix-lang/felix), which claims to be "The fastest scripting language on Earth". Not only that, it also claims to be faster than C in some benchmarks. As I see it, Felix and Julia are both trying to bring high performance to the masses without the need to be an expert in C or C++. It would be interesting to compare the performance of both languages and even better, maybe learn some tricks to improve Julia's performance.

**Comment by jiahao** [comment]
The main challenge here is that someone needs to learn enough Felix to reimplement the microbenchmarks. We'd happily take a pull request with the code if someone like you is willing to write thm.

**Comment by mardukbp** [comment]
I guess that right now only the Felix devs have the necessary knowledge.
Hopefully other Julia users will be curious about Felix...

**Comment by vtjnash** [comment]
Julia's perf suite compares against several popular languages and C. The relative benchmark to C can be used to compare against other languages. Additionally, there are already sites that do a much better job at comparing performance across a large number of languages (e.g. http://benchmarksgame.alioth.debian.org/)

closing as "not a feature request / not actionable"
