### ISSUE TITLE
Starting Julia-0.3.4.app on Mac opens an extra terminal window

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#9546]
When I double-click Julia-0.3.4.app on my desktop (downloaded from julialang.org), it opens an extra Terminal window. I don't think this was the case in 0.3.3.

**Comment by tkelman** [comment]
was this https://github.com/JuliaLang/julia/issues/8777 ?

**Comment by ViralBShah** [comment]
I don't think so, but it could be a side-effect of that fix.

**Comment by ViralBShah** [comment]
Note that this happens only if Terminal is not running. If it is, then the right things happen. Since I almost always have Terminal running, it is likely I did not notice this before.

**Comment by ViralBShah** [comment]
This is what the launcher is like right now. I think we can remove the whole `if` statement after `activate` and it should do the right thing. 

````
osascript 2>&1>/dev/null <<EOF
  tell application "System Events" to set ProcessList to get name of every process
  tell application "Terminal"
    activate
    if (ProcessList contains "Terminal") or ((count of every window) is less than 1) then
      tell application "System Events" to tell process "Terminal" to keystroke "n" using command down
    end if
    do script ("exec '${ROOT}/julia/bin/julia'")
  end tell
EOF
````

**Comment by ViralBShah** [comment]
Removing the `if` statement and even the first `tell` line (which is not required, I think), does not help.

**Comment by ViralBShah** [comment]
Cc: @staticfloat

**Comment by chrisvoncsefalvay** [comment]
If I understand correctly, what's happening here is:
- Terminal launches, launches new window as a default
- Terminal is invoked, launches another new window in which the whole thing is executed

Would this help:

```
tell application "Terminal"
    activate
    delay 0.5
    tell front window
        do script ("exec '${ROOT}/julia/bin/julia'")
    end tell
end tell
```

**Comment by staticfloat** [comment]
Replacing `Julia-0.3.4.app/Contents/Resources/script` with this:

```
ROOT="${0%/script}"

osascript 2>&1>/dev/null <<EOF
	tell application "Terminal"
	    activate
	    set currentTab to do script --
	    delay 1
	    do script ("exec '${ROOT}/julia/bin/julia'") in currentTab
	end tell
EOF
```

Works great for me.  The `delay 1` works well to avoid fighting with things users may have in their `~/.bashrc`, such as auto-starting `tmux`, etc... where the `julia` command gets typed while `tmux` is starting up and thus is ignored.

You can test this by downloading `Julia-0.3.4.app`, replacing the `script` executable with these contents, and then disabling signature checking via `sudo spctl --master-disable`.  Otherwise, it will tell you that the .app is damaged, and won't open it.  You can re-enable it afterward with `sudo spctl --master-enable`.

If this works for you guys, we just need to alter [this file](https://github.com/JuliaLang/julia/blob/master/contrib/mac/app/script) accordingly.

**Comment by ViralBShah** [comment]
I still get two windows with this. I am certainly running this script since I see the 1 second delay before julia launches.

**Comment by staticfloat** [comment]
Aiyaaa, I screwed it up.  How about this:
```
osascript 2>&1>/dev/null <<EOF
    tell application "Terminal"
        activate
        set numWindows to number of windows
        if numWindows is 0 then
            do script --
        end if
    end tell
    delay 1
    tell application "System Events"
        tell process "Terminal"
            keystroke "exec '$ROOT/julia/bin/julia'"
            keystroke return
        end tell
    end tell
EOF
```

**Comment by ViralBShah** [comment]
We have had trouble with reusing an open terminal window in the past. The only case where we want that to happen is when Terminal is not running, and was launched and opened a new window. Would that be possible?

**Comment by staticfloat** [comment]
After much finagling, try this one out:
```
osascript 2>&1>/dev/null <<EOF
tell application "System Events"
    if (count (processes whose bundle identifier is "com.apple.Terminal")) is 0 then
        tell application "Terminal"
            activate
            delay 0.5
            do script "exec '$ROOT/julia/bin/julia'" in window 0
        end tell
    else
        tell application "Terminal"
            if (exists window 0)
                do script --
            end if
            reopen
            activate
        end tell
        
        delay 0.5
        keystroke "exec '$ROOT/julia/bin/julia'"
        keystroke return
    end if
end tell
EOF
```

**Comment by ViralBShah** [comment]
This works well! I don't like the 0.5 second delay, but I guess it will save us bother.

**Comment by staticfloat** [comment]
It's the best solution I've been able to find for interacting with the terminal reliably.  This solution I have here is actually more verbose than another I came up with, but that other solution required you to set Julia.app as an assistive device in the security settings, which is unacceptable.  I think this is about as far as I'm willing to go before we should just bundle iTerm2 or something, and just launch our own terminal application inside of Julia.

**Comment by ViralBShah** [comment]
Iterm2 will certainly allow for more possibilities.

**Comment by ihnorton** [comment]
Fixed by #14365.

**Comment by ihnorton** [comment]
There's still the semi-related annoyance that launching the .app target from a non-Terminal (iterm2) command line opens a new Terminal window. Naively this could be fixed by making the app script just run `Resources/bin/julia` directly (which launches a terminal if not in one already). But I assume there was a good reason for using AppleScript...

**Comment by ViralBShah** [comment]
No good reason. I had just seen that in other projects.
