### ISSUE TITLE
Function must be explicitly imported to be extended

### ISSUE THREAD

**Issue by dpo** [JuliaLang/julia#9547]
A discussion over at [Docile.jl](https://github.com/MichaelHatherly/Docile.jl/issues/51) exposed the following behavior with Julia 0.3 and certain builds of Julia 0.4:
````
julia> methods(factorize)  # Output omitted
julia> factorize(a, b, c, d, e) = ()
ERROR: error in method definition: function LinAlg.factorize must be explicitly imported to be extended
````
while other builds of Julia 0.4 give:
````
julia> methods(factorize)  # Output omitted
julia> factorize(a, b, c, d, e) = ()
factorize (generic function with 8 methods)
````
It seems like one should be able to define a function with the same name as a function in `Base`, but which isn't mean to extend it. Or is this behavior intentional somehow?

**Comment by ihnorton** [comment]
I'm pretty sure this is intentional at this point. See also #2327 #8283.

**Comment by JeffBezanson** [comment]
The error seems to have gone away. I have no idea how that happened.

**Comment by dpo** [comment]
Are you expecting an error to be raised or not?

**Comment by JeffBezanson** [comment]
There should be an error.

**Comment by JeffBezanson** [comment]
My commit a3d637fbdfd820f6982cb1b5181626eb39f6188b is at fault.

**Comment by JeffBezanson** [comment]
Also, to clarify, you *can* define a new function with the same name as one in Base, but not when that name from Base has already been used to refer to the Base function.

**Comment by dpo** [comment]
That makes a lot of sense. And calling `methods()` would qualify as referring to the `Base` function I suppose?!

**Comment by JeffBezanson** [comment]
It's not the call to `methods` but the use of the `factorize` identifier.

**Comment by MichaelHatherly** [comment]
Thanks for the clarification Jeff.
