### ISSUE TITLE
problem with matchall and overlaps

### ISSUE THREAD

**Issue by my-little-repository** [JuliaLang/julia#9549]
I am using julia version 0.3.4-pre+2 (2014-11-24 17:47 UTC) Commit 9f76ed3 (28 days old release-0.3) x86_64-linux-gnu. I get the following behavior for matchall.

   matchall(r"11", "0001111", true)
       6-element Array{SubString{UTF8String},1}:
       "11"
       "11"
       "11" 
       "11"
       "11"
       "11"

The correct answer should be a length 3 array. This is the same bug as #8677 but the fix has probably not been backported to 0.3.

**Comment by ihnorton** [comment]
@juliabackports

**Comment by tkelman** [comment]
for @juliabackports, this was resolved in fcfcae6761ced3b4547806e58b0c6d8555a7e293
