### ISSUE TITLE
make and test failure

### ISSUE THREAD

**Issue by svaksha** [JuliaLang/julia#9555]
References: #7676, #7640 and https://github.com/JuliaLang/julia/issues/9493#issuecomment-68518842

On 32-bit Ubuntu-14.04, with commit 38ef6463f65f51396f9841a531642a6a9b7648bc, `make` and `make testall` failed (after deleting `rm usr/lib/julia/sys.so`, #9493) with this error : https://gist.github.com/svaksha/d8d741dd4394c66c00b7

**Comment by JeffBezanson** [comment]
This looks like a build inconsistency, as it is testing for fields that don't exist. It looks like the system image didn't get rebuilt, which is necessary to pick up all the changes as of that commit.

**Comment by svaksha** [comment]
Perhaps that explains why the nightlies were not working -  invoking `julia` (from anywhere on the repl) and `./julia` (git master) both showed the same version: 

```
Version 0.4.0-dev+2396 (2015-01-02 07:26 UTC) 
master/3f3998e (fork: 140 commits, 8 days)
```

**Comment by jiahao** [comment]
I also encountered this error and it went away after a `make clean`.

**Comment by svaksha** [comment]
@jiahao, ran `make` and cleanall, but the linker error (usr/lib/libjulia.so) persists and testall still has minor failures: https://gist.github.com/svaksha/d8d741dd4394c66c00b7#comment-1365578

**Comment by JeffBezanson** [comment]
I'm not sure the warning about `sigreturn` is significant. Since the tests pass now I'm going to close this, but feel free to reopen if there are further problems.

**Comment by tkelman** [comment]
Note that non-collaborators cannot actually reopen an issue, but leave a comment if you're still having trouble and someone else will do so.
