### ISSUE TITLE
open(filename, "w") throws misleading error message in case of denied permission

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [JuliaLang/julia#9560]
In Python:

``` python
with open(filename, "w+") as file:
    file.write(foo)
```

creates a file if it does not exist. In Julia, where `filename` again refers to a file that doesn't exist, 

``` julia
output_file = open(filename, "w")
```

raises

``` julia
ERROR: opening file output.txt: No such file or directory
 in systemerror at /Applications/Julia-0.4.0-dev-d066c3f061.app/Contents/Resources/julia/lib/julia/sys.dylib
 in open at /Applications/Julia-0.4.0-dev-d066c3f061.app/Contents/Resources/julia/lib/julia/sys.dylib (repeats 2 times)
```

Which is perfectly justified, but IMHO the Pythonic behaviour is more useful. Is there a community interest in having a version similar to the Pythonic one coded or are we on the whole happy and am I the only one displeased with this?

**Comment by JeffBezanson** [comment]
That's interesting; for me on linux passing "w" does create a file if it doesn't exist.

**Comment by garborg** [comment]
It always has for me on OSX, too.

**Comment by garborg** [comment]
It does for me on the commit your binary seems be built from, too:
```julia
#git checkout d066c3f && make
#julia-dev               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2302 (2014-12-28 22:21 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit d066c3f (4 days old master)
|__/                   |  x86_64-apple-darwin14.0.0

julia> cd(mktempdir()); readdir()
0-element Array{Union(UTF8String,ASCIIString),1}

julia> open("new", "w")
IOStream(<file new>)

julia> readdir()
1-element Array{Union(UTF8String,ASCIIString),1}:
 "new"
```

**Comment by chrisvoncsefalvay** [comment]
That... is perplexing. This is indeed the binary @garborg is showing. I have rebuilt the binary and it now works. I presume this was an issue with me - sorry to have wasted your time. Feel free to close it after me :)

**Comment by StefanKarpinski** [comment]
No problem, @chrisvoncsefalvay – I'd much rather have bug reports that turn out to be false alarms than problems that we're not aware of :-)

**Comment by ihnorton** [comment]
Permissions issue?

**Comment by nalimilan** [comment]
If that's a permission issue, then the error message is at best misleading.

**Comment by j-d-b** [comment]
Same confusing error message for me, and it was a permissions issue.

**Comment by vtjnash** [comment]
We just forward the system error message. I am unable to replicate this for a permission issue either. I suspect what happened is the cwd folder was deleted, so that all relative path operations now fail (until the user calls `cd` to a new existing directory). Not sure there is anything to be done about that in julia.
```
julia> open("/root/filename", "w")
ERROR: SystemError: opening file "/root/filename": Permission denied
```
