### ISSUE TITLE
conditional break in nested loop causes fatal crash

### ISSUE THREAD

**Issue by mmuurr** [JuliaLang/julia#9563]
While reading the manual and exploring the language, I discovered this strange error:

```julia
for i = 1:2
  for j = 1:2
    if i == 1 && j == 2
      break
    end
    println(i, j)
  end
end
```

On version 0.3.3 (Mac OS 10.9.5) this leads to a full julia crash with the following error:

```
Assertion failed: (Headers.size() >= 2 && "Should be irreducible"), function findIrreducibleHeaders, file BlockFrequencyInfoImpl.cpp, line 605.

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)

Abort trap: 6
```

Replacing `break` with, e.g. `println("foo")` works just fine.

I'm _very_ new to julia, so perhaps I'm doing something wrong here, but a full system crash seems strange.

**Comment by StefanKarpinski** [comment]
That's very odd. Any code that causes Julia itself to crash is a bug, so this certainly is. Thanks for reporting it.

**Comment by tknopp** [comment]
Cannot reproduce at Mac OS 10.10 and version 0.3.4

**Comment by mmuurr** [comment]
Hm, I also can't reproduce it using version 0.3.3 on juliabox.org, so it might be an unfortunate combination of julia version and OS version (though it's the only issue I've encountered so far).
I failed to include in the report that julia was installed on my system via MacPorts (which, as of this morning, still sees 0.3.3 as the latest version).

**Comment by JeffBezanson** [comment]
As a wild guess, this could be related to the version of LLVM being used as a result of installing via MacPorts. The file `BlockFrequencyInfoImpl.cpp` mentioned in the assertion does not seem to exist in LLVM 3.3, which is what Julia 0.3.x should use.

**Comment by StefanKarpinski** [comment]
That seems pretty plausible.

**Comment by tkelman** [comment]
What does `versioninfo()` say in the Julia install that has the assertion failure?

**Comment by mmuurr** [comment]
`versioninfo()` result:
```julia
Julia Version 0.3.3
Commit b24213b* (2014-11-23 20:19 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment]
Thanks @mmuurr, though now that I look at https://github.com/JuliaLang/julia/blob/master/base/Makefile I realize that unless Macports is specifically setting `LLVM_VER`, the `libLLVM-3.3` there is inaccurate. This might actually be a problem for distributions or anyone else who enables `USE_SYSTEM_LLVM`...

I think this would require tracking down wherever Macports has its build instructions for Julia and seeing whether they're following best practices. Most of the OSX package management for Julia use has been favoring Homebrew as an officially-maintained source - the tap for Julia dependencies and Julia itself is run by the same person (`@staticfloat`) who builds the OSX .app binaries.

**Comment by tkelman** [comment]
Yep they're using LLVM 3.5, see https://trac.macports.org/browser/trunk/dports/lang/julia/Portfile

A) You might want to open a bug with them (or comment on https://trac.macports.org/ticket/45187) and say they should be using LLVM 3.3 since that's what's officially supported right now.

B) Though not completely supported, this probably shouldn't be happening with LLVM 3.5. Can anyone reproduce with 3.5?

**Comment by ihnorton** [comment]
> B) Though not completely supported, this probably shouldn't be happening with LLVM 3.5. Can anyone reproduce with 3.5?

I cannot reproduce on LLVM master, but I find it hard to believe that anything would compile if LLVM_VER doesn't actually match the provided library version.

**Comment by tkelman** [comment]
see #9566 - codegen.cpp gets everything it needs from llvm-version.h, it's just our makefile and base/build_h.jl that might get wrong information

**Comment by ihnorton** [comment]
Ah, ok. But pretty sure there is still some other stuff outside codegen that is conditional (backtrace related).

**Comment by Keno** [comment]
I remember this bug being reported before with LLVM 3.5. Let me see if I can find it.

**Comment by Keno** [comment]
See https://github.com/JuliaLang/julia/issues/8296.
