### ISSUE TITLE
Markdown fails to parse Autolinks

### ISSUE THREAD

**Issue by mpastell** [JuliaLang/julia#9564]
It seems that Markdown.parse in 0.4 doesn't parse autolinks (http://spec.commonmark.org/0.14/#autolink).

``` julia
julia> Markdown.parse("<http://github.com>")
  <http://github.com>
```

As a related question, should I report Markdown bugs here or to `Markdown.jl`? This is the third Markdown bug I come across today and reported the two others to `Markdown.jl`, but they also exist in `base.Markdown`.

**Comment by hayd** [comment]
This is the correct place for Markdown bugs.

This is a pretty easy enhancement, we can simply parse this to the same object as if we'd seen `[http://github.com](http://github.com)`. I have a patch to add this and auto emails too.
