### ISSUE TITLE
Warnings in tests

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#9571]
I see these errors and warnings when doing `make test-reflection`. The error sounds scary, but the tests do not fail.
````
The following 'Returned code...' warnings indicate normal behavior:
Warning: Returned code may not match what actually runs.
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
Warning: Returned code may not match what actually runs.
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
error: failed to compute relocation: X86_64_RELOC_UNSIGNED
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
````

**Comment by tkelman** [comment]
see #9521, cc @timholy on that one

on the same issue title, we also have: https://github.com/JuliaLang/julia/pull/9518#issuecomment-68585454 when you do `make testall1`

and some Windows-only `bash.exe: warning: could not find /tmp, please create!` that I should probably try to figure out how to suppress somehow on appveyor

**Comment by vtjnash** [comment]
are you using LLVM3.5+ on a Mac? if so, those warnings are due to an upstream issue that Keno knows how to fix with reading MachO debug info reloc tables. the net result for now is that the line numbers are missing in backtraces.

**Comment by ViralBShah** [comment]
Yes, I am using LLVM 3.5. I had forgotten that I had a Make.user that used the newer LLVM.

**Comment by ViralBShah** [comment]
Please close this if there is already an issue about this.

**Comment by tkelman** [comment]
#7910, right? just the extra-long warnings because of it are new
