### ISSUE TITLE
Occasional "ERROR: test failed: isready(rr1)" on AppVeyor and OSX Travis

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#9572]
See
https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.1069/job/r89nh7863xwt4axv
https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.1033/job/w29umga18ob007s3
https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.993/job/0qiadv446dghm09v

for examples. Seems to only happen on Win64, where I'm running tests in serial on AppVeyor due to #7942. This might be a manifestation of the same problem?

Possibly related but maybe something else, on 32 bit:
https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.925/job/yivgyj95e80d85l9

```
    From worker 2:       * parallel
exception on 2: ERROR: test failed: (3 <= 1)
 in expression: maximum(workloads) - minimum(workloads) <= 1
 in error at error.jl:21
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in runtests at C:\projects\julia\test\testdefs.jl:5
 in run_work_thunk at multi.jl:603
 in run_work_thunk at multi.jl:602
 in anonymous at task.jl:852
while loading parallel.jl, in expression starting on line 131
```

**Comment by vtjnash** [comment]
not really. that might be a compilation delay if you're blocking sys.dll from loading (such as by using julia-debug.exe). we could do a dummy run to try to cut down on that delay. or just insert a `wait(async1)`

**Comment by tkelman** [comment]
Apparently this can happen on OSX too? https://travis-ci.org/JuliaLang/julia/jobs/47393656

**Comment by tkelman** [comment]
another OSX example https://travis-ci.org/JuliaLang/julia/jobs/47532713 (hopefully no one restarts that one)

**Comment by tkelman** [comment]
I'm going to close this since I think appveyor has actually been fairly well-behaved (except for the occasional freeze and timeout, which there's a different issue for) and we've got much bigger problems on Travis. We can reopen if this specific problem starts coming back frequently.

**Comment by tkelman** [comment]
from the osx buildbot: http://buildbot.e.ip.saba.us:8010/builders/build_osx10.9/builds/1503/steps/shell_2/logs/stdio

**Comment by tkelman** [comment]
Just saw this again locally. Totally intermittent, as so many of these are.

**Comment by tkelman** [comment]
This is happening really often on the os x buildbot: http://build.julialang.org:8010/builders/build_osx10.9-x64?numbuilds=250

No one sees this locally?

**Comment by KristofferC** [comment]
Seen this recently?
