### ISSUE TITLE
I feel naming inconsistency with `beginswith`.

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/julia#9578]
We have the [`beginswith`](http://julia.readthedocs.org/en/latest/stdlib/strings/#Base.beginswith) function to check whether a string *begins* with a given prefix.
This is good, I often use it. But its name looks inconsistent compared to other function names in Julia.

To list some, other functions use "start" in their name:
* [`seekstart`](http://julia.readthedocs.org/en/latest/stdlib/io-network/?highlight=start#Base.seekstart)
* [`start`](http://julia.readthedocs.org/en/latest/stdlib/collections/?highlight=start#Base.start)
* [`start_timer`](http://julia.readthedocs.org/en/latest/stdlib/base/?highlight=start#Base.start_timer)

and no other functions use the word "begin" except `beginswith`.
So I believe it would be better to rename `beginswith` to `startswith` for consistency.
I want to know how you feel about this (maybe too trivial to think).

As a reference, Python has the [`str.startswith`](https://docs.python.org/2/library/stdtypes.html#str.startswith) method, which works in the same way as `beginswith` does.

**Comment by kmsquire** [comment]
I have to say that this has bugged me slightly for about two years, but never enough to try to come up with a justification. So, +1!

**Comment by mpastell** [comment]
+1 for renaming

**Comment by bicycle1885** [comment]
I'm almost ready to create a pull request.

**Comment by bicycle1885** [comment]
This is it: https://github.com/JuliaLang/julia/pull/9583 (didn't GitHub automatically create a cross-link to a referring pull request?)

**Comment by ivarne** [comment]
Apparently not when you referenced the issue number in the headline, not the body of the pull request.

**Comment by JeffBezanson** [comment]
:bike: :house:

**Comment by kmsquire** [comment]
Is there any way to turn that into a tag? ;-)

**Comment by jiahao** [comment]
That tag would probably get used on half the issues...

**Comment by bicycle1885** [comment]
:expressionless:
