### ISSUE TITLE
a `which` that returns the method `invoke` would call

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#9589]
Currently calling `which` with abstract types does not return very predictable result (or at least not very useful)

```julia
julia> function f(::Any, ::Any)
       Any
       end
f (generic function with 1 method)

julia> function f(::Integer, ::Integer)
       Integer
       end
f (generic function with 2 methods)

julia> function f(::FloatingPoint, ::FloatingPoint)
       FloatingPoint
       end
f (generic function with 3 methods)

julia> which(f, (Any, Any))
f(::Integer,::Integer) at none:2
```

However, there's the builtin `invoke` which support looking up method based on the types (possibly abstract) passed in and can call the expected function
```julia
julia> invoke(f, (Any, Any), 1, 1)
Any
```

Shouldn't it be better to make `which(f, T)` always return the method that is going to be called with `invoke(f, T)`? I noticed that `which` is in `interactiveutil.jl` but it is actually also useful for tracing/translating julia program or for DSL etc...

I guess this change is technically breaking since it will change the output of an existing function but it shouldn't be a big breakage given that the output of `which` with abstract types is also currently "broken".

**Comment by JeffBezanson** [comment]
I would say `which` is redundant with `methods`. `methods` returns an array of all methods matching the given types. If there is only one element, you know exactly what will be called. So I would say `which` should just be removed.

**Comment by yuyichao** [comment]
I still think it is useful to have a function that does almost the same with `invoke` but just return the method to be called without calling it.
