### ISSUE TITLE
Deferred expression interpolation (symbol gets quoted) when no lvalue is supplied

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#9600]
```julia
julia> a = 1
1

julia> :($a+b)
:($(Expr(:$, :a)) + b)

julia> ex = :($a+b)
:(1 + b)

julia> :($a+b)
:($(Expr(:$, :a)) + b)

julia> c = ans
:($(Expr(:$, :a)) + b)

julia> Meta.show_sexpr(c)
(:call, :+, (:$, :a), :b)
julia> Meta.show_sexpr(ex)
(:call, :+, 1, :b)
```
![image](https://cloud.githubusercontent.com/assets/1525481/5605398/2620fc52-93be-11e4-9ec8-40694e5ad052.png)

**Comment by ihnorton** [comment]
Ghost of #6763.

**Comment by JeffBezanson** [comment]
This is as good an excuse as any to explicitly separate `quote` and `quasiquote`. The existing forms of quote, which interpolate with `$` inside, are actually `quasiquote`. Internally there is a short-lived expression kind called `inert` that does not interpolate. I think we should keep `quote` as-is, and just expose `inert`. Syntax for it can come later.

**Comment by timholy** [comment]
Interesting, thanks for explaining.

**Comment by bfredl** [comment]
I always thought that `Meta.quot` was the function that returned the expression that evaluated to its argument exactly, i e `eval(:(b = $(Meta.quot(`_value_`)))` would have the effect of `b = `_value_ for any _value_. But now I see that `eval(Meta.quot(Expr(:$, :a)))` evaluates to `a` and not `Expr(:$,:a)`. Do I understand it correctly that `inert` is/would be this function ?

**Comment by ihnorton** [comment]
Possibly related, interpolated module names seem to be parsed incorrectly:
```
julia> foo = :W
:W

julia> Expr(:toplevel, quote baremodule $foo end end)
:($(Expr(:toplevel, quote  # none, line 1:
    baremodule $ # line 1:
    foo
    end
end)))
```

**Comment by timholy** [comment]
Thanks, Jeff! Looks like a nice improvement.

**Comment by JeffBezanson** [comment]
It is slightly better to use :inert, but there is no way to prevent
expressions containing $ from being "captured" by an enclosing :quote.
However after the `expand()` pass, literal values can be inserted safely
using QuoteNode.

The module name issue looks separate.

**Comment by StefanKarpinski** [comment]
Can this be backported to 0.3?

**Comment by JeffBezanson** [comment]
Unfortunately only at the cost of changing how some expressions are lowered.

**Comment by StefanKarpinski** [comment]
Ok, I guess that's probably a no. Feel free to remove the backport pending label if it's not practical.
