### ISSUE TITLE
Desugar a[k; bar = baz] to getindex(a, k; bar = baz)

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#9601]
Reading the manual I was under the impression that a[...] is just sugar for getindex(a, ...), similarly for setindex!, but that does not hold true for keyword arguments.

I would love to use keywords to control on the fly compression / decompression, mmapping etc in a custom type.

Example of this behavior:
```jl
type Foo
end
import Base.getindex, Base.setindex!
getindex(a::Foo, k; kargs...) = @show k kargs
setindex!(a::Foo, v, k; kargs...) = @show v k kargs

a = Foo()
getindex(a, 1; bar = 1) # -> works
setindex!(a, 1, 2; bar = 1) # -> works

a[1; bar = true] # -> `getindex` has no method matching getindex(::Foo, ::Int64, ::Bool)
a[1; bar = true] = 2   # -> `setindex!` has no method matching setindex!(::Foo, ::Int64, ::Int64, ::Bool)
```

**Comment by tkelman** [comment]
Related: https://github.com/JuliaLang/julia/issues/7225

This syntax is used in JuMP and possibly elsewhere inside macros, not sure whether giving it an actual meaning would break anything.

**Comment by mlubin** [comment]
Yes please.

**Comment by jakebolewski** [comment]
It breaks array concatenation as you can have arrays like `Int[1,2; 3,4]` which overlap with `foo[1,2;]` because `Int` and `foo` are just symbols at parse time.
