### ISSUE TITLE
shallow/deep copy

### ISSUE THREAD

**Issue by Albert65** [JuliaLang/julia#9606]
Hi All,
Please, let me know what might be wrong in the code below (it fails on Mac OS Yosemite, julia 0.3.4):

x = rand(2,3);
y = x;
z = copy(x);
w = deepcopy(x);
x = rand(2,3);
assert(y == x);    # ‘y’ is a shallow of ‘x’, it changes with ‘x’
assert(z == x);    # ‘z’ is a shallow of ‘x’, it changes with ‘x’
assert(w != x);    # ‘w’ is a deep copy of the former array ‘x’

**Comment by timholy** [comment]
y=x constructs a reference to the same underlying memory that x is a reference 
to; however, when you change the binding of x, it doesn't also change the 
binding of the rest.

--Tim

**Comment by JeffBezanson** [comment]
That's right; `x = rand(2,3)` makes `x` point to a new object, and `y` still points to the old array.

`copy` and `deepcopy` refer to how deeply inside the argument object gets copied; they have no effect on variables that might be assigned to point to the object.

**Comment by Albert65** [comment]
Thanks Tim and Jeff, I see the point. I keep in mind C++ and Matlab models, which are different from Julia. I wish the documentation is amended to stress the difference in coping concepts, with some examples like the one above.

**Comment by timholy** [comment]
@Albert65, it would be great if you'd edit the documentation to clarify the things you find confusing. See https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation
