### ISSUE TITLE
a speed increase for factor()

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/julia#9611]
After removing a prime factor `factor()` does not check if the remaining number to be factored is prime. Sometimes a number factors into small primes and one large one. Making this check allows factoring numbers that are otherwise out of reach for the current algorithm.

```julia
julia> @time factor(int128(2)^101+1)
elapsed time: 9.7113e-5 seconds (4000 bytes allocated)
Dict{Int128,Int64} with 2 entries:
  3                                                           => 1
  845100400152152934331135470251 => 1

julia> @time factor(int128(2)^101-3)
elapsed time: 9.1461e-5 seconds (3824 bytes allocated)
Dict{Int128,Int64} with 2 entries:
  163                                                     => 1
  15553995094824900631861389023 => 1
```

[Here is the change](https://github.com/jlapeyre/julia/blob/factoringspeed/base/primes.jl#L96-L99)
It should not slow the algorithm because it is only performed after having found factors, not when search for new factors.

**Comment by ViralBShah** [comment]
Could you submit a PR against julia master?

**Comment by jlapeyre** [comment]
Sure. I'll comment here when it is done.

**Comment by jlapeyre** [comment]
I could add a test.  This consumes ~1ms.  But, if there is a regression, the effect is that the test runs for a long time or forever.  Is this reasonable ?

**Comment by jlapeyre** [comment]
I'll include the test in the PR and let the merger decide what to do with it.

**Comment by jlapeyre** [comment]
The patch is in the queue and passed the CI tests. I'll close this.

**Comment by StefanKarpinski** [comment]
> I could add a test. This consumes ~1ms. But, if there is a regression, the effect is that the test runs for a long time or forever. Is this reasonable ?

I think that's fine – as long as it gets noticed if it's broken.
