### ISSUE TITLE
A loop unroll macro

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#9616]
I wonder if it will be useful to have a loop unroll macro, which can force explicit unrolling of loops for certain things.

This came up in #8869. @StefanKarpinski implemented unrolling in #8786, which is easy enough to do, but nice to generalize for other cases.

**Comment by jakebolewski** [comment]
Isn't this what `@nexpr` basically is?

**Comment by StephenVavasis** [comment]
I have implemented an unroll macro; see my posting on the julia users newsgroup.  -- Steve Vavasis
