### ISSUE TITLE
DomainError in bigint_pow

### ISSUE THREAD

**Issue by xyproto** [JuliaLang/julia#9618]
`big(3)^big(9)^big(9)^big(9)`

gives

`
ERROR: DomainError
 in bigint_pow at gmp.jl:352
 in ^ at gmp.jl:356
`

This is for Julia 0.3.4 on 64-bit Arch Linux.

**Comment by aviks** [comment]
Not sure if this is a bug.

From the source of `biginit_pow` it looks like the exponent has to be less than the largest unsigned integer (which is 18446744073709551615 on 64 bits). 

`^` is parsed as right associative, which means that the exponent in your expression above becomes larger that that value.
```julia
julia> Base.Meta.show_sexpr( :( big(3)^big(9)^big(9)^big(9)))
(:call, :^, (:call, :big, 3), (:call, :^, (:call, :big, 9), (:call, :^, (:call, :big, 9), (:call, :big, 9))))
```
If you really wanted right associative exponentiation, then I don't know if there is a way.  GMP's exponentiation function is limited to an `uint` exponent: https://gmplib.org/manual/Integer-Exponentiation.html#Integer-Exponentiation

However, if you force the expression to be left associative, then you could do: 

```julia
julia> ((big(3)^9)^9)^9
662818605424187176105172864214479748588986673875686419462793267420461248113287928124072014075084032555900857691049061274135779819474602180821485109388447092848836753879024702508785576075431392037236950553064188689954912598712398079759040464474717726449363185622056684690721420542800623411346656785162817900551337542270334990205437212700131838846883
```

**Comment by xyproto** [comment]
Thank you for the great reply. I'm not sure if this is a bug either. If this is not a bug, I think this issue should be considered a feature request for a slightly more informative error message.

**Comment by jiahao** [comment]
The answer to this computation has `~10^(3e8)` digits...

**Comment by JeffBezanson** [comment]
Yes, this is hitting a hard limit in GMP and, really, in the size of universe.

**Comment by jiahao** [comment]
Technically speaking the current `DomainError` is correct for the reasons above. However, an `OverflowError` may be more in line with what users expect since the result would certainly overflow for `|x|>1` anyway.

**Comment by aviks** [comment]
I'm  uncertain if an OverflowError is any better than a DomainError without any more context. 

We cant catch exceptions by type, so this is really a message to the user.  You are therefore assigning a lot of meaning to the words "DomainError" vs "OverflowError" . Which may be true in some domains (sic) but I'm not sure is universally understood. At least at first glance, I'll personally find these hard to disambiguate these from each other, or from "ArgumentError". 

In my mind, the goal is, when the user gets this error, does he understand what is wrong without reading library code?

**Comment by jiahao** [comment]
In my mind `DomainError` indicates a problem with the domain, i.e. the function is not defined for its inputs, whereas `OverflowError` indicates a problem with the range, specifically that the output is too large to be represented.

This case triggers both. However, the `OverflowError` seems more appropriate to me when just looking at the operation `x^y` purely as the mathematical exponentiation operation. The `DomainError` makes sense only if I know something about the implementation of `x^y` as you have explained above.

See also #8286, where doing very large arithmetic in GMP leads to nasty `SIGABRT`s when it overflows.
