### ISSUE TITLE
fix vsnprintf in src/support/asprintf.c for Windows (julia -h doesn't work)

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#9624]

**Comment by samoconnor** [comment]
In srs/support/asprintf.c the buffer realloc() logic does not work on win32 for long input strings.
This code expects vsnprintf() to return a length larger than the input buffer length if the buffer is too small.
On windows vsnprintf() returns -1 if the buffer is too small.

If #define INIT_SZ in asprintf.c is set larger then ./julia.exe -h works.

On Unix (man vsnprintf)
     "... if the return value is greater than or equal to the n argument, the string was too short and some of the printed characters were discarded."

On win32 http://msdn.microsoft.com/en-us/library/1kt27hek.aspx
    "if the number of characters to write is greater than count, these functions return -1 indicating that output has been truncated."

See: https://github.com/JuliaLang/julia/blob/master/src/support/asprintf.c#L62

**Comment by tkelman** [comment]
Wow, thanks @samoconnor. How much larger did you need to make it to get things to work? I'm building now with 256, will see if that's enough.

(Also useful trick for referencing specific lines of code, hit y and github will replace the url with one that references the specific sha, [like so](https://github.com/JuliaLang/julia/blob/e140b62d3e46fe9848bda767480f199b6a6fd8b1/src/support/asprintf.c#L62))

**Comment by samoconnor** [comment]
I made it 12800, just to see if it worked.
I guess it has to be as long as the help message.

**Comment by tkelman** [comment]
Yeah, that message is longer than I thought it was. 2048 works at the moment, 1024 doesn't, but that message is also likely to get longer over time.

**Comment by samoconnor** [comment]
OK, but while tweaking INIT_SZ serves to demonstrate the bug, it doesn't fix the underlying problem, which is that win32 vsnprintf is not POSIX compliant. It looks like asprintf.c needs an #ifdef WINDOWS with an algorithm that doubles the buffer size until it is big enough (or similar).

**Comment by vtjnash** [comment]
or use `_vsc[w]printf` http://msdn.microsoft.com/en-us/library/w05tbk72%28VS.71%29.aspx ?
