### ISSUE TITLE
Type annotations in global scope

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#964]
Is it expected behaviour that I can't type annotate variable declarations in global scope? Example:

``` julia
julia> foo::Float = 0.1
foo not defined

julia> function bar()
         foo::Float = 0.1
       end

julia> bar()
0.1
```

**Comment by StefanKarpinski** [comment]
I'm not sure why this is considered breaking. Just because we ignore it now? If so, can we at least make this syntax an error on globals so that it is no longer breaking and can be added in 1.1 instead of having to wait until 2.0?

**Comment by mbauman** [comment]
This is no longer breaking after #17445.

**Comment by xgdgsc** [comment]
Sometimes I just copy code from other people' s module to see the output. Can we make this a warning instead of error?

**Comment by StefanKarpinski** [comment]
Or better yet: add proper support for it.

**Comment by oscardssmith** [comment]
If someone is willing to give me some guidance, I'll happily make the PR to fix this.
