### ISSUE TITLE
sparse JLD file from win7/64 do not work in Linux

### ISSUE THREAD

**Issue by paulanalyst** [JuliaLang/julia#9646]
data=load("D_z_win.jld","D")
ERROR: .... on the end of bug
File D_z_win.jld was created at win 7/64 in this same way like this sparse (I,J,V)
On the win machine is julia 3.0

samsung2@samsung2:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.3 (2014-10-21 20:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
|__/                   |  i686-linux-gnu

julia> I=vec(readcsv("I.txt"));

julia> J=vec(readcsv("J.txt"));

julia> V=vec(readcsv("V.txt"));

julia> D=sparse(int(I),int(J),int(V));

julia> using HDF5,JLD

julia> save("D.jld","D",D)

julia> data=load("D.jld","D")
10000000x30000 sparse matrix with 1000000 Int32 entries:
	[170590  ,        1]  =  1
	[275820  ,        1]  =  1
	[3131540 ,        1]  =  1
	[3182060 ,        1]  =  1
	[3286470 ,        1]  =  1
	[3398480 ,        1]  =  1
	[3690470 ,        1]  =  1
	⋮
	[3215620 ,    30000]  =  1
	[3509960 ,    30000]  =  1
	[4311630 ,    30000]  =  1
	[4984860 ,    30000]  =  1
	[5425410 ,    30000]  =  1
	[6618640 ,    30000]  =  1
	[6698030 ,    30000]  =  1
	[7282230 ,    30000]  =  1

julia> data=load("D_z_win.jld","D")
ERROR: stored type Base.SparseMatrix.SparseMatrixCSC{Core.Float64,Core.Int64} does not match currently loaded type
 in jldatatype at /home/samsung2/.julia/v0.3/HDF5/src/jld_types.jl:637
 in read at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:331
 in read at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:316
 in anonymous at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:983
 in jldopen at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:237
 in load at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:982

Paul

**Comment by jiahao** [comment]
This is an issue with HDF5.jl, not Julia.

cc: @timholy
