### ISSUE TITLE
Segfault OS/X nightly

### ISSUE THREAD

**Issue by waTeim** [JuliaLang/julia#9661]
Here's the stack trace.  I'm a little reluctant to pull this and start debugging because my system is working currently (pulled last week so fairly recent).  I'm sending this because it happens on OS/X but not linux and its a segfault.  It may be ephemeral and possibly a difference in versions that were tested on Linux versus OS/X.  Maybe this is an early effect of the making JL_SET_STACK_BASE  unnecessary?  Heads up, anyway.  

    signal (11): Segmentation fault: 11
    jl_is_submodule at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/module.c:460
    _ZL13emit_functionP17_jl_lambda_info_tb at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/codegen.cpp:3737
    _Z19jl_eh_restore_stateP13_jl_handler_t at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/./julia.h:1179
    jl_compile at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/codegen.cpp:684
    jl_trampoline_compile_function at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/builtins.c:861
    jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/./julia.h:995
    jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/gf.c:1630
    jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/jlapi.c:161
    _ZN2nj4Call4evalERNSt3__16vectorINS1_10shared_ptrINS_5ValueEEENS1_9allocatorIS5_EEEEx at /Users/travis/build/waTeim/node-julia/build/Release/nj.node (unknown line)
    _ZN2nj4Expr4evalEv at /Users/travis/build/waTeim/node-julia/build/Release/nj.node (unknown line)
    _ZN5JMain4evalERKNSt3__110shared_ptrIN2nj4ExprEEE at /Users/travis/build/waTeim/node-julia/build/Release/nj.node (unknown line)
    _ZN5JMainclEv at /Users/travis/build/waTeim/node-julia/build/Release/nj.node (unknown line)
    _ZNSt3__114__thread_proxyINS_5tupleIJM5JMainFvvEPS2_EEEEEPvS7_ at /Users/travis/build/waTeim/node-julia/build/Release/nj.node (unknown line)
    _pthread_body at /usr/lib/system/libsystem_pthread.dylib (unknown line)
    _pthread_struct_init at /usr/lib/system/libsystem_pthread.dylib (unknown line)

**Comment by waTeim** [comment]
Update with some version info

Crashing version (osx, from above)

    3.00s$ julia -e 'versioninfo()'
    Julia Version 0.4.0-dev+2541
    Commit e5b4e0b (2015-01-07 04:56 UTC)
    Platform Info:
      System: Darwin (x86_64-apple-darwin13.4.0)
      CPU: Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
      LAPACK: libopenblas
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

By comparison (functional, linux)

    4.25s$ julia -e 'versioninfo()'
    Julia Version 0.4.0-dev+2538
    Commit 38d02bd* (2015-01-06 22:43 UTC)
    Platform Info:
      System: Linux (x86_64-linux-gnu)
      CPU: AMD Opteron(tm) Processor 6376                 
      WORD_SIZE: 64
      BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Piledriver)
      LAPACK: liblapack.so.3
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

**Comment by ViralBShah** [comment]
What code triggers it?

**Comment by jakebolewski** [comment]
I've seen the same error happen randomly on Travis when building the system image as well.

**Comment by waTeim** [comment]
I kind of have my hands around it now, because it's only most-of-the-time repeatable.  I think there might be some garbage collection going on.

**Comment by JeffBezanson** [comment]
We should definitely initialize `parent` to `NULL` in `jl_new_module`. Seems like a pretty bad oversight to me.

**Comment by JeffBezanson** [comment]
Done. Thanks for finding this.

**Comment by waTeim** [comment]
Hey no problem.  Glad to.  What to about about **jl_f_new_module**?

**Comment by ivarne** [comment]
That extra initialization seems relevant for `release-0.3`.

**Comment by jiahao** [comment]
Looks like this issue has been resolved.
