### ISSUE TITLE
make testall fails at * numbers

### ISSUE THREAD

**Issue by Fedster** [JuliaLang/julia#9662]
Hi All, 

on OSX 10.10.1, fortran Homebrew gcc49 4.9.2_1, on the very latest commit:

Version 0.4.0-dev+2543 (2015-01-07 09:08 UTC)
Commit d74d8cc

make testall gives:

From worker 6:	     * numbers
exception on 8: ERROR: test error in expression: try  # line 2042:
    (a,b,c) = (1,2)
catch ex # line 2042:
    ex::BoundsError.a === (1,2) && ex.i == 3
end
type BoundsError has no field a
 in anonymous at test.jl:2042
 in do_test at test.jl:47
 in runtests at /usr/local/julia/test/testdefs.jl:5
 in anonymous at multi.jl:852
 in run_work_thunk at multi.jl:603
 in anonymous at task.jl:852
while loading core.jl, in expression starting on line 2042
ERROR: test error in expression: try  # line 2042:
    (a,b,c) = (1,2)
catch ex # line 2042:
    ex::BoundsError.a === (1,2) && ex.i == 3
end
type BoundsError has no field a
while loading core.jl, in expression starting on line 2042
while loading /usr/local/julia/test/runtests.jl, in expression starting on line 42

make[1]: *** [all] Error 1
make: *** [testall] Error 2

**Comment by timholy** [comment]
See if a `make clean && make` or maybe even a `make cleanall && make` fixes the problem.

**Comment by Fedster** [comment]
make clean && make testall worked.

Best

F


> On 7 Jan 2015, at 14:07, Tim Holy <notifications@github.com> wrote:
> 
> See if a make clean && make or maybe even a make cleanall && make fixes the problem.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


--
Federico Calboli
f.calboli@gmail.com
