### ISSUE TITLE
`call` overloading needs documentation

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#9680]
Merged PR #8712 came without documentation.  Documentation is needed for:

- `call` itself, probably in the std-lib
- how constructors now work and the relation to `convert`.  In particular constructors for abstract types, `new{...}`,etc

**Comment by stevengj** [comment]
I added some docs in 11ab1b3b911481bf0c6c71afafd3870d952d258e ... does this solve the issue?

**Comment by ViralBShah** [comment]
The commit above does address the manual part. It would also be nice to have an entry in the `stdlib` documentation that can be looked up with `help`.

**Comment by stevengj** [comment]
Added to `stdlib` docs by 00bd32213037d630664d909bed51a83a1077d084.

**Comment by mauro3** [comment]
Jeff's initial comment on PR #8712 suggests that there is quite a few nifty things which can be done with the new call-feature, for instance his subarray example.  Should this not be documented as well?

**Comment by mauro3** [comment]
Oops, I didn't manage to scroll down.  So I'll need to update my comment!  Sorry!

**Comment by stevengj** [comment]
@JeffBezanson moved it to constructors.rst already.

**Comment by mauro3** [comment]
I think with closing the related  #12242, this is also resolved.
