### ISSUE TITLE
Profiler does not appear to correctly record function call hierarchy in profile results

### ISSUE THREAD

**Issue by johngrogan** [JuliaLang/julia#9689]
Hi,

I am attempting to profile some code, and I have noticed that sometimes the samples in the results have an incorrect call hierarchy.

There is some example code here https://gist.github.com/johngrogan/19f07c356cd3cf491b1b that shows it occuring (at least on my machine). The example code being profiled has a simple call hierarchy:

 do_block() calls do_iteration() which calls do_maths()

My expectation is that any profiling samples that show the do_maths() function will always be captured under a do_iteration() call, however I am seeing it captured under a do_block() call.

I ran the example from the command line

```
julia profprob.jl
```

This creates the file profile-output.txt with the default print format. An example is here https://gist.github.com/johngrogan/31078c950a9379669a31 . In the example, lines 53, 91, and 92 are do_maths() calls that are indented directly under a do_block() call, rather than a do_iteration() call.

While the example doesn't look like a big deal, it is demonstrating the issue that I'm seeing a lot in the actual code I am profiling. I also see this when using ProfileView - the incorrect hierarchy shows itself as blocks at the wrong 'level' in the diagram stack. 

Anyway, I hope the example is helpful in any investigation.

Thanks,
John

Julia Version 0.3.6-pre+1
Commit ee38819 (2015-01-08 22:40 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by timholy** [comment]
I can confirm this, and I've seen it before. I have no clue where it comes from.

One of the things to keep in mind is that the way you were displaying the profile results, a lot of "intermediate" calls (those involving C functions) get suppressed. So one might have imagined that being the problem. But that turns out not to be it, as the following analysis shows:
```julia
# First, run your demo script
# Collect the profiling results
bt, lidict = Profile.retrieve();
# Gather into unique backtraces and the number of repetitions
ubt, counts = Profile.tree_aggregate(bt);
# Each time "do_maths" appears, what function called it?
for (ind,b) in enumerate(ubt)
    for i = 1:length(b)
        if lidict[b[i]].func == "do_maths"
            println(ind, ": ", lidict[b[i-1]].func)
        end
    end
end
```
While the vast majority have `do_iteration` as the immediate predecessor, you'll definitely see some examples of `do_block`. This proves that it's not an artifact of presentation. This happens even if you run julia with `--inline=no`.

Unfortunately, I'm not sure how to pursue it further. CCing @Keno, @vtjnash in case they have good ideas.

**Comment by johngrogan** [comment]
I downloaded and installed Windows version of julia, namely...

```
julia> versioninfo()
Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

...and had a go at reproducing the results. 

So far, with the Windows build, I have failed to see any case where the function call hierarchy is not as expected.  The profile backtracing seems to works 100% fine with the Windows build, but not with Linux builds (a guestimate would be the backtrace details is accurate 'high 90s' % of the time on stuff I'm looking at). 

Note that, regardless of this Linux issue with the backtrace accuracy, I'm finding the profiling tools still work very well for finding where the hotspots are.

For the record, my Linux distro is kubuntu 14.04, and I get julia through building via make from a github clone.

**Comment by vtjnash** [comment]
> So far, with the Windows build, I have failed to see any case where the function call hierarchy is not as expected

that makes me very happy, as win64 has been the hardest platform to get functional backtraces

**Comment by timholy** [comment]
Agreed, that's awesome. Without trying to be a wet blanket, I'll point out there's a chance it could be a red herring, because Windows also takes 1/10 of the number of backtraces as Linux. So it takes longer runs to collect the same statistics. But @johngrogan, if you have run this many times, then your statistics should be adequate.

Does your Linux run on the same machine (or same hardware) as your Windows? I'm wondering if CPU architecture might also play a role. I doubt it's the explanation in this particular comparison, but while we're chatting I thought it would be worth asking.

**Comment by johngrogan** [comment]
Same machine -  the Linux machine is a VirtualBox VM guest running on a Windows 8 host. I could try a native Linux machine if you think that is useful - won't be same hardware though.

I tried slowing down the Linux profiling via Profile.init(1000000, 0.01), and it made no visible difference - the incorrect backtraces are stll there (I double checked that this did in fact produce 10x less samples...)

**Comment by timholy** [comment]
You've really nailed that it's an OS-specific issue. Thanks!

**Comment by cstjean** [comment]
I'm seeing C calls to openlibm at the top-level. I believe this is the same issue, but I'm on OSX... It's very reproducible on my machine, not a fluke.

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin16.7.0

julia> @noinline sum_of_sin(n) = sum(sin, 1:n)
sum_of_sin (generic function with 1 method)

julia> sum_of_sin(10) # warm it up
1.4111883712180104

julia> @profile sum_of_sin(10000000)
1.955891408541025

julia> Profile.print(maxdepth=4, C=true)
1    .../Programa/julia/julia:?; main
 1 ...ic/Programa/julia/julia:?; true_main
  1 ...usr/lib/julia/sys.dylib:?; jlcall__start_18966
   1 ./client.jl:413; _start()
1027 ...rama/julia/src/task.c:267; start_task
 1027 ...a/julia/src/./julia.h:1424; jl_apply
   1027 ./event.jl:73; (::Base.REPL.##1#2{Base.REPL.REP...
    1027 ./REPL.jl:97; macro expansion
2    ...libopenlibm.2.3.dylib:?; __kernel_rem_pio2
172  ...libopenlibm.2.3.dylib:?; ldexp
7    ...libopenlibm.2.3.dylib:?; rintl
```

**Comment by vtjnash** [comment]
> I'm seeing C calls to openlibm at the top-level

That is probably an issue with the library and/or compiler emitting insufficient unwind info. We specify `-fasynchronous-unwind-tables` on libjulia to avoid this problem locally.

**Comment by vtjnash** [comment]
I wonder if we've just caught the program in an intermediate state here. We see the same noise happening in macOS, despite being completely different unwinders and formats.
```
julia> bt, lidict = Profile.retrieve();

julia> for (i, ip) in enumerate(bt)
         node = lidict[ip][end]
         if node.func === :do_maths
             up = lidict[bt[i + 1]][1]
             if up.func !== :do_iteration
               @show node, up
             end
         end
       end
(node, up) = (do_maths(::Float64, ::Float64) at profprob.jl:12, do_block(::Array{Float64,2}) at profprob.jl:39)
(node, up) = (do_maths(::Float64, ::Float64) at profprob.jl:5, ip:0x7fd5254286ef)
(node, up) = (do_maths(::Float64, ::Float64) at profprob.jl:12, do_block(::Array{Float64,2}) at profprob.jl:41)
(node, up) = (do_maths(::Float64, ::Float64) at profprob.jl:12, do_block(::Array{Float64,2}) at profprob.jl:39)
(node, up) = (do_maths(::Float64, ::Float64) at profprob.jl:5, ip:0x7fd5254286ef)
```

> I'm seeing C calls to openlibm at the top-level

That is probably an issue with the library and/or compiler emitting insufficient unwind info. We specify `-fasynchronous-unwind-tables` on libjulia to avoid this problem locally.

**Comment by vtjnash** [comment]
I ran this today, and did not spot any broken frames. Seems like unwind info and/or libunwind is now functioning more correctly
