### ISSUE TITLE
Shouldn't have to specify julia path in `jl_init`.

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#9691]
As it stands, if a path is not passed to `jl_init`, the default logic in `_julia_init` is used. There, if `jl_compileropts.julia_home` and the `JULIA_HOME` environment variable are not set, it derives the julia path from that of the current executable. When embedding, though, that's likely not the right place.

`jl_init` should use analogous logic, but derive the default path from the executing julia shared library.

**Comment by stevengj** [comment]
See also JuliaLang/IJulia.jl#206 and #7801.

**Comment by tknopp** [comment]
@twadleigh I also run into similar problems when using the embedding stuff under windows and had the idea that #5045 could make this more robust.

**Comment by stevengj** [comment]
On MacOS and Linux, we can use `dladdr` to find the `libjulia` path.  On Windows, maybe [GetModuleFileName](http://msdn.microsoft.com/en-us/library/windows/desktop/ms683197%28v=vs.85%29.aspx)?  (See also [here](http://libsylph.sourceforge.net/wiki/Full_path_to_binary).)

**Comment by twadleigh** [comment]
Closing this. Most likely way out of date.
