### ISSUE TITLE
Shift-enter kills REPL on Linux

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#9696]
With:

```julia
julia> ERROR: Unrecognized input
 in error at error.jl:21
 in anonymous at LineEdit.jl:860
 in anonymous at LineEdit.jl:760
 in prompt! at ./LineEdit.jl:1556
 in run_interface at ./LineEdit.jl:1529
 in run_frontend at ./REPL.jl:838
 in run_repl at ./REPL.jl:170
 in _start at ./client.jl:438
```

**Comment by JeffBezanson** [comment]
Works for me. Do you have shift-enter set up to do anything in particular?

**Comment by simonster** [comment]
Hmm, it works for me in xterm and gnome-terminal but not konsole. I can fix it by switching the key binding list from "Default (XFree 4)" to "Linux console." It looks like the default keybinding is set to send `\EOM`.

**Comment by simonster** [comment]
I can also kill Julia on OS X with the same error by pressing any of the F-keys (really fn+any of the F-keys, since otherwise they're mapped to various other functions)

**Comment by JeffBezanson** [comment]
I don't see any point in our throwing an "unrecognized input" error that kills the repl on unhandled keys. Shouldn't we just ignore them? @Keno

**Comment by srp** [comment]
Possibly beep and ignore

**Comment by srp** [comment]
Speaking of which, why is the actual implementation of beep commented out?

**Comment by ivarne** [comment]
Because @nolta [hates beep](https://github.com/JuliaLang/julia/commit/ca8aea35b456fc14b4e6b99a7ee573c9fce2fa1a), and thinks others should too.

`git blame` (or the github `blame` button) makes it easy to answer questions like this.

**Comment by srp** [comment]
Thanks, I'd found the commit just not the discussion.

**Comment by Keno** [comment]
Yes, we should ignore them. Probably just an oversight in the keymap.

**Comment by timholy** [comment]
I can verify this under konsole, too. Happens frequently when I am typing `include("` and my finger lands halfway between the quote and Enter.
