### ISSUE TITLE
substitution in try-catch expression

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#9704]
Using substitution in try-catch expression does not produce expected result

```
julia> a = :a
:a

julia> ex = :(try
       catch $a
       end)
:(try 
    catch 
        a
    end)

julia> ex = :(try
       catch a
       end)
:(try 
    catch a
    end)
```

Notice in the first case `a` is in the catch block while in the second case `a` is the variable to store the exception.

**Comment by yuyichao** [comment]
Other new line sensitive structure like `let` doesn't have this issue though.

```julia
julia> a = :a
:a

julia> ex = :(let $a = 1
       end)
:(let a = 1
    end)

julia> ex = :(let
       $a = 1
       end)
:(let  # line 2:
        a = 1
    end)
```

**Comment by JeffBezanson** [comment]
Thanks. You're good at finding bugs!

**Comment by yuyichao** [comment]
... I felt like bugs are good at finding me though = = .....

Thanks for the fix...
