### ISSUE TITLE
Accelerating Sparse Cholesky Factorization on GPUs

### ISSUE THREAD

**Issue by esd100** [JuliaLang/julia#9706]
I'm not sure if anyone is working on stuff related to this, but I just stumbled across this paper today and thought it would be something to consider when people are trying to achieve Julia's goal of being fast. I guess this isn't really an "issue" but I didn't know where else to post something that I thought was informational.

http://dl.acm.org/citation.cfm?id=2688285
doi>10.1109/IA3.2014.6

Abstract—Sparse direct factorization is a fundamental tool in scientific computing. As the major component of a sparse direct solver, it represents the dominant computational cost for many analyses. While the substantial computational capability provided by GPUs (Graphics Processing Units) can help alleviate this cost, many aspects of sparse factorization and GPU computing, most particularly the prevalence of small/irregular dense math and slow PCIe communication, make it challenging to fully utilize this resource. In this paper we describe a supernodal Cholesky factorization algorithm which permits improved utilization of the GPU when factoring sparse matrices. The central idea is to stream branches of the elimination tree (subtrees which terminate in leaves) through the GPU and perform the factorization of each branch entirely on the GPU. This avoids the majority of the PCIe communication without the need for a complex task scheduler. Importantly, within these branches, many independent, small, dense operations are batched to minimize kernel launch overhead and several of these batched kernels are executed concurrently to maximize device utilization. Supernodes towards the root of the elimination tree (where a branch involving that supernode would exceed device memory) typically involve sufficient dense math such that PCIe communication can be effectively hidden, GPU utilization is high and hybrid computing can be easily leveraged. Performance results for commonly studied matrices are pre- sented along with suggested actions for further optimizations.

![screen shot 2015-01-09 at 11 31 32 pm](https://cloud.githubusercontent.com/assets/4109522/5690455/3181f6fc-9858-11e4-8983-663f6328dc31.png)
![screen shot 2015-01-09 at 11 32 09 pm](https://cloud.githubusercontent.com/assets/4109522/5690456/362d409e-9858-11e4-8e7f-5b176448fa0f.png)

**Comment by IainNZ** [comment]
Should really go on julia-users

**Comment by ViralBShah** [comment]
The cholmod solver we use has a GPU mode. It is a matter of building it, which will be non trivial, bit definitely doable.

**Comment by ViralBShah** [comment]
More information: https://developer.nvidia.com/cholmod
