### ISSUE TITLE
how to reduce memory occupation?

### ISSUE THREAD

**Issue by songroom** [JuliaLang/julia#9707]
in my project, i need to use julia to fetch datas from SQLite with using SQLite.jl ,but with increasing to above 3,000,000 records, the memory of julia occupation is creasing rapidly, and the speed of fetching data is more and more slower .
other good suggestions for me ?
thanks!

**Comment by songroom** [comment]
a test:
if you run
~~~
a =rand(10000,1000);
a=null
~~~
it  looks that memory of a has not been cleared.
but if you run again,
~~~
a=null;
~~~
memory of a has been cleared.

**Comment by jakebolewski** [comment]
This is an issue better raised on the [julia users mailing list](https://groups.google.com/forum/#!forum/julia-users).

**Comment by casasgomezuribarri** [comment]
Your link only directs to the mailing list. Could you give more information about which issue you werereferring to? (do you remember the title, user or date?)

Sorry for reopening this, but I am also having trouble reducing the memory allocation of my Julia processes, which run in a shared computer cluster. My project involves training a ConvNeuralNet with images (~10GB image library)
