### ISSUE TITLE
Openblas build fails on OS X 10.10.1

### ISSUE THREAD

**Issue by sarvagnan** [JuliaLang/julia#9709]
On a fresh clone of the Julia repo, openblas fails to build, recommended a clean.
After running make -C deps clean-openblas and make -C deps install-openblas, 
this error is shown (along with the last line of output):

gfortran -mmacosx-version-min=10.7 -m64 -O2  -O2 -m128bit-long-double -Wall -m64 -fdefault-integer-8   -o sblat1 sblat1.o ../libopenblasp-r0.2.13.a -lpthread -lgfortran -lpthread -lgfortran
ld: library not found for -lcrt1.10.6.o
collect2: error: ld returned 1 exit status
make[2]: *** [sblat1] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [tests] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make: *** [openblas-v0.2.13/libopenblas.dylib] Error 1

What should I do to get this working?
Thanks!!

**Comment by staticfloat** [comment]
Hmmm.  What version of Xcode do you have?  Are there any updates available for Xcode in the app store?

**Comment by sarvagnan** [comment]
Xcode version 6.1.1 (6A2008a)
There aren't any updates available. Xcode did install some tools when opened (not sure of the details). They haven't helped though, I get the same error.

**Comment by sarvagnan** [comment]
Though now the error is slightly longer:
gfortran -mmacosx-version-min=10.7 -m64 -O2  -O2 -m128bit-long-double -Wall -m64 -fdefault-integer-8   -o sblat1 sblat1.o ../libopenblasp-r0.2.13.a -lpthread -lgfortran -lpthread -lgfortran
gfortran -mmacosx-version-min=10.7 -m64 -O2  -O2 -m128bit-long-double -Wall -m64 -fdefault-integer-8   -o dblat1 dblat1.o ../libopenblasp-r0.2.13.a -lpthread -lgfortran -lpthread -lgfortran
ld: library not found for -lcrt1.10.6.o
collect2: error: ld returned 1 exit status
make[2]: *** [sblat1] Error 1
make[2]: *** Waiting for unfinished jobs....
ld: library not found for -lcrt1.10.6.o
collect2: error: ld returned 1 exit status
make[2]: *** [dblat1] Error 1
make[1]: *** [tests] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make: *** [openblas-v0.2.13/libopenblas.dylib] Error 1

**Comment by staticfloat** [comment]
What happens if you run `xcode-select --install`?

**Comment by sarvagnan** [comment]
It worked! Xcode-select --install pulled up a bunch of updates that it then installed. Now openblas builds.  Is this the first step that should be taken when a build fails?
Thanks!!

**Comment by staticfloat** [comment]
This command is only necessary when first running Xcode on a machine that has been upgraded to OSX 10.10, so you shouldn't have to worry about it ever again.  The first thing you should try you already did, which is to `make clean`/`make cleanall` and try again!
