### ISSUE TITLE
non-deterministic ArgumentError when loading package

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/julia#9718]
I get this error every, maybe 1/20 times that I load a particular package. 

Always the [same code](https://github.com/jlapeyre/PrimeSieve.jl/blob/master/src/primesieve_c.jl#L98)  triggers the error. Note there is a comment in the code about the error, but the bug was present before the comment!

> ERROR: ArgumentError("invalid base 10 digit '@' in \"100000000000000000000000@\\0\\0\\0\"")
>  in parseint_nocheck at string.jl:1538
>  in parseint_nocheck at string.jl:1566
>  in int128 at string.jl:1587
>  in primepi_xmax at /home/jlapeyre/.julia/v0.4/PrimeSieve/src/primecount_c.jl:97
>  in include at ./boot.jl:248
>  in include_from_node1 at ./loading.jl:128
>  in include at ./boot.jl:248
>  in include_from_node1 at ./loading.jl:128
>  in reload_path at ./loading.jl:152
>  in _require at ./loading.jl:67
>  in require at ./loading.jl:52
> while loading /home/jlapeyre/.julia/v0.4/PrimeSieve/src/primecount_c.jl, in expression starting on line 98
> while loading /home/jlapeyre/.julia/v0.4/PrimeSieve/src/PrimeSieve.jl, in expression starting on line 36

**Comment by jakebolewski** [comment]
Closing for now, please respond to this thread if this is still an issue.
