### ISSUE TITLE
`bswap(x::Float32)` dangerous and unused?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#9726]
I notice that `bswap(x::Float32)` and `bswap(x::Float64)` change the byte order of the float's internal representation, and then re-interpret the result again as a float. This is dangerous; some CPUs e.g. have a "flush-subnormals-to-zero" mode that may garble the resulting number. Similarly, if they encounter a signalling nan, the code may abort. Whether this happens in practice depends on how the compiler stores the resulting "nonsense" floating-point number.

Note that these functions are actually unused, as `write` in IO re-interprets floating-point numbers as integers before applying the equivalent of `hton`.

I thus suggest to remove `bswap(x::Float32)` and `bswap(x::Float64)`.

**Comment by Keno** [comment]
Is there actually any real hardware that does this if the number is not subsequently used in a floating point operation?

**Comment by JeffBezanson** [comment]
There should be no danger in, say, reading in a Float32 array and then doing `map!(bswap, A)` on it.

**Comment by iamed2** [comment]
`hton(x::Float64)` (for example) requires this method to exist, and though I'm not currently using it, I may again in the future. PostgreSQL requires network byte order for sending 32- and 64-bit floats using the binary method.

**Comment by eschnett** [comment]
If you like to have this function, do you want to add a test case for it?

**Comment by iamed2** [comment]
Sure, I can do that tonight.
