### ISSUE TITLE
Julia/Valgrind documentation + suppressions needed

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#9733]
Julia could really use some developer documentation explaining how to run Julia under Valgrind.  This should explain
- how to [deal with architecture mismatch errors under valgrind](https://groups.google.com/forum/#!searchin/julia-dev/valgrind/julia-dev/ATr983gW9FA/HjheEXp9s3wJ)
- how to suppress spurious warnings

CPython has an incredibly good [guide for running under valgrind](https://github.com/python/cpython/blob/master/Misc/README.valgrind) along with a [sample suppression file](https://github.com/python/cpython/blob/master/Misc/valgrind-python.supp).

**Comment by timholy** [comment]
That sounds great. Willing to take a crack at it? (For the first point, just do `rm usr/lib/julia/sys.so` and proceed as you normally would with valgrind. That library is only needed to shorten the startup time, julia runs fine without it.)

**Comment by garrison** [comment]
I can write a few lines of documentation, but I really know next to nothing about writing a suppressions file.  If somebody could provide one (even if incomplete), that would be great.

**Comment by timholy** [comment]
FWIW, I have no idea, either. So I'm no help here.

**Comment by garrison** [comment]
I've figured out how to create a basic valgrind suppression file, so I'll probably have a pull request ready on this soon.

**Comment by ihnorton** [comment]
possibly worth mentioning that default suppressions are borked in some versions of valgrind (which might have made it into systems depending on release window, not sure). see: https://github.com/JuliaLang/julia/issues/8314#issuecomment-55766210

**Comment by Keno** [comment]
We can use some valgrind magic to have it ignore the architecture mismatch errors. I also have a few suppressions to add, once @garrison creates his pull request. I think a good place to put it might be `contrib/julia.supp`.

**Comment by garrison** [comment]
@Keno Can you elaborate on how to use valgrind magic to ignore the architecture mismatch error?  Is this something you've done already or something you think should be possible?

**Comment by Keno** [comment]
Nothing fancy, just using the `RUNNING_ON_VALGRIND` from valgrind.h (we might have to copy that into the source tree since we still want to build on systems that don't have valgrind installed).

**Comment by garrison** [comment]
See PR #9911.

**Comment by garrison** [comment]
Thanks!
