### ISSUE TITLE
mapfoldl and mapfoldr not exported

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#9736]
Both are mentioned in the docs and available as `Base.mapfoldX`, but not exported.

**Comment by nalimilan** [comment]
Would you make a pull request for this? You just need to add them to the lists of `exports` at `base/exports.jl`. You can even do it directly on GitHub.

**Comment by rened** [comment]
absolutely! I just wasn't sure whether that is all there is to it. PR is #9737
