### ISSUE TITLE
Prefixing method with module name breaks code on 0.4.0

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#9739]
Example:

0.3.4
```
julia> methods(cdCreateCanvas)
# 1 method for generic function "cdCreateCanvas":
cdCreateCanvas(context::Ptr{cdContext},data::Ptr{None}) at C:\programs\Gits\IUP.jl\src\libcd.jl:269
```
0.4.0
```
julia> methods(cdCreateCanvas)
# 1 method for generic function "cdCreateCanvas":
cdCreateCanvas(context::Ptr{IUP_CD.cdContext},data::Ptr{Union()}) at C:\programs\Gits\IUP.jl\src\libcd.jl:269
```

which later breaks the code (that works in 0.3.4) with
```
ERROR: `cdCreateCanvas` has no method matching cdCreateCanvas(::Ptr{IUP_CD.cdContext}, ::Ptr{Void})
Closest candidates are:
  cdCreateCanvas(::Ptr{IUP_CD.cdContext}, ::Ptr{Union()})
```

**Comment by ivarne** [comment]
Usually issues such as this is much easier to fix if we get a (minimal) reproducible example that can be pasted into a REPL session. You seem to be referencing [IUP.jl](https://github.com/joa-quim/IUP.jl), and as it requires binary dependencies, it is kind of a hassle to install just to debug this issue.

**Comment by ivarne** [comment]
Sometimes issues like this can be caused by loading  the same module twice, eg with `reload`. Can you try the examples again in a new session?

**Comment by joa-quim** [comment]
Yes, it happens with IUP and that's why I didn't try to find a small set of commands that reproduce the problem. However, I do recall that there was a post or an issue that referenced this issue not long time ago. I just wasn't able to find it again. 
And no, it's not a double module loading thing. It happens right on the first call.

**Comment by Keno** [comment]
This isn't a bug. `Void`, which used to be `Union()` is now the type of `nothing`, so the second argument is the problem.

**Comment by tkelman** [comment]
Looks like Compat.jl might need some code to help packages deal with the Void change?

**Comment by Keno** [comment]
Using `Ptr{Void}` will work on both versions, as long as it's done everywhere.

**Comment by joa-quim** [comment]
Sorry, a bit too concentrated info to me. You mean changing Ptr{None} to Ptr{Void} in https://github.com/joa-quim/IUP.jl/blob/master/src/libcd.jl#L269 ?

If I do so, I don't get the previous error but instead simply (after loading an image)
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: UNKNOWN at 0x32f1160 --
```
In case someone wants to try (needs to install IUP), It occurs with (im_view is an example in the `examples` dir)
```
using im_view_;
im_view()
```

**Comment by Keno** [comment]
Yes, that's what I mean. Does it also segfault on 0.3?

**Comment by joa-quim** [comment]
No, 0.3 runs fine

**Comment by Keno** [comment]
Ok, I suspect than that doing the change is not the problem, but that there is some other bug causing the segfault. Are you able to get a backtrace.

**Comment by joa-quim** [comment]
Sorry, no. That's the only error message I get (it's a Win build btw).

**Comment by Keno** [comment]
Ok, I can take a look tomorrow and see if I can reproduce.

**Comment by JeffBezanson** [comment]
IUP issue opened: https://github.com/joa-quim/IUP.jl/issues/1
