### ISSUE TITLE
Backtrace states: error repeats 2 times and shows no other information

### ISSUE THREAD

**Issue by Mike43110** [JuliaLang/julia#9752]
```
ERROR: InexactError()
 in in at range.jl:553 (repeats 2 times)
while loading C:\Users\Michael\Dropbox\Masters\Masters-Experiments\Experiment1-J
ulia\main.jl, in expression starting on line 35
```

I get the above when running a function defined in main (which calls many other functions)
Should this not show the entire backtrace rather?
(If there is a way to view it already I apologise)

On 0.3.5

**Comment by tkelman** [comment]
win32 or win64? Source build or binary? Can you try the same code on a different platform (or point to reproducible example code) and see if the backtrace is any different?

**Comment by Mike43110** [comment]
Windows 8.1 x64 Haswell binary build. 
Sorry for forgetting that!

I will setup a virtual machine and test it on Ubuntu. Should be able to confirm in a few hours.

**Comment by Mike43110** [comment]
```
ERROR: LoadError: InexactError()
 in in at range.jl:561
 in collisionFitness at /home/mmmmm/Experiment1-Julia/RobotFitness.jl:285
 in updateFitness! at /home/mmmmm/Experiment1-Julia/RobotFitness.jl:8
 in genIndividuals at /home/mmmmm/Experiment1-Julia/RobotGA.jl:54
 in evolve! at /home/mmmmm/Experiment1-Julia/RobotGA.jl:25
 in testFunction at /home/mmmmm/Experiment1-Julia/main.jl:29
 in include at ./boot.jl:248
 in include_from_node1 at ./loading.jl:128
while loading /home/mmmmm/Experiment1-Julia/main.jl, in expression starting on line 35
```
Is the full error displayed. Tested using the nightly build on ubuntu inside vmware.

On the nightly on windows the error was: 
```
```

**Comment by tkelman** [comment]
This and #9771 look very similar. Can you provide the code to reproduce this?

**Comment by Mike43110** [comment]
I could generate the backtrace without requiring --inline=0.

```
xMin = round(Int, min(old_point.x, point.x))
xMax = round(Int, max(old_point.x, point.x))
xRange = xMin:xMax #create the range
if length(X1) > 0 && round(Int, X1[1]) in xRange
    x1 = X1[1]
    x2 = xRange[end]#change to point
    y1 = polyval(y,x1)
    y2 = polyval(y,x2)#change to point
    r_remain = sqrt((x2-x1)^2 + (y2-y1)^2)
    fitness += r_remain
elseif length(X2) > 0 && round(Int, X2[1]) in xRange
    x1 = X2[1]
    x2 = xRange[end]#change to point
    y1 = polyval(y,x1)
    y2 = polyval(y,x2) #change to point
    r_remain = sqrt((x2-x1)^2 + (y2-y1)^2)
    fitness += r_remain
end
```

This is the area which is causing the issue. This is a snippet of a fitness function of a GA.
I would have to provide all my code to reproduce this neatly unfortunately, can't provide a simplified version.
.

**Comment by tkelman** [comment]
I have a relatively small amount of pure-Julia code that shows similar behavior:
```
Pkg.clone("https://github.com/tkelman/BLOM.jl")
Pkg.checkout("BLOM","backtrace")
Pkg.test("BLOM")
```

On Linux latest 0.4 master, the full backtrace is
```
ERROR: LoadError: BoundsError
 in deleteat! at array.jl:593
 in concat_expressions at /home/tkelman/.julia/v0.4/BLOM/src/sparseutils.jl:243
 in + at /home/tkelman/.julia/v0.4/BLOM/src/operators.jl:19
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:321
 in _start at ./client.jl:413
while loading /home/tkelman/.julia/v0.4/BLOM/test/runtests.jl, in expression starting on line 12
```

On 0.3.6 Win64, I get `in deleteat! at array.jl:554 (repeats 2 times)` and that's it. 0.4 Win64 isn't much better, even without sys.dll. 0.4 Win32 is better, it's missing `in +` but the rest of the backtrace is there.

**Comment by vtjnash** [comment]
i suspect this is either a duplicate or fixed
