### ISSUE TITLE
Make fails on RHEL for latest version of v0.3 branch

### ISSUE THREAD

**Issue by grayclhn** [JuliaLang/julia#9753]
Make fails to build julia on the release-0.3 branch (commit 74acbbf)
and on master (commit 7f915c7) for Red Hat Linux with the error
```
[cut other make output...]
/usr/bin/ld: unrecognized option '-Bsymbolic-functions'
/usr/bin/ld: use the --help option for usage information
collect2: ld returned 1 exit status
make[2]: *** [/home/gcalhoun/julia/usr/lib/libjulia.so] Error 1
make[1]: *** [julia-release] Error 2
```

I used `git bisect` to track the bug down to commit eb95148, which
cherry-picks commit 34105d3 to backport pull request #9130.  Make
successfully builds julia in v0.3 after reverting commit eb95148 and
in master after reverting commits 34105d3 and 1a60f0a. The commits
that I've reverted add a `-Bsymbolic-functions` flag, but I don't know
what that flag does or how important it is.

Output of `versioninfo()` (after reverting the commit and building
release-0.3)
```
Julia Version 0.3.6-pre+5
Commit fc33c8c (2015-01-13 15:21 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux6E)
  CPU: Intel(R) Xeon(R) CPU           X5482  @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY PENRYN)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment]
This is red hat 6? What compiler / binutils versions? cc @waTeim

This would be really easy to deal with if we were using autotools or cmake. With just gnu make it's a bit messier to solve in a nice way.

**Comment by staticfloat** [comment]
This flag is really nice to have for embedding purposes, so we'll probably just need to figure out a way to nicely disable it when absolutely necessary.

**Comment by tkelman** [comment]
LLVM 3.5 will force using compilers newer than RHEL 5 / 6 come with by default, so at that point using the devtoolset (which has new enough binutils that this isn't an issue) will be mandatory on those distributions rather than optional-but-recommended like it is now. We should still come up with a fix for release-0.3 though.

**Comment by waTeim** [comment]
Ok. so RHE 6 can be old school, but as it turns out, I'm working on a host right now that is in fact running RHE 6.5 and it DOES have a linker that supports it, so it's not just RHE6, it's an older version of RHE6 that is encountering this problem.

    lsb_release -a
    LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
    Distributor ID:	RedHatEnterpriseServer
    Description:	Red Hat Enterprise Linux Server release 6.5 (Santiago)
    Release:	6.5
    Codename:	Santiago

    ld -version
    GNU ld version 2.20.51.0.2-5.36.el6 20100205

    ld -Bsymbolic-functions
    ld: no input files

in comparison

    ld  -Bflubbity-floo
    ld: unrecognized option '-Bflubbity-floo'
    ld: use the --help option for usage information

**Comment by grayclhn** [comment]
It's actually RHEL 5.11, I think, and I have no expectation that julia
0.4 will work. (At least, without more effort on my part.)

binutils is version 2.17.50.0.6 and gcc is version 4.4.7.

**Comment by grayclhn** [comment]
Addendum to the last comment: I don't really expect 0.3.x to work on RHEL 5 either, but if it's just a matter of selectively disabling one flag, that seems possible. I'm also happy to just patch the makefile on my computer, if the problem doesn't affect anyone else.

**Comment by staticfloat** [comment]
You can patch the Makefile for sure, but I would suggest installing the CERN
devtoolset 2.1 <http://linux.web.cern.ch/linux/devtoolset/#dts21>.  That's
what I use to build the generic linux binaries
<http://julialang.org/downloads/> on CentOS 5.11 with.
-E

**Comment by grayclhn** [comment]
Thanks. I'll look into that.

**Comment by tkelman** [comment]
whoops, I guess given the issue title we should technically keep this open until it gets backported

**Comment by tkelman** [comment]
Oh yeah, backported this in eaad06c0a55fa0e201b1c23f5bf74000b179fd6a. Closing.
