### ISSUE TITLE
error when trying to assign a function name to a constant variable is confusing

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#9773]
When you get the error
```
julia>const ff = 1
julia>ff()=1
invalid method definition: not a generic function
```
When I saw this in a large code block I was very puzzled about what julia tried to tell my. While when the variable name is not a constant then the error seems much more understandable:
```
julia>f = 1
julia>f()=1
cannot define function f; it already has a value
```
Where it is clear what julia means.

**Comment by nalimilan** [comment]
Indeed. Though I'd rather say `cannot define function f: an object with this name already exists`.

**Comment by JeffBezanson** [comment]
This is in `jl_method_def` in toplevel.c. It's easy to add the variable name to this error message.

**Comment by dhoegh** [comment]
My main concern where the wording of the error. `not a generic function` do not say anything about what the user done wrong while `it already has a value` does.

**Comment by dhoegh** [comment]
Thank you. @juliabackports

**Comment by tkelman** [comment]
backported in 5b255899ce6334e6cfb1ceeb4faf015ae5af364e
