### ISSUE TITLE
Weird behavior of iteration of tuple over tuple

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#9784]
I can't make any sense of this behavior. Maybe I'm missing something, but this sounds really unexpected and thus potentially misleading to me.

```julia
julia> for (a,b) in (1:3,)
           @show (a,b)
       end
(a,b) = (1,2)
```

**Comment by jakebolewski** [comment]
All nested iterables work this way.

```julia
julia> a = Any[1:2, 3:4, 5:6]
3-element Array{Any,1}:
 1:2
 3:4
 5:6

julia> for (x,y) in a
       @show x,y
       end
(x,y) => (1,2)
(x,y) => (3,4)
(x,y) => (5,6)
```

You destructure each argument in the toplevel iterable and assign the first two values from calling `next` to x and y.

similarly you can do
```julia
julia> (x,y) = 1:3
1:3

julia> x
1

julia> y
2
```

**Comment by nalimilan** [comment]
OK, I guess there are valid use cases where one wants to discard the third element in the tuple. I'd certainly prefer a more explicit behavior, e.g. using `_`, but well...
