### ISSUE TITLE
take in iterator protocol

### ISSUE THREAD

**Issue by doomsplayer** [JuliaLang/julia#9785]
are there any plan to add `take` to the iterator protocol?
code example:
    
    a=[1,2,3,4,5]
    collect(take(filter(x->x%2==0),1)) # => [2]
    collect(take(filter(x->x%2)==0,2)) # => [2,4]

**Comment by garborg** [comment]
See [JuliaLang/Iterators.jl](https://github.com/JuliaLang/Iterators.jl) for take and similar.

**Comment by ViralBShah** [comment]
Such a question is also better to ask on the mailing lists.

**Comment by doomsplayer** [comment]
sorry for annoying. mail list first the next time :P
