### ISSUE TITLE
Better support for intptr_t in 0.4

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#9786]
I was just stumbling across the issue, that the type alias `Cssize_t` isn't the correct choice to emulate an `intptr_t`, since Julia 0.4 doesn't allow for overflow anymore.
Example:
```Julia
julia> ptr = Ptr{Void}(typemax(UInt64))
Ptr{Void} @0xffffffffffffffff
julia> convert(Cssize_t, ptr)
ERROR: InexactError()
 in convert at pointer.jl:7 (repeats 2 times)
```
This is not what is needed, as a real `intptr_t` should allow for overflow.
Taken from stdint:
```
intptr_t: Integer type capable of holding a value converted from a 
void pointer and then be converted back to that type with a value 
that compares equal to the original pointer.
```
This is a problem, when interfacing with c-libraries using `intptr_t` and will introduce subtle bugs if ignored.
I stumbled upon this, while creating an OpenCL/OpenGL interop context, which requires an opengl surface handle (`Ptr{Void}`) from the OS, which needs to be converted to an `intptr_t` in order to pass it to OpenCL. (JuliaGPU/OpenCL.jl#63)

Best,
Simon

**Comment by stevengj** [comment]
I agree; should be a simple patch to change the `Ptr`-to-`UInt` conversion to `convert{T<:Union(Int,UInt)}(::Type{T}, x::Ptr) = box(T, unbox(Ptr,x))`

**Comment by stevengj** [comment]
Hmm, we also need `convert{P,T<:Union(Int,UInt)}(::Type{Ptr{P}}, x::T) = box(Ptr{P},unbox(T,x))` to make  bidirectional conversion possible.

**Comment by SimonDanisch** [comment]
That would be a relatively simple fix! 
I don't know any cases, that would speak against this solution.

**Comment by stevengj** [comment]
Here is something really weird:
```
julia> convert(Int, typemax(UInt64))
ERROR: InexactError()
 in convert at /Users/stevenj/Code/julia/usr/lib/julia/sys.dylib

julia> convert(Int8, typemax(UInt64))
-1
```
Why is conversion to `Int` checked but not `Int8`?

**Comment by stevengj** [comment]
(Not that it matters, but I would translate `intptr_t` into `Int` in Julia, not `Cssize_t`.)

**Comment by vtjnash** [comment]
i'm inclined to revert this and actually make pointer conversions much more strict. it's completely foolish that we are currently less restrictive about pointer-to-integer conversions than C. pointers aren't signed quantities, so using signed variables can potentially lead to comparison/ordering errors.

to be really accurate to the ssize_t spec [XSI], the test at the top was actually correctly failing. the number `typemax(UInt64)`, in addition to never being a valid memory location, is also not in the range of valid values for `Cssize_t` (which excludes includes negative numbers)

also, fwiw, apparently when a similar issue was reported on the glib bugtracker, it was rejected: https://sourceware.org/bugzilla/show_bug.cgi?id=13575

**Comment by SimonDanisch** [comment]
I didn't get the point of signed pointers, but this seems to be the [explanation](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=223):
```
The introduction of intptr_t is chiefly important in 64-bit computing. The problem is that most 64-bit systems use the LP64 model, whereby long and data pointers have the same size of 64-bits, whereas int has only 32-bits. If you want to write dually-targeted code for 32/64-bit platforms, intptr_t is guaranteed to work correctly on both.
```
OpenCL forces me to convert a `Ptr{Void}` to an `intptr_t`, which can overflow at conversion. 
This would mean, we need our own intptr_t type, since you say that ssize_t can't model the correct behavior, correct?

**Comment by vtjnash** [comment]
yes. to be very strictly accuracy, the `size_t` type may not be large enough to store any pointer (google will help you find references for this). for hardware currently supported by julia, this theoretical concern doesn't seem to matter, however. technically, `(U)Int` is the exact counterpart of `(u)intptr_t`, as stevengj mentioned.

the other awkward part of this is that math on the intptr_t type is technically undefined and may have different behavior than the same math on the void* type. i suspect an example of where this might be true includes cases where the memory is in different memory regions – e.g. a DMA buffer or a GPU, rather than main memory.

**Comment by vtjnash** [comment]
pondering this further, i think we should replace the `convert` method definitions here with `mod` (aka `0 % Ptr{Void} === C_NULL`)
