### ISSUE TITLE
Error in dlopen on Windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#9793]
I get this:

````
julia> ispath("C:/Program Files (x86)/Java/jre7/bin/client/jvm.dll")
true

julia> dlopen("C:/Program Files (x86)/Java/jre7/bin/client/jvm.dll")
ERROR: could not load module C:/Program Files (x86)/Java/jre7/bin/client/jvm.dll: The specified module could not be found.

 in dlopen at c.jl:19

julia>
````

Julia 0.3.5. Found this while trying to use Taro, then narrowed it down to JavaCall, and now this.

**Comment by ihnorton** [comment]
Are you using 32-bit Julia? Otherwise this usually means there is a dependency missing. You could try dependency walker to figure out what the loader is looking for.

**Comment by davidanthoff** [comment]
Yep, that was it. Thanks!
