### ISSUE TITLE
improve windows backtraces

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#9796]
By replacing Microsoft's dbghelp.dll with the one included in wine, we should be able to fix our backtraces (e.g. fix the symbol name lookup in gcc-compiled code, and maybe even considerably speed up the throwing of errors).

It seems someone's already done the work to port it: http://mingw32dbghelp.sourceforge.net/Readme.txt

So this issue is a matter of building that library and dropping the resulting binary into usr/bin and seeing where it can go from there

**Comment by vtjnash** [comment]
as predicted, this is about 40x faster than the microsoft-provided debugger library (still might be up to 5x slower than mac/linux, since there's probably still lots of room to optimize). additionally, it gives correct line numbers (and function names) for the sys.dll and libjulia files.

wine dbghelp library modified for usage on windows:
https://github.com/vtjnash/dbghelp2

julia build tree, modified to link against the library built in the previous step (copy both files from lib/dbghelp/GCC_RELEASE to the appropriate usr folder in the julia build tree):
build with https://github.com/JuliaLang/julia/tree/jn/win_backtrace_lines

**Comment by timholy** [comment]
Wow, amazing!

**Comment by tkelman** [comment]
dwarf.c does not compile from either Cygwin or Linux
```
x86_64-w64-mingw32-gcc -o"/home/tkelman/github/dbghelp2/objs/GCC_RELEASE//dbghelp/dwarf.o" "dlls/dbghelp/dwarf.c"   -DWINE_UNICODE_API= -D__WINESRC__=1 -DHAVE_REGEX_H=1 -Wall -Wno-unused-variable -D_IMAGEHLP_SOURCE_= -DNONAMELESSUNION= -DNONAMELESSSTRUCT= -DDLLPREFIX='L""' -Iinclude -Iinclude/mingw64 -I"include" -c
In file included from /usr/share/mingw-w64/include/winspool.h:12:0,
                 from /usr/share/mingw-w64/include/windows.h:102,
                 from /usr/share/mingw-w64/include/rpc.h:16,
                 from /usr/share/mingw-w64/include/objbase.h:7,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from dlls/dbghelp/dwarf.c:53:
/usr/share/mingw-w64/include/prsht.h:86:3: error: unknown type name ‘LPCDLGTEMPLATE’
   typedef LPCDLGTEMPLATE PROPSHEETPAGE_RESOURCE;
   ^
```

**Comment by tkelman** [comment]
With `-DWIN32_LEAN_AND_MEAN` it will compile but not link. Undefined references to `_assert` and `__imp___iob_func`

**Comment by tkelman** [comment]
fix your fixme's for cross-compilation, `LD='$(CXX)'` and it'll link

**Comment by tkelman** [comment]
Might need Wine's ntdll for 32 bit, getting undefined references to RtlImageNtHeader and RtlImageRvaToVa despite `-lntdll` on the link line.

**Comment by vtjnash** [comment]
> as predicted, this is about 40x faster than the microsoft-provided debugger library

oops, i tested against the wrong version of julia: 0.3.5 was already 10x faster than 0.3.0

and with llvm 3.6, it may be true that llvm starts doing this line number fix for us
