### ISSUE TITLE
Unicode superscript numbers for exponentiation

### ISSUE THREAD

**Issue by jonasrauber** [JuliaLang/julia#9806]
I am sorry if this has already been discussed somewhere, but I couldn't anything.

I think it would be very nice to be able to use more unicode symbols to make the code more beautiful:

```julia
julia> 3^2
9

julia> 3²
ERROR: syntax: invalid character "²"
```
These days it's so easy to type these unicode characters (e.g. using ctrl+cmd+space on OS X), so it would be nice if one would be able to use them in this intuitive way.

**Comment by StefanKarpinski** [comment]
People seem to like using these superscripts as part of variable names, e.g. `χ²`. Since you can't write general superscripts this way, that seems like a pretty usage to me.

**Comment by jonasrauber** [comment]
I didn't realize that you can use it in variable names but this is indeed a pretty good usage. So I think we can close this issue as exponentiation using superscripts might then lead to ambiguity with variable names. Another solution would be to allow exponentiation using superscripts only for numbers, but that's probably too confusing.

**Comment by juliohm** [comment]
I use it in variables names, see:

https://github.com/juliohm/ImageQuilting.jl/blob/master/src/imquilt.jl#L185

**Comment by StefanKarpinski** [comment]
Given the lack of generality and how easy it is to write `x^2`, and that people seem to like having superscripts and subscripts in variable names, I think it's probably best to leave this as it is.
