### ISSUE TITLE
Vectorize rem()

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#9807]
In GNU Octave we can write:

```octave
f = @(n) rem(n,2)

f(1:10)
```

Julia's `%` operator shouldn't work likewise? It currently doesn't have a method for ranges.

**Comment by kmsquire** [comment]
Perhaps we should add a "vectorization" tag, to keep track of the various related issues?  (Might be too broad, though...)

**Comment by ivarne** [comment]
See also https://github.com/JuliaLang/julia/issues/8450

**Comment by jakebolewski** [comment]
There is a host of other vectorization issues that subsume this one.
