### ISSUE TITLE
Allow deprecation of curly Exprs

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#9830]
In #9820 @matrixmorpheus attempted to deprecate the constructor `Triangular{S, T, :U, true}` which no longer exists on 0.4-dev. However,

``` jl
julia> @deprecate Triangular{S, T, :U, true} Base.LinAlg.UnitUpperTriangular
ERROR: invalid usage of @deprecate
```

This error is triggered currently because the expression being deprecated is not currently supported.

```
julia> dump(:( Triangular{S, T, :U, true}))
Expr 
  head: Symbol curly
  args: Array(Any,(5,))
    1: Symbol Triangular
    2: Symbol S
    3: Symbol T
    4: QuoteNode 
      value: Symbol U
    5: Bool true
  typ: Any
```

(`@deprecate` only handles `Expr`s with `head == call` currently).

I tried to change [this line](https://github.com/JuliaLang/julia/blob/e98b817c600a7b60c466a69fcf7b68f2ec9a6612/base/deprecated.jl#L14) to add the last `|| ...` clause:

``` jl
isa(old,Expr) && (old.head == :call || old.head == :curly)
```

but this resulted in a new error instead when I tried to execute the same `@deprecate` command:

```
ERROR: syntax: invalid assignment location
```

so I'm not sure how to fix this.

**Comment by JeffBezanson** [comment]
I don't think there is any good way to do this.

**Comment by jakebolewski** [comment]
Unfortunately this means implementing something along the lines of #8240 would be hugely breaking.

**Comment by tkelman** [comment]
Does this work now given 1b6efc7ab297b7b8aea4d7cb0b52fb589392042b ?

**Comment by JeffBezanson** [comment]
It works only if just the name changes; we don't have a way to deprecate given combinations of type parameters.

**Comment by ViralBShah** [comment]
@JeffBezanson Should we close this?

**Comment by JeffBezanson** [comment]
We don't have this feature, but it's also pretty hard to implement and I have no immediate plans to do it.
