### ISSUE TITLE
Shared array example needs fixing 

### ISSUE THREAD

**Issue by mbeltagy** [JuliaLang/julia#9841]
In https://github.com/JuliaLang/julia/blob/master/doc/manual/parallel-computing.rst

The example provided 
```julia
S = SharedArray(Int, (3,4), init = S -> S[myid()-1:nworkers():length(S)] = myid())
```
produces an exception in 0.3.5
```
exception on 1: ERROR: BoundsError()
 in setindex! at array.jl:323
 in setindex! at sharedarray.jl:215
 in anonymous at none:1
 in anonymous at multi.jl:660
 in run_work_thunk at multi.jl:621
 in run_work_thunk at multi.jl:630
 in anonymous at task.jl:6
```

It seems that in the latest implementation myid() could start at 1 and hence a bounds error happens. 
This could be a possible fix. 
```julia
 S = SharedArray(Int, (3,4), init = S -> S[myid():nworkers():length(S)] = myid())
```

**Comment by ViralBShah** [comment]
Cc: @amitmurthy

**Comment by amitmurthy** [comment]
Thanks @mbeltagy . Fixed in master, should be backported in the next 0.3 release.
