### ISSUE TITLE
building julia from source fails on mac

### ISSUE THREAD

**Issue by sononix** [JuliaLang/julia#9842]
I had previous install a julia 4.0-dev about 6 months ago and decided to update to the latest on github today 

I remember previously I had issues with a gfortran install and had to update to 4.9.1 .... I had thought gcc was also 4.9.1 but now that I check I see its version is 4.2.1

well when I run make on the julia repository on github I get this error

zblat3.f:1447:0: warning: 'REALPART_EXPR <bets>' may be used uninitialized in this function [-Wmaybe-uninitialized]
ld: library not found for -lcrt1.10.6.o
collect2: error: ld returned 1 exit status
make[4]: *** [sblat1] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [tests] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[2]: *** [openblas-v0.2.13/libopenblas.dylib] Error 1
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2

any suggestions other than > make -C deps clean-openblas and make OPENBLAS_USE_THREAD=0 as I have already tried these
tks
M

**Comment by tkelman** [comment]
run `xcode-select --install`, it looks like you've upgraded OSX

**Comment by sononix** [comment]
updated xcode - and re-ran make on the julia folder 

ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[4]: *** [libopenblasp-r0.2.13.dylib] Error 1
make[3]: *** [shared] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[2]: *** [openblas-v0.2.13/libopenblas.dylib] Error 1
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2

**Comment by tkelman** [comment]
Could you post the entire message, not just the end? (try gist.github.com and then post a link here) Where is your `gfortran` from? Is it updated?

**Comment by sononix** [comment]
the entire message is pretty large -

Ive restablish symlink to gcc-4.9 
make clean 
make

the entire terminal output is 
 https://gist.github.com/sononix/3b9f4995c27c434a998e

**Comment by sononix** [comment]
gfortran in /usr/local/bin

$ gfortran -v
gfortran: warning: couldn't understand kern.osversion '14.0.0
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc49/4.9.1/libexec/gcc/x86_64-apple-darwin13.3.0/4.9.1/lto-wrapper
Target: x86_64-apple-darwin13.3.0
Configured with: ../configure --build=x86_64-apple-darwin13.3.0 --prefix=/usr/local/Cellar/gcc49/4.9.1 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-gmp=/usr/local/opt/gmp4 --with-mpfr=/usr/local/opt/mpfr2 --with-mpc=/usr/local/opt/libmpc08 --with-cloog=/usr/local/opt/cloog018 --with-isl=/usr/local/opt/isl011 --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc49 4.9.1 --enable-fortran' --with-bugurl=https://github.com/Homebrew/homebrew-versions/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 4.9.1 (Homebrew gcc49 4.9.1 --enable-fortran)

**Comment by tkelman** [comment]
I think the main Homebrew gcc is on 4.9 right now, so you might be better off using it instead of homebrew-versions.

But that error is a new one. Try `make cleanall && make -C deps distclean-openblas distclean-suitesparse distclean-arpack`

**Comment by sononix** [comment]
if I run 

brew update
brew tap staticfloat/julia
brew install julia

I get julia but its version 3.5 any chance of getting version 4

**Comment by tkelman** [comment]
try `brew install --HEAD julia`

**Comment by sononix** [comment]
much appreciated - tks Tony
