### ISSUE TITLE
atsign-simd borks multidimensional iterators

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#9858]
It would be lovely to be able to turn on vectorization with our new multidimensional iterators, but currently there are some issues. Here's a demo of the challenges:
```julia
# Vectorizes nicely
function f1(A)
    s = 0.0
    for j = 1:size(A,2)
        @simd for i = 1:size(A,1)
            @inbounds s += A[i,j]
        end
    end
    s
end

# Doesn't vectorize because @simd is on the outer loop
# Not a problem in and of itself, but worth noting when one is thinking about multidimensional iterators
function f2(A)
    s = 0.0
    @simd for j = 1:size(A,2)
        for i = 1:size(A,1)
            @inbounds s += A[i,j]
        end
    end
    s
end

# Gives an error
function f3_broken(A)
    s = 0.0
    @simd for I in eachindex(A)
        @inbounds s += A[I]
    end
    s
end

# Works, but not vectorized
function f3(A)
    s = 0.0
    for I in eachindex(A)
        @inbounds s += A[I]
    end
    s
end
```
The error from `f3_broken` is
```
ERROR: MethodError: `step` has no method matching step(::Base.IteratorsMD.CartesianRange{Base.IteratorsMD.CartesianIndex_2})
 in f3_broken at none:54
```

CC @ArchRobison, to ask whether there's a good way to achieve this. In case you haven't followed these iterators, they're defined in the `IteratorsMD` module at the top of `multidimensional.jl`. Conceptually, they are equivalent to using a tuple to encode the state, and iterate like this: `(1,1), (2,1), ..., (m, 1), (1, 2), (2, 2), ...`.

**Comment by ArchRobison** [comment]
Thanks for the examples.  The use of `@simd` in `f2` means that the outer loop has no cross-iteration dependencies, but the inner loop might have such dependencies.  The Intel compiler can handle that kind of vectorization in some cases, but currently LLVM cannot.  

`f3_broken` is an entirely reasonable thing to write.  I'll ponder how to generalize `@simd` to cover it.

**Comment by Jutho** [comment]
Not sure if this is the right place, but on a related note, is it possible to apply simd to speed up the integer additions involved with adding two `CartesianIndex{N}` objects (see [here](https://github.com/JuliaLang/julia/blob/4c6a3d2034b9638205dc26d0f54e5d30387152e1/base/multidimensional.jl#L65) for the definition). Does LLVM automatically recognize this? I have reported some timings [here](https://groups.google.com/forum/?fromgroups=#!topic/julia-dev/o4BZqLcTorg) for adding `CartesianIndex{M}` objects for `M=1,...,8` and compared to normal `Int` addition. Due to the loop counter, there are `M+1` `Int` additions going on in every iteration. The timings do scale more favorably than just linear in `M+1` (up to `M<8` where it breaks down due to the issue discussed in that post), but to a non-expert like myself, there is no clear sign of some simd vectorization at work.

**Comment by ArchRobison** [comment]
With regard to the general problem.  We have to live with LLVM's simple vectorizer, which wants to see a dumb-simple inner loop with obviously unit-stride accesses.  We could feed it that by making `@simd for` expand a loop into *two* for loops: 
* an outer one that handles all dimensions except the innermost one.  For 1D loops, it would be a one-trip dummy loop that the LLVM optimizer will remove.
* an dumb simple inner loop that caters to the vectorizer.

That's how an expert programmer would partition the original loop, unless there was a loop-collapse or loop-interchange opportunity.

This approach seems straightforward to implement.  Given:
```
@simd for i in r
    ...
```
the macro would expand the loop into the equivalent of the following:
```
for j in simd_outer_range(r)
      for k=0:simd_inner_length(r)-1   # Hang simdloop marker on this loop
           i = simd_index(r,j,k)               # Build user-level index from the two loop indices
           ...
      end
end
```
We just have to make sure that `simd_index(r,j,k)` is inlined and is the sum of a loop-invariant expression (in terms of r and j) and linear part `k`, so the compiler can pick it apart, hoist the loop-invariant portion, and see that the remaining part has unit stride when it does.

The defaults for the `simd_`... functions, for sake of backwards compatibility, would be:
* simd_outer_range(r) = 1:1
* simd_inner_length(r) = length(r)
* simd_index(r,j,k) = first(r)+k*step(r)
Or maybe these should be restricted to `r::OrginalRange`.

`multidimensional.jl` could define its own overloads of the three functions above.

**Comment by ArchRobison** [comment]
@Jutho: It's mostly separate from `@simd`. The root problem is that LLVM can express vector operations on its vector datatypes, but not on struct datatypes that are bitwise identical to those types.    [Here](https://gist.github.com/ArchRobison/a340bc43c8fabb02e739) is code-gen for one of your examples.  Bitcasting to/from aggregate types is also prohibited, which rules out the obvious work-around.  The best work-around I can come up with is to store the struct into memory and then reload it as an LLVM vector (before the loop), and then do the reverse at the end of the loop.  

A big motivating case is complex numbers, though that's in principle an easier case since instances of `complex{T}` are immutable, and thus could be mapped easily onto an LLVM vector data type.  I forget if there's a layout-compatibility issue with C that stops us from doing that.

**Comment by timholy** [comment]
That sounds like a good strategy. If I understand you correctly, this doesn't require any low-level changes to julia's SIMD handling, just a mutation of the user-written loop.

In a brief test, it looks like LLVM optimizes away `for j = 1:1`, which means there would be no penalty for simple loops.
```julia
julia> function f(x)
           s = 0.0
           for j = 1:1
               for k = 1:length(x)
                   @inbounds s += x[k]
               end
           end
           s
       end
f (generic function with 1 method)

julia> function g(x)
           s = 0.0
           for k = 1:length(x)
               @inbounds s += x[k]
           end
           s
       end
g (generic function with 1 method)

julia> x = rand(3);

julia> @code_llvm f(x)

define double @julia_f_45227(%jl_value_t*) {
top:
  %1 = getelementptr inbounds %jl_value_t* %0, i64 2, !dbg !958
  %2 = bitcast %jl_value_t* %1 to i64*, !dbg !958
  %3 = load i64* %2, align 8, !dbg !958, !tbaa %jtbaa_arraylen
  %4 = icmp sgt i64 %3, 0, !dbg !958
  br i1 %4, label %L2.preheader.us, label %L7

L2.preheader.us:                                  ; preds = %top
  %5 = getelementptr inbounds %jl_value_t* %0, i64 1, !dbg !963
  %6 = bitcast %jl_value_t* %5 to i8**, !dbg !963
  %.op = add i64 %3, 1, !dbg !963
  %7 = select i1 %4, i64 %.op, i64 1, !dbg !963
  %8 = load i8** %6, align 8, !dbg !963, !tbaa %jtbaa_arrayptr
  %9 = bitcast i8* %8 to double*, !dbg !963
  br label %L2.us, !dbg !958

L2.us:                                            ; preds = %L2.us, %L2.preheader.us
  %"#s6.0.us" = phi i64 [ %10, %L2.us ], [ 1, %L2.preheader.us ]
  %s.1.us = phi double [ %14, %L2.us ], [ 0.000000e+00, %L2.preheader.us ]
  %10 = add i64 %"#s6.0.us", 1, !dbg !958
  %11 = add i64 %"#s6.0.us", -1, !dbg !963
  %12 = getelementptr double* %9, i64 %11, !dbg !963
  %13 = load double* %12, align 8, !dbg !963, !tbaa %jtbaa_user
  %14 = fadd double %s.1.us, %13, !dbg !963
  %15 = icmp eq i64 %10, %7, !dbg !963
  br i1 %15, label %L7, label %L2.us, !dbg !963

L7:                                               ; preds = %top, %L2.us
  %s.2.lcssa = phi double [ %14, %L2.us ], [ 0.000000e+00, %top ]
  ret double %s.2.lcssa, !dbg !966
}

julia> @code_llvm g(x)

define double @julia_g_45228(%jl_value_t*) {
top:
  %1 = getelementptr inbounds %jl_value_t* %0, i64 2, !dbg !961
  %2 = bitcast %jl_value_t* %1 to i64*, !dbg !961
  %3 = load i64* %2, align 8, !dbg !961, !tbaa %jtbaa_arraylen
  %4 = icmp sgt i64 %3, 0, !dbg !961
  br i1 %4, label %L.preheader, label %L3, !dbg !961

L.preheader:                                      ; preds = %top
  %5 = getelementptr inbounds %jl_value_t* %0, i64 1, !dbg !966
  %6 = bitcast %jl_value_t* %5 to i8**, !dbg !966
  %7 = load i8** %6, align 8, !dbg !966, !tbaa %jtbaa_arrayptr
  %8 = bitcast i8* %7 to double*, !dbg !966
  br label %L, !dbg !961

L:                                                ; preds = %L.preheader, %L
  %"#s17.0" = phi i64 [ %9, %L ], [ 1, %L.preheader ]
  %s.0 = phi double [ %13, %L ], [ 0.000000e+00, %L.preheader ]
  %9 = add i64 %"#s17.0", 1, !dbg !961
  %10 = add i64 %"#s17.0", -1, !dbg !966
  %11 = getelementptr double* %8, i64 %10, !dbg !966
  %12 = load double* %11, align 8, !dbg !966, !tbaa %jtbaa_user
  %13 = fadd double %s.0, %12, !dbg !966
  %14 = icmp eq i64 %"#s17.0", %3, !dbg !966
  br i1 %14, label %L3, label %L, !dbg !966

L3:                                               ; preds = %L, %top
  %s.1 = phi double [ 0.000000e+00, %top ], [ %13, %L ]
  ret double %s.1, !dbg !969
}
```

**Comment by ArchRobison** [comment]
I'll try prototyping this and send a PR for us to experiment with.  It looks like the change to `base/simdloop.jl` is fairly small.  

I edited my design note to add `j` as a parameter to `simd_inner_length`, so that the scheme generalizes to triangular/ragged index spaces.
