### ISSUE TITLE
Replace `LLVM_34` and friends by `LLVM_VERSION`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#9860]
Julia's LLVM interface code contains many constructs of the kind
```
#ifdef LLVM33
            #define LLVM_FP(a,b) APFloat(a,b)
#else
            #define LLVM_FP(a,b) APFloat(b,true)
#endif
```
which handle the API changes in LLVM between different versions. The macros `LLVM33` have a somewhat counter-intuitive meaning in that they mean "version x OR LATER". In the case above, the `#else` branch thus only triggers for LLVM 3.2 and earlier. This is confusing.

I suggest to replace the various `LLVM*` macros by a single macro `LLVM_VERSION, and check this explicitly, as in `#if LLVM_VERSION >= 34` (or similar). This is easier to understand, and also reduces the number of macros that need to be defined.

Alternatively, we can rename `LLVM33` etc. to `LLVM33_OR_LATER` etc.

**Comment by sjkelly** [comment]
> I suggest to replace the various LLVM* macros by a single macro LLVM_VERSION, and check this explicitly, as in#if LLVM_VERSION >= 34` (or similar). This is easier to understand, and also reduces the number of macros that need to be defined.

+1 I was confused by this when reading the codegen code as well.

**Comment by jakebolewski** [comment]
I forgot this changed somewhat recently.  +1 for a more explicit check.
