### ISSUE TITLE
Is `edit(::Callable)` broken on v0.4?

### ISSUE THREAD

**Issue by Sean1708** [JuliaLang/julia#9866]
I noticed the following behaviour on the master branch from 7 days ago, but it's also present on the current master.

``` julia
julia> versioninfo()
Julia Version 0.4.0-dev+2833
Commit 5c5bf9d (2015-01-20 23:10 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> edit(length)  # doesn't work
ERROR: no method found for the specified argument types
 in which at reflection.jl:178
 in edit at interactiveutil.jl:55

julia> edit(edit)  # :(
ERROR: no method found for the specified argument types
 in which at reflection.jl:178
 in edit at interactiveutil.jl:55

julia> edit(length, (AbstractArray,))  # works if you supply the types

julia> edit(length, (AbstractVector,))  # and the type doesn't have to be exact
```

On v0.3, however

``` julia
julia> versioninfo()
Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> edit(length)  # works fine

julia> edit(edit)  # also works fine
```

Running `edit(which, (Function, Any...))` takes me to [this](https://github.com/JuliaLang/julia/blob/5c5bf9d68296d10b1ccbd1eddcc3c4d8d32763f5/base/deprecated.jl#L9) line suggesting that the issue might be related to the [deprecation](https://github.com/JuliaLang/julia/blob/5c5bf9d68296d10b1ccbd1eddcc3c4d8d32763f5/base/deprecated.jl#L167) of `which(f, args...)`.

Possibly also related to #9471 or #9536?

**Comment by mbauman** [comment]
I noticed this, too. I have the following in my .juliarc.jl, but haven't submitted it since I'm not sure it's the right solution here:

```julia
Base.functionloc(f::Base.Callable) = (m = methods(f); isempty(m) ? error("no methods for $f found") : functionloc(first(m)))
```

**Comment by Sean1708** [comment]
Awesome thanks, for most of my use-cases the methods are in the same file so this is good enough for me.

**Comment by JeffBezanson** [comment]
Yes, we used to use the most specific matching method here. However that is really quite arbitrary. In the version of julia I happen to be looking at now, `edit(length)` would take you to `length(mt::MethodTable) at reflection.jl:133`. I don't think that's useful.

However you can get that behavior with `edit(methods(length, (Any...))[1])`.

We should remove the default value for the type argument to `functionloc`, and instead make `functionloc(f)` only work if `f` has one definition.
