### ISSUE TITLE
Pkg.update() fails 

### ISSUE THREAD

**Issue by sononix** [JuliaLang/julia#9879]
julia> Pkg.update()
INFO: Updating METADATA...
error: Your local changes to the following files would be overwritten by merge:
	HDF5/versions/0.4.10/requires
Please, commit your changes or stash them before you can merge.
Aborting
ERROR: failed process: Process(`git pull -q`, ProcessExited(1)) [1]
 in error at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in pipeline_error at process.jl:502
 in run at pkg/git.jl:22
 in anonymous at pkg/entry.jl:250
 in with_env at env.jl:177
 in anonymous at pkg/entry.jl:249
 in cd at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in update at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:28
 in cd at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in cd at pkg/dir.jl:28
 in update at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib

julia> versioninfo()
Julia Version 0.4.0-dev+2849
Commit 3743969* (2015-01-21 22:50 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by tkelman** [comment]
Did you make a local change to that file? Or is this some strange consequence of https://github.com/JuliaLang/METADATA.jl/pull/2015 ?

If you go to `~/.julia/v0.4/METADATA`, run `git status` and `git diff`, what do you see?

**Comment by sononix** [comment]
no changes to the local files have been trying to install julia from github and using brew for some reason I getting errors when trying to run packages 

so Im not even sure which one I have running atm - 

git status - ends up something like this

https://gist.github.com/sononix/db201c2c7ec58093c54d

**Comment by tkelman** [comment]
And `git diff`? That looks like almost every file under METADATA has been modified somehow.

**Comment by sononix** [comment]
In the end I deleted in the ~/.julia file and ran Pkg.update() again  - tks
