### ISSUE TITLE
Data structures for LLVM IR

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#9885]
As mentioned in https://github.com/JuliaLang/julia/pull/9840#issuecomment-71090984, would make a good up-for-grabs project. These could be output by `code_llvm`, input into `llvmcall`, manipulated or generated by Julia code, etc.

Could maybe even extend to assembly data structures for `code_native` (a la PeachPy https://bitbucket.org/MDukhan/peachpy), but doing just LLVM IR first would be more self-contained.

**Comment by ihnorton** [comment]
https://github.com/jakebolewski/LLVM.jl?

**Comment by tkelman** [comment]
Yeah, pretty much, how long has that been there?

**Comment by JeffBezanson** [comment]
I think the only realistic way to do this is via cxx.jl, and accessing the actual LLVM data structures. The LLVM class hierarchy is *enormously* complex.

**Comment by StefanKarpinski** [comment]
But the LLVM language is far less complex and we could expose a representation of *that*.

**Comment by tkelman** [comment]
Right - what LLVM.jl appears to be trying to do, connecting to the entire compiler infrastructure and internal code structure, is more than I had in mind here. An IR representation could easily be out in a package, but if it's small and useful, then it would be worth hooking up to the couple of places in Base where we currently work with IR as strings.
