### ISSUE TITLE
Exporting undefined symbol from a module should be an error

### ISSUE THREAD

**Issue by aviks** [JuliaLang/julia#9886]
Or maybe `TAB`-completion should not show undefined, but exported, symbols. It is confusing to tab-complete a name, but then see it come up as undefined. 

```julia
julia> module A
         export x
         y() = "this is y"
       end

julia> A.<TAB>
eval x     y
julia> A.x
ERROR: UndefVarError: x not defined

julia> using A

julia> 
```

**Comment by JeffBezanson** [comment]
If a module has a lazily-initialized global variable, it might reasonably be undefined for a while. I'm not sure it's much less confusing for an exported variable to first be hidden, then at some later point appear in the tab completion list.

**Comment by JeffBezanson** [comment]
@StefanKarpinski what do you think? I'm inclined to just leave it, since we generally are ok with lazily-initialized globals.

**Comment by StefanKarpinski** [comment]
Yeah, I'm ok with the current behavior. When a module exists in a broken state like this, this behavior seems acceptable. Clearly the binding is supposed to exist, so completing it doesn't seem crazy.

**Comment by StefanKarpinski** [comment]
For some reason this discussion focused entirely on the tab completion behavior which seems like a side show, whereas the real issue seems to be best addressed by the title, not the example: should it be an error for `x` to be undefined when the module is closed? The only justifiable exception I can think of is if it were defined in an `__init__` function.

**Comment by cpf-work** [comment]
This is a rather old discussion, nevertheless I stumbled accross this issue now multiple times. I developed code then realised I have to change naming of something in a module but forgot to change the name in the export.
It is not a big issue and there might be reasons why it is like it is. However I would find it "natural" that exporting something which is not defined in a module throws an error.
