### ISSUE TITLE
IOBuffer of SubString

### ISSUE THREAD

**Issue by hayd** [JuliaLang/julia#9888]
It seems like this might be useful to define, for example if you don't know whether the type is a string or a substring.

I had a go implemented with the following in this [commit](https://github.com/hayd/julia/commit/8cd5310a5ec5287ff4ce26598a0a42e55689d613):
```
IOBuffer(s::SubString) = IOBuffer(s.string.data[s.offset:s.endof], true, false)
```
however, that seems not to work. :(

**Comment by ivarne** [comment]
How doesn't it work?

**Comment by hayd** [comment]
@ivarne great question, I will try and come up with a simple example (was hoping it was somethng obvious).

The bug was with unicode in markdown tables with the above definition (from the commit).

**Comment by ivarne** [comment]
Looking at how the `.endof` and `.offset` fields are used leads me to think that 
```julia
IOBuffer(s::SubString) = IOBuffer(s.string.data[(s.offset:(s.offset+s.endof)) - 1], true, false)
```
will work much better.

**Comment by stevengj** [comment]
That seems suboptimal because it is creating a copy of the data (at least until #9150 lands).

**Comment by ivarne** [comment]
I just thought `IOBuffer` needed a real `Array`, but if it can work directly with a `SubArray`, it might be worth it.

**Comment by stevengj** [comment]
It looks like the code would work with any `AbstractVector` supporting `pointer` and `stride` where the stride is 1 (i.e. contiguous).  This should include contiguous subarrays, although I'm not sure what methods are defined for `SubArray` as I haven't used that type much.

**Comment by vtjnash** [comment]
i think we can make IOBuffer parameterized by the type of the AbstractVector{Uint8} that it contains, rather than forcing Vector{Uint8}. that would also allow it to wrap a SharedArray too.

**Comment by JeffBezanson** [comment]
Doesn't IOBuffer kind of need to own the vector it wraps? I guess a read-only or non-growable IOBuffer on a SubArray would be ok though.

**Comment by stevengj** [comment]
@JeffBezanson, in the `IOBuffer(::String)` case the buffer is read-only.

**Comment by vtjnash** [comment]
right. when creating a IOBuffer from an existing object, it should typically default to read-only

**Comment by vtjnash** [comment]
this was implemented in https://github.com/JuliaLang/julia/pull/11554
