### ISSUE TITLE
Julia's emacs mode should use SMIE for more structured editing features

### ISSUE THREAD

**Issue by ikirill** [JuliaLang/julia#9889]
Octave-mode uses it, and it offers some nice features:

- When use place point on an "end", the corresponding block beginning (e.g., "if") is highlighted like a matching parenthesis.
- When you do forward-sexp starting at an expression (e.g., if...end), it understands enough to skip the entire expression, like it should, not just the next symbol.
- You can also easily select/delete/copy entire expressions, e.g., whole loops/blocks/function definitions.
- Things like outline/hide-show modes will work better, too, probably.

Would there be any interest in this?

**Comment by PythonNut** [comment]
It also allows you to guess the style of the code with `smie-config-guess`.

**Comment by yuyichao** [comment]
Moved to https://github.com/JuliaLang/julia-emacs/issues/6
