### ISSUE TITLE
Evanescent inference error in complicated type with nested parameters

### ISSUE THREAD

**Issue by daanhb** [JuliaLang/julia#9893]
I was exploring the extension of the idea of inlineable Functors in NumericFuns to multivariate and composite functions. This leads to very complicated types very quickly. In the code below, the final statement leads to an error from inference.jl, but running the exact same statement again yields the correct result. This behaviour looks like #7049. I get the error in Julia 0.3.5, and in a recent 0.4 (julia-fc61385c7c).

I simplified the code, but failed to narrow it down to a small abstract problem, so it is still rather long. A comment for readability: the goal is that g = f(x)+f(x) results in g(x) being a function of x, but h = f(x)+f(y) results in a function h(x,y) of x and y. Everything is a type. (I'm not convinced that this is a good idea, but at least I found an issue that can be fixed.)

First the type definitions:

```
# Fun is a function of one variable, defined by overloading call.
immutable Fun
end
call(f::Fun, x) = x

# CompositeFun is just the sum of two functions
immutable CompositeFun{F1,F2}
    f :: F1
    g :: F2
end
call(cf::CompositeFun, x...) = call(cf.f, x...) + call(cf.g, x...)

# Variables are types and S is intended to be a symbol, e.g. :x
immutable Variable{S}
end

# This constructor is not typesafe, but convenient
Variable(s::Symbol) = Variable{s}()

# BoundFun bounds a function of several arguments to named variables.
# VARS is intended to be a tuple of Variable{S}'s
immutable BoundFun{F,VARS}
    f :: F
    vars :: VARS
end
call(bf::BoundFun, x...) = call(bf.f, x...)
call(f::Fun, x::Variable) = BoundFun(f,(x,))

# We want f(x) + g(y) to result in h(x,y). An intermediate step is to 'promote'
# f(x) and g(y) to functions of two variables, such as p(x,y) = f(x).
# IDX is a tuple. It enumerates indices of the variables of p that should be passed on to f.
immutable PromotedFun{F,IDX}
    f :: F
end

# Again, constructor is not typesafe
PromotedFun{F}(f::F, idx) = PromotedFun{F,idx}(f)

call{F,IDX}(pf::PromotedFun{F,IDX}, x...) = call(pf.f, map(t -> x[t], IDX)...)

# Side comment: the calling function above will not be inlined when the function is
# passed as a parameter. Maybe because of the map in the definition.
# More specialized implementations do work, such as:
call{F,IDX1}(pf::PromotedFun{F,(IDX1,)}, x...) = call(pf.f, x[IDX1])
```

Adding two functions uses promotion of univariate functions to multivariate functions:
```
(+)(f::BoundFun, g::BoundFun) = (+)(promote(f,g)...)
(+){F1,F2,VARS}(f::BoundFun{F1,VARS}, g::BoundFun{F2,VARS}) = BoundFun(CompositeFun(f.f, g.f), f.vars)

promote{F1,F2,VARS}(f::BoundFun{F1,VARS}, g::BoundFun{F2,VARS}) = (f,g)

function promote{F1,F2,VARS1,VARS2}(f::BoundFun{F1,VARS1}, g::BoundFun{F2,VARS2})
    # ugly implementation because I don't know any better
    vars_array = union(f.vars,g.vars)
    vars_tuple = tuple(vars_array...)

    idx1 = tuple(indexin([f.vars...], vars_array)...)
    idx2 = tuple(indexin([g.vars...], vars_array)...)
    
    fp = PromotedFun(f.f, idx1)
    gp = PromotedFun(g.f, idx2)

    (BoundFun(fp, vars_tuple), BoundFun(gp, vars_tuple))
end
```
Adding functions seems to work, but we hit an error when trying to evaluate a function that is the sum of three functions.
```
x = Variable(:x)
y = Variable(:y)
z = Variable(:z)

f = Fun()

g = call(f, x) + call(f, x)    # g is a function of one variable, fine
call(g,1)

h = call(f, x) + call(f, y)    # h is a function of two variables, still fine
call(h, 1, 2)

# the type of p is ridiculous - indication that this is not the way to go :-)
p = call(f, x) + call(f, y) + call(f, z) 

call(p, 1, 2, 3)
```

For me, that final statement the first time I run it results in:
```
type: TypeVar: expected Type{T<:Top}, got (Int64,)
while loading In[14], in expression starting on line 1

 in limit_type_depth at ./inference.jl:316
 in anonymous at ./inference.jl:304
 in map at ./tuple.jl:47
 in limit_type_depth at ./inference.jl:304
 in anonymous at ./inference.jl:304
 in map at ./tuple.jl:47
 in limit_type_depth at ./inference.jl:304
 in anonymous at ./inference.jl:304
 in map at ./tuple.jl:47
 in limit_type_depth at ./inference.jl:304
 in anonymous at ./inference.jl:304
 in map at ./tuple.jl:47
 in limit_type_depth at ./inference.jl:304
 in anonymous at ./inference.jl:382
 in builtin_tfunction at ./inference.jl:541
 in abstract_call at ./inference.jl:860
 in abstract_eval_call at ./inference.jl:903
 in abstract_eval at ./inference.jl:935
 in abstract_eval_arg at ./inference.jl:866
 in abstract_eval_call at ./inference.jl:878
 in abstract_eval at ./inference.jl:935
 in abstract_eval_arg at ./inference.jl:866
 in abstract_eval_call at ./inference.jl:878
 in abstract_eval at ./inference.jl:935
 in abstract_eval_arg at ./inference.jl:866
 in typeinf at ./inference.jl:1472
 in typeinf_ext at ./inference.jl:1216
```

Calling p a second time with the same parameter yields 6 (=1+2+3), like it should.

Given that a function called limit_type_depth is invoked, I can imagine that the type of p breaks some limit. I could live with that, but it is still strange that the second invocation of the statement does work, so maybe something else is going on?

**Comment by StefanKarpinski** [comment]
> Evanescent inference error (in complicated type with nested parameters)

Jeff's new band name?

**Comment by daanhb** [comment]
No, I'm pretty sure that band exists already, think I heard it on the radio

**Comment by daanhb** [comment]
Okay, here is a (much) simpler code that triggers the same problem. 
````
immutable TypeA{T,I}
    t :: T
end

TypeA{T}(t::T,i) = TypeA{T,i}(t)

call{T,I}(a::TypeA{T,I}, x) = call(a.t, x[I[1]])

call(a::Int, x) = a*x

# define some variables
t1 = TypeA(3,(1,))
t2 = TypeA(t1,(1,))
t3 = TypeA(t2,(1,))
t4 = TypeA(t3,(1,))
t5 = TypeA(t4,(1,))
t6 = TypeA(t5,(1,))
t7 = TypeA(t6,(1,))
t8 = TypeA(t7,(1,))
````
These definitions and declarations all work. The transient error occurs when trying to invoke the function call on any of the tX variables, and it goes wrong starting with t5. For example, you have to run the statement
```
call(t5, 2)
```
twice before you get the right answer 6. If instead after the above definitions you try to call t6, it takes three times to get the right answer. For t7 it is four times, for t8 five times, all after restarting Julia.

**Comment by daanhb** [comment]
I have occasionally checked back and continued to see this bug, until today. It had something to do with tuples as parameters of nested types (the tuple parameter in the minimal examples was essential) and it was probably fixed with the tuple overhaul. As far as I'm concerned, this issue can be closed.
