### ISSUE TITLE
Improve code generation for C function calls

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#9894]
LLVM generates strange code for function calls. For example:

```
julia> code_native(sin, (Float64,))
    .section    __TEXT,__text,regular,pure_instructions
Filename: math.jl
Source line: 123
    push    RBP
    mov RBP, RSP
    sub RSP, 16
    vmovsd  QWORD PTR [RBP - 8], XMM0
    movabs  RAX, sin
Source line: 123
    call    RAX
    vucomisd    XMM0, XMM0
    jp  L41
L35:    add RSP, 16
    pop RBP
    ret
L41:    vmovsd  XMM1, QWORD PTR [RBP - 8]
    vucomisd    XMM1, XMM1
    jp  L35
    movabs  RAX, jl_domain_exception
    mov RDI, QWORD PTR [RAX]
    movabs  RAX, jl_throw_with_superfluous_argument
    mov ESI, 123
    call    RAX
```

Here, the two lines

```
    movabs  RAX, sin
    call    RAX
```

first load the address of the `sin` function into the `rax` register, and then perform an indirect call. This could be simplified to a single line

```
    call    sin
```

which would be shorter and faster.

I conjecture that LLVM does not know, at code generation time, that the distance between the `call` instruction and the `sin` function fits into 32 bits, and thus cannot use the simpler form.

**Comment by vtjnash** [comment]
`sin` is no longer a function call
