### ISSUE TITLE
AppVeyor broken?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#9899]
Twice in a row, AppVeyor reported errors without actually trying to build anything. See e.g. #9898. The error message is only "An error occurred while executing the command definition. See the inner exception for details.", the log file is empty.

**Comment by tkelman** [comment]
Dunno. cc @FeodorFitsner

**Comment by FeodorFitsner** [comment]
Will take a look.

-Feodor

**Comment by tkelman** [comment]
Thanks!

**Comment by FeodorFitsner** [comment]
Kick off a new build - should be OK now.

**Comment by FeodorFitsner** [comment]
Looks like build number counter was stuck due to some racing condition. Will take a look.

**Comment by tkelman** [comment]
Looks pretty much fixed now, thanks as always for the impressively rapid response.
