### ISSUE TITLE
AppVeyor times out

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#9903]
I have AppVeyor time out for #9898 when running on one core. The multi-core run did not time out. The build was stuck in `osutils.jl` -- this always takes a long time.

**Comment by staticfloat** [comment]
We are aware of appveyor issues.  If you'd like us to restart a build for you, just comment on the issue in particular and we can deal with it there.

**Comment by tkelman** [comment]
This may be related to the long-standing #7942, but I'm not positive.

**Comment by vtjnash** [comment]
closing since this is not exactly actionable

**Comment by tkelman** [comment]
I've raised this with Feodor and he's watched a few cases where a build had hung, but it was hard to tell whether anything was obviously wrong. Would be nice to fix this at some point, if anyone can figure out what's causing it.
