### ISSUE TITLE
nd comprehension broken for `:`

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#9904]
the following expression hangs the julia syntax expander:
````
julia> f() = [ [1 2;3 4] for i=1:2, : ]
```

**Comment by JeffBezanson** [comment]
We never really decided whether this is a real feature or not.

**Comment by vtjnash** [comment]
yeah, Stefan seemed to be of the opinion that it should just be removed. it's doesn't appear to be documented.
