### ISSUE TITLE
'INFO: ...' in STDERR

### ISSUE THREAD

**Issue by HackerMD** [JuliaLang/julia#9907]
when Julia is called from Python via subprocess.Popen(), 'INFO: ...' ends up in standard error

**Comment by JeffBezanson** [comment]
We deliberately send output from `info()` to stderr. The idea is that these are informative side messages, and not part of a program's normal output, so they should go to stderr. Could you expand on why this is a problem? Are you seeing `INFO: ` messages that shouldn't be printed in the first place?

**Comment by HackerMD** [comment]
Thank you for your reply! I realized in the meanwhile that it should go there and that sending these kind of messages to stderr is common practice. It confused be because I thought that only 'error' messages would go there. My bad!
