### ISSUE TITLE
Algebraic calculation accuracy in relation to the arithmetic. The sample covariance.

### ISSUE THREAD

**Issue by paulanalyst** [JuliaLang/julia#9908]
Algebraic calculation accuracy in relation to the arithmetic. The sample covariance.

D=readcsv("v4dane.txt");
k,l=size(D);
file is here: https://drive.google.com/file/d/0B9xW5VtANWhDUzR3QjJ4dExyM0E/view?usp=sharing

computing cov algebraic way:
E=mean(D,1)
C=((D'*D-E'*E)/k).-E'*E

computing cov  by "cov"
c=cov(D,corrected=false)

computing cov  step by step
julia> sum((D[:,1].-sum(D[:,1])/k).^2)./k
417.62196506606745

julia> C[1,1]
417.6094319789106

julia> c[1,1]
417.6219650660668

C is loaded with big mistake I made.
Algebraic method is useful when you have large arrays when using the command cov is impossible. It looks like the BLAS introduces errors. How to get around this? Should be: 417.6219. Not 417.6094.
Paul

**Comment by johnmyleswhite** [comment]
This seems to be a problem with how floating point works vs. how you'd like it to work. Is this problem unique to Julia?

**Comment by paulanalyst** [comment]
sample from Octave seems yhe same problem:

> C=((D'*D-E'*E)/k).-E'*E
C =

   417.60943    28.39085    -0.34849     8.48988
    28.39085   268.63621    -3.79978    -1.82335
    -0.34849    -3.79978    80.45352    53.74892
     8.48988    -1.82335    53.74892   643.86833

>>

**Comment by jiahao** [comment]
This looks like floating-point roundoff error. If you need a very accurate result, try `c=cov(big(D),corrected=false)` (although it will be slower).

**Comment by andreasnoack** [comment]
I think you formula is wrong. It should either

julia> C1 = D'D/k - E'E

or

julia> C2 = (D - E) |> t -> t't/k

which gives

julia> C1[1]

417.6219650660677

julia> C2[1]

417.6219650660669

but using cov i better.

2015-01-24 11:59 GMT-05:00 paulanalyst <notifications@github.com>:

**Comment by paulanalyst** [comment]
Thx Andreas , 
C1 is ok
julia> sum((D[:,1].-sum(D[:,1])/k).^2)./k-C1[1]
-2.2737367544323206e-13
but I cant compute C2 way:

julia> C2 = (D - E) |> t -> t't/k
ERROR: dimensions must match
 in promote_shape at operators.jl:200

Paul

**Comment by andreasnoack** [comment]
I forgot a dot. I should be
```julia
julia> C2 = (D .- E) |> t -> t't/k
```

**Comment by andreasnoack** [comment]
...but again: use `cov`. Do you have an example where there is a substantial performance difference between `cov` and the method for `C1`?

**Comment by paulanalyst** [comment]
I prefer "cov"  but if a have matrix data with 3*10^4 cols I have no RAM for "cov". In this sytuaition I must use D'D/k - E'E.
Paul

**Comment by nalimilan** [comment]
You can compute the covariance between one column and each of the other columns with `cov(D[:, i], D)` or `cov(sub(D, :, i), D)`. Iterate over all columns, and you should get the same results possibly with a lower RAM usage.
