### ISSUE TITLE
`sizehint!(::Dict, n)` doesn't grow Dicts enough

### ISSUE THREAD

**Issue by garborg** [JuliaLang/julia#9909]
It seems like `sizehint!(d, n)` should grow `d` so that it could hold `n` pairs before rehashing and `resize!`ing its fields again. Currently `d` is only ready to hold `floor(n * 2/3)` pairs after resizing.

Other methods in Base use it assuming the the former behavior, and allocate more than they could. Simple change, but first, is there any any reason not make it?

**Comment by mlubin** [comment]
The current behavior seems bizarre.

**Comment by ivarne** [comment]
The relevant line is in [/base/dict.jl#L482](https://github.com/JuliaLang/julia/blob/08663d4bb05c5b8805a57f46f4feacb07c7f2564/base/dict.jl#L482)

**Comment by JeffBezanson** [comment]
Even more relevant: https://github.com/JuliaLang/julia/blob/08663d4bb05c5b8805a57f46f4feacb07c7f2564/base/dict.jl#L569

However, resizing behavior also depends on the number of collisions, so it is not really possible to guarantee holding `n` items without rehashing, unless we allow lookup performance to degrade all the way to `O(n)`.

**Comment by garborg** [comment]
I was thinking switching `function sizehint!(d::Dict, newsz)` to 
```julia
function sizehint!(d::Dict, newsz)
    newsz = ceil(Int, 1.5 * sz)
```
would be good enough.
It improves performance on any sizes I've tested and brings use (if not guarantee) in line with other `sizehint!` methods, at the cost of surface inconsistency with `rehash!`, but everything that uses the unexported `rehash!` is already reaching into `Dict` implementation and knows what `length`s it changes, and the name change above seems to clear up the surface inconsistency.

**Comment by JeffBezanson** [comment]
Ok, that's fine. I wonder if we can bring the max load factor up to 3/4 or 4/5 (and thus lower that constant to 1.33 or 1.25). It seems to me the collision chain length is much more important than the fraction of space used. After all an ideal table would be 100% full with no collisions!

**Comment by kshyatt** [comment]
Is this still a problem?

**Comment by garborg** [comment]
It looks both changes are still todos: making sizehint! aware of the load factor and either increasing the load factor or changing how to decide when to resize.

**Comment by StefanKarpinski** [comment]
I don't think that making the decision based on chain length is a good idea. Then anyone who can construct hash collisions can force the table to use O(2^n) memory by inserting O(n) items, which is just begging for a nasty DoS attack. The worst case if resizing is based on number of pairs inserted regardless of collision behavior is that some items are slow to look up and table size is proportional to the number of items inserted.

**Comment by StefanKarpinski** [comment]
Along that line of thinking, if you give a sizehint!, it should simply resize the dict storage so that if that many items are inserted, the table will have the necessary storage size.
