### ISSUE TITLE
unclear documentation on embedding

### ISSUE THREAD

**Issue by Ken-B** [JuliaLang/julia#9914]
The [C example](http://julia.readthedocs.org/en/latest/manual/embedding/#high-level-embedding) in the docs has these 2 initial steps:

    jl_init(NULL);
    jl_eval_string("print(sqrt(2.0))");

but right below the text talks about another step in between concerning tasks, which I don't see in the example: "The second statement initializes Julia’s task scheduling system".

Could someone clarify this? Thanks.

**Comment by vtjnash** [comment]
that statement should refer to `jl_init` itself now (until https://github.com/JuliaLang/julia/pull/9461is merged, and the statement becomes entirely unnecessary)

**Comment by Ken-B** [comment]
That section of the documentation seems to have been adapted, so I'll close this issue. Thanks.
