### ISSUE TITLE
Sparse matrix \ throws error and segfaults with symmetric RHS

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#9915]
```julia
julia> speye(2)\speye(2)
CHOLMOD error: B cannot be stored in symmetric mode

signal (11): Segmentation fault
call at sparse/cholmod.jl:452
solve at sparse/cholmod.jl:825
\ at sparse/cholmod.jl:878
A_ldiv_B! at sparse/cholmod.jl:870
jl_apply_generic at /usr/local/julia/usr/bin/../lib/libjulia.so (unknown line)
\ at linalg/generic.jl:241
jl_apply_generic at /usr/local/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 1224344712)
unknown function (ip: 1224342223)
unknown function (ip: 1224414669)
jl_toplevel_eval_in at /usr/local/julia/usr/bin/../lib/libjulia.so (unknown line)
eval_user_input at REPL.jl:54
jlcall_eval_user_input_223884 at  (unknown line)
jl_apply_generic at /usr/local/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at task.jl:83
unknown function (ip: 1224370721)
unknown function (ip: 0)
fish: Job 1, “julia” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by andreasnoack** [comment]
I'm working on a quite extensive overhaul of cholmod.jl so I'll try to include a fix for this to avoid other changes to the file while I'm working on it.

**Comment by andreasnoack** [comment]
Okay. I have found the bug and will fix it as part of the my overhaul.

**Comment by tkelman** [comment]
@andreasnoack please separate the bugfix from major changes. This bug is present on release-0.3 as well, and should be fixed there if at all possible.

**Comment by andreasnoack** [comment]
I'd like to avoid too many conflicts here, but the fix is so small that it shouldn't be an issue. I'll see if I can separate out the bug fix. For 0.3 it shouldn't be an issue as the other changes won't be back ported.

**Comment by tkelman** [comment]
If the bug fix will be a separate commit that can be cleanly backported, that's perfect and it doesn't matter too much whether or not it's in the same PR. Thanks, just wanted you to keep it in mind so the bugfix won't have to be dissected piecemeal out of a bigger commit.

**Comment by andreasnoack** [comment]
@JuliaBackports

**Comment by simonster** [comment]
Thanks!

**Comment by tkelman** [comment]
backported in 6e32fc73de1085acdfb04ec79558b117d8530c80
