### ISSUE TITLE
SubArray manipulations inconsistent in modifying original matrix

### ISSUE THREAD

**Issue by poulson** [JuliaLang/julia#9916]
I have started putting together notebooks for a numerical linear algebra course taught using Julia,
    http://nbviewer.ipython.org/github/poulson/ATiNLA/tree/master/
and there have been a surprising number of gotchas with respect to using "sub" to create SubArrays. Most have to do with the ambiguity of when a modification of a SubArray instance will modify the global matrix that the SubArray originally pointed to, or whether it will instead create a copy and modify the copy. 

For example, I recently observed ``ASub /= B``, where ``ASub`` is a SubArray and ``B`` is some square matrix, not modifying the SubArray in place, and instead modifying a copy.

**Comment by andreasnoack** [comment]
Great to hear that you'll use Julia for a linear algebra course.

Regarding your example, all of the operations `A op= B` are expanded to `A = A op B` and `A op B` will always allocate a new array. This has been discussed a couple of places, but https://github.com/JuliaLang/julia/issues/249 is probably the most relevant issue here. Right now in place array operations are done with `A_mul_B!`, `Ac_mul_B!`, `A_ldiv_B!`, `A_rdiv_B!` and so forth.

Please give more example of where you find the `SubArray` behavior unintuitive. We plan to return `SubArray`s from array indexing so they will be much more frequent in the future.

**Comment by poulson** [comment]
@andreasnoack Thanks for the pointer to that discussion; it would seem that it's currently best to avoid using the ``sub`` function explicitly within factorizations and instead keep around index sets for operations of the form ``A[ind2,ind2] -= A[ind2,ind1]*A[ind1,ind2]``. Am I correct in interpreting your statement as saying that, if the index sets are contiguous, this will soon become faster in Julia (due to returning a ``SubArray``)?

It also seems that ``diag`` is not supported for ``SubArray``.

**Comment by JeffBezanson** [comment]
@andreasnoack is right; the key point is that `a -= b` is *never* an in-place operation unless `a` is an indexing expression and not just a variable. You can use `A[:,:] = ...` to ensure `A` is modified. That will at least avoid the need to manually track which indexes to use.

We should make `diag` work for `SubArray`. It is currently defined for `Matrix` but as far as I can see that could be changed to `AbstractMatrix`. @andreasnoack any reason not to?

**Comment by andreasnoack** [comment]
Maybe I misunderstood you. If I understand your example correctly, it shouldn't be necessary to store the indexes. Instead you could use `[:,:]` to update the `SubArray`, e.g. by writing `Asub[:,:] /= B`.

`diag` will work very soon. Probably within minutes. I'm just waiting for the tests to finish.

**Comment by JeffBezanson** [comment]
:)

**Comment by poulson** [comment]
Wonderful, thanks for the fast replies! I ran into this issue much later than expected since many of the updates in symmetric-indefinite factorizations map awkwardly to BLAS. http://nbviewer.ipython.org/github/poulson/ATiNLA/blob/master/LDL.ipynb

**Comment by andreasnoack** [comment]
It should work now on master. I think we could consider a back port it to 0.3 because the change is only an extension of the signature of `diag` from `Matrix` to `AbstractMatrix` and it seems as an oversight because `diagind` was already defined for `AbstractMatrix`.

**Comment by tkelman** [comment]
> I think we could consider a back port it to 0.3

I'd let it run through PkgEvaluator just in case, but otherwise I agree.

**Comment by tkelman** [comment]
backported in 9670299bde9bcce6d7cd360bc91a62fc0afd20cb
