### ISSUE TITLE
Seg fault on OSX when dumping bit code

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/julia#9923]
I'm pretty clueless, so this may not really be a Julia issue, but I had the following problem:

julia> versioninfo()
Julia Version 0.4.0-dev+2898
Commit cbdaa0c (2015-01-25 10:34 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

From base, I try:

$ ../julia --build XX --dump-bitcode=yes --compile=all -J ../usr/lib/julia/sys0.ji -f sysimg.jl 
exports.jl
base.jl
reflection.jl
build_h.jl
version_git.jl
c.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
rounding.jl
float.jl
complex.jl
rational.jl
abstractarray.jl
subarray.jl
array.jl
subarray2.jl
functors.jl
bitarray.jl
intset.jl
dict.jl
set.jl
hashing.jl
iterator.jl
simdloop.jl
reduce.jl
inference.jl
osutils.jl
char.jl
ascii.jl
utf8.jl
utf16.jl
utf32.jl
iobuffer.jl
string.jl
utf8proc.jl
regex.jl
pcre.jl
base64.jl
io.jl
iostream.jl
libc.jl
env.jl
errno.jl
path.jl
intfuncs.jl
task.jl
show.jl
stream.jl
uv_constants.jl
socket.jl
stat.jl
fs.jl
process.jl
multimedia.jl
grisu.jl
file.jl
methodshow.jl
floatfuncs.jl
math.jl
float16.jl
cartesian.jl
multidimensional.jl
primes.jl
reducedim.jl
ordering.jl
collections.jl
sort.jl
combinatorics.jl
version.jl
gmp.jl
mpfr.jl
hashing2.jl
dSFMT.jl
random.jl
printf.jl
nullable.jl
serialize.jl
multi.jl
loading.jl
poll.jl
darray.jl
mmap.jl
sharedarray.jl
datafmt.jl
deepcopy.jl
interactiveutil.jl
replutil.jl
test.jl
meta.jl
i18n.jl
help.jl
Terminals.jl
LineEdit.jl
REPLCompletions.jl
REPL.jl
client.jl
markdown/Markdown.jl
docs.jl
util.jl
linalg.jl
broadcast.jl
sparse.jl
sparse/abstractsparse.jl
statistics.jl
fftw.jl
dsp.jl
sysinfo.jl
constants.jl
quadgk.jl
fastmath.jl
deprecated.jl
pkg.jl
graphics.jl
profile.jl
Dates.jl
basedocs.jl
precompile.jl

signal (11): Segmentation fault: 11
push_root at /Users/ericforgy/Code/julia/src/gc.c:1498
gc_push_root at /Users/ericforgy/Code/julia/src/gc.c:1623
jl_gc_collect at /Users/ericforgy/Code/julia/src/gc.c:2051
__pool_alloc at /Users/ericforgy/Code/julia/src/gc.c:971
_new_array_ at /Users/ericforgy/Code/julia/src/array.c:80
_new_array at /Users/ericforgy/Code/julia/src/array.c:365
ml_matches at /Users/ericforgy/Code/julia/src/gf.c:1946
_methods at reflection.jl:100
jlcall__methods_26156 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
_methods at reflection.jl:117
jlcall__methods_26156 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
_methods at reflection.jl:117
jlcall__methods_26156 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
_methods at reflection.jl:117
jlcall__methods_26156 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
inlineable at inference.jl:2125
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
inlining_pass at inference.jl:2723
inlining_pass at inference.jl:2657
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
inlining_pass at inference.jl:2617
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1597
jlcall_typeinf_26368 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf_ext at inference.jl:1243
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:488
jl_mt_assoc_by_type at /Users/ericforgy/Code/julia/src/gf.c:1005
jl_apply_generic at /Users/ericforgy/Code/julia/src/gf.c:1670
_sub at subarray.jl:85
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:505
func_for_method at inference.jl:625
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call_gf at inference.jl:701
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call at inference.jl:842
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_call at inference.jl:934
abstract_eval at inference.jl:959
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_arg at inference.jl:898
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1524
jlcall_typeinf_26368 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1249
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call_gf at inference.jl:729
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call at inference.jl:842
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_call at inference.jl:934
abstract_eval at inference.jl:959
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_arg at inference.jl:898
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1524
jlcall_typeinf_26368 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1249
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call_gf at inference.jl:729
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call at inference.jl:842
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_call at inference.jl:934
abstract_eval at inference.jl:959
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_arg at inference.jl:898
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_call at inference.jl:910
abstract_eval at inference.jl:959
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_arg at inference.jl:898
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_call at inference.jl:910
abstract_eval at inference.jl:959
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_arg at inference.jl:898
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1524
jlcall_typeinf_26132 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1249
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call_gf at inference.jl:729
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call at inference.jl:842
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_call at inference.jl:934
abstract_eval at inference.jl:959
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_interpret at inference.jl:1122
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1461
jlcall_typeinf_26368 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1249
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call_gf at inference.jl:729
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call at inference.jl:842
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_call at inference.jl:934
abstract_eval at inference.jl:959
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_arg at inference.jl:898
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1524
jlcall_typeinf_26368 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1249
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call_gf at inference.jl:729
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call at inference.jl:842
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_call at inference.jl:887
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_eval_call at inference.jl:934
abstract_eval at inference.jl:959
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
abstract_interpret at inference.jl:1114
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf at inference.jl:1461
jlcall_typeinf_26368 at  (unknown line)
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
typeinf_ext at inference.jl:1243
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:1057
jl_apply at /Users/ericforgy/Code/julia/src/./julia.h:488
jl_trampoline_compile_function at /Users/ericforgy/Code/julia/src/builtins.c:918
jl_compile_all_defs at /Users/ericforgy/Code/julia/src/gf.c:1548
_compile_all at /Users/ericforgy/Code/julia/src/gf.c:1575
_compile_all at /Users/ericforgy/Code/julia/src/gf.c:1579
jl_compile_all at /Users/ericforgy/Code/julia/src/gf.c:1605
julia_save at /Users/ericforgy/Code/julia/src/init.c:1199
main at /Users/ericforgy/Code/julia/base/../julia (unknown line)
Segmentation fault: 11

**Comment by carnaval** [comment]
I would guess this one is on me. I'm having a look.

**Comment by carnaval** [comment]
Ah. Didn't think about the auto-close. Please tell me if it persists as of a3d9203 so I can re-open.

**Comment by EricForgy** [comment]
Thanks guys. That fixed it for me.
