### ISSUE TITLE
Writing to a socket closed remotely causes local REPL to crash

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#9934]
From the REPL start a server:

```
lport = listen(11000)

while true
    aport = accept(lport)
    let aport=aport
        @schedule begin
            try
                println("Got a new connection")
                print(aport, "HTTP/1.1 200 OK\r\n\r\n")
                while true
                    println(aport, "Hello ", time())
                    println("Sent data")
                    sleep(1.0)
                end
            catch e
                println(e)
            end
        end
    end
end
```

In another REPL type `client = connect("localhost", 11000)` and exit. This causes the first REPL to abnormally exit with a broken pipe.

```
julia> lport = listen(11000)
TCPServer(active)

julia> while true
           aport = accept(lport)
           let aport=aport
               @schedule begin
                   try
                       println("Got a new connection")
                       print(aport, "HTTP/1.1 200 OK\r\n\r\n")
                       while true
                           println(aport, "Hello ", time())
                           println("Sent data")
                           sleep(1.0)
                       end
                   catch e
                       println(e)
                   end
               end
           end
       end
Got a new connection
Sent data
Sent data
Sent data

signal (13): Broken pipe
write at /lib/x86_64-linux-gnu/libpthread.so.0 (unknown line)
unknown function (ip: -988407916)
uv_write2 at /home/amitm/Work/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
jl_write_no_copy at /home/amitm/Work/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
write at stream.jl:733
print at ascii.jl:93
jlcall_print_43565 at  (unknown line)
jl_apply_generic at /home/amitm/Work/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
print at string.jl:4
jl_apply_generic at /home/amitm/Work/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
jl_f_apply at /home/amitm/Work/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
println at string.jl:5
jl_apply_generic at /home/amitm/Work/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at task.jl:9
unknown function (ip: -988688351)
unknown function (ip: 0)
```

```

julia> versioninfo()
Julia Version 0.4.0-dev+2930
Commit 27959aa (2015-01-27 04:47 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by vtjnash** [comment]
see also: https://github.com/JuliaLang/julia/pull/9724

dieing on SIGPIPE is a regression from 0.2

**Comment by elextr** [comment]
Its best to ensure SIGPIPE is ignored properly.  

If libuv doesn't handle the SIGPIPE then Julia shouldn't be trying to second guess it.

Unless you want to terminate the server its very hard to do anything useful if you actually catch the signal, unless the sigaction version of the handler is used (which can give you the fd relating to the SIGPIPE I believe).  But its still a question of "now what do I do?" how to tell libuv/the rest of the program the pipe has closed.

Also signals will not play nice with future Julia that uses threads (or any current C libraries that use threads).

**Comment by vtjnash** [comment]
libuv expects that the SIGPIPE signal will be ignored by the host program (in this case julia), so that it can handle it gracefully, and synchronously

**Comment by elextr** [comment]
So its "just" a case of finding out what re-enabled it.

**Comment by amitmurthy** [comment]
Doesn't libuv handle EPIPE on a  `write` call? If so, why can't we just ensure SIGPIPE is ignored after all libraries have been loaded.

**Comment by elextr** [comment]
@amitmurthy I would hope libuv handles EPIPE, but Julia probably can't avoid problems with loaded libraries that re-enable SIGPIPE (other than mumbling at their developers) since the REPL can load them at any time, and any function called can also re-enable it, so a time "after all libraries" doesn't exist.  

No library *should* touch signals deliberately, since they don't know what other libraries or the main program do, but not all abide by that rule (yes it is fun when two libraries both try to use SIGUSR1).  Julia itself should just ensure SIGPIPE is ignored or masked.

**Comment by amitmurthy** [comment]
I think the best we can do is ignore SIGPIPE after all base libraries are loaded and initialized. For example,  just before `process_options` is called in `base/client.jl`. I understand that we cannot handle libraries loaded by external packages, via a `using Foo` for example overriding it. But this would be more a documentation issue and the fault would lie with the library implementation. 

But as things stand, a reliable server/daemon cannot be written in Julia.

**Comment by amitmurthy** [comment]
Looking at the commit history, @Keno did add a SIGPIPE ignore in https://github.com/JuliaLang/julia/commit/6bbd87c05efb3084ee6984b4e40866779a8cacdb

However, that commit was rendered ineffective by @vtjnash's commit https://github.com/JuliaLang/julia/commit/0195310b3572f78ec02a0f4a75378b3cc6009ff7

I tested removing the SIGPIPE print-backtrace-and-die handler added by @vtjnash and things work as expected. libuv handles EPIPE as expected. The correct behavior ought to be to ignore it. 

@vtjnash ?

**Comment by vtjnash** [comment]
it shouldn't be there. in that commit, i was cleaning up the previous commit to include signals with a default action of `terminate process`, but SIGPIPE should be SIG_IGN, even though it defaults to terminating the process
