### ISSUE TITLE
inconsistent documentation of default vs keyword arguments

### ISSUE THREAD

**Issue by skariel** [JuliaLang/julia#9935]
see image below, the same goes for all documentation: why aren't the default values of positional arguments documented in the method signature? Seems this is done only for keyword argumets

![screenshot from 2015-01-27 11 04 46](https://cloud.githubusercontent.com/assets/2347816/5915958/58ffa19c-a614-11e4-8600-4238a7a6d73a.png)

**Comment by nalimilan** [comment]
I guess you're talking about the `localfile` argument to `download()`? Indeed, you can see the default value by calling `@edit download("a")`.

Would you prepare a pull request to fix the documentation? It's in `doc/stdlib/file.rst`. (In the long-term these docs will be generated automatically, so they will always be consistent.)

If you feel like it, you could also replace `download(url)` function with a simple `localfile=tempname()` in the main `download(url, localfile)` function signature.

Thanks!

**Comment by skariel** [comment]
yeah well, it's not just the download function this is just a random example -- it's all over the place. Signatures should be really generated automatically. I'm just pointing this issue. Solving by just manually fixing the text here is wrong and it would require a massive effort

**Comment by skariel** [comment]
I mean, is there a plan to use the new documentation system to automatically generate the official documentation?

**Comment by nalimilan** [comment]
Ah, OK. Indeed the plan seems to be to generate all of this automatically, but it's harder than it seems because some functions have many different signatures and we need to find something more clever than just listing them. See https://github.com/JuliaLang/julia/pull/9838

I'm closing this issue in favor of the other discussion.
