### ISSUE TITLE
keyword arguments of form `x=x` in let-block

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#9948]
Keywords arguments which have the form: `f(;x=x) = ...` don't work as I would expect.

```
julia> x = 3
3

julia> f(;x=x) = x
f (generic function with 1 method)

julia> f()
ERROR: x not defined

julia> g(;x_=x) = x_
g (generic function with 1 method)

julia> g()
3
```

I would expect `f` to work, although the doc says it should not: http://docs.julialang.org/en/latest/manual/functions/?highlight=keyword#evaluation-scope-of-default-values .  

However, it does work in a `let` block but with surprising behavior:
```
julia> h = let
       y = 3
       h(;y=y) = y
       end
h (generic function with 1 method)

julia> h()
3

julia> h(y=5)
5

julia> h()
5
```
So using the keyword actually modifies its default value!  Of course this can be used for neat tricks like so:
```
julia> f = let
           z = 0
           f(; z=z+1) = println(z)
       end
f (generic function with 1 method)

julia> for i=1:10
           f()
       end
1
2
3
4
5
6
7
8
9
10
```
!

The behavior in the let block looks like a bug to me but maybe just a gotcha?

(edit: made all variable distinct as otherwise the REPL needs to be restarted to get the observed behavior)

**Comment by JeffBezanson** [comment]
The surprising behavior in `let` seems to be fixed by #13412.

**Comment by mauro3** [comment]
No, I still get the same behavior on today's master (note that the REPL needed to be restarted in original example; now I updated the example such that this needn't be done).  Essentially, it looks like the variable needs to be global to trigger the error and local to get the strange updating behavior.

**Comment by vtjnash** [comment]
I think the behavior observed here is correct per design?

**Comment by mauro3** [comment]
Pondering this again, yes, it seems correct, if confusing.  Maybe it should be added to the doc that the keyword arguments have hard-local scope (thus the change of behavior when using `let`).

**Comment by mauro3** [comment]
I think this is another +1 on whether to make functions be hard-scoped for local variables too. x-refs: #5331,  #10559, #14959 and https://github.com/JuliaLang/julia/issues/16727#issuecomment-223490684

**Comment by JeffBezanson** [comment]
This is a bug. Arguments should always introduce new variables.
