### ISSUE TITLE
var(A) does not work for Any arrays

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#9949]
`var(Any[1,2,3])` gives `ERROR: 'zero' has no method matching zero(::Type{Any})`.  The problem seems to be the line
```
momenttype{T}(::Type{T}) = typeof((zero(T) + zero(T)) / 2)
```
in `base/statistics.jl`.   Perhaps this should only be for `Number` types, with a fallback `momenttype(T) = T`?

cc: @pjervis from JuliaOpt/NLopt.jl#15

**Comment by andreasnoack** [comment]
Dup of #8319
