### ISSUE TITLE
Do CSE across loop test and body

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#9960]
Julia is thwarting LLVM's CSE when the subexpression occurs in a loop test and loop body.  Here is an example:
```
function foo(a, b,c)
    while (a*b+c)==1
        a /= (a*b+c)
    end
    a
end

code_llvm (foo,(Float64,Float64,Float64))
```
The output is:
```
L:                                                ; preds = %L.preheader, %L
  %a.0 = phi double [ %8, %L ], [ %0, %L.preheader ]
  %6 = fmul double %a.0, %1, !dbg !10
  %7 = fadd double %6, %2, !dbg !10
  %8 = fdiv double %a.0, %7, !dbg !10
  %9 = fmul double %8, %1, !dbg !10
  %10 = fadd double %9, %2, !dbg !10
  %11 = fcmp oeq double %10, 1.000000e+00, !dbg !10
  br i1 %11, label %L, label %L3.loopexit, !dbg !10
```
Note how `a*b+c` is evaluated twice in the loop.  A partial iteration has been peeled from the loop, which obscures the fact that `a*b+c` is being redundantly evaluated.  

From first glance, it appears that the partial peeling has already happened when LLVM sees the IR.  I'm guessing that it's being done early to improve type inference for the loop test (i.e. poor man's context-sensitivity by cloning code).  It's conceivable that a CSE-like pass could recognize this sort of thing.  Or maybe try to unpeel after type inferencing when types match?

See my comments [here](https://groups.google.com/d/msg/julia-users/_g_hWhg524g/n84XxX-D0W4J) for another example.

**Comment by vtjnash** [comment]
in whichever PR Jeff changed lowering to stop duplicating the condition, this was fixed also. now llvm is able to perform the desired CSE in the loop body

```llvm
julia> code_llvm (foo,(Float64,Float64,Float64))
define double @julia_foo_32845(double, double, double) #0 {
top:
  %3 = fmul double %1, %0
  %4 = fadd double %3, %2
  %5 = fcmp une double %4, 1.000000e+00
  br i1 %5, label %L2, label %if.preheader

if.preheader:                                     ; preds = %top
  br label %if

L2.loopexit:                                      ; preds = %if
  br label %L2

L2:                                               ; preds = %L2.loopexit, %top
  ret double %0

if:                                               ; preds = %if.preheader, %if
  %6 = fmul double %0, %1
  %7 = fadd double %6, %2
  %8 = fcmp une double %7, 1.000000e+00
  br i1 %8, label %L2.loopexit, label %if
}
```
