### ISSUE TITLE
range eltype bug: eltype(0:1//3:10) == Int

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#9962]
```jl
julia> eltype(0:1//3:10)
Int64

julia> [0:1//3:10]
ERROR: InexactError()
 in vcat at range.jl:502

julia> collect(0:1//3:10)
ERROR: InexactError()
 in collect at array.jl:242
 in collect at array.jl:254
```

Not sure when this broke, but this is no good, obviously.

**Comment by StefanKarpinski** [comment]
Also broken on the latest 0.3 version.

**Comment by andreasnoack** [comment]
Also broken on 0.3.3 and 0.3.0

2015-01-29 14:15 GMT-05:00 Stefan Karpinski <notifications@github.com>:

**Comment by ivarne** [comment]
```julia
julia> (0:1//3:10)[2]
ERROR: InexactError()
 in getindex at range.jl:260
```

This is caused by the different `step` type that we needed for date ranges to work. It works if I change the type of the endpoints. (eg. `0//1:1//3:10`).

**Comment by andreasnoack** [comment]
It has probably never worked. Just tried https://github.com/JuliaLang/julia/commit/c402ce95b9d3540edbabb228fe585bf98d195d4a which is the merge commit of the new ranges and the problem is present there as well.

**Comment by ivarne** [comment]
Maybe we should do type promotion on both `start`, `step` and `stop` if the type is subtype of `Number`(or maybe `Real`)?

**Comment by StefanKarpinski** [comment]
It did work before the addition of the second type parameter for some range types.

**Comment by tkelman** [comment]
backported in 505677cb2ad46871c5bc0b59f505d670c4a55ebe (along with some other recently added tests which showed up as a conflict, they pass locally so if they don't cause issues on CI may as well have them on release-0.3 too)
