### ISSUE TITLE
Documentation for push! and append! is confusing

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#9963]
The current docs for `push!` and `append!` (on 0.4-dev) suggest that both can be used to add more than one item to the end of a collection, but do not explain the differences clearly.

```jl
help?> push!
search: push! pushdisplay hash cosh flush sum! using quote else Task is cos sin tanh rand! svd acscd Sys show last cosc fill! hist

  push!(collection, items...) → collection

  Insert items at the end of collection.

  push!([1,2,3], 4) == [1,2,3,4]

help?> append!
search: append! prepend! end prod! send open type TopNode Type typeof typemin select! seekend gperm union! nthperm! pwd pinv secd

Base.append!(collection, items) -> collection.

   Add the elements of "items" to the end of a collection.

      julia> append!([1],[2,3])
      3-element Array{Int64,1}:
       1
       2
       3
```

It takes a bit of thought to realize that the correct syntaxes look like

```jl
push!([1, 2, 3], 4, 5, 6) # = [1, 2, 3, 4, 5, 6]
append!([1, 2, 3], [4, 5, 6]) # = [1, 2, 3, 4, 5, 6]
```

The doc strings are not wrong, but really could use elaboration.

**Comment by dpsanders** [comment]
I think your two new examples are very clear and should be added to the documentation of both `push!` and `append!` with cross-references.

(For example, I did not know that you could `push!` more than one item, and have just used it for the first time.)

**Comment by rasmusbrandt** [comment]
This fact has often confused me, and looking into the docs never really clarified the situation. I agree that the two examples should be added to the documentation.

**Comment by kmsquire** [comment]
Cc: @stevengj
