### ISSUE TITLE
implicit convert call in fill! changes copying semantics

### ISSUE THREAD

**Issue by joehuchette** [JuliaLang/julia#9964]
```jl
x = Any[]
y = Array(Vector{Int}, 3)
z = Array(Vector{Any}, 3)
fill!(y, x)
fill!(z, x)
push!(y[2], 3)
push!(z[2], 3)
```
then
```
julia> y
3-element Array{Array{Int64,1},1}:
 Int64[]
 [3]
 Int64[]

julia> z
3-element Array{Array{Any,1},1}:
 Any[3]
 Any[3]
 Any[3]
```
I believe that ``fill!(y, x)`` is calling ``convert(::Type{Vector{Int}}, x)`` implicitly, which makes a copy. This seems semantically sketchy, since the copying behavior depends on type information and whether ``convert`` copies data or not. At the very least the documentation here is misleading:
> Base.fill!(A, x)
> Fill array "A" with the value "x". If "x" is an object
>   reference, all elements will refer to the same object.

cc @mlubin

**Comment by simonster** [comment]
We could call `convert(eltype(A), x)` and then fill the array with its result. In fact, we already do this when the array is an `Array{T<:Union(Integer,FloatingPoint)}`. Then all the elements of the array would refer to the same object, although the object might not be the same object as `x`.

**Comment by joehuchette** [comment]
That seems reasonable.
