### ISSUE TITLE
Deprecate 'endof' for non-string types

### ISSUE THREAD

**Issue by garborg** [JuliaLang/julia#9966]
i.e.
```julia
endof(t::(Any...,)) at tuple.jl:4
endof(x::Number) at number.jl:13
endof(a::AbstractArray{T,N}) at abstractarray.jl:25
endof(c::Char) at char.jl:19
```
It's redundant with `length` (outside of strings), defined much less often, and the few places I see using `endof` more generally than with strings, it seems the code wouldn't work with strings, so no win, and could work with other things that have a `length`.

**Comment by vtjnash** [comment]
`endof` is the lowered form of `x[end]`
