### ISSUE TITLE
Mention requirement of installing git for folks using the generic linux binaries

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#9969]
For folks who download the generic linux binaries, `Pkg` does not work if git is not installed, as is common on many stock distributions. Perhaps we need to put a note along these lines on the downloads page, or add a pre-requisites columnn to our various downloads.

**Comment by kshyatt** [comment]
@wildart @Keno @tkelman is this still something we need to do?

**Comment by tkelman** [comment]
Not needed in 0.5.
