### ISSUE TITLE
Better error needed for misuse of keyword args

### ISSUE THREAD

**Issue by jdlangs** [JuliaLang/julia#9972]
I had a mental lapse and forgot to use the keyword argument name when invoking a function. I ended being baffled for a good five minutes before realizing what happened.

```
julia> f(;x=1) = x+1
f (generic function with 1 method)

julia> f(;x=3)
4

julia> f(;3)
ERROR: BoundsError
 in anonymous at no file
```

This seems like something the parser should be able to pick up instantly.

**Comment by ivarne** [comment]
+1 for making this a parser error.

Note that the `;` is optional for calling a function with keyword arguments.

**Comment by JeffBezanson** [comment]
Note the following is valid:

```
julia> f(;x=1) = x+1
f (generic function with 1 method)

julia> p = :x=>1
:x=>1

julia> f(;p)
2
```

**Comment by phobon** [comment]
That does complicate it. Then maybe a couple runtime asserts can be added to check that whatever is passed is iterable with at least 2 elements, and the first is a symbol?

I realize it's probably a rarely seen case but the current error really does confuse way more than help to debug.

**Comment by Snnappie** [comment]
I just ran into this when generating function calls with named arguments from a macro.

A minimal example:

```julia
julia> f(;x=1) = x+1
f (generic function with 1 method)

julia> macro m(named...)
           esc(:(f(;$(named...))))
       end

julia> @m x=1
ERROR: BoundsError
 in anonymous at no file

julia> @m :x=>1
2

julia> macroexpand(:(@m x=1))
:(f(; x = 1))

```

What makes the `BoundsError` particularly confusing is the apparently correct output from `macroexpand`.

**Comment by Rory-Finnegan** [comment]
+1. I guess a parsing error makes the most sense. Mostly, I'd just like the error to remind me what the signature is vs what it received, cause I'm dumb and have been confused by this a couple times.
