### ISSUE TITLE
build_executable.jl windows support

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#9973]
I am trying to build a standalone executable on windows and I'm running into some problems.
I have added gcc as stated in the script.

First of I ran into a problem with a missing string escape when windows paths is written to a userimg file in `emit_userimgjl`. It causes the userimg to contain an `include("folder\folder\file.jl")` with only single `\`. By inserting include(\"$(escape_string(script_file))\") on line: https://github.com/JuliaLang/julia/blob/26ae20698cf0fc57ae6fc60ba42140884e71f558/contrib/build_executable.jl#L224 the path to the script is correct on windows.

After overcoming this problem I get this error:
```
INFO: Linking sys.dll
INFO: System image successfully built at C:\Users\Hoegh\Julia-0.4.0-dev_19_1\bin\libeps_to_pdf.dll
WARNING: Building sys.dll on Windows against LLVM < 3.5.0 can cause incorrect backtraces! Delete generated sys.dll to avoid these
problems
INFO: To run Julia with this image loaded, run: julia -J C:\Users\Hoegh\Julia-0.4.0-dev_19_1\bin\libeps_to_pdf.ji

running: gcc -g -Wl,--no-as-needed -IC:\Users\Hoegh\Julia-0.4.0-dev_19_1\include\julia -IC:\Users\Hoegh\src -IC:\Users\Hoegh\src/
upport -IC:\Users\Hoegh\usr/include C:\Users\Hoegh\AppData\Local\Temp\jul9D3B.tmp\start_func.c -o C:\Users\Hoegh\Julia-0.4.0-dev_
9_1\bin\eps_to_pdf.exe -Wl,-rpath,C:\Users\Hoegh\Julia-0.4.0-dev_19_1\bin -LC:\Users\Hoegh\Julia-0.4.0-dev_19_1\bin -ljulia -leps
to_pdf
ERROR: LoadError: could not spawn `gcc -g -Wl,--no-as-needed '-IC:\Users\Hoegh\Julia-0.4.0-dev_19_1\include\julia' '-IC:\Users\Ho
gh\src' '-IC:\Users\Hoegh\src/support' '-IC:\Users\Hoegh\usr/include' 'C:\Users\Hoegh\AppData\Local\Temp\jul9D3B.tmp\start_func.c
 -o 'C:\Users\Hoegh\Julia-0.4.0-dev_19_1\bin\eps_to_pdf.exe' '-Wl,-rpath,C:\Users\Hoegh\Julia-0.4.0-dev_19_1\bin' '-LC:\Users\Hoe
h\Julia-0.4.0-dev_19_1\bin' -ljulia -leps_to_pdf`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:216 (repeats 2 times)
while loading C:\Users\Hoegh\Julia-0.4.0-dev_19_1\share\julia\build_executable.jl, in expression starting on line 247
```
When I run the command manually i get:
```
C:\Users\Hoegh\Julia-0.4.0-dev_19_1>gcc -g -Wl,--no-as-needed -IC:\Users\Hoegh\Julia-0.4.0-dev_19_
1\include\julia -IC:\Users\Hoegh\src -IC:\Users\Hoegh\src/support -IC:\Users\Hoegh\usr/include C:\
Users\Hoegh\AppData\Local\Temp\jul9D3B.tmp\start_func.c -o C:\Users\Hoegh\Julia-0.4.0-dev_19_1\bin
\eps_to_pdf.exe -Wl,-rpath,C:\Users\Hoegh\Julia-0.4.0-dev_19_1\bin -LC:\Users\Hoegh\Julia-0.4.0-de
v_19_1\bin -ljulia -leps_to_pdf
In file included from C:\Users\Hoegh\Julia-0.4.0-dev_19_1\include\julia/uv.h:59:0,
                 from C:\Users\Hoegh\Julia-0.4.0-dev_19_1\include\julia/ios.h:5,
                 from C:\Users\Hoegh\Julia-0.4.0-dev_19_1\include\julia/libsupport.h:12,
                 from C:\Users\Hoegh\Julia-0.4.0-dev_19_1\include\julia/julia.h:10,
                 from C:\Users\Hoegh\AppData\Local\Temp\jul9D3B.tmp\start_func.c:1:
C:\Users\Hoegh\Julia-0.4.0-dev_19_1\include\julia/uv-win.h:241:3: error: unknown type name 'SRWLOCK'
```
The file I try to compile looks like:
```
function main()
    println("test")
end
```
@few do you have any idea what's wrong?

**Comment by few** [comment]
The SRWLOCK error sounds like this: https://github.com/joyent/libuv/issues/263
So try adding -D_WIN32_WINNT=0x0600 to the gcc command line.

**Comment by dhoegh** [comment]
@few, Awesome it worked, I will give it a more thorough test tomorrow. The things I have found that needs to be changed to get windows support is:
* `-D_WIN32_WINNT=0x0600` commandline argument to gcc
* inserting include(\"$(escape_string(script_file))\") on line: https://github.com/JuliaLang/julia/blob/26ae20698cf0fc57ae6fc60ba42140884e71f558/contrib/build_executable.jl#L224
*  The reference to gcc should be as in https://github.com/JuliaLang/julia/blob/b1dbc8c1a1f063abc114944d1083986a55cac827/contrib/build_sysimg.jl#L91-L93 to get the one installed by `WinRPM`. I have used one that came prepackaged with Anaconda. Maybe you could use the whole `find_system_linker` from `build_sysimg.jl` to get the correct gcc on both windows and unix.

**Comment by vtjnash** [comment]
(presumably that should be `-D_WINVER=0x0502` == Win XP SP2)
