### ISSUE TITLE
Something fishy with math. consts?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#9975]
See e.g.

* https://github.com/Aerlinger/Tau.jl/issues/7: `ERROR: LoadError: test failed: (a = 6.2831853071795... == 6.283185307179586)`
* https://github.com/jlapeyre/LambertW.jl/issues/1: `ERROR: LoadError: LoadError: test failed: (0.5671432904097838 == a = 0.5671432904097...)`
* https://github.com/jlapeyre/ZChop.jl/issues/2: `ERROR: LoadError: test failed: (3.141592653589793 == a = 3.1415926535897...)`

**Comment by IainNZ** [comment]
```
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2997 (2015-01-30 05:35 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit e41a507 (0 days old master)
|__/                   |  x86_64-unknown-linux-gnu
```

**Comment by IainNZ** [comment]
I think this is https://github.com/JuliaLang/julia/pull/9198 related?

**Comment by IainNZ** [comment]
@simonbyrne can you do a quick check to see if these errors in these package tests are because they were relying on some behaviour they shouldnt?

**Comment by simonbyrne** [comment]
Yes: now all numbers should only compare equal if they are actually numerically equal, so `pi != float(pi)`.

**Comment by IainNZ** [comment]
Excellent
