### ISSUE TITLE
Adding make target to build source tarball with documentation

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#9977]
I'd like to add a new make target which would allow creating a tarball containing only the Julia source (and not all dependencies as `source-dist` currently), but also build the HTML/PDF documentation. This would remove the need to have Sphinx on the build machine, which creates terrible dependency chains (recent Python, etc.) on RHEL5 and 6.

So I think it would make sense to have a new target which would be equivalent to `source-dist`, except that it would not include dependencies, and that it would build the docs. Then `install` should also be adapted to install the docs if the folders are present. What do you think about this?

By the way, our target names are currently not very standard. `dist` usually means "source distribution", not a binary one. And `release-candidate` looks like what the autotools call `distcheck` (i.e. run tests before making a release tarball), except that we could improve it by making a tarball, unpacking it and building from it, which is the best check that the release is OK (see e.g. [this](http://octave.1599824.n4.nabble.com/Re-What-is-make-distcheck-td4658782.html)). Thus I suggest we rename `dist` to `binary-dist`, `source-dist` to `dist-full` or `dist-deps`, `release-candidate` to `distcheck`, and call the new target `dist`.

CC: @staticfloat @tkelman

**Comment by tkelman** [comment]
Yeah, I agree with all of this. Making distribution packagers' lives easier and being more compliant with standard naming practices are both good things.

**Comment by tkelman** [comment]
One potential annoyance is making the distinction between the existing source-dist (all dependencies included) and the new dist (just the submodules and docs?) clear when we post tarballs. I'm not sure off the top of my head whether github releases lets you post multiple different release tarballs. Maybe we should put the new dist tarballs only on S3 and document the links to them under DISTRIBUTING.md but otherwise not publicize them too much, since only distribution packagers will really want to use them.

**Comment by staticfloat** [comment]
We can put multiple tarballs on GitHub, and/or we can also start stashing them on S3.

I give overall blanket approval of conforming to standard packaging names, hopefully we'll never run into a situation where two names swap places; hopefully it will only be cases where the old name no longer works.

**Comment by tkelman** [comment]
Though to not break the buildbots too much we'll probably want to add a `binary-dist` target on release-0.3 that just calls `dist`, then we can migrate the buildbots to consistently use the new target instead of `dist` which will have different meanings between 0.3 and 0.4.

**Comment by nalimilan** [comment]
Yeah, sounds like a good strategy to start with.

**Comment by nalimilan** [comment]
Closing in favor of https://github.com/JuliaLang/julia/pull/10253 (merged) and https://github.com/JuliaLang/julia/pull/11411
