### ISSUE TITLE
Missing ``copy`` for graphs

### ISSUE THREAD

**Issue by poulson** [JuliaLang/julia#9982]
Lack of existence of ``copy`` for ``Graph``.

EDIT: Due to the destructive nature of a routine in JuliaSparse/Metis.jl that is not supposed to be destructive, I had falsely assumed that ``copy`` would produce a shallow copy of a sparse matrix.

**Comment by ivarne** [comment]
The only type named `Graph` in `Base` julia is `Pkg.Resolve.MaxSum.Graph`. Is that the one you are referring to, or does this issue really belong in [JuliaLang/Graphs.jl](https://github.com/JuliaLang/Graphs.jl)?

**Comment by poulson** [comment]
@ivarne You're correct; my mistake. The original issue included an item from ``base/`` (``SparseMatrixCSC``), but I retracted that issue. I'll close and resubmit for Graphs.jl.
