### ISSUE TITLE
Performance issue due to problem with type inference and im

### ISSUE THREAD

**Issue by ikirill** [JuliaLang/julia#9989]
This is from [this thread](https://groups.google.com/forum/#!topic/julia-users/03LrySk1ULU) on julia-users.

I have a structure

    type FourierPoly
      periods :: Vector{Int}
      radiuses :: Vector{Float64}
      phase_offsets :: Vector{Float64}
    end

and two functions below. polyder is called at most as often as polyval, yet its memory consumption (from --track-allocation=user) is an order of magnitude higher:

            - function polyval(f::FourierPoly, t::Float64)
     33694968   s = zero(Complex128)
            0   @inbounds for k = 1:length(f.periods)
            0     s += exp(2.pi*(t + f.phase_offsets[k]) * f.periods[k] * im) * f.radiuses[k]
            -   end
            0   return s::Complex128
            0 end
            0 
            0 function polyder(f::FourierPoly, t::Float64)
            0   s = zero(Complex128)
    492303248   @inbounds for k = 1:length(f.periods)
            0     θ = 2.pi * f.periods[k]
    164100720     s += θ * im * exp((t + f.phase_offsets[k]) * θ * im) * f.radiuses[k]
       257652   end
            0   return s::Complex128
            - end

@timholy pointed out (thanks!) that replacing im with `myim = convert(Complex128, im)` addresses the problem, which indicates a possible type inference bug. With that change, in a different run, I got:

            - function polyval(f::FourierPoly, t::Float64)
     53796432   s = zero(Complex128)
            0   @inbounds for k in 1:length(f.periods)
            0     s += exp(2.pi*(t + f.phase_offsets[k]) * f.periods[k] * im) * f.radiuses[k]
            0   end
            0   return s::Complex128
            0 end
            0 
            0 function polyder(f::FourierPoly, t::Float64)
            0   myim = convert(Complex128, im)
            0   s = zero(Complex128)
      3105208   @inbounds for k in 1:length(f.periods)
            0     θ = 2.pi * f.periods[k]
            0     s += θ * myim * exp((t + f.phase_offsets[k]) * θ * myim) * f.radiuses[k]
            -   end
            0   return s::Complex128
            - end

Using `@code_warntype`, the issue seems to be that `im` is thought to be of type `Any` (`_var3` below)

    julia> @code_warntype polyder(FourierPoly(), 0.1)
    Variables:
      f::FourierPoly
      t::Float64
      s::Complex{Float64}
      #s1704::UnitRange{Int64}
      #s1703::Int64
      #s1702::(Int64,Int64)
      k::Int64
      θ::Float64
      _var0::Array{Int64,1}
      _var1::Int64
      _var2::Float64
      _var3::Complex{Bool}
      _var4::Float64
      _var5::Float64
      _var6::Complex{Float64}
      _var7::Complex{Float64}
      _var8::Int64
      _var9::Int64

    Body:
      begin  # /Users/kirill/Sandboxes/ComputationalMathematics/FourierPolynomialPlots/FourierPolynomialPlots.jl, line 56:
          s = $(Expr(:new, Complex{Float64}, :((top(box))(Float64,(top(sitofp))(Float64,0))), :((top(box))(Float64,(top(sitofp))(Float64,0))))) # line 57:
          $(Expr(:boundscheck, false))
          _var0 = (top(getfield))(f::FourierPoly,:periods)::Array{Int64,1}
          _var1 = (top(arraylen))(_var0::Array{Int64,1})::Int64
          #s1704 = $(Expr(:new, UnitRange{Int64}, 1, :(((top(getfield))(Intrinsics,:select_value))((top(sle_int))(1,_var1::Int64)::Bool,_var1::Int64,(top(box))(Int64,(top(sub_int))(1,1)))::Int64)))
          #s1703 = (top(getfield))(#s1704::UnitRange{Int64},:start)::Int64
          unless (top(box))(Bool,(top(not_int))(#s1703::Int64 === (top(box))(Int64,(top(add_int))((top(getfield))(#s1704::UnitRange{Int64},:stop)::Int64,1))::Bool)) goto 1
          2:
          _var8 = #s1703::Int64
          _var9 = (top(box))(Int64,(top(add_int))(#s1703::Int64,1))
          k = _var8::Int64
          #s1703 = _var9::Int64 # line 59:
          θ = (top(box))(Float64,(top(mul_float))((top(box))(Float64,(top(mul_float))(2.0,3.141592653589793)),(top(box))(Float64,(top(sitofp))(Float64,(top(arrayref))((top(getfield))(f::FourierPoly,:periods)::Array{Int64,1},k::Int64)::Int64)))) # line 60:
          _var5 = (top(box))(Float64,(top(add_float))(t::Float64,(top(arrayref))((top(getfield))(f::FourierPoly,:phase_offsets)::Array{Float64,1},k::Int64)::Float64))
          _var4 = θ::Float64
          _var3 = im::Any
          _var2 = (top(box))(Float64,(top(mul_float))(_var5::Float64,_var4::Float64))
          _var7 = s::Complex{Float64}
          _var6 = θ::Float64 * im * exp($(Expr(:new, Complex{Float64}, :(((top(getfield))(Intrinsics,:select_value))((top(getfield))(_var3::Complex{Bool},:re)::Bool,_var2::Float64,((top(getfield))(Intrinsics,:select_value))((top(slt_int))((top(box))(Int64,_var2::Float64),0)::Bool,(top(box))(Float64,(top(neg_float))((top(box))(Float64,(top(sitofp))(Float64,0)))),(top(box))(Float64,(top(sitofp))(Float64,0)))::Float64)::Float64), :(((top(getfield))(Intrinsics,:select_value))((top(getfield))(_var3::Complex{Bool},:im)::Bool,_var2::Float64,((top(getfield))(Intrinsics,:select_value))((top(slt_int))((top(box))(Int64,_var2::Float64),0)::Bool,(top(box))(Float64,(top(neg_float))((top(box))(Float64,(top(sitofp))(Float64,0)))),(top(box))(Float64,(top(sitofp))(Float64,0)))::Float64)::Float64))))::Complex{Float64} * (top(arrayref))((top(getfield))(f::FourierPoly,:radiuses)::Array{Float64,1},k::Int64)::Float64::Complex{Float64}
          s = $(Expr(:new, Complex{Float64}, :((top(box))(Float64,(top(add_float))((top(getfield))(_var7::Complex{Float64},:re)::Float64,(top(getfield))(_var6::Complex{Float64},:re)::Float64))), :((top(box))(Float64,(top(add_float))((top(getfield))(_var7::Complex{Float64},:im)::Float64,(top(getfield))(_var6::Complex{Float64},:im)::Float64)))))
          3:
          unless (top(box))(Bool,(top(not_int))((top(box))(Bool,(top(not_int))(#s1703::Int64 === (top(box))(Int64,(top(add_int))((top(getfield))(#s1704::UnitRange{Int64},:stop)::Int64,1))::Bool)))) goto 2
          1:
          0:
          $(Expr(:boundscheck, :((top(getfield))(Base,:pop)))) # line 62:
          return s::Complex{Float64}
      end::Complex{Float64}

**Comment by JeffBezanson** [comment]
I think this is actually the same issue as #5011, and is due to the number of arguments to `*`. We are doing something very bad to the 5-argument call to the varargs `*`. It can be worked around by adding some intermediate parentheses, like this:

```
function polyder(f::FourierPoly, t::Float64)
    s = zero(Complex128)
    @inbounds for k = 1:length(f.periods)
        θ = 2.pi * f.periods[k]
        s += (θ * im) * exp((t + f.phase_offsets[k]) * (θ * im)) * f.radiuses[k]
    end
    return s::Complex128
end
```

The printing of `im::Any` seems to be a bug. We see `_var3 = im::Any`, but notice the type of `_var3` is `Complex{Bool}`, so we actually do know the type of `im`.

**Comment by timholy** [comment]
It is curious, though, that replacing `im` with `myim` fixes the performance problem even without adding parentheses.

**Comment by simonster** [comment]
That may just be because `myim` avoids a `convert` call and that makes `*` small enough to be inlined.

**Comment by JeffBezanson** [comment]
That is probably right.

**Comment by JeffBezanson** [comment]
closing as dup of #5011
