### ISSUE TITLE
tril(M, k) not documented

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#9990]
The two-argument forms of `tril`, `tril!`, `triu`, and `triu!` exist for some matrix types but are not documented. Furthermore, coverage over the special matrix types is spotty.

**Comment by jakebolewski** [comment]
`tril` and `triu` also do not do any bounds checking for out of range diagonals.

**Comment by kshyatt** [comment]
In particular, these special matrix types don't work with `triu` and `tril` (basically all the ones in `Base.LinAlg`):
- [ ] `Bidiagonal`
- [ ] `Tridiagonal`
- [ ] `SymTridiagonal`
- [ ] `Hermitian`
- [ ] `UpperTriangular`
- [ ] `LowerTriangular`
- [ ] `Diagonal`

**Comment by ViralBShah** [comment]
A lot of stuff doesn't work on special matrix types. I tend to use them sparingly, and only in linear algebra calls, and not much otherwise.

**Comment by jiahao** [comment]
See #8001

**Comment by kshyatt** [comment]
Finished by #12574.

**Comment by tkelman** [comment]
Still missing docs.
