### ISSUE TITLE
round(x, ::RoundingMode) is not documented

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#9995]
The new `RoundingMode`s are not documented.

Also, the documentation for `round` is no longer accurate for 0.4...?

```
   "round(x)" returns the nearest integral value of the same type as
   "x" to "x", breaking ties by rounding away from zero.
```

On 0.4-dev:

```jl
julia> round(0.5)
0.0
```

On release-0.3:

```jl
julia> round(0.5)
1.0
```

**Comment by jiahao** [comment]
There are also the new types `RoundUp`, `RoundDown` etc. which are also not documented.

cc @simonbyrne can has?

**Comment by simonbyrne** [comment]
I did [update the docs](https://github.com/JuliaLang/julia/pull/9344/files#diff-1b93b2bd585f1eb42df445590f059fdcL3202) with the change, however the changes seem to have been lost with docs reorganisation (#9428: I guess the dates overlapped). I'll make another PR.

**Comment by jiahao** [comment]
Ok, good to know. cc: @nalimilan, let's try to avoid losing changes.

**Comment by nalimilan** [comment]
Sorry, I tried manually re-applying all the commits, but I must have missed this one. I should have merged the PR much faster to avoid conflicts...

**Comment by jiahao** [comment]
Also @simonbyrne could you have a look at #8291? Thanks.
