### ISSUE TITLE
Pkg.Entry.check_metadata() leaks memory on 0.4

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#9998]
This is probably a bug with the new gc, cc @carnaval 

Run `Pkg.Entry.check_metadata()` from `~/.julia/v0.4` and watch the memory consumption in top. With Julia 0.3, it never takes more than about 5-6% of memory (Linux 64 - old machine, I think it has 3 GB total). On 0.4, it takes over 90%. This is causing metadata's tests to get killed on Travis.

**Comment by tkelman** [comment]
```
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3028 (2015-02-01 00:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 2d43235* (0 days old master)
|__/                   |  x86_64-linux-gnu
 
julia> @time Pkg.Entry.check_metadata()
elapsed time: 256.958162245 seconds (130116 MB allocated, 41.93% gc time in 5948 pauses with 0 full sweep)


  | | |_| | | | (_| |  |  Version 0.3.6-pre+45 (2015-01-28 22:44 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 1fbf6e1* (3 days old release-0.3)
|__/                   |  x86_64-linux-gnu

julia> @time Pkg.Entry.check_metadata()
elapsed time: 385.057665299 seconds (147437330084 bytes allocated, 49.43% gc time)
```

Oddly the numbers are comparable, though from watching top you wouldn't think so. Leaking somewhere on 0.4?

**Comment by tkelman** [comment]
Unsurprisingly, bisect confirms 7c8acce9fb73c3edb caused this.

**Comment by carnaval** [comment]
I'm looking into this. It comes from the way we try to "predict" how much memory will be freed after gc sweep. It seems to be diverging from the truth, making the gc think it is freeing enough memory to never run an old generation collection.

**Comment by tkelman** [comment]
Thanks @carnaval! Confirmed fixed, no more memory leak that I can see.
```
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3073 (2015-02-02 22:28 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 2f97c78* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> @time Pkg.Entry.check_metadata()
elapsed time: 242.225599057 seconds (130478 MB allocated, 38.57% gc time in 5965 pauses with 71 full sweep)
```

Though it would still be nice if anyone who understands what this function does took a crack at optimizing it a little, I think this is the dominant factor in `Pkg.publish` taking so long.
